Add API endpoint for deleting filtered hosts
RedHatInsights/insights-host-inventory pull request #1011
Opened 2021-10-06 23:13 UTC by thearifismail

# Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/ESSNTL-1203).
(A description of your PR's changes, along with why/context to the PR, goes here.)

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-11-03 15:33 UTC, kruai commented on api/host.py
> +        # QUESTION: Is ValueError the correct exception?  Should it be just "Exception"?
I think ValueError makes sense. I see where it's raised, and we want to handle that scenario. If a different exception is raised, we may end up wanting to handle it differently

2021-11-03 18:11 UTC, kruai requested changes

2021-11-03 18:11 UTC, kruai commented on tests/test_api_hosts_delete.py
> +    host_ids_xjoin_post(response, status=200)
This is making it so it gets the same list of 2 hosts every time, no matter what the query parameters are. Doesn't that invalidate the purpose of this test?

2021-11-03 19:18 UTC, thearifismail commented on api/host.py
> +    ids_list = ()
Gone!

2021-11-03 19:29 UTC, thearifismail commented on api/host.py
> +    return provided_args
Oops `return False` was left over and should've been removed.

2021-11-03 19:34 UTC, thearifismail commented on api/host.py
> +        flask.abort(400, str(e))
> If this failstate is caused by an xjoin outage, we should most likely return HTTP 503, not 400.

Adding `except ConnectionError as ce` with `abort(503, ce)`

2021-11-03 19:52 UTC, thearifismail commented on api/host.py
> +    return provided_args
I think using a function is cleaner; with one return statement 👍

2021-11-03 19:53 UTC, thearifismail commented on api/host.py
> +    return provided_args
> What's the purpose of this function? I only see it used in one place, and it looks like it just creates a list. I vote for removing this function and just creating the list where you need it

IMO using a function in the exception block is cleaner; be that used once.

2021-11-03 21:09 UTC, thearifismail commented on api/host.py
> +            if delete_by_id([obj["id"]]):
> My comment from my previous review doesn't appear to have carried over, so I'm going to copy&paste it:
> 
> > delete_by_id is an API endpoint that returns a Flask response; I don't think those evaluate to boolean values the way you expect, and an API endpoint calling a separate API endpoint doesn't seem like the way to go. If you want to reuse some of its logic, can you refactor out what you need and use delete_hosts() for the rest?

Moving the host deletion code to a new method `_delete_filtered_hosts(host_id_list)`, which is caller by both `delete_by_id(host_id_list)` and `delete_host_list(...)`

2021-11-03 21:16 UTC, thearifismail commented on api/host.py
> +        logger.info(f'Host to delete: {obj["id"]}')
> If each item in `ids_list` is not an ID, then `get_host_ids_list_xjoin` is still not returning data in the correct format. I'm making a mental note to check out the code when I get there.

This and the one in, https://github.com/RedHatInsights/insights-host-inventory/pull/1011#discussion_r742093002 , are gone after refactoring host deletion.

2021-11-04 12:25 UTC, thearifismail commented on app/instrumentation.py
> +def log_delete_filtered_hosts_failed(logger, host_id, control_rule):
with refactoring this method is not used anymore and has been deleted.

2021-11-04 12:27 UTC, thearifismail commented on app/instrumentation.py
> +    logger.debug("Host search engine down or host ids not found", extra={"access_rule": get_control_rule()})
yes. `response = graphql_query(HOST_IDS_QUERY, variables, log_get_host_id_list_failed)["hosts"]`

2021-11-04 13:17 UTC, thearifismail commented on swagger/api.spec.yaml
> +          description: Invalid request.
Resolving for being outdated.

2021-11-04 13:18 UTC, thearifismail commented on swagger/api.spec.yaml
> +      example: 22cd8e39-13bb-4d02-8316-84b850dc5136
Gone, not used anymore

2021-11-04 13:20 UTC, thearifismail commented on swagger/api.spec.yaml
> +      - 22cd8e39-13bb-4d02-8316-84b850dc5136
Removed!!!

2021-11-04 14:45 UTC, thearifismail commented on tests/fixtures/api_fixtures.py
> +    def _api_delete_filtered_hosts(url, identity=USER_IDENTITY, query_parameters=None, extra_headers=None):
It IS the same HOST_URL used by a call to `build_hosts_url()` in the test, "test_delete_hosts_using_filter".  It is the same mechanism used for getting hosts like `test/test_api_hosts_get.py::test_query_using_display_name`

2021-11-04 14:50 UTC, thearifismail commented on tests/fixtures/graphql_fixtures.py
> +    return graphql_query(return_value=XJOIN_HOST_IDS_RESPONSE)
removed!!!

2021-11-04 18:21 UTC, thearifismail commented on api/host.py
> +):
Added Staleness as a param to filter on to the delete_host_list

2021-11-05 15:48 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +        "tags=ns1/key2=val1&display_name=hbi_display.redhat.com",
Done by adding `staleness`, `provider_type`, `provider_id`,

2021-11-08 17:19 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    assert remaining_hosts.count() == 0
With the given test framework, it is hard to get more granularity.  However, when hosts are deleted successfully, then the following message is provided:
`Hosts found for deletion: 2`
`Deleted hosts: 2`

2021-11-12 21:25 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    assert_response_status(response_status, expected_status=200)
The flask.response returned by `delete_host_list()` is blank but the test does verify that delete event was created.  To see only the correct hosts are deleted, the tests creates two sets of hosts and delete only one.  The presence of remaining hosts is verified after the deletions.

2021-11-18 19:13 UTC, ryandillinfelton commented on api/host.py
> +    # import pdb; pdb.set_trace()
Loose comment

2021-11-18 19:13 UTC, ryandillinfelton commented on app/instrumentation.py
> +
Remove unused code

2021-11-18 21:44 UTC, ryandillinfelton requested changes
Didn't get to review all the tests yet but I need to put this away for the day. I noted a few assorted changes. Also please remove the /util file changes.

2021-11-18 21:44 UTC, ryandillinfelton commented on tests/fixtures/api_fixtures.py
> +    def _api_delete_filtered_hosts(url, identity=USER_IDENTITY, query_parameters=None, extra_headers=None):
The example you cite generates a host url then uses it with the `api_get` fixture. I think this pattern makes sense here since `api_get` can be used on any endpoint.

Right now this `api_delete_filtered_hosts` operates more like an `api_delete` fixture. 

Why not generate the URL in the fixture? Have the caller pass the query parameters in and remove the URL parameter. Similar how `api_delete_host` works.
```
@pytest.fixture(scope="function")
def api_delete_host(flask_client):
    def _api_delete_host(host_id, identity=USER_IDENTITY, query_parameters=None, extra_headers=None):
        url = f"{HOST_URL}/{host_id}"
        return do_request(
            flask_client.delete, url, identity, query_parameters=query_parameters, extra_headers=extra_headers
        )

    return _api_delete_host
```

2021-11-18 21:44 UTC, ryandillinfelton commented on tests/fixtures/graphql_fixtures.py
> +@pytest.fixture(scope="function")
It doesn't look like you use this fixture

2021-11-18 21:44 UTC, ryandillinfelton commented on utils/kafka_producer.py
> +NUM_HOSTS = int(os.environ.get("NUM_HOSTS", 8))
This looks like a change left over from manual testing. Can you remove it?

2021-11-18 21:44 UTC, ryandillinfelton commented on utils/payloads.py
> +        "is_marketplace": True,
The changes to this file look like they're left over from manual testing. Can you remove them?

2021-11-18 21:44 UTC, ryandillinfelton commented on api/filtering/filtering.py
> +    tags,
Why is this moved?

2021-11-19 15:07 UTC, thearifismail commented on api/filtering/filtering.py
> +    tags,
To maintain the alphabetic ordering of the args

2021-11-19 15:12 UTC, thearifismail commented on swagger/api.spec.yaml
> +        '200':
Agree.  Set the success response to "202" with "Request for deletion of filtered hosts have been accepted".

2021-11-19 15:15 UTC, thearifismail commented on tests/fixtures/api_fixtures.py
> +    return _api_get_filtered_hosts
Gone!

2021-11-19 15:34 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    host_ids_xjoin_post(response, status=200)
Intent of this test is to call `api_delete_filtered_hosts(url)`, which queries `xjoin-search` and `host_ids_xjoin_posts` makes hosts available to `get_host_ids_list_xjoin()` which in turn is called by `api_delete_filtered_hosts(url)`.  Which hosts are deleted is not the focus.  

To ensure corrects hosts are returned, `tests_xjoin.py` has:

1. test_xjoin_search_query_using_hostfilter
2. test_xjoin_search_query_using_hostfilter_display_name
3. test_xjoin_search_query_using_hostfilter_provider
4. test_xjoin_search_query_using_hostfilter_staleness_with_search

2021-11-19 17:28 UTC, thearifismail commented on tests/fixtures/api_fixtures.py
> +    def _api_delete_filtered_hosts(url, identity=USER_IDENTITY, query_parameters=None, extra_headers=None):
okay... removed the URL as input param to the fixture and passed in filter as query_parameters.

2021-11-19 17:31 UTC, thearifismail commented on utils/kafka_producer.py
> +NUM_HOSTS = int(os.environ.get("NUM_HOSTS", 8))
reverted!

2021-11-19 17:33 UTC, thearifismail reviewed
@kruai @ryandillinfelton responded to comments and removed URL as an input param to the `api_delete_filtered_hosts` fixture.

2021-11-19 17:33 UTC, thearifismail commented on utils/payloads.py
> +        "is_marketplace": True,
reverted

2021-11-19 17:38 UTC, ryandillinfelton commented on api/filtering/filtering.py
> +    tags,
But the rest aren't in alphabetical order. `filter` and `registered_with` come after `tags`, and `fqdn` is before `display_name`.

2021-11-19 17:40 UTC, ryandillinfelton commented
There are still a lot of loose comments and sections of commented out code in this PR. I tagged a few in my last review.

2021-11-19 19:41 UTC, ryandillinfelton requested changes
Reviewed the tests

2021-11-19 19:41 UTC, ryandillinfelton commented on tests/test_api_hosts_delete.py
> +    response = {"data": resp}
Looking at the test a little more, I think you can avoid having to do this step entirely so feel free to resolve this. I'll leave the comment though just do demonstrate `enumerate()` and `copy.deepcopy()` since they're pretty helpful but don't come up all that often.

2021-11-19 19:41 UTC, ryandillinfelton commented on tests/test_api_hosts_delete.py
> +    host_ids = [str(host.id) for host in created_hosts]
You could cast `XJOIN_HOSTS_RESPONSE_FOR_FILTERING["hosts"]["data"]` to a list of hosts and call `db_create_multiple_hosts()` using the `hosts` keyword argument to avoid the extra data and id switching.
```suggestion
    hosts_to_create = [Host(**host_init_data) for host_init_data in XJOIN_HOSTS_RESPONSE_FOR_FILTERING["hosts"]["data"]]
    created_hosts = db_create_multiple_hosts(hosts=hosts_to_create)
```

2021-11-19 19:41 UTC, ryandillinfelton commented on tests/test_api_hosts_delete.py
> +    new_ids = [str(host.id) for host in new_hosts]
If the values of the second set of hosts don't matter much (aside from having different IDs) you could just call `db_create_multiple_host()` to create 10 minimal hosts. Since things like the `canonical_facts` of the hosts won't effect if they get deleted or not it shouldn't make a difference.

2021-11-19 19:44 UTC, ryandillinfelton commented on swagger/api.spec.yaml
> +          description: Request for deletion of filtered hosts have been accepted.
Just a small typo
```suggestion
          description: Request for deletion of filtered hosts has been accepted.
```

2021-11-19 19:56 UTC, ryandillinfelton commented on api/host_query_xjoin.py
> +        all_filters += owner_id_filter()
Account is in the identity header that we forward to xjoin-search. Xjoin search handles the filtering on account on its own. There is no way to filter on account through the xjoin-search graphQL API because you can't perform a request without a valid identity header, same deal as HBI.

2021-11-19 20:13 UTC, thearifismail commented
@ryandillinfelton, About `There are still a lot of loose comments and sections of commented out code in this PR. I tagged a few in my last review.`

Based on the diffs, there no more `TODOs` left.  However there are 9 pre-existing ones.  I don't know much about them except "TODO: 'identity.auth_type is not 'classic-proxy' is a temporary fix." which should be removed after verifying that the `classic-proxy` has been fixed for good.

As far as the commented out code in `kafka_producer.py` and `payloads.py` is concernted, it should be left in place as reflects the nature of changed made for testing.

2021-11-19 20:24 UTC, thearifismail commented on tests/fixtures/graphql_fixtures.py
> +@pytest.fixture(scope="function")
Yes made a separate fixture for clarity in the tests using it.  `patch_xjoin_post` eluded that existing hosts were being used.  That's why created a separate fixture.

2021-11-19 20:48 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    response = {"data": resp}
Thanks for reminding deepcopy(). Now using deepcopy but before updating response with the IDs of the newly created hosts in the DB.  About enumeration's use, IMO clarity and easy to read code is better than compact one liner.

2021-11-19 20:58 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    new_ids = [str(host.id) for host in new_hosts]
Good idea.  `newData` gone and using `new_hosts = db_create_multiple_hosts()`

2021-11-19 20:59 UTC, thearifismail commented on swagger/api.spec.yaml
> +          description: Request for deletion of filtered hosts have been accepted.
I was taught that `have` was used for I and plural.

2021-11-19 21:28 UTC, ryandillinfelton commented on api/host.py
> +        f"Hosts found for deletion: {len(ids_list)} \nDeleted hosts: {delete_count}", status.HTTP_200_OK
Status should be 202 accepted here

2021-11-20 00:13 UTC, thearifismail commented on tests/test_xjoin.py
> +    mocker, query_source_xjoin, graphql_query_empty_response, api_delete_filtered_hosts
that does not help because host.id are generated by db and the mocked response does not have the id new ids.

2021-11-20 00:16 UTC, thearifismail commented
All @ryandillinfelton  concerns addressed, except partial deletions when some of the hosts are present in xjoin but not in db. Question is should the PR be held for it?

2021-11-30 14:28 UTC, thearifismail commented
@kruai when you get a chance, please take a last look.  All known issues and comments have been addressed.

2021-12-06 16:43 UTC, kruai requested changes

2021-12-06 16:43 UTC, kruai commented on tests/test_api_hosts_delete.py
> +    response_status, response_data = api_delete_filtered_hosts({"insights_id": "6e7b6317-0a2d-4552-a2f2-b7da0aece49d"})
Neither of the hosts in `XJOIN_HOSTS_RESPONSE_FOR_FILTERING` have this Insights ID. Since this test passes right now, something is broken in either the code or the test :disappointed:

2021-12-06 16:43 UTC, kruai commented on tests/helpers/graphql_utils.py
> +XJOIN_HOSTS_RESPONSE_FOR_FILTERING = {
This isn't the format your `HOST_IDS_QUERY` uses; it should only return Host ID and canonical facts.

2021-12-06 16:43 UTC, kruai commented on tests/test_xjoin.py
> +    assert response_status == 404
This doesn't make sense to me; we don't want to expect 404 here unless this is specifically testing a scenario where the user deletes a host that doesn't exist. If the goal of this test is just to validate the graphql request, you can just remove `response_status`, `response_data`, and this 404 assertion imo

2021-12-06 16:43 UTC, kruai commented on tests/test_xjoin.py
> +    assert response_status == 404
Same 404 issue here and in the following tests; I won't leave any more comments about it though

2021-12-06 16:43 UTC, kruai commented on tests/test_xjoin.py
> +    )
It looks like this test passes regardless of what happens in the code above. What does this test that's different from the others?

2021-12-06 22:57 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    response_status, response_data = api_delete_filtered_hosts({"insights_id": "6e7b6317-0a2d-4552-a2f2-b7da0aece49d"})
Fixed the test.

2021-12-06 22:58 UTC, thearifismail commented on tests/test_xjoin.py
> +    assert response_status == 404
Fixed tests following the suggestion here here.

2021-12-06 23:01 UTC, thearifismail commented on api/filtering/filtering.py
> +    tags,
Yes, made the changed for alphabetic ordering.  Yes, it did lead to more changes but now they are done.

2021-12-06 23:02 UTC, thearifismail commented on api/host.py
> +    fields=None,
inadvertent deletion.  added `registered_with` back in.

2021-12-06 23:03 UTC, thearifismail commented on tests/test_xjoin.py
> +    assert response_status == 404
Done!

2021-12-06 23:19 UTC, thearifismail commented on tests/test_xjoin.py
> +    )
The intent was to use staleness, but now questioning its need.

2021-12-07 14:25 UTC, kruai commented on api/filtering/filtering.py
> +    tags,
But like @ryandillinfelton said, the other ones aren't in alphabetical order either. This just adds more changes that are unrelated to the task, like the param order for `get_host_list` and `get_tags`.

2021-12-07 14:34 UTC, thearifismail commented on tests/helpers/graphql_utils.py
> +XJOIN_HOSTS_RESPONSE_FOR_FILTERING = {
Fixed the template query

2021-12-07 14:58 UTC, thearifismail commented on tests/test_xjoin.py
> +    )
Removed this test as it served no real purpose.

2021-12-07 15:19 UTC, thearifismail commented on tests/helpers/graphql_utils.py
> +XJOIN_HOSTS_RESPONSE_FOR_FILTERING = {
Fixed `HOST_IDS_QUERY` to return "id" and "canonical_facts"

2021-12-07 20:31 UTC, kruai requested changes
I think this is nearly ready!

2021-12-07 20:31 UTC, kruai commented on api/filtering/filtering.py
> +    tags,
If it's really important to alphabetize the params for some reason, we'd also need to rearrange `fqdn` and `registered_with`... But as I don't really see the benefit to reordering these params, I'd like it to stay in the order it was before, in order to reduce the number of changes to files that would have otherwise not be modified.

2021-12-07 20:31 UTC, kruai commented on api/host.py
> +
Unused, please remove

2021-12-07 20:31 UTC, kruai commented on tests/helpers/graphql_utils.py
> +        "meta": {"total": 2},
IDK if this affects anything, but the total number of hosts in your response is actually 3

2021-12-07 20:31 UTC, kruai commented on tests/test_api_hosts_delete.py
> +    response_status, response_data = api_delete_filtered_hosts({"insights_id": "a58c53e0-8000-4384-b902-c70b69faacc5"})
A bit scary because only one of the hosts in your mock xjoin response has that `insights_id`, but I suppose it's fine if you're just testing the delete-specific functionality in this test

2021-12-07 20:31 UTC, kruai commented on tests/test_xjoin.py
> +    mocker, query_source_xjoin, graphql_query_empty_response, api_delete_filtered_hosts
Yeah. You could create the hosts in the DB for that, but I don't know how useful that would be if the "deletion" part is covered by `test_delete_hosts_using_filter`.

2021-12-07 21:35 UTC, thearifismail commented on api/host.py
> +
Gone.

2021-12-07 21:38 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    response_status, response_data = api_delete_filtered_hosts({"insights_id": "a58c53e0-8000-4384-b902-c70b69faacc5"})
Yes, testing `delete-specific` functionality.

2021-12-08 14:29 UTC, thearifismail commented
/retest

2021-12-08 16:46 UTC, kruai approved these changes

2021-12-10 21:19 UTC, ryandillinfelton approved these changes
I got a nitpick but overall I think it looks good and I can live with the function name thing. LGTM

2021-12-10 21:19 UTC, ryandillinfelton commented on api/host.py
> +def _delete_filtered_hosts(host_id_list):
I think the name of the function is misleading since it's used in other places as well. Like when it's used as part of `delete_by_id` it's not deleting filtered hosts, it's just deleting hosts using a list of ids. I propose changing the name to reflect it's behavior and uses.
```suggestion
def _delete_hosts_by_id_list(host_id_list):
```

2021-12-13 13:59 UTC, thearifismail commented
/retest

2021-12-13 17:22 UTC, thearifismail commented
/retest

2021-12-13 20:47 UTC, thearifismail commented
/retest

2021-12-13 21:52 UTC, merged