WIP: Implement Ansible object filter
RedHatInsights/insights-host-inventory pull request #1024
Opened 2021-11-02 14:29 UTC by kruai

# Overview

This PR is being created to address [ESSNTL-1572](https://issues.redhat.com/browse/ESSNTL-1572).
The goal of this PR is to allow filtering on the `ansible` System Profile object. If my refactoring goes well, I'd love to generalize this to work for basic "object" types in the SP.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-11-02 17:26 UTC, kruai commented on api/filtering/filtering.py
> +        )
I just realized this "wildcard" stuff was leftover from when this was just the Ansible filter. I'm making this more generic right now

2021-11-02 18:58 UTC, ryandillinfelton commented on api/filtering/filtering.py
> +    for name in input_object:
We could easily make this a follow up. As is this will only work for single level deep objects. It should really be recursive (or equivalently iterative but that seems trickier)  if we'd like to make it more robust.

2021-11-04 15:12 UTC, kruai commented
The unit tests are passing, so I'm unclear as to why the PR check is failing atm. Is there an easy way to get it to run again without pushing another change? I seem to recall that re-running the job works, but doesn't show on the PR.

2021-11-04 15:42 UTC, ryandillinfelton commented
> The unit tests are passing, so I'm unclear as to why the PR check is failing atm. Is there an easy way to get it to run again without pushing another change? I seem to recall that re-running the job works, but doesn't show on the PR.

Usually re-running does work.

2021-11-04 15:47 UTC, kruai commented
> > The unit tests are passing, so I'm unclear as to why the PR check is failing atm. Is there an easy way to get it to run again without pushing another change? I seem to recall that re-running the job works, but doesn't show on the PR.
> 
> Usually re-running does work.

Oh, you're right. I must have used "Build Now" or "Rebuild Last" earlier. "Retry" appears to work, though the check is still failing. Investigating now

2021-11-04 15:55 UTC, kruai commented
Appears to be failing in a bonfire step where it's attempting to find a front-end deployment file. I'll post in Slack about it

2021-11-04 16:03 UTC, ryandillinfelton approved these changes

2021-11-04 19:03 UTC, thearifismail submitted a review, later dismissed
LGTM

2021-11-04 20:47 UTC, ryandillinfelton requested changes
Woops

2021-11-04 20:47 UTC, ryandillinfelton commented on api/filtering/filtering.py
> +        field_value = _get_field_value(input_object[name], child_filter)
Whoops. This only works for singly nested stuff rn.

2021-11-05 15:18 UTC, thearifismail reviewed
The `test_query_hosts_filter_spf_ansible` should include AND

2021-11-05 15:18 UTC, thearifismail commented on tests/test_xjoin.py
> +        {"OR": [{"spf_ansible": {"controller_version": {"matches": "7.1"}}}]},
Shouldn't `AND` be included also?

2021-11-05 16:41 UTC, kruai commented on tests/test_xjoin.py
> +        {"OR": [{"spf_ansible": {"controller_version": {"matches": "7.1"}}}]},
No, I don't see how that would work. Where are you suggesting it would go?

2021-11-05 22:06 UTC, kruai commented on api/filtering/filtering.py
> +        field_value = _get_field_value(input_object[name], child_filter)
I overhauled my implementation, and it should work for fully nested stuff now.

2021-11-09 20:48 UTC, ryandillinfelton approved these changes
Te functionality and implementation looks good to me, as does the test coverage. We've discussed the potential issues this may cause with future support of multiple values for object fields, but the conclusion is that the trade of is acceptable.

2021-11-09 21:39 UTC, ryandillinfelton requested changes
Whoops. I looked into Arifs comment more and I believe the boolean operation is wrong. Let me know your thoughts. It's not a hard and fast rule, it's mostly up to our judgement. The rule of thump i use is `AND` for combining different parameters, `OR` for combining multiple of the same type.

2021-11-09 21:39 UTC, ryandillinfelton commented on tests/test_xjoin.py
> +        {"OR": [{"spf_ansible": {"controller_version": {"matches": "7.1"}}}]},
> Shouldn't `AND` be included also?

It's not possible to request which boolean operation you want to use for the query in the REST API.  That said I think we should make this AND by default since we are not supporting multiple values per field here. I believe that's usually how our parameters work.

different fields are "anded" together, same field with multiple values is "ored"

2021-11-09 22:18 UTC, thearifismail reviewed
Minor comments

2021-11-09 22:42 UTC, kruai commented on app/__init__.py
> +def process_spec(spec, process_unindexed=False):
`process_system_profile_spec` is not the only calling function. This function is now also called recursively by itself, so that it can generate queries based on deep objects.

2021-11-09 22:57 UTC, kruai commented
> Whoops. I looked into Arifs comment more and I believe the boolean operation is wrong. Let me know your thoughts. It's not a hard and fast rule, it's mostly up to our judgement. The rule of thump i use is `AND` for combining different parameters, `OR` for combining multiple of the same type.

OK. Because there's only one clause inside, this doesn't affect the query logic at all. However, if that's our rule of thumb, then I'll push the change.

2021-11-09 23:01 UTC, thearifismail commented on app/__init__.py
> +def process_spec(spec, process_unindexed=False):
oh I meant system_profile was the only context.  okay recursion is the reason.

2021-11-09 23:07 UTC, thearifismail approved these changes

2021-11-11 16:18 UTC, ryandillinfelton approved these changes
I'll  approve to unblock. I would like to also see test expansion in the follow up though.

With deep object queries we allow users to specify operation
`filter[system_profile][ansible][controller_version][eq]=7.1`
`filter[system_profile][ansible][controller_version][matches]=7*`

the way it's set up now is a sensible default and something we allow though.

2021-11-11 16:47 UTC, merged