Check kafka availability before deleting hosts
RedHatInsights/insights-host-inventory pull request #1047
Opened 2021-12-11 00:18 UTC by thearifismail

# Overview

This PR is being created to address [ESSNTL-38](https://issues.redhat.com/browse/ESSNTL-38).
(A description of your PR's changes, along with why/context to the PR, goes here.)

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [x] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [x] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-12-13 21:28 UTC, RonnyPfannschmidt commented on lib/host_kafka.py
> +        nw_addr = (host, int(port))
i suggest to put that into get_bootstrap servers instead of splitting it here, that way the check can be simplified

2021-12-13 21:29 UTC, RonnyPfannschmidt commented on lib/host_kafka.py
> +    kafka_check = 999
lets remove the need for that variable alltogether

2021-12-13 21:30 UTC, RonnyPfannschmidt commented on lib/host_kafka.py
> +        conn_check = kafka_socket.connect_ex(nw_addr)
```suggestion
        maybe_error_code = kafka_socket.connect_ex(nw_addr)
        if maybe_error_code == 0:
           return True
```

makes things way more easy on the loop

2021-12-13 21:31 UTC, RonnyPfannschmidt commented on lib/host_kafka.py
> +    if isinstance(kafkas, str):
always normalize to a list of servers

2021-12-13 21:32 UTC, RonnyPfannschmidt commented on lib/host_kafka.py
> +            if kafka_check == 0:
instead of break, use a return, and use `contextlib.closing` on the socket to do cleanup

2021-12-13 23:44 UTC, thearifismail commented on lib/host_kafka.py
> +        nw_addr = (host, int(port))
Done!

2021-12-13 23:44 UTC, thearifismail commented on lib/host_kafka.py
> +    kafka_check = 999
Gone!

2021-12-13 23:44 UTC, thearifismail commented on lib/host_kafka.py
> +        conn_check = kafka_socket.connect_ex(nw_addr)
Done!

2021-12-13 23:44 UTC, thearifismail commented on lib/host_kafka.py
> +    if isinstance(kafkas, str):
Done!

2021-12-13 23:45 UTC, thearifismail commented on lib/host_kafka.py
> +            if kafka_check == 0:
IMO, not needed.  The code is too simple to use the suggestion.

2021-12-14 02:24 UTC, thearifismail commented on lib/host_kafka.py
> +            if kafka_check == 0:
Done.  Changed mind and update the code to use `contextlib.closing`

2021-12-14 13:50 UTC, thearifismail commented
/retest

2021-12-14 14:29 UTC, RonnyPfannschmidt commented on lib/host_kafka.py
> +def _get_bootstrap_servers(kafka_socket, servers):
nice compression - new the name 
```suggestion
def _any_bootstrap_server_connects(kafka_socket, servers) ->  bool:
```

seems like match

2021-12-14 15:08 UTC, thearifismail commented
/retest

2021-12-14 19:08 UTC, thearifismail commented
/retest

2021-12-14 20:33 UTC, thearifismail commented
/retest

2021-12-17 13:16 UTC, thearifismail commented
/retest

2021-12-17 13:29 UTC, thearifismail commented
/retest

2021-12-20 17:56 UTC, kruai requested changes
The implementation mostly looks good! I have some suggestions to simplify some things, and some notes on the unit testing.

2021-12-20 17:56 UTC, kruai commented on tests/test_api_hosts_delete.py
> +    mocker.patch("api.host.kafka_available", return_value=True)
This change is made in so many tests that it would make more sense to use pytest fixtures. I recommend the following:

1. Create a fixture for when kafka should be available (let's call it `patch_kafka_available` for explanation purposes). It patches "api.host.kafka_available" the way you're doing in the above code.
2. Update the `api_delete_host` fixture to use the new `patch_kafka_available` fixture, so kafka will automatically be available for any test that uses `api_delete_host`.
3. Then, you can remove `mocker` from these tests, as they will be patched automatically.

When you test the functionality for kafka NOT being available, you can create another fixture (named `patch_kafka_unavailable`, for instance) and use that.

2021-12-20 17:56 UTC, kruai commented on lib/host_kafka.py
> +                    return True
can be simplified
```suggestion
                if not kafka_socket.connect_ex(new_addr):
                    return True
```

2021-12-20 17:56 UTC, kruai commented on lib/host_kafka.py
> +    return kafka is True
can be simplified
```suggestion
    with closing(socket.socket(socket.AF_INET, socket.SOCK_STREAM)) as kafka_socket:
        return _any_bootstrap_server_connects(kafka_socket, servers)
```

2021-12-20 17:56 UTC, kruai commented on tests/test_unit.py
> +                    thismock.reset_mock()
Why is this change here?

2021-12-20 17:56 UTC, kruai commented on tests/test_unit.py
> +        real._any_bootstrap_server_connects.assert_called_once_with(mock.ANY, None)
This is more of an issue of readability... but why did you make a variable named `real` which is set to the whole `host_kafka` class? `available` also seems unnecessary, since it's only read once. It would be more concise and IMO easier to understand without the extra vars:

```suggestion
        host_kafka._any_bootstrap_server_connects = MagicMock()
        host_kafka._any_bootstrap_server_connects.return_value = True

        assert host_kafka.kafka_available()
        host_kafka._any_bootstrap_server_connects.assert_called_once_with(mock.ANY, None)
```

2021-12-20 17:56 UTC, kruai commented on tests/test_unit.py
> +        real._any_bootstrap_server_connects.assert_called_once_with(mock.ANY, kafka_servers)
These are all effectively testing the same things, which are:

1. `kafka_available` will call `_any_bootstrap_server_connects` and pass it the list of servers you provide
2. `kafka_available` will return what you mocked for `_any_bootstrap_server_connects.return_value`

It isn't actually testing whether any of the servers are invalid or malformed. In order to do that, you'll need some tests that actually validate `_any_bootstrap_server_connects`. In those tests, I'd recommend patching `kafka_socket.connect_ex` to return a mock error code.

2021-12-20 17:56 UTC, kruai commented on lib/host_kafka.py
> +        servers = [config.bootstrap_servers]
they're already a list
```suggestion
        servers = config.bootstrap_servers
```

2021-12-20 18:51 UTC, ryandillinfelton requested changes
I think Asa covered most of the bases here.

I somewhat disagree about on suggested change on style grounds but that's up for debate and will work correctly either way. Over all looks pretty close. 

Let me know if I'm off base with the return comment, it looks the there is a test covering that case so if it passes maybe I'm misunderstanding something.

2021-12-20 18:51 UTC, ryandillinfelton commented on lib/host_kafka.py
> +def _any_bootstrap_server_connects(kafka_socket, servers) -> bool:
The function will never return false and may cause an error if non of the servers can be connected to.

2021-12-20 18:51 UTC, ryandillinfelton commented on lib/host_kafka.py
> +                    return True
If you do that it may be worth adding a comment explaining what's going on. Or maybe just keep the variable cast even though we only use the value once for clarity.
I think that
```
if not maybe_errorcode:
``` 
is pretty self documenting. reads like "if there's not an error code". However

```
if not kafka_socket.connect_ex(new_addr):
```
is not very clear IMO. It reads a bit like "if not connected to new address" or something.

2021-12-20 18:51 UTC, ryandillinfelton commented on tests/test_unit.py
> +class KafkaAvailabilityTests(TestCase):
Could use explicit testing for exception handling.

2021-12-21 14:50 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    mocker.patch("api.host.kafka_available", return_value=True)
Done.  Added a fixture `patch_kafka_available()` and a supporting function `_kafka_patch()`

2021-12-21 14:56 UTC, thearifismail commented on lib/host_kafka.py
> +                    return True
Added comment "# connect_ex() returns zero when the socket is open and accessible"

2021-12-21 14:57 UTC, thearifismail commented on lib/host_kafka.py
> +    return kafka is True
Fixed per suggestion. I have an old habit of "not returning from within a loop

2021-12-21 15:01 UTC, thearifismail commented on tests/test_unit.py
> +                    thismock.reset_mock()
`thismock` had to be used in place of the original `mock` variable but now it is not needed due to code changes.

2021-12-21 15:21 UTC, thearifismail commented on lib/host_kafka.py
> +        servers = [config.bootstrap_servers]
When there is a single Kafka server, a string is returned as `host:port`.  `[]` has been added to deal with such cases.

2021-12-21 15:29 UTC, thearifismail commented on api/host.py
> +        deletion_count = 0
oh this was left over after the reversion of delete filtered hosts

2021-12-21 15:31 UTC, thearifismail commented on lib/host_kafka.py
> +def _any_bootstrap_server_connects(kafka_socket, servers) -> bool:
In case of failures, callers have:
`logger.error("Kafka server not available.")`
`flask.abort(status.HTTP_503_SERVICE_UNAVAILABLE)`

2021-12-21 15:39 UTC, thearifismail commented on tests/test_unit.py
> +                    thismock.reset_mock()
oh still needed.  The presence of `from unittest import mock` cause `flake` to fail with: 
```
tests/test_unit.py:1189:21: F402 import 'mock' from line 11 shadowed by loop variable
```

2021-12-21 16:09 UTC, thearifismail commented on tests/test_unit.py
> +class KafkaAvailabilityTests(TestCase):
```
def _any_bootstrap_server_connects(kafka_socket, servers) -> bool:
```
When Kafka is not available, `_any_bootstrap_server_connects` simply logs a message and does not throw any exception.  In the API code, when `kafka_available()` does not return `True`, does the following:
```
            logger.error("Kafka server not available.")
            flask.abort(status.HTTP_503_SERVICE_UNAVAILABLE)
```

2021-12-21 17:34 UTC, thearifismail commented on tests/test_unit.py
> +        real._any_bootstrap_server_connects.assert_called_once_with(mock.ANY, kafka_servers)
Can not patch `socket.connect_ex()` for being `read-only`.  

The intent for these tests to test different permutations which can be used as Kafka server addresses.

2021-12-21 17:59 UTC, thearifismail commented
/retest

2021-12-21 20:13 UTC, thearifismail commented
/retest

2021-12-21 20:50 UTC, ryandillinfelton commented on lib/host_kafka.py
> +        servers = [config.bootstrap_servers]
That will make a double nested given a list though right? Should it conditionally cast to a list like
```
servers = [config.bootstrap_servers] if config.bootstrap_servers is string else config.bootstrap_servers
```
or something like that?

2021-12-21 21:58 UTC, thearifismail commented on lib/host_kafka.py
> +        servers = [config.bootstrap_servers]
Updated the code add suggested for being elegant.  Reason behind the previous implementation was `[[...]]` evaluated as string.  Here is how it was checked:
```
>>> fruit = [["apples", "oranges", "apricots"]]
>>> type(fruit)
<class 'list'>
>>> 
```

2022-01-07 13:19 UTC, fijshion commented
I could be misreading the code, it appears to do a single check for Kafka availability before deleting rows in the DB. What happens if Kafka goes down after the initial check but before the Kafka is message is attempted to be sent? I know this isn't very likely but when it happens it'll be a headache. Is it possible to roll back the DB change (via a DB transaction) if the Kafka message fails to be produced instead?

2022-01-07 21:39 UTC, thearifismail commented
> I could be misreading the code, it appears to do a single check for Kafka availability before deleting rows in the DB. What happens if Kafka goes down after the initial check but before the Kafka is message is attempted to be sent? I know this isn't very likely but when it happens it'll be a headache. Is it possible to roll back the DB change (via a DB transaction) if the Kafka message fails to be produced instead?

Being a very unlikely scenario, IMO it should be addressed in future as a refinement to this implementation.  Committing this one will help dealing with other places where ever hosts are deleted.

A bit of googling revealed that there is a notion of flashing back committed DB transactions but not sure if SQLAlchemy can or not.  The simpler option is checking "Kafka availability" [here](https://github.com/thearifismail/insights-host-inventory/blob/6069cf16d83648321f3a37ebc282088a4d560bd1/lib/host_delete.py#L37) before deleting every host.  This can be done in a separate PR.

2022-01-10 12:46 UTC, fijshion commented
SQLAlchemy does have transactions: https://docs.sqlalchemy.org/en/14/orm/session_transaction.html. I don't see any reason not to start with the code in this PR, but I just want to make sure using transactions isn't deprioritized because of it. DB transactions are standard practice and a clean way to handle this type of scenario. It also looks like SQLAlchemy makes them pretty simple to implement.

2022-01-10 13:11 UTC, kruai commented
> SQLAlchemy does have transactions: https://docs.sqlalchemy.org/en/14/orm/session_transaction.html. I don't see any reason not to start with the code in this PR, but I just want to make sure using transactions isn't deprioritized because of it. DB transactions are standard practice and a clean way to handle this type of scenario. It also looks like SQLAlchemy makes them pretty simple to implement.

That sounds like a good plan. We had been holding off on doing _Kafka_ transactions because we'd need to migrate to a different client lib first, but I'd love if we could start using transactions more.

FYI, we use the functions `session_guard` and `multi_session_guard` to handle session transactions already; we could probably use them here as well.

2022-01-13 16:00 UTC, thearifismail commented
/retest

2022-01-13 16:30 UTC, bennyturns commented
/retest

2022-01-13 16:51 UTC, bennyturns commented
/retest

2022-01-13 17:16 UTC, bennyturns commented
/retest

2022-01-13 20:54 UTC, thearifismail commented
/retest

2022-01-25 22:40 UTC, ryandillinfelton commented on tests/test_api_hosts_delete.py
>      assert_response_status(response_status, expected_status=404)
If you set up your fixtures differently you won't need to pass mocker to api_delete_host in every test you call it in. This change would cut down a lot of the line changes in this PR.

I tested it out just to make sure I was right and ended up just making the changes so I've opened a PR with the changes here: https://github.com/thearifismail/insights-host-inventory/pull/9

2022-01-25 22:50 UTC, ryandillinfelton commented on lib/host_kafka.py
> +def _any_bootstrap_server_connects(kafka_socket, servers) -> bool:
I was wondering about how statements like `if kafka_available():` in `host/delete.py` would resolve since this function doesn't abort the process or return false when it can't connect to any servers. Turns out functions will return `None` in python if there is no explicit return statement and since None will evaluate to false branching based on the return will work. I would still prefer an explicit `return False` fall though though for clarity. But I'll admit that's nitpicky so up to you.

2022-01-25 23:35 UTC, thearifismail commented on tests/test_api_hosts_delete.py
>      assert_response_status(response_status, expected_status=404)
Thanks @ryandillinfelton pulled last [PR #10](https://github.com/thearifismail/insights-host-inventory/pull/10)

2022-01-26 20:36 UTC, ryandillinfelton commented on tests/test_api_hosts_delete.py
> -def test_delete_hosts_using_filter(
Why is this test being deleted?

2022-01-26 23:32 UTC, kruai requested changes
I have a few remaining questions and concerns

2022-01-26 23:32 UTC, kruai commented on tests/fixtures/api_fixtures.py
> +    return _patch_kafka_available
At the moment, these appear to only be replacing inline calls to `mocker.patch()`. Is that correct?
Since we want `kafka_available` to return True by default in our tests, I think it would be better to use a session-scoped patch, and then patch it as _unavailable_ when you need to test that scenario.

2022-01-26 23:32 UTC, kruai commented on lib/host_delete.py
> +        host_deleted = _deleted_by_this_query(host)
`_deleted_by_this_query(host)` only works after the deletion has been committed, according to its comments... is this tested and working as expected?

2022-01-26 23:32 UTC, kruai commented on lib/host_delete.py
> +            delete_query.session.commit()
I'm unable to find either a call to `rollback` or usage of `session_guard`. Is this attempting to use transactions as @fijshion suggested? If so, can you point me to where the rollback occurs?

2022-01-26 23:32 UTC, kruai commented on tests/test_unit.py
> +from unittest import mock
You don't need to import this. `ANY`, `MagicMock` and `Mock` are all already imported.

2022-01-26 23:32 UTC, kruai commented on tests/test_unit.py
> +                    thismock.reset_mock()
That failed because you imported `mock`, which you didn't need to do (see above comment)

2022-01-27 14:46 UTC, ryandillinfelton approved these changes
LGTM! :tada:

2022-01-27 16:14 UTC, thearifismail commented on lib/host_delete.py
> +        host_deleted = _deleted_by_this_query(host)
`_deleted_by_this_query(host)` is called before committing the change. The comments has been changed to match the current implementation.  Besides, `ObjectDeletedError` is not mentioned or handled anywhere else in the host-inventory code.

2022-01-27 16:16 UTC, thearifismail commented on lib/host_delete.py
> +            delete_query.session.commit()
just added rollback.  session_guard not needed because the transaction is committed when successful and rolled back when fails.

2022-01-27 16:17 UTC, thearifismail commented on lib/host_delete.py
> +        logger.error(f"host with {host.id} because Kafka server not available.")
Fixed the error message.

2022-01-27 16:17 UTC, thearifismail commented on lib/host_delete.py
> +        flask.abort(status.HTTP_503_SERVICE_UNAVAILABLE)
flask.abort removed.

2022-01-27 16:18 UTC, thearifismail commented on lib/host_kafka.py
> +def _any_bootstrap_server_connects(kafka_socket, servers) -> bool:
Now the method return False instead to running `flask.abort()`

2022-01-27 16:50 UTC, thearifismail commented on lib/host_delete.py
> +                host_deleted = _delete_host(select_query.session, event_producer, host)
Fixed code to return False when a host is not deleted.

2022-01-27 17:32 UTC, thearifismail commented on tests/test_unit.py
> +from unittest import mock
No.  Removing them complains `not found` or `undefined`

2022-01-27 17:44 UTC, thearifismail commented
@kruai Changed fixture scope to session`@pytest.fixture(scope="session")` .  Kafka unavailable checks are tested by unit tests. No new integration tests created because there are existing tests to deal with KafkaError

2022-01-27 19:49 UTC, kruai commented on tests/test_unit.py
> +from unittest import mock
I'm saying that right now, this file already imports a number of things from `unittest.mock`, including `ANY`.
It appears that you only added `from unittest import mock` so that you could use `mock.ANY`, but that's already imported.
If you just change the lines you added to `ANY` instead of `mock.ANY`, you can remove this import statement

2022-01-27 22:41 UTC, thearifismail commented on tests/test_unit.py
> +from unittest import mock
Ah.  Thanks.  Done

2022-02-07 21:29 UTC, kruai requested changes
In addition to the kafka availability tests you added, we also need some tests to validate the output when kafka fails to produce the DELETE messages. Or, if we already have tests that validate this, they should be updated to demonstrate that the deletion has been rolled back after the kafka error.

(Also, please update this PR's description to summarize at least the basics of what it's addressing)

2022-02-07 21:29 UTC, kruai commented on lib/host_delete.py
> +            delete_query.session.commit()
I'm concerned about if `write_event()` fails and raises an exception. When using `session_guard`, it catches exceptions and automatically rolls back; in your code, I only see a rollback happen if `_deleted_by_this_query(host)` returns false (which only happens if something else deletes the host first). 

Is it being rolled back somewhere else I'm not seeing?

2022-02-07 21:29 UTC, kruai commented on tests/fixtures/api_fixtures.py
> +    return _patch_kafka_available
`scope="session"` applies the fixture for the whole session, which works, but only if you actually use the fixture. I don't see this fixture being used anywhere

2022-02-07 21:29 UTC, kruai commented on tests/fixtures/api_fixtures.py
> +    return _kafka_patch
As far as I can tell, you're patching the same function every time. Do we need a dedicated function for this, when we can just patch `mocker.patch("lib.host_delete.kafka_available")` directly?

2022-02-07 21:29 UTC, kruai commented on tests/test_api_hosts_delete.py
> +    mocker.patch("lib.host_delete.kafka_available")
Not gonna comment on all of these, but... you have the `patch_kafka_available` fixture now. These patches should no longer be necessary once the fixture is requested. It would probably make sense to be requested by `event_producer_mock` - what do you think @ryandillinfelton?

2022-02-08 14:19 UTC, thearifismail commented on api/host.py
> +        if not len(ids_list):
Fixed!

2022-02-08 23:00 UTC, thearifismail commented on lib/host_delete.py
> +            delete_query.session.commit()
Now using `with session_guard(select_query.session)` before starting the deletions.

2022-02-08 23:02 UTC, thearifismail commented on lib/host_delete.py
> +    # Before committing the change, verify that the host has been marked 'expired'
`instance_state(host).expired` means the host has marked for deletion but its deletion has not been committed yet.

2022-02-09 01:59 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    mocker.patch("lib.host_delete.kafka_available")
Removed the `patch_kafka_available()` fixture.  Since `kafka_availablility` check stretches across the whole session, I tried to create a fixture for use in place of `mocker.patch("lib.host_delete.kafka_available")`, but have not found a way yet.

2022-02-09 02:00 UTC, thearifismail reviewed
@asa, please take a look.  Thanks.

2022-02-09 15:41 UTC, kruai commented on lib/host_delete.py
> +    # Before committing the change, verify that the host has been marked 'expired'
My understanding from the SQLAlchemy docs is that an object gets `expired` if another session has deleted the object; I think here we're making sure not to attempt to delete a host that was deleted by another process (like Reaper, or even another DELETE request).
But anyway, the code was returning whether the host was _not_ expired, so I was just correcting the comment.

2022-02-09 18:11 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    mocker.patch("lib.host_delete.kafka_available")
@kruai @ryandillinfelton,
yesterday while trying to create a clean and crisp fixture to make `kafka_available` but the only way I could make it work was adding `kafka_patch("lib.host_delete.kafka_available")` to the `api_delete_host`, `api_delete_filtered_hosts`, and `api_delete_all_hosts` fixture but doing so required passing in `mocker` from every test using `api_delete_*`, which would lead to a lot more changes than what is in now.  That's why I took that out.

2022-02-15 21:48 UTC, kruai commented on tests/test_api_hosts_delete.py
> +    mocker.patch("lib.host_delete.kafka_available")
No, I said the `event_producer_mock` fixture, not any of the API ones; you're not patching an API function anyway.
I pulled down your code and removed all of those `mocker.patch()` statements and instead put one in the definition for `event_producer_mock`, and it functions as expected.

2022-02-15 22:08 UTC, kruai requested changes
A few notes, but... I still take issue with this `patch` approach, especially because developers will just have to know to manually add this patch statement every time they use the event producer. See my comment about adding it to the `event_producer_mock` fixture

2022-02-15 22:08 UTC, kruai commented on tests/test_culling.py
> -    assert db_get_host(created_host.id)
Why is this assertion being removed?

2022-02-17 16:26 UTC, thearifismail commented on tests/test_culling.py
> -    assert db_get_host(created_host.id)
with use of `session_guard(select_query.session)` in `delete_hosts()`, the session is closed already when `host_reaper_run()` is called.  So instead whether an event was created or not.

2022-02-17 16:27 UTC, thearifismail commented on tests/test_culling.py
> -    assert db_get_host(created_host.id)
with use of `session_guard(select_query.session)` in `delete_hosts()`, the session is closed already when `host_reaper_run()` is called.  So instead whether an event was created or not.

2022-02-17 17:36 UTC, thearifismail commented on lib/host_delete.py
> +    # Before committing the change, verify that the host has been marked for deletion.
Put the original comment back.

2022-02-17 20:35 UTC, kruai requested changes
Needs some cleanup, but it's almost there

2022-02-17 20:35 UTC, kruai commented on tests/test_culling.py
> -    assert db_get_host(created_host.id)
True that the session gets closed, but I don't see why that means we can't check that the host still exists. If you're getting an error saying that `created_host` isn't bound to a session, I'd recommend only storing the ID, i.e.:
```
created_host_id = db_create_host(host=host).id
```
Then, you should be able to make both assertions without issue:
```
assert db_get_host(created_host_id)
assert event_producer_mock.event is None
```

That being said, the purpose of this test isn't to verify that the DB and Kafka messages are in sync, so consider this change optional - it shouldn't block the merge

2022-02-17 20:35 UTC, kruai commented on tests/test_api_hosts_delete.py
> +    event_datetime_mock, event_producer_mock, db_create_host, api_delete_host, mocker
`mocker` is defined but not used

2022-02-17 20:35 UTC, kruai commented on tests/test_api_hosts_delete.py
> +    event_producer_mock, db_create_multiple_hosts, db_get_hosts, api_delete_all_hosts, patch_xjoin_post, mocker
`mocker` is defined but not used

2022-02-17 20:35 UTC, kruai commented on tests/test_api_hosts_delete.py
> +    send_side_effects, kafka_producer, event_producer, db_create_multiple_hosts, api_delete_host, db_get_hosts, mocker
`mocker` is defined but not used

2022-02-17 20:35 UTC, kruai commented on tests/test_culling.py
> +def test_reaper_shutdown_handler(db_create_host, db_get_hosts, inventory_config, mocker, event_producer_mock):
`mocker` is defined but not used

2022-02-17 20:35 UTC, kruai commented on tests/test_culling.py
> -    assert db_get_host(created_host.id)
OK. I'm not gonna copy&paste what I said in the other place you made this change, but this check can still be done by changing one of the vars. Optional though and won't block the merge

2022-02-17 20:35 UTC, kruai commented on tests/test_culling.py
> +
`mocker` should be removed from the params, and the `mocker.patch` statement should be removed. Both the `event_producer` and `kafka_producer` fixtures are entirely mocked objects that don't call `kafka_available`.

2022-02-17 21:11 UTC, thearifismail commented on tests/test_api_hosts_update.py
> +    mocker.patch("lib.host_delete.kafka_available")
`EventProducer.write_event()` needs `Kafka` for `send._kafka_prodcuer.send(...)`.  When `Kafka` is not available `assert event_producer.write_event.call_args_list[-1][0][2]["event_type"] == "delete"` fails.  The fix is to either update the `event_producer` fixture or use `mocker.patch()` like I did.  Since there were only 3 places where `event_producer` needed patching, I chose to go with explicit patching.

2022-02-17 21:13 UTC, thearifismail commented on tests/test_culling.py
> +def test_dont_get_only_culled(mq_create_hosts_in_all_states, event_producer_mock, api_get):
Fixed.

2022-02-17 21:14 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    send_side_effects, kafka_producer, event_producer, db_create_multiple_hosts, api_delete_host, db_get_hosts, mocker
Gone!

2022-02-17 21:14 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    event_datetime_mock, event_producer_mock, db_create_host, api_delete_host, mocker
Gone!

2022-02-17 21:14 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    event_producer_mock, db_create_multiple_hosts, db_get_hosts, api_delete_all_hosts, patch_xjoin_post, mocker
Gone!

2022-02-17 21:14 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    mocker,
Gone!

2022-02-17 21:14 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    event_datetime_mock, event_producer_mock, db_create_host, api_delete_host, mocker
Gone!

2022-02-17 21:14 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    event_datetime_mock, event_producer_mock, db_create_host, api_delete_host, mocker
Gone!

2022-02-17 21:14 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    event_datetime_mock, event_producer_mock, db_create_host, api_delete_host, mocker
Gone!

2022-02-17 21:15 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    event_datetime_mock, event_producer_mock, db_create_host, db_get_host, api_delete_host, mocker
Gone!

2022-02-17 21:15 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    event_datetime_mock, event_producer_mock, db_create_host, db_get_host, api_delete_host, mocker
Gone!

2022-02-17 21:18 UTC, thearifismail commented on tests/test_culling.py
> +def test_delete_ignores_culled(mq_create_hosts_in_all_states, api_delete_host, mocker):
Gone!

2022-02-17 21:19 UTC, thearifismail commented on tests/test_culling.py
> +def test_delete_works_on_non_culled(mq_create_hosts_in_all_states, api_delete_host, mocker):
Gone!

2022-02-17 21:27 UTC, thearifismail commented on tests/test_culling.py
> +
without mocker.patch(), the test fails.   As mentioned above:
EventProducer.write_event() needs Kafka for send._kafka_prodcuer.send(...). When Kafka is not available assert event_producer.write_event.call_args_list[-1][0][2]["event_type"] == "delete" fails. The fix is to either update the event_producer fixture or use mocker.patch() like I did. Since there were only 3 places where event_producer needed patching, I chose to go with explicit patching.

2022-02-21 22:24 UTC, kruai requested changes
One comment and a couple requests.

2022-02-21 22:24 UTC, kruai commented on tests/test_culling.py
> +def test_reaper_shutdown_handler(db_create_host, db_get_hosts, inventory_config, event_producer_mock):
Just curious... why is the `event_producer_mock` fixture being added here?

2022-02-21 22:24 UTC, kruai commented on tests/test_culling.py
> -    assert db_get_host(created_host.id)
@thearifismail You shouldn't create the host again after it's deleted... I meant that because only the ID is used, you could replace this (L340):
```
created_host = db_create_host(host=host)
```
with this:
```
created_host_id = db_create_host(host=host).id
```
That way, you can just use `created_host_id` for your checks, since it will persist after the host is deleted.

2022-02-21 22:24 UTC, kruai commented on tests/test_culling.py
> +    created_host_id = db_create_host(host=created_host).id
It doesn't make sense to create and validate a new host here. See my above comment about `created_host_id`.

2022-02-22 15:56 UTC, thearifismail commented
/retest

2022-02-22 18:08 UTC, thearifismail commented on tests/test_culling.py
> +def test_reaper_shutdown_handler(db_create_host, db_get_hosts, inventory_config, event_producer_mock):
Had to add back `event_producer_mock`, the fixture because it provides `kafka` when not available.

2022-02-22 18:10 UTC, thearifismail commented on tests/test_culling.py
> +    created_host_id = db_create_host(host=created_host).id
I did wonder checking for an updated event NOT create but then it slipped off.  Since it is not needed, now it checks if an event was generated or not which does not.

2022-02-22 22:47 UTC, ryandillinfelton requested changes
I left some suggestions around reworking exception handing and some structure and clarity changes.

I also think this need a more tests.

The current unit tests don't give me much confidence since basically all of the new logic is mocked. I really don't think you should be mocking `_any_bootstrap_server_connects` in the unit tests at all since it is what should be being tested.

I would also like:

- API tests that make sure we get the correct response from the API when Kafka isn't available.
- Tests that make sure it fails gracefully if Kafka goes down during a bulk delete operation.
- Tests that verify that the hosts are not deleted, and no delete events are produced if Kafka is not available

2022-02-22 22:47 UTC, ryandillinfelton commented on lib/host_delete.py
> +        raise KafkaError("Kafka server not available.  Stopping host deletions.")
I don't think that the code currently will stop _attempting_ to delete hosts when this error is raised. There is no exception handling done in the `delete_hosts` loop, so it will continue running and raising these exceptions.

I think this exception handling and structure need work. There's more nesting than needed, making it the responsibility of callers to raise the correct error when kafka can't be reached is error prone, and the exception you're raising is not being caught or acted upon.

I think you should instead check if Kafka is available first and if it's not re-raise the exception and return early.

```suggestion
    try:
        kafka_available()
    except KafkaError:
        logger.error(f"host with {host.id} NOT deleted because Kafka server not available.")
        raise

    delete_query.delete(synchronize_session="fetch")
    host_deleted = _deleted_by_this_query(host)
    if host_deleted:
        delete_host_count.inc()
        event = build_event(EventType.delete, host)
        insights_id = host.canonical_facts.get("insights_id")
        headers = message_headers(EventType.delete, insights_id)
        event_producer.write_event(event, str(host.id), headers, wait=True)
        delete_query.session.commit()
        return host_deleted
    else:
        delete_query.session.rollback()
        return host_deleted
```

2022-02-22 22:47 UTC, ryandillinfelton commented on lib/host_kafka.py
> +                if not errcode:
For clarity and to avoid any unlikely type coercion issues. Maybe also make 0 a constant in this file for more clarity. Then you could remove the comment

```suggestion
                if errcode == SUCCESS_CODE:
```

2022-02-22 22:47 UTC, ryandillinfelton commented on lib/host_kafka.py
> +        return _any_bootstrap_server_connects(kafka_socket, servers)
This goes along with the other comments in this review about changing how exceptions are handled. I think it would make sense to have the KafkaError raised here instead of where this is called. Then callers can chose to handle the exception as they see fit.

```suggestion
def kafka_available(servers=None):
    with closing(socket.socket(socket.AF_INET, socket.SOCK_STREAM)) as kafka_socket:
        if not _any_bootstrap_server_connects(kafka_socket, servers):
            raise KafkaError("No Kafka server available")
```

2022-02-22 22:47 UTC, ryandillinfelton commented on lib/host_delete.py
> +                    host_deleted = _delete_host(select_query.session, event_producer, host)
The KafkaError should be handled here to stop deletion if Kafka stops being available during a bulk deletion 

```suggestion
               try:
                   host_deleted = _delete_host(select_query.session, event_producer, host)
               except KafkaError:
                   logger.error("KafkaError: Stopping bulk deletion")
                   raise
```

2022-02-22 22:47 UTC, ryandillinfelton commented on tests/test_unit.py
> +        host_kafka._any_bootstrap_server_connects.assert_called_once_with(ANY, kafka_servers)
As is `kafka_available` just returns whatever `_any_bootstrap_server_connects` returns. Since `_any_bootstrap_server_connects` is mocked these tests aren't very useful.

2022-02-22 22:47 UTC, ryandillinfelton commented on lib/host_kafka.py
> +        logger.error(f"No servers available: {str(ve)}")
Where would the value error come from?

This looks to me like this should just return false if the for loop ends without returning true. Am I missing something?

2022-02-23 00:23 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    assert event_producer._kafka_producer.send.call_count == 0
When there is a Kafka error, no hosts are deleted and no events are generated.

2022-02-23 15:33 UTC, thearifismail commented on api/host.py
>          flask.abort(503)
Done!

2022-02-23 17:00 UTC, thearifismail commented on lib/host_kafka.py
> +                if not errcode:
Now using `errcode == 0`

2022-02-23 21:16 UTC, thearifismail commented on lib/host_delete.py
> +        raise KafkaError("Kafka server not available.  Stopping host deletions.")
> I don't think that the code currently will stop _attempting_ to delete hosts when this error is raised. There is no exception handling done in the `delete_hosts` loop, so it will continue running and raising these exceptions.
> 
> I think this exception handling and structure need work. There's more nesting than needed, making it the responsibility of callers to raise the correct error when kafka can't be reached is error prone, and the exception you're raising is not being caught or acted upon.
> 
> I think you should instead check if Kafka is available first and if it's not re-raise the exception and return early.

The current state of implementation is the result of review comments from the team.  The first implementation was to check for Kafka availability before starting the deletion.  If Kafka was inaccessible, don't start deleting hosts.  Then Chris K pointed out what if Kakfa disappeared after some hosts got delete but not all, which was a valid point.

When the first KafkaError is raised for the lack of Kafka availability, exception is caught by the caller in "api.host.py::delete*"

2022-02-23 21:21 UTC, thearifismail commented on lib/host_delete.py
> +                    host_deleted = _delete_host(select_query.session, event_producer, host)
The KafkaError is handled by the caller in `api.host`

2022-02-23 21:23 UTC, thearifismail commented on tests/test_unit.py
> +        host_kafka._any_bootstrap_server_connects.assert_called_once_with(ANY, kafka_servers)
This is a unit test.  Relying on QE to run integration tests against it.

2022-02-23 21:25 UTC, thearifismail commented on lib/host_kafka.py
> +        logger.error(f"No servers available: {str(ve)}")
`ValueError` is returned when a bogus kakfa server is provided.

2022-02-24 23:41 UTC, ryandillinfelton requested changes

2022-02-24 23:41 UTC, ryandillinfelton commented on tests/test_unit.py
> +        host_kafka._any_bootstrap_server_connects.assert_called_once_with(ANY, kafka_servers)
I just don't see what logic is being tested here. You're mocking the return value of `_any_bootstrap_server_connects` then checking the results of a call to `kafka_available` which just returns whatever `_any_bootstrap_server_connects` returns. No matter what values are provided for `kafka_servers` the test still passes.

Since `_any_bootstrap_server_connects` is entirely mocked I can replace it's whole body with pass and the tests still show no issues, and since no tests cover it's functionality the whole test suite still passes.

```
def _any_bootstrap_server_connects(kafka_socket, servers) -> bool:
    pass

def kafka_available(servers=None):
    with closing(socket.socket(socket.AF_INET, socket.SOCK_STREAM)) as kafka_socket:
        return _any_bootstrap_server_connects(kafka_socket, servers)
```

Since the core logic we're concerned with verifying lives in `_any_bootstrap_server_connects` we should make sure that the tests cover it. I understand a unit test should be focusing on one unit, but in this case `kafka_available` is basically just a context wrapper so I think it makes sense to test it and it's helper function in the same set of tests. You don't even need to mock anything since kafka does run during the tests and these are just verifying the handling of good/bad server addresses.

These all worked for me. And now if I effect how server addresses are verified they fail.
```
class KafkaAvailabilityTests(TestCase):
    def setUp(self,):
        super().setUp()
        self.config = Config(RuntimeEnvironment.TEST)

    def test_happy_path(self):
        assert host_kafka.kafka_available()

    def test_valid_server(self):
        assert host_kafka.kafka_available([self.config.bootstrap_servers])

    def test_list_of_valid_servers(self):
        kafka_servers = ["127.0.0.1:29092", "localhost:29092"]
        assert host_kafka.kafka_available(kafka_servers)

    def test_list_with_first_bad_second_good_server(self):
        kafka_servers = ["localhost29092", "127.0.0.1:29092"]
        assert host_kafka.kafka_available(kafka_servers)

    # second bad with missing ':'.  Returns as soon as the first kafka server found.
    def test_list_with_first_good_second_bad_server(self):
        kafka_servers = ["127.0.0.1:29092", "localhost29092"]
        assert host_kafka.kafka_available(kafka_servers)

    def test_one_invalid_bootstrap_server(self):
        kafka_servers = ["localhost29092"]
        assert host_kafka.kafka_available(kafka_servers) is None
```

2022-02-24 23:41 UTC, ryandillinfelton commented on lib/host_kafka.py
> +        logger.error(f"No servers available: {str(ve)}")
In my testing I wasn't able to get this log to show up. What conditions would cause it and how are they different than those that get caught by the invalid server address except?
```
except ValueError as ve:
                logger.error(f"Invalid server address: {str(ve)}")

2022-02-24 23:41 UTC, ryandillinfelton commented on lib/host_delete.py
> +        raise KafkaError("Kafka server not available.  Stopping host deletions.")
Gotcha, the raise stops the loop the function is called in. I thought you had to re-raise the exception for some reason.

I do think we could make this less nested though.
 
```suggestion
    if not kafka_available():
        logger.error(f"host with {host.id} NOT deleted because Kafka server not available.")
        raise KafkaError("Kafka server not available.  Stopping host deletions.")
    
    delete_query.delete(synchronize_session="fetch")
    host_deleted = _deleted_by_this_query(host)
    
    if not host_deleted:
        delete_query.session.rollback()
        return host_deleted

    delete_host_count.inc()
    event = build_event(EventType.delete, host)
    insights_id = host.canonical_facts.get("insights_id")
    headers = message_headers(EventType.delete, insights_id)
    event_producer.write_event(event, str(host.id), headers, wait=True)
    delete_query.session.commit()
    return host_deleted
```

2022-02-25 17:28 UTC, thearifismail reviewed
@ryandillinfelton please look at the responses.

2022-02-25 17:28 UTC, thearifismail commented on tests/test_unit.py
> +        host_kafka._any_bootstrap_server_connects.assert_called_once_with(ANY, kafka_servers)
> Mocking is needed because pr_check runs in a standalone container with no Kafka available.  At this time, only DB is available but not sure if DB runs in the same container or has access to one.  In the past, kafka_availibility was not checked so mocking needs was not felt.

Working on how to verify failures.

2022-02-25 17:28 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> -@pytest.mark.parametrize(
This test is not needed any more and fails due to changes in code.

2022-02-25 17:28 UTC, thearifismail commented on tests/test_unit.py
> +class KafkaAvailabilityTests(TestCase):
When Kafka not available None is returned and an exception thrown this func caller and the raised exception is caught by the caller in API code.

2022-02-26 00:07 UTC, thearifismail reviewed
@ryandillinfelton, now connect_ex wrapper is used for patching

2022-02-26 00:07 UTC, thearifismail commented on lib/host_kafka.py
> +        logger.error(f"No servers available: {str(ve)}")
if a bogus host without `:` is used to get ValueError.

2022-03-08 17:24 UTC, kruai commented on lib/host_kafka.py
> +        logger.error(f"No servers available: {str(ve)}")
Correct, but that gets caught by the `except ValueError as ve:` on line 32. At that point, the error is handled, and does not get reraised in order to be caught on line 38. Is that what you mean @ryandillinfelton ?

2022-03-08 17:31 UTC, kruai requested changes
Requesting a few more changes, mostly typos. But there are also still some threads that remain unresolved

2022-03-08 17:31 UTC, kruai commented on tests/test_culling.py
> +        facke_event_producer,
```suggestion
        fake_event_producer,
```

2022-03-08 17:31 UTC, kruai commented on tests/test_culling.py
> +    assert facke_event_producer.write_event.call_count == 2
```suggestion
    assert fake_event_producer.write_event.call_count == 2
```

2022-03-08 17:31 UTC, kruai commented on tests/test_api_hosts_delete.py
> -@pytest.mark.parametrize(
Can you explain your reasoning? I think it's valuable to know that a delete operation is aborted properly when the producer errors out

2022-03-08 20:38 UTC, thearifismail commented on tests/test_culling.py
> +    facke_event_producer = mock.Mock()
Fixed.

2022-03-08 20:39 UTC, thearifismail commented on tests/test_culling.py
> +        facke_event_producer,
Fixed.

2022-03-08 20:39 UTC, thearifismail commented on tests/test_culling.py
> +    assert facke_event_producer.write_event.call_count == 2
fixed.

2022-03-08 20:40 UTC, thearifismail commented on tests/test_culling.py
> +    event_producer_mock, db_create_host_in_unknown_state, db_get_host, inventory_config, db_create_host
Left over; should've been removed.

2022-03-08 21:13 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> -@pytest.mark.parametrize(
I don't understand the comment.  Is the comment placed?  Irregardless of this comment, this test has not been modified by this PR.

2022-03-08 21:46 UTC, thearifismail reviewed
responded to Asa's comments.

2022-03-08 21:49 UTC, thearifismail commented on lib/host_delete.py
> +        raise KafkaError("Kafka server not available.  Stopping host deletions.")
This suggestion has been implemented.

2022-03-09 17:41 UTC, kruai commented on tests/test_unit.py
> +class KafkaAvailabilityTests(TestCase):
Based on our conversation earlier, this was resolved.

2022-03-09 17:41 UTC, kruai approved these changes

2022-03-09 17:46 UTC, ryandillinfelton approved these changes
LGTM! Thanks for being such a good sport about the review process! I know these ones that go on for a long time are exhausting.

2022-03-09 23:35 UTC, merged

2022-03-17 11:41 UTC, RonnyPfannschmidt commented on api/host.py
> +    if len(ids_list) == 0:
this broke a qe test, i think we should change it back

2022-03-17 11:41 UTC, RonnyPfannschmidt commented on api/host.py
> +    if len(ids_list) == 0:
(removal of the message that is)