Enable deleting all hosts using cautionary args
RedHatInsights/insights-host-inventory pull request #1070
Opened 2022-01-17 22:13 UTC by thearifismail

# Overview

This PR is being created to address [ESSNTL-1967](https://issues.redhat.com/browse/ESSNTL-1967).
(A description of your PR's changes, along with why/context to the PR, goes here.)

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [x] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [x] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2022-01-18 13:25 UTC, thearifismail commented
/retest

2022-01-18 13:45 UTC, thearifismail commented
/retest

2022-01-18 14:12 UTC, thearifismail commented
/retest

2022-01-18 14:24 UTC, thearifismail commented
/retest

2022-01-18 15:15 UTC, thearifismail commented
/retest

2022-01-18 16:04 UTC, fijshion commented
/retest

2022-01-18 16:36 UTC, fijshion commented
/retest

2022-01-18 19:58 UTC, ryandillinfelton commented
This seems quite safe, but I can't help but feel it may be more safe to make a separate delete_all endpoint.
Maybe
`/api/delete/all` 
or
`/api/delete-all/`
for even more separation. I would still support a confirmation parameter.

One reason is, with how destructive the action is, I think the more idiot-proof we can make it the better. Having it be an entirely separate endpoint exclusively for deleting everything makes me feel safer. No need to ever touch it at all if I don't want all my hosts gone.

Another is that syntactically I think it's a bit weird. The query parameter isn't modifying the action, it's asking for a different (admittedly similar) action. As a result the possible query parameters interact is odd ways. For example:
`/api/delete?providerId={some_id}&delete_all=true&confirm=true`
is valid, but the filter is irrelevant.

I also worry someone might think they need to add `delete_all` to have all the hosts selected by their query deleted, or that they must always attach `confirm` to their query as if it's a protection for any delete, not just `delete_all` which would reduce it's effectiveness. I think the latter point could be avoided by renaming it to `confirm_delete_all` to be more explicit about what it's confirming.

My personal preference is for `api/delete-all?confirm_delete_all=true` as it seems the safest, and avoids syntactic weirdness since the only possible query parameter would be the confirmation. Then the `/delete` endpoint would be reserved for deleting hosts through filters, while `delete/all` or `/delete-all` would be reserved for clearing all the hosts from an account. `confirm` would also be acceptable in this case, but I'm all for making this as cumbersome and explicit as possible a la typing the whole repo name when deleting a repo on github.

2022-01-19 00:46 UTC, thearifismail commented
/retest

2022-01-19 15:13 UTC, kruai commented
> This seems quite safe, but I can't help but feel it may be more safe to make a separate delete_all endpoint. Maybe `/api/delete/all` or `/api/delete-all/` for even more separation. I would still support a confirmation parameter.
> 
> One reason is, with how destructive the action is, I think the more idiot-proof we can make it the better. Having it be an entirely separate endpoint exclusively for deleting everything makes me feel safer. No need to ever touch it at all if I don't want all my hosts gone.
> 
> Another is that syntactically I think it's a bit weird. The query parameter isn't modifying the action, it's asking for a different (admittedly similar) action. As a result the possible query parameters interact is odd ways. For example: `/api/delete?providerId={some_id}&delete_all=true&confirm=true` is valid, but the filter is irrelevant.
> 
> I also worry someone might think they need to add `delete_all` to have all the hosts selected by their query deleted, or that they must always attach `confirm` to their query as if it's a protection for any delete, not just `delete_all` which would reduce it's effectiveness. I think the latter point could be avoided by renaming it to `confirm_delete_all` to be more explicit about what it's confirming.
> 
> My personal preference is for `api/delete-all?confirm_delete_all=true` as it seems the safest, and avoids syntactic weirdness since the only possible query parameter would be the confirmation. Then the `/delete` endpoint would be reserved for deleting hosts through filters, while `delete/all` or `/delete-all` would be reserved for clearing all the hosts from an account. `confirm` would also be acceptable in this case, but I'm all for making this as cumbersome and explicit as possible a la typing the whole repo name when deleting a repo on github.

These are valid points. I'd prefer not to add yet another DELETE `/hosts` endpoint, but I do completely understand your concern... Here are my thoughts on these approaches, for what they're worth.

If we stick with having one DELETE endpoint:
- We could raise an exception if both a filter and `delete_all` are provided
- In addition to the requirements we've already discussed, I think having very clear descriptions for these params in our API spec should be sufficient idiot-proofing for developers poking around on the API. The average user will be deleting from the UI, which will not be able to make this mistake.

If we make a separate DELETE endpoint:
- Since the current endpoint is DELETE `/hosts/{host_id_list}`, I'd prefer the new endpoint to at least follow our established pattern and be something like DELETE `/hosts/all?confirm_delete_all=true`

2022-01-21 14:22 UTC, thearifismail commented
Though, I was in favor of creating a new endpoint for deleting all hosts, @kruai argument is persuasive.  It is simpler than adding a new endpoint.  I am leaning toward raising an exception when `delete_all` is used with an other filter.  The second point in Asa's response to Ryan is already in place

2022-01-26 16:04 UTC, kruai requested changes

2022-01-26 20:33 UTC, thearifismail commented on api/host.py
> +def _validate_filter(**kwargs):
renamed the function to `_delete_all_hosts_filter()`

2022-01-26 20:36 UTC, thearifismail commented on api/host.py
> +    ):
Using `args = locals()`, causes test failures, which I think puts `staleness` into action.  Using locals() should wait until after staleness defaults have been removed.

2022-01-26 20:39 UTC, thearifismail commented on swagger/api.spec.yaml
> +      description: The Confirm option provided for additional caution
Updated the description to this suggestion.

2022-01-26 20:42 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +        ind += 1
updated

2022-01-26 20:53 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    assert "Deleting every host requires delete_all=true&confirm=true" in response_data["detail"]
parametrize the filter to use confirm and delete_all

2022-01-26 21:06 UTC, thearifismail commented on tests/test_xjoin.py
> +    graphql_query_empty_response.assert_called_once_with(HOST_IDS_QUERY, {"filter": (mocker.ANY)}, mocker.ANY)
Thanks to the default values for staleness `mocker.ANY` is needed.  Will fix updated when `args = locals()` will be added.

2022-02-01 15:43 UTC, thearifismail commented
This PR work is covered by https://github.com/RedHatInsights/insights-host-inventory/pull/1082

2022-02-01 15:43 UTC, closed without merging