Only allow [contains] operand on array fields [ESSNTL-2069]
RedHatInsights/insights-host-inventory pull request #1078
Opened 2022-01-25 21:01 UTC by ryandillinfelton

# Overview

This PR is being created to address [ESSNTL-2069](https://issues.redhat.com/browse/ESSNTL-2069).

This PR makes it so [contains] is no longer considered a valid operand on non-array string fields. This was considered misleading because the [contains] operand is intended to be used on array fields to filter on if those fields contain a specific string, so using it on a single string (though functionally equivalent to [eq]) doesn't make much sense. 

I also extended [contains] support to wildcard string. There are currently no wildcard string arrays in the spec, so it's basically untested, but because elasticsearch, and by extention xjoin-search don't differentiate between arrays and singular values it should be fine. The output for both (the query sent to xjoin) is unchanged, we've only changed the API interface for clarity.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2022-01-26 16:25 UTC, kruai requested changes

2022-01-26 16:25 UTC, kruai commented on api/filtering/filtering_common.py
> +    "operating_system": OPERATION_SETS.range.value,
Before this change, `SPEC_OPERATIONS_LOOKUP` would always return an array of Strings. Now, the `string`, `wildcard`, and `boolean` keys return a plain String. Can we keep it consistent?

2022-01-26 16:25 UTC, kruai commented on api/filtering/filtering_common.py
>      "integer": OPERATION_SETS.eq.value[0],
Same thing here: `boolean`, `range`, and `integer` have String values, while everything else uses an array of Strings.

2022-01-26 16:25 UTC, kruai commented on app/__init__.py
> +                "is_array": _get_field_is_array(field, props),
Since `_get_field_is_array` is only used here, should it just be inline?
```suggestion
                "is_array": "array" == props["type"],
```

2022-01-26 20:15 UTC, ryandillinfelton commented
@kruai I made the changes you suggested

2022-01-27 20:47 UTC, kruai approved these changes

2022-01-27 22:23 UTC, merged