Delete all hosts using a separate API endpoint.
RedHatInsights/insights-host-inventory pull request #1082
Opened 2022-02-01 15:25 UTC by thearifismail

# Overview

This PR is being created to address ESSNTL-1967.
It adds a new API endpoint `/hosts/delete_all_hosts` which requires two parameters `delete_all=true` and `confirm_delete_all=true`.  Requiring two input parameters to delete all hosts is an extra caution to avoid any unintended use.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [x] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [x] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2022-02-01 16:32 UTC, kruai requested changes
Looks mostly good. Just a couple points

2022-02-01 16:32 UTC, kruai commented on tests/test_api_hosts_delete.py
> +    assert '"type": "delete"' in event_producer_mock.event
It would also be good to verify that the event producer was used the correct number of times, since the above only tells you that at least one "delete" event was written. As we expect all of the hosts you created to be deleted, it would look something like this:
```suggestion
    assert '"type": "delete"' in event_producer_mock.event
    assert event_producer_mock.write_event.call_count == len(created_hosts)
```

2022-02-01 16:32 UTC, kruai commented on tests/test_api_hosts_delete.py
> +    assert len(new_hosts) == remaining_hosts.count()
This is invalid - there should be no hosts remaining.

2022-02-01 16:36 UTC, ryandillinfelton requested changes

2022-02-01 16:36 UTC, ryandillinfelton commented on tests/test_xjoin.py
> +    graphql_query_empty_response.assert_called_once_with(HOST_IDS_QUERY, {"filter": (mocker.ANY)}, mocker.ANY)
Doesn't using any make the test ineffective? If anything could be in filter, then it could be adding filters that would prevent it from selecting all hosts.

2022-02-01 16:36 UTC, ryandillinfelton commented on swagger/api.spec.yaml
> +  /hosts/delete_all_hosts:
I think `/hosts/all` would look a cleaner.

2022-02-01 16:36 UTC, ryandillinfelton commented on api/host.py
> +        flask.abort(400, "Deleting all hosts requires delete_all=true and confirm_delete_all=true.")
I don't think it's really necessary to have two separate errors for sending none and sending one.
```suggestion
    if not all([delete_all, confirm_delete_all]):
        logger.error("To delete all hosts, provide delete_all=true and confirm_delete_all=true in the request.")
        flask.abort(400, "To delete all hosts, provide delete_all=true and confirm_delete_all=true in the request.")
```

2022-02-01 16:36 UTC, ryandillinfelton commented on api/host.py
> +    return flask_json_response(json_data, status.HTTP_202_ACCEPTED)
Did we decide to keep going with the 202 transition?

2022-02-01 16:42 UTC, thearifismail commented on swagger/api.spec.yaml
> +  /hosts/delete_all_hosts:
IMO, `/hosts/all` hides the only intent of this endpoint.  That's why `delete_all_hosts` is better.

2022-02-01 16:43 UTC, thearifismail commented on api/host.py
> +    return flask_json_response(json_data, status.HTTP_202_ACCEPTED)
I fretted about it and forgo to check with you guys

2022-02-01 17:32 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    new_ids = [str(host.id) for host in new_hosts]
Thanks to copy/paste; removed.  The source had it to check for unintended deletion.

2022-02-01 17:50 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    assert '"type": "delete"' in event_producer_mock.event
the `event_producer_mock` does not have `call_count` for the write event but the `delete count` is available in response data; so using `assert response_data.get('hosts_deleted') == len(created_hosts)`

2022-02-01 17:53 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    assert len(new_hosts) == remaining_hosts.count()
Gone!

2022-02-01 17:59 UTC, thearifismail commented on tests/test_xjoin.py
> +    graphql_query_empty_response.assert_called_once_with(HOST_IDS_QUERY, {"filter": (mocker.ANY)}, mocker.ANY)
Now the code uses an `empty filter` using `{"filter": ()}`

2022-02-01 19:59 UTC, ryandillinfelton commented on api/host.py
> +    return flask_json_response(json_data, status.HTTP_202_ACCEPTED)
I'm still a bit mixed on it, but It does seem like an outlier in terms of scale so that make sit feel less incongruous

2022-02-01 20:13 UTC, ryandillinfelton commented on api/host.py
> +        flask.abort(400, "Deleting all hosts requires delete_all=true and confirm_delete_all=true.")
Yes. I'm suggesting we just return one error message if both or either is missing, and `if not all([delete_all, confirm_delete_all])` will cover all of those cases.

Also, do we really need the `delete_all_hosts=true` parameter if that's the sole purpose of the endpoint? I'm still all for requiring confirmation, but I think `confirm=true` is enough. Originally we only had `delete_all_hosts` to tell the api what we were trying to do since it was part of the filtered host delete endpoint but it feels superfluous here.

2022-02-01 20:15 UTC, ryandillinfelton commented on swagger/api.spec.yaml
> +  /hosts/delete_all_hosts:
I think since it's sent with a DELETE verb it's clear.
In relation to other endpoints that support the DELETE verb it's
`DELETE hosts?{filters}`
`DELETE hosts/{host_id_list}`
`DELETE hosts/all`
I think, especially with context, it's clear that the endpoint deletes all hosts

2022-02-01 20:27 UTC, thearifismail commented on swagger/api.spec.yaml
> +  /hosts/delete_all_hosts:
It is not a vanity issue but a willful intent to make it hard to delete all hosts.  That's why I would like to leave it as is.

2022-02-01 20:49 UTC, thearifismail commented on api/host.py
> +        flask.abort(400, "Deleting all hosts requires delete_all=true and confirm_delete_all=true.")
Yes, earlier missed `all`.  Changed it to use `if not all([delete_all, confirm_delete_all]):`

2022-02-01 20:52 UTC, thearifismail commented on api/host.py
> +    return flask_json_response(json_data, status.HTTP_202_ACCEPTED)
let's leave it to `202` because deleting filtered hosts also returns `202`.

2022-02-01 20:53 UTC, thearifismail commented on api/host.py
> +    return flask_json_response(json_data, status.HTTP_202_ACCEPTED)
If you insist, then I can change it using a separate PR with Asa's input.  It may require changing some tests also.

2022-02-02 13:25 UTC, kruai commented on api/host.py
> +    return flask_json_response(json_data, status.HTTP_202_ACCEPTED)
Pretty sure we decided to use 202 for update/delete endpoints going forward. We're not changing the existing ones because of the risk of breaking existing implementations

2022-02-02 13:30 UTC, kruai commented on swagger/api.spec.yaml
> +  /hosts/delete_all_hosts:
I'm for `DELETE /hosts/all` as well, fwiw... I don't think `DELETE /hosts/all` hides any intent at all, and in fact is pretty explicit. It is pretty redundant to do `DELETE /hosts/delete_all_hosts?delete_all=true&confirm_delete_all=true`.

2022-02-02 14:03 UTC, ryandillinfelton requested changes

2022-02-02 15:56 UTC, kruai commented on tests/test_api_hosts_delete.py
> +    assert '"type": "delete"' in event_producer_mock.event
Ah, you're right... you'd need to do `mocker.patch.object(event_producer_mock, "write_event")` before calling the endpoint, but then you wouldn't be able to check the value of `event`. In that case, I'm resolving this, and we can deal with `write_event` counts in the Kafka PR

2022-02-02 16:05 UTC, thearifismail commented on api/host.py
> +        ids_list = get_host_ids_list_xjoin(None, None, None, None, None, None, None, None, None, {})
Since the issue has to be addressed on the `xjoin-search` side, I have removed the use of limit which I inserted for debugging.  So pagination is not an issue.  Reaper gets hosts using DB query and bypasses xjoin altogether. 

Questions:

1.  Should deleting all hosts bypass xjoin and get hosts list from the DB directly?
2.  Should inventory show the total number of hosts and the number of hosts deleted?
3.  Should the inventory code iterate over until all hosts are deleted?
4.  Should this PR be delivered with the current behavior?  The design and behavior short comings be discussed and addressed in a separate PR?

2022-02-02 16:09 UTC, thearifismail reviewed
@kruai @ryandillinfelton the endpoint has been changed to `hosts/all`.  Please look at the response about limit use.

2022-02-02 16:17 UTC, thearifismail commented on api/host_query_xjoin.py
> +    variables = {"filter": all_filters, "limit": 100}  # max limit 100 allowed by xjoin-search
removed limit altogether.  I had added for investigation purpose.

2022-02-02 18:16 UTC, kruai commented on api/host.py
> +        ids_list = get_host_ids_list_xjoin(None, None, None, None, None, None, None, None, None, {})
My thoughts:

1. Good point... now that it's a separate endpoint, that would make more sense. 
2. It would make sense to return the total number of hosts deleted in the API response.
3. Not sure I understand, but since we have to write an event for each host we delete, we must iterate by necessity.
4. I think we can save the above for a follow-up PR so as not to block the Prod deploy. We'll likely need to prioritize pagination, though, as @ryandillinfelton brings up a good point... that would need to be implemented for both bulk-delete endpoints.

2022-02-02 18:49 UTC, thearifismail commented on api/host.py
> +        ids_list = get_host_ids_list_xjoin(None, None, None, None, None, None, None, None, None, {})
> 3\. Not sure I understand, but since we have to write an event for each host we delete, we must iterate by necessity.

The iteration IS done but is limited to the number of hosts returned.  Though `xjoin-search` query does return the `total` number of hosts, it is not used to keep track.  Inventory code needs an update to track of the total number of hosts available and how many have been deleted.  Then API caller function, like "delete_all_hosts()"  can keep track of total vs deleted and keep iterating until all available have been deleted.  That said, bypassing "xjoin-search" and query DB sounds simple.

2022-02-02 19:52 UTC, kruai commented on api/host.py
> +        ids_list = get_host_ids_list_xjoin(None, None, None, None, None, None, None, None, None, {})
I don't think returning the number of deleted hosts is required to merge this, but it wouldn't hurt either.

2022-02-02 22:47 UTC, ryandillinfelton requested changes

2022-02-02 22:47 UTC, ryandillinfelton commented on api/host.py
> +    delete_count = _delete_filtered_hosts(ids_list)
Why make two calls to the database rather than just using a single delete expression and letting the database handle it?
We should be able to essentially send `DELETE FROM hosts WHERE account_number={account_number}` since we're just deleting every host on an account.

2022-02-02 22:47 UTC, ryandillinfelton commented on swagger/openapi.json
> +      },
I mentioned this in another thread on this PR but I don't think I got a conclusive answer. I don't think we really need the delete_all_hosts=true parameter. It made sense when it was an option on the more general bulk delete endpoint, but now that deleting all is the sole purpose of the endpoint it feels redundant. I'm still all for requiring confirmation, but I think `confirm_delete_all=true` is enough.

2022-02-02 23:40 UTC, thearifismail commented on api/host.py
> +    delete_count = _delete_filtered_hosts(ids_list)
I myself realized that two DB calls but the first one is very quick and the second one `_delete_filtered_hosts(ids_list)` deletes one host at a time and generates events which lead to synching of host-inventory with `xjoin-search` index and synching with other databases.  Furthermore, `delete_all_hosts` is expected to get used seldom.  There making two calls should not be an issue.

2022-02-03 14:04 UTC, ryandillinfelton commented on api/host.py
> +    delete_count = _delete_filtered_hosts(ids_list)
I see, I completely overlooked needing to publish events about those deletes. I think it's acceptable, 2 DB calls really isn't that expensive.

2022-02-03 14:06 UTC, ryandillinfelton commented on swagger/openapi.json
> +      },
@thearifismail @kruai thoughts on this? I'm ultimately okay with either but I'd prefer to simplify to just one.

2022-02-03 14:14 UTC, kruai commented on swagger/openapi.json
> +      },
I agree with this. When we originally planned on using 1 endpoint, we wanted 2 booleans:

- 1 to specify that we wanted to delete *all* hosts instead of providing a filter
- 1 to confirm that you want to do that

Now that we're splitting it into 2 endpoints, I think choosing to use the `DELETE /hosts/all` endpoint replaces the first boolean; using one confirmation boolean on a dedicated endpoint should suffice IMO.

2022-02-03 15:09 UTC, kruai commented on api/host.py
> +    delete_count = _delete_filtered_hosts(ids_list)
Yeah, I agree that it's fine here.

2022-02-03 15:31 UTC, thearifismail commented on swagger/openapi.json
> +      },
`delete_all` gone!  Just pushed the update

2022-02-03 15:35 UTC, thearifismail commented
/retest

2022-02-03 15:40 UTC, ryandillinfelton requested changes
Just found one little isue

2022-02-03 15:40 UTC, ryandillinfelton commented on api/host.py
> +def delete_all_hosts(delete_all=None, confirm_delete_all=None):
```suggestion
def delete_all_hosts(confirm_delete_all=None):
```

2022-02-03 16:00 UTC, thearifismail commented on api/host.py
> +def delete_all_hosts(delete_all=None, confirm_delete_all=None):
Thanks.  Fixed.

2022-02-03 17:12 UTC, ryandillinfelton approved these changes
LGTM

2022-02-03 19:25 UTC, kruai approved these changes

2022-02-03 19:25 UTC, kruai commented on api/host_query_db.py
> +    ids_list = [str(host.id) for host in query_results]
My only concern with this approach is that `query_results` will become much larger than it needs to be; optimally, we'd want to query just the IDs instead of the entire hosts. But, that needn't block this PR if people do not agree.

2022-02-03 20:16 UTC, thearifismail commented
Created https://issues.redhat.com/browse/ESSNTL-2197 for fetching just host IDs

2022-02-03 20:17 UTC, thearifismail commented
/retest

2022-02-03 20:40 UTC, merged