Support new filter combinations
RedHatInsights/insights-host-inventory pull request #1085
Opened 2022-02-02 17:29 UTC by kruai

# Overview

This PR is being created to address [ESSNTL-2172](https://issues.redhat.com/browse/ESSNTL-2172).
Until now, we haven't allowed the user to filter on more than 1 of the following:

- fqdn
- display_name
- hostname_or_id
- insights_id

This was likely due to the front-end never sending one of these at a time. However, it makes sense that we'd need to allow for combinations of these, as users/apps can use our API directly. This PR updates our filter logic to account for these scenarios, and modifies one of the xjoin tests to validate the new expected output.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2022-02-02 18:33 UTC, thearifismail reviewed
see comments

2022-02-02 18:33 UTC, thearifismail commented on tests/test_xjoin.py
> +        (("OR", "insights_id"), f"hostname_or_id={quote(generate_uuid())}&insights_id={quote(generate_uuid())}"),
I don't fully understand the xjoin-search filtering mechanism.  Why `AND` filter has not been included?

2022-02-02 18:37 UTC, kruai commented on api/filtering/filtering.py
> +        query_filters += ({"fqdn": {"eq": fqdn.casefold()}},)
That's what I was asking in my post on Slack - I can't think of a reason we'd restrict it to only one. We likely never considered it because the UI only sends one of these at a time, but I don't see why it should be off-limits

2022-02-02 18:39 UTC, kruai commented on api/filtering/filtering.py
> +    if insights_id:
The order does not matter if we implement it in the way I'm suggesting, no. I don't get your point about `ELEVATED_CANONICAL_FACTS`, though; those fields are given special consideration during matching/deduplication, not filtering

2022-02-02 18:45 UTC, kruai commented on tests/test_xjoin.py
> +        (("OR", "insights_id"), f"hostname_or_id={quote(generate_uuid())}&insights_id={quote(generate_uuid())}"),
When filtering on `hostname_or_id`, the root of the query filter becomes "OR", as in:
```
OR: [
  { display_name: "foo" },
  { fqdn: "bar }
]
```

`AND` isn't included in the test because the filtering function we're testing doesn't use it.

2022-02-02 18:48 UTC, kruai commented on tests/test_xjoin.py
> +    mocked_filter += (mocker.ANY,)
If you mean the `mocker.ANY` on line 337, it's because we're generating random values we don't care about, and I'm keeping consistency from the original test. The goal of the test was originally to determine the priority of these fields; I've changed the test so that it verifies that the fields are all used in the xjoin filter.

If you mean the `mocker.ANY` on line 339, that's the `mocker.ANY` I moved from the assertion section. That's used because there are timestamps there whose value we don't care about.

2022-02-02 18:52 UTC, thearifismail commented on api/filtering/filtering.py
> +        query_filters += ({"fqdn": {"eq": fqdn.casefold()}},)
I asked because it was such an obvious disparity and thought there could be some genuine reason.  I am okay with this change.

2022-02-02 19:00 UTC, thearifismail commented on tests/test_xjoin.py
> +        (("OR", "insights_id"), f"hostname_or_id={quote(generate_uuid())}&insights_id={quote(generate_uuid())}"),
Yes, I saw hostname_or_id uses OR but the question popped about AND.  Sounds good.

2022-02-02 19:10 UTC, thearifismail approved these changes
LGTM

2022-02-02 19:10 UTC, thearifismail commented on tests/test_xjoin.py
> +    mocked_filter += (mocker.ANY,)
Yes, I saw random value being used but thought it should check the filter had used the randomly generated value for fidelity.  My question was for line 337.  
This is Good.

2022-02-02 20:56 UTC, ryandillinfelton requested changes
I don't know that we should address this bug by allowing all of these filters to be used together. I don't thinks there is a use case here. `fqdn`, `hostname`, `id`, and `display_name` are all fields which should be unique to a host. I don't see why I would want to select a single host using its `fqdn` and `display_name` rather than either one individually. I think that we should instead check if more than one of the mutually exclusive fields is passed as a filter query and return an error if they are.

2022-02-02 20:56 UTC, ryandillinfelton commented on api/filtering/filtering.py
>          hostname_or_id_filters = ({"display_name": contains_lc}, {"fqdn": contains_lc})
If a user sends a request with both `fqdn` and `hostname_or_id` defined fqdn will be defined twice and almost certainly return no hosts. The same if they send `display_name` and `hostname_or_id`. `display_name` ends up defined twice.

2022-02-02 22:26 UTC, kruai commented on api/filtering/filtering.py
>          hostname_or_id_filters = ({"display_name": contains_lc}, {"fqdn": contains_lc})
Good call. I don't really have a preference how we handle this situation, so I just pushed an update that raises an exception in those situations instead.

2022-02-02 22:33 UTC, ryandillinfelton approved these changes
LGTM. For the record this doe snot mean we will never allow all of the id fields to be used at the same time. But I think this solves the issue of some fields being ignored causing unexpected results rather simply.

2022-02-03 14:56 UTC, thearifismail approved these changes
LGTM

2022-02-03 15:21 UTC, merged