[WIP] Fix problem with os version range operation
RedHatInsights/insights-host-inventory pull request #1096
Opened 2022-02-16 16:57 UTC by thearifismail

# Overview

This PR is being created to address [ESSNTL-2138](https://issues.redhat.com/browse/ESSNTL-2138).  The fix is to handle None for OS minor version.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [x] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2022-02-16 20:23 UTC, ryandillinfelton requested changes
The functionality is technically correct, but there is a bug in the query generation causing it to create an over complicated query. I've suggested a way to fix the bug and reduce the complexity of the generation function.

2022-02-16 20:23 UTC, ryandillinfelton commented on api/filtering/custom_filters.py
> +            os_filter = _build_major_equality_filter(major, minor, name, operation)
The branching on operation type is unnecessary, both branches do the same thing. We can just short circuit if the minor version is missing and leave the rest of the logic the same. I chose to inline the function calls since they are only used in one place.
```suggestion
    if minor is None:
        return {"spf_operating_system": {"major": {operation: major}, "name": {"eq": name}}}

    os_filter = {"spf_operating_system": {"major": {"eq": major}, "minor": {operation: minor}, "name": {"eq": name}}}
```

2022-02-16 20:23 UTC, ryandillinfelton commented on api/filtering/custom_filters.py
> +        # For 'gte' and 'lte', the 'eq' check handled in the previous block.
If you commit the suggestion in my other comment this should be removed since that block would be gone.

2022-02-16 22:12 UTC, thearifismail commented on api/filtering/custom_filters.py
> +            os_filter = _build_major_equality_filter(major, minor, name, operation)
I knew this would be questioned immediately but left it in for clarity because it explicitly shows how each operator is getting filtered; makes the code easy to read for someone not too familiar.  That said, the code is update per the recommendation here.  The code compact but hides the filter building complexity.  IMO, the explicit code is easier to follow, but the change is here if you don't buy the explicit reasoning.

2022-02-21 19:53 UTC, kruai commented on api/filtering/custom_filters.py
> +            os_filter = _build_major_equality_filter(major, minor, name, operation)
Personally, I think the longer and more explicit version is harder to read and understand, because it creates a logical split where both branches do the same thing

2022-02-21 20:52 UTC, kruai commented on api/filtering/custom_filters.py
> +
If this filter is used:
```
filter[system_profile][operating_system][RHEL][version][gte]=7
```
then this function would return:
```
{"spf_operating_system": {"major": {"gte": 7}, "name": {"eq": "RHEL"}}}
```
We used to only allow `eq`, `lt`, and `gt` on the major version. Have you checked whether these are allowed on the xjoin side?

2022-02-21 20:52 UTC, kruai commented on api/filtering/custom_filters.py
> -        # The major operation should only ever be 'lt' or 'gt'
This restriction still applies, doesn't it?

2022-02-21 21:08 UTC, thearifismail commented on api/filtering/custom_filters.py
> +
Yes `xjoin-search` has `gte` and `lte` implemented.  Thanks to major and minor version handled separately, this filter has to be split into `eq` and `lt`/`gt`

2022-02-21 21:08 UTC, thearifismail commented on api/filtering/custom_filters.py
> -        # The major operation should only ever be 'lt' or 'gt'
Yes it does.

2022-02-21 21:13 UTC, thearifismail commented on tests/test_xjoin.py
>                                  {"spf_operating_system": {"major": {"gt": 7}, "name": {"eq": "RHEL"}}},
Duplicate entry is not needed anymore due to the following code and has been removed:
```
    if minor is None:
        return {"spf_operating_system": {"major": {operation: major}, "name": {"eq": name}}}
```

2022-02-21 21:14 UTC, thearifismail commented on api/filtering/custom_filters.py
> +            os_filter = _build_major_equality_filter(major, minor, name, operation)
Ok

2022-02-21 22:42 UTC, kruai commented on api/filtering/custom_filters.py
> -        # The major operation should only ever be 'lt' or 'gt'
OK - why is the comment being removed, then?

2022-02-21 22:44 UTC, kruai commented on api/filtering/custom_filters.py
> +
OK. In that case, I have no issue with this

2022-02-21 23:58 UTC, thearifismail commented on api/filtering/custom_filters.py
> -        # The major operation should only ever be 'lt' or 'gt'
Since this code block gets used for `lte` and `gte`, I found this comment confusing.  It took me a while to realize that the prior `eq` were being used `lte` and `gte` also.  That's why I took it out.

2022-02-22 13:19 UTC, kruai commented on api/filtering/custom_filters.py
> -        # The major operation should only ever be 'lt' or 'gt'
Ah, maybe it needs an update to clarify it, then. It's just saying that the major operation should only ever be `lt` or `gt` when using an inequality on a major+minor version. So, it converts `lte` and `gte` by removing the third character (if any).

2022-02-22 18:30 UTC, ryandillinfelton commented on api/filtering/custom_filters.py
> -        # The major operation should only ever be 'lt' or 'gt'
Yeah I agree with Asa here. I added a comment originally because it's really weird to just remove the last letter of the string for seemingly no reason.
maybe this comment would be more clear
```
# This portion of the query is filtering only on major version to select all hosts with a major version greater
# or lesser than the target. If GTE or LTE were used in this portion it would return render the previous portion 
# of the query useless. To prevent this and get the desired behavior we use a sub-string of the first two characters
# of the supplied operation so that the major operation is always "gt" or "lt".
```

2022-02-22 18:35 UTC, ryandillinfelton requested changes
Mainly blocking on the return of a comment explaining the major_version substring since I think that behavior is very confusing if not explained explicitly. I can take or leave the header comment, but I don't think it adds clarity so I would prefer to leave it out.

2022-02-22 18:35 UTC, ryandillinfelton commented on api/filtering/custom_filters.py
> +# build filter based on the operation and OS name and version
I'm not against function header comments if they clarify it's use or workings, but I think all the information in this comment is already covered by the functions name and parameters.

2022-02-22 19:01 UTC, thearifismail commented on api/filtering/custom_filters.py
> -        # The major operation should only ever be 'lt' or 'gt'
Set this comment.

2022-02-22 19:38 UTC, thearifismail commented on api/filtering/custom_filters.py
> +# build filter based on the operation and OS name and version
the header comment gone.

2022-02-22 21:23 UTC, ryandillinfelton approved these changes
LGTM

2022-02-22 21:50 UTC, kruai approved these changes

2022-02-22 21:50 UTC, merged