[WIP] Allow querying for the existence of objects on hosts
RedHatInsights/insights-host-inventory pull request #1099
Opened 2022-02-23 21:58 UTC by ryandillinfelton

# Overview

I don't think we have a Jira for this one. We had an urgent request to allow searching for if the ansible objects was nil/not_nil. We currently support this behavior on scalar system_profile fields, but not on objects. This PR allows nil/not_nil queries to be made against object fields in the same way we allow it with scalars.

[WIP] There are still a few things that need to be done. If the [WIP] tag is gone, and the PR is no longer a draft ignore this, it means I forgot to delete it. Or check these are actually here, I'm not your boss.

- [ ] Testing
  - [ ]  Objects can only be checked for nil/not_nil, no other values
  - [ ]  [eq] operation is okay to use for checking nil/not_nil but no others
  - [ ]  Check if new tests are required to insure that existing query validation was not weakened

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2022-02-23 23:19 UTC, ryandillinfelton commented
Documentation of the new feature should be done as a follow up since the docs live elsewhere. I'll link in the description when it's ready, but may wait for this to be approved first in case requested changes change the interface.

2022-02-24 13:57 UTC, kruai requested changes
Just requesting a few spelling/grammar changes. Thanks for being so thorough with the testing!

2022-02-24 13:57 UTC, kruai commented on api/filtering/filtering.py
> +def _create_object_existance_query(field_name, field_value):
```suggestion
def _create_object_existence_query(field_name, field_value):
```

2022-02-24 13:57 UTC, kruai commented on api/filtering/filtering.py
> +    # Wondering if that was always a bug
It may have been, for deep objects. Unsure, but I don't think it's a concern right now.

2022-02-24 13:57 UTC, kruai commented on api/filtering/filtering.py
> +        return (_create_object_existance_query(field_name, field_value),)
```suggestion
        return (_create_object_existence_query(field_name, field_value),)
```

2022-02-24 13:57 UTC, kruai commented on api/filtering/filtering.py
> +        return (_create_object_existance_query(field_name, field_value["eq"]),)
```suggestion
        return (_create_object_existence_query(field_name, field_value["eq"]),)
```

2022-02-24 13:57 UTC, kruai commented on tests/test_xjoin.py
> +# Test generic filtering for object fields (the object itself not it's properties)
```suggestion
# Test generic filtering for object fields (the object itself, not its properties)
```

2022-02-24 13:57 UTC, kruai commented on tests/test_xjoin.py
> +        # build_system_profile_sap_sids_url
Can probably be removed, since you have a separate test for it

2022-02-24 14:17 UTC, ryandillinfelton commented on api/filtering/filtering.py
> +    # Wondering if that was always a bug
Oh yeah meant to remove that comment. It was for me during exploratory

2022-02-24 15:28 UTC, kruai approved these changes
LGTM

2022-02-24 17:06 UTC, thearifismail approved these changes

2022-02-24 17:07 UTC, thearifismail approved these changes
LGTM

2022-02-24 17:07 UTC, merged