new endpoint for listing unique OS versions per account
RedHatInsights/insights-host-inventory pull request #1106
Opened 2022-03-11 18:37 UTC by ryandillinfelton

# Overview

This PR is being created to address [ESSNTL-564](https://issues.redhat.com/browse/ESSNTL-564). (Kind of)

I list 564 as the Jira since it was what was planned, but the goals have changed drastically so I may swap it in the future with a different more specific card. Essentially with xjoin-search being replaced soon we thought it unwise to add full generic unique value listing as a feature. This will unblock the main issue that was proposed to solve, listing OS versions on an account for use with filtering.

Here is an example query and response. Please note I am using local test data that sidesteps our usual ingestion validation. All fields on operating_system are currently required, and worst case, `name` has always been required. So the first result should never appear in production. That said it's good to know it will not 500 if it does.
```
/api/inventory/v1/system_profile/operating_system
```
```
{
    "total": 4,
    "count": 4,
    "page": 1,
    "per_page": 50,
    "results": [
        {
            "value": {
                "name": "",
                "major": null,
                "minor": null
            },
            "count": 4
        },
        {
            "value": {
                "name": "FED",
                "major": 1,
                "minor": 1
            },
            "count": 1
        },
        {
            "value": {
                "name": "RHEL",
                "major": 0,
                "minor": 0
            },
            "count": 1
        },
        {
            "value": {
                "name": "RHEL",
                "major": 2,
                "minor": 2
            },
            "count": 1
        }
    ]
}
```

TODO (This is still a WIP):
- [ ]  Add tests

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2022-03-16 17:28 UTC, thearifismail commented on app/instrumentation.py
> +def log_get_operating_system_succeeded(logger, data):
This logger should be generalized for all properties in `system_profile`.

2022-03-16 17:28 UTC, thearifismail commented on swagger/api.spec.yaml
> +  /system_profile/operating_system:
Same comment as earlier, can this endpoint be generalized over `system_profile`?

2022-03-16 17:28 UTC, thearifismail commented on swagger/api.spec.yaml
> +          $ref: '#/components/schemas/Total'
Is `Total` really needed when count is available?

2022-03-16 17:28 UTC, thearifismail commented on tests/test_xjoin.py
>                      url = url_builder(query=prefix + suffix)
Personally, I prefer `+` for ease of understanding and other languages concatenate strings this way but fashion and modernity police likes f'{prefix}{suffix}'.

2022-03-16 18:50 UTC, ryandillinfelton commented on tests/test_xjoin.py
>                      url = url_builder(query=prefix + suffix)
I'm not sure what you mean, I'm not concatenating any strings here. I'm just adding the url_builder to the subtest so that when the test fails we may have a better indication of which endpoint the test is failing on. When I made this change I accidentally made a change that broke the filters on the /sap_system endpoint but none of the other. I was confused for a while because I was only testing that it worked on the /hosts endpont. I think noting it will help others in the same situation in the future.

2022-03-16 18:54 UTC, ryandillinfelton commented on api/system_profile.py
> +    log_get_operating_system_succeeded(logger, data)
This is how the other /system_profile endpoints handle failure. And considering this whole file will need to be refactored whenever we actually do a generic unique values endpoint I'm inclined to kick any refactory changes down the road.

2022-03-16 18:55 UTC, ryandillinfelton commented on api/system_profile.py
> +            # we're not indexing null timestamps in ES
Honestly IDK. Copy paste casualty. Was probably relevant when we first added the SAP endpoints.

2022-03-16 18:56 UTC, ryandillinfelton commented on api/system_profile.py
> +                    total
total is present on the other system_profile endpoints and is not equivalent to count. Both are necessary.

2022-03-16 18:58 UTC, ryandillinfelton commented on api/system_profile.py
> +OPERATING_SYSTEM_QUERY = """
This is a stop-gap solution to unblock teams waiting on getting unique `operating_system` values. You're absolutely right that this will not scale, but it is the existing pattern we will have to deal with when we actually can implement the generic unique values endpoint. Until then i don't want to spend extra cycles implementing any changes we *think* will make the transition to generic easier.

2022-03-16 19:03 UTC, ryandillinfelton commented on swagger/api.spec.yaml
> +  /system_profile/operating_system:
We're not generalizing the endpoint at this time. But when we do, if we follow the design I proposed, the generalized endpoints will follow this pattern. `/system_profile/{field_name}/{subfield_name}` etc. From a user perspective the interface will remain the same. As for now there is also the issue of `sap_sids` having a unqiue sap_sids_filter that would be meaningless to other system_profile endpoints which would make generalizing fairly complex, not to mention trying to keep an eye out for any other fields that may need special treatment. Basically it's just out of scope for this PR.

2022-03-16 19:43 UTC, thearifismail commented on api/system_profile.py
> +    log_get_operating_system_succeeded(logger, data)
Yes, please refactor the code when generic unique values endpoint is done.  Right now it does not look good.

2022-03-16 19:43 UTC, thearifismail commented on swagger/api.spec.yaml
> +          $ref: '#/components/schemas/Total'
What about this question?

2022-03-16 19:43 UTC, thearifismail commented on tests/test_xjoin.py
>                      url = url_builder(query=prefix + suffix)
Isn't this `prefix + suffix` string concatenation?  The concatenation of prefix+suffix is assigned to the query?

2022-03-21 13:54 UTC, kruai requested changes
Mostly got some questions

2022-03-21 13:54 UTC, kruai commented on api/system_profile.py
> +    log_get_operating_system_succeeded(logger, data)
Can you clarify the issue or link to an example of the way you'd prefer it be implemented @thearifismail ? The way he's implementing it is in line with how we've implemented the API endpoints for both the Host and System Profile. If `graphql_query` fails, it logs the failure and aborts, so the success is never called

2022-03-21 13:54 UTC, kruai commented on swagger/api.spec.yaml
> +      summary: get all sap system values and counts on an account
The tags got swapped with the `/system_profile/sap_sids` endpoint

2022-03-21 13:54 UTC, kruai commented on swagger/api.spec.yaml
> +      summary: get all sap sids values and counts on an account
The tags got swapped with the `/system_profile/sap_system` endpoint

2022-03-21 14:13 UTC, ryandillinfelton commented on swagger/api.spec.yaml
> +      summary: get all sap sids values and counts on an account
This is Intentional. I think having them all categorized under system profile makes more sense, especially as we add more system_profile resources like operating_system.

2022-03-21 14:35 UTC, kruai commented on swagger/api.spec.yaml
> +      summary: get all sap sids values and counts on an account
My bad, I misread; thought they were being unintentionally swapped. I'm fine with consolidation

2022-03-21 17:36 UTC, ryandillinfelton commented on api/system_profile.py
> +    filter=None,
It's got the same parameters as the other system profile endpoints (aside from the sap_sids filter). I think it would be good to assess expanding the filtering on them to match `/hosts` but since I don't know how involved that would be, and I'd like all of the system profile endpoints to support the same host filters, I'd prefer to make that a standalone task rather than fold it into this.

2022-03-21 17:37 UTC, ryandillinfelton commented on api/system_profile.py
> +        flask.abort(503)
Removed :+1:

2022-03-21 18:14 UTC, kruai commented on api/system_profile.py
> +    filter=None,
Fair point, but considering the use case, it might make more sense for it to match the `/hosts` implementation. My understanding system profile endpoints are like that so we can fetch data for a specific page of hosts; for the unique values, we want to get the full list of unique operating systems for all hosts (on all pages) in the current search. Does that make sense, or am I off base?

2022-03-24 15:51 UTC, thearifismail commented
@ryandillinfelton shouldn't this be closed now because this changed is already in https://github.com/RedHatInsights/insights-host-inventory/pull/1109/files?

2022-03-28 18:03 UTC, ryandillinfelton commented
> @ryandillinfelton shouldn't this be closed now because this changed is already in https://github.com/RedHatInsights/insights-host-inventory/pull/1109/files?

This is about returning the operating system versions represented on a set of hosts, nothing to do with per_reporter_staleness.

2022-04-26 15:21 UTC, thearifismail approved these changes
LGTM

2022-04-28 15:24 UTC, kruai approved these changes
LGTM

2022-04-28 19:07 UTC, merged