[WIP]Update registered_with to accept all reporters and add per_reporter_staleness filters
RedHatInsights/insights-host-inventory pull request #1115
Opened 2022-03-30 21:27 UTC by thearifismail

# Overview

This PR is being created to address [ESSNTL-2448](https://issues.redhat.com/browse/ESSNTL-2448).
The PR updates "registered_with" to accept all reporters in addition to "insights" and add filters for per_reporter_staleness.

This PR should be on hold until "per_reporter_staleness" filters are implemented in "xjoin-search".  

TODO in this PR.  Update tests to verify "per_reporter_staleness".

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2022-03-31 12:34 UTC, kruai commented
Converted this to a draft since it's WIP

2022-03-31 15:29 UTC, kruai reviewed
Left a few comments on the direction; I didn't review the tests because I figured it would make sense to nail down the implementation first. In the Jira, I had posted Ryan's original PR (#838) that adds per-reporter staleness filters. While we're getting input from the `registered_with` param instead, that PR has some graphql queries that you might want to reference for your expected output.

2022-03-31 15:29 UTC, kruai commented on swagger/api.spec.yaml
> +      description: Filters out any host not registered by the specified reporter
```suggestion
      description: Filters out any host not registered by the specified reporters
```

2022-03-31 15:32 UTC, kruai commented
Additionally, I'm going to speak with Christian this afternoon to get more specifics about the use case. For instance:

-   When the user selects a data collector in the filter, should it show hosts that have EVER been reported by the collector, or just hosts that have been reported in the last month (or other period of time)?
- When the user selects multiple data collectors, should it show hosts that have been reported by EITHER collector, or only ones that have been reported to by BOTH?

Regardless of what the answers to these questions are, they will only require small changes once the initial implementation is nailed down.

2022-04-01 13:31 UTC, thearifismail commented
/retest

2022-04-04 15:43 UTC, kruai commented
> Additionally, I'm going to speak with Christian this afternoon to get more specifics about the use case. For instance:
> 
> * When the user selects a data collector in the filter, should it show hosts that have EVER been reported by the collector, or just hosts that have been reported in the last month (or other period of time)?
> * When the user selects multiple data collectors, should it show hosts that have been reported by EITHER collector, or only ones that have been reported to by BOTH?
> 
> Regardless of what the answers to these questions are, they will only require small changes once the initial implementation is nailed down.

FYI, I got responses to these questions from Christian:

- We should only show hosts that have been reported to by the specified reporters within our usual culling period; i.e. we should check that `now` is earlier than `stale_timestamp` + 14 days.
- We want EITHER (i.e. use `OR`), which is what you're already doing.

2022-04-12 17:45 UTC, kruai requested changes
Left some comments. I didn't comment on the last couple of tests because I expect they'll be updated in tandem with the changes to the implementation

2022-04-12 17:45 UTC, kruai commented on api/filtering/filtering.py
> +def _build_registered_with_per_reporter_filter(registered_with):
Since this is also being called from other files, it should probably not start with an underscore:
```suggestion
def build_registered_with_per_reporter_filter(registered_with):
```

2022-04-12 17:45 UTC, kruai commented on api/filtering/filtering.py
> +        prs_list.append(
I just realized that we'll need to keep handling the `registered_with=insights` case so that we don't break its current functionality. With the refactoring you've done, though, this should be a pretty simple change:
```suggestion
    for item in registered_with:
        if item == "insights":
            prs_list.append({"NOT": {"insights_id": {"eq": None}}})
        else:
            prs_list.append(
```

2022-04-12 17:45 UTC, kruai commented on tests/test_api_hosts_delete.py
> +
Isn't this entire test just a copy&paste of the test above it (`test_delete_hosts_using_filter`)? Why not just add those new parameterized values to the existing test?

2022-04-12 17:45 UTC, kruai commented on tests/test_api_hosts_delete.py
> +        ("registered_with", "yupana"),
`registered_with` is an array now, not just a string

2022-04-12 17:45 UTC, kruai commented on tests/test_api_hosts_get.py
> +    ),
If `field` is always going to be `registered_with`, it doesn't need to be parameterized

2022-04-12 17:45 UTC, kruai commented on tests/test_api_hosts_get.py
> +
Same issue with this test - it's almost exactly a copy&paste of the test above it (`test_get_hosts_only_insights`). Not to mention, that test is verifying `registered_with` as well. Instead of making a new test, the old test can just be parameterized to add the new values.

2022-04-12 17:45 UTC, kruai commented on tests/test_xjoin.py
> +    url = build_hosts_url(query=f"?registered_with={reporter}")
good, though because `registered_with` is now an array, this should also test situations where multiple reporters are selected

2022-04-12 17:45 UTC, kruai commented on tests/test_xjoin.py
> +        },
Since this test was just verifying the functionality for `?registered_with=insights` specifically, it actually shouldn't need to change

2022-04-12 17:45 UTC, kruai commented on tests/test_xjoin.py
> +                },
same thing here

2022-04-14 20:46 UTC, thearifismail commented on tests/test_xjoin.py
> +    url = build_hosts_url(query=f"?registered_with={reporter}")
Using array for "registered_with" requires a number of things to be done.  I am hoping that QE has some test.  If not, then we can deal with it later.

2022-04-19 13:25 UTC, kruai commented on api/filtering/filtering.py
> +        regwith_filter += ({"OR": prs_list},)
It's generally best not to modify parameters that are passed in. I'd recommend something like this:
```suggestion
    if registered_with:
        prs_list = []
        for item in registered_with:
            if item == "insights":
                prs_list.append = ({"NOT": {"insights_id": {"eq": None}}},)
            else:
                prs_list.append(
                    {
                        "per_reporter_staleness": {
                            "reporter": {"eq": item},
                            "stale_timestamp": {
                                "gt": str(datetime.now(timezone.utc) - inventory_config().culling_culled_offset_delta)
                            },
                        },
                    }
                )
        regwith_filter += ({"OR": prs_list},)
```
If that doesn't work and you have to remove an element for some reason, it should be done in a separate variable. Basically just something like this: 
```
reg_with_no_insights = registered_with
if "insights" in reg_with_no_insights:
    # insights-specific logic goes here
    reg_with_no_insights.remove("insights")
# rest of the logic goes here, using reg_with_no_insights instead of registered_with
```

2022-04-19 13:25 UTC, kruai commented on api/filtering/filtering.py
> +                }
Looks good!

2022-04-19 14:15 UTC, kruai requested changes
Implementation mostly looks good - the tests just need some fixes now

2022-04-19 14:15 UTC, kruai commented on tests/test_xjoin.py
> +        },
We should also test the tags endpoint with some other reporters (including an array of them). You can test those in either this test or a separate one... if you decide to make a separate one, this test's name should be changed to something like `test_tags_query_variables_registered_with_insights`

2022-04-19 14:15 UTC, kruai commented on tests/test_xjoin.py
> +@pytest.mark.parametrize("reporter", ("cloud-connector", "puptoo", "rhsm-conduit", "yupana"))
This should also validate the filter when an array is passed in, like the above tests.

2022-04-19 14:15 UTC, kruai commented on tests/test_xjoin.py
> +        },
This test looks good, but it's effectively removing the `registered_with=insights` test. We should still test that use case, since we're not removing it yet.

2022-04-19 14:15 UTC, kruai commented on tests/test_xjoin.py
> +        },
Same thing here ^

2022-04-19 14:15 UTC, kruai commented on tests/test_xjoin.py
> +@pytest.mark.parametrize("reporter", ("cloud-connector", "puptoo", "rhsm-conduit", "yupana"))
This should also test how the filters look when multiple reporter values are provided.

2022-04-19 14:15 UTC, kruai commented on tests/test_xjoin.py
> +@pytest.mark.parametrize("reporter", ("cloud-connector", "puptoo", "rhsm-conduit", "yupana"))
This should also test how the filters look when multiple reporter values are provided.

2022-04-19 14:18 UTC, kruai commented on tests/test_xjoin.py
> +    url = build_hosts_url(query=f"?registered_with={reporter}")
As we discussed in person today, query parameters support multiple values by default. This is done simply by providing the variable twice, e.g. `?registered_with=puptoo&registered_with=yupana`

2022-04-19 16:00 UTC, thearifismail commented on tests/test_xjoin.py
> +    url = build_hosts_url(query=f"?registered_with={reporter}")
> As we discussed in person today, query parameters support multiple values by default. This is done simply by providing the variable twice, e.g. `?registered_with=puptoo&registered_with=yupana`

Done!

2022-04-19 16:29 UTC, thearifismail commented on tests/test_xjoin.py
> +
Moved.

2022-04-19 18:11 UTC, thearifismail commented on tests/test_xjoin.py
> +        },
Done!

2022-04-19 18:14 UTC, thearifismail commented on tests/test_xjoin.py
> +@pytest.mark.parametrize("reporter", ("cloud-connector", "puptoo", "rhsm-conduit", "yupana"))
Added a new test `def test_system_profile_sap_sids_endpoint_registered_with_multiple_reporters` using `query="?registered_with=cloud-connector&registered_with=puptoo&registered_with=rhsm-conduit"`

2022-04-25 19:16 UTC, kruai requested changes
The tests need some refactoring, but the implementation looks good

2022-04-25 19:16 UTC, kruai commented on tests/test_xjoin.py
> +@pytest.mark.parametrize("reporter", ("cloud-connector", "puptoo", "rhsm-conduit", "yupana"))
That's functional, but I do think that test can be refactored into this one and parameterized

2022-04-25 19:16 UTC, kruai commented on tests/test_api_hosts_get.py
> +def test_get_hosts_registered_with(mq_create_three_specific_hosts, mq_create_or_update_host, api_get, value):
That's good, but it's almost identical to this test. It should probably be refactored into this & parameterized

2022-04-25 19:16 UTC, kruai commented on tests/test_api_hosts_delete.py
> +    assert len(host_ids) > 0
Now that I better understand the test, this can be removed (optional)

2022-04-25 20:04 UTC, thearifismail reviewed
Except for `test_api_hosts_get.py::test_get_hosts_registered_with` all the `*_per_reporter` tests vs `*_multiple_reporters` tests must be separate due to the difference in validation filters in assertion calls.

2022-04-25 20:04 UTC, thearifismail commented on tests/test_xjoin.py
> +        },
Same as above.

2022-04-26 13:06 UTC, kruai commented on tests/test_xjoin.py
> +            ),
It's true that it needs 3 blocks, but that doesn't mean it can't be refactored. I can make a PR to your branch to demonstrate

2022-04-26 16:07 UTC, kruai commented on tests/test_xjoin.py
> +            ),
It doesn't enhance the implementation, but neither does having multiple nearly-identical tests. It doesn't make sense to me to have multiple tests that validate the same functionality, but with different values; that's the whole purpose of parameterization.

It's not complicated to refactor, either - I made [this PR to your branch](https://github.com/thearifismail/insights-host-inventory/pull/11) to demonstrate. What do you think?

2022-04-26 19:10 UTC, thearifismail commented on tests/test_xjoin.py
> +            ),
Done!

2022-04-26 20:40 UTC, kruai approved these changes
I think this is ready, and can go in after [xjoin-search PR 153](https://github.com/RedHatInsights/xjoin-search/pull/153) gets merged

2022-04-27 12:46 UTC, thearifismail commented
removed the hold label because the [xjoin-search PR #153](https://github.com/RedHatInsights/xjoin-search/pull/153) has been merged.

2022-04-27 12:46 UTC, merged