add org_id handling by HBI
RedHatInsights/insights-host-inventory pull request #1125
Opened 2022-05-10 15:49 UTC by thearifismail

# Overview

This PR is being created to address [ESSNTL-2525](https://issues.redhat.com/browse/ESSNTL-2525).
It adds the `ORG_ID` provided in a host's payload.  It also implements the handling of `org_id` when passed in with identity.
`host.account` and `identity.account_name` are expected to work as before.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2022-05-10 19:13 UTC, kruai requested changes
Left some comments. There are also some places `org_id` needs to be added:

- The returned data in the host [xjoin query](https://github.com/thearifismail/insights-host-inventory/blob/add_org_id/api/host_query_xjoin.py#L40)
- The [HostDeleteEvent schema](https://github.com/thearifismail/insights-host-inventory/blob/add_org_id/app/queue/events.py#L68)
- `threadctx.org_id` in identity.py, following the example set by [threadctx.account_number](https://github.com/thearifismail/insights-host-inventory/blob/add_org_id/app/auth/identity.py#L106)
- `ContextualFilter.filter()`, following the examples set by [threadctx.account_number](https://github.com/thearifismail/insights-host-inventory/blob/add_org_id/app/logging.py#L107-L112)
- Both identity types in [_asdict()](https://github.com/thearifismail/insights-host-inventory/blob/add_org_id/app/auth/identity.py#L111), in identity.py
- Should be a property in [HostWrapper](https://github.com/thearifismail/insights-host-inventory/blob/add_org_id/app/utils.py#L128-L134)
- Should be a field in the [KafkaPayloadTracker definition](https://github.com/thearifismail/insights-host-inventory/blob/add_org_id/app/payload_tracker/__init__.py#L105), and should be passed in the same way as `account`
- We probably need to include the same rhsm-conduit workaround we did for [account_number](https://github.com/thearifismail/insights-host-inventory/blob/add_org_id/app/queue/queue.py#L76)
- The identities in the README should be updated to include `org_id`

There might be a few more places, but I think that's most or all of them

2022-05-10 22:36 UTC, thearifismail commented
@kruai Responeded to all comments.
> * The returned data in the host [xjoin query](https://github.com/thearifismail/insights-host-inventory/blob/add_org_id/api/host_query_xjoin.py#L40)
    Done!
> * The [HostDeleteEvent schema](https://github.com/thearifismail/insights-host-inventory/blob/add_org_id/app/queue/events.py#L68)
    Done!
> * `threadctx.org_id` in identity.py, following the example set by [threadctx.account_number](https://github.com/thearifismail/insights-host-inventory/blob/add_org_id/app/auth/identity.py#L106)
    Done!
> * `ContextualFilter.filter()`, following the examples set by [threadctx.account_number](https://github.com/thearifismail/insights-host-inventory/blob/add_org_id/app/logging.py#L107-L112)
    Done!
> * Both identity types in [_asdict()](https://github.com/thearifismail/insights-host-inventory/blob/add_org_id/app/auth/identity.py#L111), in identity.py
    Done!
> * Should be a property in [HostWrapper](https://github.com/thearifismail/insights-host-inventory/blob/add_org_id/app/utils.py#L128-L134)
    Done!
> * Should be a field in the [KafkaPayloadTracker definition](https://github.com/thearifismail/insights-host-inventory/blob/add_org_id/app/payload_tracker/__init__.py#L105), and should be passed in the same way as `account`
    Done!
> * We probably need to include the same rhsm-conduit workaround we did for [account_number](https://github.com/thearifismail/insights-host-inventory/blob/add_org_id/app/queue/queue.py#L76)
> * The identities in the README should be updated to include `org_id`
Added an example of identity using `org_id`

2022-05-10 22:46 UTC, thearifismail reviewed
@asa responded to your comments

2022-05-11 15:56 UTC, thearifismail commented
/retest

2022-05-12 20:43 UTC, kruai requested changes
Like we discussed earlier, `org_id` should not be required yet; we can't start requiring it until later in the migration

2022-05-12 20:43 UTC, kruai commented on app/queue/queue.py
> +                identity["org_id"] = host.get("org_id")
Same as before, you can just use the `get()`.
```suggestion
            host.get("org_id")
```

2022-05-12 20:43 UTC, kruai commented on tests/test_unit.py
> +        org_id = "3340851"
`org_id` should not be required, though; if it's requiring a value right now, then something needs to change in the implementation. Otherwise a lot of stuff will break, because they're not required to send it yet

2022-05-12 20:43 UTC, kruai commented on tests/helpers/test_utils.py
> +        identity["org_id"] = org_id
Why would it require a change in the fixture? You just have to pass in a value for the `identity` param which has `org_id` set

2022-05-12 20:43 UTC, kruai commented on tests/test_mq_service.py
> +# This test uses org_id
Not sure this comment is helpful, since you can see `org_id` in the test

2022-05-12 20:43 UTC, kruai commented on tests/test_mq_service.py
> +        "b64_identity": get_encoded_idstr(org_id="1234567890"),
Same response as up there... you can just deepcopy `SYSTEM_IDENTITY` and add `org_id` to it, and pass it into `get_encoded_idstr()`, right?

2022-05-12 20:43 UTC, kruai commented on tests/test_unit.py
> +        unchanged_data = {"display_name": None, "account": None, "org_id": None, "reporter": "yupana"}
But like we discussed earlier this week, we can't require it yet. We can't start requiring it until all reporters are sending it, and after we've populated it for all of the records in the DB.

2022-05-13 15:39 UTC, InsightsDroid commented
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
4bb3d1a1-79bc-4d4b-b1c7-589a9167a298
d317a596-b892-4f54-9488-a5979044e4bf

2022-05-13 15:42 UTC, thearifismail reviewed
Addressed all comments.

2022-05-13 15:42 UTC, thearifismail commented on tests/test_unit.py
> +        unchanged_data = {"display_name": None, "account": None, "org_id": None, "reporter": "yupana"}
Removed `org_id` as a requirement in this test

2022-05-13 15:42 UTC, thearifismail commented on app/queue/queue.py
> +                identity["org_id"] = host.get("org_id")
Done!

2022-05-13 15:45 UTC, thearifismail commented
/retest

2022-05-13 16:02 UTC, InsightsDroid commented
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
1ba7cc98-2c80-4637-8bd5-ed4e2596aeb1
964c88e5-21aa-4e20-9e91-75c9e5f80069

2022-05-13 18:14 UTC, kruai requested changes
`org_id` should still be removed from `test_with_only_required_fields`, and the IQE test failures should be resolved

2022-05-13 18:14 UTC, kruai commented on tests/test_unit.py
> +        unchanged_data = {"display_name": None, "account": None, "org_id": None, "reporter": "yupana"}
It's still there

2022-05-13 19:54 UTC, InsightsDroid commented
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
61e344b2-47f7-44ba-96d0-3538e4bcdbb1
8e5585c8-b1c6-43c1-b3a0-7d4d10632260

2022-05-16 12:55 UTC, kruai approved these changes
It looks good to me now! I'm gonna test a bit more locally but I think it's ready

2022-05-23 08:01 UTC, fstavela commented
/retest

2022-05-23 18:27 UTC, thearifismail commented
@fstavela,  what's the status of testing for this PR?  Thanks.

2022-05-26 06:09 UTC, fstavela commented
/retest

2022-05-27 14:19 UTC, fstavela approved these changes

2022-05-27 14:20 UTC, fstavela commented
/retest

2022-05-31 12:37 UTC, merged