Fixed "staleness=unknown" xjoin search
RedHatInsights/insights-host-inventory pull request #1126
Opened 2022-05-11 18:35 UTC by roliveri

# Overview

This PR is being created to address [ESSNTL-2166](https://issues.redhat.com/browse/ESSNTL-2166).

Filtering on "staleness=unknown" returns all hosts, when going through xjoin. This is because the xjoin-specific section ignores the "unknown" staleness filter.
This PR implements this filter.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2022-05-11 18:58 UTC, InsightsDroid commented
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
be594029-94ba-4eca-9b75-090c0f76bf2f
f65c7293-7354-40bb-b465-fdacea1b91d5

2022-05-12 13:27 UTC, kruai requested changes
These changes look good! However, I think the "unknown" staleness case should be added to a couple other tests in the same file (`test_query_variables_staleness`, `test_tags_query_variables_staleness`).

2022-05-12 14:32 UTC, roliveri commented on tests/test_xjoin.py
> +            {"eq": None},  # unknown
Since the original test was for the staleness filter, that would mean that the test was invalid all along. However, I don't think that is the case because the test was failing without the modification, so the staleness filter was being executed.

2022-05-12 14:50 UTC, InsightsDroid commented
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
2bedd17f-6b79-4bb3-99ea-68f785d47703
c8ae7ffa-d402-4784-9a09-89fe9b0fe130

2022-05-12 15:32 UTC, roliveri commented on tests/test_xjoin.py
> +            {"eq": None},  # unknown
That's definitely not the case. I traced the code before making these changes, and it was calling the staleness filter with "unknown". Otherwise, the tests wouldn't fail after making my change.

2022-05-12 17:54 UTC, kruai commented on tests/test_xjoin.py
> +            {"eq": None},  # unknown
Rich is correct - while "unknown" is one of the default staleness values, it was never applied to the xjoin query (which this fix is addressing).

2022-05-12 17:57 UTC, kruai approved these changes

2022-05-12 19:06 UTC, thearifismail approved these changes

2022-05-12 19:06 UTC, thearifismail commented on tests/test_xjoin.py
> +            {"eq": None},  # unknown
hmmm.  I wonder if pytest caches played tricks on me earlier.  This `def staleness_filter()` is now getting executed.  Earlier I had executed the same test and used `pdb` to halt the execution for debugging but the executions had not stopped.  Anyway it is working now so approving it.

2022-05-12 19:08 UTC, merged