Check response for None before indexing
RedHatInsights/insights-host-inventory pull request #1134
Opened 2022-06-01 17:26 UTC by roliveri

HBI returns 500 on /hosts request, through xjoin, if there are no hosts in the database. This is because xjoin returns None in this situation and we try to index that return value.

# Overview

This PR is being created to address [ESSNTL-1158](https://issues.redhat.com/browse/ESSNTL-1158).
In get_host_list_using_filters(), check response for None before indexing.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2022-06-02 14:30 UTC, kruai requested changes
I left a comment, but can you please also create one test that validates this fix? It should patch the xjoin response (likely with `patch_xjoin_post`), using the response that xjoin-search actually returns when there are 0 hosts. My comment in this PR has the response data, if that helps!

2022-06-02 14:30 UTC, kruai commented on api/host_query_xjoin.py
> +    if response is None:
After setting up xjoin-search and creating the index but _not_ populating it with hosts, this is the response I get from the host query:
```
{
  "data": {
    "hosts": {
      "meta": {
        "count": 0,
        "total": 0
      },
      "data": []
    }
  }
}
```
The `graphql_query` function returns the value of the (inner) `data` field, which I'd think would be an empty array, not None. Correct me if I'm wrong, but should this not be checking against an empty array instead of None?

2022-06-03 13:53 UTC, kruai commented on api/host_query_xjoin.py
> +    if response is None:
IMO we should expect that the index exists; otherwise, something is wrong with xjoin, and our usual exception handling should suffice. To simulate not having any hosts, I just ran seed.js after removing the code that actually adds/indexes the hosts, which happens here: https://github.com/RedHatInsights/xjoin-search/blob/master/test/seed.js#L84

2022-06-08 15:46 UTC, roliveri commented on api/host_query_xjoin.py
> +    if response is None:
@kruai as we discussed, when the index exists and there are no hosts, the code works as expected.

We also discussed the possibility of propagating the error from the `xjoin-search` layer to the `insights-host-inventory` API return. However, it appears `xjoin-search` does not return an error in this case. The  `insights-host-inventory` code is indeed checking for non-200 return codes from `xjoin-search`.

It looks like `elasticsearch` is returning a 404 status to `xjoin-search`, as it appears in the `xjoin-search` log, but `xjoin-search` ultimately returns a 200 status to `insights-host-inventory`.

Given the fix for this would require changes to `xjoin-search`, it would be a high-risk change for a rare (or non-existent) edge case.

Should we just check for None on our end, and possibly log the unexpected return value from `xjoin-search`?

2022-06-14 13:50 UTC, kruai commented on api/host_query_xjoin.py
> +    if response is None:
@roliveri LMK your thoughts - I'm open to other ideas if you'd prefer a different approach

2022-06-23 08:16 UTC, fstavela commented
/retest

2022-06-28 09:24 UTC, fstavela approved these changes

2022-06-29 15:16 UTC, roliveri commented on api/host_query_xjoin.py
> +    if response is None:
@kruai Should the returned status be 503 or 500?
It seems to me 500 would be more appropriate in this case.

2022-06-29 15:21 UTC, kruai commented on api/host_query_xjoin.py
> +    if response is None:
I try to avoid 500 since that's the generic catch-all. Generally if our app returns status 500 it means that we failed to handle an exception

2022-06-29 19:02 UTC, kruai requested changes
Just one more request!

2022-06-29 19:02 UTC, kruai commented on tests/test_xjoin.py
> +
Looks good, but this can also be parameterized to reduce duplication:
```suggestion
@pytest.mark.parametrize("response_data", (None, {}))
def test_host_request_xjoin_invalid_response_none(patch_xjoin_post, api_get, response_data):
    patch_xjoin_post(response={"data": response_data}, status=200)
    request_id = generate_uuid()

    response_status, response_data = api_get(
        HOST_URL, extra_headers={"x-rh-insights-request-id": request_id, "foo": "bar"}
    )

    assert response_status == 503


```

2022-06-29 20:55 UTC, roliveri commented on tests/test_xjoin.py
> +
Done.

2022-06-29 21:06 UTC, thearifismail approved these changes
LGTM

2022-06-30 13:07 UTC, kruai approved these changes
LGTM!

2022-06-30 13:07 UTC, merged