ESSNTL-2863: Inventory doesn't send update event messages after updating facts
RedHatInsights/insights-host-inventory pull request #1140
Opened 2022-06-17 13:16 UTC by FabriciaDinizRH

# Overview

This PR is being created to address [ESSNTL-2863](https://issues.redhat.com/browse/ESSNTL-2863).

Adds a event emitter when host facts are updated by namespace.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2022-06-23 11:15 UTC, InsightsDroid commented
Test results are available in Ibutsu:
https://url.corp.redhat.com/ibutsu-runs-f00a647b-b384-4ed4-9a09-a36b8559a6f9

2022-06-27 07:32 UTC, fstavela commented
I tested this and it works and sends update event message after the facts have been updated via REST API.

However, I found out that this message, or any other event message, doesn't include `facts`. I don't know if this was decided in the past and it is intentional, or if it is a bug, so I created another Jira card for it and I'm okay with fixing it in another PR, so I think this is good to go.

Mentioned Jira: https://issues.redhat.com/browse/ESSNTL-3012

2022-06-28 09:26 UTC, fstavela submitted a review, later dismissed

2022-06-28 12:59 UTC, kruai commented
> I tested this and it works and sends update event message after the facts have been updated via REST API.
> 
> However, I found out that this message, or any other event message, doesn't include `facts`. I don't know if this was decided in the past and it is intentional, or if it is a bug, so I created another Jira card for it and I'm okay with fixing it in another PR, so I think this is good to go.
> 
> Mentioned Jira: https://issues.redhat.com/browse/ESSNTL-3012

I don't think I was around when this was decided, but I also don't know which services need each host's facts to be sent on every update. It seems like this was an intentional choice based on the documentation, since the `facts` field is defined in the expected message format, but is not in the created/updated event interface. We leave a number of other fields out of the events we produce, like `subscription_manager_id`, `satellite_id`, and `bios_uuid`. I'm guessing we only included the fields we absolutely needed to provide in order to keep the message size down, which is an issue we're hitting today.

2022-06-28 13:10 UTC, kruai commented
Actually, which services need to keep track of the `facts` field @fstavela? It only makes sense to send an update event when `facts` gets updated if `facts` is also included in the created/updated event, and it only makes sense to add it to those events if an existing app is consuming our messages and needs to synchronize that field

2022-06-28 13:15 UTC, fstavela commented
> 

I see all of those UUID fields in the created/updated events. Basically, I see everything there (including the entire system_profile) except of the `facts`. You can see the example received event in the description of the created Jira card.

2022-06-28 13:20 UTC, fstavela commented
> Actually, which services need to keep track of the `facts` field @fstavela? It only makes sense to send an update event when `facts` gets updated if `facts` is also included in the created/updated event, and it only makes sense to add it to those events if an existing app is consuming our messages and needs to synchronize that field

Hmm, you are right. I don't know about any such application, but I would guess that there is some, since the field is actively being populated by the reporters.

However, I would also like to know what exactly is that field used for, for me it looks like a lot of times the data there is duplicated from `system_profile`. Isn't `facts` just some historic predecessor of `system_profile`? Do we even still need it?

2022-06-28 13:48 UTC, kruai commented
> > > I tested this and it works and sends update event message after the facts have been updated via REST API.
> > > However, I found out that this message, or any other event message, doesn't include `facts`. I don't know if this was decided in the past and it is intentional, or if it is a bug, so I created another Jira card for it and I'm okay with fixing it in another PR, so I think this is good to go.
> > > Mentioned Jira: https://issues.redhat.com/browse/ESSNTL-3012
> > 
> > 
> > I don't think I was around when this was decided, but I also don't know which services need each host's facts to be sent on every update. It seems like this was an intentional choice based on the documentation, since the `facts` field is defined in the expected message format, but is not in the created/updated event interface. We leave a number of other fields out of the events we produce, like `subscription_manager_id`, `satellite_id`, and `bios_uuid`. I'm guessing we only included the fields we absolutely needed to provide in order to keep the message size down, which is an issue we're hitting today.
> 
> I see all of those UUID fields in the created/updated events. Basically, I see everything there (including the entire system_profile) except of the facts. You can see the example received event in the description of the created Jira card.

Oh, you're right. In that case, we need to update our documentation to reflect that...


> > Actually, which services need to keep track of the `facts` field @fstavela? It only makes sense to send an update event when `facts` gets updated if `facts` is also included in the created/updated event, and it only makes sense to add it to those events if an existing app is consuming our messages and needs to synchronize that field
> 
> Hmm, you are right. I don't know about any such application, but I would guess that there is some, since the field is actively being populated by the reporters.
> 
> However, I would also like to know what exactly is that field used for, for me it looks like a lot of times the data there is duplicated from `system_profile`. Isn't `facts` just some historic predecessor of `system_profile`? Do we even still need it?

I don't know! It would be great if we could just remove it, but we need to check with our dependent services first. I _do_ see that it's not a syndicated field in Cyndi, but we need to make sure nobody is querying it from us directly

2022-06-29 14:17 UTC, kruai requested changes
In addition to my suggested change, we should also cover the event message production in our testing. It should at least verify that a message was produced for each host that was updated

2022-06-29 14:17 UTC, kruai commented on api/host.py
> +        _emit_patch_event(serialized_host, host.id, host.canonical_facts.get("insights_id"))
This needs to be inside the `for host` loop in order to produce an update for each host:
```suggestion
        if db.session.is_modified(host):
            db.session.commit()
            serialized_host = serialize_host(host, staleness_timestamps(), EGRESS_HOST_FIELDS)
            _emit_patch_event(serialized_host, host.id, host.canonical_facts.get("insights_id"))
```

2022-06-30 14:02 UTC, kruai commented on tests/test_api_hosts_update.py
> +    event_producer_mock, event_datetime_mock, db_create_host, db_get_host, api_patch
`db_get_host` is not used and should be removed.

2022-06-30 14:05 UTC, kruai commented on tests/test_api_hosts_update.py
> +    created_host = db_create_host(host=host, extra_data={"facts": DB_FACTS})
This is an optional change, but since `host` is only used once, I personally wouldn't create a variable for it. Up to you, though! If you think it makes it less readable, I'm fine with leaving it the way it is.
```suggestion
    created_host = db_create_host(host=db_host(), extra_data={"facts": DB_FACTS})
```

2022-06-30 14:07 UTC, kruai commented on tests/test_api_hosts_update.py
> +    response_status, response_data = api_patch(facts_url, DB_NEW_FACTS)
Kind of a nitpick, but generally when a function returns a value that won't be used, you just use `_`.
```suggestion
    response_status, _ = api_patch(facts_url, DB_NEW_FACTS)
```

2022-06-30 14:23 UTC, FabriciaDinizRH commented on tests/test_api_hosts_update.py
> +    response_status, response_data = api_patch(facts_url, DB_NEW_FACTS)
I like to learn those things. I'll use _ from now on

2022-06-30 14:30 UTC, kruai approved these changes
LGTM!

2022-06-30 15:06 UTC, thearifismail approved these changes
LGTM

2022-06-30 15:12 UTC, merged