adds temporary file for the error message
RedHatInsights/insights-host-inventory pull request #1154
Opened 2022-07-06 15:02 UTC by FabriciaDinizRH

# Overview

This PR is being created to address [ESSNTL-xxxx](https://issues.redhat.com/browse/ESSNTL-xxxx).
(A description of your PR's changes, along with why/context to the PR, goes here.)

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2022-07-07 08:36 UTC, fstavela commented
/retest

2022-07-07 09:27 UTC, fstavela commented
/retest

2022-07-12 14:20 UTC, kruai commented on app/queue/queue.py
> +            send_kafka_error_message(host=input_host)
You'll also need to pass the error to the function, right?

2022-07-12 14:25 UTC, FabriciaDinizRH commented on app/models.py
> +    error = fields.Nested(HostValidationErrorSchema)
I have no specific reason to put that in `model.py`, I was just trying to make sense of the workflow. I also think those might belong in `events.py`. I will change that in the next commit.

2022-07-12 14:27 UTC, FabriciaDinizRH commented on app/queue/queue.py
> +            send_kafka_error_message(host=input_host)
yes, I just need to understand the structure of the error before adding it everywhere.

2022-07-12 14:37 UTC, FabriciaDinizRH commented on app/queue/events.py
> +
> It might be difficult to classify validation errors as an EventType. CREATED, UPDATED, and DELETE are all events posted to the events topic, and they all only provide data from the Host.

In this case it would need be something separate from the existing structure, like a NotificationType? I can see that working. And it would fix the problem with EVENT_TYPE_MAP.

2022-07-13 09:53 UTC, FabriciaDinizRH commented on app/queue/queue.py
> +        rh_message_id=create_message_id(),  # will this need to be saved somewhere?
rh_message_id is optional but it is used to ensure the message is only going to be processed once.
The encoding is necessary according to [this document](https://core-platform-apps.pages.redhat.com/notifications-docs/dev/user-guide/send-notification.html#_protecting_your_kafka_messages_against_duplicate_processing).

2022-07-25 11:48 UTC, RonnyPfannschmidt commented on app/queue/notifications.py
> +        "org_id": host["org_id"] if host["org_id"] else None,
to prepare for account_id going away and org_id coming in painlessly

```suggestion
        "account_id": host.get("account_id"),
        "org_id": host.get("org_id"),
```

2022-07-25 11:51 UTC, RonnyPfannschmidt commented on app/queue/event_producer.py
> +class NotificationEventProducer:
thisone pretty much shares amost all of the code, except the topci name, perhaps we can pass the toic name as input and make a `EventProducer(config, config.var_with_topicname)

2022-07-28 15:12 UTC, FabriciaDinizRH commented on app/environment.py
> +    @property
I don't think is necessary since I combined the event producers

2022-08-04 09:09 UTC, FabriciaDinizRH commented on app/queue/queue.py
> +    rh_message_id = _encode_message_id(message_id)
@thearifismail the bytearray format is a requirement for the rh_message_id. The code on `_encode_message_id()` is provided by the notification guidelines on [this link](https://core-platform-apps.pages.redhat.com/notifications-docs/dev/user-guide/send-notification.html#_protecting_your_kafka_messages_against_duplicate_processing)

2022-08-04 12:51 UTC, thearifismail commented on app/queue/notifications.py
> +        "event_type": notification_type.name.replace("_", "-"),
I speculated about hyphen's use.  Do you have replace the underscore with a hyphen?

2022-08-04 14:54 UTC, FabriciaDinizRH commented on app/queue/notifications.py
> +        "event_type": notification_type.name.replace("_", "-"),
@thearifismail oh, sorry. The hyphen is necessary because the name of the event on the notification application has a hyphen, and I needed to match that.

2022-08-04 14:55 UTC, FabriciaDinizRH commented on app/__init__.py
> +        notification_event_producer_failure.labels(
I'll take a look at it

2022-08-05 08:55 UTC, fstavela commented
Even if the build gets fixed, please don't merge this PR until @RonnyPfannschmidt finishes testing of it and approves the PR. Ideally we should push the org_id changes to Prod first before merging this, but I don't know when we get unblocked on that, so if this is ready and tested first, we can push it together.

2022-08-09 16:15 UTC, kruai requested changes
Great work on the structure! I just have a few suggestions and questions

2022-08-09 16:15 UTC, kruai commented on tests/test_mq_service.py
> +        event_producer_mock.write_event.assert_called_once_with(event, key, headers)
A couple of things here:

- We expect the _notification_ event producer to write a message, not the regular event producer, right? If there's a validation error, I would not expect a host to be written to the events topic.
- Because of the exception, the assertion on line 1494 does not occur. Assertions should be made outside of the scope of `pytest.raises`.
- The `event_producer_mock` fixture you're using has a `write_event` method, but it isn't a Mock, so `assert_called_once_with` doesn't exist.

2022-08-09 16:15 UTC, kruai commented on app/exceptions.py
> +        }
Are these changes necessary? The `severity` you're adding appears to be specific to the notification events, and I don't see severity being added or changed on any InventoryExceptions being raised

2022-08-10 10:15 UTC, FabriciaDinizRH commented on app/queue/queue.py
> +RUNTIME_ENVIRONMENT = RuntimeEnvironment.JOB
Yeah, it stopped being used after the final changes and I forgot to remove it.

2022-08-10 11:16 UTC, FabriciaDinizRH commented on tests/test_mq_service.py
> +        event_producer_mock.write_event.assert_called_once_with(event, key, headers)
@kruai you're correct, I should be checking the notification event producer.
As for the `assert_called_once_with`, that explains why it kept giving me an error except when I put it inside the scope of `pytest.raises`. I'm fixing this.

2022-08-10 11:17 UTC, FabriciaDinizRH commented on app/exceptions.py
> +        }
@kruai that could be removed for now, since we one have one severity and I had already hard coded it.

2022-08-15 12:38 UTC, kruai submitted a review, later dismissed
LGTM! The only other thing I can think of is to test that a notification event is *not* produced when there is no validation error. That check can probably be added to an existing test rather than having its own, unless you think it needs it. That's for extra credit, though :)

2022-08-18 17:15 UTC, kruai approved these changes
Still looks good to me!

2022-08-19 19:13 UTC, CodeHeeler submitted a review, later dismissed
Great job, thanks for adding this and for being proactive in including tests and fixtures updates, a good model for future work.

2022-08-29 15:20 UTC, CodeHeeler approved these changes
Still LGTM, thank you again!

2022-08-29 19:59 UTC, kruai approved these changes
Gave it another once-over. Still LGTM!

2022-08-30 10:07 UTC, merged