Replace kafka-python with confluent-kafka.
RedHatInsights/insights-host-inventory pull request #1173
Opened 2022-07-27 15:39 UTC by thearifismail

# Overview

This is DRAFT PR implementing [ESSNTL-1878](https://issues.redhat.com/browse/ESSNTL-1878) to save the current state.  Tests not working.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2022-08-01 09:07 UTC, RonnyPfannschmidt commented on app/queue/event_producer.py
> +__event__ = None
those globals have to go, all the data should be available on the message object

2022-08-01 09:09 UTC, RonnyPfannschmidt commented on app/queue/queue.py
> +            if message is None or message.error() is not None:
the error should be raised

2022-08-01 13:14 UTC, thearifismail commented on app/queue/queue.py
> +            if message is None or message.error() is not None:
Now an error is logged without exiting/stopping the service.

2022-08-03 17:31 UTC, CodeHeeler approved these changes
LGTM, though I'm not well-versed in kafka.  Had a comment on the SSL handling.  Thanks for taking care of this library swap!

2022-08-03 17:31 UTC, CodeHeeler commented on app/config.py
> +        self.payload_tracker_kafka_producer = {"bootstrap.servers": self.bootstrap_servers}
How is confluent kafka handling SSL now?

2022-08-04 19:31 UTC, kruai requested changes
I haven't reviewed the tests yet; I think there are some things in the implementation that need to be ironed out first

2022-08-05 21:52 UTC, thearifismail reviewed
@asa Fixed SSL config and producer and consumer.  With code update, your original comments related to SSL and consumer config have disappeared.

2022-08-05 21:53 UTC, thearifismail commented on inv_mq_service.py
> +        }
Added back in but had to use the config for confluent-kafka.  The link provided as a code comment.

2022-08-09 14:59 UTC, kruai requested changes
Requesting some more changes. Please don't change the output of tests just to make them pass; make sure they still validate the same functionality they were originally built to test.
Also, please make sure you remove classes, fixtures, and such that are no longer used (`MockFuture`, for instance).

2022-08-09 14:59 UTC, kruai commented on app/queue/queue.py
> +                logger.error(f"Message received but has an error, which is {str(message.error())}")
What error was it? We should probably have a bit more handling for it, like incrementing a failure metric at the very least.

2022-08-09 14:59 UTC, kruai commented on app/queue/queue.py
> +                    logger.info("A message received.")
Doesn't make sense; `A message was received` would work, though I think it should probably just stay as `Message received`.

2022-08-09 14:59 UTC, kruai commented on tests/test_api_hosts_delete.py
> +    event_producer._kafka_producer.produce.side_effect = produce_side_effects
This changes what is being tested. This test wasn't validating that the producer works as expected when kafka isn't available; it was testing that the deletion stops if an exception is raised. As it is, the producer never gets to produce a message, and the side effects don't come into play.

2022-08-09 14:59 UTC, kruai commented on tests/test_api_hosts_delete.py
> +    assert event_producer._kafka_producer.produce.call_count == 0
Here you've changed the results of the test so that it passes even though the functionality has changed. The first message does not raise an error, so one host should have been deleted.

2022-08-09 14:59 UTC, kruai commented on tests/test_culling.py
> +    assert event_producer._kafka_producer.produce.call_count == 0
You've done the same thing here as above, which invalidates the test. Please fix.

2022-08-09 14:59 UTC, kruai commented on tests/test_mq_service.py
> +def test_event_loop(mocker, flask_app):
No, this still needs to test that it handles exceptions. Please do not keep changing the purpose of unit tests just so that they pass.

2022-08-09 14:59 UTC, kruai commented on tests/test_mq_service.py
> +    assert handle_message_mock.call_count == 1
Same as above. The expected results have been changed to hide that the functionality has changed.

2022-08-09 14:59 UTC, kruai commented on tests/test_unit.py
> +                produce.assert_called_once_with(self.topic_name, event.encode("utf-8"), callback=ANY)
This used to test that they `key` was correct, but that has been removed. The key is a very important part of the message and needs to be tested here.

2022-08-09 14:59 UTC, kruai commented on tests/test_unit.py
> +                poll.assert_called_once_with()  # calls on callback
If you're not testing any arguments, use `poll.assert_called_once()`.

2022-08-09 14:59 UTC, kruai commented on tests/test_unit.py
> -        )
This assertion should not be removed.

2022-08-09 16:26 UTC, thearifismail commented on app/instrumentation.py
> +    logger.debug(debug_message, extra=debug_extra)
No logs don't change.   I used to use formatted strings but Kyle Lape had adamantly insisted to use `f-string` for being easier than anything else available.

2022-08-22 14:32 UTC, kruai requested changes

2022-08-22 14:32 UTC, kruai commented on tests/test_mq_service.py
> +    assert handle_message_mock.call_count == 1
This still hasn't been updated. I think it's best to keep testing what was originally being tested, which is that multiple messages are processed before the shutdown signal is received. `call_count` should remain at 2, but the interrupt should have one more `False` added to its side effects

2022-08-22 14:32 UTC, kruai commented on tests/test_unit.py
> +                produce.assert_called_once_with(self.topic_name, event.encode("utf-8"), callback=ANY)
In the old test, the assertion validated that the message was being produced with the correct key (`host_id`). The new assertion does not test that, but it needs to. Does that help clarify?

2022-08-22 14:32 UTC, kruai commented on app/queue/event_producer.py
> +        producer.poll()
I didn't realize this before, but why is this function in MessageDetails instead of the producer? Having it here makes it so you have to call `MessageDetails.send(producer)`, which makes it seem like you're telling the message to send the producer. `Producer.send(messageDetails)` makes more sense to me...

2022-08-22 14:32 UTC, kruai commented on tests/test_unit.py
> -        )
This assertion is still missing.

2022-08-22 14:32 UTC, kruai commented on tests/test_api_hosts_delete.py
> +    ),
This used to validate that the deletion would stop after either of these scenarios:
1. The `future` returned by `send()` raises an exception
2. The `send()` itself raises an exception

Now, this function only tests scenario 2 twice. In order to test both, you'll have to also test the scenario where `on_delivered()` receives an error.

2022-08-22 14:32 UTC, kruai commented on tests/test_culling.py
> +    ((mock.Mock(), KafkaException()), (mock.Mock(), KafkaException("oops"))),
Same issue as what I commented in `test_delete_stops_after_kafka_producer_error`

2022-08-22 14:59 UTC, kruai commented on app/queue/event_producer.py
> +    headers: str
Are you sure this is a `str`? In `write_event()`, it's an array of tuples.

2022-08-25 12:39 UTC, thearifismail reviewed
@asa, this PR is ready review.

2022-08-25 12:39 UTC, thearifismail commented on tests/test_mq_service.py
> +    assert handle_message_mock.call_count == 1
Fixed.

2022-08-25 12:39 UTC, thearifismail commented on tests/test_unit.py
> +                produce.assert_called_once_with(self.topic_name, event.encode("utf-8"), callback=ANY)
A host ID IS passed in to the `producer.produce()` with the host info in the event.  In `kafka-python`, a `host_id` was sent as an argument to `producer.send()` despite being present in the event.  

Here is the event json with "host.id" that is passed in as an argument to `produce.assert_called_once_with(<topic>, <event>, <callback>)`
```
{
  "type": "created",
  "host": {
    "reporter": "test_reporter",
    "stale_timestamp": "2022-08-25T12:19:11.169401+00:00",
    "account": "test",
    "org_id": "test",
    "fqdn": "fqdn",
    "id": "fe9a8aaf-dfc0-4ecd-bb55-de31f489d182"
  },
  "metadata": {
    "request_id": "e8123e45-80ae-4763-9150-e2e8b63535fa"
  },
  "timestamp": "2022-08-25T12:19:11.260830+00:00",
  "platform_metadata": null
}
```

2022-08-29 15:42 UTC, kruai requested changes

2022-11-03 14:13 UTC, closed without merging