Validate Identity objects using a schema.
RedHatInsights/insights-host-inventory pull request #1196
Opened 2022-09-14 16:38 UTC by roliveri

# Overview

This PR is being created to address [ESSNTL-647](https://issues.redhat.com/browse/ESSNTL-647).

Implemented Marshmallow schemas to validate identity data.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2022-09-14 19:22 UTC, thearifismail reviewed
Should the be tests targeting new classes in Idenity?

2022-09-15 14:05 UTC, roliveri commented on app/auth/identity.py
> +            print(result)
@thearifismail print statement removed.

2022-09-15 14:06 UTC, CodeHeeler approved these changes
LGTM, thank you!

2022-09-15 15:03 UTC, kruai commented
I'm currently reviewing, but taking some time to mess around with these new schemas. I'll have it done in a bit!

2022-09-15 15:32 UTC, thearifismail reviewed
Should there be unit tests targeting new classes?  User and System identities have their own fields.  It will be good to have validations for those fields.  Here are some identities that I have used for creating hosts or testing.
```
 complete system identity
IDENTITY = {
    "org_id": "test",
    "type": "System",
    "auth_type": "cert-auth",
    "system": {"cn": "1b36b20f-7fa0-4454-a6d2-008294e06378", "cert_type": "system"},
    "internal": {"auth_time": 6300},
}

# system identity: invalid or incomplete for testing
IDENTITY = {
    "org_id": "sysorgid",
    "type": "System",
    "auth_type": "invalid-auth",
    "system": {"cn": "1b36b20f-7fa0-4454-a6d2-008294e06378", "cert_type": "system"},
    "internal": {"auth_time": 6300},
}

# complete user identity
IDENTITY = {
    "org_id": "test",
    "type": "User",
    "auth_type": "basic-auth",
    "user": {"email": "tuser@redhat.com", "first_name": "test"},
}

# incomplete or invalid user identity for testing
IDENTITY = {
    "org_id": "test",
    "type": "User",
    "auth_type": "basic-auth",
}
```

2022-09-15 16:27 UTC, roliveri commented
@thearifismail The new schema classes re-implement the logic that already existed in the `Identity` `__init__`, so I thought the existing tests should provide suitable coverage.

If we need to provide additional test cases, then my question is: Should the schema classes be tested directly, or should we add test cases to `Identity`?

2022-09-15 16:42 UTC, lphiri commented
Hello everyone,
Not sure what the driver is for  this change - but 3scale should be the source of truth for what the schema is.
If this can wait, I suggest waiting for this ticket to be completed : https://issues.redhat.com/browse/RHCLOUD-12047

2022-09-15 16:42 UTC, kruai requested changes
I have a few suggestions to simplify things, but it's otherwise looking good. And I do agree with Arif that some additional tests would be great!
I do also wonder if we can simplify this further... I wanna briefly investigate whether we can make our schema require different fields depending on another field's value (user vs system)

2022-09-15 16:58 UTC, kruai commented
> Hello everyone, Not sure what the driver is for this change - but 3scale should be the source of truth for what the schema is. If this can wait, I suggest waiting for this ticket to be completed : https://issues.redhat.com/browse/RHCLOUD-12047

@lphiri: We use this utility class to more easily parse and validate the identity we're sent. The driver for this change is that wanted to switch to using a schema to validate it, in order to make the logic a bit cleaner.
We can also update this once the schema has been figured out on the 3scale side, but that ticket was opened in Feb 2021 and it's still unassigned. Are there actually plans to implement it soon?

2022-09-15 18:39 UTC, roliveri commented
> I wanna briefly investigate whether we can make our schema require different fields depending on another field's value (user vs system)

@kruai I was wondering if that was possible. I did some searching but didn't find anything. I didn't want to spend too much time on it as I wanted to get something working first - hoping someone would know of a better way. I hope you come up with a more elegant solution.

2022-09-15 18:58 UTC, kruai commented
> > I wanna briefly investigate whether we can make our schema require different fields depending on another field's value (user vs system)
> 
> @kruai I was wondering if that was possible. I did some searching but didn't find anything. I didn't want to spend too much time on it as I wanted to get something working first - hoping someone would know of a better way. I hope you come up with a more elegant solution.

If I do figure out anything, it will be built on top of your existing identity schema work, so don't block on me :)

2022-09-15 19:01 UTC, roliveri commented on app/auth/identity.py
> +    return Identity({"org_id": org_id, "type": IdentityType.USER.value, "auth_type": AuthType.BASIC})
This drove me crazy when the tests were failing. The only thing I can think of is that `OneOf()` performs comparisons differently.

2022-09-19 14:28 UTC, roliveri commented on app/auth/identity.py
> +    cn = fields.Str(required=True)
@kruai 
I think `SystemInfoIdentitySchema` should use `unknown = INCLUDE`, because I think it may contain other fields that weren't validated in the original code, but saved in the system dict nonetheless.

2022-09-19 16:39 UTC, roliveri commented
@kruai @thearifismail 
After reading through `test_api_auth.py`, I think testing the new schema classes directly would be redundant.

I'm going through the existing test cases to see if there are any holes in the coverage. If not, it's my opinion that the tests are fine as is.

Let me know if you disagree.

2022-09-20 16:51 UTC, roliveri commented
@kruai 
I can add a `test_identity_schema.py` file to specifically test the schema.
However I must point out that we don't currently test the formats of individual fields except for length.

Should we add higher-level validation - like valid email or cn? Doing so would add new failure cases that didn't exist before, which may be risky. In the past, it seems we just relied on the backend validation to catch these.

2022-09-22 17:40 UTC, roliveri commented
I added tests for the new schema classes.

I may be on to a way to implement conditionally required fields based on the value of other fields. If it doesn't pan out by Friday, I'll remove the draft.

2022-09-23 17:13 UTC, roliveri commented
@kruai I was able to move the user/system logic into the schema class.
It seems cleaner this way, but I still don't know if theres a better way to accomplish this.

2022-09-27 12:49 UTC, kruai commented
@roliveri Apologies for not responding - I was in Hackathon mode. I was only expecting tests that made sure invalid data in each field would trigger the appropriate exception, but the new test file looks good and thorough!

2022-09-27 12:49 UTC, kruai approved these changes

2022-09-27 13:50 UTC, thearifismail approved these changes

2022-09-27 15:19 UTC, merged