[ESSNTL-2739]
RedHatInsights/insights-host-inventory pull request #1198
Opened 2022-09-19 15:10 UTC by FabriciaDinizRH

# Overview

This PR is being created to address [ESSNTL-xxxx](https://issues.redhat.com/browse/ESSNTL-xxxx).
(A description of your PR's changes, along with why/context to the PR, goes here.)

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2022-09-19 15:15 UTC, CodeHeeler requested changes

2022-09-19 15:15 UTC, CodeHeeler commented on app/queue/queue.py
>          "insights_id": host_data.get("insights_id"),
Shouldn't this insights_id be removed as you did in app/queue/notifications.py line 75 above as it is now within the canonical_facts?

2022-09-19 15:20 UTC, FabriciaDinizRH commented on app/queue/queue.py
>          "insights_id": host_data.get("insights_id"),
Yes! I have forgotten about this one, thanks

2022-09-19 15:30 UTC, CodeHeeler submitted a review, later dismissed
Looks great, thanks!

2022-09-19 18:04 UTC, CodeHeeler submitted a review, later dismissed
LGTM

2022-09-20 09:13 UTC, fstavela commented
I'm still getting the same error:
```
[2022-09-20 09:03:34,904] [1] [140713125044480] [inventory.app.queue.queue] [ERROR] Validation error while adding or updating host: {'_schema': ['provider_type and provider_id are both required.']}
[2022-09-20 09:03:34,905] [1] [140713125044480] [inventory.app.queue.queue] [ERROR] Unable to process message
Traceback (most recent call last):
File "/opt/app-root/src/app/queue/queue.py", line 313, in event_loop
handler(message.value, event_producer, notification_event_producer=notification_event_producer)
File "<decorator-gen-6>", line 2, in handle_message
File "/opt/app-root/lib64/python3.8/site-packages/prometheus_client/context_managers.py", line 66, in wrapped
return func(*args, **kwargs)
File "/opt/app-root/src/app/queue/queue.py", line 298, in handle_message
send_kafka_error_message(notification_event_producer, host=host, detail=str(ve.detail))
File "/opt/app-root/src/app/queue/queue.py", line 333, in send_kafka_error_message
minimal_host = _build_minimal_host_info(host)
File "/opt/app-root/src/app/queue/queue.py", line 139, in _build_minimal_host_info
"canonical_facts": deserialize_canonical_facts(host_data, all=True),
File "/opt/app-root/src/app/serialization.py", line 62, in deserialize_canonical_facts
raise ValidationException(str(e.messages)) from None
app.exceptions.ValidationException: {'_schema': ['provider_type and provider_id are both required.']}
```
and the notification message is not produced

2022-09-21 10:14 UTC, FabriciaDiniz commented
> I'm still getting the same error:
> 
> ```
> [2022-09-20 09:03:34,904] [1] [140713125044480] [inventory.app.queue.queue] [ERROR] Validation error while adding or updating host: {'_schema': ['provider_type and provider_id are both required.']}
> [2022-09-20 09:03:34,905] [1] [140713125044480] [inventory.app.queue.queue] [ERROR] Unable to process message
> Traceback (most recent call last):
> File "/opt/app-root/src/app/queue/queue.py", line 313, in event_loop
> handler(message.value, event_producer, notification_event_producer=notification_event_producer)
> File "<decorator-gen-6>", line 2, in handle_message
> File "/opt/app-root/lib64/python3.8/site-packages/prometheus_client/context_managers.py", line 66, in wrapped
> return func(*args, **kwargs)
> File "/opt/app-root/src/app/queue/queue.py", line 298, in handle_message
> send_kafka_error_message(notification_event_producer, host=host, detail=str(ve.detail))
> File "/opt/app-root/src/app/queue/queue.py", line 333, in send_kafka_error_message
> minimal_host = _build_minimal_host_info(host)
> File "/opt/app-root/src/app/queue/queue.py", line 139, in _build_minimal_host_info
> "canonical_facts": deserialize_canonical_facts(host_data, all=True),
> File "/opt/app-root/src/app/serialization.py", line 62, in deserialize_canonical_facts
> raise ValidationException(str(e.messages)) from None
> app.exceptions.ValidationException: {'_schema': ['provider_type and provider_id are both required.']}
> ```
> 
> and the notification message is not produced

weird, I was getting an error still, but the message was being produced ok. I'll check what's happening

2022-09-27 12:50 UTC, kruai submitted a review, later dismissed

2022-09-29 08:50 UTC, fstavela commented
/retest

2022-09-29 08:54 UTC, fstavela commented
I triggered the build pipeline again, because it looks like the image was not built correctly last time. I'm still not getting the notifications, but during the debugging I found out that the code in the latest image doesn't have the latest changes.

2022-09-29 09:16 UTC, fstavela commented
@FabriciaDinizRH Messages are now produced and also `account_id` is present in the notifications.

One last thing is that `host_id` is still always `None`. I don't think this is a blocker, so I think we can merge this and release and fix the `host_id` problem in another PR.

2022-09-29 09:17 UTC, fstavela approved these changes

2022-09-29 13:33 UTC, kruai approved these changes

2022-09-30 12:24 UTC, CodeHeeler approved these changes
LGTM, thank you!

2022-09-30 12:28 UTC, thearifismail approved these changes
LGTM

2022-09-30 12:45 UTC, merged