[WIP] Implemented operation_args for the add_host operation.
RedHatInsights/insights-host-inventory pull request #1281
Opened 2023-02-23 17:14 UTC by roliveri

# Overview

The new Errata notification reporter will report only a subset of the yum repositories and packages that are reported by insights. 

Currently, HBI performs a shallow merge of system profile facts. So any data below the first level, like yum repos and packages, are overwritten in their entirety. This means that sparse data reported by the Errata notification reporter would overwrite any existing full set of data. Changes need to be made to the system profile update logic to ensure that this doesn't happen.

Toward this end, this PR implements changes to enable the passing of optional arguments to the existing "add_host" operation.

The specific argument implemented here is `defer_to_reporter`, which indicates which reporter's system profile data should have priority over the caller's data. So, Errata notifications would pass "puptoo" as the argument. Then, if the report matches an existing host and "puptoo" is a non-stale reporter for the that host, the existing system profile data will not be overwritten.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-02-23 17:20 UTC, roliveri commented
@kruai As we discussed, this is the implementation for the issue with merging of system profile facts between errata notifications and insights.

I plan on implementing tests when I get back from PTO, but I wanted to give people the opportunity to review and comment while I'm away.

2023-03-13 15:19 UTC, strider commented
/retest

2023-03-13 15:39 UTC, fstavela commented
@strider This needs to be rebased against master first.

2023-03-22 21:08 UTC, roliveri commented
@fstavela After I rebased as you suggested, the tests were passing. After adding tests specific to this change, now they're failing, but the failure appears to be in an unrelated area. All my tests pass when run locally. Do you have any idea what the problem might be?

2023-03-23 10:51 UTC, fstavela commented
/retest

2023-03-23 12:57 UTC, fstavela commented
> @fstavela After I rebased as you suggested, the tests were passing. After adding tests specific to this change, now they're failing, but the failure appears to be in an unrelated area. All my tests pass when run locally. Do you have any idea what the problem might be?

Hmm, it looks like it's caused by this issue: https://github.com/RedHatInsights/bonfire/issues/283

I fixed it with a [workaround](https://github.com/RedHatInsights/insights-host-inventory/pull/1255) in the past, but it looks like it's not related to the test run time, but rather the amount of transferred data (aka. logs amount), which has been increased since then. I'll try to fix it ASAP.

2023-03-23 20:47 UTC, CodeHeeler approved these changes
LGTM, thanks for adding the thorough tests in particular!

2023-03-27 19:18 UTC, kruai requested changes
Good tests! They're very logical, though I think they could be refactored a bit. I've left some recommendations/discussion points

2023-03-27 19:27 UTC, roliveri commented on tests/helpers/db_utils.py
> +    assert found_host
When `found_host` is `None`, the statement: `assert host_id == found_host.id` fails with a name error instead of an assertion failure. I added the assertion to make the failure case more clear.

2023-03-27 19:30 UTC, roliveri commented on utils/payloads.py
> +    return json.dumps(message1).encode("utf-8"), json.dumps(message2).encode("utf-8")
Actually, I only added this code to aid in my initial testing. I never intended on committing it. Thanks for catching this. I'll remove it.

2023-03-27 19:37 UTC, roliveri commented on tests/helpers/db_utils.py
> +    return host
I originally had this code inline but it was duplicated in a number of test cases. Creating this common function eliminated some of the redundancy in the tests.

2023-03-27 19:41 UTC, roliveri commented on tests/helpers/db_utils.py
> +        org_id=SYSTEM_IDENTITY["account_number"],
I only did that to be consistent with other referenced to `SYSTEM_IDENTITY["account_number"]` in the same file. If I change this, I probably should change all of them. What's your opinion.

2023-03-27 19:47 UTC, roliveri commented on lib/host_repository.py
> +
I did consider passing a collection, but it wasn't clear if this would ever be used beyond this initial use case, and I didn't want to over complicate things. If you think it should accept a collection initially, I'm willing to change it. Let me know.

2023-03-27 21:29 UTC, kruai commented on lib/host_repository.py
> +
I think you're right not to overengineer it now, if it doesn't seem likely to be needed in the near future. Just wanted to get your opinion on it first!

2023-03-27 21:32 UTC, kruai commented on tests/helpers/db_utils.py
> +        org_id=SYSTEM_IDENTITY["account_number"],
I only see an account number being set to `SYSTEM_IDENTITY["account_number"]` on [line 66](https://github.com/RedHatInsights/insights-host-inventory/blob/10faf97b67da1b76ab441b4962dc999a320a6898/tests/helpers/db_utils.py#L66). Where are you seeing `org_id` set to the identity's account number?

2023-03-27 21:59 UTC, kruai commented on tests/helpers/test_utils.py
> +    return original_system_profile, updated_system_profile
I thought I had commented on this method, but I must have forgotten to add it to the review... this helper function basically returns `valid_system_profile()` twice, but with one value altered on each. This tells me that we could just give `valid_system_profile()` an optional param for supplied field values (similar to what I suggested [here](https://github.com/RedHatInsights/insights-host-inventory/pull/1281/files#r1149692445)). I think that would make the tests slightly clearer and remove the need for such a specific a helper function

2023-03-27 22:00 UTC, kruai commented on tests/helpers/db_utils.py
> +    assert found_host
OK, I can see how that might help with clarity in case of error.

2023-03-27 22:16 UTC, kruai commented on tests/helpers/db_utils.py
> +    return host
OK... if you think it should stay, I'd like to request a rename; `db_base_host` is vague and it isn't clear how it differs from `db_minimal_host`. It also actually creates the host in the DB rather than just return a host, which should be communicated as well

2023-03-28 13:59 UTC, roliveri commented on tests/helpers/db_utils.py
> +        org_id=SYSTEM_IDENTITY["account_number"],
Right, originally I was setting `account_number`, like the other places in the code. I changed it to `org_id` when it was failing to find the existing host because the `org_id` didn't match. I'll change it.

2023-03-28 14:04 UTC, roliveri commented on tests/helpers/db_utils.py
> +        org_id=SYSTEM_IDENTITY["account_number"],
I'll also change the references in `test_mq_service.py`.

2023-03-28 16:50 UTC, roliveri commented
@kruai I've made the suggested changes. Let me know what you think.
The test: `ci.ext.devshift.net PR build - All tests` seems to fail sporadically, but it doesn't appear to be related to this PR.

2023-03-28 21:11 UTC, kruai approved these changes
LGTM

2023-03-28 21:11 UTC, kruai commented on tests/helpers/test_utils.py
> +    system_profile = {
I meant something a bit more generic like `values={}` so you can overwrite any values in the SP, but this works too.

2023-03-28 21:11 UTC, kruai commented
/retest

2023-03-29 13:33 UTC, merged