feat(ESSNTL-4375) - Create POST /groups/<group-id>/hosts endpoint
RedHatInsights/insights-host-inventory pull request #1286
Opened 2023-03-08 15:13 UTC by fellipeh

This PR is being created to address ESSNTL-4375.
Adds the POST `/groups/{group_id}/hosts` endpoint. The post doc looks like the following:

```
[
  "host_id_1",
  "host_id_2",
  "host_id_3"
]
```
If the list is empty, it fails validation and returns 400. If "host_ids" is provided, the list of hosts will be associate to the group.

# Overview

This PR is being created to address [ESSNTL-xxxx](https://issues.redhat.com/browse/ESSNTL-xxxx).
(A description of your PR's changes, along with why/context to the PR, goes here.)

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-03-08 15:37 UTC, kruai requested changes
I have a few suggestions; this also needs tests.

2023-03-08 15:37 UTC, kruai commented on api/group_hosts.py
> +import flask
Do you think we need a separate file for the associations? If so:
- We should put [the corresponding DELETE function](https://github.com/RedHatInsights/insights-host-inventory/blob/master/api/group.py#L103) in here too
- We might wanna rename it to `host_group.py` to match the DB table name

2023-03-08 15:37 UTC, kruai commented on api/group_hosts.py
> +        assoc_list = replace_host_list_for_group(db.session, group_to_update, host_id_list)
This endpoint should add hosts to the group's existing list of hosts, not replace it

2023-03-08 15:37 UTC, kruai commented on swagger/api.spec.yaml
> +        Adds hosts list in body to provided group.
```suggestion
        Adds host list in request body to provided group.
```

2023-03-08 15:37 UTC, kruai commented on swagger/api.spec.yaml
> +        description: A dictionary with hosts IDs to associate to provided group.
```suggestion
        description: A list of hosts IDs to associate with the provided group.
```

2023-03-08 15:37 UTC, kruai commented on swagger/api.spec.yaml
> +          description: Successfully associatd hosts to group.
```suggestion
          description: Successfully associated hosts with group.
```

2023-03-08 15:37 UTC, kruai commented on api/group_hosts.py
> +def associate_hosts_by_group(group_id, body):
Given the delete function is named `delete_hosts_from_group`, I feel this would be clearer as `add_hosts_to_group`

2023-03-09 16:12 UTC, thearifismail commented on swagger/api.spec.yaml
> +      operationId: api.group_hosts.associate_hosts_by_group
The implementing method should be called `add_hosts_to_group`, which is direct and easy to understand.

2023-03-09 16:23 UTC, CodeHeeler reviewed
Overall looks good, agree with a lot of kruai's suggestions, added a few of my own.

2023-03-09 16:23 UTC, CodeHeeler commented on swagger/openapi.json
> +          "description": "Data required to associante host IDs to a group.",
typo, associate

2023-03-09 16:23 UTC, CodeHeeler commented on swagger/openapi.json
> +            "description": "Successfully associate Hosts to the Group.",
similar to kruai's suggestion above:
"description: Successfully associated hosts with group."

2023-03-09 16:23 UTC, CodeHeeler commented on swagger/openapi.json
> +        "operationId": "api.group_hosts.associate_hosts_by_group",
just a reminder that if you update the name as kruai suggested above, be sure to rename here as well: https://github.com/RedHatInsights/insights-host-inventory/pull/1286/files#r1129635075

2023-03-10 07:47 UTC, fstavela commented
/retest

2023-03-29 16:54 UTC, fellipeh commented
/retest

2023-03-31 11:08 UTC, FabriciaDinizRH requested changes

2023-03-31 11:08 UTC, FabriciaDinizRH commented on api/host_group.py
> +def delete_hosts_from_group(group_id, host_id_list):
on `lib/group_repository` there's a function that delete hosts from the group (the name is `remove_hosts_from_group`). You may look into merging/using these two functions

2023-03-31 11:08 UTC, FabriciaDinizRH commented on tests/test_api_host_group.py
> +    response_status, _ = api_add_hosts_to_group(group_id, [host for host in host_id_list[0:2]])
here you're using api_*add*_hosts_to_group, it should be the remove/delete method

2023-03-31 11:08 UTC, FabriciaDinizRH commented on tests/test_api_host_group.py
> +# def test_remove_hosts_from_nonexistent_group(db_create_group, db_create_host, api_remove_hosts_from_group):
Asa's patch tests might help you with these commented tests

2023-03-31 12:26 UTC, fellipeh commented on api/host_group.py
> +def delete_hosts_from_group(group_id, host_id_list):
Per discussion on Slack, I'll be removing `delete` methods from this PR.. making this PR only for `add`

2023-03-31 12:27 UTC, fellipeh commented on tests/test_api_host_group.py
> +# def test_remove_hosts_from_nonexistent_group(db_create_group, db_create_host, api_remove_hosts_from_group):
Per discussion on Slack, I'll be removing `delete` methods from this PR.. making this PR only for `add`

2023-03-31 19:08 UTC, fellipeh commented
/retest

2023-03-31 19:49 UTC, kruai requested changes
Looking good, though I left some recommendations. Also, there should be a test to validate the functionality when a group isn't found, and one for when a host isn't found

2023-03-31 19:49 UTC, kruai commented on tests/test_api_host_group.py
> +    response_status, _ = api_add_hosts_to_group(group_id, [str(host) for host in host_id_list[0:2]])
Why create 3 hosts and then only use 2?

2023-03-31 19:49 UTC, kruai commented on tests/test_api_host_group.py
> +    # Confirm API now allow to add the hosts, since it's already associated
```suggestion
    # Confirm that the API is not allowed to add the hosts, since they're already associated
```

2023-04-03 13:21 UTC, fellipeh commented on tests/test_api_host_group.py
> +    response_status, _ = api_add_hosts_to_group(group_id, [str(host) for host in host_id_list[0:2]])
The main goal here is to prove the endpoint will associate **only** the host ids provided, not all hosts in the table, that's the reason I created 3 hosts and associate only 2

2023-04-03 14:52 UTC, kruai commented
/retest

2023-04-03 17:47 UTC, fellipeh commented
/retest

2023-04-03 19:07 UTC, kruai requested changes
The implementation looks good; I still think it needs tests to cover the 2 scenarios I mentioned last time (one to validate the functionality when a group isn't found, and one for when a host isn't found)

2023-04-03 20:33 UTC, kruai commented on tests/test_api_host_group.py
> +    assert response_status == 400
I'm not sure about `test_add_missing_host_to_existing_group`, but it feels like this one should be returning 404, since it's unable to find the specified group it should add the hosts to. What do you think?

For `test_add_missing_host_to_existing_group` I'm more uncertain. The host is technically not found, but the group is found... as long as the 400 comes along with clear and useful information then it should be fine

2023-04-04 10:54 UTC, FabriciaDinizRH reviewed
It's looking good, I just had one more comment

2023-04-04 17:47 UTC, FabriciaDinizRH submitted a review, later dismissed
LGTM!

2023-04-04 18:19 UTC, kruai submitted a review, later dismissed

2023-04-05 08:22 UTC, fstavela commented
@fellipeh One of the unit tests failed: `test_add_missing_host_to_existing_group`

2023-04-05 12:29 UTC, fstavela commented
@fellipeh Here is what I found during testing: https://issues.redhat.com/browse/ESSNTL-4375?focusedId=22052551&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22052551

2023-04-11 13:55 UTC, thearifismail reviewed
there are three tests failing in `test_api_groups_update.py` 
```
((fellipeh) ) [aarif@damaan fellipeh]$ pytest --lf
========================================== test session starts ==========================================
platform linux -- Python 3.8.16, pytest-5.0.1, py-1.11.0, pluggy-0.13.1
rootdir: /home/aarif/Documents/dev-ws/insights/fellipeh, inifile: pytest.ini
plugins: cov-2.7.1, mock-3.1.1, subtests-0.3.2
collected 14 items / 10 deselected / 4 selected                                                         
run-last-failure: rerun previous 4 failures (skipped 175 files)

tests/test_api_groups_update.py FFFF                                                              [100%]

=============================================== FAILURES ================================================
__________________________________ test_patch_group_happy_path[True-0] __________________________________

db_create_group = <function db_create_group.<locals>._db_create_group at 0x7f280d866310>
db_create_host = <function db_create_host.<locals>._db_create_host at 0x7f280d866820>
db_get_group_by_id = <function db_get_group_by_id.<locals>._db_get_group_by_id at 0x7f280d866ee0>
api_patch_group = <function api_patch_group.<locals>._api_patch_group at 0x7f280da92280>, num_hosts = 0
patch_name = True

    @pytest.mark.parametrize(
        "num_hosts",
        [0, 3, 5],
    )
    @pytest.mark.parametrize("patch_name", [True, False])
    def test_patch_group_happy_path(
        db_create_group, db_create_host, db_get_group_by_id, api_patch_group, num_hosts, patch_name
    ):
        group = db_create_group("test_group")
        group_id = group.id
        orig_modified_on = group.modified_on
        assert len(db_get_group_by_id(group_id).hosts) == 0
    
        host_id_list = [str(db_create_host().id)]
    
        patch_doc = {"host_ids": host_id_list}
        if patch_name:
            patch_doc["name"] = "modified_group"
    
        response_status, response_data = api_patch_group(group_id, patch_doc)
        assert_response_status(response_status, 200)
        retrieved_group = db_get_group_by_id(group_id)
    
        if patch_name:
            assert retrieved_group.name == "modified_group"
        else:
            assert retrieved_group.name == "test_group"
    
        assert str(retrieved_group.hosts[0].id) == host_id_list[0]
    
        # Patch again with different hosts and re-validate
        host_id_list = [str(db_create_host().id) for _ in range(num_hosts)]
    
        patch_doc = {"host_ids": host_id_list}
        if patch_name:
            patch_doc["name"] = "modified_again"
    
        response_status, response_data = api_patch_group(group_id, patch_doc)
>       assert_response_status(response_status, 200)

tests/test_api_groups_update.py:50: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

response_status = 400, expected_status = 200

    def assert_response_status(response_status, expected_status=200):
>       assert response_status == expected_status
E       AssertionError

tests/helpers/api_utils.py:153: AssertionError
----------------------------------------- Captured stdout setup -----------------------------------------
Unable to configure watchtower logging.  Please verify watchtower logging configuration!
[2023-04-11 09:51:41,551] [6950] [139810322081600] [inventory.app] [INFO] Listening on API: /api/inventory/v1
[2023-04-11 09:51:41,551] [6950] [139810322081600] [inventory.app] [WARNING] WARNING: No API token was provided for Unleash server connection.  Feature flag toggles will default to their fallback values.
[2023-04-11 09:51:41,552] [6950] [139810322081600] [inventory.app] [WARNING] WARNING: The event producer has been disabled.  The message queue based event notifications have been disabled.
[2023-04-11 09:51:41,552] [6950] [139810322081600] [inventory.app] [WARNING] WARNING: The event producer has been disabled.  The message queue based notifications have been disabled.
[2023-04-11 09:51:41,552] [6950] [139810322081600] [inventory.app] [WARNING] WARNING: Using the NullProducer for the payload tracker producer.  No payload tracker events will be sent to to payload tracker.
[2023-04-11 09:51:41,552] [6950] [139810322081600] [inventory.app.payload_tracker] [INFO] Using injected producer object (<app.payload_tracker.NullProducer object at 0x7f280d852c40>) for PayloadTracker
----------------------------------------- Captured stdout call ------------------------------------------
Required Headers: %s {'x-rh-identity': b'eyJpZGVudGl0eSI6IHsiYWNjb3VudF9udW1iZXIiOiAidGVzdCIsICJvcmdfaWQiOiAidGVzdCIsICJ0eXBlIjogIlVzZXIiLCAiYXV0aF90eXBlIjogImJhc2ljLWF1dGgiLCAidXNlciI6IHsiZW1haWwiOiAidHVzZXJAcmVkaGF0LmNvbSIsICJmaXJzdF9uYW1lIjogInRlc3QifX19', 'content-type': 'application/json'}
[2023-04-11 09:51:41,810] [6950] [139810322081600] [inventory.api.group] [INFO] Patched group: 64788cf1-968e-4c80-b2a6-680f49bfe199
Required Headers: %s {'x-rh-identity': b'eyJpZGVudGl0eSI6IHsiYWNjb3VudF9udW1iZXIiOiAidGVzdCIsICJvcmdfaWQiOiAidGVzdCIsICJ0eXBlIjogIlVzZXIiLCAiYXV0aF90eXBlIjogImJhc2ljLWF1dGgiLCAidXNlciI6IHsiZW1haWwiOiAidHVzZXJAcmVkaGF0LmNvbSIsICJmaXJzdF9uYW1lIjogInRlc3QifX19', 'content-type': 'application/json'}
_________________________________ test_patch_group_happy_path[False-0] __________________________________

db_create_group = <function db_create_group.<locals>._db_create_group at 0x7f280d7a0700>
db_create_host = <function db_create_host.<locals>._db_create_host at 0x7f280d7a0790>
db_get_group_by_id = <function db_get_group_by_id.<locals>._db_get_group_by_id at 0x7f280d7a0820>
api_patch_group = <function api_patch_group.<locals>._api_patch_group at 0x7f280d872040>, num_hosts = 0
patch_name = False

    @pytest.mark.parametrize(
        "num_hosts",
        [0, 3, 5],
    )
    @pytest.mark.parametrize("patch_name", [True, False])
    def test_patch_group_happy_path(
        db_create_group, db_create_host, db_get_group_by_id, api_patch_group, num_hosts, patch_name
    ):
        group = db_create_group("test_group")
        group_id = group.id
        orig_modified_on = group.modified_on
        assert len(db_get_group_by_id(group_id).hosts) == 0
    
        host_id_list = [str(db_create_host().id)]
    
        patch_doc = {"host_ids": host_id_list}
        if patch_name:
            patch_doc["name"] = "modified_group"
    
        response_status, response_data = api_patch_group(group_id, patch_doc)
        assert_response_status(response_status, 200)
        retrieved_group = db_get_group_by_id(group_id)
    
        if patch_name:
            assert retrieved_group.name == "modified_group"
        else:
            assert retrieved_group.name == "test_group"
    
        assert str(retrieved_group.hosts[0].id) == host_id_list[0]
    
        # Patch again with different hosts and re-validate
        host_id_list = [str(db_create_host().id) for _ in range(num_hosts)]
    
        patch_doc = {"host_ids": host_id_list}
        if patch_name:
            patch_doc["name"] = "modified_again"
    
        response_status, response_data = api_patch_group(group_id, patch_doc)
>       assert_response_status(response_status, 200)

tests/test_api_groups_update.py:50: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

response_status = 400, expected_status = 200

    def assert_response_status(response_status, expected_status=200):
>       assert response_status == expected_status
E       AssertionError

tests/helpers/api_utils.py:153: AssertionError
----------------------------------------- Captured stdout call ------------------------------------------
Required Headers: %s {'x-rh-identity': b'eyJpZGVudGl0eSI6IHsiYWNjb3VudF9udW1iZXIiOiAidGVzdCIsICJvcmdfaWQiOiAidGVzdCIsICJ0eXBlIjogIlVzZXIiLCAiYXV0aF90eXBlIjogImJhc2ljLWF1dGgiLCAidXNlciI6IHsiZW1haWwiOiAidHVzZXJAcmVkaGF0LmNvbSIsICJmaXJzdF9uYW1lIjogInRlc3QifX19', 'content-type': 'application/ [...]

2023-04-11 13:55 UTC, thearifismail commented on tests/test_api_host_group.py
> +def test_add_associated_host_to_group(
What is an `associated_host` in `test_add_associated_host_to_group`?

2023-04-13 14:00 UTC, kruai commented on swagger/api.spec.yaml
> +        '200':
Should be 201 I think?

2023-04-13 16:41 UTC, fellipeh commented on api/host_group.py
> +    return flask_json_response(build_group_response(updated_group), status.HTTP_200_OK)
I changed per @fstavela requested on Jira.

2023-04-13 17:08 UTC, kruai commented on swagger/api.spec.yaml
> +        '200':
Oh nvm, thanks for clarifying!

2023-04-18 12:01 UTC, fellipeh commented on api/host_group.py
> +        assoc_list = add_host_list_for_group(db.session, group_to_update, host_id_list, throw_exception=False)
Removed

2023-04-18 16:04 UTC, kruai requested changes
Got a couple of notes. I can review `add_host_list_for_group` more thoroughly if it's needed, but I'm concerned about duplication

2023-04-19 18:46 UTC, CodeHeeler approved these changes
Looks good overall.  Agree with kruai's current suggestions.

2023-05-02 14:27 UTC, fellipeh commented on lib/group_repository.py
> +    return res
Thanks!

2023-05-02 14:29 UTC, fellipeh commented on lib/group_repository.py
> +    return assoc_list
After chat with Fabricia, we realize we have a difference between these two methods. Fabricia's  method need to raise exception if one of the hosts is already associated to the same group, and my just raise in different group. Changing Fabricia's code to adopt my logic will brake her code. So, we decided to keep both codes.

2023-05-02 14:40 UTC, CodeHeeler submitted a review, later dismissed

2023-05-02 14:52 UTC, fellipeh commented
/retest

2023-05-02 17:21 UTC, fellipeh commented
/retest

2023-05-02 18:26 UTC, kruai reviewed
I left a few notes, but here are my main takeaways:

- We need to standardize the behavior when adding hosts. It should either complain when you try to add a host that's already in a group, or it should ignore it; this should be the same across all endpoints IMO. Any opinion on this @fstavela?
- This code does not use `session_guard`, so changes are not rolled back upon error. For instance, if you try to add 2 hosts to a group, but the second host is already in a different group, host 1 will be successfully added to the group even though it returns HTTP 400.
- No MQ events are produced, so changes are not synced with Cyndi. 

Since this PR has been open for quite a while, I understand if you all think we should resolve these in a follow-up instead of keeping this one going, especially to avoid further merge conflicts. I'll leave my review as a comment instead of approve/request changes.

2023-05-02 18:26 UTC, kruai commented on lib/group_repository.py
> +    group_hosts_associated = db_get_hosts_assoc_for_group(group.id)
You can just get the associated host IDs from `group.hosts` instead of running another query

2023-05-02 18:26 UTC, kruai commented on lib/group_repository.py
> +    return Host.query.filter(Host.id.in_(host_ids))
This does the same thing as `get_host_list_by_id_list_from_db`, which is already imported and used in this file

2023-05-03 16:45 UTC, kruai approved these changes
I am OK with this code being merged, as long as the issues I mentioned in my previous review are addressed in a follow-up PR.

2023-05-03 17:46 UTC, FabriciaDinizRH approved these changes
I second Asa's comments, but let's merge this PR.

2023-05-03 18:13 UTC, kruai commented
Made a Jira to track the follow-up work: https://issues.redhat.com/browse/ESSNTL-4789

2023-05-03 18:13 UTC, merged

2023-05-04 08:17 UTC, fstavela commented
> I left a few notes, but here are my main takeaways:
> 
>     * We need to standardize the behavior when adding hosts. It should either complain when you try to add a host that's already in a group, or it should ignore it; this should be the same across all endpoints IMO. Any opinion on this @fstavela?

@kruai I agree. In my opinion, the endpoints should always complain when we want to add a host that's already in a different group. The only exception would be if I want to add a host that is already in the group to which I'm trying to add it to. The expected outcome (host being in that group) would be done, so there is probably no reason to error. And this behavior would match what PATCH does, because that, of course, also doesn't complain in this situation. It's discussed [here](https://issues.redhat.com/browse/ESSNTL-4375?focusedId=21960373&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-21960373).