feat(ESSNTL-3704, ESSNTL-4390): Add POST /groups endpoint
RedHatInsights/insights-host-inventory pull request #1287
Opened 2023-03-08 17:14 UTC by FabriciaDinizRH

# Overview

This PR is being created to address [ESSNTL-3704](https://issues.redhat.com/browse/ESSNTL-3704) and [ESSNTL-4390](https://issues.redhat.com/browse/ESSNTL-4390).

Add the POST /groups endpoint. The payload is as follows:
```
{
     "name": "test-host",
     "host_ids": []
}
```
`name` is mandatory but `host_ids` is optional.

I have improved the error messages in comparison to the first PR, but I noticed that API is the one that checks if the host_ids are valid based on the spec. In order for the API to accept invalid host_ids (and a group to be created even if the customer sends invalid ids), the spec would have to change.  More details about this issue [here](https://issues.redhat.com/browse/ESSNTL-4390) and [here](https://redhat-internal.slack.com/archives/CQFKM031T/p1676505465420629). I want to make sure that this change makes sense to everybody before going on with it.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [x] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [x] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-03-08 22:51 UTC, CodeHeeler submitted a review, later dismissed
Had one question/suggestion on the specific error code used, but otherwise looks great.  Very clean code, well thought out, addresses the problems raised in the jira discussion, and well tested.  Thank you!

2023-03-08 22:51 UTC, CodeHeeler commented on tests/test_api_groups_create.py
> +    group_data = {"name": "my_awesome_group"}
"my_awesome_group"
^ the best group :)

2023-03-08 22:51 UTC, CodeHeeler commented on api/group.py
> +            status.HTTP_406_NOT_ACCEPTABLE,
I'm not sure we should use a 406 here.  Usually we use a blanket 400, but if we wanted to be more granular than that since technically 400 is for bad syntax but here the syntax may be correct but the specific content is incorrect when compared to the schema, from what I'm seeing online, some use 409, some use 422, but 406 is being listed as a rarely used error that doesn't seem to match a schema validation error use case.

2023-03-09 10:18 UTC, vkrizan commented on lib/group_repository.py
> +            db_create_host_group_assoc(group_id=group.id, host_id=host_id)
This call adds hosts one by one with each immediately committed to db. Can you think of a better way to handle this association? Imagine million hosts being associated for a group.

2023-03-09 10:18 UTC, vkrizan commented on lib/group_repository.py
> +    created_group = Group.query.filter(Group.name == group_name, Group.org_id == current_org_id).one_or_none()
Is the group committed to db before the select here is done? Is the select even needed (can we trust the `new_group` model instance when it is written to db)?

2023-03-09 10:19 UTC, vkrizan commented on api/group.py
> +logger = get_logger(__name__)
Duplicated on line 31.

2023-03-09 14:05 UTC, FabriciaDinizRH commented on lib/group_repository.py
> +    created_group = Group.query.filter(Group.name == group_name, Group.org_id == current_org_id).one_or_none()
since it was within the same session, the select will return the group even if it was not committed yet (which I now see can be a problem if something's wrong and the session rollbacks). I have improved this part. 
The select is needed to get the `group_id` to associate the hosts with the group.

2023-03-09 14:14 UTC, vkrizan commented
![image](https://user-images.githubusercontent.com/7695766/224051224-22217cec-1865-4cf3-bced-cc738bd0b4b2.png)

@FabriciaDinizRH I highly recommend to utilize Git fixup (and force-push) to clean up PRs before they get merged. https://itnext.io/git-fixup-your-commit-e1047f2fb966

2023-03-09 14:21 UTC, kruai requested changes

2023-03-09 14:21 UTC, kruai commented on lib/group_repository.py
> +            db_create_host_group_assoc(group_id=group.id, host_id=host_id)
The main reason we'd want to do it this way is so we can send updates to the inventory.events Kafka topic, and stop+rollback upon MQ failure. That hasn't been finalized yet, though; it might actually be best to send the list of hosts to add/remove as a list in one kafka message. What do y'all think?

2023-03-09 14:21 UTC, kruai commented on api/group.py
> +        )
Feels like bad practice to catch any exception that could occur and then tell the user it's their fault :)
Also, if it could be any type of Exception, we don't know that it'll have the field `e.messages`.

2023-03-09 14:21 UTC, kruai commented on lib/group_repository.py
> +    current_account = get_current_identity().account_number
This should probably be defined in the same place as the `org_id`. Personally, I prefer having them both defined in `add_group` and passed into `_add_group`, so that you're passing in all the fields required to make a Group.

2023-03-09 14:21 UTC, kruai commented on tests/test_api_groups_create.py
> +    group_data = {"name": "my_awesome_group"}
Is this valid? It's my understanding that you're supposed to pass the full object to a POST, which would lead me to expect something like this:
```suggestion
    group_data = {"name": "my_awesome_group", "host_ids": []}
```

2023-03-09 14:21 UTC, kruai commented on tests/test_api_groups_create.py
> +    assert_response_status(response_status, expected_status=201)
The response data should be validated as well, to make sure that the structure is correct and that the group is being properly serialized.

2023-03-09 14:21 UTC, kruai commented on tests/test_api_groups_create.py
> +    assert_response_status(response_status, expected_status=201)
This response data should be validated as well

2023-03-09 14:30 UTC, vkrizan commented on lib/group_repository.py
> +            db_create_host_group_assoc(group_id=group.id, host_id=host_id)
I'd recommend here to do a bach update(s). Can you elaborate on the Kafka events (through Slack or other forum)?

2023-03-09 14:34 UTC, FabriciaDinizRH commented on lib/group_repository.py
> +            db_create_host_group_assoc(group_id=group.id, host_id=host_id)
I'll ask @kruai to weight in on this, because from what I can tell from the patch endpoint (and from all the hosts endpoints), in the future we are going to emit a kafka event for each of the assoc created, so I think we have to do that one by one.

2023-03-09 14:51 UTC, vkrizan commented on lib/group_repository.py
> +            db_create_host_group_assoc(group_id=group.id, host_id=host_id)
@kruai Do we have requirements for these Kafka events? I think we would need to reassess their design. Sending it one by one would create a storm :cloud_with_lightning: .

2023-03-09 14:52 UTC, vkrizan commented on lib/group_repository.py
> +            db_create_host_group_assoc(group_id=group.id, host_id=host_id)
@FabriciaDinizRH Changing how we insert it to db doesn't have an impact to how Kafka events would be produced. That would likely be a post-process after a successful assignment (unless the MQ failure is critical for this to be reverted).

2023-03-09 15:56 UTC, thearifismail commented on api/group.py
> +from app.models import CreateGroupSchema
Should rename to `GroupSchema` because `CreateGroupSchema` sounds like a method and not a class.  Furthermore there is not class or function named `GroupSchema`

2023-03-09 15:56 UTC, thearifismail commented on app/instrumentation.py
> +def log_add_group_succeeded(logger, group_id, control_rule):
Should choose either `add` or `create` group and that should be used consistently across multiple modules.  For logging "log_add_group_*" is being used but the group.py has `create_group`

2023-03-09 15:56 UTC, thearifismail commented on lib/group_repository.py
> +            db_create_host_group_assoc(group_id=group.id, host_id=host_id)
I like the idea of creating hosts in batches but playing devil's advocate here.  One of the challenges inventory has is hosts in DB getting out of sync with Elasticsearch index.  When using batch additions/updates, say 100 hosts;  before all 100 hosts are added, a problem occurs.  Now accounting for what host got added and what host was not could be tricky issue to deal with.

2023-03-09 15:56 UTC, thearifismail commented on lib/group_repository.py
> +    new_group = Group(name=group_name, org_id=org_id, account=current_account)
`org_id` should be retrieved from the identity the same way was account to avoid problems caused by difference between the passed in org_id and the one in the identity providing account number

2023-03-09 15:56 UTC, thearifismail commented on tests/test_api_groups_create.py
> +import pytest
Need tests creating hosts by providing a group id and not providing one.
Create groups by providing non-existent-hosts

2023-03-09 15:56 UTC, thearifismail commented on tests/test_api_groups_delete.py
Need a test to delete a group with hosts in it.

2023-03-09 16:59 UTC, vkrizan commented on lib/group_repository.py
> +            db_create_host_group_assoc(group_id=group.id, host_id=host_id)
That out-of sync problem would occur regardless of the insertion method. AFAIK Elastic taps into binary log of a database. Indexing would still need to be done for each host association.

2023-03-09 21:08 UTC, FabriciaDinizRH commented on api/group.py
> +        )
Yeah, I think I went to the other extreme there in trying to capture exceptions.

2023-03-10 07:47 UTC, fstavela commented
/retest

2023-03-10 13:55 UTC, kruai commented on api/group.py
> +from app.models import CreateGroupSchema
I think it's being named `CreateGroupSchema` to differentiate from `PatchGroupSchema`

2023-03-10 14:16 UTC, kruai commented on tests/test_api_groups_delete.py
That's not related to the POST /groups endpoint, though

2023-03-10 14:20 UTC, kruai commented on tests/test_api_groups_create.py
> +import pytest
Since you can't specify the group_id when creating a new group, putting group_id on the POST body would be the same as adding `"foo": "bar"` to the payload. Is the goal to test whether extra fields are rejected?

2023-03-14 15:51 UTC, FabriciaDinizRH commented on api/group.py
> +from app.models import CreateGroupSchema
Which just made me realize we don't need both haha

2023-03-15 10:02 UTC, vkrizan commented on api/group.py
> +        log_create_group_succeeded(logger, created_group.id, get_control_rule())
`get_control_rule()` call is repeated for each log message.

2023-03-16 20:58 UTC, kruai requested changes
I just have a couple more comments!

2023-03-17 11:16 UTC, fstavela commented
I shared my findings in a Jira comment: https://issues.redhat.com/browse/ESSNTL-4390?focusedId=21931326&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-21931326

2023-03-17 12:26 UTC, vkrizan reviewed
Looks good Fabricia. The exception handling might need to be looked at before merging.
Thank you.

2023-03-20 11:54 UTC, FabriciaDinizRH commented on api/group.py
> +        )
That must've come back in some of the conflicts, removing again.

2023-03-23 08:54 UTC, fstavela reviewed
@FabriciaDinizRH  Thank you for addressing all of the issues! I left just a few last comments.

2023-03-23 08:54 UTC, fstavela commented on lib/group_repository.py
> +        host = Host.query.filter(Host.account == current_account, Host.id == host_id).one_or_none()
I think we should check for org_id here instead of account number because an account number is not required anymore so it is possible that a host's account number is `None`.

2023-03-23 08:54 UTC, fstavela commented on lib/group_repository.py
> +        db.session.commit()
Should this `commit` be here? Would it be better to commit after we add hosts to group, or even let the `session_guard` commit for us?

2023-03-28 08:58 UTC, fstavela commented on lib/group_repository.py
> +        )
```suggestion
    # Check if the hosts exist in Inventory and correct account
    host_query = Host.query.filter((Host.org_id == current_org_id) & Host.id.in_(host_id_list)).all()
    found_ids_set = {str(host.id) for host in host_query}
    if found_ids_set != set(host_id_list):
        nonexistent_hosts = set(host_id_list) - found_ids_set
        log_host_group_add_failed(logger, nonexistent_hosts, group_id)
        raise InventoryException(
            title="Invalid request", detail=f"Could not find an existing host(s) with ID {nonexistent_hosts}."
        )
```
What do you say about something like this? The original check query would catch hosts in different account, but it wouldn't catch non-existing hosts, which then return error "A group with host list ['290fec21-f2b1-49df-92af-3194c667cac2'] already exists.", because it will pass this and fail on DB addition.

2023-03-28 08:58 UTC, fstavela commented on lib/group_repository.py
> +        )
Also, can we move this check above the check for already assigned hosts? That way we can return this error message even if we try to add a host from different account which is already assigned to a group.

2023-03-28 12:52 UTC, fstavela commented on lib/group_repository.py
> +        log_host_group_add_failed(logger, taken_hosts, group_id)
```suggestion
        log_host_group_add_failed(logger, host_id_list, group_id)
```
I'm not sure about this, so feel free to ignore this suggestion if you think we should only log the bad hosts.

2023-03-28 16:23 UTC, FabriciaDinizRH commented on lib/group_repository.py
> +        )
hahaha, that looks a lot like what I had written before changing to this version I committed. I'll change back to what you have suggested

2023-03-28 16:26 UTC, FabriciaDinizRH commented on api/group.py
> +                "type": "unknown",
I'm not sure. I copied the response used in `patch_group_by_id`.

2023-03-28 19:14 UTC, FabriciaDinizRH commented on lib/group_repository.py
> +        taken_hosts = [assoc.host_id for assoc in assoc_query]
corrected that

2023-03-28 19:15 UTC, FabriciaDinizRH commented on api/group.py
> +                "type": "unknown",
I started a discussion on slack regarding this, no one know why it exists and nothing breaks when I take it out, so I took it out.

2023-03-28 19:28 UTC, FabriciaDinizRH commented on api/group.py
> +            {
I put the responses now as flask responses and regarding the errors.
The Integrity error is already covered in the model tests and I'm not sure how to test the Inventory exception since it would be basically repeating the tests that I already have but checking for something else. The other tests for the groups endpoints also check for the response error status rather than for specific exceptions, so I followed the general trend, testing all these scenarios but checking only the final response.

2023-03-28 19:32 UTC, FabriciaDinizRH commented on api/group.py
> +            {
The way that we have been testing exceptions in Inventory is by catching exceptions that haven't been dealt with, so that's why I can't catch the exception in the existing tests, they test the whole API functionality and the functionality deals with its  expected exceptions.

2023-03-29 22:50 UTC, FabriciaDinizRH commented
/retest

2023-03-30 17:03 UTC, kruai approved these changes
LGTM!

2023-03-30 17:16 UTC, CodeHeeler approved these changes
LGTM. Great job responding to all the feedback. Good clean work. Thanks!

2023-03-30 17:38 UTC, merged