[ESSNTL-4398] Update schema to reference list of hosts
RedHatInsights/insights-host-inventory pull request #1295
Opened 2023-03-24 21:59 UTC by CodeHeeler

# Overview

This PR is being created to address [ESSNTL-4398](https://issues.redhat.com/browse/ESSNTL-4398).
Some of the schema descriptions for host update endpoints incorrectly used the singular "host" when a list of "hosts" is what is actually provided as a parameter.  In future, we may revisit this as the primary user (the UI) only ever uses a single host at a time, and if we update the code to no longer use a list, we will update the API schema version to v2, but for now, we are only updating the language used in the descriptions to accurately reflect the code and updating the unit test to check for updating multiple hosts instead of a single host.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-03-27 12:12 UTC, kruai requested changes

2023-03-27 12:12 UTC, kruai commented on swagger/api.spec.yaml
> +      summary: Get the number of tags on a host or hosts
Just for consistency with your other changes:
```suggestion
      summary: Get the number of tags on the hosts
```

2023-04-20 14:09 UTC, thearifismail submitted a review, later dismissed
LGTM

2023-04-24 14:42 UTC, thearifismail approved these changes

2023-04-25 13:50 UTC, kruai approved these changes

2023-04-25 15:01 UTC, merged