Add readme for debugging api code using k8s resources
RedHatInsights/insights-host-inventory pull request #1305
Opened 2023-04-19 21:58 UTC by thearifismail

# Overview

This PR adds a reame.md document for how to set up local development environment for debugging local code using resources deployed in a K8S resources.  This is applicable to internal development for now.  

The reason for writing this document is that developers can create hosts using `make run_inv_mq_service_test_producer` task in the make file and then get the newly created host using `curl`.  Due to the removal searches using DB, it was not possible.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-04-20 06:39 UTC, strider commented on docs/connect_to_k8s_env.md
> +Debugging the Host Inventory API code needs database, kakfa broker, Kafka Zookeeper, Debezium Connector, and xjoin-search.  Following is a list high level steps necessary to debug local API code usin
Following is a list **of** high level steps

2023-04-20 06:40 UTC, strider commented on docs/connect_to_k8s_env.md
> +1. Login to Epheremal cluster.
`s/Epheremal/Ephemeral/`

2023-04-20 06:42 UTC, strider commented on docs/connect_to_k8s_env.md
> +This section describes how to launch debugger using `vscode` to execute the local API server which in turn uses resources deployed in the ephemeral namespace.
`s/vscode/VS Code/`

2023-04-20 06:44 UTC, strider commented on docs/connect_to_k8s_env.md
> +1. Load the `host-inventory` project to vscode
`s/vscode/VS Code/`

2023-04-20 06:45 UTC, strider commented on docs/connect_to_k8s_env.md
> +2. Add a launch configuration to run the api-server (run.py) with the following environment variables:
Use backticks for `run.py` Python script.

2023-04-20 07:27 UTC, strider commented on docs/connect_to_k8s_env.md
> +Debugging the Host Inventory API code needs database, kakfa broker, Kafka Zookeeper, Debezium Connector, and xjoin-search.  Following is a list high level steps necessary to debug local API code usin
Extra space before the second sentences starting by `Following`

2023-04-20 07:32 UTC, strider requested changes
Just a few minors issues. Otherwise, it looks good to me.

2023-04-20 12:53 UTC, jpramos123 reviewed
some suggestions

tested and this works just fine

2023-04-20 13:03 UTC, kruai requested changes
Had a couple comments in addition to the existing suggestions. Thanks for writing this up!

2023-04-20 17:50 UTC, CodeHeeler approved these changes
LGTM

2023-04-20 18:46 UTC, kruai approved these changes

2023-04-22 09:29 UTC, strider approved these changes
LGTM

2023-04-22 09:41 UTC, strider requested changes

2023-04-22 09:41 UTC, strider commented on README.md
> +Instructions for setting up development environment for stepping through API code is provided [here](docs/connect_to_k8s_env.md)
Run `pre-commit run --all-files` to fix the end of files hook!

![image](https://user-images.githubusercontent.com/242115/233776228-ddaacb9d-501b-4abe-8f6f-deb538bc8ef4.png)

2023-04-24 17:25 UTC, strider approved these changes

2023-04-24 17:26 UTC, merged