[ESSNTL 4873]: Add assignment_rules table and ORM
RedHatInsights/insights-host-inventory pull request #1377
Opened 2023-05-31 15:00 UTC by FabriciaDinizRH

Related: ESSNTL-4873

# Overview

This PR is being created to address [ESSNTL-4873](https://issues.redhat.com/browse/ESSNTL-4873).
PR in draft for people to check the revision and model. 

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-06-02 15:26 UTC, FabriciaDinizRH commented
/retest

2023-06-06 07:59 UTC, fstavela commented
/retest

2023-06-08 13:35 UTC, kruai commented
Note: We had to merge a new migration to fix a data issue, so references to the down-revision (`b48ad9e4c8c5`) will need to be changed to `8277117fa057`.

2023-06-08 15:42 UTC, kruai requested changes
Looking good - just a few suggestions

2023-06-08 15:42 UTC, kruai commented on tests/test_models.py
> +    ar = db_create_assignment_rule("default assignment", group.id, {"facts": {"fqdn": "54321"}})
I elaborated a bit about my idea for the structure in the Jira, but it shouldn't make a difference for these tests, as long as they're in JSON format.

2023-06-08 15:42 UTC, kruai commented on tests/test_models.py
> +    ar = db_create_assignment_rule("default assignment", group.id, {"facts": {"fqdn": "54321"}})
Side note: I think "dummy" is a word that may be considered insensitive, and is recommended that we use `placeholder` or `sample` instead

2023-06-08 15:42 UTC, kruai commented on app/models.py
> +    __table_args__ = (Index("idxassrulesorgid", "org_id"),)
hehe (I think this is the correct way to abbreviate it though, no need to modify)

2023-06-08 15:42 UTC, kruai commented on migrations/versions/1689cda89252_add_assignment_rules_table.py
> +Revises: b48ad9e4c8c5
```suggestion
Revises: 8277117fa057
```

2023-06-08 15:42 UTC, kruai commented on migrations/versions/1689cda89252_add_assignment_rules_table.py
> +down_revision = "b48ad9e4c8c5"
```suggestion
down_revision = "8277117fa057"
```

2023-06-13 12:50 UTC, fstavela requested changes
Just a small detail, otherwise looks good.

2023-06-13 12:50 UTC, fstavela commented on app/models.py
> +    updated_on = db.Column(db.DateTime(timezone=True), default=_time_now, onupdate=_time_now)
Just to keep it consistent with other DB tables, I would rename this to `modified_on`.

Although, in the API we use `updated`, so there already is some level of inconsistency. @kruai @FabriciaDinizRH What do you think, should we use `updated_on` or `modified_on`?

2023-06-13 13:02 UTC, kruai commented on migrations/versions/1689cda89252_add_assignment_rules_table.py
> +Revises: b48ad9e4c8c5
Never mind - we undid that change, so I'm resolving this

2023-06-13 13:03 UTC, kruai commented on migrations/versions/1689cda89252_add_assignment_rules_table.py
> +down_revision = "b48ad9e4c8c5"
Never mind - we undid that change, so I'm resolving this

2023-06-13 13:23 UTC, kruai commented on app/models.py
> +    updated_on = db.Column(db.DateTime(timezone=True), default=_time_now, onupdate=_time_now)
Good call. I don't think we should do `updated_on`, since that's a third variation we'll have to keep track of. I think `modified_on` makes the most sense for consistency across DB tables. I'd definitely hear an argument for `updated` as well though if y'all prefer that

2023-06-22 18:07 UTC, thearifismail commented on app/models.py
> +    def update_modified_on(self):
Adding introducing a new attribute after the object has been initialized does not sound right.  The `__init__()` should have `self.modified_on = None` and `self.created_on = None`.

2023-06-22 18:36 UTC, thearifismail reviewed
over looks good.  some minor comments.

2023-06-22 21:26 UTC, kruai commented on tests/helpers/db_utils.py
> +    if "org_id" in values:
It's the same as what we do in other creation functions, for the sake of simplicity when writing tests. `org_id` is required to exist on the object, but we don't want to be required to supply it every time we create one; you can pass in an `org_id` to override the value if you need, but otherwise it just defaults to the one in USER_IDENTITY

2023-06-23 13:15 UTC, kruai commented on app/models.py
> +    def update(self, input_ar):
I think it's named `input_ar` to be explicit that it's the assignment rule that's being input, rather than the assignment rule that's being updated. Its naming is also consistent with every other `update` function in `models.py`.

2023-06-23 13:18 UTC, kruai commented on app/models.py
> +    def update_modified_on(self):
That's fair. The only reason we have it for Group is because there were certain situations where we needed the `modified_on` date to updated even when the Group object didn't technically change (for instance, adding or removing a Host to a Group). I don't think that applies to assignment rules, so I'll remove this method.

2023-06-23 14:47 UTC, thearifismail approved these changes
LGTM!

2023-06-23 15:08 UTC, jpramos123 approved these changes
LGTM!

Tested and table is created correctly  and tests are passing

2023-06-23 15:50 UTC, kruai approved these changes

2023-06-23 15:51 UTC, merged