fix(ESSNTL-4458): Fix too old date on filter
RedHatInsights/insights-host-inventory pull request #1386
Opened 2023-06-09 17:47 UTC by fellipeh

# Overview

This PR is being created to address [ESSNTL-4458](https://issues.redhat.com/browse/ESSNTL-4458).

Elastic Search doesn't allow date before 1970, returned message from ES:
```
date[0199-03-04T04:56:02Z] is before the epoch in 1970 and cannot be stored in nanosecond resolution
```
so,  If the date args is before 1970, remove from filters query.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-06-09 18:46 UTC, thearifismail reviewed
See the comment

2023-06-09 18:46 UTC, thearifismail commented on tests/test_api_hosts_get.py
> +    ("?updated_start=0199-03-04T04%3A56%3A02.000Z&updated_end=0199-03-04T04%3A56%3A02.000Z"),
For readability, add comment containing the `update_start` and `update_end` times in plain text, i.e. decoded values.

2023-06-12 12:39 UTC, kruai requested changes

2023-06-12 12:39 UTC, kruai commented on api/filtering/filtering.py
> +        # allow query above this year. See ticket #ESSNTL-4458
```suggestion
        # allow timestamps before this year. See ticket #ESSNTL-4458
```

2023-06-12 12:39 UTC, kruai commented on api/filtering/filtering.py
> +            query_filters += _build_modified_on_filter(updated_start, updated_end)
If `updated_start` is set to 1965 and `updated_end` is set to 2005, this code won't add either filter. I think that only the invalid filter should be dropped, not both

2023-06-12 12:39 UTC, kruai commented on tests/test_api_hosts_get.py
> +    assert_response_status(response_code, 200)
Since our xjoin requests are mocked, this tests nothing - the test would still pass without the new code changes. In order to test this, I recommend using the `graphql_query_empty_response` fixture and validating that only the proper filters were added to the xjoin request. There are a lot of examples of this in `test_xjoin.py`; let me know if you need any more details.

2023-06-12 12:57 UTC, fstavela commented
Based on the tests results, we are getting errors 500 whenever we try to one of the `updated` filters without the other. For example, if I just want to filter by `updated_start` and I don't provide `updated_end`.

2023-06-20 20:57 UTC, kruai commented on tests/test_xjoin.py
> +    assert response_status == 200
If the `updated_end` date is before the `updated_start` date, I'd actually expect it to respond with a 403 saying `updated_start cannot be after updated_end`. Otherwise, we're showing them records from after 2001, when they said they don't want to see records from before the year 199

2023-06-20 21:10 UTC, fellipeh commented on tests/test_xjoin.py
> +    assert response_status == 200
In this particular case, the `updated_end` is not valid (is less than 1970) so, it's removed from the query, before, the checking if the `updated_end` is before.  If we pass `updated_end` > 1970  and  before `updated_start`  will return and Value error, see here: https://github.com/RedHatInsights/insights-host-inventory/blob/master/api/filtering/filtering.py#L313

2023-06-23 12:54 UTC, thearifismail commented on tests/test_xjoin.py
> +    assert response_status == 200
A test is needed with end date before the start date and to verify 403 is returned in response.

2023-06-23 13:11 UTC, kruai commented on tests/test_xjoin.py
> +    assert response_status == 200
@fellipeh I know it's removed from the query on the backend to bypass the elasticsearch restriction, but it introduces inconsistency from the behavior that the user sees. Basically, it would allow the user to set the `updated_end` to an earlier date than `updated_start` if they use a date earlier than 1970, but it would error out otherwise. It's definitely an edge case but I feel like we should be consistent with not allowing the end date to be before the start date

2023-06-23 13:49 UTC, jpramos123 commented on tests/test_xjoin.py
> +    assert response_status == 200
@fellipeh @kruai I agree we need to validate and make sure `update_end` is before `update_start`.

2023-06-23 13:53 UTC, jpramos123 requested changes
Added some suggestions!

2023-06-23 13:53 UTC, jpramos123 commented on api/filtering/filtering.py
> +                updated_end=updated_end if parser.isoparse(updated_end).year > 1970 else None,
Do we need this redundant validation here?
```suggestion
                updated_start=updated_start
                updated_end=updated_end
```

2023-06-23 13:53 UTC, jpramos123 commented on api/filtering/filtering.py
> +        if parser.isoparse(updated_start).year > 1970 or parser.isoparse(updated_end).year > 1970:
Can we add a validation statement to make sure `update_start` is not before `update_end`?

If it is, maybe return an error message?

2023-06-23 13:58 UTC, kruai commented on api/filtering/filtering.py
> +        if parser.isoparse(updated_start).year > 1970 or parser.isoparse(updated_end).year > 1970:
We already have that validation; it happens inside `_build_modified_on_filter` here: https://github.com/RedHatInsights/insights-host-inventory/blob/sp-update/api/filtering/filtering.py#L314

2023-06-23 14:38 UTC, fellipeh commented on api/filtering/filtering.py
> +                updated_end=updated_end if parser.isoparse(updated_end).year > 1970 else None,
@jpramos123 yes, because we need to pass `None` to the parameter to avoid to create an filter with that, resulting with and empty: `modified_on: {}` on graphql query (in case both params are None).

2023-06-23 14:40 UTC, fellipeh commented on tests/test_xjoin.py
> +    assert response_status == 200
@jpramos123 it's already validated here: https://github.com/RedHatInsights/insights-host-inventory/blob/sp-update/api/filtering/filtering.py#L314

2023-06-23 16:00 UTC, kruai commented on api/filtering/filtering.py
> +                updated_end=updated_end if parser.isoparse(updated_end).year > 1970 else None,
This logic could instead be put inside `_build_modified_on_filter`, which would be a bit cleaner (and the code would be simpler). The dates already get isoparsed at the beginning of that function, so you could just put the 1970 check in [this condition](https://github.com/RedHatInsights/insights-host-inventory/blob/master/api/filtering/filtering.py#L316), or between the `start > end` check and the part where the `modified_on_filter` gets populated

2023-06-27 19:40 UTC, kruai requested changes

2023-06-27 19:40 UTC, kruai commented on api/filtering/filtering.py
> +                updated_end=updated_end if parser.isoparse(updated_end).year > 1970 else None,
I still think this suggestion would simplify the code and make the behavior more consistent ^

2023-06-27 19:40 UTC, kruai commented on tests/test_xjoin.py
> +    assert response_status == 200
My above suggestion still stands; the request in this should return HTTP 400 since `updated_end` is before `updated_start`

2023-06-30 15:23 UTC, kruai requested changes
The implementation looks good! Just had a few more comments on the test; `graphql_query_with_response` doesn't make any assertions

2023-06-30 15:23 UTC, kruai commented on tests/test_xjoin.py
> +    graphql_query_empty_response.graphql_query_with_response(
```suggestion
    graphql_query_empty_response.assert_called_once_with(
```

2023-06-30 15:23 UTC, kruai commented on tests/test_xjoin.py
> +    )
Since the request resulted in an HTTP 400, the code should not be making any graphql queries.

2023-06-30 15:23 UTC, kruai commented on tests/test_xjoin.py
> +    graphql_query_empty_response.graphql_query_with_response(
```suggestion
    graphql_query_empty_response.assert_called_once_with(
```

2023-06-30 15:53 UTC, kruai submitted a review, later dismissed
LGTM!

2023-06-30 18:40 UTC, kruai approved these changes

2023-07-05 09:49 UTC, FabriciaDinizRH commented
/retest

2023-07-05 12:28 UTC, thearifismail approved these changes
LGTM

2023-07-05 14:24 UTC, FabriciaDinizRH approved these changes

2023-07-06 15:09 UTC, jpramos123 approved these changes
LGTM

2023-07-06 15:24 UTC, merged