ESSNTL-4929: fix for updating time when a group is touched
RedHatInsights/insights-host-inventory pull request #1409
Opened 2023-06-27 22:15 UTC by thearifismail

# Overview

This PR is being created to address [ESSNTL-4929](https://issues.redhat.com/browse/ESSNTL-4929).
This PR fixes the bug and adds a test to verify the fix.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-06-27 23:13 UTC, FabriciaDinizRH reviewed
the code looks ok but some tests are breaking

2023-06-28 17:23 UTC, kruai requested changes

2023-06-28 17:23 UTC, kruai commented on api/host_group.py
> +        update_group_update_time(group_id)
The group's timestamp should be updated in the same transaction as when the hosts are added to it. So, the change should happen within the `session_guard` inside `add_hosts_to_group`.

2023-06-28 17:23 UTC, kruai commented on api/host_group.py
> +    update_group_update_time(group_id)
Same as above: the group's timestamp should be updated within the same transaction as when the hosts are removed, so it should happen within `remove_hosts_from_group`.

2023-06-28 17:23 UTC, kruai commented on lib/group_repository.py
> +        db.session.commit()
We already have a function that updates the `modified_on` date. All you need to do is call `group.update_modified_on()`; see the usage [here](https://github.com/RedHatInsights/insights-host-inventory/blob/master/lib/group_repository.py#L250) for reference

(Also, this function doesn't return a `Group` object even though the type hint says it does)

2023-06-28 17:23 UTC, kruai commented on tests/test_api_host_group.py
> +
We already have multiple tests that validate adding hosts to a group. Can you just add the "updated" check to one of those tests, instead of duplicating it?
You should also add that check to one of the tests for `delete_hosts_from_group` to make sure that's covered.

2023-06-29 22:23 UTC, thearifismail commented
/retest

2023-06-29 22:53 UTC, thearifismail commented
/retest

2023-06-30 16:14 UTC, kruai requested changes
Looking better; I've just got a couple more suggestions

2023-06-30 16:14 UTC, kruai commented on lib/group_repository.py
> +    return group
A couple things:

- Since we always need to add the group to the session, we might as well refactor that into this function.
- Do we actually need to do `db.session.flush()`? If so, we should put that in this function as well; if not, we should remove it.
- Now that there's a new function for this, we should refactor the code that was originally updating the group timestamp (https://github.com/RedHatInsights/insights-host-inventory/blob/master/lib/group_repository.py#L250-L251)

2023-06-30 20:11 UTC, thearifismail commented
/retest

2023-06-30 20:58 UTC, kruai approved these changes
As I mentioned in my previous review, I'd prefer if we switched out my original timestamp-updating code to reference your new function: https://github.com/RedHatInsights/insights-host-inventory/blob/master/lib/group_repository.py#L250-L251
But, I'm not going to hold up the PR just for that.

2023-06-30 21:19 UTC, merged