Essntl 4877 draft
RedHatInsights/insights-host-inventory pull request #1415
Opened 2023-07-07 23:29 UTC by thearifismail

# Overview

This PR is being created to address [ESSNTL-xxxx](https://issues.redhat.com/browse/ESSNTL-xxxx).
(A description of your PR's changes, along with why/context to the PR, goes here.)

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-07-11 10:35 UTC, FabriciaDinizRH commented on api/assignment_rule.py
> +        log_get_group_list_failed(logger)
should this be a `log_get_assignment_rule_list_failed()`?

2023-07-11 12:34 UTC, thearifismail commented on api/assignment_rule.py
> +        log_get_group_list_failed(logger)
Fixed!

2023-07-13 13:05 UTC, roliveri commented on swagger/api.spec.yaml
> +        Required permissions: inventory:assignment-rules:read
@kruai and I discussed this. I believe we concluded that, since assignment rules are part of the group feature, it should use the group rbac permissions. Is that right @kruai ?

2023-07-14 14:05 UTC, jpramos123 requested changes
Adding some suggestions.

Thanks for the PR

2023-07-14 14:05 UTC, jpramos123 commented on api/__init__.py
> +    return {"error": title, "detail": detail, "status": status}
We need to return a `flask_json_response` with the status code. Otherwise it will always return `200` in the response status.

```suggestion
    return flask_json_response({"error": title, "detail": detail, "status": status}, status)
```

Take a look at: https://github.com/RedHatInsights/insights-host-inventory/pull/1418/files#diff-d8438cdb658524a2b6e086de042e2cd85ef375b8584204e05e09fd7a0128ce62

2023-07-20 17:10 UTC, jpramos123 approved these changes

2023-07-20 22:16 UTC, thearifismail commented
Replaced by https://github.com/RedHatInsights/insights-host-inventory/pull/1429

2023-07-20 22:16 UTC, closed without merging