[ESSNTL-4876] - Create POST /assignment-rules endpoint
RedHatInsights/insights-host-inventory pull request #1418
Opened 2023-07-11 17:04 UTC by jpramos123

# Overview

This PR is being created to address [ESSNTL-4876](https://issues.redhat.com/browse/ESSNTL-4876).

Creat POST request method to create Assignment Rule object in the DB.

Todos:
1. Create tests

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [x] Input Validation
- [x] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [x] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

2023-07-11 17:49 UTC, jpramos123 commented on lib/assignment_rule_repository.py
> +def add_assignment_rule(assign_rule_data, event_producer) -> AssignmentRule:
@kruai @thearifismail Should we trigger event_producer?

2023-07-11 20:20 UTC, thearifismail reviewed
`api/assignment-rule.py` missing `rbac` and `metics` decorators
Needs `tests`.

2023-07-11 20:20 UTC, thearifismail commented on api/assignment_rule.py
> +
Needs `rbac` decorator, like
```
@api_operation
@rbac(RbacResourceType.GROUPS, RbacPermission.READ)
@metrics.api_request_time.time()
def get_assignment_rule_list(
```

2023-07-11 20:20 UTC, thearifismail commented on api/__init__.py
> +def _error_json_response(title, detail, status=status.HTTP_400_BAD_REQUEST):
all generic funtions should have been in `utils/utility.py` file.  `__init.py__` does not look an ideal module for these functions.

2023-07-11 20:52 UTC, kruai commented on api/__init__.py
> +def _error_json_response(title, detail, status=status.HTTP_400_BAD_REQUEST):
Can you elaborate? Our utils folder has always been used for random manual helper scripts and such, never things that are actually used by the main codebase. Or do you mean `app/utils.py`?

2023-07-11 20:53 UTC, kruai commented on api/assignment_rule.py
> +
Correct, though it should be `RbacPermission.WRITE`

2023-07-11 20:54 UTC, kruai commented on api/__init__.py
> +def _error_json_response(title, detail, status=status.HTTP_400_BAD_REQUEST):
I want to add that if this function is being referenced from other modules, it shouldn't start with an underscore, and should simply be `error_json_response`

2023-07-11 20:58 UTC, kruai commented on lib/assignment_rule_repository.py
> +def add_assignment_rule(assign_rule_data, event_producer) -> AssignmentRule:
No cyndi or xjoin data needs to be updated for assignment rules, right? As far as I'm aware, we're just planning to store their data in the DB, and we'll read through them when new hosts come in. I don't see what kind of event we would be producing

2023-07-13 19:40 UTC, jpramos123 commented on api/__init__.py
> +def _error_json_response(title, detail, status=status.HTTP_400_BAD_REQUEST):
Followed what was on Arifs PR and changed to `json_response`

2023-07-13 20:58 UTC, jpramos123 commented
rbac is failing to deploy

2023-07-13 20:58 UTC, jpramos123 commented
/retest

2023-07-14 14:41 UTC, thearifismail reviewed
LGTM.

2023-07-14 15:16 UTC, thearifismail commented
/retest

2023-07-14 15:59 UTC, FabriciaDinizRH approved these changes
it's looking good. I got a couple of comments but I'll not block this

2023-07-14 15:59 UTC, FabriciaDinizRH commented on api/__init__.py
> +def json_response(title, detail, status=status.HTTP_400_BAD_REQUEST):
This maybe a nitpick but the name `json_response` doesn't specify that this is only for error messages

2023-07-14 15:59 UTC, FabriciaDinizRH commented on app/serialization.py
> +        "org_id": assign_rule.org_id,
`org_id` and `account` are not specified in the `AssignmentRuleOut` spec

2023-07-14 16:29 UTC, thearifismail commented on api/__init__.py
> +def json_response(title, detail, status=status.HTTP_400_BAD_REQUEST):
That is intentional to let any status use this method.

2023-07-14 16:33 UTC, FabriciaDinizRH commented on api/__init__.py
> +def json_response(title, detail, status=status.HTTP_400_BAD_REQUEST):
@thearifismail but when building the flask response, the first field is "error"

2023-07-14 16:44 UTC, thearifismail commented on api/__init__.py
> +def json_response(title, detail, status=status.HTTP_400_BAD_REQUEST):
Response will be whatever is passed it.  If no status provided, then the default will be error, otherwise it will be whatever status is passed in.

2023-07-14 16:55 UTC, FabriciaDinizRH commented on api/__init__.py
> +    return flask_json_response({"error": title, "detail": detail, "status": status}, status)
@thearifismail I was refering to this line in the last comment

2023-07-14 18:21 UTC, jpramos123 commented on api/__init__.py
> +    return flask_json_response({"error": title, "detail": detail, "status": status}, status)
Good point @FabriciaDinizRH!
I will change it to `title` instead of `error`

2023-07-14 18:21 UTC, jpramos123 commented on api/__init__.py
> +def json_response(title, detail, status=status.HTTP_400_BAD_REQUEST):
Good point @FabriciaDinizRH!
I will change it to title instead of error

2023-07-14 18:32 UTC, thearifismail submitted a review, later dismissed
LGTM

2023-07-14 19:19 UTC, jpramos123 commented on app/serialization.py
> +        "org_id": assign_rule.org_id,
thanks, added to the spec

2023-07-14 20:02 UTC, kruai requested changes
Looking good so far - I left a few comments. I think it also needs a test to validate that it errors correctly when creating a rule for a group, when there's already a rule for a group

2023-07-14 20:34 UTC, thearifismail commented on tests/helpers/api_utils.py
> +    assert response_data["enabled"] == expected_data["enabled"]
Since "created_on" and "modified_on" are required fields in `AssignmentRoleOut`, shouldn't they be verified for their presence in the response?

2023-07-17 09:57 UTC, FabriciaDinizRH commented on swagger/api.spec.yaml
> +      description: Create Assignment Rule object using post request
the descriptions usually contain the required permission for the endpoint. Check the groups endpoint for reference

2023-07-17 18:41 UTC, jpramos123 commented on api/__init__.py
> +    return flask_json_response({"title": title, "detail": detail, "status": status}, status)
Changed the method name to `json_error_response`.
Agree with you, we don´t need the status in the JSON, we already have it in the response.

2023-07-17 18:43 UTC, jpramos123 commented on swagger/api.spec.yaml
> +              nullable: true
Updated

2023-07-17 19:01 UTC, jpramos123 commented on tests/test_api_assignment_rules.py
> +    assert "'name'" in response_data["detail"]
Good suggestion!
Applied it

Thanks

2023-07-17 19:03 UTC, jpramos123 commented on tests/test_api_assignment_rules.py
> +#    assert assign_rule_data["name"] in response_data["detail"]
This test is not working. I need to investigate more.
Uncommented and applied a skip decorator with a message.

2023-07-17 19:06 UTC, jpramos123 commented on tests/helpers/api_utils.py
> +    assert response_data["enabled"] == expected_data["enabled"]
Good call, added to the test

Thanks

2023-07-17 19:49 UTC, jpramos123 commented on lib/assignment_rule_repository.py
> +def add_assignment_rule(assign_rule_data) -> AssignmentRule:
Makes sense!
Now I'm serializing the result!

Thanks

2023-07-17 19:56 UTC, jpramos123 commented on swagger/api.spec.yaml
> +      description: Create Assignment Rule object using post request
Thanks!

Added to the spec

2023-07-18 12:53 UTC, kruai requested changes
There's just one thing that didn't get resolved from my last review, and of course the skipped test needs to be investigated. Looks good besides those though

2023-07-18 19:55 UTC, kruai approved these changes
If you can create a Jira to investigate the issues with `test_create_assignemnt_rule_same_name` and `test_create_assignemnt_rule_same_group`, then LGTM

2023-07-18 22:06 UTC, thearifismail commented on tests/test_api_assignment_rules.py
> +import pytest
This file should be named `test_api_assignment_rules_created.py` to be in line with the pattern used for `groups` and others file names containing tests for `_update.py` , `_delete.py` and so on.

2023-07-18 22:08 UTC, thearifismail commented on tests/test_api_assignment_rules.py
> +@pytest.mark.parametrize("required_fields", [["name", "group_id", "filter", "enabled"]])
```suggestion
@pytest.mark.parametrize("required_fields", [["name", "group_id", "filter", "enabled"], ["name", "group_id", "filter", "disabled"]])
```

2023-07-18 22:11 UTC, thearifismail commented on tests/test_api_assignment_rules.py
> +@pytest.mark.parametrize("required_fields", [["name", "group_id", "filter", "enabled"]])
Shouldn't `required_fields` contains values instead of the field/column names?

2023-07-18 22:15 UTC, thearifismail commented on tests/test_api_assignment_rules.py
> +            assert_response_status(response_status, expected_status=400)
minor comment: shouldn't `expected_status=status.HTTP_400_BAD_REQUEST`?

2023-07-18 22:16 UTC, thearifismail commented on tests/test_api_assignment_rules.py
> +    assert_response_status(response_status, expected_status=400)
same comment as above.

2023-07-18 22:17 UTC, thearifismail commented on tests/test_api_assignment_rules.py
> +@pytest.mark.skip(reason="Need to validate why the test is creating duplicates in the DB")
Are these the two tests, giving trouble?

2023-07-19 12:04 UTC, kruai commented on api/__init__.py
> +def json_error_response(title, detail, status=status.HTTP_400_BAD_REQUEST):
As far as I'm aware, it's only used for errors, which is why it has "title" and "detail". We already use `flask_json_response` for our non-error responses

2023-07-19 12:06 UTC, kruai commented on api/assignment_rule.py
> +            error_message = f"A assignment rule with name {name} alredy exists."
Good catch

2023-07-19 12:11 UTC, kruai commented on app/instrumentation.py
> +def log_post_assignment_rule_succeeded(logger, id):
We're pretty flexible with our verbs in the logging functions so far - another function even uses `add`. That said, I'm not against `log_create_assignment_rule_succeeded` and `log_create_assignment_rule_failed`

2023-07-19 12:12 UTC, kruai commented on app/models.py
> +    group_id = fields.Str(required=True, validate=verify_uuid_format)
The code that you're commenting on in a schema, and it's already validating exactly what you're suggesting. Am I missing something?

2023-07-19 12:14 UTC, kruai commented on tests/test_api_assignment_rules.py
> +import pytest
Good call. Slight correction though: `test_api_assignment_rules_create.py`, not past-tense

2023-07-19 12:15 UTC, kruai commented on tests/test_api_assignment_rules.py
> +            assert_response_status(response_status, expected_status=400)
I don't think we've ever done that in our tests

2023-07-19 12:22 UTC, kruai commented on tests/test_api_assignment_rules.py
> +@pytest.mark.parametrize("required_fields", [["name", "group_id", "filter", "enabled"]])
@thearifismail  No, we want the column names. This test is validating that if we remove a required field from the POST body, validation fails, so it's testing for each of those one at a time.

@jpramos123, that being said... you have both `@pytest.mark.parametrize` or `subtests.test()`, but should pick one in this scenario. Currently, `parametrize` is doing nothing, because it's just passing in that one static array, so the whole test is running only once. You can either:

- use `parametrize` and get rid of `for field in required_fields` and remove the subtests section
- remove `parametrize` and keep the rest of the test as-is

2023-07-19 13:10 UTC, thearifismail commented on tests/test_api_assignment_rules.py
> +@pytest.mark.parametrize("required_fields", [["name", "group_id", "filter", "enabled"]])
Thanks @kruai that makes sense.

2023-07-19 15:19 UTC, jpramos123 commented on app/instrumentation.py
> +def log_post_assignment_rule_succeeded(logger, id):
I will keep it as it is.

We can standardize it when we do a refactor.

2023-07-19 15:19 UTC, jpramos123 commented on app/instrumentation.py
> +def log_post_assignment_rule_failed(logger):
I will keep it as it is.

We can standardize it when we do a refactor.

2023-07-19 15:25 UTC, jpramos123 commented on tests/test_api_assignment_rules.py
> +@pytest.mark.skip(reason="Need to validate why the test is creating duplicates in the DB")
They are! I'm going to open a ticket to address these!

2023-07-19 15:31 UTC, jpramos123 commented on app/models.py
> +    group_id = fields.Str(required=True, validate=verify_uuid_format)
I don't get what is your suggestion here.

In this line we make sure that the `group_id` is a required field and is in UUID format.

The `org_id` in the `Group`  you are referring is the `db.Model` that is going to be the class used to manipulate `Group` entities in the application, not the schema used to validate that the input is correct!

2023-07-19 15:53 UTC, jpramos123 commented on tests/test_api_assignment_rules.py
> +@pytest.mark.skip(reason="Need to validate why the test is creating duplicates in the DB")
Here is the ticket: 

RHINENG-1284
--


[RHINENG-1284](https://issues.redhat.com/browse/RHINENG-1284)

2023-07-19 15:59 UTC, jpramos123 commented on api/assignment_rule.py
> +        name = validated_create_assignment_rule.get("name")
Okay! We can reduce some resource usage here :)

2023-07-19 16:10 UTC, jpramos123 commented on tests/test_api_assignment_rules.py
> +@pytest.mark.parametrize("required_fields", [["name", "group_id", "filter", "enabled"]])
Thanks! Made the changes!

2023-07-19 16:23 UTC, thearifismail approved these changes

2023-07-19 19:35 UTC, jpramos123 commented
/retest

2023-07-20 09:09 UTC, FabriciaDinizRH approved these changes
LGTM!

2023-07-20 17:41 UTC, merged