[ESSNTL-4879]: Create GET /assignment-rules/<id> endpoint.
RedHatInsights/insights-host-inventory pull request #1421
Opened 2023-07-14 16:26 UTC by roliveri

# Overview

This PR is being created to address [ESSNTL-4879](https://issues.redhat.com/browse/ESSNTL-4879).
Implemented the GET /assignment-rules/<id> endpoint.

Please note: Given the amount of common files and code, I've included the code from:
https://github.com/RedHatInsights/insights-host-inventory/pull/1415
in this PR, to make it easier to merge them in the future. I hope it doesn't cause confusion.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-07-17 10:16 UTC, FabriciaDinizRH requested changes
It's looking good so far, just some "groups" needing to be changed to "assignment rules"

2023-07-17 10:16 UTC, FabriciaDinizRH commented on swagger/api.spec.yaml
> +        Required permissions: inventory:groups:read
```suggestion
        Required permissions: inventory:assignment-rules:read
```

2023-07-17 10:16 UTC, FabriciaDinizRH commented on swagger/api.spec.yaml
> +        - $ref: '#/components/parameters/groupOrderByParam'
```suggestion
        - $ref: '#/components/parameters/assignmentRuleOrderByParam'
```

2023-07-17 10:16 UTC, FabriciaDinizRH commented on swagger/api.spec.yaml
> +        - $ref: '#/components/parameters/groupOrderHowParam'
```suggestion
        - $ref: '#/components/parameters/assignmentRuleOrderHowParam'
```

2023-07-17 10:16 UTC, FabriciaDinizRH commented on swagger/api.spec.yaml
> +      title: Group properties with host count
```suggestion
      title: Assignment-rule properties with host count
```

2023-07-17 10:16 UTC, FabriciaDinizRH commented on swagger/api.spec.yaml
> +        Data of a single group belonging to an account.
```suggestion
        Data of a single assignment-rule belonging to an account.
```

2023-07-17 10:16 UTC, FabriciaDinizRH commented on swagger/api.spec.yaml
> +          group_out:
```suggestion
          assignment_rule_out:
```
???

2023-07-17 10:16 UTC, FabriciaDinizRH commented on swagger/api.spec.yaml
> +              $ref: '#/components/schemas/GroupOutWithHostCount'
```suggestion
              $ref: '#/components/schemas/AssignmentRuleOutWithHostCount'
```

2023-07-17 12:17 UTC, thearifismail commented on swagger/api.spec.yaml
> +        Required permissions: inventory:groups:read
@FabriciaDinizRH `assignment-rules` are associated with `groups`.  That's why `inventory:groups:read` is the correct permission, IMO.

2023-07-17 12:18 UTC, thearifismail commented
Holding off review because once the create/post endpoint PR gets merged, it is going to affect `AssignmentRuleOut`

2023-07-31 19:21 UTC, roliveri commented
@thearifismail - rebased with master. It appears the AssignmentRuleOut dependancies are included.

2023-08-01 13:52 UTC, kruai requested changes
Got a few comments. Good happy-path test, though I'd also request a few more tests to catch the other scenarios. For instance, the HTTP 400 triggered by the ValueError, the scenario where a rule isn't found, and the scenario where one of the requested rules isn't allowed by the RBAC permissions.

2023-08-01 13:52 UTC, kruai commented on api/assignment_rule.py
> +    return True
These don't have definitions in the API spec, and are also outside the scope of the PR

2023-08-01 13:52 UTC, kruai commented on api/assignment_rule.py
> +    return True
This isn't defined in the API spec, and is also outside the scope of the PR

2023-08-01 13:52 UTC, kruai commented on api/assignment_rule.py
> +    return True
I don't think this is used anywhere

2023-08-01 13:52 UTC, kruai commented on swagger/api.spec.yaml
> +      required: false
Is this used anywhere? I can't find any other references to it

2023-08-01 13:52 UTC, kruai commented on swagger/api.spec.yaml
> +      example: sre-assignment-rule
I'm having trouble finding where this is used as well

2023-08-01 13:52 UTC, kruai commented on swagger/api.spec.yaml
> +            $ref: "#/components/schemas/HostCount"
Where is this component used?

2023-08-01 15:40 UTC, roliveri commented on swagger/api.spec.yaml
> +            $ref: "#/components/schemas/HostCount"
I think it came in as part of a prior merge, then removed at a later time. When I merged again, it just appeared as though I added it. I'll remove it.

2023-08-01 16:19 UTC, FabriciaDinizRH commented on swagger/api.spec.yaml
> +      example: sre-assignment-rule
@roliveri I don't think this need to be a schema, because we already have `assignmentRuleName` in `#/components/parameters`

2023-08-01 16:19 UTC, FabriciaDinizRH commented on api/assignment_rule.py
> +    return True
agreed. With the latest changes, this function got moved to another file (if it was going to be used)

2023-08-03 15:56 UTC, FabriciaDinizRH submitted a review, later dismissed

2023-08-03 16:22 UTC, roliveri commented
/retest

2023-08-03 16:26 UTC, kruai reviewed
Just needs one tiny change to a description but then LGTM!

2023-08-03 16:26 UTC, kruai commented on swagger/api.spec.yaml
> +        should use this identifier to reference groups.
The description describes group IDs, not assignment rule IDs

2023-08-04 15:04 UTC, roliveri commented
/retest

2023-08-04 15:07 UTC, thearifismail reviewed
Just one minor comment.  Rest LGTM

2023-08-04 15:07 UTC, thearifismail commented on api/assignment_rule.py
> +        abort(400, str(e))
```suggestion
        abort(status.HTTP_400_BAD_REQUEST, str(e))
```

2023-08-04 15:07 UTC, thearifismail commented on api/assignment_rule.py
> +        abort(400, str(e))
Suggesting the ^^^ for consistency about the status.HTTP_* are used in the code.  In test, numbers like `200` and `400` are used.

2023-08-04 16:04 UTC, thearifismail approved these changes
LGTM

2023-08-04 16:53 UTC, roliveri commented
@thearifismail @kruai Changes made.

2023-08-07 10:49 UTC, FabriciaDinizRH approved these changes

2023-08-07 12:36 UTC, kruai approved these changes

2023-08-07 13:43 UTC, merged