[ESSNTL-5023] - Create table and ORM model for account_staleness_culling
RedHatInsights/insights-host-inventory pull request #1428
Opened 2023-07-20 20:40 UTC by jpramos123

# Overview

This PR is being created to address [ESSNTL-5023](https://issues.redhat.com/browse/ESSNTL-5023).
This PR creates the migration script to create the table in the DB, ORM model and add tests to validate it.

Todo:
1. Add tests

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-07-26 12:24 UTC, fellipeh requested changes
Good Job!

It's not an important one, but just one request change if is ok..

2023-07-26 12:24 UTC, fellipeh commented on app/models.py
> +            self.edge_culling_delta = input_acc.edge_culling_delta
```suggestion
        if input_acc.conventional_staleness_delta:
            self.conventional_staleness_delta = input_acc.conventional_staleness_delta
        if input_acc.conventional_stale_warning_delta:
            self.conventional_stale_warning_delta = input_acc.conventional_stale_warning_delta
        if input_acc.conventional_culling_delta:
            self.conventional_culling_delta = input_acc.conventional_culling_delta
        if input_acc.edge_staleness_delta:
            self.edge_staleness_delta = input_acc.edge_staleness_delta
        if input_acc.edge_stale_warning_delta:
            self.edge_stale_warning_delta = input_acc.edge_stale_warning_delta
        if input_acc.edge_culling_delta:
            self.edge_culling_delta = input_acc.edge_culling_delta
```

2023-07-26 16:03 UTC, fellipeh submitted a review, later dismissed
LGTM

2023-07-27 13:04 UTC, kruai reviewed
Implementation looks good! Just a few notes.
Also, having the deltas be in seconds seems more precise than we need, but I don't expect we'll run into any issues with Integer's max value unless they need to set it more than 68 years into the future, and I doubt there's any value in supporting that.

2023-07-27 16:49 UTC, jpramos123 commented on app/models.py
> +        edge_culling_delta=None,
Yeah, I think we should standardize as well.
I will apply the changes

2023-07-27 16:51 UTC, jpramos123 commented on migrations/versions/fc4921790a66_create_account_staleness_culling_table.py
> +        sa.Column("conventional_staleness_delta", sa.Integer, default=100800, nullable=False),
We can replace it with 24 hours. I think it would be more consistent!

But this is the value that was originally defined in ingress (and it was 29, not 28 hehe)
https://github.com/RedHatInsights/insights-puptoo/blob/master/src/puptoo/app.py#LL47C52-L47C52

2023-07-27 17:16 UTC, jpramos123 commented on migrations/versions/fc4921790a66_create_account_staleness_culling_table.py
> +        sa.Column("edge_culling_delta", sa.Integer, default=15552000, nullable=False),
I was thinking about it, as those values can be "Never" I think we must use a string instead of a Int.
https://www.sketch.com/s/dd09e06a-9bb3-4cda-9bf3-2fe92d949145/a/AZnGpP4

Thoughts?

2023-07-27 18:46 UTC, kruai commented on migrations/versions/fc4921790a66_create_account_staleness_culling_table.py
> +        sa.Column("conventional_staleness_delta", sa.Integer, default=100800, nullable=False),
I don't mind either way! If the original uses 28/29 hours I'm fine leaving it at that

2023-07-28 14:07 UTC, fellipeh approved these changes

2023-07-28 15:14 UTC, kruai approved these changes

2023-07-28 15:55 UTC, thearifismail reviewed
Before it is too late, I hope a less confusing and less awkward alternate replaces `AccountStalenessCulling`

2023-07-28 15:55 UTC, thearifismail commented on tests/fixtures/db_fixtures.py
> +        immutable_staleness_delta=None,
Good using immutable validates the use of the word `conventional` which IMO was found confusing but could not suggest any appropriate alternate.

2023-07-28 17:47 UTC, jpramos123 commented on tests/fixtures/db_fixtures.py
> +        immutable_staleness_delta=None,
I think we can keep it this way, as it aligns with the frontend

2023-07-28 18:19 UTC, thearifismail approved these changes

2023-07-28 18:25 UTC, jpramos123 commented on app/models.py
> +class AccountStalenessCulling(db.Model):
I would rather keep it as it is right now.
I was going to put the name as `AccountStalenessAndCulling`, but I though it was too big

2023-07-28 19:28 UTC, merged

2023-08-01 14:48 UTC, kruai commented on tests/fixtures/db_fixtures.py
> +        immutable_staleness_delta=None,
conventional and immutable are the designated terms that we should be using.