ESSNTL-4877: add assignment-rules GET endpoint
RedHatInsights/insights-host-inventory pull request #1429
Opened 2023-07-20 22:15 UTC by thearifismail

# Overview

This PR is being created to address [ESSNTL-4877](https://issues.redhat.com/browse/ESSNTL-4877).
This PR replaces PR #1415 

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-07-21 13:42 UTC, thearifismail commented
/retest

2023-07-21 20:19 UTC, jpramos123 requested changes
Thanks for the PR!

Below are some comments and findings

2023-07-21 20:19 UTC, jpramos123 commented on api/assignment_rule_query.py
> +        ASSIGNMENT_RULES_ORDER_HOW_MAPPING[param_order_how.lower()]
This is causing an error!
The dictionary keys should be `asc` or `desc` not the fields name

2023-07-21 20:19 UTC, jpramos123 commented on tests/test_api_assignment_rules_get.py
> +from tests.helpers.api_utils import assert_response_status
I suggest creating tests to validate all query parameters:

1. order_by
2. order_how
3. per_page
4. page

2023-07-21 20:19 UTC, jpramos123 commented on lib/assignment_rule_repository.py
> +    enabled = assign_rule_data.get("enabled")
Thanks for adding this field to the repository!

2023-07-24 18:46 UTC, thearifismail commented on lib/assignment_rule_repository.py
> +    enabled = assign_rule_data.get("enabled")
Done!

2023-07-25 20:48 UTC, jpramos123 commented on api/assignment_rule_query.py
> +ASSIGNMENT_RULES_ORDER_HOW_NEW = {"asc": asc, "desc": desc}
```suggestion
ASSIGNMENT_RULES_ORDER_HOW_BY_FIELD= {"org_id": asc, "account": desc, "name": asc, "group_id": asc}
ASSIGNMENT_RULES_ORDER_HOW = {"asc": asc, "desc": desc}
```

2023-07-25 20:49 UTC, jpramos123 approved these changes
One suggestion!

LGTM!

2023-07-25 23:30 UTC, jpramos123 approved these changes
LGTM

2023-07-26 10:41 UTC, FabriciaDinizRH requested changes
Overall all good, but one the tests has an incorrect behavior

2023-07-26 10:41 UTC, FabriciaDinizRH commented on tests/test_api_assignment_rules_get.py
> +    assert response_data["total"] == 3
Each group is only supposed to have one assignment rule, [as discussed here](https://redhat-internal.slack.com/archives/CQFKM031T/p1689271922019339)

2023-07-26 10:41 UTC, FabriciaDinizRH commented on swagger/api.spec.yaml
> +      description: Filter by assignement-rule name
```suggestion
      description: Filter by assignment-rule name
```

2023-07-26 10:41 UTC, FabriciaDinizRH commented on api/assignment_rule_query.py
> +    return assingnment_rules_list, total
```suggestion
    return assignment_rules_list, total
```

2023-07-26 10:41 UTC, FabriciaDinizRH commented on api/assignment_rule_query.py
> +    assingnment_rules_list = (
```suggestion
    assignment_rules_list = (
```

2023-07-26 10:41 UTC, FabriciaDinizRH commented on tests/test_api_assignment_rules_get.py
> +def test_order_by_and_order_how(db_create_assignment_rule, db_create_group, api_get, order_by, order_how):
This test is a bit confusing for me. I don't see how it can test the ordering with only one assignment rule created.

2023-07-26 15:34 UTC, thearifismail commented on tests/test_api_assignment_rules_get.py
> +def test_order_by_and_order_how(db_create_assignment_rule, db_create_group, api_get, order_by, order_how):
Refactored the test to create more than one assignment_rules and then verify the order based based on `order_by` and `order_how` parameters.

2023-07-26 16:19 UTC, thearifismail commented
/retest

2023-07-26 16:43 UTC, FabriciaDinizRH commented on tests/test_api_assignment_rules_get.py
> +    assert response_data["total"] == 3
for future reference: this is going to be addressed by [another task](https://issues.redhat.com/browse/RHINENG-1284)
@jpramos123 heads up, there are going to be more tests to fix because we want to merge this PR asap

2023-07-26 17:19 UTC, FabriciaDinizRH approved these changes

2023-07-26 17:56 UTC, jpramos123 commented on tests/test_api_assignment_rules_get.py
> +    assert response_data["total"] == 3
Thanks @FabriciaDinizRH I will add this PR to the ticket so we don't lose the track of it

2023-07-26 17:57 UTC, jpramos123 approved these changes

2023-07-26 19:12 UTC, thearifismail commented
/retest

2023-07-26 19:53 UTC, thearifismail commented
/retest

2023-07-26 20:37 UTC, merged