feat(ESSNTL-5037): Adding staleness post endpoint
RedHatInsights/insights-host-inventory pull request #1454
Opened 2023-08-08 13:16 UTC by fellipeh

# Overview

This PR is being created to address [ESSNTL-5037](https://issues.redhat.com/browse/ESSNTL-5037).

Adding `account staleness` POST endpoint

2023-08-22 14:53 UTC, fellipeh commented
/retest

2023-08-22 15:03 UTC, jpramos123 requested changes
Thanks for the PR

Below are some suggestions

2023-08-22 15:03 UTC, jpramos123 commented on tests/test_api_account_staleness_create.py
> +
I would add tests to validate the RBAC roles we created.
Refer to: https://github.com/RedHatInsights/insights-host-inventory/pull/1371/files#diff-67132a592b391fd29ab8eedfb9cbe1bd23b82f0728f3ffa7e1b3e9f681edc118

2023-08-22 15:28 UTC, kruai requested changes

2023-08-22 15:28 UTC, kruai commented on app/models.py
> +    edge_culling_delta = fields.Str(required=True, validate=marshmallow_validate.Length(min=1, max=36))
Do all of these need to be required? Just wondering because we _do_ have default values for all of these fields. I could see a user wanting to set a custom value for just one of them, and wanting to leave the rest as the defaults

2023-08-22 15:28 UTC, kruai commented on app/instrumentation.py
> +    logger.info("Created account staleness Failed with org_id %s", org_id)
```suggestion
    logger.info("Failed to create staleness for account with org_id %s", org_id)
```

2023-08-22 17:43 UTC, thearifismail reviewed
Not done yet

2023-08-22 17:43 UTC, thearifismail commented on api/account_staleness.py
> +        logger.exception(f"Input validation error while creating account staleness: {body}")
```suggestion
        logger.exception(f'Input validation error, "{str(e.messages)}", while creating account staleness: {body}')
```

2023-08-22 17:43 UTC, thearifismail commented on api/account_staleness.py
> +        logger.exception(f"Input validation error while creating account staleness: {body}")
include the exception in the log message so that some one looking at Kibana can see the reason why it failed.

2023-08-22 17:43 UTC, thearifismail commented on lib/account_staleness.py
> +    return created_staleness
rename the var to show it is an ID.  The current var suggests it to be a complete staleness object.

2023-08-22 17:43 UTC, thearifismail commented on lib/account_staleness.py
> +def get_account_staleness_by_org_id(org_id) -> AccountStalenessCulling:
This method is not being called, except, a test.  Is it really needed?

2023-08-22 17:43 UTC, thearifismail commented on lib/account_staleness.py
> +    created_staleness = AccountStalenessCulling.query.filter(AccountStalenessCulling.org_id == org_id).one_or_none()
The comment says ID being returned?  Looks like a staleness object is returned.  Either the comment or the var name is not correct.

2023-08-22 17:43 UTC, thearifismail commented on api/account_staleness.py
> +        error_message = f"A account staleness with org_id {org_id} already exists."
```suggestion
        error_message = f'A account staleness with org_id {validated_data.get("org_id")} already exists.'
```

2023-08-22 17:43 UTC, thearifismail commented on api/account_staleness.py
> +        org_id = validated_data.get("org_id")
```suggestion
```

2023-08-22 17:43 UTC, thearifismail commented on swagger/api.spec.yaml
> +        - BearerAuth: []
Why is `BearerAuth` need by a `POST` call but not GET?

2023-08-22 18:02 UTC, fellipeh commented on lib/account_staleness.py
> +    return created_staleness
`created_staleness` is a complete `AccountStalenessCulling` object.

2023-08-22 20:13 UTC, fellipeh commented on swagger/api.spec.yaml
> +        - BearerAuth: []
Just following as same others endpoint... @kruai  any thought on this?

2023-08-22 20:15 UTC, kruai commented on swagger/api.spec.yaml
> +        - BearerAuth: []
¯\_(ツ)_/¯

2023-08-23 13:44 UTC, fellipeh commented
/retest

2023-08-23 15:03 UTC, kruai commented on lib/account_staleness.py
> +def get_account_staleness_by_org_id(org_id) -> AccountStalenessCulling:
If this function is a test helper, it should probably be a DB fixture: https://github.com/RedHatInsights/insights-host-inventory/blob/master/tests/fixtures/db_fixtures.py
I'd leave the actual access function for when that endpoint is implemented, as it's out of scope for this PR, and may end up needing to do things differently

2023-08-23 15:09 UTC, kruai commented on app/models.py
> +    edge_culling_delta = fields.Str(required=True, validate=marshmallow_validate.Length(min=1, max=36))
@fellipeh I'm just unresolving this bc I didn't see any discussion on it. It's more of a requirements question though, so CCing @jpramos123 ^

2023-08-23 15:24 UTC, kruai requested changes
Got a few more notes in addition to the comments I left before the review.

2023-08-23 15:24 UTC, kruai commented on tests/test_api_account_staleness_create.py
> +        "edge_culling_delta": "120",
These field names need to be updated to match the implementation.

2023-08-25 14:04 UTC, fellipeh commented on api/account_staleness.py
> +        return json_error_response(inve.title, inve.detail, status.HTTP_400_BAD_REQUEST)
You're right, we only have `IntegrityError`  exception.. removing...

2023-08-25 16:40 UTC, jpramos123 commented on app/models.py
> +    edge_culling_delta = fields.Str(required=True, validate=marshmallow_validate.Length(min=1, max=36))
@kruai @fellipeh I think they should NOT be required fields, as you mentioned, the user can chose to set just one of this values, and the rest will be created using the default values.

2023-08-28 14:09 UTC, kruai commented on swagger/api.spec.yaml
> +        - BearerAuth: []
From our most recent discussion: it should be fine to remove the bearer auth.

2023-08-28 17:05 UTC, jpramos123 commented on tests/test_api_account_staleness_create.py
> +
@fellipeh I still would like to have some test that validate the RBAC roles:
See this as a reference: https://github.com/RedHatInsights/insights-host-inventory/pull/1371/files#diff-e7c80922b4d5365c140f8fef9fe0925798e1b11b603bce7c8620d4556517ad68R161

2023-08-28 17:06 UTC, jpramos123 requested changes

2023-08-28 19:00 UTC, kruai commented on app/models.py
> +    edge_culling_delta = fields.Str(required=True, validate=marshmallow_validate.Length(min=1, max=36))
@fellipeh I'm again unresolving this because I do not see a follow-up; at least one field should be provided, but they should not all be required

2023-08-28 19:10 UTC, kruai requested changes
A few more comments (mostly about all of the payload fields being required), but there's steady progress! I like the new tests

2023-08-28 19:10 UTC, kruai commented on app/models.py
> +    immutable_culling_delta = fields.Str(required=True, validate=marshmallow_validate.Length(min=1, max=36))
Just so we don't lose track of this, the verdict is that not all of these fields are required (since they have default values). The payload should provide at least one of them, but none of them should be marked as required

2023-08-28 19:10 UTC, kruai commented on swagger/api.spec.yaml
> +      allOf:
Should use `anyOf` if one or more of them is required
```suggestion
      anyOf:
```

2023-08-28 19:10 UTC, kruai commented on tests/test_api_account_staleness_create.py
> +    assert_response_status(response_status, 400)
If only one value needs to be provided, then the post should probably succeed and return 201

2023-08-28 19:16 UTC, fellipeh commented on app/models.py
> +    immutable_culling_delta = fields.Str(required=True, validate=marshmallow_validate.Length(min=1, max=36))
We'll follow with  should provide at least one, so I removed the require=True.

2023-08-28 19:17 UTC, fellipeh commented on tests/test_api_account_staleness_create.py
> +    assert_response_status(response_status, 400)
This supposed to test an `invalid` payload. I believe the name I used make the confusion, I'll change it.

2023-08-28 19:46 UTC, fellipeh commented on app/models.py
> +    edge_culling_delta = fields.Str(required=True, validate=marshmallow_validate.Length(min=1, max=36))
Resolved per slack conversation.

2023-08-28 19:56 UTC, kruai submitted a review, later dismissed

2023-08-28 20:48 UTC, jpramos123 approved these changes

2023-08-28 20:54 UTC, jpramos123 requested changes
Please, can you change this method name?

This will help me a lot when merging your code to mine

2023-08-28 20:54 UTC, jpramos123 commented on app/serialization.py
> +def serialize_account_staleness(account_staleness):
```suggestion
def serialize_account_staleness_response(account_staleness):
```

2023-08-28 21:36 UTC, thearifismail reviewed
Over all looks good.  One minor comment though

2023-08-28 21:36 UTC, thearifismail commented on swagger/openapi.json
> +                "maxLength": 36
`maxLength: 36` is used for uuid values; even the times expressed in `"created_at": "2023-07-28T14:32:16.353082"` is 25 chars long.  A time delta of a thousand years has `31536000000 seconds`, which is 11 chars. IMO, these lengths should be set to some realistic values.  Over allocation of memory can have negative imact.

2023-08-29 13:26 UTC, kruai approved these changes

2023-08-29 13:40 UTC, jpramos123 approved these changes

2023-08-29 13:47 UTC, merged