Draft: Segmentio tracking for inventory API.
RedHatInsights/insights-host-inventory pull request #1472
Opened 2023-08-29 14:16 UTC by roliveri

Initial POC for adding instrumentation to track inventory API events in Segmentio.

2023-09-05 13:39 UTC, roliveri commented
/retest

2023-09-08 14:21 UTC, roliveri commented on api/segmentio.py
> +        )
Yes, I'll add that.
We should probably check to see if there's a standard of preferred name for insights host inventory.

2023-09-15 20:35 UTC, marleystipich2 commented on api/segmentio.py
> +            op_name,
Small suggestion but maybe we could name these 2 fields too for readabilty like
```
user_id=identity.org_id,
event=op_name,
```

2023-09-19 20:39 UTC, thearifismail reviewed
Why another analytic tracking tool is needed on the top of what's already implemented?

2023-09-19 20:39 UTC, thearifismail commented on api/segmentio.py
> +    print(f"\n**** analytics.write_key: {analytics.write_key}")
Should't a `logger` be used in place of `print`?

2023-09-19 20:39 UTC, thearifismail commented on app/__init__.py
> +    print(f"\n****** Initializing Segmentio - analytics.write_key: {analytics.write_key}")
Should use logger in place of print

2023-09-20 14:40 UTC, thearifismail commented
> @kruai @thearifismail We also need to call `analytics.flush()` on shutdown. I looked, but I'm not sure where that should be done. Any suggestions?

How will `analytics` start or initialize?  The invenvetory MQ service uses ShutdownHandler, which is in `lib/handlers.py`

2023-09-20 14:56 UTC, kruai commented on api/segmentio.py
> +    print(f"\n**** analytics.write_key: {analytics.write_key}")
You're probably referring to the other print statements, but just in case: We should absolutely not print or log secrets

2023-09-26 15:38 UTC, roliveri commented
/retest

2023-09-27 17:43 UTC, thearifismail reviewed
One comment; rest LGTM

2023-10-09 17:57 UTC, roliveri commented
/retest

2023-10-11 13:27 UTC, marleystipich2 commented
/retest

2023-10-12 15:20 UTC, marleystipich2 commented
@thearifismail We added some tests to this. Could we get another review when you get a chance? Also, there are some tests failing in the PR check but they pass locally.

2023-10-12 21:08 UTC, roliveri commented
/retest

2023-10-13 15:59 UTC, roliveri commented
/retest

2023-10-16 07:57 UTC, fstavela commented
/retest

2023-10-16 14:21 UTC, kruai requested changes

2023-10-16 19:51 UTC, kruai approved these changes

2023-10-16 20:13 UTC, marleystipich2 approved these changes
Looks good to me! Thanks, @roliveri 👍

2023-10-16 20:40 UTC, thearifismail approved these changes

2023-10-16 22:32 UTC, roliveri commented
/retest

2023-10-17 00:32 UTC, merged