feat(ESSNTL-5197): RBAC structuring, group data censoring
RedHatInsights/insights-host-inventory pull request #1473
Opened 2023-08-29 20:04 UTC by kruai

# Overview

This PR is being created to address [ESSNTL-5197](https://issues.redhat.com/browse/ESSNTL-5197).

- Gives `rbac_filter` a rigid structure to make its usage more clear
- Gives `rbac_filter` default values instead of the whole object being `None` if not provided
- Removes group data from host API responses if the user does not have `groups:read` permission for that group
- Add test and modify an existing one

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-09-07 14:21 UTC, kruai commented
/retest

2023-09-07 15:18 UTC, kruai commented
I swear, we keep getting those `RemoteDisconnected` intermittent errors. But you can see (in the required PR build) that it's just that network blip and not caused by a real test failure

2023-09-11 11:22 UTC, FabriciaDinizRH requested changes
Awesome work! The middleware got me a bit overwhelmed, but everything looks ok.
Got a small suggestion though

2023-09-11 14:38 UTC, kruai commented on api/host.py
>  @rbac(RbacResourceType.HOSTS, RbacPermission.READ)
good catch!

2023-09-11 14:39 UTC, kruai commented on app/serialization.py
> +def deserialize_host_xjoin(data, rbac_filter=None):
Nope, it's leftover from when I was brainstorming and put it in the wrong function. I'll remove it

2023-09-12 18:21 UTC, thearifismail commented on lib/middleware.py
> +class RbacFilter:
Since there are no functions in RbacFilter, why couldn't this be a `dictionary`?

2023-09-12 18:21 UTC, thearifismail commented on lib/middleware.py
> +class RbacIdFilter:
What is the benefit of creating a new class/type for just attributes when there are not functions in the class?  Furthermore, `RbacIdFilter` does not get referenced from outside of `middleware.py`?

2023-09-12 18:21 UTC, thearifismail commented on lib/middleware.py
> +                additional_ids, match_found = _get_allowed_ids(
`_get_group_ids()` is more clear than `allowed` and easy to understand

2023-09-12 18:21 UTC, thearifismail commented on lib/middleware.py
> +def _get_attribute_filter_value(rbac_permission) -> Set[str]:
The parent filename is too generic, which makes reader wonder about is `attribute` about?  If it is a group's attribute then call it `_get_group_filter_value` and if `rbac` then `_get_rbac_filter_value.

2023-09-12 18:21 UTC, thearifismail commented on lib/middleware.py
> +        data_restrictions: Dict[str, RbacIdFilter] = {},
What's the string parameter is for?

2023-09-12 19:59 UTC, kruai commented on lib/middleware.py
> +class RbacFilter:
It originally was a huge multi-layer dictionary, and it would _technically_ function implemented that way, but anybody coding with it would be doing so blind. Intellisense can tell you the attributes of a class, but can't guess at dictionary keys. I also think it's cleaner and more organized with a class structure, so instead of code snippets like this:
```
if rbac_filter["filter_by"] and rbac_filter["filter_by"]["resource"] == RbacResourceType.GROUPS:
    filters += (AssignmentRule.group_id.in_(rbac_filter["filter_by"]["id_set"]),)
```
we get things like this:
```
if rbac_filter.filter_by and rbac_filter.filter_by.resource == RbacResourceType.GROUPS:
    filters += (AssignmentRule.group_id.in_(rbac_filter.filter_by.id_set),)
```

2023-09-12 20:16 UTC, kruai commented on lib/middleware.py
> +def _get_attribute_filter_value(rbac_permission) -> Set[str]:
`attributeFilter` is the field on RBAC permissions that limits what resources the user can access. It's not a group's attribute, and `rbac_filter` doesn't make sense because I'm specifically getting the value of `attributeFilter` from the permission's `resourceDefinition`

2023-09-12 20:19 UTC, kruai commented on lib/middleware.py
> +        data_restrictions: Dict[str, RbacIdFilter] = {},
I left a multiline comment right above this explaining the dict's structure. It's for quicker and easier access to the data restriction specific to that permission

2023-09-12 20:20 UTC, kruai commented on lib/middleware.py
> +                additional_ids, match_found = _get_allowed_ids(
I tried to keep it general in as many places as possible, because the value of `attributeFilter` in RBAC's response isn't technically guaranteed to be group IDs. HBI doesn't support other values for that yet, but I figured it would be best to play it safe and flexible for when that changes.

2023-09-12 20:20 UTC, kruai commented on lib/middleware.py
> +class RbacIdFilter:
As for the benefits of using a class instead of a dictionary, see my previous comment.
You're correct, `RbacIDFilter` is only used inside `middleware.py`. It's used twice in `RbacFilter` - once for the main filter, and once to represent the data that's restricted.

2023-09-13 20:50 UTC, thearifismail commented on lib/middleware.py
> +class RbacFilter:
I like the code clarity of using class.  At the time of this comment I was thinking about performance and class hierarchy and a quick google search did say that dictionaries had better performance than classes; however I did not find much on class hierarchy structure, like in C++ or Java.

2023-09-15 21:57 UTC, thearifismail approved these changes

2023-09-19 15:57 UTC, FabriciaDinizRH commented
The same required tests that are breaking in this PR are breaking in João's PR, so the problem is not the PR

2023-09-19 15:57 UTC, FabriciaDinizRH approved these changes

2023-09-19 16:18 UTC, thearifismail approved these changes

2023-09-19 16:35 UTC, kruai commented
> The same required tests that are breaking in this PR are breaking in João's PR, so the problem is not the PR

OK. It also looks like it's unrelated to the changes in this PR, so I'll go ahead and merge.

2023-09-21 13:57 UTC, kruai commented
I've put this back into draft status because we're not actually ready for this change yet. We want to make sure that all apps have the same display behavior, so we shouldn't start hiding the names until other apps are ready to do so as well (see the linked Jira ticket for more details).

2024-08-12 16:48 UTC, kruai commented
We have no plans to censor the group names, and we have already refactored RBAC. Closing.

2024-08-12 16:48 UTC, closed without merging