feat(ESSNTL-5302): Add delete staleness endpoint
RedHatInsights/insights-host-inventory pull request #1474
Opened 2023-08-30 13:32 UTC by fhbash

# Overview

This PR is being created to address [ESSNTL-5302](https://issues.redhat.com/browse/ESSNTL-5302).
- Adding `delete` endpoint for Account Staleness endpoint
- Update openapi schema file to reflect new endpoint
- 
## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-08-30 16:05 UTC, fellipeh commented
/retest

2023-08-30 16:41 UTC, jpramos123 submitted a review, later dismissed
LGTM

2023-08-30 17:02 UTC, kruai requested changes
This should have at least one RBAC test, but it looks good besides that

2023-08-30 17:02 UTC, kruai commented on tests/fixtures/api_fixtures.py
> +        return do_request(flask_client.delete, STALENESS_URL, identity, query_parameters, extra_headers)
Does it make sense to use this function with query parameters or extra headers? It's fine as-is, just wondering bc it doesn't look like any query params are allowed on that endpoint, and those are both optional params on `do_request`

2023-08-30 21:44 UTC, thearifismail reviewed
One minor comment for this PR.

2023-08-30 21:44 UTC, thearifismail commented on tests/test_api_account_staleness_delete.py
> +def test_delete_non_existing_account_staleness(api_delete_account_staleness):
the test should check for NoResultFound exception

2023-08-31 12:32 UTC, fellipeh commented on tests/test_api_account_staleness_delete.py
> +def test_delete_non_existing_account_staleness(api_delete_account_staleness):
This is an API test, `NoResultFound` is encapsulated into an `HTTP_404_NOT_FOUND` http response, so, afaik there isn't possible to check the exception here.

2023-08-31 14:35 UTC, jpramos123 requested changes
Lets add the feature flag

2023-08-31 14:35 UTC, jpramos123 commented on api/account_staleness.py
> +@api_operation
Lets start applying the feature flags:

Use this flag: "hbi.custom-staleness"

See this as a reference: https://github.com/RedHatInsights/insights-host-inventory/blob/master/api/group.py#L69

2023-08-31 15:12 UTC, kruai commented on tests/test_api_account_staleness_delete.py
> +def test_delete_non_existing_account_staleness(api_delete_account_staleness):
I agree - NoResultFound is what results in the 404, so I'd argue that's what it's testing

2023-09-01 15:51 UTC, fellipeh commented
/retest

2023-09-01 16:27 UTC, fellipeh commented
/retest

2023-09-04 14:24 UTC, fellipeh commented
/retest

2023-09-04 15:17 UTC, fellipeh commented
/retest

2023-09-04 17:26 UTC, fellipeh commented
/retest

2023-09-04 18:09 UTC, jpramos123 approved these changes
LGTM

2023-09-05 12:49 UTC, thearifismail approved these changes
To address the confusing naming concerns, here is the Jira card [ESSNTL-5336](https://issues.redhat.com/browse/ESSNTL-5336)

2023-09-05 14:49 UTC, merged