Add doc for running special job
RedHatInsights/insights-host-inventory pull request #1475
Opened 2023-08-30 17:02 UTC by thearifismail

# Overview

This PR is being created to address [RHINENG-1401](https://issues.redhat.com/browse/RHINENG-1401).
It adds a document stating how to run jobs using a different image than the one specified the clowdapp template for the parent app.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-08-31 13:42 UTC, kruai requested changes
Thanks for writing this up!

2023-08-31 13:42 UTC, kruai commented on README.md
> +There may be a job (ClowdJobInvocation), which requires using a special image that is different from the one used by the parent application, i.e. host-inventory.  Clowder out-of-the-box does not allo
```suggestion
There may be a job (ClowdJobInvocation) which requires using a special image that is different from the one used by the parent application, i.e. host-inventory.  Clowder out-of-the-box does not allow it.  [Running a Special Job](docs/running_special_job.md) describes how to accomplish it.
```

2023-08-31 13:42 UTC, kruai commented on docs/running_special_job.md
> +A recent update to the Hosts table in Host-Inventory database required updating every host in the table.  Making such change was tricky for the Production deployment because it posed Chicken and Egg
```suggestion
A recent update to the Hosts table in the Host-Inventory database required updating every host in the table.  Making such change was tricky for the Production deployment because it posed a chicken-and-egg problem.  The update could be made by executing a job created by a new ClowdJobInvocation (CJI) using a special image that is different from the current image. The problem was that the ClowdApp operator did not allow CJIs to use a different image than the one used by the parent/main clowdapp, host-inventory, and that is the reason for this document.
```

2023-08-31 13:42 UTC, kruai commented on docs/running_special_job.md
> +The problem was solved by hard coding the new image in a new CJI definition in the [Clowdapp template](https://github.com/RedHatInsights/insights-host-inventory/blob/f12eeec16cda33d9e90dfdcd2999deb2b
```suggestion
The problem was solved by hard-coding the new image in a new CJI definition in the [Clowdapp template](https://github.com/RedHatInsights/insights-host-inventory/blob/f12eeec16cda33d9e90dfdcd2999deb2bb03604f/deploy/clowdapp.yml#L630) and then updating the [SaaS file](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/services/insights/host-inventory/deploy-clowder.yml) to explicitly use an [IMAGE_TAG](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/services/insights/host-inventory/deploy-clowder.yml#L99) for deploying the parent clowdapp, host-inventory.
```

2023-08-31 13:42 UTC, kruai commented on docs/running_special_job.md
> +1.  Create new image as required. e.g. quay.io/cloudservices/insights-inventory:bca5615
How did you create that new image? Did you push something manually, or did you use one of the quay images that was automatically built via CI?

2023-08-31 13:42 UTC, kruai commented on docs/running_special_job.md
> +            labels:
Is this needed? It doesn't look like `labels` has any values, unless `app` is supposed to be indented one more level

2023-08-31 13:42 UTC, kruai commented on README.md
> +## Running Adhoc Jobs using Different Image
```suggestion
## Running ad hoc jobs using a different image
```

2023-08-31 13:42 UTC, kruai commented on docs/running_special_job.md
> +7.  Update the [host-inventory SAAS](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/services/insights/host-inventory/deploy-clowder.yml) file.
```suggestion
7.  Update the [host-inventory SaaS](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/services/insights/host-inventory/deploy-clowder.yml) file.
```

2023-08-31 13:42 UTC, kruai commented on docs/running_special_job.md
> +9.  Clone the [app-interface](https://gitlab.cee.redhat.com/service/app-interface) repo again to add the new CJI.
Why does it need to be cloned twice? Can't they just make a new branch on the repo they cloned in step 6?

2023-08-31 13:42 UTC, kruai commented on docs/running_special_job.md
> +        kubectl get po | grep just-host-synchronizer # note job name in the pod name
Should this be `kubectl get pods`?

2023-08-31 20:32 UTC, thearifismail commented on docs/running_special_job.md
> +1.  Create new image as required. e.g. quay.io/cloudservices/insights-inventory:bca5615
updated the statement to `Create/update the script as required by the job and create a pull request, which should automatically build a Quay image via continuous integration, e.g. quay.io/cloudservices/insights-inventory:bca5615`

2023-08-31 20:36 UTC, thearifismail commented on docs/running_special_job.md
> +            labels:
Probably not but I copy pasted the whole file for clarity.  It is the exact file that is used.

2023-08-31 20:40 UTC, thearifismail commented on docs/running_special_job.md
> +9.  Clone the [app-interface](https://gitlab.cee.redhat.com/service/app-interface) repo again to add the new CJI.
I started with one MR but Pete Savage suggested to separate Ref update and IMAGE_TAG change to one and then updating the job run number to a separate MR for ensuring it worked as expected.

2023-08-31 20:41 UTC, thearifismail commented on docs/running_special_job.md
> +        kubectl get po | grep just-host-synchronizer # note job name in the pod name
`po` is just an alias for `pods` and is widely used.

2023-08-31 20:47 UTC, thearifismail commented on docs/running_special_job.md
> +    ```
The `CJI` status `true` shows it completed successfuly or as expected and how pods status should look.

2023-08-31 21:29 UTC, thearifismail commented
/retest

2023-09-05 21:26 UTC, kruai commented on docs/running_special_job.md
> +        kubectl get po | grep just-host-synchronizer # note job name in the pod name
It's fine either way, I just wasn't familiar with it. Thanks for the info

2023-09-08 14:32 UTC, kruai approved these changes

2023-09-08 17:05 UTC, merged