feat(events): RHINENG-1789 push additional headers with kafka events
RedHatInsights/insights-host-inventory pull request #1479
Opened 2023-09-11 17:16 UTC by skateman

# Overview

This PR is being created to address [RHINENG-1789](https://issues.redhat.com/browse/RHINENG-1789).
We need some additional headers for the emitted kafka messages upon database changes for a more fine-grained filtering in cyndi. Vulnerability and patch require the `reporter` field to be exposed as a header, other apps need additinally the OS name and whether the host is an edge host or not.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-09-11 18:05 UTC, thearifismail requested changes
@skateman this change has wider implications than these 2 files.  First, database creation failed, which if fixed by adding `from app.models import Host` created the DB but caused 179 out 1120 tests to fail. 
Since it has pretty big implications, I suggest creating a Jira card so the issue could be addressed appropriately.

2023-09-12 13:15 UTC, kruai requested changes
There are places where a string is still being sent to `message_headers` rather than the full host. The unit test suite show 178 failures and 30 errors. If you're having trouble running the tests locally, let us know and we can help you out

2023-09-13 05:48 UTC, skateman commented
Yup, will work on that

2023-09-14 09:41 UTC, skateman commented
@kruai @thearifismail I have no idea why the remaining tests are failing and don't even thave the opportunity do debug it as the developer setup documentation you have in the README doesn't work for me (neither does the docker build). Can you please either help me out with a developer container or point me in the right direction why are tests failing? 🙏

2023-09-14 11:43 UTC, vkrizan commented on api/host.py
> +        host.reporter,
```
Traceback (most recent call last):
  File "/home/vkrizan/insights/insights-host-inventory/rebuild_events_topic.py", line 64, in run
    sync_event_message(json.loads(message.value()), session, event_producer)
  File "/home/vkrizan/insights/insights-host-inventory/app/queue/queue.py", line 204, in sync_event_message
    host.reporter,
AttributeError: 'LimitedHost' object has no attribute 'reporter'
```

2023-09-14 12:34 UTC, thearifismail commented
> Yup, will work on that

Looks like you got it working because I just checked out the `adjust-headers` branch and it passed all tests.

2023-09-14 19:01 UTC, thearifismail commented
I asked @fstavela to look into it because IQE tests are failing

2023-09-15 09:52 UTC, fstavela commented
/retest

2023-09-15 19:02 UTC, kruai approved these changes
The remaining IQE test failures appear to be due to intermittent network issues (remote disconnect stuff). I'd like to get another approval before merging, but this looks fine to me.

2023-09-15 20:35 UTC, thearifismail approved these changes

2023-09-18 09:21 UTC, fstavela approved these changes
LGTM

2023-09-18 12:51 UTC, merged