RHINENG-1653: Create DELETE /groups/hosts endpoint
RedHatInsights/insights-host-inventory pull request #1492
Opened 2023-09-19 13:37 UTC by FabriciaDinizRH

# Overview

This PR is being created to address [RHINENG-1653](https://issues.redhat.com/browse/RHINENG-1653).
It implements the DELETE `/groups/hosts/{host_id_list}` endpoint. The api spec was updated and tests were added for the new functionality.

I also did extracted the code for checking feature flags on the groups file to its own function since it is used multiple times in the code.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [x] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [x] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [x] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-09-22 13:53 UTC, jpramos123 approved these changes
LGTM!

2023-09-22 13:53 UTC, jpramos123 commented on api/group.py
> +def check_inventory_groups_flag():
It could be a generic function that receives the flag name, like:

`def check_unleash_flag(FLAG_NAME):`

2023-09-22 13:53 UTC, jpramos123 commented on api/group.py
> +def check_inventory_groups_flag():
Not a blocker btw!

2023-09-22 13:53 UTC, jpramos123 commented on api/group.py
> +        deleted_for_group = remove_hosts_from_group(
Should this variable be named `deleted_from_group`?
If not, forget it!!

```suggestion
        deleted_from_group = remove_hosts_from_group(
```

2023-09-25 10:56 UTC, FabriciaDinizRH commented on api/group.py
> +def check_inventory_groups_flag():
good suggestion, since it was going to be more generic, I moved it to the feature_flag file

2023-09-25 10:56 UTC, FabriciaDinizRH commented on api/group.py
> +        deleted_for_group = remove_hosts_from_group(
that's right!

2023-09-26 14:08 UTC, kruai requested changes
I have a couple suggestions, but I also wanted to say I really appreciate your thoroughness in your tests, especially `test_delete_hosts_from_different_groups_RBAC_denied`; it's great that you made sure that the changes were rolled back and no MQ events were produced.

2023-09-26 14:08 UTC, kruai commented on swagger/api.spec.yaml
> +        Delete a list of hosts from the groups they are in. [Not Implemented]
```suggestion
      summary: Delete a list of hosts from the groups they are in
      description: >-
        Delete a list of hosts from the groups they are in.
```

2023-09-26 18:12 UTC, FabriciaDinizRH commented on api/group.py
> +            hosts_per_group[str(group.id)].append(host_id)
very cool syntax, will update

2023-09-26 19:44 UTC, kruai approved these changes

2023-09-26 21:39 UTC, thearifismail commented on swagger/api.spec.yaml
> +  '/groups/hosts/{host_id_list}':
What's the purpose of `hosts` in `/groups/hosts/{host_id_list}` in this path when the implementing function is `api.group.delete_hosts_from_different_groups`?  Why can't the path in URL be `groups/{host_id_list}` should work?

2023-09-26 21:39 UTC, thearifismail commented on swagger/api.spec.yaml
> +  '/groups/hosts/{host_id_list}':
The function name `delete_hosts_from_groups` should be fine.  The word `different` in function name suggests that one host can be in more than one groups, which is not the case.

2023-09-26 21:39 UTC, thearifismail commented on api/group.py
> +def delete_hosts_from_different_groups(host_id_list, rbac_filter=None):
Since this is a REST API endpoint, it should use logger to log messages for debugging and error tracking.  I think the `abort()` calls in this and `rbac_group_id_check()` is going to abort without providing any information.

2023-09-26 21:39 UTC, thearifismail commented on api/group.py
> +        abort(status.HTTP_404_NOT_FOUND, "Hosts not found.")
Since host_ids_list is being provided, the correct message should be, "The provided hosts are ungrouped" or "The provided hosts are not in any group"

2023-09-26 21:39 UTC, thearifismail commented on swagger/openapi.json
> +            "description": "Hosts not found."
Same message as before, the provided hosts are not associated to any group

2023-09-27 11:18 UTC, FabriciaDinizRH commented on api/group.py
> +from lib.group_repository import get_group_from_host_id
yeah, that sounds better

2023-09-27 11:25 UTC, FabriciaDinizRH commented on swagger/api.spec.yaml
> +  '/groups/hosts/{host_id_list}':
@thearifismail The endpoint DELETE `/groups/{some_list_of_ids}` is used to delete groups, so I can't use it.
I though `delete_hosts_from_groups` was dangerously close to the existing `delete_hosts_from_group` so I wanted to make the function names more distinct. Do you have any suggestions on better wording, or just the `s` should be ok?

2023-09-27 14:02 UTC, FabriciaDinizRH commented on api/group.py
> +def delete_hosts_from_different_groups(host_id_list, rbac_filter=None):
That's true. But I think it would be good to create a new task for this, since this endpoint is not the only one using the main check function and new log and metric would have to be created.

2023-09-27 20:23 UTC, thearifismail commented on swagger/api.spec.yaml
> +  '/groups/hosts/{host_id_list}':
If the suggested path has already been taken, then `hosts/` in the URL should be fine and hope end users don't complain.

2023-09-27 20:40 UTC, thearifismail commented on api/group.py
> +def delete_hosts_from_different_groups(host_id_list, rbac_filter=None):
okay here is the JIRA card https://issues.redhat.com/browse/RHINENG-2320

2023-09-29 09:55 UTC, FabriciaDinizRH commented
/retest

2023-09-29 10:43 UTC, FabriciaDinizRH commented
The error in the required tests is "aborted connection", not related to the PR.

2023-09-29 13:08 UTC, thearifismail commented
/retest

2023-10-02 13:28 UTC, kruai approved these changes

2023-10-02 14:23 UTC, thearifismail approved these changes
LGTM!

2023-10-03 12:03 UTC, merged