fix(ESSNTL-5422): Improve error message
RedHatInsights/insights-host-inventory pull request #1506
Opened 2023-09-27 14:06 UTC by fellipeh

# Overview

This PR is being created to address [ESSNTL-5422](https://issues.redhat.com/browse/ESSNTL-5422).

Improving error messages on staleness endpoint

2023-09-27 14:16 UTC, kruai requested changes
Not sure `_get_org_id` it needs to be its own function since it's really simple, but it's not necessarily a problem either. I've just got one suggestion to streamline

2023-09-27 14:16 UTC, kruai commented on api/staleness.py
> +    return current_identity.org_id
Since current_identity is only used once, this can just be a one-liner
```suggestion
    return get_current_identity().org_id
```

2023-09-27 14:27 UTC, thearifismail commented on api/staleness.py
> +        abort(status.HTTP_404_NOT_FOUND, f"An account staleness record for org_id {_get_org_id()} does not exist.")
It is a host which goes stale NOT the account the host belongs to.

2023-09-27 14:27 UTC, thearifismail commented on api/staleness.py
> +        abort(status.HTTP_404_NOT_FOUND, f"An account staleness record for org_id {_get_org_id()} does not exist.")
```suggestion
        abort(status.HTTP_404_NOT_FOUND, f"Staleness record for org_id {_get_org_id()} does not exist.")
```

2023-09-27 14:47 UTC, thearifismail commented
@fellipeh can you please update your branch now that `account_staleness` have been replaced by `staleness` in the parent repo?

2023-09-27 14:48 UTC, fellipeh commented on api/staleness.py
> +    return current_identity.org_id
I refactored using your suggestion

2023-09-27 14:49 UTC, fellipeh commented on api/staleness.py
> +        abort(status.HTTP_404_NOT_FOUND, f"An account staleness record for org_id {_get_org_id()} does not exist.")
Make sense to have `Staleness`  word instead of Account Staleness

2023-09-27 14:49 UTC, fellipeh commented on api/staleness.py
> +        abort(status.HTTP_404_NOT_FOUND, f"An account staleness record for org_id {_get_org_id()} does not exist.")
Make sense to have `Staleness`  word instead of Account Staleness

2023-09-27 14:49 UTC, fellipeh commented on api/staleness.py
> +        abort(status.HTTP_404_NOT_FOUND, f"An account staleness record for org_id {_get_org_id()} does not exist.")
Make sense to have `Staleness`  word instead of Account Staleness

2023-09-27 15:46 UTC, fellipeh commented
/retest

2023-09-27 18:17 UTC, fellipeh commented
/retest

2023-09-28 13:18 UTC, thearifismail approved these changes

2023-09-28 13:51 UTC, kruai approved these changes

2023-09-28 16:50 UTC, merged