Change staleness/culling filter logic to handle multiple types of systems
RedHatInsights/insights-host-inventory pull request #1516
Opened 2023-10-05 17:37 UTC by jpramos123

# Overview

This PR is being created to address the following:
[ESSNTL-5050](https://issues.redhat.com/browse/ESSNTL-5050)
[ESSNTL-5051](https://issues.redhat.com/browse/ESSNTL-5051)
[ESSNTL-5215](https://issues.redhat.com/browse/ESSNTL-5215)
[ESSNTL-5036](https://issues.redhat.com/browse/ESSNTL-5036)

This PR has a lot of changes, please review it carefully!

It changes the way inventory builds its GraphQL queries to handle immutable (host_type == 'edge') and conventional  (host_type == None) hosts, with their new fresh, stale, stale_warning and deletion timestamps.
The same changes applies to the SQLAlchemy queries we do to the PostgresDB.

It also changes the way the host_reaper handle the host's exclusion order. It first searches for the org_ids that have a custom staleness created the in DB, otherwise it uses the system default values.

Several changes were made to the tests in order to get it working just fine.

One file with new tests specifically to the custom staleness was added as well.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-10-05 18:25 UTC, jpramos123 commented
/retest

2023-10-05 21:35 UTC, jpramos123 commented
/retest

2023-10-05 22:08 UTC, jpramos123 commented
/retest

2023-10-06 13:52 UTC, fellipeh submitted a review, later dismissed
LGTM.  Also I prefer more people looking at it before merge

cc @kruai @thearifismail

2023-10-09 11:18 UTC, fellipeh commented
/retest

2023-10-10 15:19 UTC, kruai requested changes
A few suggestions and comments

2023-10-10 15:19 UTC, kruai commented on lib/host_repository.py
> +    host_types = host_types
redundant
```suggestion
```

2023-10-10 15:19 UTC, kruai commented on swagger/api.spec.yaml
>                nullable: true
Why are the date-time formats being resolved?

2023-10-10 15:19 UTC, kruai commented on tests/test_api_hosts_update.py
> +    _ = db_create_staleness_culling(
```suggestion
db_create_staleness_culling(
```

2023-10-10 15:19 UTC, kruai commented on tests/test_api_facts.py
> +
Can you instead directly create hosts that are already in the stale/culled state? It would be best to not make the tests take longer. All of these `time.sleep()` calls would currently make the test suite take 26 seconds longer.

2023-10-10 15:28 UTC, jpramos123 commented on api/filtering/filtering.py
> +    stale_filter = staleness_filter(["not_culled"])
It is used here: https://github.com/RedHatInsights/insights-host-inventory/pull/1516/files#diff-e820e39e2b09650171328ecf510c90c8be448bd0ec61d31753609161b98417cfR96

In which calls this method is the class: https://github.com/RedHatInsights/insights-host-inventory/pull/1516/files#diff-e820e39e2b09650171328ecf510c90c8be448bd0ec61d31753609161b98417cfR75

2023-10-10 15:32 UTC, jpramos123 commented on app/xjoin.py
> +    ]
No! I like the suggestion!

Thanks for catching this

2023-10-10 15:37 UTC, jpramos123 commented on swagger/api.spec.yaml
>                nullable: true
Thanks for catching this! It was changed because of the `never` stale we had in the past. I will change this!

2023-10-10 18:58 UTC, jpramos123 commented on tests/test_api_facts.py
> +
I'm afraid it won't be able to be done.
The new staleness timestamps are based on the `modified_on` field from the host, that is not in the constructor and is updated automatically when something changes in the host.

We can create a new field tho.

Thoughts?

2023-10-10 20:19 UTC, kruai commented on tests/test_api_facts.py
> +
I would mock `datetime.now()` before creating the hosts - that should allow you to control the staleness then, right? There's info about mocking datetime in the python docs: https://docs.python.org/3/library/unittest.mock-examples.html#partial-mocking

2023-10-10 20:26 UTC, kruai commented on api/filtering/filtering.py
> +    stale_filter = staleness_filter(["not_culled"])
thanks!

2023-10-10 21:18 UTC, thearifismail reviewed
Still reviewing but this is to get rolling with changes if necessary

2023-10-10 21:18 UTC, thearifismail commented on lib/host_repository.py
> +    host_types = host_types
Is this assignment to itself is a left over from a previous version?  Should be removed.

2023-10-10 21:18 UTC, thearifismail commented on tests/fixtures/db_fixtures.py
> +def db_create_staleness_culling_1_second():
Will it be not more powerful and flexible to let the culling time be an input parameter; that way different time units could be used for testing?

2023-10-12 20:24 UTC, thearifismail reviewed
See comments

2023-10-12 20:24 UTC, thearifismail commented on tests/test_mq_service.py
> +    key, event, headers = mq_create_or_update_host(host, return_all_data=True)
```suggestion
    key, event, _ = mq_create_or_update_host(host, return_all_data=True)
```

2023-10-17 13:59 UTC, jpramos123 commented on tests/test_api_facts.py
> +
@kruai Thanks, I was able to create using this guide you shared.

@thearifismail For tests I would say it makes sense so we can validate that the application has the correct behavior for deleted/culled hosts. But in a normal usage, I understand it would be a bug, which is not the case here

2023-10-17 20:23 UTC, jpramos123 commented on swagger/api.spec.yaml
> +      description: "Culling states of the hosts. Default: fresh,stale"
We are going to replace "culling" by "delete" in a next PR.

Added `stale_warning`!

2023-10-17 20:39 UTC, jpramos123 commented on app/culling.py
>      def _stale_warning_timestamp(self):
Done

2023-10-17 20:39 UTC, jpramos123 commented on app/culling.py
> +    filtered_states = (state for state in staleness_states if state not in ("unknown",))
Removed!

2023-10-17 20:43 UTC, jpramos123 commented on app/queue/queue.py
> +                    # when setted once
Fixed typo

2023-10-17 20:45 UTC, jpramos123 commented on app/serialization.py
> +def serialize_acc_staleness(acc_st):
Done!

Thanks!

2023-10-17 20:46 UTC, jpramos123 commented on app/xjoin.py
> +from api.staleness_query import get_staleness_db
Changed to `get_staleness_obj`.

Thanks

2023-10-17 20:48 UTC, jpramos123 commented on lib/host_repository.py
> +    host_types = host_types
Removed!

2023-10-17 20:49 UTC, jpramos123 commented on tests/fixtures/db_fixtures.py
> +def db_create_staleness_culling_1_second():
We can use `db_create_staleness_culling` for this!

`db_create_staleness_culling_1_second` was created to address this specific case when all the values are set to 1.

2023-10-17 21:13 UTC, jpramos123 commented on tests/test_api_facts.py
> +    db_create_multiple_hosts, db_create_staleness_culling, api_put, clean_g
This value is always set when `get_staleness_db` now `get_staleness_obj` is called or when a new host is added/updated in MQ.

I prefer to have it like it is now. I will add a comment to the `clean_g` fixture to highlight when this value is created.

2023-10-17 21:17 UTC, jpramos123 commented on tests/helpers/graphql_utils.py
> +    conditions = staleness_conditions
Done!

2023-10-17 21:18 UTC, jpramos123 commented on tests/test_api_staleness_get.py
> +def test_get_default_staleness(api_get, clean_g):
See my response

2023-10-17 21:20 UTC, jpramos123 commented on tests/test_culling.py
> +def test_patch_ignores_culled(db_create_staleness_culling_1_second, mq_create_hosts_in_all_states, api_patch, clean_g):
changed to `test_fail_patch_culled_host`

2023-10-17 21:20 UTC, jpramos123 commented on tests/test_custom_staleness.py
> +    clean_g,
See my response above

2023-10-17 21:22 UTC, jpramos123 commented on tests/test_mq_service.py
> +    key, event, headers = mq_create_or_update_host(host, return_all_data=True)
Lets leave these changes for a future code factoring.
There are a lot of test cases that have the same code pattern

Thanks

2023-10-17 21:48 UTC, jpramos123 commented on app/culling.py
> +            None: {
Yes it is allowed!

And we need to use `None` to facilitate the filters for the `conventional` hosts

2023-10-18 20:38 UTC, thearifismail commented on tests/test_api_facts.py
> +    db_create_multiple_hosts, db_create_staleness_culling, api_put, clean_g
I meant `g` needs its own fixture for creating and removing it explicitly. Before the `clean_g` fixture was added, `g` was created indirectly and no one was aware of its existence.  Its need was felt after `clean_g` was added.  In future it will bite someone else at an inopportune time.  Given the size of this PR, let's approve the PR but a JIRA card should be created to properly handle `g`

2023-10-18 21:15 UTC, thearifismail approved these changes

2023-10-23 15:01 UTC, kruai requested changes
I need to review a few more things, but I have a few issues I listed. I also want to check with you... are the values in `g` thread-safe? If a pod is processing multiple hosts' data in separate threads, will there just be one value in g that gets overwritten by each one?

2023-10-23 19:07 UTC, jpramos123 commented on host_reaper.py
> +    query = session.query(Host).filter(*query_filter)
I will try to figure out one query so we can make it less stressful for the application to handle it!

Thank you for the deep review!

2023-10-24 15:37 UTC, fellipeh commented on tests/test_api_facts.py
> +    clean_g,
After reading the docs, looks like @jpramos123 has an point here.

2023-10-24 15:37 UTC, fellipeh submitted a review, later dismissed

2023-10-24 19:23 UTC, jpramos123 commented on lib/host_repository.py
> +    return and_(*filter_, (Host.system_profile_facts["host_type"].as_string() == host_type))
Correct, this happens when we have a `conventional` host

2023-10-25 13:29 UTC, kruai commented on tests/test_api_facts.py
> +    clean_g,
Interesting... I guess that makes sense for the API requests that use Flask, though I also see `flask.g` being used in a number of non-API contexts, like our MQ services, reaper, etc.
Since these don't use requests (and don't otherwise use Flask), would that not cause issues?

2023-10-27 21:40 UTC, jpramos123 commented on tests/test_api_facts.py
> +    clean_g,
@kruai  I think we are good!
If we look at MQ, the event attached to an [Application Context](https://github.com/RedHatInsights/insights-host-inventory/pull/1516/files#diff-08d3eb76a0fcb1dc61b0bfa4ca74d97315116073476ff033029a69ac180cf008L328)

And we are also [cleaning it](https://github.com/RedHatInsights/insights-host-inventory/pull/1516/files#diff-08d3eb76a0fcb1dc61b0bfa4ca74d97315116073476ff033029a69ac180cf008R348-R350) before sending any message.

Same apply to the host_reaper, as it is attached to flask's application context.

This is my understanding.

2023-10-30 14:43 UTC, kruai commented on tests/test_api_facts.py
> +    clean_g,
It's in an application context, but the same context is used for all processed messages, which appears to be the reason that cleaning is required (the variable stays even after we've moved on to a new message). It's scary to me to have this kind of manual teardown be required; it's also much more difficult to find out where the value for this global variable came from while debugging, especially since the value gets set any time someone calls `serialize_host()`... people aren't going to realize that serializing a host modifies the value of a global variable.

So for instance, if you're processing data for HostA and then need to serialize HostB for some reason, `g.acc_st` is now incorrect for HostA. 

@thearifismail @FabriciaDinizRH @fellipeh @fstavela  I don't want to hold up this PR since it seems there's time pressure on it, but am I the only one who has concerns about this direction? If it's just me, maybe we just need to make a follow-up Jira to make the global variable usage more clear or something?

2023-10-30 15:17 UTC, kruai requested changes
I wanna get opinions from the rest of the team on the comment thread I tagged them in, but also those calls to `time.sleep()` really need to be removed (see my previous review).

2023-10-30 16:30 UTC, fstavela commented on tests/test_api_facts.py
> +    clean_g,
In general, I'm not a fan of global variables and I try to limit their usage as much as possible, especially if they change values too often. However, I understand that sometimes they might be the best way to move forward.

I tried to review the usage of `g.acc_st`, but since it's a pretty big PR, I think it would be easier and quicker if we had a team call where you can explain and show where it's used and what is the purpose, and we can all discuss if it's the best approach. I think it would save time compared to everyone trying to review individually.

From what I understand from a quick look at the code, it is used mainly to save DB calls when we try to work with multiple hosts at the same time. If that's the case, wouldn't it be more clear to get the staleness values from DB at the beginning of the API request / when reaper starts, and then pass this value to other methods/functions where we need it as a parameter, instead of using the global variable? But again, my understanding might be wrong, so I'm open to hop on a call and discuss.

2023-10-31 19:59 UTC, thearifismail commented on tests/test_api_facts.py
> +    clean_g,
I questioned the use of `g.acc_st` when one of my PR was failing some tests in [def clean_g()](https://github.com/RedHatInsights/insights-host-inventory/blob/1e9c8a0f177902d3fa3719ce1814de41a7921c1c/tests/fixtures/app_fixtures.py#L37).  At the time I was focusing on get my tests passed; so I created the [PR #1507](https://github.com/RedHatInsights/insights-host-inventory/pull/1507).  The reason for telling tangential story is that I had hell of a time finding out how host-inventory tests were using `g` and not cleaning up.  This is inline with what @kruai has said in his comment.

IMO, the use of `g.acc_st` be removed and. like @fstavela, I don't like using global variables or constants.  I suggest reading the staleness from DB and passing it around as needed.

2023-11-06 19:01 UTC, jpramos123 commented
/retest

2023-11-08 22:09 UTC, jpramos123 commented on tests/test_custom_staleness.py
> +    time.sleep(1)
@kruai I will figure out a way of not using this, but lets try to move with this PR!

2023-11-08 22:09 UTC, jpramos123 commented on tests/test_api_facts.py
> +    clean_g,
Removed the usage of `g.acc_st`! 


Thanks for the discussion

2023-11-08 22:17 UTC, jpramos123 commented
/retest

2023-11-09 14:16 UTC, jpramos123 commented
/retest

2023-11-09 14:22 UTC, FabriciaDinizRH commented
> /retest

some of these errors are similar to Arif's PR (problems retrieving secrets) and the other one seems to be related to the quay problems Asa mentioned in slack 
`or: writing blob: initiating layer upload to /v2/cloudservices/insights-inventory/blobs/uploads/ in quay.io: denied: System is currently read-only. Pulls will succeed but all write operations are currently suspended."`

2023-11-09 16:04 UTC, kruai commented
/retest

2023-11-09 16:45 UTC, jpramos123 commented
/retest

2023-11-09 22:38 UTC, kruai requested changes
A few suggestions and questions. I think the tests look good (besides the `sleep` calls, which I won't block on for now), though I wanna look at them with fresher eyes tomorrow

2023-11-09 22:38 UTC, kruai commented on lib/group_repository.py
> +        custom_staleness = get_staleness_obj(get_current_identity())
Does the `custom_staleness` assignment need to happen inside the `session_guard`? Is there a scenario where we want `custom_staleness` to be `None`?
```suggestion
    custom_staleness = get_staleness_obj(get_current_identity())
    with session_guard(db.session):
        _add_hosts_to_group(group_id, host_id_list)
```

2023-11-09 22:38 UTC, kruai commented on lib/group_repository.py
> +        custom_staleness = get_staleness_obj(get_current_identity())
Same Q here:
```suggestion
    custom_staleness = get_staleness_obj(get_current_identity())
    with session_guard(db.session):
        new_group = Group(name=group_name, org_id=org_id, account=account)
        db.session.add(new_group)
        db.session.flush()
```

2023-11-09 22:38 UTC, kruai commented on lib/group_repository.py
> +
OK I see that this is happening a lot, so assume my question applies to each instance to reduce repetition lol

2023-11-09 22:38 UTC, kruai commented on lib/host_repository.py
> +def find_hosts_by_staleness(staleness_types, query, identity, host_types):
Does `host_types` need to be a param? From what I can tell, it's always going to be set to all host types (i.e. `["edge", None]`)

2023-11-09 22:38 UTC, kruai commented on lib/host_repository.py
> +def find_hosts_sys_default_staleness(staleness_types, host_types):
Same host_types comment here

2023-11-09 22:38 UTC, kruai commented on lib/host_repository.py
> +    return query.filter(or_(False, *staleness_conditions))
Shouldn't this just be an `or_` on all the staleness conditions? Adding False to the condition changes nothing, right? I see this happening in a lot of places, so just pretend I'm commenting this same thing in each place.

2023-11-09 22:38 UTC, kruai commented on lib/host_synchronize.py
> +                if custom_staleness_dict:
In what situation is this condition false?

2023-11-09 22:38 UTC, kruai commented on lib/host_synchronize.py
> +    custom_staleness = None
For scope safety, this should be done inside the `for host in host_list` loop. Otherwise the value will carry over from the previous loop until it is overwritten

2023-11-09 22:38 UTC, kruai commented on tests/test_custom_staleness.py
> +    time.sleep(1)
OK, I won't block on this for now

2023-11-10 13:04 UTC, jpramos123 commented on api/staleness_query.py
> +        logger.debug("Setting account staleness data to global request context")
Definitely! Removed it!

2023-11-10 13:08 UTC, jpramos123 commented on api/staleness_query.py
> +        acc_st = Staleness.query.filter(*filters).one()
Thanks! Good suggestion

2023-11-10 13:09 UTC, jpramos123 commented on api/staleness_query.py
> +    return acc_st
Agreed!

2023-11-10 13:16 UTC, jpramos123 commented on api/staleness_query.py
> +        from app import inventory_config
It was presenting circular imports, but looks like it is working just fine!

Moved the import to the top of the code

2023-11-10 13:19 UTC, jpramos123 commented on app/culling.py
> +        # Build this dictionary dynamically?
Yeah, maybe I was overthinking here hehe

2023-11-10 13:20 UTC, jpramos123 commented on app/culling.py
> +
Looks like it is not! I will remove it from the code base

2023-11-10 13:25 UTC, jpramos123 commented on app/culling.py
> +    return _filters
I think it was a code garbage that I left when I was debugging this piece of code!

Thanks for catching this!

2023-11-10 13:29 UTC, jpramos123 commented on app/serialization.py
> +                del serialized_host["system_profile"]["host_type"]
This is because of this change here: https://github.com/RedHatInsights/insights-host-inventory/pull/1516/commits/786b36bfede2950f54b05135f2ad4cee232a958e#diff-04429941e1177c2477b235a6601f8f45875cb9d3ca78996c6f27c85c9c4c136bR124-R126

We need the host type to be available all the type when we do a GraphQL query, so when we serialize the host, we can choose the correct staleness (immutable or conventional) staleness timestamps.

2023-11-10 19:31 UTC, thearifismail reviewed
left some comments.

2023-11-10 19:31 UTC, thearifismail commented on lib/host_synchronize.py
> +                if custom_staleness_dict:
It may be worth commenting that the org_id in a host and in custom_staleness are associated to the same Identity. That's why no comparison of org_ids is needed.

2023-11-10 19:31 UTC, thearifismail commented on tests/fixtures/db_fixtures.py
> +def db_create_staleness_culling_1_second():
This fixture is not needed at all as the tests using it did not need it.

2023-11-10 19:31 UTC, thearifismail commented on tests/test_culling.py
> +def test_put_facts_ignores_culled(db_create_staleness_culling_1_second, mq_create_deleted_hosts, api_put):
Culling 1 second fixture is not needed anymore

2023-11-10 19:31 UTC, thearifismail commented on tests/test_custom_staleness.py
> +    time.sleep(1)
Should there be a bogus staleness with timestamp values set to strings?

2023-11-13 16:47 UTC, jpramos123 commented on app/serialization.py
> +    }
Changed functions naming, added type hint and comment

Thanks

2023-11-13 17:11 UTC, jpramos123 commented on lib/host_repository.py
> +def find_hosts_by_staleness_reaper(staleness_types, identity, host_types):
Done! Removed the param and using the constant directly in the loop

2023-11-13 17:11 UTC, jpramos123 commented on host_reaper.py
> -    query_filter = exclude_edge_filter(stale_timestamp_filter(*conditions.culled()))
Deleted

2023-11-13 17:15 UTC, jpramos123 commented on host_reaper.py
> +    query_filters = filter_culled_hosts_using_sys_default_staleness(logger, org_ids, query_filters)
Agreed!

2023-11-13 17:19 UTC, jpramos123 commented on lib/group_repository.py
> +        custom_staleness = get_staleness_obj(get_current_identity())
I don't think it is a hard need. But I would guarantee that we are inside a session to perform this DB interaction!

There is no scenario where `custom_staleness` is `None`

2023-11-13 17:23 UTC, jpramos123 commented on lib/group_repository.py
> +        custom_staleness = get_staleness_obj(get_current_identity())
Same answer from above

2023-11-13 17:29 UTC, jpramos123 commented on lib/group_repository.py
> +
Same answer from above!

2023-11-13 17:30 UTC, jpramos123 commented on lib/host_repository.py
> +def find_hosts_by_staleness(staleness_types, query, identity, host_types):
Changed this definition, now I'm using the constant to perform the loops in the function that use `HOST_TYPES`

2023-11-13 17:40 UTC, jpramos123 commented on lib/host_repository.py
> +    return query.filter(or_(False, *staleness_conditions))
As we are creating the `or_` expressions dynamically (from a list of expressions), we need specify False at the beginning of the expression. See:

"_The [or_()](https://docs.sqlalchemy.org/en/20/core/sqlelement.html#sqlalchemy.sql.expression.or_) construct must be given at least one positional argument in order to be valid; a [or_()](https://docs.sqlalchemy.org/en/20/core/sqlelement.html#sqlalchemy.sql.expression.or_) construct with no arguments is ambiguous. To produce an “empty” or dynamically generated [or_()](https://docs.sqlalchemy.org/en/20/core/sqlelement.html#sqlalchemy.sql.expression.or_) expression, from a given list of expressions, a “default” element of [false()](https://docs.sqlalchemy.org/en/20/core/sqlelement.html#sqlalchemy.sql.expression.false) (or just False) should be specified_" [1]

``` python
from sqlalchemy import false
or_criteria = or_(false(), *expressions)
```

[1] [Link to `or_()` documentation](https://docs.sqlalchemy.org/en/20/core/sqlelement.html#sqlalchemy.sql.expression.or_)

2023-11-13 17:42 UTC, jpramos123 commented on lib/host_synchronize.py
> +                if custom_staleness_dict:
@kruai When there is no custom staleness data in the database. But thinking twice, this condition is redundant and is already being covered in the `try/except` for the `KeyError`

2023-11-13 17:44 UTC, jpramos123 commented on lib/host_synchronize.py
> +    custom_staleness = None
Alright, moved it to inside the the for loop

Thanks

2023-11-13 17:48 UTC, jpramos123 commented on api/staleness.py
> +        acc_st = get_staleness_obj()
Changed all references from `acc_st` to `staleness`

2023-11-13 17:54 UTC, jpramos123 commented on app/serialization.py
> +    # TODO: In future, this must handle groups staleness deltas
Done!

2023-11-13 17:57 UTC, jpramos123 commented on app/queue/queue.py
> +                input_host, identity, staleness_timestamps, custom_staleness=custom_staleness
Agreed! Changed to staleness!

2023-11-13 17:58 UTC, jpramos123 commented on app/serialization.py
> +        "conventional_staleness_delta": acc_st.conventional_staleness_delta,
Not in this case, here I only want the staleness values in a simple dictionary

2023-11-13 18:48 UTC, jpramos123 commented on app/queue/queue.py
> +                input_host, identity, staleness_timestamps, custom_staleness=custom_staleness
Changed most references to `staleness`

2023-11-13 21:48 UTC, thearifismail commented on tests/test_custom_staleness.py
> +    time.sleep(1)
The test asked will be good but I am not going to block the PR for not having a test using bogus timestamps.

2023-11-13 22:03 UTC, thearifismail approved these changes
My concerns appear to have been addressed.  Thanks.

2023-11-13 23:42 UTC, kruai commented on lib/host_repository.py
> +    return query.filter(or_(False, *staleness_conditions))
I appreciate the link! I would have thought that `*staleness_conditions` fulfill the role of 1+ positional arguments... but I guess the idea is that if `staleness_conditions` ends up being empty, it might cause the expression to fail?
All the unit tests still pass when I remove `False` from each of these instances, but you're def doing things according to the docs, so I yield :)

2023-11-13 23:45 UTC, kruai requested changes
It looks good to me, but there are 5 test failures that need to be addressed before merging (4 in `test_list_hosts_by_staleness`, 1 in `test_dedup_culled_host`).

2023-11-13 23:46 UTC, kruai approved these changes
Oops, I meant to hit the approve button :facepalm:
But please do determine whether a change needs to be made to the code or the tests that are currently failing

2023-11-13 23:54 UTC, jpramos123 commented
@kruai These tests are IQE tests! I spoke with Mike Sager and he told me I should ignore it for now.

I will move on and merge the code

2023-11-14 15:59 UTC, kruai commented
@jpramos123 informed me that @msager27 gave approval and that the test failures are expected, so I'm going to merge this.

2023-11-14 15:59 UTC, merged