feat(ESSNTL-5498): Change staleness perms
RedHatInsights/insights-host-inventory pull request #1530
Opened 2023-10-23 13:14 UTC by fellipeh

# Overview

This PR is being created to address [ESSNTL-5498](https://issues.redhat.com/browse/ESSNTL-5498).
Changing `staleness` permissions according to new workflow

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-10-23 13:23 UTC, fellipeh commented
/retest

2023-10-23 14:18 UTC, thearifismail reviewed
The code LGTM but the pipeline failing.

2023-10-23 15:05 UTC, kruai requested changes
We should have at least one RBAC test that validates that this approach works.

2023-10-24 18:27 UTC, thearifismail approved these changes

2023-10-24 18:54 UTC, jpramos123 approved these changes

2023-10-24 18:54 UTC, jpramos123 commented on tests/helpers/rbac-mock-data/inv-account-staleness-read-only.json
>            "permission": "inventory:staleness:read"
Maybe we can already add the newest `"staleness:staleness:read/write"` over here

2023-10-25 16:44 UTC, fellipeh commented
> i.e. it fails if the user has the staleness permission but not the host one, and vice-versa.

🤔 I understood exactly to be this way, looking the Miro flow design (link on ticket).

2023-11-01 13:57 UTC, fellipeh commented
/retest

2023-11-01 18:44 UTC, kruai approved these changes
optimally we'd want to check the staleness-read allowed/prohibited as well, but I won't block on that

2023-11-01 19:00 UTC, merged