rhineng-2302: update serialize_group function to exclude culled hosts from host cou…
RedHatInsights/insights-host-inventory pull request #1535
Opened 2023-11-02 20:26 UTC by thearifismail

…nt in a group

# Overview

This PR is being created to address [RHINENG-2303](https://issues.redhat.com/browse/RHINENG-2303).

It updates the `serialize_group` function to exclude culled hosts not yet removed by the host-reaper cronjob.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [x] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-11-06 21:11 UTC, kruai commented
@thearifismail FYI the link in the description is broken, and also `https://issues.redhat.com/browse/RHINENG-230` doesn't link to the correct ticket

2023-11-06 22:32 UTC, thearifismail commented
> @thearifismail FYI the link in the description is broken, and also `https://issues.redhat.com/browse/RHINENG-230` doesn't link to the correct ticket

@kruai thank you Fixed!!!

2023-11-07 11:07 UTC, FabriciaDinizRH reviewed
Just some minor comments, but the code looks good.

2023-11-07 11:07 UTC, FabriciaDinizRH commented on app/serialization.py
> +            staleness_delta = datetime.now(tz=timezone.utc) - host.stale_timestamp
```suggestion
            staleness_delta = current_time - host.stale_timestamp
```

2023-11-07 11:07 UTC, FabriciaDinizRH commented on app/serialization.py
> +            print((current_time - stale_timestamp).days - culling_delta.days)
Should this print still be here?

2023-11-07 11:07 UTC, FabriciaDinizRH commented on tests/test_api_host_group.py
> +def test_group_with_culle_hosts(
```suggestion
def test_group_with_culled_hosts(
```

2023-11-07 11:07 UTC, FabriciaDinizRH commented on tests/test_api_host_group.py
> +    response_status, response_data = api_get(GROUP_URL + "/" + ",".join([str(group_id)]))
there's a function in `api_utils.py` that builds the group url, I think it might look cleaner than creating the url manually

2023-11-07 14:56 UTC, kruai commented on app/serialization.py
> +            print((current_time - stale_timestamp).days - culling_delta.days)
nope

2023-11-07 15:05 UTC, thearifismail commented on app/serialization.py
> +            staleness_delta = datetime.now(tz=timezone.utc) - host.stale_timestamp
oh current_time and stale_timestamp should have been removed.  Gone!

2023-11-07 15:06 UTC, thearifismail commented on app/serialization.py
> +            print((current_time - stale_timestamp).days - culling_delta.days)
Gone!

2023-11-07 15:06 UTC, thearifismail commented on tests/test_api_host_group.py
> +def test_group_with_culle_hosts(
Fixed!

2023-11-07 15:06 UTC, thearifismail commented on tests/test_api_host_group.py
> +    response_status, response_data = api_get(GROUP_URL + "/" + ",".join([str(group_id)]))
oh thanks you!  Fixed!

2023-11-07 15:38 UTC, kruai requested changes

2023-11-07 15:38 UTC, kruai commented on tests/test_api_host_group.py
> +    # Confirm that the group now only contains 3 hosts
```suggestion
    # Confirm that the group contains 3 hosts
```

2023-11-07 15:38 UTC, kruai commented on tests/test_api_host_group.py
> +    response_status, response_data = api_get(build_groups_url(str(group_id)))
```suggestion
    _, response_data = api_get(build_groups_url(group_id))
```

2023-11-07 15:38 UTC, kruai commented on tests/test_api_host_group.py
> +    response_status, response_data = api_get(GROUP_URL + "/" + ",".join([str(group_id)]))
```suggestion
    _, response_data = api_get(build_groups_url(group_id))
```

2023-11-07 15:38 UTC, kruai commented on app/serialization.py
> +                group.hosts.remove(host)
We don't want to display the culled host, but this is modifying the DB. I have a couple issues with this:
- It's happening within an operation that should only be reading data, not modifying or deleting it
- It's not using the existing functions which were set up so that the proper MQ messages are sent to keep cyndi synced; in this case

imo, it would be better to return a filtered host count/host list in this function, which would then be used by `serialize_group`

2023-11-07 15:38 UTC, kruai commented on tests/fixtures/db_fixtures.py
> +
Not needed (see below)

2023-11-07 15:38 UTC, kruai commented on tests/test_api_host_group.py
> +    db_update_resource(culled_host)
Not needed; you have already updated the stale_timestamp in the line above. The test result is the same whether or not you call this function

2023-11-07 15:47 UTC, thearifismail commented on tests/test_api_host_group.py
> +    # Confirm that the group now only contains 3 hosts
fixed!!!

2023-11-07 15:48 UTC, thearifismail commented on tests/test_api_host_group.py
> +    response_status, response_data = api_get(build_groups_url(str(group_id)))
Fixed!

2023-11-07 15:48 UTC, thearifismail commented on tests/test_api_host_group.py
> +    response_status, response_data = api_get(GROUP_URL + "/" + ",".join([str(group_id)]))
Fixed!

2023-11-07 17:09 UTC, thearifismail commented on app/serialization.py
> +                group.hosts.remove(host)
Renamed the function which now returns a list of `unculled hosts`

2023-11-07 17:09 UTC, thearifismail commented on tests/fixtures/db_fixtures.py
> +
Gone!

2023-11-07 17:10 UTC, thearifismail commented on tests/test_api_host_group.py
> +    db_update_resource(culled_host)
Gone!

2023-11-07 17:16 UTC, thearifismail commented on app/serialization.py
> +            staleness_delta = datetime.now(tz=timezone.utc) - host.stale_timestamp
Fixed!

2023-11-07 20:56 UTC, kruai requested changes
looking better, just requesting a couple more changes.

Also, are you coordinating with @jpramos123? It may cause a conflict with his PR, and this implementation will need to be changed after his goes in

2023-11-07 20:56 UTC, kruai commented on app/serialization.py
> +    from app import inventory_config
What's the benefit of importing inside the function rather than the top of the file? From what I've found:

- This is a bit slower: the import is processed every time the function is called, which will be pretty frequent, since it's the serialization function
- If there's an issue with the import, it won't be detected until the function is run. If it's at the top of the file, it's detected on startup

2023-11-07 20:56 UTC, kruai commented on app/serialization.py
> +                hosts.append(host)
The length check is redundant; the for-each loop will just skip if the length is 0.
Also, `culling_delta` is set to the same value on every iteration of the loop. That should either be moved above the loop, or just simplified since `culling_delta` is only used once (see below):
```suggestion
    for host in group.hosts:
        staleness_delta = datetime.now(tz=timezone.utc) - host.stale_timestamp
        if staleness_delta < inventory_config().culling_culled_offset_delta:
            hosts.append(host)
```

2023-11-07 22:26 UTC, thearifismail commented on app/serialization.py
> +    from app import inventory_config
Putting at the top of the file encountered: 
```
Exception has occurred: ImportError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
cannot import name 'inventory_config' from partially initialized module 'app' (most likely due to a circular import) (/home/aarif/Documents/dev-ws/insights/insights-host-inventory/app/__init__.py)
  File "/home/aarif/Documents/dev-ws/insights/insights-host-inventory/app/serialization.py", line 7, in <module>
    from app import inventory_config
  File "/home/aarif/Documents/dev-ws/insights/insights-host-inventory/app/queue/events.py", line 14, in <module>
    from app.serialization import serialize_canonical_facts
  File "/home/aarif/Documents/dev-ws/insights/insights-host-inventory/app/__init__.py", line 27, in <module>
    from app.queue.events import EventType
  File "/home/aarif/Documents/dev-ws/insights/insights-host-inventory/run.py", line 4, in <module>
    from app import create_app
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,
ImportError: cannot import name 'inventory_config' from partially initialized module 'app' (most likely due to a circular import) (/home/aarif/Documents/dev-ws/insights/insights-host-inventory/app/__init__.py)
```
However, using a constant for the culling data solved the problem.

2023-11-07 22:44 UTC, thearifismail commented on app/serialization.py
> +                hosts.append(host)
Done!

2023-11-08 10:55 UTC, FabriciaDinizRH commented
/retest

2023-11-08 21:02 UTC, kruai commented on app/serialization.py
> +    from app import inventory_config
Oh, interesting!

2023-11-08 21:05 UTC, thearifismail commented on app/serialization.py
> +    from app import inventory_config
Yes, that's was the reason that I had put it inside the function to get going but then had forgotten to take care of it properly

2023-11-08 21:11 UTC, kruai commented on app/serialization.py
> +    from app import inventory_config
OK while I thought it was neat, calling `Config()` _is_ actually recreating the entire config from scratch, which isn't great. I'll experiment with the imports a bit

2023-11-08 21:25 UTC, kruai commented on app/serialization.py
> +    from app import inventory_config
OK @thearifismail, here's what I'd suggest. At the top of the file:
```
from flask import current_app
```
Then, you can compare the staleness in the function using:
```
if staleness_delta < current_app.config["INVENTORY_CONFIG"].culling_culled_offset_delta
```

2023-11-08 21:28 UTC, kruai commented on app/serialization.py
> +    from app import inventory_config
Optimally we'd want to remove a dependency that's causing the circular import issue, but I'll leave it up to you whether you wanna tackle that.

2023-11-08 21:30 UTC, kruai commented
> > Also, are you coordinating with @jpramos123? It may cause a conflict with his PR, and this implementation will need to be changed after his goes in
> 
> @kruai, No, I have not but I am not sure how it could conflict. If this PR look good to you, I think we should merge it and then deal with conflicts if there are any.

OK, as long as you're OK making another PR updating this implementation after his goes in.
Also, just so everyone's on the same page, I think we should get the go-ahead from @jpramos123 before merging.

2023-11-08 21:39 UTC, thearifismail commented
@jpramos123 Let's have a quick chat about it.  
@kruai are you okay with the current state of the PR?  If you're can you give it go-ahead?  I will merge it AFTER talking to @jpramos123.  Thanks.

2023-11-08 21:43 UTC, kruai commented
> @jpramos123 Let's have a quick chat about it. @kruai are you okay with the current state of the PR? If you're can you give it go-ahead? I will merge it AFTER talking to @jpramos123. Thanks.

I had tagged you in a comment in our `_get_unculled_hosts` thread. There's an issue with the use of `Config()`. I think it should be good to go after that's fixed

2023-11-08 22:06 UTC, jpramos123 commented
@kruai I spoke with @thearifismail and we agreed that we can move on with this code changes. They are not conflicting directly with #1516. We just need to make sure we change the way we filter the hosts after #1516 is merged.

Thanks

2023-11-08 22:27 UTC, thearifismail commented on app/serialization.py
> +    from app import inventory_config
I would like to resolve the dependency issue but not now, so I updated the code using your suggestion of using `from flask import current_app` for now.

2023-11-08 23:48 UTC, kruai approved these changes

2023-11-09 13:40 UTC, FabriciaDinizRH approved these changes
LGTM!

2023-11-09 13:44 UTC, FabriciaDinizRH commented
/retest

2023-11-09 13:53 UTC, FabriciaDinizRH commented
`Access denied to Vault Secrets at 'insights/secrets/qe/global/ibutsu'
Access denied to Vault Secrets at 'insights/creds/vault-insights-approle'`
`Error: authenticating creds for "quay.io": Requesting bear token: invalid status code from registry 500 (Internal Server Error)`

some secret errors in the build

2023-11-09 14:06 UTC, kruai commented
> `Access denied to Vault Secrets at 'insights/secrets/qe/global/ibutsu' Access denied to Vault Secrets at 'insights/creds/vault-insights-approle'` `Error: authenticating creds for "quay.io": Requesting bear token: invalid status code from registry 500 (Internal Server Error)`
> 
> some secret errors in the build

That first one might be caused by a recent PR, but the second one is definitely caused by the ongoing Quay outage.

2023-11-09 16:04 UTC, kruai commented
/retest

2023-11-09 16:43 UTC, merged