Update Grafana dashboard title to differentiate from ConsoleDot Dashboard
RedHatInsights/insights-host-inventory pull request #1555
Opened 2023-11-16 20:42 UTC by thearifismail

# Overview

This PR is being created to address [RHINENG-2397](https://issues.redhat.com/browse/RHINENG-2397).
(A description of your PR's changes, along with why/context to the PR, goes here.)

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-11-16 20:55 UTC, kruai requested changes
This changes a lot of stuff, but does not update the title. The title is on [this line](https://github.com/RedHatInsights/insights-host-inventory/pull/1555/files#diff-7cd9231d40270af1e95fd4a38a3dcdc48a52ba51f274416632fa8d2164aefe5aR1196).
Also, can you please update the name in the metadata as well (near the bottom of the file)? That's also likely to cause issues since it's exactly the same as the MSK dashboard.

2023-11-16 23:44 UTC, thearifismail commented
Title and the name in metadata updated.  The deleted expression was for a disabled query that should have been removed.

2023-11-22 13:03 UTC, FabriciaDinizRH approved these changes

2023-11-30 13:55 UTC, kruai approved these changes

2023-11-30 16:14 UTC, merged