fix(ESSNTL-2068): filtering logic for multiple  values for the same SP field
RedHatInsights/insights-host-inventory pull request #1559
Opened 2023-11-22 23:15 UTC by FabriciaDinizRH

# Overview

This PR is being created to address [ESSNTL-2068](https://issues.redhat.com/browse/ESSNTL-2068).
It changes the logic to always use OR when filtering for multiple values in the same system_profile field.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [x] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-11-23 22:03 UTC, FabriciaDinizRH commented
@fstavela I don't understand some of the IQE errors in the build (the `False(...)` ones specifically)

2023-11-27 18:02 UTC, thearifismail submitted a review, later dismissed

2023-11-30 20:48 UTC, kruai requested changes

2023-11-30 23:41 UTC, FabriciaDinizRH commented on api/filtering/filtering.py
> +            field_filter = ({list_operator: foo_list},)
Yeah, it should work for any comparator. I'll take a look at that

2023-12-06 13:54 UTC, fstavela commented
@FabriciaDinizRH There is just one issue and it's on the `sap_sids` filter. This field is a list, so we should keep the AND logic on the filter here. There 2 options for how to use this filter, either with a `contains` comparator or without any comparator. With the `contains` comparator (`filter[system_profile][sap_sids][contains][]=ABC&filter[system_profile][sap_sids][contains][]=C1E`) everything works fine and the filter uses `AND` logic. But, if I don't use any comparator (`filter[system_profile][sap_sids][]=ABC&filter[system_profile][sap_sids][]=C1E`), then it uses `OR` logic. UI uses this filter and it used `AND` logic until now, so I don't think we should change it.

I also found one more issue with the filtering of integer and datetime fields with different than `eq` comparators, like `gt`, `gte`, etc., but it didn't work even before this PR, so I created a new Jira for it and it can be fixed in another PR: https://issues.redhat.com/browse/RHINENG-5911

Otherwise, the PR works fine, thanks.

2023-12-14 20:58 UTC, FabriciaDinizRH commented
/retest

2023-12-18 17:11 UTC, kruai reviewed
Looks good, but just one question before I approve

2023-12-18 17:11 UTC, kruai commented on api/filtering/filtering.py
> +                    child_is_array,
`child_is_array` is equal to `child_spec["is_array"]`. Since we're already passing `child_spec` to the function, can we just determine whether it's an array from inside the builder function?

2023-12-19 14:15 UTC, FabriciaDinizRH commented on api/filtering/filtering.py
> +                    child_is_array,
you're right. I fixed it.
I'm not entirely satisfied with my solution but let me know what you think.

2023-12-19 23:19 UTC, kruai reviewed
I played around with this PR a bit, and I don't think the `is_array` param is needed. The changes I'd like to suggest would be too unwieldy for PR comments, so I've put them in this commit: https://github.com/RedHatInsights/insights-host-inventory/commit/ff3b75c3663e94f592115dcbd59dfafd0c26a1d5

Please correct me if I'm missing something though!

2024-01-03 13:38 UTC, FabriciaDinizRH commented
> I played around with this PR a bit, and I don't think the `is_array` param is needed. The changes I'd like to suggest would be too unwieldy for PR comments, so I've put them in this commit: [ff3b75c](https://github.com/RedHatInsights/insights-host-inventory/commit/ff3b75c3663e94f592115dcbd59dfafd0c26a1d5)
> 
> Please correct me if I'm missing something though!

@kruai the `sap_sids` fields should remain using the AND logic, as per Fero's last comment. That's why I included a check for 'is_array'.

2024-01-03 16:26 UTC, kruai commented
> > I played around with this PR a bit, and I don't think the `is_array` param is needed. The changes I'd like to suggest would be too unwieldy for PR comments, so I've put them in this commit: [ff3b75c](https://github.com/RedHatInsights/insights-host-inventory/commit/ff3b75c3663e94f592115dcbd59dfafd0c26a1d5)
> > Please correct me if I'm missing something though!
> 
> @kruai the `sap_sids` fields should remain using the AND logic, as per Fero's last comment. That's why I included a check for 'is_array'.

Ah, right - please disregard that suggestion, then. I've been re-reviewing and might have another suggestion this afternoon. Since `is_array` is implied by the contents of `spec`, and it feels like the logic for determining OR vs AND should be contained within `_get_list_operator`, I wanna try out a couple more things

2024-01-03 19:20 UTC, kruai requested changes
OK, just got a few suggestions for logic consolidation and cleanup.

2024-01-03 19:20 UTC, kruai commented on api/filtering/filtering.py
> +                    is_array=None,
Making a few suggestions for `is_array` to be False instead of None, since the naming and usage implies a boolean
```suggestion
                    is_array=False,
```

2024-01-03 19:20 UTC, kruai commented on api/filtering/filtering.py
> +def _base_filter_builder(builder_function, field_name, field_value, field_filter, operation, is_array=None, spec=None):
```suggestion
def _base_filter_builder(builder_function, field_name, field_value, field_filter, operation, is_array=False, spec=None):
```

2024-01-03 19:20 UTC, kruai commented on api/filtering/filtering.py
> +            field_filter = ({list_operator: foo_list},)
I think this logic should be contained within the `_get_list_operator` function, so that the logic for determining "OR" vs "AND" is done in one place. So L263 would change to:
```
list_operator = _get_list_operator(field_name, field_filter, operation, is_array)
```
and the function itself would change to:
```
def _get_list_operator(field_name, field_filter, operation, is_array):
    if (operation == "eq" and not is_array) or field_name in OR_FIELDS or field_filter == "object":
        # Filtering system_profile fields by multiple values of the same field uses OR logic,
        # fields with type array should have the default operator
        return "OR"
    else:
        return "AND"
```

2024-01-03 19:20 UTC, kruai commented on api/filtering/filtering.py
> +    builder_function, field_name, field_value, field_filter, operation, is_array=None, spec=None
```suggestion
    builder_function, field_name, field_value, field_filter, operation, is_array=False, spec=None
```

2024-01-03 19:20 UTC, kruai commented on api/filtering/filtering.py
> +        if is_array is None and spec is not None:
```suggestion
        if not is_array and spec is not None:
```

2024-01-03 19:20 UTC, kruai commented on api/filtering/filtering.py
> +        if is_array is None and spec is not None:
But also, is this conditional needed? In what situation would this apply?

2024-01-04 11:35 UTC, FabriciaDinizRH commented on api/filtering/filtering.py
> +        if is_array is None and spec is not None:
I used it as a way of populating `is_array` in case it is not provided but the `spec` is. But it turns out the code works fine without it.

2024-01-04 11:36 UTC, FabriciaDinizRH commented
/retest

2024-01-04 19:27 UTC, kruai approved these changes

2024-01-09 14:30 UTC, thearifismail approved these changes
LGTM

2024-01-09 15:02 UTC, merged