fix(RHINENG-4012): Validate custom staleness values are consisent
RedHatInsights/insights-host-inventory pull request #1570
Opened 2023-11-30 19:14 UTC by jpramos123

# Overview

This PR is being created to address [RHINENG-4012](https://issues.redhat.com/browse/RHINENG-4012).

Validates if staleness input values are consistent.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-12-11 15:10 UTC, kruai requested changes
Looking good, just a few recs

2023-12-11 15:10 UTC, kruai commented on app/models.py
> +
In order to reduce the repetition here, I suggest something like this:
```suggestion
        staleness_fields = ["time_to_stale", "time_to_stale_warning", "time_to_delete"]
        for host_type in ("conventional", "immutable",):
            for i in range(len(staleness_fields) - 1): # For all but the last field
                for j in range(i+1, len(staleness_fields)): # For all fields after that field
                    if data[(field_1 := f"{host_type}_{staleness_fields[i]}")] >= data[(field_2 := f"{host_type}_{staleness_fields[j]}")]:
                        raise MarshmallowValidationError(
                            f"{field_1} must be lower than {field_2}"
                        )
```

`field_1` and `field_2` can be instantiated on separate lines if L878 is too hard to read.

2023-12-11 17:54 UTC, jpramos123 commented on api/staleness.py
> +        validated_data = StalenessSchema().load(data_to_validate)
Loved it! Thanks!

2023-12-11 21:43 UTC, jpramos123 commented on tests/test_api_staleness_create.py
> +    assert_response_status(response_status, 400)
Added all scenarios to as parametrize! Thanks

2023-12-11 22:02 UTC, kruai approved these changes
LGTM if you were OK with my `validate_staleness` suggestion! I hope you didn't feel pressured to replace it completely - I wanted to reduce repetition, but we can meet halfway if you think it's a bit hard to read

2023-12-11 22:06 UTC, jpramos123 commented
> LGTM if you were OK with my `validate_staleness` suggestion! I hope you didn't feel pressured to replace it completely - I wanted to reduce repetition, but we can meet halfway if you think it's a bit hard to read

Naah!! I loved it! I was not able to see this path!! 

Thank you for the suggestion!

2023-12-12 13:47 UTC, jpramos123 commented
/retest

2023-12-12 14:16 UTC, merged