fix(RHINENG-4565): Add staleness GET permission tests
RedHatInsights/insights-host-inventory pull request #1578
Opened 2023-12-13 18:20 UTC by fellipeh

# Overview

This PR is being created to address [RHINENG-4565](https://issues.redhat.com/browse/RHINENG-4565).

Make sure we test RBAC permissions to GET staleness endpoint

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-12-14 18:31 UTC, kruai requested changes
Looks good, though I think it needs a test to make sure that verifies that the endpoint works correctly when an `rbac_filter` is provided (i.e. when the RBAC response has an `attributeFilter`, which is what was breaking it originally)

2023-12-14 19:21 UTC, thearifismail reviewed
Looks good with just one question?

2023-12-14 19:21 UTC, thearifismail commented on tests/test_api_staleness_get.py
> +    for response_file in STALENESS_READ_PROHIBITED_RBAC_RESPONSE_FILES:
Should there be a test with some valid RBAC permissions?

2023-12-15 13:21 UTC, fellipeh commented on tests/test_api_staleness_get.py
> +    for response_file in STALENESS_READ_PROHIBITED_RBAC_RESPONSE_FILES:
done

2023-12-15 14:14 UTC, fellipeh commented
/retest

2023-12-15 14:31 UTC, thearifismail approved these changes
LGTM

2023-12-15 16:17 UTC, fellipeh commented
/retest

2023-12-18 13:53 UTC, kruai requested changes

2023-12-18 13:53 UTC, kruai commented on tests/test_api_staleness_get.py
> +    url = build_staleness_url(query=f"?rbac_filter={rbac_filter}")
`rbac_filter` isn't a query param and doesn't make sense in this context. In order to replicate the scenario this PR is fixing, you need to set the attributeFilter of the RBAC response. Here's an example where we do this: https://github.com/RedHatInsights/insights-host-inventory/blob/master/tests/test_xjoin.py#L1452

2023-12-18 16:56 UTC, kruai requested changes

2023-12-18 16:56 UTC, kruai commented on tests/test_api_staleness_get.py
> +    url = build_sys_default_staleness_url()
The `rbac_filter` param is no longer used, so this change should probably just be reverted

2023-12-18 16:56 UTC, kruai commented on tests/test_api_staleness_get.py
> +def test_get_staleness_rbac_denied(subtests, mocker, api_get, db_get_staleness_culling, enable_rbac):
It doesn't look like `db_get_staleness_culling` is used anywhere

2023-12-18 16:56 UTC, kruai commented on tests/test_api_staleness_get.py
> +def test_get_staleness_rbac_allowed(subtests, mocker, api_get, db_get_staleness_culling, enable_rbac):
It doesn't look like `db_get_staleness_culling` is used anywhere here either

2023-12-18 17:57 UTC, kruai approved these changes

2023-12-18 17:57 UTC, fellipeh commented
/retest

2023-12-18 18:26 UTC, fellipeh commented
/retest

2023-12-18 18:51 UTC, merged