[RHINENG-6095] - Use custom staleness in per_reporter_staleness
RedHatInsights/insights-host-inventory pull request #1585
Opened 2024-01-02 20:15 UTC by jpramos123

# Overview

This PR is being created to address [RHINENG-6095](https://issues.redhat.com/browse/RHINENG-6095).

It fixes the wrong stale_timestamp in the per_reporter_staleness

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-01-02 20:24 UTC, thearifismail approved these changes
LGTM

2024-01-02 21:12 UTC, jpramos123 commented
/retest

2024-01-02 22:12 UTC, kruai approved these changes

2024-01-03 11:46 UTC, FabriciaDinizRH requested changes

2024-01-03 11:46 UTC, FabriciaDinizRH commented on app/serialization.py
> +        per_reporter_staleness[reporter]["stale_timestamp"] = _serialize_staleness_to_string(stale_timestamp)
As per [Fero's comment on Slack](https://redhat-internal.slack.com/archives/CQFKM031T/p1704272447515359?thread_ts=1704226749.219639&cid=CQFKM031T), `stale_timestamp` can't be used in the per reporter staleness.

2024-01-03 21:24 UTC, jpramos123 commented on app/serialization.py
> +        per_reporter_staleness[reporter]["stale_timestamp"] = _serialize_staleness_to_string(stale_timestamp)
Thanks, this is now fixed

2024-01-03 21:43 UTC, jpramos123 commented
/retest

2024-01-03 21:55 UTC, jpramos123 commented
/retest

2024-01-04 20:48 UTC, jpramos123 commented
/retest

2024-01-04 21:17 UTC, jpramos123 commented
/retest

2024-01-04 23:27 UTC, jpramos123 commented
/retest

2024-01-05 13:16 UTC, FabriciaDinizRH approved these changes
LGTM!

2024-01-05 13:20 UTC, FabriciaDinizRH reviewed
The code looks good but a few rest tests related to staleness culling are failing due to "no valid result obtained"

2024-01-05 15:01 UTC, kruai approved these changes

2024-01-05 15:33 UTC, thearifismail approved these changes

2024-01-05 17:53 UTC, merged