Enforce validation of User Identity field types
RedHatInsights/insights-host-inventory pull request #1589
Opened 2024-01-05 17:44 UTC by kruai

# Overview

This PR is being created to address concerns that were [raised on Slack](https://redhat-internal.slack.com/archives/CQFKM031T/p1704444852691029). Although the `is_org_id` field in the x-rh-identity header is a boolean value, it's safer for us to validate the types for these fields, so this PR enforces that. It also adds a test to make sure that various falsy/invalid values for `is_org_id` are not interpreted as truthy in our rbac bypass.

Follows up on #1580.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [x] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [x] Tests: validate exceptions and failure scenarios
- [x] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [x] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-01-05 19:02 UTC, FabriciaDinizRH requested changes

2024-01-05 19:02 UTC, FabriciaDinizRH commented on app/auth/identity.py
> +    user = m.fields.Nested(UserInfoIdentitySchema, required=True)
Since user is now required, `create_mock_identity_with_org_id()` on line 160 has to return an additional `user: {}` for the tests that are breaking to pass.

2024-01-05 20:33 UTC, kruai commented on app/auth/identity.py
> +    user = m.fields.Nested(UserInfoIdentitySchema, required=True)
Oh, that was actually an oversight; the user object should not be required. I'll remove that restriction.

2024-01-08 07:38 UTC, fstavela commented
/retest

2024-01-08 08:41 UTC, fstavela commented
/retest

2024-01-08 09:19 UTC, fstavela commented
/retest

2024-01-08 12:47 UTC, FabriciaDinizRH submitted a review, later dismissed
The all-tests errors seem unrelated to the PR, so all good!

2024-01-09 14:11 UTC, kruai commented on app/auth/identity.py
> +    last_name = m.fields.Str(validate=m.validate.Length(min=1))
Good call - I've removed the length validations.

2024-01-09 15:58 UTC, FabriciaDinizRH approved these changes

2024-01-09 15:59 UTC, FabriciaDinizRH commented
/retest

2024-01-09 16:02 UTC, thearifismail approved these changes
LGTM

2024-01-09 16:04 UTC, merged