Define separate resource params, remove unused floorist params
RedHatInsights/insights-host-inventory pull request #1595
Opened 2024-01-16 21:33 UTC by bsquizz

Separates CPU/mem requests & limits into separate parameters for each app component -- allowing us to tune them for better resource utilization in ephemeral environments.

2024-01-17 13:40 UTC, thearifismail submitted a review, later dismissed
LGTM

2024-01-17 14:15 UTC, kruai requested changes
The title says it's a draft, but the PR isn't a draft. Should it be?

2024-01-17 14:15 UTC, kruai commented on deploy/clowdapp.yml
> +- name: CPU_LIMIT_SYNCHRONIZER
```suggestion
- name: CPU_REQUEST_SYNCHRONIZER
```

2024-01-17 14:15 UTC, kruai commented on deploy/clowdapp.yml
> +- name: CPU_LIMIT_REAPER
```suggestion
- name: CPU_REQUEST_REAPER
```

2024-01-17 14:15 UTC, kruai commented on deploy/clowdapp.yml
> +- name: CPU_LIMIT_SP_VALIDATOR
```suggestion
- name: CPU_REQUEST_SP_VALIDATOR
```

2024-01-17 14:15 UTC, kruai commented on deploy/clowdapp.yml
> +- name: CPU_LIMIT_PENDO_SYNCHER
```suggestion
- name: CPU_REQUEST_PENDO_SYNCHER
```

2024-01-17 21:27 UTC, bsquizz commented on deploy/clowdapp.yml
> +- name: CPU_LIMIT_SYNCHRONIZER
Good catches here, fixed all of these

2024-01-17 21:48 UTC, bsquizz commented
Changes were merged into app-interface to support these new param names.

2024-01-18 13:57 UTC, kruai commented
@bsquizz Looks like the values in deploy-clowder.yml in app-interface don't abide by the limit-to-request ratio restriction (i.e. can't be more than 2:1)

2024-01-18 14:42 UTC, kruai commented
/retest

2024-01-18 16:01 UTC, kruai approved these changes
LGTM

2024-01-18 20:07 UTC, merged