[RHINENG-6095] - fix staleness filter
RedHatInsights/insights-host-inventory pull request #1617
Opened 2024-02-07 22:45 UTC by jpramos123

# Overview

This PR is being created to address [RHINENG-6095](https://issues.redhat.com/browse/RHINENG-6095).

It fixes a issue found when filtering hosts with `registered_with=`, before the it was not able to identify the correct staleness for each of the reporters. Now it is able to filter the hosts by the reporter_staleness per reporter correctly.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

2024-02-08 09:50 UTC, vkrizan commented on api/filtering/filtering.py
> +STALENESS_VALUES = ["not_culled"]
Doesn't this change the semantics of this constant to be default staleness values?

2024-02-08 09:50 UTC, vkrizan commented on api/filtering/filtering.py
> +        staleness = STALENESS_VALUES
Since the default was moved out of the `build_registered_with_filter` function, is the `None` handling of `staleness`  arg still necessary?

2024-02-08 14:49 UTC, jpramos123 commented on app/culling.py
> +def staleness_to_conditions_per_reporter(staleness, staleness_states, host_type, reporter, timestamp_filter_func):
Changed!

2024-02-08 14:53 UTC, jpramos123 commented on api/filtering/filtering.py
> +STALENESS_VALUES = ["not_culled"]
Yeah, make sense naming it as `DEFAULT_STALENESS_VALUES`

2024-02-08 14:54 UTC, jpramos123 commented on api/filtering/filtering.py
> +        staleness = STALENESS_VALUES
Not necessary anymore! Thanks for catching this

2024-02-08 15:34 UTC, vkrizan commented on app/culling.py
> +def staleness_to_conditions(staleness, staleness_states, host_type, reporter, timestamp_filter_func):
The reporter might have been last with `None` as a default. :slightly_smiling_face:

2024-02-08 16:11 UTC, kruai requested changes

2024-02-08 16:11 UTC, kruai commented on app/xjoin.py
> +def _stale_timestamp_per_reporter_filter(gt=None, lte=None, host_type=None, reporter=None):
Doesn't make sense to default this to `None`, since `per_reporter_staleness.reporter` can't be None/null

2024-02-08 16:11 UTC, kruai commented on app/culling.py
> +        )
This logic is iffy to me. Now `reporter` and `timestamp_filter_func` are tightly coupled and can be in conflict: if you call this function with `reporter="puptoo"` and `timestamp_filter_func=_stale_timestamp_filter`, it'll error out. It would also return unexpected results if you use `reporter=None` with `timestamp_filter_func=_stale_timestamp_per_reporter_filter`.

The cleanest way I can think to resolve this right now is:

1. Revert this function's changes (remove the reporter param, condition, etc), and remove the `None` reporter value from all the calls to `staleness_to_conditions`
2. In `per_reporter_staleness_filter`, use a partial function for the timestamp_filter_func param: `partial(_stale_timestamp_per_reporter_filter, reporter=reporter)`

Alternatively, we could add a `reporter` param to `_stale_timestamp_filter` that simply does nothing, but that feels iffy too. @vkrizan thoughts?

2024-02-08 19:23 UTC, jpramos123 commented on api/filtering/filtering.py
>          query_filters += build_registered_with_filter(registered_with, staleness)
Done! 

Thanks for the review

2024-02-08 19:24 UTC, jpramos123 commented on app/culling.py
> +        )
@kruai Loved this suggestion, I applied it to the code.

Now I'm using `partial` and not duplication the function

2024-02-08 19:36 UTC, jpramos123 commented on app/xjoin.py
> +def _stale_timestamp_per_reporter_filter(gt=None, lte=None, host_type=None, reporter=None):
I was forcing the null because of the following error:
`SyntaxError: non-default argument follows default argument`

But I changed the place of the `reporter` attribute and we are good now

Thanks

2024-02-08 20:18 UTC, kruai commented on app/xjoin.py
> +def _stale_timestamp_per_reporter_filter(gt=None, lte=None, host_type=None, reporter=None):
Ah OK, that amount of rewriting isn't worth it. Thanks for clarifying!

2024-02-08 20:19 UTC, kruai approved these changes

2024-02-09 01:58 UTC, merged

2024-02-09 10:31 UTC, vkrizan commented on app/culling.py
> +        )
Good idea with the `partial`.