Convert GET /system_profile/sap_system endpoint from XJoin to DB
RedHatInsights/insights-host-inventory pull request #1619
Opened 2024-02-08 15:44 UTC by chambridge

# Overview

This PR is being created to address [RHINENG-7077](https://issues.redhat.com/browse/RHINENG-7077).

* Add feature flag and new DB based call to API
* Create new DB query aggregation on sap_system value
* Add new test case to create sap_system entries and compare aggregation for true/false values

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-02-08 20:34 UTC, kruai requested changes

2024-02-08 20:34 UTC, kruai commented on tests/test_system_profile.py
> +        assert len(list(set(ordered_sap_system_data))) == len(response_data["results"])
Does it need to be converted to a list?
```suggestion
        assert len(set(ordered_sap_system_data)) == len(response_data["results"])
```

2024-02-08 20:34 UTC, kruai commented on tests/test_system_profile.py
> +            assert item_count == len(not_sap_list)
You know, I didn't think about this for `test_system_profile_operating_system`, but... I did all this shuffling and ordering for `test_get_hosts_order_by_operating_system` because I was validating the sorting of operating_system objects.  If ordering isn't important to these tests, all this might be kinda overkill. wdyt?

2024-02-08 22:39 UTC, chambridge commented on tests/test_system_profile.py
> +        assert len(list(set(ordered_sap_system_data))) == len(response_data["results"])
ok, pushed

2024-02-08 22:39 UTC, chambridge commented on tests/test_system_profile.py
> +            assert item_count == len(not_sap_list)
sure. removed.

2024-02-09 10:37 UTC, vkrizan commented on api/host_query_db.py
> +        Host.system_profile_facts["sap_system"].astext.cast(Boolean) is not None,
Isn't the `is not None` evaluated as statement here? AFAIK identity check with `is` cannot be overloaded (o be used by frameworks). But I might be wrong.

2024-02-09 14:38 UTC, chambridge commented on api/host_query_db.py
> +        Host.system_profile_facts["sap_system"].astext.cast(Boolean) is not None,
Searched at the Sqlalchemy on this topic. Looks like the `is not None` sequence results in just a `True` instead of adding a clause for `IS NOT NULL`. I've updated the code to use a `!= None` which looks like it is equivalent to the usage of `is_not(None)`.

2024-02-09 16:22 UTC, vkrizan approved these changes

2024-02-09 17:23 UTC, kruai approved these changes

2024-02-09 22:13 UTC, thearifismail approved these changes

2024-02-12 12:37 UTC, merged