Search for provider_id AND provider_type.
RedHatInsights/insights-host-inventory pull request #1631
Opened 2024-02-21 17:08 UTC by roliveri

# Overview

This PR is being created to address [RHINENG-2706](https://issues.redhat.com/browse/RHINENG-2706).

provider IDs are only guaranteed to be unique for the given provider_type. Because of this, both provider_id and provider_type must match in order to identify the host entry. 

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-02-21 17:49 UTC, roliveri commented
/retest

2024-02-22 00:24 UTC, roliveri commented
/retest

2024-02-28 02:09 UTC, kruai requested changes

2024-02-28 02:09 UTC, kruai commented on lib/host_repository.py
> +
I think this could use a comment explaining why, for posterity

2024-02-29 15:40 UTC, roliveri commented on lib/host_repository.py
> +
Most of the scenarios I've encountered are in testing. Many tests construct hosts and requests at a lower level, bypassing the schema checks. This check made it much easier to identify the tests that need to be updated, and should force newly added tests to conform to this restriction.

In addition, it may also be useful outside of testing, just in case the schema is changed or a new code path is added that bypasses the schema check.

2024-03-04 15:17 UTC, fstavela commented
I reviewed the failing test pipelines and they are failing because of a failing unit test:
```
19:43:44 =========================== short test summary info ============================
19:43:44 FAILED tests/test_api_host_group.py::test_group_with_culled_hosts - ValueErro...
19:43:44 = 1 failed, 1241 passed, 2 skipped, 20909 warnings, 1631 subtests passed in 59.37s =
```

2024-03-12 19:56 UTC, roliveri commented
@fstavela I don't see `tests/test_api_host_group.py::test_group_with_culled_hosts` failing.

I do see:
```
=========================== short test summary info ============================
14:05:53 FAILED tests/rest/test_deduplication.py::test_dedup_of_similar_hosts[provider_id]
14:05:53 = 1 failed, 196 passed, 7 skipped, 4703 deselected, 5046 warnings in 794.69s (0:13:14)
```
However, I believe the issue isn't with the test itself. This is probably an actual bug.
I'll have to dig deeper.

2024-03-13 19:01 UTC, roliveri commented
@fstavela I think I found the issue with `tests/rest/test_deduplication.py::test_dedup_of_similar_hosts` 

See: https://gist.github.com/roliveri/9bb0778f32c95cd1ee436a8d5986c764

I think lines 36-38 should be added, given both `provider_id` and `provider_type` must match.

What do you think?

2024-03-20 17:16 UTC, fstavela commented
> @fstavela I think I found the issue with `tests/rest/test_deduplication.py::test_dedup_of_similar_hosts`
> 
> See: https://gist.github.com/roliveri/9bb0778f32c95cd1ee436a8d5986c764
> 
> I think lines 36-38 should be added, given both `provider_id` and `provider_type` must match.
> 
> What do you think?

Thank you! You are right. I updated the tests and they should work now. Can you please rebase your branch?

2024-03-26 12:32 UTC, fstavela approved these changes
The remaining failed tests are not related to this PR, so I think we can merge this.

The failed reaper script tests are related to this issue: https://issues.redhat.com/browse/RHINENG-9031

The other failed tests had to be updated because of the recent schema and error msg changes. I've updated the tests and they pass now.

2024-03-26 14:48 UTC, kruai approved these changes

2024-03-26 15:02 UTC, FabriciaDinizRH approved these changes
LGTM!

2024-03-26 20:16 UTC, merged