Rhineng 6095 fix staleness reporter
RedHatInsights/insights-host-inventory pull request #1633
Opened 2024-02-28 14:15 UTC by jpramos123

# Overview

This PR is being created to address [RHINENG-xxxx](https://issues.redhat.com/browse/RHINENG-xxxx).
(A description of your PR's changes, along with why/context to the PR, goes here.)

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-03-04 20:47 UTC, thearifismail reviewed
@jpramos123 the PR looks good as programmed but I have questions that will be easier to ask over Google Meet than phrasing the questions properly here.

2024-03-04 20:47 UTC, thearifismail commented on api/tag.py
> +            staleness,  # Staleness to not use the default values
what does this comment mean?  What is lost when this comment is not provided?

2024-03-04 22:56 UTC, jpramos123 commented on api/tag.py
> +            staleness,  # Staleness to not use the default values
It is an old comment, I will remove it

2024-03-05 14:17 UTC, thearifismail approved these changes
LGTM

2024-03-05 16:19 UTC, kruai requested changes

2024-03-05 16:19 UTC, kruai commented on api/system_profile.py
> +        },
```suggestion
            hostFilter: {
                AND: $hostFilter,
        },
```

2024-03-05 16:19 UTC, kruai commented on api/system_profile.py
> +        },
```suggestion
            hostFilter: {
                AND: $hostFilter,
            },
```

2024-03-05 16:19 UTC, kruai commented on api/tag.py
> +        },
```suggestion
            hostFilter: {
                AND: $hostFilter,
            },
```

2024-03-05 16:19 UTC, kruai commented on api/filtering/filtering.py
> +
I know I bring this up every time, but I'm concerned about the staleness filter to be dependent on `registered_with`. As a user, I'd expect `registered_with` to filter the hosts in the exact same way regardless of whether I'm already using the `staleness` filter (and vice-versa).

Isn't the above logic functionally equivalent to the following?

```
    if staleness:
        staleness_filters = tuple(staleness_filter(staleness))
        query_filters += ({"OR": staleness_filters},)

    if registered_with:
        query_filters += build_registered_with_filter(registered_with)
```

The main difference is that your version has an extra "AND" that contains both filters, but the whole list of filters is ANDed on the top level anyway

2024-03-05 18:33 UTC, jpramos123 commented on api/filtering/filtering.py
> +
True, just realized that I made a change in the query it self, so it won't be necessary to add another AND to wrap the filter! 

Thanks for this!

I made some tests locally, and looks like I have the same behavior

2024-03-05 20:14 UTC, kruai requested changes
Still needs a few tweaks but it's almost there. And I just wanna shout out your work on the SAP stuff - great job standardizing that even more :smile:

2024-03-05 20:14 UTC, kruai commented on api/filtering/filtering.py
> +    return {"OR": prs_list}
Is there a reason for this change? Doing it this way makes it more cumbersome to add it to the filter list, i.e. why you had to change `query_filters += build_registered_with_filter(registered_with)` to `query_filters += (build_registered_with_filter(registered_with),)`. Also, all the other filter functions return a tuple rather than a dict

2024-03-05 20:14 UTC, kruai commented on api/system_profile.py
> +        },
The indentation is still off here

2024-03-05 20:14 UTC, kruai commented on api/system_profile.py
> +        },
The indentation is still off here as well

2024-03-05 20:14 UTC, kruai commented on api/tag.py
> +        },
Indentation still needs to be fixed here as well

2024-03-05 21:03 UTC, jpramos123 commented on api/filtering/filtering.py
> +    return {"OR": prs_list}
Actually, there is no reason for that.

I probably tested it with some code that was breaking it (I remember It was failing to concatenate something).

Just adjusted it back

2024-03-05 21:15 UTC, kruai approved these changes
LGTM assuming the build passes, and after @fstavela gives some kinda general thumbs up!

2024-03-06 12:29 UTC, fstavela approved these changes
I ran the tests that failed in the PR check again and they passed, so I wouldn't worry about that. I also ran some tests created by @msager27 for `registered_with` filter and a combination of that with `staleness`, and it seems to work fine. I would still like to let @msager27 test it more before we release it to Prod, but I didn't find any obvious issue, so I think we can safely merge this and then do additional testing in Stage.

2024-03-06 13:13 UTC, FabriciaDinizRH approved these changes

2024-03-06 13:13 UTC, merged