RHINENG-4837: Add dumb-init to enable hbi processes using PID 1
RedHatInsights/insights-host-inventory pull request #1634
Opened 2024-02-28 22:59 UTC by thearifismail

# Overview

This PR is being created to address [RHINENG-4837](https://issues.redhat.com/browse/RHINENG-4837).
@RonnyPfannschmidt here is the PR for your review.  

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-02-29 04:56 UTC, RonnyPfannschmidt requested changes
Please adopt args and the entry point script as the issue mentions

Without the script and args everything is worse

2024-02-29 04:56 UTC, RonnyPfannschmidt commented on deploy/clowdapp.yml
>          command:
This needs to use args,else it's broken on k8s

2024-03-01 11:27 UTC, RonnyPfannschmidt commented on deploy/clowdapp.yml
>          command:
Command replaces the docker entry point

Args replaces the docker command

When using command the docker entry point is ignored

2024-03-07 20:59 UTC, thearifismail commented
Replaced by https://github.com/RedHatInsights/insights-host-inventory/pull/1642

2024-03-22 15:39 UTC, kruai commented
Closing this because it was replaced by another PR.

2024-03-22 15:39 UTC, closed without merging