Allow in development APIs to be processed by Connexion but hidden from viewable spec
RedHatInsights/insights-host-inventory pull request #1635
Opened 2024-02-29 14:53 UTC by chambridge

# Overview

This PR is being created to address [RHINENG-8613](https://issues.redhat.com/browse/RHINENG-8613).
* Use middleware to capture the after request call and alter the json

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-02-29 15:00 UTC, chambridge commented
/retest

2024-03-01 10:41 UTC, vkrizan requested changes

2024-03-01 10:41 UTC, vkrizan commented on run.py
> +    if "openapi" not in response_text:
This is very rigid. This could affect any response from the app, that can have some serious consequences. 

This middleware for tampering with responses for OpenAPI is defined on the whole app scope, as opposed to a specific blueprint. Cannot be this configured an the openapi lib (swagger, or which one provides this)? Or make an enhancement to the lib. This implementation is way too high on the "stack" and with wide scope.

If there are no other possibilities to enhance the openapi lib directly, then matching on an request path would be preferred. Implementation should be separate from general `run.py`.

2024-03-01 13:59 UTC, chambridge commented on run.py
> +    if "openapi" not in response_text:
That's fair criticism. Here is an alternative implementation. But it comes with it that the team will need to manage the development openapi spec and update the customer facing spec when new or adjusted APIs are available:
https://github.com/RedHatInsights/insights-host-inventory/pull/1637

2024-03-01 15:01 UTC, closed without merging