feat(rhineng-8548): Create new indexes based on query analysis
RedHatInsights/insights-host-inventory pull request #1646
Opened 2024-03-07 21:07 UTC by chambridge

# Overview

This PR is being created to address [RHINENG-8548](https://issues.redhat.com/browse/RHINENG-8548).
* Add index for display_name from filter and order_by frequency
* Add index for system_profile_facts from filter frequency

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-03-07 21:40 UTC, thearifismail submitted a review, later dismissed

2024-03-08 13:32 UTC, thearifismail commented
/retest

2024-03-08 18:15 UTC, jpramos123 commented
/retest

2024-03-08 18:18 UTC, jpramos123 submitted a review, later dismissed

2024-03-08 18:42 UTC, jpramos123 commented
/retest

2024-03-13 13:05 UTC, kruai requested changes

2024-03-13 13:05 UTC, kruai commented on migrations/versions/7c97d8464b6b_add_indexes_for_display_name_and_system_.py
> +    op.execute("CREATE INDEX idxgroups ON hosts USING GIN (groups jsonb_ops);")
I recommend using `CONCURRENTLY` for the GINs, and potentially also `IF NOT EXISTS` for all of them.
`CONCURRENTLY` so that these upgrades don't lock the DB during the upgrade, and `IF NOT EXISTS` because each mq-p1 pod runs this on startup, and if the upgrade takes a while, those pods will just crashloop until the indexes have been created.

2024-03-14 00:25 UTC, chambridge commented on migrations/versions/7c97d8464b6b_add_indexes_for_display_name_and_system_.py
> +    op.execute("CREATE INDEX idxgroups ON hosts USING GIN (groups jsonb_ops);")
Ok. I've pushed an update based you your PR https://github.com/RedHatInsights/insights-host-inventory/pull/1638/files

2024-03-14 13:36 UTC, kruai approved these changes

2024-03-14 14:34 UTC, thearifismail approved these changes
LGTM

2024-03-19 12:48 UTC, kruai requested changes
The perf team was unable to run the migration because multiple pods tried to create `idxdisplay_name`.

2024-03-20 12:59 UTC, kruai approved these changes

2024-03-20 19:29 UTC, thearifismail approved these changes
LGTM

2024-03-21 12:21 UTC, kruai commented
/retest

2024-03-21 13:39 UTC, merged