RHINENG-4837: add dumb-init to run HBI containers
RedHatInsights/insights-host-inventory pull request #1655
Opened 2024-03-19 14:36 UTC by thearifismail

# Overview

This PR is being created to address [RHINENG-4837](https://issues.redhat.com/browse/RHINENG-4837).  It adds `dumb-init` and `run_command.sh` to run containers and ensures the desired commands running the pods are triggered by `dumb-init`.

cc: @RonnyPfannschmidt

This PR replaces PR #1634 and PR #1642 to avoid codE conflicts.

## top output from various pods
```
$ k exec -it host-inventory-mq-p1-647557d77b-q5968 -- top
Defaulted container "host-inventory-mq-p1" out of: host-inventory-mq-p1, host-inventory-mq-p1-init (init)

top - 13:59:50 up  1:19,  0 users,  load average: 1.09, 1.20, 0.83
Tasks:   4 total,   1 running,   3 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.7 us,  0.7 sy,  0.0 ni, 96.1 id,  1.4 wa,  0.0 hi,  0.1 si,  0.0 st
MiB Mem :  15995.9 total,   3168.9 free,   4350.6 used,   8476.4 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  10734.4 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                  
      8 1001      20   0 1720580  84520  18968 S   0.3   0.5   0:05.54 inv_mq_service.                          
      1 1001      20   0    4256    900    820 S   0.0   0.0   0:00.00 dumb-init                                
      7 1001      20   0   35032   3640   3212 S   0.0   0.0   0:00.00 run_command.sh                           
    244 1001      20   0   52112   4372   3728 R   0.0   0.0   0:00.00 top                                      

$ k exec -it host-inventory-mq-pmin-5b8b7dd9c-26gm4 -- top

top - 14:00:20 up  1:19,  0 users,  load average: 0.77, 1.11, 0.81
Tasks:   4 total,   1 running,   3 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.5 us,  1.5 sy,  0.0 ni, 93.0 id,  1.9 wa,  0.0 hi,  0.1 si,  0.0 st
MiB Mem :  15995.9 total,   3166.2 free,   4352.8 used,   8477.0 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  10732.2 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                  
      8 1001      20   0 1720656  84112  18584 S   0.3   0.5   0:05.86 inv_mq_service.                          
      1 1001      20   0    4256    932    856 S   0.0   0.0   0:00.00 dumb-init                                
      7 1001      20   0   35032   3732   3308 S   0.0   0.0   0:00.00 run_command.sh                           
    267 1001      20   0   52148   4076   3396 R   0.0   0.0   0:00.00 top                                      

$ k exec -it host-inventory-mq-sp-64ff8c86-qpflw -- top

top - 14:00:39 up  1:20,  0 users,  load average: 1.29, 1.21, 0.85
Tasks:   4 total,   1 running,   3 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.3 us,  1.2 sy,  0.0 ni, 93.3 id,  2.0 wa,  0.0 hi,  0.1 si,  0.1 st
MiB Mem :  15995.9 total,   3168.9 free,   4349.7 used,   8477.3 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  10735.3 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                  
      8 1001      20   0 1720684  84416  18856 S   0.7   0.5   0:06.08 inv_mq_service.                          
      1 1001      20   0    4256    932    852 S   0.0   0.0   0:00.00 dumb-init                                
      7 1001      20   0   35032   3480   3056 S   0.0   0.0   0:00.00 run_command.sh                           
    273 1001      20   0   52148   3972   3292 R   0.0   0.0   0:00.00 top                                      

$ k exec -it host-inventory-service-7d55d8665d-8xlc9 -- top

top - 14:01:05 up  1:20,  0 users,  load average: 1.89, 1.36, 0.91
Tasks:   8 total,   1 running,   7 sleeping,   0 stopped,   0 zombie
%Cpu(s):  4.6 us,  2.3 sy,  0.0 ni, 92.4 id,  0.5 wa,  0.0 hi,  0.3 si,  0.0 st
MiB Mem :  15995.9 total,   3166.1 free,   4352.1 used,   8477.7 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  10732.9 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                  
      1 1001      20   0    4256    852    772 S   0.0   0.0   0:00.00 dumb-init                                
      7 1001      20   0   35164   3532   3104 S   0.0   0.0   0:00.00 run_command.sh                           
      8 1001      20   0  352796  73180  14648 S   0.0   0.4   0:00.86 gunicorn                                 
     10 1001      20   0 1207256  81472  13888 S   0.0   0.5   0:04.24 gunicorn                                 
     11 1001      20   0 1207256  81408  13824 S   0.0   0.5   0:04.08 gunicorn                                 
     12 1001      20   0 1207256  81408  13824 S   0.0   0.5   0:03.97 gunicorn                                 
     13 1001      20   0 1207256  81528  13948 S   0.0   0.5   0:04.08 gunicorn                                 
    130 1001      20   0   52148   4016   3336 R   0.0   0.0   0:00.00 top                                      

$ 
```
## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-03-19 17:15 UTC, thearifismail commented
/retest

2024-03-20 10:34 UTC, RonnyPfannschmidt requested changes
in this i have mostly nitpicks about details on running the script


i recommend to unify the scripts into a flask shell config later on to ensure a managed entrypoint

more recent flask versions have cli tools 

https://flask.palletsprojects.com/en/3.0.x/cli/

2024-03-20 10:34 UTC, RonnyPfannschmidt commented on deploy/clowdapp.yml
> +          "gunicorn",
this one should be a function in the entrypoint script

2024-03-20 10:34 UTC, RonnyPfannschmidt commented on run_command.sh
> +    echo "ERROR: Provide a command to start one of the following:"
this help lies, as its not listing things one can run

i recommend adding a switch case for given names of subcommands so that help text and given commands can match

there should be a script command that evals $2

it should line up in a way that shifts both the command name and the script while leaving the rest of the args alone (so that one can pass extra args as desired)

2024-03-20 16:33 UTC, thearifismail commented
/retest

2024-03-20 17:02 UTC, thearifismail commented on run_command.sh
> +    echo "ERROR: Provide a command to start one of the following:"
Sorry this was the script I wrote a while back but yestereday, I put back in to make things work.  For the script is simplified to make it work. Elaborations should be done in a separate PR.

2024-03-20 17:03 UTC, thearifismail commented on deploy/clowdapp.yml
> +          "gunicorn",
IMO, this function should be implemented in a separate PR.  For the now the `dumb-init` works and meets the essence.

2024-03-22 12:07 UTC, thearifismail commented
@RonnyPfannschmidt What are your thoughts about my last comment about making `run_command.sh` more elaborate in a separate PR?

2024-03-22 12:44 UTC, RonnyPfannschmidt commented on run_command.sh
> +    echo "ERROR: Provide a command to start one of the following:"
its fine to do those changes later, but it will have the expense of more transitions in the deployment ccnfiguration

2024-03-22 13:14 UTC, RonnyPfannschmidt approved these changes
LGTM for the scope - we agreed to defer the restructure of the details of how the container chooses its purpose for a later point as that needs a small design spike before

2024-03-22 13:31 UTC, thearifismail commented
/retest

2024-03-22 14:31 UTC, kruai approved these changes
Seems like it still works as expected. I'm surprised that `python3` can be removed from the script execution command; does the `#!/usr/bin/python` you added to the top of the scripts implicitly tell dumb-init how to run them?

2024-03-22 14:54 UTC, thearifismail commented
> Seems like it still works as expected. I'm surprised that `python3` can be removed from the script execution command; does the `#!/usr/bin/python` you added to the top of the scripts implicitly tell dumb-init how to run them?

Yes.

2024-03-22 14:54 UTC, merged

2024-03-26 07:22 UTC, skateman commented
This broke our developer setup, nothing unfixable, but please next time let us know if you are changing something in the area so we can prepare 🙏

2024-03-26 12:33 UTC, thearifismail commented
@skateman I am sorry that your setup was affected by this change, but I am not sure how could have I anticipated that this local change would affect other services.  If you have an idea, please let me know for the next time.  Thanks.