refactor(RHINENG-8614): add missing error codes in API docs
RedHatInsights/insights-host-inventory pull request #1676
Opened 2024-03-28 10:56 UTC by FabriciaDinizRH

# Overview

This PR is being created to address [RHINENG-8614](https://issues.redhat.com/browse/RHINENG-8614).

- adds missing error codes to the following endpoints:
   - GET /hosts
   - GET /resource-types
   - GET /resource-types/inventory-groups
   - GET /account/staleness
   - PATCH /account/staleness
   - POST /account/staleness
   - GET /account/staleness/defaults

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-04-03 12:52 UTC, kruai requested changes
Looks good, just got one rec

2024-04-03 12:52 UTC, kruai commented on swagger/openapi.json
> +            "description": "Internal error."
IMO our 5xx errors don't need to be documented, because they mean that something internal broke that we weren't able to handle.

2024-04-03 13:02 UTC, kruai approved these changes
:+1:

2024-04-09 16:43 UTC, strider approved these changes
LGTM

2024-04-10 09:47 UTC, merged