bug(rhineng-9037): Handle embedded percents and colons values
RedHatInsights/insights-host-inventory pull request #1682
Opened 2024-04-01 17:22 UTC by chambridge

# Overview

This PR is being created to address [RHINENG-9037](https://issues.redhat.com/browse/RHINENG-9037).
* escape values with percents and colons to avoid unintended SQL interaction.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-04-01 17:55 UTC, kruai requested changes
The changes look good, but it could use a test to validate it

2024-04-02 09:46 UTC, vkrizan commented on tests/test_api_hosts_get.py
> +                host_list_or_id=created_hosts[0].id, query="?fields[system_profile]=os_kernel_version,owner_id"
Shouldn't the `query` argument take the `query` variable here?

2024-04-02 13:13 UTC, chambridge commented on tests/test_api_hosts_get.py
> +                host_list_or_id=created_hosts[0].id, query="?fields[system_profile]=os_kernel_version,owner_id"
🤦 I've fixed the test case now.

2024-04-02 13:38 UTC, chambridge commented
/retest

2024-04-02 14:03 UTC, kruai commented
/retest

2024-04-02 14:35 UTC, kruai approved these changes

2024-04-02 14:35 UTC, merged

2024-04-02 14:36 UTC, vkrizan commented on api/filtering/db_custom_filters.py
> +        value = escape_sql_from_string_val(value)
Where is the value properly escaped so there are no more "other" SQL interactions?