consolidate/correct  openapi types -
RedHatInsights/insights-host-inventory pull request #1734
Opened 2024-04-25 08:56 UTC by RonnyPfannschmidt

# Overview

This PR is being created to address [RHINENG-xxxx](https://issues.redhat.com/browse/RHINENG-xxxx).

* extract delay type
* consolidate optionals in type specification
* use allOf to compose the types better
* consolidate Per reporter Staleness timestamp type

- [ ] consolidate changes to prod openapi spec
- [ ] create the jira spike 
- [ ] validate date types

2024-06-05 12:24 UTC, RonnyPfannschmidt commented on swagger/api.spec.yaml
> +      - system_default
without this openapi-codegen creates a broken deserailizer (something abut collapsing primitive types and not passing over the validation regex)

2024-06-05 12:29 UTC, kruai requested changes
I appreciate the refactors! The one thing I'm requesting is that `openapi.json` needs to be updated as well, and at the moment I think that's a manual process...

2024-06-05 13:00 UTC, RonnyPfannschmidt commented
@kruai i believe we dont have a tool to fix it - i'll take a look at deep diffing

2024-06-05 13:39 UTC, kruai approved these changes

2024-06-11 12:50 UTC, kruai requested changes
There are 10 tests failing, all staleness-related. Looks like a schema issue.

2024-06-11 19:18 UTC, kruai requested changes

2024-06-11 19:18 UTC, kruai commented on app/serialization.py
> +        # TODO: investigate why e serialized ot the wrong names
Is this still a TODO?

2024-06-11 19:18 UTC, kruai commented on api/staleness_query.py
> +            "modified_on": None,
Shouldn't this now be `created` and `modified`?

2024-06-11 19:18 UTC, kruai commented on swagger/api.spec.yaml
> +
Why are all of these `400` responses being added?

2024-06-11 19:18 UTC, kruai commented on swagger/api.spec.yaml
> -        <br /><br />
This should not be removed.

2024-06-11 19:18 UTC, kruai commented on swagger/api.spec.yaml
> +        }
This isn't yaml formatting.

2024-06-11 19:18 UTC, kruai commented on tests/test_api_staleness_update.py
> +            pprint(data)
These should be removed

2024-06-11 19:18 UTC, kruai commented on dev.yml
The changes to this file break docker-compose for me. Are these solely to make it work with podman-compose?

2024-06-11 19:20 UTC, RonnyPfannschmidt commented on api/staleness_query.py
> +            "modified_on": None,
this replicates a db record - it really should use a namespace instead of a attrdict to make it more clear

its a serialize input, not a output

2024-06-11 19:21 UTC, RonnyPfannschmidt commented on dev.yml
let me undo it, i miss-added them when commiting - those are o make it work with docker-compose on rootless podman

2024-06-11 19:30 UTC, RonnyPfannschmidt commented on swagger/api.spec.yaml
> -        <br /><br />
good catch, this was a sync mistake (sap systems got removed from openapi.json)

2024-06-11 19:36 UTC, kruai commented on api/staleness_query.py
> +            "modified_on": None,
oops, my bad. thanks for clarifying

2024-06-11 19:36 UTC, kruai commented on swagger/api.spec.yaml
> +
`api.spec.yaml` is the source of truth - they should have been removed from openapi.json instead

2024-06-11 19:42 UTC, kruai commented on swagger/api.spec.yaml
> +
Unresolving, as this has not been addressed

2024-06-11 19:47 UTC, RonnyPfannschmidt commented on swagger/api.spec.yaml
> +
https://github.com/RedHatInsights/insights-host-inventory/pull/1676/files

this is a artifact of the manual sync - my followup pr will automate the snc

2024-06-11 19:49 UTC, RonnyPfannschmidt commented on app/serialization.py
> +        # TODO: investigate why e serialized ot the wrong names
nope, removed, thanks

2024-06-11 19:52 UTC, kruai commented on swagger/api.spec.yaml
> -        <br /><br />
This should not be removed

2024-06-11 20:10 UTC, RonnyPfannschmidt commented on swagger/api.spec.yaml
> -        <br /><br />
returned it, i vaguely recall sap_sytem being removed, however a history search yielded no results, so i suspet this one is a merge artifact

2024-06-11 20:11 UTC, kruai approved these changes

2024-06-11 20:37 UTC, kruai commented
/retest

2024-06-11 21:15 UTC, kruai commented
/retest

2024-06-11 21:44 UTC, merged