feat(RHINENG-8714): Consume events from platform.export.requests
RedHatInsights/insights-host-inventory pull request #1749
Opened 2024-05-06 20:13 UTC by jpramos123

# Overview

This PR is being created to address [RHINENG-8714](https://issues.redhat.com/browse/RHINENG-8714).
It created the HBI export-service and consume events from the export-service Kafka topic.

Todos:
- Add logs
- Add tests
- Add metrics

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-06-04 19:14 UTC, jpramos123 commented
/retest

2024-06-10 19:26 UTC, kruai requested changes

2024-06-10 19:26 UTC, kruai commented on app/queue/queue.py
> +def handle_export_message(message, event_producer, notification_event_producer, message_operation=create_export):
Are you expecting to need a different value for `message_operation`? We use that structure for our host-ingress MQ because the operation is different depending on the topic

2024-06-10 19:26 UTC, kruai commented on app/queue/export_service.py
> +    return "success"
Just to be clear, this will be done in a follow-up?

2024-06-10 19:26 UTC, kruai commented on deploy/clowdapp.yml
> +      minReplicas: ${{REPLICAS_SP}}
This should have its own separate replica count

2024-06-10 19:26 UTC, kruai commented on deploy/clowdapp.yml
> +            memory: ${MEMORY_REQUEST_MQ_SP}
This should have its own CPU and memory values as well

2024-06-10 19:26 UTC, kruai commented on inv_export_service.py
> +    topic_to_handler = {config.export_service_topic: create_export}
If this only ever listens to one topic, I don't think this is needed

2024-06-10 19:26 UTC, kruai commented on app/queue/export_service.py
> +    return "success"
I think this would make more sense as a boolean, if the function is just going to return whether it succeeded or failed

2024-06-11 14:59 UTC, jpramos123 commented on app/queue/queue.py
> +            raise ValidationError('application field must be "host-inventory"')
Good catch! This should be an extra validation. The way it is now, it will raise an error every time we the service finds an export-service that is not related to host-inventory application. Changed the code to validate the application in the message queue first.

2024-06-11 15:08 UTC, jpramos123 commented on app/queue/queue.py
> +def handle_export_message(message, event_producer, notification_event_producer, message_operation=create_export):
No, I just followed the same way we use to consume messages from host-ingress MQ...

2024-06-11 15:08 UTC, jpramos123 commented on app/queue/export_service.py
> +    return "success"
Yes!

2024-06-11 15:12 UTC, jpramos123 commented on deploy/clowdapp.yml
> +      minReplicas: ${{REPLICAS_SP}}
Done!

2024-06-11 15:12 UTC, jpramos123 commented on deploy/clowdapp.yml
> +            memory: ${MEMORY_REQUEST_MQ_SP}
Done!

2024-06-11 15:26 UTC, jpramos123 commented on inv_export_service.py
> +    topic_to_handler = {config.export_service_topic: create_export}
Removed, and adding the `create_export` function to the `message_operation` directly.

2024-06-11 15:27 UTC, jpramos123 commented on app/queue/export_service.py
> +    return "success"
I like this suggestion, changing it

Thanks

2024-06-11 17:04 UTC, thearifismail commented on lib/metrics.py
> +create_export_count = Counter("inventory_create_export", "The total amount of host exports created")
counter name confusing and incomplete.  What is being exported?

2024-06-11 17:04 UTC, thearifismail commented on tests/helpers/export_service_utils.py
> +                "x-rh-identity": "fakeId",
Shouldn't `x-rh-identity` value be an encoded string?

2024-06-11 17:15 UTC, thearifismail commented on app/queue/export_service.py
> +    if response.status_code != 202:
Should start using constants because they communicate precisely what that status is or expected. e.g. this one should be `HTTPStatus.ACCEPTED`

2024-06-11 20:51 UTC, jpramos123 commented on app/queue/export_service.py
> +def _handle_export_response(response, exportFormat, exportUUID):
The idea is to receive the response and validate if it succeeded or not. `create_export` is going to call it, which is on going in the implementation!

2024-06-11 20:55 UTC, jpramos123 commented on app/queue/metrics.py
> +    "inventory_export_service_message_parsing_seconds", "Time spent parsing a message from the export service"
I think they are needed so we can evaluate the efficiency of the methods we are creating for this feature and if needed improve it

2024-06-11 21:12 UTC, jpramos123 commented on app/queue/queue.py
> +    export_request_uuid = fields.Str(required=True)
Yeah, I think we can use fields.UUID. And no, it won't create a new UUID, but assign the UUID string to a UUID object.

2024-06-11 21:17 UTC, jpramos123 commented on app/queue/queue.py
> +        if data["application"] != "host-inventory":
`host-inventory` was the most convenient name to use in this case, which is the name of our service at the end. The message we receive from the `export-service` must contain this field with the specified name for us to process it on our side.
 
I forgot to change this one reference. We have a global variable called `EXPORT_SERVICE_APPLICATION` in the top of this file.

Changed to the correct reference.

2024-06-11 21:18 UTC, jpramos123 commented on app/queue/queue.py
> +def parse_operation_message(message):
This one is used by ingress MQ. At the end is process the MQ messages

2024-06-11 21:19 UTC, jpramos123 commented on app/queue/queue.py
> +    parsed_message = common_message_parser(message)
With this implementation yes, we have 2 kind of messages, one is from ingress MQ, other from this new `export-service` feature.

2024-06-11 21:20 UTC, jpramos123 commented on app/queue/queue.py
> +        and parsed_message["data"]["resource_request"]["application"] == EXPORT_SERVICE_APPLICATION
In the top of this file

2024-06-11 22:03 UTC, jpramos123 commented on app/queue/queue.py
> +def handle_export_message(message, event_producer, notification_event_producer, message_operation=create_export):
I think this naming is ok! We use the same for `handle_message` for the MQ messages as well

2024-06-11 22:04 UTC, jpramos123 commented on deploy/clowdapp.yml
> +    - name: export-service
I see, but the name of the service we are building is the `host-inventory-export-service`

2024-06-11 22:04 UTC, jpramos123 commented on inv_export_service.py
> +    register_shutdown(consumer_shutdown, "Closing consumer")
Changed to `"Closing export service consumer"`

2024-06-11 22:13 UTC, jpramos123 commented on lib/metrics.py
> +create_export_count = Counter("inventory_create_export", "The total amount of host exports created")
The hosts that are in the database are being extracted and exported to the user.
This is to count the number of times an export was created in the application so we can measure it

2024-06-11 22:22 UTC, jpramos123 commented on tests/helpers/export_service_utils.py
> +                "x-rh-identity": "fakeId",
Added an encoded string

2024-06-11 22:24 UTC, jpramos123 commented on app/queue/export_service.py
> +    if response.status_code != 202:
Good catch, changed to the correct status

2024-06-11 23:16 UTC, jpramos123 commented on app/queue/queue.py
>      except json.decoder.JSONDecodeError:
Added a test to validate empty `message`

2024-06-12 14:28 UTC, FabriciaDinizRH approved these changes

2024-06-12 14:28 UTC, FabriciaDinizRH commented on app/queue/metrics.py
> +export_service__message_handler_failure = Counter(
```suggestion
export_service_message_handler_failure = Counter(
```

2024-06-12 14:28 UTC, FabriciaDinizRH commented on app/queue/metrics.py
> +export_service__message_handler_time = Summary(
```suggestion
export_service_message_handler_time = Summary(
```

2024-06-12 20:37 UTC, jpramos123 commented on app/queue/metrics.py
> +export_service__message_handler_failure = Counter(
Thanks Fabi

2024-06-12 20:37 UTC, jpramos123 commented on app/queue/metrics.py
> +export_service__message_handler_time = Summary(
Thanks Fabi

2024-06-13 14:54 UTC, kruai reviewed
I think this is good, but I just wanted to follow up on one thing in an effort to simplify the implementation a bit

2024-06-13 14:54 UTC, kruai commented on app/queue/queue.py
> +def handle_export_message(message, event_producer, notification_event_producer, message_operation=create_export):
To follow up on this: can we not just remove that param, since the message operation is going to be the same no matter what?

2024-06-13 15:59 UTC, jpramos123 commented on app/queue/queue.py
> +def handle_export_message(message, event_producer, notification_event_producer, message_operation=create_export):
@kruai Done! I split the event loop into one specific for the export service and simplified the `handle_export_message` function

2024-06-13 19:32 UTC, merged