feat(RHINENG-8714): add resource string and change app string
RedHatInsights/insights-host-inventory pull request #1795
Opened 2024-06-18 11:17 UTC by jpramos123

# Overview

This PR is being created to address [RHINENG-8714](https://issues.redhat.com/browse/RHINENG-8714).

Add resource string and change the app string

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-06-18 12:09 UTC, jpramos123 commented
/retest

2024-06-18 19:34 UTC, jpramos123 commented
/retest

2024-06-18 20:31 UTC, kruai requested changes

2024-06-18 22:13 UTC, jpramos123 commented on app/queue/queue.py
>                          metrics.consumed_message_size.observe(len(str(msg).encode("utf-8")))
Thanks, removed it!

2024-06-19 01:30 UTC, kruai commented on app/queue/export_service.py
> +
OK. Still might be better for it to just be `export:systems` appended to `EXPORT_SERVICE_APPLICATION`, but it's nothing to block on.

2024-06-19 01:30 UTC, kruai approved these changes

2024-06-19 13:01 UTC, merged