[RHINENG-9060] Add DB Call for export service
RedHatInsights/insights-host-inventory pull request #1798
Opened 2024-06-18 14:50 UTC by strider

# Overview

to be written

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-06-19 14:12 UTC, jpramos123 requested changes

2024-06-19 14:12 UTC, jpramos123 commented on app/queue/export_service.py
> +        data_to_export = _handle_rbac_to_export(
This is going to fail with the following error:

```[inventory.app.queue.export_service] [ERROR] rbac() got an unexpected keyword argument 'org_id'```

We need to adapt the `rbac` middleware function in order to use it here correctly! Take a look in the PoC:

https://github.com/RedHatInsights/insights-host-inventory/pull/1671/files#diff-563d70d46b1e53533f16a52a0dad1bbe66b80afbb48c49e39850b08aa7a14fbd

2024-06-19 14:12 UTC, jpramos123 commented on app/queue/queue.py
> +    id = fields.UUID()
No need to add these values here. My last PR already creates the `ExportEventSchema` class to validate the data schema!

2024-06-19 16:57 UTC, strider commented on app/queue/queue.py
> +    id = fields.UUID()
Done

2024-06-19 16:58 UTC, strider commented on app/queue/export_service.py
> +        data_to_export = _handle_rbac_to_export(
Done

2024-06-19 16:58 UTC, strider commented on app/queue/export_service.py
> +        IDENTITY_HEADER: export_svc_data["data"]["resource_request"][IDENTITY_HEADER],
done

2024-06-19 16:58 UTC, strider commented on app/queue/export_service.py
> +from app.auth import get_current_identity
done

2024-06-19 16:58 UTC, strider commented on app/queue/export_service.py
> +    identity = get_current_identity()
done

2024-06-21 12:15 UTC, jpramos123 requested changes

2024-06-21 13:26 UTC, jpramos123 commented on api/host_query_db.py
> +    columns = [
I'm thinking here, instead of using this columns field fetch the entire Host object and create a custom serializer for the export service.

2024-06-21 13:26 UTC, jpramos123 commented on api/host_query_db.py
> +    results = query.with_entities(*columns)
We can have a larga amount of data depending of the customer that is going to export the data. We may use this functionality from sqlalchemy to help us on performance when doing DB queries:

https://docs.sqlalchemy.org/en/20/orm/queryguide/api.html#fetching-large-result-sets-with-yield-per

2024-06-26 13:32 UTC, jpramos123 commented on api/host_query_db.py
> +    filters = query_filters(rbac_filter=rbac_filter)
To fix the current issue, we should do something like this

```suggestion
    filters, _= query_filters(rbac_filter=rbac_filter)
```

2024-06-26 14:50 UTC, kruai commented on api/host_query_db.py
> +    results = query.with_entities(*columns)
Is there any reason we can't use `_find_all_hosts` for this? Seems like this function is duplicating a lot of it. Is it just the extra value in `group_by`?

2024-06-26 14:50 UTC, kruai commented on app/queue/export_service.py
> +    identity = create_mock_identity_with_org_id(org_id)
Just wanna confirm... when we receive an MQ message telling us to create an export, does it not have an identity on it (like in the metadata or something)?

2024-06-26 15:11 UTC, strider commented on app/queue/export_service.py
> +    identity = create_mock_identity_with_org_id(org_id)
Yes! 

For example:
`[2024-06-26 16:31:30,552] [73913] [8537656320] [inventory.app.queue.queue] [DEBUG] parsed_message: {'id': UUID('8dc7bb26-f6f1-4223-aa8a-764e88ea79e9'), 'schema': 'https://console.redhat.com/api/schemas/events/v1/events.json', 'source': 'urn:redhat:source:console:app:export-service', 'subject': 'urn:redhat:subject:export-service:request:6b345933-944d-470a-a14b-c803b3bb45bb', 'specversion': '1.0', 'type': 'com.redhat.console.export-service.request', 'time': datetime.datetime(2024, 6, 26, 14, 31, 30, tzinfo=datetime.timezone.utc), 'redhatorgid': '5894300', 'dataschema': 'https://console.redhat.com/api/schemas/apps/export-service/v1/resource-request.json', 'data': {'resource_request': {'application': 'urn:redhat:application:inventory', 'export_request_uuid': UUID('6b345933-944d-470a-a14b-c803b3bb45bb'), 'filters': {'endDate': '2024-04-01T00:00:00Z', 'productId': 'Ansible', 'startDate': '2022-02-01T00:00:00Z'}, 'format': 'json', 'resource': 'urn:redhat:application:inventory:export:systems', 'uuid': '8e814ddf-ef9a-4e25-b57a-7362b000c2c3', 'x_rh_identity': 'eyJpZGVudGl0eSI6IHsiYWNjb3VudF9udW1iZXIiOiAiYWNjb3VudDEyMyIsICJvcmdfaWQiOiAiNTg5NDMwMCIsICJ0eXBlIjogIlVzZXIiLCAidXNlciI6IHsiaXNfb3JnX2FkbWluIjogdHJ1ZSwgInVzZXJuYW1lIjogImZyZWQifSwgImludGVybmFsIjogeyJvcmdfaWQiOiAib3JnMTIzIn19fQ=='}}}`

2024-06-26 15:18 UTC, strider commented on api/host_query_db.py
> +
Yes It is useless. Will clean that up.

2024-06-26 17:03 UTC, strider commented on api/host_query_db.py
> +    results = query.with_entities(*columns)
No reason at all and this will be addressed in the next iteration.

2024-06-27 18:20 UTC, thearifismail commented on api/host_query_db.py
> +    q_base = (
how about calling it `base_query`?  Should it be called `group_query`, which is what it is?  Also the same code exists in two different functions with in the same file/module; better put it in a function and call the function when needed

2024-06-27 18:20 UTC, thearifismail commented on app/auth/identity.py
> +            "user": {"is_org_admin": False},
Is `is_org_admin` really needed that this function has to be updated?  Why not use the `return Identity(USER_IDENTITY)?

2024-06-27 18:20 UTC, thearifismail commented on app/queue/export_service.py
> +    identity = create_mock_identity_with_org_id(org_id)
Shouldn't the value of `x-rh-identity` be used instead of creating a mock identity?

2024-07-02 17:01 UTC, jpramos123 commented on api/host_query_db.py
> +    columns = [
@strider Lets fetch the entire host, without column filtering.

I created this card to create a serializer for the export service, and I'm going to work on it: [RHINENG-11163](https://issues.redhat.com/browse/RHINENG-11163)

2024-07-02 17:03 UTC, jpramos123 commented on app/queue/export_service.py
> +    identity = create_mock_identity_with_org_id(org_id)
@thearifismail We need to mock the identity to use the Identity object in the application. As we are not receiving an API call, the Identity is not automatically created by Flask. This is the reason of creating is by hand

2024-07-02 17:09 UTC, jpramos123 requested changes
Remove the columns filter, and fetch the entire host so we serialize the data to the format we need

2024-07-02 17:09 UTC, jpramos123 commented on api/host_query_db.py
> +    ]
```suggestion
```

2024-07-02 17:09 UTC, jpramos123 commented on api/host_query_db.py
> +    export_host_query = _find_all_hosts(query_base=query_base, columns=columns, identity=identity).filter(*q_filters)
```suggestion
    export_host_query = _find_all_hosts(query_base=query_base, identity=identity).filter(*q_filters)
```

2024-07-02 18:38 UTC, jpramos123 requested changes

2024-07-02 18:38 UTC, jpramos123 commented on api/host_query_db.py
> +        pass
Remove this portion of code from here, I will add it to the `export_service.py` when the JSON/CSV formatting is done.
```suggestion
```

2024-07-03 15:23 UTC, jpramos123 approved these changes

2024-07-08 13:44 UTC, strider commented
Rebasing, rebasing ...

2024-07-08 14:09 UTC, strider commented on api/host_query_db.py
> +from app.common import inventory_config
Yes, I am aware the `Config` class has better knowledge but in our case, it seems to be overkilled. In the last version of this PR, I am reusing the same code from `api.host_query.staleness_timestamps`

2024-07-08 14:09 UTC, strider commented on api/host_query_db.py
> +    export_host_query = _find_all_hosts(query_base=q_base, columns=columns, identity=identity).filter(*q_filters)
Yes it is needed.

2024-07-08 16:03 UTC, thearifismail commented on app/queue/export_service.py
> +            f"{config.export_service_endpoint}/app/export/v1/{exportUUID}/{applicationName}/{resourceUUID}/upload"
see the comment about creating a smaller structure holding different config params

2024-07-08 16:03 UTC, thearifismail commented on tests/helpers/export_service_utils.py
> +        "account": None,
`account` has been replace by `org_id`; is it still needed?

2024-07-09 12:19 UTC, strider commented on api/host_query_db.py
> +    export_format: str = "json",
That function is called from `app.queue.export_service.create_export`[1] with the `export_format` parameter coming from the export service event. I would prefer to let it here in the scope of this PR. And it will fully used by https://github.com/RedHatInsights/insights-host-inventory/pull/1826.

2024-07-09 12:20 UTC, strider commented on app/queue/export_service.py
> +            # todo(gchamoul):
This is addressed by RHINENG-9820 and https://github.com/RedHatInsights/insights-host-inventory/pull/1826

2024-07-09 12:23 UTC, strider commented on tests/helpers/export_service_utils.py
> +        "account": None,
That data example used in the tests are coming from the data the `utils/kafka_producer.py` script is generating. This script needs to be updated as well with the current schema version.

2024-07-09 13:09 UTC, thearifismail approved these changes
LGTM

2024-07-09 13:28 UTC, FabriciaDinizRH approved these changes
LGTM, great job!

2024-07-09 13:41 UTC, kruai commented on api/host_query_db.py
> +    )
I feel like I asked this before (sorry if I did), but does it need to group by both Group.id and Group.name here? If not, you could just call `_find_all_hosts` using the default query_base

2024-07-09 13:55 UTC, kruai commented on lib/middleware.py
> +
This kind of change makes me think we need to refactor or separate things out a bit. I don't want to block on this; however, I want to mess around with a refactor after it gets merged.

2024-07-10 13:16 UTC, kruai approved these changes
Looks great!

2024-07-10 19:44 UTC, jpramos123 approved these changes
LGTM

2024-07-12 22:26 UTC, merged