RHINENG-10853: creates structure for the stale host notification
RedHatInsights/insights-host-inventory pull request #1801
Opened 2024-06-21 15:46 UTC by FabriciaDinizRH

# Overview

This PR is being created to address [RHINENG-10853](https://issues.redhat.com/browse/RHINENG-10853).
I broke down [RHINENG-7833](https://issues.redhat.com/browse/RHINENG-7833) into 2 sub-tasks to make everyone's life easier, so this is the first one, addressing just the creation of the notification without the code to send it.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-06-24 15:13 UTC, kruai requested changes

2024-06-24 15:13 UTC, kruai commented on app/queue/notifications.py
> +# Stale became stale notification
```suggestion
# System became stale notification
```

2024-06-24 15:13 UTC, kruai commented on app/queue/notifications.py
> +    hostname = fields.Str(required=True)
Would it be more clear to rename this to "fqdn" to better differentiate this from "display_name"? (No change needed if you disagree)

2024-06-24 15:13 UTC, kruai commented on app/queue/notifications.py
> +    return result
tiny optional suggestion, since `result` is only used in this one location
```suggestion
    return SystemStaleSchema().dumps(notification)
```

2024-06-25 11:44 UTC, FabriciaDinizRH commented on app/queue/notifications.py
> +    hostname = fields.Str(required=True)
yeah, it makes sense

2024-06-26 14:53 UTC, kruai requested changes

2024-06-26 14:53 UTC, kruai commented on app/queue/notifications.py
> +            "fqnd": canonical_facts.get("fqdn", ""),
```suggestion
            "fqdn": canonical_facts.get("fqdn", ""),
```

2024-06-26 14:53 UTC, kruai commented on app/queue/notifications.py
> +            "fqnd": canonical_facts.get("fqdn", ""),
```suggestion
            "fqdn": canonical_facts.get("fqdn", ""),
```

2024-06-26 14:53 UTC, kruai commented on app/queue/notifications.py
> +    hostname = fields.Str(required=True)
OK, then I'll suggest:
```suggestion
    fqdn = fields.Str(required=True)
```

2024-06-26 15:25 UTC, roliveri commented on app/queue/notifications.py
> +                "payload": {
For this notification, is this set of canonical facts sufficient? Would it make sense to include others, like provider_id/provider_type, etc?

2024-06-26 16:12 UTC, FabriciaDinizRH commented on app/queue/notifications.py
> +                "payload": {
It is. You can see the example email at the second to last page of [this doc](https://docs.google.com/document/d/1-AjQsBrr9lYTZz22usov8RpWrUSkEJPaAA4Nhl6pYoo/edit) and it pretty much just uses the host_id.

2024-06-27 14:42 UTC, FabriciaDinizRH commented on app/queue/notifications.py
> +    hostname = fields.Str(required=True)
Hey, Jerome asked me to keep it as hostname for consistency with other notifications and third party services, so I added a comment explaining this

2024-06-27 15:46 UTC, roliveri approved these changes
LDTM

2024-06-27 16:52 UTC, strider approved these changes

2024-06-27 17:19 UTC, thearifismail reviewed
LGTM.  It will be nice to include in the notification when the system will be deleted.

2024-06-27 17:20 UTC, thearifismail approved these changes

2024-06-27 17:48 UTC, kruai approved these changes

2024-06-29 11:40 UTC, merged