Populate Kafka header with bootc information.
RedHatInsights/insights-host-inventory pull request #1824
Opened 2024-07-07 17:52 UTC by roliveri

# Overview

This PR is being created to address [RHINENG-9536](https://issues.redhat.com/browse/RHINENG-9536).
(A description of your PR's changes, along with why/context to the PR, goes here.)

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Include raw query examples in the PR description, if adding/modifying SQL query
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-07-08 05:34 UTC, skateman approved these changes
![The Seal of Approval](http://www.skateman.eu/seal.jpg)

2024-07-09 08:24 UTC, fstavela commented
/retest

2024-07-09 14:00 UTC, thearifismail reviewed
supporting @fstavela comment

2024-07-09 14:07 UTC, kruai approved these changes

2024-07-09 14:09 UTC, kruai requested changes
Oops - didn't see the IQE test failures and Fero's comment. Implementation looks good, but it sounds like the header needs to be a string.

2024-07-11 14:48 UTC, roliveri commented on app/queue/events.py
> +        "is_bootc": is_bootc,
@fstavela 
I'm not seeing this issue in the unit tests. Does that mean the EventProducer isn't properly covered in our unit tests?

2024-07-12 13:45 UTC, roliveri commented on app/queue/events.py
> +        "is_bootc": is_bootc,
@fstavela 
I've updated the code, changing `is_bootc` from a boolean to string representation ("True" of "False").

@skateman 
Please note the change in the datatype of `is_bootc` in the event header.

2024-07-12 14:03 UTC, roliveri commented
@fstavela 
It looks like most, if not all, of the remaining iqe test failures should be resolved by updating `events_message_expected_headers()`, in `mq_utils.py`, to include the `is_bootc` header.

2024-07-15 11:48 UTC, fstavela approved these changes

2024-07-15 11:50 UTC, fstavela commented
> @fstavela It looks like most, if not all, of the remaining iqe test failures should be resolved by updating `events_message_expected_headers()`, in `mq_utils.py`, to include the `is_bootc` header.

You are right, everything looks good now. I have an MR with the necessary updates ready, but I can't merge it until this PR is merged, because then the tests would be failing on other PRs. If it's possible, I suggest merging this PR even with the failed PR checks and then I will update the tests immediately. If it's not possible, I can skip the tests first, let the PR check pass and then I can update and reenable them.

2024-07-15 15:14 UTC, thearifismail approved these changes

2024-07-15 15:42 UTC, merged