[RHINENG-9820] Structure export content in JSON/CSV
RedHatInsights/insights-host-inventory pull request #1826
Opened 2024-07-09 00:26 UTC by jpramos123

# Overview

This PR is being created to address [RHINENG-9820](https://issues.redhat.com/browse/RHINENG-9820).
It adds a host serializer specific for the export-service and a JSON to CSV parser.

TODO:
1. Tests

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Include raw query examples in the PR description, if adding/modifying SQL query
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-07-15 16:47 UTC, thearifismail reviewed
What are the required host_params for creating an export_service_event? 
Need a test missing the required host_params for an export event
Test using bogus attributes; export event should no created

2024-07-15 16:47 UTC, thearifismail commented on app/serialization.py
> +    def _find_host_state(host, stale_timestamp, stale_warning_timestamp):
host not needed as an input param

2024-07-15 16:47 UTC, thearifismail commented on app/serialization.py
> +    serialized_host["system_check_in"] = _serialize_datetime(host.modified_on)
`modified_on` and `updated` are already.  Can one of those be used instead of introducing a new parameter `system_check_in`?

2024-07-15 16:47 UTC, thearifismail commented on app/serialization.py
> +def serialize_host_export_service(host: Host, staleness_timestamps, staleness) -> dict:
There is a `seralize_host()` and this function.  Can the common attributes be put in a common but smaller function for cleaner implementation and avoid repetition

2024-07-15 16:47 UTC, thearifismail commented on app/serialization.py
> +def serialize_host_export_service(host: Host, staleness_timestamps, staleness) -> dict:
Should there be any validation as to what host attributes be included in the export event?

2024-07-15 16:47 UTC, thearifismail commented on app/serialization.py
> +    serialized_host["host_type"] = host.host_type
Should it check if host_type has its value to avoid having serialized_host["host_type"] = None

2024-07-15 21:30 UTC, jpramos123 commented on app/queue/export_service.py
>  EXPORT_SERVICE_SYSTEMS_RESOURCE = "urn:redhat:application:inventory:export:systems"
Sorry for the confusion. But this is going to be used in the API request we send to the Export Service API.

It is being implemented by @strider in this PR: https://github.com/RedHatInsights/insights-host-inventory/pull/1830

2024-07-15 22:13 UTC, jpramos123 commented on app/serialization.py
> +def serialize_host_export_service(host: Host, staleness_timestamps, staleness) -> dict:
@thearifismail Changed the name to `serialize_host_for_export`.

I would like to keep these serializer separated as in future would be easier to remove/add new parameters.

For the export event, we already validate what we get from the kafka queue. The hosts payload are validated in the tests with the expected fields

2024-07-15 22:13 UTC, jpramos123 commented on app/serialization.py
> +    def _find_host_state(host, stale_timestamp, stale_warning_timestamp):
Thanks

2024-07-15 22:13 UTC, jpramos123 commented on app/serialization.py
> +    serialized_host["system_check_in"] = _serialize_datetime(host.modified_on)
I think it make sense, changed to `modified_on`

2024-07-15 22:14 UTC, jpramos123 commented on app/serialization.py
> +    serialized_host["system_check_in"] = _serialize_datetime(host.modified_on)
Same value is used by notifications, and this is what the customer will see at the end. I would like to keep it as it is.

2024-07-15 22:15 UTC, jpramos123 commented on app/serialization.py
> +    serialized_host["host_type"] = host.host_type
We have two values for the `host_type` field, one is `None` other is `edge`. So we are good with `serialized_host["host_type"] = None`

2024-07-15 22:17 UTC, jpramos123 commented
> What are the required host_params for creating an export_service_event? Need a test missing the required host_params for an export event Test using bogus attributes; export event should no created

Host parameters are fixed, the client/user won't be able (at least for now) of choosing the parameters to be returned.

We already have tests for validating the expected fields for the message we receive from kafka.

2024-07-16 12:30 UTC, strider submitted a review, later dismissed
LGTM

2024-07-16 20:49 UTC, thearifismail commented on app/serialization.py
> +    serialized_host["system_check_in"] = _serialize_datetime(host.modified_on)
I was trying to limit the variablity

2024-07-16 20:49 UTC, thearifismail commented on app/queue/export_service.py
>  EXPORT_SERVICE_SYSTEMS_RESOURCE = "urn:redhat:application:inventory:export:systems"
Question is does this string value/pattern `urn:redhat:application:inventory:export:systems` follow some logic and hierarchy.  Say `urn:inventory:export:systems` will work?

2024-07-17 17:56 UTC, jpramos123 commented on app/queue/export_service.py
>  EXPORT_SERVICE_SYSTEMS_RESOURCE = "urn:redhat:application:inventory:export:systems"
@thearifismail yes, they follow a logic. It uses the URN scheme[1]. It is unique and is used to validate a resource.
The standard we are using here is `urn:NID:application:INSIGHTS_APP_NAME:export:TYPE_OF_EXPORT`

Thanks for this question!

[1] https://en.wikipedia.org/wiki/Uniform_Resource_Name

2024-07-17 18:30 UTC, thearifismail commented
> > What are the required host_params for creating an export_service_event? Need a test missing the required host_params for an export event Test using bogus attributes; export event should no created
> 
> Host parameters are fixed, the client/user won't be able (at least for now) of choosing the parameters to be returned.
> 
> We already have tests for validating the expected fields for the message we receive from kafka.

Where are the fixed host parameters? A host has a lot more parameters than the ones returned for each host by the `get_hosts_list()` function

2024-07-17 18:50 UTC, thearifismail commented
@jpramos123 I had [this comment](https://github.com/RedHatInsights/insights-host-inventory/pull/1798/files#r1668905850) on @strider's PR, which he said would be added to PR #1826.  What happened it.

2024-07-17 19:01 UTC, thearifismail reviewed
LGTM except for this [comment](https://github.com/RedHatInsights/insights-host-inventory/pull/1798/files#r1668905850)

2024-07-17 20:11 UTC, kruai requested changes
A few requests

2024-07-17 20:11 UTC, kruai commented on tests/helpers/export_service_utils.py
> +    ]
To avoid repetition, and so you don't have to update it each time you update the header:
```suggestion
    row = [mocker.ANY] * len(header)
```

2024-07-17 20:11 UTC, kruai commented on tests/helpers/export_service_utils.py
> +    ]
This same list of fields is re-used a lot. Can we refactor it?

2024-07-17 20:11 UTC, jpramos123 commented
> @jpramos123 I had [this comment](https://github.com/RedHatInsights/insights-host-inventory/pull/1798/files#r1668905850) on @strider's PR, which he said would be added to PR #1826. What happened it.

@thearifismail I think this can be implemented in this PR: https://github.com/RedHatInsights/insights-host-inventory/pull/1830
As it is related to the communication of inventory with the export service

@strider May we address arif's suggestion on in next PR?

2024-07-19 14:29 UTC, jpramos123 commented on app/serialization.py
> +def serialize_host_for_export(host: Host, staleness_timestamps, staleness) -> dict:
Done

Thanks @thearifismail and @kruai

2024-07-19 14:30 UTC, jpramos123 commented on app/serialization.py
> +        return state
Done

2024-07-19 14:31 UTC, jpramos123 commented on tests/helpers/export_service_utils.py
> +    ]
Done!

Thanks!!

2024-07-19 14:37 UTC, jpramos123 commented on tests/helpers/export_service_utils.py
> +    ]
Added `_EXPORT_SERVICE_FIELDS` to `app.serialization` and reusing it on the tests!

2024-07-19 14:40 UTC, jpramos123 commented on app/serialization.py
> +        hasattr(host, "system_profile_facts")
Looks like it is not. As this a default column in the DB.
At the end I just copied this part of the code from the `serialize_host` function. This one is going to die now

Thanks

2024-07-19 14:50 UTC, strider approved these changes
LGTM

2024-07-19 17:36 UTC, kruai reviewed
Loving all the improvements! I just have one more suggestion, but I won't block on it

2024-07-19 17:36 UTC, kruai commented on app/culling.py
> +    def find_host_state(stale_timestamp, stale_warning_timestamp):
Tiny suggestion
```suggestion
    @staticmethod
    def find_host_state(stale_timestamp, stale_warning_timestamp):
```

2024-07-19 18:07 UTC, kruai approved these changes

2024-07-19 21:16 UTC, thearifismail approved these changes
Don't want to block the PR because of a couple of minor concerns.

2024-07-19 21:16 UTC, thearifismail commented on app/serialization.py
> +_EXPORT_SERVICE_FIELDS = [
What is the benefit of keeping it private, i.e. starting with `underscore` provide when it is being imported by other modules?

2024-07-19 21:16 UTC, thearifismail commented on app/serialization.py
> +                serialized_host["group_id"] = host.groups[0]["id"]  # Assuming just one group per host
Is it expected to change when multiple groups have the same host, i.e. when host.groups[1]["id"] will have a value?

2024-07-21 16:04 UTC, jpramos123 commented on app/serialization.py
> +                serialized_host["group_id"] = host.groups[0]["id"]  # Assuming just one group per host
Yes it is!! We can may change it in future.

2024-07-21 16:04 UTC, jpramos123 commented on app/serialization.py
> +_EXPORT_SERVICE_FIELDS = [
It is only used here and in a test...

2024-07-21 16:04 UTC, merged