feat(RHINENG-10853): add logic to newly registered system notifications
RedHatInsights/insights-host-inventory pull request #1844
Opened 2024-07-22 19:02 UTC by FabriciaDinizRH

# Overview

This PR is being created to address [RHINENG-10853](https://issues.redhat.com/browse/RHINENG-10853).

- add the logic necessary to send the notifications for newly registered hosts.
- add a few changes to `notifications.py` that will be overwritten by the [refactoring PR](https://github.com/RedHatInsights/insights-host-inventory/pull/1825)

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [x] Descriptive comments provided in complex code blocks
- [ ] Include raw query examples in the PR description, if adding/modifying SQL query
- [x] Tests: validate optimal/expected output
- [x] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-07-23 09:24 UTC, fstavela commented
/retest

2024-07-23 22:39 UTC, thearifismail reviewed
@FabriciaDinizRH I am not done but have comment on the code.  One question is when a host does not have an `insights_id`, like this [line](https://github.com/RedHatInsights/insights-host-inventory/blob/d830962a7de6adafc8c04c981242376874c6e7c0/app/queue/notifications.py#L137), does it mean that no notification will be sent?

2024-07-25 23:37 UTC, FabriciaDinizRH commented on app/queue/notifications.py
> +    tags = fields.Raw()
Using Dict() gives me the following error in several tests:
`ValueError: dictionary update sequence element #0 has length 3; 2 is required`

2024-07-30 09:03 UTC, vkrizan commented on app/queue/notifications.py
> +    tags = fields.Raw()
Can you decode the error for Dict?

2024-07-30 09:03 UTC, vkrizan commented on app/queue/notifications.py
> +        groups = host.get("groups")
Second parameter of `dict.get` is a default value. Can it be used here instead of doing the key check?

2024-07-30 09:03 UTC, vkrizan commented on app/queue/notifications.py
> +        system_profile = host.get("system_profile")
Similar to these two above...

2024-07-30 09:03 UTC, vkrizan commented on tests/test_mq_service.py
> -def test_verify_bootc_in_headers(expected_value, system_profile, mq_create_or_update_host):
Why is this test being removed?

2024-07-30 09:03 UTC, vkrizan commented on tests/test_notifications.py
> -    assert notification["account_id"] == SYSTEM_IDENTITY["account_number"]
Please keep the check for account_id as it still might be used on event consumers.

2024-07-30 10:02 UTC, FabriciaDinizRH commented on app/serialization.py
> +        if os.get("name").lower() == "rhel":
the default is "". Since the field is rhel version, if the os is not rhel this field would be an empty string.

2024-07-30 13:09 UTC, FabriciaDinizRH commented on tests/test_notifications.py
> -    assert notification["account_id"] == SYSTEM_IDENTITY["account_number"]
Mikel Barcina from the notification team said I could remove it because they just ignore it as well

2024-07-30 13:10 UTC, FabriciaDinizRH commented on tests/test_mq_service.py
> -def test_verify_bootc_in_headers(expected_value, system_profile, mq_create_or_update_host):
ouch, that's a merge fix that went wrong

2024-07-30 21:00 UTC, FabriciaDinizRH commented on app/serialization.py
> +        if os.get("name").lower() == "rhel":
Yeah, you're right. I see, `lower()` would raise an error there, I'll fix it

2024-07-31 16:22 UTC, FabriciaDinizRH commented on app/queue/notifications.py
> +    tags = fields.Raw()
done

2024-07-31 16:23 UTC, FabriciaDinizRH commented on app/queue/queue.py
> +            if message_operation == add_host:
I didn't want to pass the `notification_event_producer` to the other operations, but since there's just one other, I did it

2024-08-01 15:53 UTC, kruai commented on app/queue/queue.py
> +
The main issue I foresee with this is that the message is sent before the transaction has been committed to the DB. This could lead to situations where the notification is sent, but then the transaction is rolled back (and the host is not created). The host events are produced here upon a successful commit: https://github.com/RedHatInsights/insights-host-inventory/blob/search-tag-dollar-sign/app/queue/queue.py#L546

2024-08-01 15:53 UTC, kruai commented on tests/helpers/mq_utils.py
> +    }
Should these be of type `set`, since they're being compared to sets directly below this?

2024-08-01 15:53 UTC, kruai commented on tests/test_mq_service.py
> +    mock_notification_event_producer.write_event.assert_called_once()
IIRC, the original intent of this `assert_not_called()` was to assert that there was no notification produced due to validation errors. Can we make a more specific assertion so we know that this is producing a "host added" notification rather than a "validation error" notification?

2024-08-01 16:20 UTC, jpramos123 approved these changes
One comment

2024-08-01 16:28 UTC, jpramos123 requested changes
Please take a look above question

2024-08-01 21:29 UTC, FabriciaDinizRH commented on app/queue/queue.py
> +def update_system_profile(host_data, platform_metadata, notification_event_producer=None, operation_args={}):
It fails because I added the notification producer [here](https://github.com/RedHatInsights/insights-host-inventory/pull/1844/files/8062b2eeebb20d0c7c9db6553d4cc55f844ed37d#diff-08d3eb76a0fcb1dc61b0bfa4ca74d97315116073476ff033029a69ac180cf008R356) and that calls this function as well, so it needs to be there

2024-08-02 16:16 UTC, FabriciaDinizRH commented on tests/helpers/mq_utils.py
> +    }
I thought sets containing values could be initialized using curly braces. Is it outdated/unused currently?

2024-08-08 20:41 UTC, jpramos123 commented on app/queue/queue.py
> +
Understood!

Now we need to figure out how to:
1. Know when the message receive is related to add_host
2. A way to of having `host_data` outside of this function

2024-08-12 20:39 UTC, jpramos123 submitted a review, later dismissed

2024-08-12 20:41 UTC, jpramos123 commented on tests/helpers/mq_utils.py
> +    }
@FabriciaDinizRH is correct here! There are sets, not dicts

2024-08-12 21:07 UTC, kruai requested changes

2024-08-12 21:07 UTC, kruai commented on app/queue/queue.py
> +        self.serialized_host = sh
We can make this change without adding a `serialized_host` field to this class (redundant since we have host_row). You can just call the serialization function when it's needed. For example: https://github.com/RedHatInsights/insights-host-inventory/blob/master/app/queue/queue.py#L416

2024-08-12 21:07 UTC, kruai commented on app/serialization.py
> +            return f"{major}.{minor}"
This change seems irrelevant to the PR's purpose

2024-08-12 21:07 UTC, kruai commented on tests/helpers/mq_utils.py
> +    }
My mistake! Thank you for the information.

2024-08-12 21:07 UTC, kruai commented on tests/test_mq_service.py
> +    mock_notification_event_producer.write_event.assert_called_once()
This one is still open ^

2024-08-12 22:32 UTC, jpramos123 commented on tests/test_mq_service.py
> +    mock_notification_event_producer.write_event.assert_called_once()
Using `assert_called_once` is not the expected behavior? We generate the notification in line 134 then we use the assertion

2024-08-12 22:35 UTC, kruai commented on tests/test_mq_service.py
> +    send_notification(mock_notification_event_producer, NotificationType.new_system_registered, host.data())
Just noticed this - is this manually sending a notification from the test? If that's the case, then won't `mock_notification_event_producer.write_event` always have been called in the assertion?

2024-08-13 15:59 UTC, thearifismail approved these changes
LGTM

2024-08-13 16:16 UTC, jpramos123 commented on tests/test_mq_service.py
> +    send_notification(mock_notification_event_producer, NotificationType.new_system_registered, host.data())
Yes it is calling it, otherwise `mock_notification_event_producer.write_event` will never be called, as it is not sending the notification inside the `handle_menssage`/`add_host` function. 

Is not this test expected to handle the happy_path for the host creation?

2024-08-13 20:32 UTC, jpramos123 commented on tests/test_mq_service.py
> +    mock_notification_event_producer.write_event.assert_called_once()
Added in line 143 the event_type validation.

2024-08-13 21:06 UTC, kruai commented on tests/test_mq_service.py
> +    send_notification(mock_notification_event_producer, NotificationType.new_system_registered, host.data())
It is expected to handle the happy path; I just don't understand how the assertion is useful if the notification is sent manually within the test, and not within the code we're testing. Since the notification is no longer sent within `handle_message`, perhaps this notification should be validated in a different test (one that uses `event_loop()`, for instance)?

2024-08-13 21:24 UTC, kruai requested changes
A few more questions and concerns

2024-08-13 21:24 UTC, kruai commented on tests/test_mq_service.py
> +    )
I'm seeing this kind of change in a number of places. Why is it needed?
Can it be refactored, or does `minimal_host()` need to be updated or something?

2024-08-13 21:24 UTC, kruai commented on tests/test_notifications.py
> +    assert notification["org_id"] == SYSTEM_IDENTITY["org_id"]
These tests also don't assert that a notification was produced upon host creation, since the notification is sent within the test and not the code. It does validate the notification itself, though

2024-08-14 07:11 UTC, fstavela commented
/retest

2024-08-14 09:39 UTC, vkrizan commented on tests/test_notifications.py
> +# def test_add_host_fail(mocker):
Commented code. Either remove it or mark the test as xfail.

2024-08-14 09:50 UTC, vkrizan requested changes

2024-08-14 09:50 UTC, vkrizan commented on app/serialization.py
> +        if os.get("name") == "rhel":
Constant `"rhel"`

2024-08-14 09:50 UTC, vkrizan commented on app/serialization.py
> +            return f"{major:03}.{minor:03}"
Why is this formatted with 0 fill. It does not look good: `008.001`.

2024-08-14 09:50 UTC, vkrizan commented on app/queue/queue.py
> +                                send_notification(
Aesthetically this looks slanted. The two `if`s can be merged together. Or alternatively, you can prepare a list (or generator) that would get the necessary objects, and then do the loop.

2024-08-15 19:59 UTC, jpramos123 commented on app/queue/queue.py
> +                                send_notification(
Done!

2024-08-15 20:31 UTC, jpramos123 commented
/retest

2024-08-15 21:21 UTC, jpramos123 commented
/retest

2024-08-16 20:43 UTC, kruai reviewed
Looking good! It's really close. I just have a nitpick about the naming of a param.

_(I also think we should restructure the serialization function, but that shouldn't be done in this PR)_

2024-08-16 20:43 UTC, kruai commented on app/serialization.py
> +    for_create_host_notification=False,
Might be good to rename this to something more descriptive to its function, like `omit_null_facts` or something similar. Honestly we might wanna restructure this function in a follow-up to make it easier to maintain

2024-08-16 20:43 UTC, kruai commented on app/serialization.py
> +def serialize_canonical_facts(canonical_facts, for_create_host_notification=False):
Same here; probably want a clearer name for the `for_create_host_notification` param

2024-08-16 22:50 UTC, jpramos123 commented on app/serialization.py
> +    for_create_host_notification=False,
Done! Created [RHINENG-12028](https://issues.redhat.com/browse/RHINENG-12028) to address the refactoring/restructure

2024-08-19 12:29 UTC, kruai approved these changes

2024-08-19 13:31 UTC, thearifismail approved these changes
LGTM

2024-08-19 13:37 UTC, merged