feat(api): Invalidate cached systems in groups and staleness apis
RedHatInsights/insights-host-inventory pull request #1853
Opened 2024-07-25 20:34 UTC by chambridge

# Overview

* Define key deletion types and abstract them out
* Add cached system key deletion to group and staleness flows
* Define method for cached system key
* Add cache opportunity on cached system miss

You can reuse testing instructions from here: https://github.com/RedHatInsights/insights-host-inventory/pull/1841
However now if you alter staleness or groups in the org cached systems will be removed. 

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Include raw query examples in the PR description, if adding/modifying SQL query
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-07-25 21:31 UTC, kruai requested changes

2024-07-25 21:31 UTC, kruai commented on api/cache.py
> +    delete_keys(org_id)
What's the purpose of having a second function that does the same thing?

2024-07-25 21:31 UTC, kruai commented on api/group.py
> +    delete_cached_system_keys(current_identity.org)
```suggestion
    delete_cached_system_keys(current_identity.org_id)
```

2024-07-25 21:31 UTC, kruai commented on api/host_query.py
> +    return serialize_host(host, timestamps, False, additional_fields, staleness, system_profile_fields)
Would make more sense in `app.serialization` imo

2024-07-25 21:31 UTC, kruai commented on api/host.py
> +        output_host = serialize_host_with_params(host_list[0])
I'm noting that this will only ever return one host; that works for the insights-client scenario we know about, but I'm a bit concerned about potential issues. Like if they decide they want to determine whether multiple hosts are returned for that insights ID, or if some other service using system-identity sends a request to this endpoint

2024-07-25 21:56 UTC, chambridge commented on api/cache.py
> +    delete_keys(org_id)
originally thought it would add clarity but I've removed it.

2024-07-25 21:57 UTC, chambridge commented on api/group.py
> +    delete_cached_system_keys(current_identity.org)
thanks. change made. :bow:

2024-07-25 21:57 UTC, chambridge commented on api/host_query.py
> +    return serialize_host(host, timestamps, False, additional_fields, staleness, system_profile_fields)
moved.

2024-07-25 21:57 UTC, chambridge commented on api/host.py
> +        output_host = serialize_host_with_params(host_list[0])
added a check to only do this if there is a single host.

2024-07-25 22:26 UTC, kruai approved these changes

2024-07-26 13:11 UTC, thearifismail approved these changes

2024-07-26 13:16 UTC, thearifismail approved these changes

2024-07-26 13:48 UTC, merged