fix(RHINENG-11769) Fix Export Data Field names and add some new
RedHatInsights/insights-host-inventory pull request #1869
Opened 2024-08-07 15:37 UTC by strider

# Overview

This PR is being created to address [RHINENG-11769](https://issues.redhat.com/browse/RHINENG-11769).

This commit fixes the field names that we export.
- "id" becomes "host_uuid"
- "os_release" becomes "rhel_version"
- "updated" becomes "system_check_in"

The "host_type" field is set to "conventional" for non-edge hosts.

It also adds these fields:
- "hostname" sets from the "fqdn" field

Example:

```
{'display_name': 'b1280d.foo.redhat.com',
 'group_id': None,
 'group_name': None,
 'host_type': 'conventional',
 'host_uuid': '937c265c-53a3-40c5-9a83-cbc5bf913a27',
 'hostname': 'b1280d.foo.redhat.com',
 'rhel_version': 'Red Hat EL 7.0.1',
 'satellite_id': None,
 'state': 'fresh',
 'subscription_manager_id': None,
 'system_check_in': '2024-08-07T12:09:54.867575+00:00',
 'tags': [{'key': 'key3', 'namespace': 'NS1', 'value': 'val3'},
          {'key': 'key3', 'namespace': 'NS3', 'value': 'val3'},
          {'key': 'prod', 'namespace': 'Sat', 'value': None},
          {'key': 'key', 'namespace': 'SPECIAL', 'value': 'val'}]}
```

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Include raw query examples in the PR description, if adding/modifying SQL query
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-08-07 17:05 UTC, jpramos123 commented
/retest

2024-08-07 19:30 UTC, thearifismail reviewed
I am not going to block this PR but IMO, the requirements doc should be fixed to state `os_release` and `modified_on`, which is what in the code and better represent the state of host objects than using `os_version` and `ast_updated`

2024-08-08 07:28 UTC, strider commented on app/serialization.py
> +            serialized_host["host_type"] = "conventional"
This is only a formatting purpose and we do this only for the export service. The schema should not be changed. We just want to avoid the `None` value in the export archive.

2024-08-08 07:31 UTC, strider commented on app/serialization.py
> +    if "fqdn" in fields and for_export_svc:
I agree that a better management of this `fqdn` exported field should be done here. I am going to propose something else according to your recommandation.

PS: This is only for the export service and how we format the exported data for the customer.

2024-08-08 12:11 UTC, thearifismail submitted a review, later dismissed

2024-08-08 12:11 UTC, thearifismail commented on app/serialization.py
> +            serialized_host["host_type"] = "conventional"
Don't want to block this but is important in my opinion to be dealt with.  There was another instance where `host_type=None` made it awkward to deal with.  To address the issue, I just submitted [RHINENG-11889](https://issues.redhat.com/browse/RHINENG-11889)

2024-08-16 17:14 UTC, jpramos123 submitted a review, later dismissed

2024-08-16 17:45 UTC, jpramos123 commented
/retest

2024-08-19 20:49 UTC, kruai reviewed
This technically works, but these changes are complicating the serialization logic even further, especially now that export-service uses different names than our usual serialization. I'd really prefer if we could separate out the export-service-specific logic

2024-08-19 20:49 UTC, kruai commented on app/serialization.py
> +            serialized_host["os_version"] = serialized_host["os_release"]
Doing it this way will result in the serialized host having both "os_version" and "os_release" fields. Same goes for the rest of these fields, so I won't comment on all of them. Is the idea to put all of them (including duplicate fields) inside the serialized_host object, and then remove all the ones that aren't needed for the export service at the end?

2024-08-19 20:49 UTC, kruai commented on app/serialization.py
> +            serialized_host["last_updated"] = serialized_host["updated"]
Doing it this way will result in the serialized host having both "last_updated" and "updated" fields

2024-08-19 22:10 UTC, thearifismail reviewed
I have the same comment as @kruai.  `last_updated` should be replaced by `updated` or `modified_on`.  `os_release` is not needed.  Thanks to anybody can deliver to any project, the System Profile schema has quite a few overlapping fields which are responsible for this confusing situation.

2024-08-19 22:10 UTC, thearifismail commented on app/serialization.py
> +    "last_updated",
Couldn't `udpated` be used instead of creating a new attribute, `last_updated`?  Furthermore, even `updated` should be replaced by `modified_on`, which is what is used as the DB column title.

2024-08-19 22:10 UTC, thearifismail commented on app/serialization.py
> +            serialized_host["os_version"] = serialized_host["os_release"]
`os_version` should replace `os_release`.

2024-09-03 19:33 UTC, jpramos123 commented
@kruai @thearifismail I created a new host serializer specifically for the exp-svc feature

2024-09-03 19:34 UTC, jpramos123 commented on app/serialization.py
> +    "last_updated",
We want to use the fields specified in this card: https://issues.redhat.com/browse/RHINENG-11769

2024-09-03 19:34 UTC, jpramos123 commented on app/serialization.py
> +            serialized_host["os_version"] = serialized_host["os_release"]
@thearifismail We want to use the fields specified in this card: https://issues.redhat.com/browse/RHINENG-11769

2024-09-04 17:46 UTC, jpramos123 commented
/retest

2024-09-05 14:30 UTC, thearifismail commented on app/serialization.py
> +    "last_updated",
IMO, the fields specified in [RHINENG-11769](https://issues.redhat.com/browse/RHINENG-11769) should be changed to "updated".  I am sure @msager will not have any problem unless "updated" is being used already for some other reason and is still required.  My intent is to not add another variable that we could do without.

2024-09-05 14:30 UTC, thearifismail commented on app/serialization.py
> +    "last_updated",
IMO, the fields specified in [RHINENG-11769](https://issues.redhat.com/browse/RHINENG-11769) should be changed to "updated".  I am sure @msager will not have any problem unless "updated" is being used already for some other reason and is still required.  My intent is to not add another variable that we could do without.

2024-09-05 14:30 UTC, thearifismail commented on app/serialization.py
> +    "last_updated",
IMO, the fields specified in [RHINENG-11769](https://issues.redhat.com/browse/RHINENG-11769) should be changed to "updated".  I am sure @msager will not have any problem unless "updated" is being used already for some other reason and is still required.  My intent is to not add another variable that we could do without.

2024-09-05 14:30 UTC, thearifismail commented on app/serialization.py
> +    "last_updated",
IMO, the fields specified in [RHINENG-11769](https://issues.redhat.com/browse/RHINENG-11769) should be changed to "updated".  I am sure @msager will not have any problem unless "updated" is being used already for some other reason and is still required.  My intent is to not add another variable that we could do without.

2024-09-05 14:38 UTC, FabriciaDinizRH commented on app/serialization.py
> +            serialized_host["os_version"] = serialized_host["os_release"]
@jpramos123 the problem that Asa mentioned is still in the code, about having the two fields present at the end.

2024-09-05 14:47 UTC, jpramos123 commented on app/serialization.py
> +            serialized_host["os_version"] = serialized_host["os_release"]
@FabriciaDinizRH I don't see this anymore...
If we take a look at these lines: https://github.com/RedHatInsights/insights-host-inventory/pull/1869/files#diff-957087e16a2fa0e73c463f90ad900d1d451a760f3d0a4c4f1ac461e76ed6626cR304-R308

We are using the `os_release` that is in the `field` variable to create the `os_version` that is in the `serialized_host` dict. So there no duplication for this field

2024-09-05 14:53 UTC, thearifismail reviewed
please see my comments

2024-09-05 14:53 UTC, thearifismail commented on app/serialization.py
> +    "last_updated",
IMO, the fields specified in [RHINENG-11769](https://issues.redhat.com/browse/RHINENG-11769) should be changed to "updated".  I am sure @msager will not have any problem unless "updated" is being used already for some other reason and is still required.  My intent is to not add another variable that we could do without.

2024-09-05 14:53 UTC, thearifismail commented on app/serialization.py
> +def serialize_host_export_svc(
the function name does read right; it is a host that is being serialized NOT a service.  How about `serialize_host_to_export()`?

2024-09-05 18:47 UTC, kruai commented on app/serialization.py
> +def serialize_host_export_svc(
Or `serialize_host_for_export` / `serialize_host_for_export_svc`

2024-09-05 19:02 UTC, kruai requested changes

2024-09-05 19:02 UTC, kruai commented on app/serialization.py
> +    "last_updated",
I agree with Arif that we should use the existing field names whenever possible, assuming we have a choice here

2024-09-05 20:19 UTC, thearifismail commented
I am sorry. I thought you had made the changes.
- Arif

On Thu, Sep 5, 2024 at 4:13 PM Joao Paulo Ramos ***@***.***>
wrote:

> What changed? For some reason diff's don't load when I choose "Changes
> since my last review".
>
>    1. @jpramos123 <https://github.com/jpramos123> Are you going to
>    replace last_updated with updated?
>    2. Also renaming the function to serialize_host_for_export_svc?
>    3. Getting the count of hosts to export
>
> @thearifismail <https://github.com/thearifismail> Yes, I'm working on the
> changes for this PR!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/RedHatInsights/insights-host-inventory/pull/1869#issuecomment-2332551391>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJRWAAYXEC67R5HY45FHMY3ZVC3ONAVCNFSM6AAAAABMEVUFBWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMZSGU2TCMZZGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-09-06 14:04 UTC, kruai commented on app/serialization.py
> +    "hostname",
I opened some discussion on this [here](https://docs.google.com/document/d/1MyfSjPpbu-E0oYPPGRsV-S9Mor1FbMqcv-tlDGUCRFE/edit); I'd like if we can just keep using "fqdn" rather than "hostname"

2024-09-06 18:48 UTC, jpramos123 commented on app/serialization.py
> +    "hostname",
Changed `hostnane` to use the default `fqdn` field

2024-09-06 19:10 UTC, jpramos123 commented
/retest

2024-09-06 19:24 UTC, thearifismail commented on tests/helpers/export_service_utils.py
> +        "last_updated": "2024-07-23T16:24:41.167465+00:00",
this "last_updated" should be replaced by "updated".

2024-09-06 19:24 UTC, thearifismail commented on tests/helpers/export_service_utils.py
> +        "last_updated": "2024-07-23T16:24:41.159435+00:00",
this "last_updated" should be replaced by "updated".

2024-09-06 19:24 UTC, thearifismail commented on tests/helpers/export_service_utils.py
> +        "last_updated": "2024-07-23T16:24:40.562889+00:00",
this "last_updated" should be replaced by "updated".

2024-09-06 19:24 UTC, thearifismail commented on tests/helpers/export_service_utils.py
> +        "last_updated": "2024-07-23T16:24:41.167465+00:00",
this "last_updated" should be replaced by "updated".

2024-09-06 19:24 UTC, thearifismail commented on app/serialization.py
> +    if host.host_type == "edge" or (
Will this question be answered in this PR?

2024-09-06 19:29 UTC, kruai requested changes

2024-09-06 19:29 UTC, kruai commented on app/serialization.py
> +        )
This logic is unnecessary here. `serialized_host` has those timestamps on it when it gets returned from `serialize_host()`, so there's no need to duplicate the code

2024-09-06 19:29 UTC, kruai commented on app/serialization.py
> +    if "id" in fields:
`fields` is constant, so there's no need to check for "id", "groups", etc. You can remove all of those checks

2024-09-06 19:29 UTC, kruai commented on tests/helpers/export_service_utils.py
> +        "os_version": "Red Hat EL 7.0.1",
```suggestion
        "os_release": "Red Hat EL 7.0.1",
```

2024-09-06 19:29 UTC, kruai commented on tests/helpers/export_service_utils.py
> +        "last_updated": "2024-07-23T16:24:41.159435+00:00",
```suggestion
        "updated": "2024-07-23T16:24:41.159435+00:00",
```

2024-09-06 19:29 UTC, kruai commented on tests/helpers/export_service_utils.py
> +        "os_version": "Red Hat EL 7.0.1",
```suggestion
        "os_release": "Red Hat EL 7.0.1",
```

2024-09-06 19:29 UTC, kruai commented on tests/helpers/export_service_utils.py
> +        "last_updated": "2024-07-23T16:24:40.562889+00:00",
```suggestion
        "updated": "2024-07-23T16:24:40.562889+00:00",
```

2024-09-06 19:29 UTC, kruai commented on tests/helpers/export_service_utils.py
> +        "os_version": "Red Hat EL 7.0.1",
```suggestion
        "os_release": "Red Hat EL 7.0.1",
```

2024-09-06 19:29 UTC, kruai commented on tests/helpers/export_service_utils.py
> +        "last_updated": "2024-07-23T16:24:41.167465+00:00",
```suggestion
        "updated": "2024-07-23T16:24:41.167465+00:00",
```

2024-09-06 20:35 UTC, kruai approved these changes

2024-09-06 20:37 UTC, jpramos123 commented on app/serialization.py
> +    if host.host_type == "edge" or (
Removed that portion of the code that is not necessary here. 

Thanks

2024-09-06 20:40 UTC, thearifismail approved these changes

2024-09-09 12:17 UTC, merged