feat(performance): Use batched queries to improve DB call performance
RedHatInsights/insights-host-inventory pull request #1871
Opened 2024-08-07 22:51 UTC by jpramos123

# Overview

This PR is being created to address [RHINENG-11833](https://issues.redhat.com/browse/RHINENG-11833).
This PR aims to improve the DB call that is made by the export service.

Today if we have a big amount of hosts for in a account, and we make an export request, the pods are killed because of Out Of Memory (OOM) issue.

Using batched queries would reduce the chances of breaking the pods.

I'm proposing using `yield_per` from [SQLAlchemy](https://docs.sqlalchemy.org/en/20/core/connections.html#streaming-with-a-fixed-buffer-via-yield-per)  to address this change.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Include raw query examples in the PR description, if adding/modifying SQL query
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-08-08 08:50 UTC, vkrizan commented on api/host_query_db.py
> +            serialized_hosts_list.append(
This would still have the issue of reaching a memory limit. Each batch should be pushed out, clearing the memory for next batch.

2024-08-08 08:50 UTC, vkrizan commented on api/host_query_db.py
> +        for host in partition:
Although for-loops may be more readable, a (list) comprehension might be faster, especially on lager sets.

2024-08-08 08:54 UTC, strider reviewed
It works pretty well as is.

However, we may address my comment about the config object.

2024-08-08 08:54 UTC, strider commented on api/host_query_db.py
> +
João, there is no need to get this here as the `create_export` function gets the `inventory_config` by parameter. You may just need to pass the batch size value to the `get_hosts_to_export(...)` as parameter as well instead of instantiate all the Config object here.

My two cents.

2024-08-08 12:36 UTC, thearifismail commented on api/host_query_db.py
> +
I agree with @strider because the app has already been created and config available.

2024-08-08 12:45 UTC, thearifismail commented on api/host_query_db.py
> +            serialized_hosts_list.append(
@jpramos123 This is what I meant yesterday to process a chunk, manually set the object to None before iterating again.

2024-08-08 17:34 UTC, jpramos123 commented on api/host_query_db.py
> +            serialized_hosts_list.append(
I see! I need to validate with export-svc team, but I'm I doubt we can send chunks of data to be handled by the service now.

At the end, we need to send all the data that is being serialized at the same time via  POST request.

But... still there is a possibility to improve and implement this feature on export-service side.

Thanks!

2024-08-08 17:34 UTC, jpramos123 commented on api/host_query_db.py
> +        for host in partition:
Thanks, I will do this change!

2024-08-08 17:35 UTC, jpramos123 commented on api/host_query_db.py
> +
Thanks! I will address this ASAP

2024-08-08 18:03 UTC, thearifismail commented on api/host_query_db.py
> +            serialized_hosts_list.append(
@jpramos123 , it is a host-inventory pod that's crashing, right?  Unless a request for data export comes with an ID, which must go back with the response, there should be no problem with how many chunks host-inventory sends back.

2024-08-20 21:37 UTC, jpramos123 commented on api/host_query_db.py
> +            serialized_hosts_list.append(
@vkrizan I made a try, but looks like that the go server needs to handle the chunked requests on their side.
Still, can you evaluate my last draft commit changes? 

The export-service-go returns 410 with the message: `his resource has already been processed`

2024-08-21 09:47 UTC, vkrizan commented on api/host_query_db.py
> +            serialized_hosts_list.append(
@jpramos123 I'll check out out... Feel free to merge the database optimization first, and then we can do chunking next.

2024-08-21 09:50 UTC, vkrizan commented on api/host_query_db.py
> +            serialized_hosts_list.append(
Update the `get_hosts_to_export` to yield a chunk of hosts. It still prepares the full list!

2024-08-21 11:23 UTC, vkrizan commented on api/host_query_db.py
> +            serialized_hosts_list.append(
If chunks aren't supported, then it needs to be done using stream (as in file upload). https://requests.readthedocs.io/en/latest/user/advanced/#streaming-uploads It does not necessarily have to be a file, a file-like object would do (https://docs.python.org/3/library/io.html).

2024-08-21 22:34 UTC, jpramos123 commented
/retest

2024-08-22 12:06 UTC, jpramos123 commented
/retest

2024-09-04 13:01 UTC, vkrizan requested changes

2024-09-04 13:01 UTC, vkrizan commented on app/queue/export_service.py
> +            logger.debug("End of iterator")
@jpramos123 Why can't we use `for` (each) loop? This reimplements iterator pattern that is already part of the Python language.

2024-09-04 13:21 UTC, vkrizan commented on app/queue/export_service.py
> +                host_data.append(next(data_to_export))
We did serialized it one at the time before, so fundamentally this is the same.

> We decided to not to use the batch POST calls for now.

Can you elaborate on this one? 
If we don't want to do a batched POST call, then lets keep this PR clean from this serialization batching and only have the db query batch improvement.

2024-09-05 08:26 UTC, vkrizan approved these changes

2024-09-05 08:26 UTC, vkrizan commented on app/queue/export_service.py
> +            host_data.append(host)
This can be shortened by calling `list()` on the generator.

2024-09-05 14:22 UTC, kruai reviewed
Mostly looks good, I just wanna keep an accurate type hint (and also I agree with Viliam's suggestion)

2024-09-05 14:22 UTC, kruai commented on api/host_query_db.py
> +):
```suggestion
) -> Iterator[dict]:
```

Note that you'll need to add this to your imports:
`from typing import Iterator`

2024-09-05 14:30 UTC, jpramos123 commented on api/host_query_db.py
> +):
Added this suggestion!

2024-09-05 14:30 UTC, jpramos123 commented on app/queue/export_service.py
> +            host_data.append(host)
Done!

2024-09-05 14:32 UTC, vkrizan approved these changes

2024-09-05 14:41 UTC, vkrizan commented on api/host_query_db.py
> +    for host in db.session.scalars(export_host_query):
What would `.scalars()` do here? And, what's the difference between that and `.all()`?

2024-09-05 14:46 UTC, vkrizan requested changes
I'm unsure about the use of `.scalars()`. By the docs, it would return all rows on the first column. Which does seem wrong and would likely bring back the memory issue, if that's true. Can you please double check?

2024-09-05 15:25 UTC, vkrizan approved these changes

2024-09-05 16:17 UTC, thearifismail commented on app/queue/export_service.py
> +                export_format=exportFormat,
How many different export formats are possible?  It looks like `json` is the only option.  Can it work without even specifying format?

2024-09-05 17:28 UTC, kruai submitted a review, later dismissed

2024-09-05 19:15 UTC, jpramos123 commented on app/queue/export_service.py
> +                export_format=exportFormat,
2 types, CSV and JSON.

The default export is JSON

2024-09-05 19:33 UTC, jpramos123 commented on api/host_query_db.py
> +    for host in db.session.scalars(export_host_query):
Added this suggestion as a debug log

Thanks

2024-09-05 19:35 UTC, kruai approved these changes

2024-09-05 20:23 UTC, thearifismail approved these changes

2024-09-05 21:30 UTC, merged