fix(RHINENG-11980): Do not export culled hosts
RedHatInsights/insights-host-inventory pull request #1926
Opened 2024-09-13 17:52 UTC by jpramos123

# Overview

This PR is being created to address [RHINENG-11980](https://issues.redhat.com/browse/RHINENG-11980).

It fixes the behavior of exporting culled hosts when using the export-service.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Include raw query examples in the PR description, if adding/modifying SQL query
- [x] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-09-16 18:08 UTC, thearifismail commented on app/queue/export_service.py
> +    identity = create_mock_identity_with_org_id(org_id)
`create_mock_identity_with_org_id()` assumes `USER` as the `IdentityType`.  What happens when the provided `org_id` belongs to `IdentityType.SYSTEM`?

2024-09-16 18:10 UTC, thearifismail commented
running `podman-compose -f dev.yml up` appears to get stuck
```
$ pc -f dev.yml up
0fdb0af8b1787341167e96de929873698b089fb29c5b94ad7d9168c6d9c62e4f
Error: creating named volume "42688411761f3b0b6ad9565de6460e1d63ec823c957c69681467ac8d023159b0": allocating lock for new volume: allocation failed; exceeded num_locks (2048)
Error: creating named volume "2ea0e60c6498d7a0865415d25d81721a33ed60117e965f54872ae18b1160e201": allocating lock for new volume: allocation failed; exceeded num_locks (2048)
fb831c1d844b3cd989e8bbb17f8fe61813c14066a6e4e265810e5a428f1ca651
Error: "hbi-db" is not a valid container, cannot be used as a dependency: no container with name or ID "hbi-db" found: no such container
Error: "zookeeper" is not a valid container, cannot be used as a dependency: no container with name or ID "zookeeper" found: no such container
Error: "hbi-db" is not a valid container, cannot be used as a dependency: no container with name or ID "hbi-db" found: no such container
Error: allocating lock for new container: allocation failed; exceeded num_locks (2048)
[export-service]  | Error: no container with name or ID "export-service" found: no such container
[db]              | Error: no container with name or ID "hbi-db" found: no such container
[kafka]           | Error: no container with name or ID "kafka" found: no such container
[s3-createbucket] | Error: no container with name or ID "s3-createbucket" found: no such container
[zookeeper]       | Error: no container with name or ID "zookeeper" found: no such container
[unleash]         | Error: no container with name or ID "unleash" found: no such container
[minio]           | MinIO Object Storage Server
[minio]           | Copyright: 2015-2024 MinIO, Inc.
[minio]           | License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
[minio]           | Version: RELEASE.2024-08-03T04-33-23Z (go1.22.5 linux/amd64)
[minio]           | 
[minio]           | API: http://0.0.0.0:9099 
[minio]           | WebUI: http://0.0.0.0:9991 
[minio]           | 
[minio]           | Docs: https://min.io/docs/minio/linux/index.html
[minio]           | INFO: 
[minio]           |  You are running an older version of MinIO released 1 month before the latest release 
[minio]           |  Update: Run `mc admin update ALIAS` 
[minio]           | 
[minio]           | 
```

2024-09-16 18:12 UTC, thearifismail commented
Before the latest push to this branch, `podman-compose` could not launch only the Kafka container but this one has problems with many more

2024-09-16 20:05 UTC, jpramos123 commented
> running `podman-compose -f dev.yml up` appears to get stuck
> 
> ```
> $ pc -f dev.yml up
> 0fdb0af8b1787341167e96de929873698b089fb29c5b94ad7d9168c6d9c62e4f
> Error: creating named volume "42688411761f3b0b6ad9565de6460e1d63ec823c957c69681467ac8d023159b0": allocating lock for new volume: allocation failed; exceeded num_locks (2048)
> Error: creating named volume "2ea0e60c6498d7a0865415d25d81721a33ed60117e965f54872ae18b1160e201": allocating lock for new volume: allocation failed; exceeded num_locks (2048)
> fb831c1d844b3cd989e8bbb17f8fe61813c14066a6e4e265810e5a428f1ca651
> Error: "hbi-db" is not a valid container, cannot be used as a dependency: no container with name or ID "hbi-db" found: no such container
> Error: "zookeeper" is not a valid container, cannot be used as a dependency: no container with name or ID "zookeeper" found: no such container
> Error: "hbi-db" is not a valid container, cannot be used as a dependency: no container with name or ID "hbi-db" found: no such container
> Error: allocating lock for new container: allocation failed; exceeded num_locks (2048)
> [export-service]  | Error: no container with name or ID "export-service" found: no such container
> [db]              | Error: no container with name or ID "hbi-db" found: no such container
> [kafka]           | Error: no container with name or ID "kafka" found: no such container
> [s3-createbucket] | Error: no container with name or ID "s3-createbucket" found: no such container
> [zookeeper]       | Error: no container with name or ID "zookeeper" found: no such container
> [unleash]         | Error: no container with name or ID "unleash" found: no such container
> [minio]           | MinIO Object Storage Server
> [minio]           | Copyright: 2015-2024 MinIO, Inc.
> [minio]           | License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
> [minio]           | Version: RELEASE.2024-08-03T04-33-23Z (go1.22.5 linux/amd64)
> [minio]           | 
> [minio]           | API: http://0.0.0.0:9099 
> [minio]           | WebUI: http://0.0.0.0:9991 
> [minio]           | 
> [minio]           | Docs: https://min.io/docs/minio/linux/index.html
> [minio]           | INFO: 
> [minio]           |  You are running an older version of MinIO released 1 month before the latest release 
> [minio]           |  Update: Run `mc admin update ALIAS` 
> [minio]           | 
> [minio]           | 
> ```

This is working just fine on my side. But I'm using docker-compose.

2024-09-16 20:21 UTC, jpramos123 commented on app/queue/export_service.py
> +    identity = create_mock_identity_with_org_id(org_id)
Good question. When trying to use an different IDENTITY with the system type, I was not able to even pass through the export-service API.

@dehort do you have an example of using the Identity with the system type?

Thanks

2024-09-16 21:30 UTC, kruai requested changes

2024-09-16 21:30 UTC, kruai commented on api/filtering/db_filters.py
> +        staleness_obj = serialize_staleness_to_dict(get_staleness_obj())
`get_staleness_obj()` already has handling for `identity=None`, and that's its default value, so:
```suggestion
    staleness_obj = serialize_staleness_to_dict(get_staleness_obj(identity))
```

2024-09-16 21:30 UTC, kruai commented on api/filtering/db_filters.py
> +            filters += _staleness_filter(staleness, host_type_filter, identity)
Both paths do the same thing
```suggestion
        filters += _staleness_filter(staleness, host_type_filter, identity)
```

2024-09-16 21:30 UTC, kruai commented on api/host_query_db.py
> +    staleness_states = ["fresh", "stale", "stale_warning"]
These are already defined by `ALL_STALENESS_STATES` in host_repository.py; we could use that instead of re-defining them

2024-09-16 21:30 UTC, kruai commented on api/filtering/db_filters.py
> +    identity=None,
I don't love the idea of adding `identity` to this function, but... it seems it's needed for `get_staleness_obj()`, right?

2024-09-17 13:25 UTC, jpramos123 commented on api/host_query_db.py
> +    staleness_states = ["fresh", "stale", "stale_warning"]
Thanks, updated!

2024-09-17 13:26 UTC, jpramos123 commented on api/filtering/db_filters.py
> +    identity=None,
Correct, that was needed or it was going to break when the `identity` was equal to `None`.

2024-09-17 14:01 UTC, kruai commented on api/filtering/db_filters.py
> +    identity=None,
OK. Would probably be best if we then made `identity` required, and removed calls to `get_current_identity` within the flow, but that should be a separate PR; I'll play around with it after this goes in

2024-09-17 14:02 UTC, dehort commented on app/queue/export_service.py
> +    identity = create_mock_identity_with_org_id(org_id)
@jpramos123 I believe the SYSTEM identity type is generated when the user/system authenticates with a cert?  So I believe what you are seeing is related to this https://issues.redhat.com/browse/RHCLOUD-34799

2024-09-17 14:05 UTC, kruai approved these changes

2024-09-17 14:20 UTC, jpramos123 commented on app/queue/export_service.py
> +    identity = create_mock_identity_with_org_id(org_id)
@dehort Thanks! That is correct!

@thearifismail Can we move on as this is an open issue on export-service side?

Thanks

2024-09-17 15:37 UTC, jpramos123 commented
/retest

2024-09-19 11:27 UTC, fstavela commented
/retest

2024-09-19 14:00 UTC, jpramos123 commented
/retest

2024-09-19 15:12 UTC, jpramos123 commented
/retest

2024-09-19 16:11 UTC, kruai requested changes

2024-09-19 16:11 UTC, kruai commented on tests/test_export_service.py
> +        time.sleep(1)
We do need to avoid using this whenever possible, since each one adds a second to the runtime of the unit test suite. I know you left a comment above this, though, and I suppose we can address it with [RHINENG-3408](https://issues.redhat.com/browse/RHINENG-3408)...

2024-09-19 16:11 UTC, kruai commented on tests/test_export_service.py
> +def test_export_one_host(mock_post, flask_app, db_create_host, db_create_staleness_culling, mocker):
It doesn't look like `@mock.patch`, `mock_post`, or `mocker` are used in this test

2024-09-19 16:11 UTC, kruai commented on tests/test_export_service.py
> +def test_do_not_export_culled_hosts(mock_post, flask_app, db_create_host, db_create_staleness_culling, mocker):
It doesn't look like `@mock.patch`, `mock_post`, or `mocker` are used in this test

2024-09-19 16:48 UTC, jpramos123 commented on app/queue/export_service.py
> +    return host_data
I would like to keep it like this as the `get_hosts_to_exports` is serializing the hosts using `yield`, at least we optimize that portion of the code using the generator.
Does it make sense?

2024-09-19 19:01 UTC, kruai commented on app/queue/export_service.py
>          REQUEST_ID_HEADER: str(exportUUID),
Just noting that the `exportUUID` type hint says that it's already a str. If it's actually a UUID, the type hint should be updated; if it's a str, then the cast is not necessary

2024-09-19 19:18 UTC, kruai commented on app/queue/export_service.py
> +    return host_data
I don't think I quite understand... `get_hosts_to_exports` is returning a generator, which is great. The part that confuses me is that it's always immediately converted into a list, which loads the whole dataset into memory anyway. It feels like the original intent was to feed the generator into a chunk-encoded POST request.
Anyway, I suppose this isn't strictly related to exporting culled hosts, so it can be a follow-up or something like that. Seems closer to [RHINENG-11833](https://issues.redhat.com/browse/RHINENG-11833).

2024-09-19 19:20 UTC, kruai commented on app/queue/export_service.py
> +def get_host_list(identity: Identity, exportFormat: str, rbac_filter: dict, inventory_config: Config):
```suggestion
def get_host_list(identity: Identity, exportFormat: str, rbac_filter: dict, inventory_config: Config) -> List[dict]:
```

2024-09-19 19:21 UTC, kruai commented on app/queue/export_service.py
> +):
```suggestion
) -> bool:
```

2024-09-19 19:22 UTC, kruai commented on app/queue/export_service.py
> +def _format_export_data(data: dict, exportFormat: str):
```suggestion
def _format_export_data(data: dict, exportFormat: str) -> str:
```

2024-09-19 21:59 UTC, thearifismail commented on Makefile
> +IDENTITY_HEADER="eyJpZGVudGl0eSI6IHsiYWNjb3VudF9udW1iZXIiOiAiYWNjb3VudDEyMyIsICJvcmdfaWQiOiAiNTg5NDMwMCIsICJ0eXBlIjogIlVzZXIiLCAiYXV0aF90eXBlIjogImJhc2ljLWF1dGgiLCAidXNlciI6IHsiaXNfb3JnX2FkbWluIjogdH
what is the reason for adding `"auth_type": "basic-auth "` to Identity?  Why not  any of the following:
```
    BASIC = "basic-auth"
    CERT = "cert-auth"
    JWT = "jwt-auth"
    UHC = "uhc-auth"
    SAML = "saml-auth"
    X509 = "X509"
```

2024-09-19 21:59 UTC, thearifismail commented on app/queue/export_service.py
> +def extract_export_svc_data(export_svc_data: dict):
@kruai suggestion had 4 members in the Tuple. I added one more because because this function returns 5 attributes.

2024-09-19 21:59 UTC, thearifismail commented on app/queue/export_service.py
> +    }
yes `rbac_request_headers` defined twice.

2024-09-19 21:59 UTC, thearifismail commented on app/queue/export_service.py
> +def create_export(
`create_export()` has 4 return statements sprinkled throughout the function.  This is confusing.  It is preferred to have only one `return` statement. So please provide a variable and set its value to True or False replacing the return statements, and return the value at the end.

2024-09-19 21:59 UTC, thearifismail commented on tests/helpers/export_service_utils.py
> +                        "eyJpZGVudGl0eSI6IHsib3JnX2lkIjogInRlc3QiL"
linter gone mad... Is it confusing or I am the only one find it confusing?

2024-09-20 12:56 UTC, jpramos123 commented on Makefile
> +IDENTITY_HEADER="eyJpZGVudGl0eSI6IHsiYWNjb3VudF9udW1iZXIiOiAiYWNjb3VudDEyMyIsICJvcmdfaWQiOiAiNTg5NDMwMCIsICJ0eXBlIjogIlVzZXIiLCAiYXV0aF90eXBlIjogImJhc2ljLWF1dGgiLCAidXNlciI6IHsiaXNfb3JnX2FkbWluIjogdH
I'm using `basic-auth` which is the first in the list you sent

2024-09-20 12:59 UTC, jpramos123 commented on app/queue/export_service.py
> +    return host_data
Agreed.

Would be ideal to address this specifically there, I will start a follow up PR so we can discuss this optimization there.

Thanks

2024-09-20 13:10 UTC, jpramos123 commented on tests/helpers/export_service_utils.py
> +                        "eyJpZGVudGl0eSI6IHsib3JnX2lkIjogInRlc3QiL"
Tried to make it prettier.

2024-09-20 13:15 UTC, jpramos123 commented on app/queue/export_service.py
> +def create_export(
I don't like this idea, because, depending where we are in the code, thing are going to be processed unnecessarily.

Take this example:

```
    export_service_endpoint = inventory_config.export_service_endpoint

    if not allowed:
        session = Session()
        request_url = _build_export_request_url(
            export_service_endpoint, exportUUID, applicationName, resourceUUID, "error"
        )
        _handle_export_error(
            "You don't have the permission to access the requested resource.",
            "403",
            request_url,
            session,
            request_headers,
            exportUUID,
            exportFormat,
        )
        return False

    session = Session()
```

I don't want the code to continue to process without necessity. So the `return` statements are based on the code behavior.

Thanks

2024-09-20 16:21 UTC, thearifismail commented on app/queue/export_service.py
> +def create_export(
if `if not allowed: ` has a corresponding `else` block with `try except` in it, then there should be no unnecessary execution.

2024-09-20 18:12 UTC, jpramos123 commented on app/queue/export_service.py
> +def create_export(
Done, added the else statement and the variable. Good idea for debugging the code in future...

2024-09-20 20:49 UTC, thearifismail commented on app/queue/export_service.py
> +def create_export(
with the new latest implementation, `if not allowed` block is executed the function returns without closing the sesssion.  Here is what I think should be done.

1. initialize session in once before checking if allowed or not.
2. Using finally for closing the session is good but it requires `try{}` block.
3. first start `try` block, then `if allowed` and performa the work.  Current `if not allowed` should be done in `else` block inside the `try` block.  Then handle exception and finally `finally` to wrap up

2024-09-20 21:29 UTC, jpramos123 commented on app/queue/export_service.py
> +def create_export(
1. Thanks, good catch! Added the `session.close()`
2. It was a matter of adding `session.close()`  to the `if not allowed`
3. The way it is now is cleaner for reading, as it just validate the `if not` statement, otherwise continues the flow.

Thanks

2024-09-20 21:35 UTC, thearifismail submitted a review, later dismissed

2024-09-23 14:59 UTC, kruai reviewed
Looks good, just got a tiny suggestion for the tests

2024-09-23 14:59 UTC, kruai commented on tests/test_export_service.py
> +        inventory_config = flask_app.app.config.get("INVENTORY_CONFIG")
We have an `inventory_config` fixture that automatically handles this

2024-09-23 14:59 UTC, kruai commented on tests/test_export_service.py
> +        inventory_config = flask_app.app.config.get("INVENTORY_CONFIG")
Same as above - you should be able to use the `inventory_config` fixture

2024-09-23 15:18 UTC, kruai approved these changes

2024-09-23 15:56 UTC, merged