fix(RHINENG-11863): User without host read permission is able to export hosts
RedHatInsights/insights-host-inventory pull request #1929
Opened 2024-09-16 19:57 UTC by jpramos123

# Overview

This PR is being created to address [RHINENG-11863](https://issues.redhat.com/browse/RHINENG-11863).

This fixes the issue that was allowing user without host-read to export hosts from inventory. Now it raises an exception when the user does not have the correct permission and fails the export request. 

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Include raw query examples in the PR description, if adding/modifying SQL query
- [x] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-09-16 20:57 UTC, kruai requested changes

2024-09-16 20:57 UTC, kruai commented on app/queue/export_service.py
> +            abort(HTTPStatus.FORBIDDEN)
`create_export()` is MQ, not API. Doesn't make sense to return HTTP 403 to a kafka consumer

2024-09-16 20:57 UTC, kruai commented on app/queue/export_service.py
> +            e, 500, export_service_endpoint, exportUUID, applicationName, resourceUUID, session, request_headers
A few notes/questions for this line:
- Why the hardcoded 500 for the status code?
- It would be cleaner to just pass in the `request_url` instead of all of its pieces separately.
- It seems a bit odd to return `_handle_export_error()` when it's always gonna be False. Honestly instead of returning a boolean, I think it would make more sense for `create_export` to just raise an exception if it fails

2024-09-17 09:46 UTC, vkrizan commented on app/queue/export_service.py
> +    return False
Minor: This return value is suppose to be an outcome of the parent, hence it shouldn't be part of this handle function (this one should be kept without return value).

2024-09-17 09:46 UTC, vkrizan commented on app/queue/export_service.py
> +        if allowed:
The allowed should be checked prior to getting into the `try-except` block of the export, and before generating a session to the export endpoint service: right after `rbac_request_headers`.

2024-09-17 13:43 UTC, jpramos123 commented on app/queue/export_service.py
> +            abort(HTTPStatus.FORBIDDEN)
My idea was to use it to raise the exception and use the status code/message that is sent to the export-service API via POST request. I can make it by hand as well.

Do you think would be clear/correct this way?

Thanks

2024-09-17 13:46 UTC, jpramos123 commented on app/queue/export_service.py
> +    return False
Thanks I will try to figure out something better.

2024-09-17 15:54 UTC, jpramos123 commented on app/queue/export_service.py
> +            abort(HTTPStatus.FORBIDDEN)
Built it by hand!

Let me know if it fits

2024-09-18 09:13 UTC, vkrizan commented on app/queue/export_service.py
> +    except Exception as e:
This is not very ideal, as this catches (almost) everything and claims it to be a `403 Forbidden` (as per `status_code` passed to the handler). Move the check of `allowed` outside of the `try-except`, and handle other errors with differently. If an error can be handled still within the same function, then it does not make sense to throw it and then catch it later on (at least not how it is done in this case).

2024-09-18 12:57 UTC, vkrizan commented on app/queue/export_service.py
> +    host_data = list(
Consider keeping this under the try-except block, in case the db fetch or serialization fail it would be reported back.

2024-09-18 13:20 UTC, jpramos123 commented on app/queue/export_service.py
> +    host_data = list(
Done!

2024-09-18 13:30 UTC, vkrizan approved these changes
Thank you!

2024-09-18 13:51 UTC, kruai requested changes
A few small suggestions. I also think `create_export()` could be DRY'd a bit more... I'm gonna take a stab at it to make sure I'm not off base, though, and I don't wanna block on it

2024-09-18 13:51 UTC, kruai commented on app/queue/export_service.py
> +    session.post(url=request_url, headers=request_headers, data=json.dumps({"message": str(e), "error": status_code}))
This POST's response isn't considered; seems like it should be evaluated using `_handle_export_response`

2024-09-18 13:51 UTC, kruai commented on app/queue/export_service.py
> +    export_service_endpoint, exportUUID, applicationName, resourceUUID, request_type: str
this could use some more type hints

2024-09-18 13:51 UTC, kruai commented on app/queue/export_service.py
> +def _handle_export_error(e, status_code, request_url, session, request_headers):
this could use type hints

2024-09-18 17:56 UTC, jpramos123 commented on app/queue/export_service.py
> +    session.post(url=request_url, headers=request_headers, data=json.dumps({"message": str(e), "error": status_code}))
Done

2024-09-18 17:56 UTC, jpramos123 commented on app/queue/export_service.py
> +    export_service_endpoint, exportUUID, applicationName, resourceUUID, request_type: str
Done

2024-09-18 17:56 UTC, jpramos123 commented on app/queue/export_service.py
> +def _handle_export_error(e, status_code, request_url, session, request_headers):
Done

2024-09-18 22:25 UTC, kruai approved these changes

2024-09-19 11:27 UTC, fstavela commented
/retest

2024-09-19 13:24 UTC, merged