fix(RHINENG-12212): fix host_url in notification
RedHatInsights/insights-host-inventory pull request #1962
Opened 2024-09-27 11:32 UTC by FabriciaDinizRH

# Overview

This PR is being created to address [RHINENG-12212](https://issues.redhat.com/browse/RHINENG-12212).

- sets host_url for prod envs

I created a bug for urls for stage/ephemeral envs. 

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Include raw query examples in the PR description, if adding/modifying SQL query
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-09-27 13:15 UTC, jpramos123 requested changes
Please, review the approach in this PR. I don't feel comfortable introducing a bug that we can already solve in this PR.

Thanks

2024-09-27 13:37 UTC, FabriciaDinizRH commented on app/queue/notifications.py
> +PROD_URL = "https://console.redhat.com/insights/inventory/"
@jpramos123 this is going to fix the existing behavior for the customers. After that is fixed for them I can take a bit more time to figure out about the env variable and setting it everywhere it is needed

2024-09-27 13:39 UTC, thearifismail commented on app/queue/notifications.py
> +PROD_URL = "https://console.redhat.com/insights/inventory/"
I aggree with @jpramos123.  Furhermore, target environment URL called `PROD_URL` does not look right.  Type of environment and its URL should be provided using environment variables

2024-09-27 14:06 UTC, FabriciaDinizRH commented on app/queue/notifications.py
> +PROD_URL = "https://console.redhat.com/insights/inventory/"
Ok, so I'll wait for advisor's response

2024-09-30 14:37 UTC, FabriciaDinizRH commented
/retest

2024-09-30 14:40 UTC, FabriciaDinizRH commented on app/queue/notifications.py
> +PROD_URL = "https://console.redhat.com/insights/inventory/"
@kruai should I change the config variable name in this PR to `PLATFORM_HOSTNAME`?

2024-10-01 09:52 UTC, FabriciaDinizRH commented
/retest

2024-10-02 15:13 UTC, jpramos123 requested changes
Looks good, but I have a suggestion.

Thanks for the PR

2024-10-02 15:13 UTC, jpramos123 commented on app/config.py
> +        self.consoledot_hostname = os.getenv("CONSOLEDOT_HOSTNAME", "https://console.redhat.com")
I would rather set the default value to the one that is used `locally` or in `ephemeral`.
It should be `localhost`.

We can set the environment variable in stage and prod files in gitlab!

2024-10-02 15:13 UTC, jpramos123 commented on app/config.py
> +        self.consoledot_hostname = os.getenv("CONSOLEDOT_HOSTNAME", "https://console.redhat.com")
I would rather set the default value to the one that is used locally or in ephemeral.
It should be localhost.

We can set the environment variable in stage and prod files in gitlab!

2024-10-02 15:13 UTC, jpramos123 commented on deploy/clowdapp.yml
> +  value: 'https://console.redhat.com'
I would rather set the default value to the one that is used locally or in ephemeral.
It should be localhost.

We can set the environment variable in stage and prod files in gitlab!

2024-10-02 15:27 UTC, FabriciaDinizRH commented on app/config.py
> +        self.consoledot_hostname = os.getenv("CONSOLEDOT_HOSTNAME", "https://console.redhat.com")
done

2024-10-02 15:27 UTC, FabriciaDinizRH commented on app/config.py
> +        self.consoledot_hostname = os.getenv("CONSOLEDOT_HOSTNAME", "https://console.redhat.com")
done

2024-10-02 15:27 UTC, FabriciaDinizRH commented on deploy/clowdapp.yml
> +  value: 'https://console.redhat.com'
done

2024-10-02 15:30 UTC, jpramos123 requested changes
Small change in the READM.md file

2024-10-02 15:30 UTC, jpramos123 commented on README.md
> +# For testing notifications in stage/ephemeral, set this to the appropriate url
```suggestion
# Set the appropriate URL value  to be used in stage/prod environments. Default value is:
```

2024-10-02 15:34 UTC, kruai requested changes

2024-10-02 15:34 UTC, kruai commented on README.md
> +# For testing notifications in stage/ephemeral, set this to the appropriate url
These instructions are for local setup; do we care about the hostname used for notifications produced locally? If we do, then my guess is that the hostname should be set to `localhost` or `0.0.0.0:8080`, since that's what we've configured for the local env.
(Note that the value for Stage is automatically configured, so no need to specify that here).

2024-10-02 15:34 UTC, kruai commented on README.md
> +# CONSOLEDOT_HOSTNAME="https://console.redhat.com"
If we do want developers to configure this field for their local setup, then this should be uncommented and probably put at the end of the list of env vars. Also, the protocol (`https://`) should be left off

2024-10-02 15:34 UTC, kruai commented on deploy/clowdapp.yml
> +  value: 'https://console.redhat.com'
It only contains the hostname, not the protocol
```suggestion
  value: 'console.redhat.com'
```

2024-10-02 15:34 UTC, kruai commented on app/config.py
> +
I see this line in both `clowder_config()` and `non_clowder_config()`. We set this the same way regardless of whether we're using clowder, so this value should be set within `__init__()`.

Also, you can remove `get_base_url()` and just set it here to simplify a bit:
```
self.consoledot_hostname = os.getenv("CONSOLEDOT_HOSTNAME", "localhost")
self.base_ui_url = f"https://{self.consoledot_hostname}/insights/inventory"
```

2024-10-02 15:34 UTC, kruai commented on app/config.py
> +
Should be removed (see above)

2024-10-02 17:37 UTC, FabriciaDinizRH commented on README.md
> +# For testing notifications in stage/ephemeral, set this to the appropriate url
I see. I still struggle with things that go "under the hood". I wanted to let everything written out but I agree it can be left out here

2024-10-02 17:44 UTC, FabriciaDinizRH commented on README.md
> +# For testing notifications in stage/ephemeral, set this to the appropriate url
I'll take Asa's suggestion and remove this bit to make things simpler

2024-10-02 18:04 UTC, kruai submitted a review, later dismissed

2024-10-02 19:08 UTC, jpramos123 requested changes
Last review

2024-10-02 19:08 UTC, jpramos123 commented on deploy/clowdapp.yml
> +  value: 'console.redhat.com'
Shouldn't me localhost as well here? 
This must be overwritten in stage/prod deployment files

```suggestion
  value: 'localhost'
```

2024-10-02 19:09 UTC, kruai commented on deploy/clowdapp.yml
> +  value: 'console.redhat.com'
Oh, for some reason I thought it was already "localhost". Yes I agree that it should be

2024-10-02 21:40 UTC, thearifismail submitted a review, later dismissed

2024-10-03 12:52 UTC, kruai approved these changes

2024-10-03 13:07 UTC, jpramos123 approved these changes

2024-10-03 13:09 UTC, merged