fix(RHINENG-12212): add CONSOLE_HOSTNAME to the correct deploy sections
RedHatInsights/insights-host-inventory pull request #1994
Opened 2024-10-09 15:54 UTC by FabriciaDinizRH

# Overview

This PR is being created to address [RHINENG-12212](https://issues.redhat.com/browse/RHINENG-12212).

- add CONSOLE_HOSTNAME to mq sections

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Include raw query examples in the PR description, if adding/modifying SQL query
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-10-09 19:12 UTC, jpramos123 commented on deploy/clowdapp.yml
> +  value: console.stage.redhat.com
I will keep it as `localhost` and change the variable name in stage deployment file...

@kruai thoughts?

2024-10-10 12:38 UTC, kruai commented on deploy/clowdapp.yml
> +  value: console.stage.redhat.com
I would keep it as `localhost` as well; then if we see `localhost` being used in one of those payloads, we'll know that the env config is wrong

2024-10-10 13:13 UTC, jpramos123 requested changes
Just one suggestion

Thanks

2024-10-10 13:13 UTC, jpramos123 commented on deploy/clowdapp.yml
> +  value: console.stage.redhat.com
```suggestion
  value: localhost
```

2024-10-11 14:10 UTC, thearifismail approved these changes

2024-10-11 16:20 UTC, kruai approved these changes
LGTM!

2024-10-12 00:50 UTC, jpramos123 approved these changes

2024-10-14 09:57 UTC, merged