RHINENG-13638: use env var for number of kafka partitions
RedHatInsights/insights-host-inventory pull request #2059
Opened 2024-11-07 23:07 UTC by thearifismail

rh-pre-commit.version: 2.2.0
rh-pre-commit.check-secrets: ENABLED

# Overview

This PR is being created to address [RHINENG-13638](https://issues.redhat.com/browse/RHINENG-13638).
Description from the JIRA card:
Inventory has a fixed number (1) of Kafka partitions for all topics it uses: https://github.com/RedHatInsights/insights-host-inventory/blob/160fc2b2f2d9fdcaefc9ca39e5f8cb311f418064/deploy/clowdapp.yml#L1100-L1114

We should make this adjustable by env var. The reason is that when I want to test Inventory with multiple pods in ephemeral (for example to reproduce the race condition issues) I can set the number of pods, but since only one consumer can be connected to one partition, only one pod is doing all of the work and others are sitting idle when we have only 1 partition.

Note: Some of the topics have more partitions in ephemeral even if we set the number to 1 (for example mq-p1). The reason for this is that the clowder fetches the partitions config of all services using the topic and sets the number of partitions to the highest requested number. We can document this somewhere.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Include raw query examples in the PR description, if adding/modifying SQL query
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-11-19 14:57 UTC, fstavela reviewed
I left a few comments, otherwise looks good. Maybe we could omit the `NUMBER_OF` at the beginning of the var names, but I'm OK with the current names as well.

2024-11-19 14:57 UTC, fstavela commented on deploy/clowdapp.yml
> +        partitions: $NUMBER_OF_{KAFKA_HOST_INGRESS_P1_TOPIC_PARTITIONS}
This should probably be `${NUMBER_OF_KAFKA_HOST_INGRESS_P1_TOPIC_PARTITIONS}`. I guess this is also the reason why the pipeline is failing.

2024-11-19 14:57 UTC, fstavela commented on deploy/clowdapp.yml
> +  description: The number of partitions for payload trcer topcs.
Typo: "payload tracker topics"

2024-11-19 14:57 UTC, fstavela commented on deploy/clowdapp.yml
> +- name: NUMBER_OF_KAFKA_HOST_INGRESS_TOPIC_PARTITIONS
This and the next 3 new values are missing a description

2024-11-26 16:01 UTC, kruai requested changes

2024-11-26 16:01 UTC, kruai commented on deploy/clowdapp.yml
> +          value: ${NUMBER_OF_KAFKA_EVENT_TOPIC_PARTITIONS}
I don't want to post this for every single instance of this, but why do we need to know the number of partitions for a topic within the app itself?

2024-11-27 15:07 UTC, chambridge commented
Should we add any information that this should only be used for ephemeral otherwise it needs to by synched with changes to the https://github.com/RedHatInsights/platform-mq/tree/master repo.

For example `platform.notifications.ingress` configuration is specified here:
https://github.com/RedHatInsights/platform-mq/blob/master/topics/topics.json#L108-L110

2024-11-27 17:03 UTC, kruai approved these changes

2024-11-28 08:51 UTC, fstavela reviewed
The PR checks are failing because `oc` isn't able to process the template, here is the error:
```
17:13:38 2024-11-27 16:13:38 [    INFO] [          MainThread] deploy failed: 'oc process' command failed: error: failed to read input object (not a Template?): unable to decode "STDIN": json: cannot unmarshal number into Go struct field Parameter.parameters.value of type string
17:13:38 ERROR: deploy failed: 'oc process' command failed: error: failed to read input object (not a Template?): unable to decode "STDIN": json: cannot unmarshal number into Go struct field Parameter.parameters.value of type string
```
I guess the numbers of partitions have to be strings? Like `'1'`

2024-11-28 08:51 UTC, fstavela commented on deploy/clowdapp.yml
> +        partitions:  ${NUMBER_OF_KAFKA_HOST_INGRESS_TOPIC_PARTITIONS}
Just a nitpick, but there is one additional leading space here that can be removed

2024-12-02 14:27 UTC, thearifismail commented
Add comment `https://github.com/RedHatInsights/insights-host-inventory/pull/2059#issuecomment-2504113018` in resonse to @chambridge [comment](https://github.com/RedHatInsights/insights-host-inventory/pull/2059#issuecomment-2504113018)

2024-12-02 15:01 UTC, thearifismail commented
> The PR checks are failing because `oc` isn't able to process the template, here is the error:
> 
> ```
> 17:13:38 2024-11-27 16:13:38 [    INFO] [          MainThread] deploy failed: 'oc process' command failed: error: failed to read input object (not a Template?): unable to decode "STDIN": json: cannot unmarshal number into Go struct field Parameter.parameters.value of type string
> 17:13:38 ERROR: deploy failed: 'oc process' command failed: error: failed to read input object (not a Template?): unable to decode "STDIN": json: cannot unmarshal number into Go struct field Parameter.parameters.value of type string
> ```
> 
> I guess the numbers of partitions have to be strings? Like `'1'`
Switching back to integer type for the values of number of partitions because of the following error in build log.
```
14:33:47 The ClowdApp "host-inventory" is invalid: 
14:33:47 
14:33:47 * spec.kafkaTopics[0].partitions: Invalid value: "string": spec.kafkaTopics[0].partitions in body must be of type integer: "string"
14:33:47 
14:33:47 * spec.kafkaTopics[1].partitions: Invalid value: "string": spec.kafkaTopics[1].partitions in body must be of type integer: "string"
14:33:47 
14:33:47 * spec.kafkaTopics[2].partitions: Invalid valu... (618 more, please see e.stderr)
```

2024-12-04 21:22 UTC, bsquizz commented on deploy/clowdapp.yml
> +        partitions: ${NUMBER_OF_KAFKA_NOTIFICATION_TOPIC_PARTITIONS}
You need to use a double bracket here to pass in the integer value instead of a string value. For example: `${{NUMBER_OF_KAFKA_NOTIFICATION_TOPIC_PARTITIONS}}`

2024-12-06 16:10 UTC, kruai requested changes

2024-12-06 16:10 UTC, kruai commented on deploy/clowdapp.yml
> +apiVersion: template.openshift.io/v1
What's the purpose of this change?

2024-12-06 16:10 UTC, kruai commented on deploy/clowdapp.yml
> +          value: ${NUMBER_OF_KAFKA_EVENT_TOPIC_PARTITIONS}
This still has not been addressed @thearifismail. These deployments don't need the "number of partitions" environment variables

2024-12-06 16:10 UTC, kruai commented on deploy/clowdapp.yml
> +  description: Number of partitions for the payload tracker topics.
```suggestion
  description: Number of partitions for the payload tracker topic
```

2024-12-06 16:10 UTC, kruai commented on deploy/clowdapp.yml
> +  description: Number of partitions for the export-service topic.
```suggestion
  description: Number of partitions for the export-service topic
```

2024-12-06 16:40 UTC, kruai requested changes

2024-12-06 16:40 UTC, kruai commented on deploy/clowdapp.yml
> +
```suggestion
```

2024-12-06 16:40 UTC, kruai commented on deploy/clowdapp.yml
> +
```suggestion
```

2024-12-06 16:40 UTC, kruai commented on deploy/clowdapp.yml
> +  value: test
```suggestion
```

2024-12-06 16:40 UTC, kruai commented on deploy/clowdapp.yml
> +apiVersion: template.openshift.io/v1
Still wanna know if this change is related @thearifismail

2024-12-09 13:53 UTC, kruai approved these changes

2024-12-09 14:12 UTC, merged