feat(RHINENG-13314): Log specific SP fields defined in env config
RedHatInsights/insights-host-inventory pull request #2097
Opened 2024-11-27 18:12 UTC by jpramos123

# Overview

This PR is being created to address [RHINENG-13314](https://issues.redhat.com/browse/RHINENG-13314).
It implements the new env var called `SP_FIELDS_TO_LOG`, that is used to print the specified system profile fields in our logs. The logs were added to: add host, update host and delete host methods.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Include raw query examples in the PR description, if adding/modifying SQL query
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-12-03 21:06 UTC, jpramos123 commented
/retest

2024-12-05 17:13 UTC, jpramos123 commented
/retest

2024-12-05 21:10 UTC, thearifismail reviewed
Generally speaking the logging system profile fields should be a part of over log configuration.  This implementation suggests that system profile fields are accessory to host data and not a part of it, which is not true.

Another question is how are nested fields being logged? e.g. `systemd` or `operating_system`?

2024-12-05 21:10 UTC, thearifismail commented on app/instrumentation.py
> +        system_profile_fields,
Shouldn't system_profile fields comprise a subsection of the input_host?

2024-12-05 21:10 UTC, thearifismail commented on app/instrumentation.py
> +        f"Error adding host: {message}\nSystem Profile: {system_profile_fields}", extra={"host": host_data}
Same comment as above... system_profile fields should be a part of host_data.

2024-12-05 21:48 UTC, thearifismail reviewed
Forgot earlier to say that the `lib` directory is a better home for `system_profile_log.py`.  The utility folders, IMO, should be hold helper code/module that is not part of main execution

2024-12-06 15:03 UTC, jpramos123 commented on app/config.py
> +        self.sys_profile_fields_log = os.getenv("SYS_PROFILE_FIELDS_LOG", "")
I like the `sp_fields_to_log` suggestion

2024-12-09 12:29 UTC, jpramos123 commented on app/config.py
> +    def build_sys_profile_fields(self):
Done

2024-12-09 12:32 UTC, jpramos123 commented on app/instrumentation.py
> +        system_profile_fields,
Yes. I was not seeing the `extras` fields being logged locally, but I see they are logged in Kibana (which is the place we want to analyse this kind of logs)

2024-12-09 14:23 UTC, jpramos123 commented
> Generally speaking the logging system profile fields should be a part of over log configuration. This implementation suggests that system profile fields are accessory to host data and not a part of it, which is not true.
> 
> Another question is how are nested fields being logged? e.g. `systemd` or `operating_system`?

The nested fields are logged as a JSON string

2024-12-09 15:39 UTC, thearifismail commented on app/config.py
> +        self.sys_profile_fields_log = os.getenv("SYS_PROFILE_FIELDS_LOG", "")
Don't see this function in code anymore?

2024-12-10 16:33 UTC, kruai requested changes

2024-12-10 16:33 UTC, kruai commented on \
I don't think this file was added intentionally

2024-12-10 16:33 UTC, kruai commented on README.md
> +These fields are logged when `adding`, `updating` or `deleting` a host from inventory. It is very helpfull to debug hosts in Kibana.
```suggestion
These fields are logged when adding, updating or deleting a host from inventory. It is very helpful when debugging hosts in Kibana.
```

2024-12-10 16:33 UTC, kruai commented on app/config.py
> +
Same as above.

2024-12-10 16:33 UTC, kruai commented on app/config.py
> +
Since this is the same in the clowder and non-clowder configs, this can just be put in the `__init__` function. Also, since we always want it as list of fields rather than a string, we should just create the list once and not build it each time. So:

`self.sp_fields_to_log = os.getenv("SP_FIELDS_TO_LOG", "").split(",")`

2024-12-10 16:33 UTC, kruai commented on app/config.py
> +            return self.sp_fields_to_log.split(",")
Splitting an empty string returns an empty array by default
```suggestion
        return self.sp_fields_to_log.split(",")
```

2024-12-10 16:33 UTC, kruai commented on utils/system_profile_log.py
> +    return sp_fields_to_log
If `host_data` could either be a dict or a Host, I think it should be separated into multiple functions to better DRY, and so the typing is more clear. So something like:

```
def extract_sp_to_log(sp_data: dict) -> dict:
    return {k: sp_data[k] for k in inventory_config().sp_fields_to_log if k in sp_data}

def extract_host_model_sp_to_log(host: Host) -> dict:
    return extract_sp_to_log(host.system_profile_facts)

def extract_host_dict_sp_to_log(host_data: dict) -> dict:
    return extract_sp_to_log(host_data["system_profile"])
```

2024-12-13 13:09 UTC, jpramos123 commented on \
Thanks, removed

2024-12-13 14:06 UTC, jpramos123 commented on app/config.py
> +            return self.sp_fields_to_log.split(",")
At the end I removed this methods as it was not necessary

2024-12-13 14:07 UTC, jpramos123 commented on utils/system_profile_log.py
> +    return sp_fields_to_log
Done

2024-12-13 14:07 UTC, jpramos123 commented
> Forgot earlier to say that the `lib` directory is a better home for `system_profile_log.py`. The utility folders, IMO, should be hold helper code/module that is not part of main execution

I would rather keep it under `utils` directory!

Thanks

2024-12-13 20:28 UTC, thearifismail reviewed
LGTM but will take another look on Monday.

2024-12-16 16:13 UTC, thearifismail commented on app/config.py
> +        self.sys_profile_fields_log = os.getenv("SYS_PROFILE_FIELDS_LOG", "")
I see this function has been removed.

2024-12-16 16:19 UTC, thearifismail commented on README.md
> +These fields are logged when `adding`, `updating` or `deleting` a host from inventory. It is very helpfull to debug hosts in Kibana.
Verified the change is done.

2024-12-16 16:24 UTC, thearifismail approved these changes
LGTM

2024-12-17 01:58 UTC, kruai approved these changes

2024-12-17 13:26 UTC, merged