RHINENG-12670: Add script for publishing hosts
RedHatInsights/insights-host-inventory pull request #2109
Opened 2024-12-04 17:44 UTC by thearifismail

rh-pre-commit.version: 2.2.0
rh-pre-commit.check-secrets: ENABLED

# Overview

This PR is being created to address [RHINENG-12670](https://issues.redhat.com/browse/RHINENG-12670).
It checks the host-inventory database for a publication named `hbi_hosts_pub`.  If the publication is not found, it creates it.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Include raw query examples in the PR description, if adding/modifying SQL query
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-12-04 22:07 UTC, chambridge requested changes
Some suggestions and comments.

2024-12-04 22:07 UTC, chambridge commented on inv_publish_hosts.py
> +        found = result.cursor.fetchone()[0]
Does this work if the publication doesn't exist? Feels like you would be trying to get the zeroth index of `None` in that case.

2024-12-04 22:07 UTC, chambridge commented on deploy/clowdapp.yml
> +            value: ${BYPASS_UNLEASH}
I don't think this job needs all of these environment values for what its doing. We should just remove the unnecessary items.

2024-12-05 15:18 UTC, thearifismail commented on inv_publish_hosts.py
> +        found = result.cursor.fetchone()[0]
When the index does not exist, the `fetchone()[0]` returns ` `False`

2024-12-05 17:10 UTC, thearifismail reviewed
@chambridge addressed your comments.

2024-12-05 19:16 UTC, chambridge requested changes
A few more changes needed here.

Also this doesn't currently run when deployed as you need to add `inv_publish_hosts.py` to the Dockerfile.

The job is failing in ephemeral:
```
./run_command.sh: line 12: ./inv_publish_hosts.py: No such file or directory
```
https://ci.ext.devshift.net/job/RedHatInsights-insights-host-inventory-pr-check/5521/artifact/artifacts/k8s_artifacts/ephemeral-czeej6/logs/host-inventory-syndicator-28890400-7qpgv_host-inventory-syndicator.log

2024-12-05 19:16 UTC, chambridge commented on inv_publish_hosts.py
> +            logger.info(f'Publication "{PUBLICATION_NAME}" found!')
Can we add a check here to make sure all the replication slots are active?
`select slot_name, active from pg_replication_slots`
active column will be a true or false boolean. If the value is false can we print out the slot_name that is not active this could highlight a replication failure that needs to be resolved.

After printing out any inactive replication slots, if one exists than can we exit the Job with a failure `exit(1)` that way the Job alert will bring our attention the replication issue if it exists.

2024-12-06 15:42 UTC, thearifismail reviewed
@chambridge addressed your comments.

2024-12-06 15:42 UTC, thearifismail commented on inv_publish_hosts.py
> +            logger.info(f'Publication "{PUBLICATION_NAME}" found!')
Done!

2024-12-06 21:04 UTC, chambridge commented on Dockerfile
> +COPY inv_publish_hosts.py inv_publish_hosts
```suggestion
COPY inv_publish_hosts.py inv_publish_hosts.py
```
Minor typo here. You can see the job is still currently failing in the tests.

2024-12-09 15:43 UTC, chambridge approved these changes
lgtm

2024-12-09 15:49 UTC, thearifismail commented
/test

2024-12-10 13:01 UTC, strider approved these changes
LGTM

2024-12-10 14:08 UTC, merged