[RHINENG-7833] - Send notification newly-stale hosts
RedHatInsights/insights-host-inventory pull request #2123
Opened 2024-12-09 14:49 UTC by jpramos123

# Overview

This PR is being created to address [RHINENG-7833](https://issues.redhat.com/browse/RHINENG-7833).
It adds the functionality of sending notifications for hosts that went stale in the last X seconds. To define this X seconds, it was used the time windows between the job runs. Let say the last run was 1 hour ago, the new job that is going to run is going to fetch the hosts that went stale 1 hour ago. In cases that the job fails to run for some reason, this gap will increase. By default, the job is running every 1 hour.

To save the last run, it was created a tabled called `hbi_metadata`, that has 3 attributes:
- name
- type
- last_succeed

The `last_update` field is the one used to create the window time between the successful jobs runs.

It also refacts the host reaper, as this new feature is also a job that runs every certain amount of time. The common code used by both jobs were added to the `jobs/common.py` file.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Include raw query examples in the PR description, if adding/modifying SQL query
- [x] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-12-17 14:15 UTC, jpramos123 commented
/retest

2024-12-24 09:45 UTC, FabriciaDinizRH approved these changes
I think this needs more tests, but I'll not block it

2025-01-02 15:22 UTC, msager27 commented
/retest

2025-01-21 20:51 UTC, jpramos123 commented
/retest

2025-01-21 22:19 UTC, kruai requested changes
I wanna give this a more thorough review tomorrow, but a couple of quick things: 

- `staleness_to_conditions` got moved, so this PR is re-adding it in a new location
- I think it would be better if we didn't pass the config through all those functions that don't need it just to fetch the verification window. If we do need it, we could grab the value straight from `inventory_config`, for instance. But also, I don't know whether `_stale_in` should be built into the Conditions class; "stale_in" isn't a valid staleness state, and I think that makes `staleness_to_conditions` much less straightforward. I'd lean towards making a new filtering function, or potentially a new function to pass into timestamp_filter_func (haven't though that one through yet though)

2025-01-21 22:19 UTC, kruai commented on deploy/clowdapp.yml
> +            value: 'true'
I realize we can probably disable this on the other jobs as well, but I'm pretty sure we don't need payload tracker here

2025-01-21 22:19 UTC, kruai commented on deploy/clowdapp.yml
> +            value: "${INVENTORY_CACHE_THREAD_POOL_MAX_WORKERS}"
We can omit all this as the job isn't using the cache

2025-01-22 14:36 UTC, jpramos123 commented on app/culling.py
> +    return (timestamp_filter_func(*getattr(condition, state)(), host_type=host_type) for state in filtered_states)
Removed from here

2025-01-22 14:41 UTC, jpramos123 commented on deploy/clowdapp.yml
> +            value: "${INVENTORY_CACHE_THREAD_POOL_MAX_WORKERS}"
Removed from file

2025-01-29 22:08 UTC, kruai requested changes
I'll need to make a second pass at this tomorrow, but here are my thoughts so far, in addition to the inline comments:

- Thanks for refactoring the common job code! Great DRYing
- I don't see where the HostInventoryMetadata record is updated after the job completes. I see where it's created if it doesn't exist, but nowhere else
- The `HostStale` class feels kinda redundant, and its naming does not make its purpose very clear. I'd need to play around with the code a bit to see if there is a simpler and clearer way to achieve this; I encourage other reviewers to try as well

2025-01-29 22:08 UTC, kruai commented on stale_host_notification.py
This naming makes it sound like a class. How do you feel about naming it something like `stale_host_notification_producer.py` or `generate_stale_host_notifications.py`?

2025-01-29 23:13 UTC, thearifismail reviewed
Still reviewing

2025-01-29 23:13 UTC, thearifismail commented on stale_host_notification.py
> +def _create_host_stale_metadata_in_db(session: Session) -> HostInventoryMetadata:
Is it creating or checking staleness?  A host's staleness is set when the host is created or updated; the name is confusing.  May be adding the comment before the function signature will be helpful.

2025-01-30 19:49 UTC, thearifismail reviewed
@jpramos123 Based on the code review so far, three issues have come up to the fore. 

1. Modules arrangement.  Though this is a project wide issue but to get started from now on let's limit ourselves to stale_host_inventory and jobs/common.py.  I suggest starting with combining "stale_host_notification.run()" and "jobs.common.main()" functions; rest of the common code should go to the "lib" folder. IMO, the jobs folder is not needed.
2. Confusing names of variables, functions, and modules.  Look at each variable and what is this variable for and does its name communicates its purpose?  If it does not then, rename it to communicate its purpose.  If the names get too long, don't worry to get started.  Please look at my comments to see which names I found confusing or need clarification.
3. HostInventoryMetadata table.  First of all the name is confusing.  Is this table really needed?  Which I guess it is to save the "last update time" between two different notification events.  In its current form, this table is updated when all notifications have been sent?  Question is, what happens when there are 1000 hosts which have gone stale and notifications for 999 have been sent successfully but the last one did not go due to some problem.  This means the notification event did not complete successfully, so the last_update_time can not be updated.  Therefore it seems more appropriate that "last_update_time" should be recorded for each host.  The problem with this approach is that there will be way too much traffic updating this table.  If database should not hold "host-inventory-metadata", what other options are available to persist last update time between different notification events/episodes.

2025-02-03 14:28 UTC, jpramos123 commented on lib/metrics.py
> +    "inventory_stale_host_notification_processing_time", "Time spent notifying stale hosts from the database"
This suggestions make sense to me, thanks for that

2025-02-03 14:30 UTC, jpramos123 commented on app/models.py
> +    id = db.Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
No, I think this is something that I automatically assumed we needed by default. But make it sense to remove it to make it clear. Yes, name+type are already covering as a PK!

2025-02-03 16:54 UTC, jpramos123 commented on app/models.py
> +    last_update = db.Column(db.DateTime(timezone=True), default=_time_now, onupdate=_time_now)
Done

2025-02-03 17:59 UTC, jpramos123 commented on stale_host_notification.py
> +def _create_host_operation_result(host, identity, logger):
Done

2025-02-03 18:12 UTC, jpramos123 commented on jobs/common.py
> +    # run(config, logger, session, event_producer, notification_event_producer, shutdown_handler, application)
Done

2025-02-03 18:19 UTC, jpramos123 commented on app/models.py
> +    type = db.Column(db.String(255))
Fair enough. I will keep it as 32

2025-02-03 18:49 UTC, jpramos123 commented on app/models.py
> +        self.last_update = datetime.now(timezone.utc)
Thanks for catching this.
Made the changes in the code.

2025-02-03 18:50 UTC, jpramos123 commented on stale_host_notification.py
All good, changed to `generate_stale_host_notifications.py`

2025-02-03 18:54 UTC, jpramos123 commented on stale_host_notification.py
> +    stale_host_notification_processing_time,
This is exactly what it is doing. from the methods description:

```
Time a block of code or function, and observe the duration in seconds.
```

2025-02-03 18:56 UTC, jpramos123 commented on stale_host_notification.py
> +    stale_host_notification_count,
Done!

2025-02-03 18:56 UTC, jpramos123 commented on dev.yml
> +      image: prom/pushgateway
Done!

2025-02-03 18:58 UTC, jpramos123 commented on jobs/common.py
> +from functools import partial
IMPOV, the structure is fine.

We have the folder called `jobs` that indicates that the it is going to contain `jobs` related code. Inside it, we have the `common.py` file, that indicates the we have common code for the `jobs` in that file

2025-02-03 19:00 UTC, jpramos123 commented on stale_host_notification.py
> +def _create_host_stale_metadata_in_db(session: Session) -> HostInventoryMetadata:
the function name indicates it is creating as we can see it starts with **_create_**

2025-02-03 19:03 UTC, jpramos123 commented on lib/metrics.py
> +stale_host_notification_count = Counter(
Done. Addressed by your previous comment.

2025-02-03 19:07 UTC, jpramos123 commented on stale_host_notification.py
> +            .where(HostInventoryMetadata.name == "host_stale", HostInventoryMetadata.type == "job")
Possibilities are:
```
name: hbi_api
type: api
```
or
```
name: host_reaper
type: job
```

This is what comes to my mind right now

2025-02-03 19:16 UTC, jpramos123 commented on stale_host_notification.py
> +        stale_host_timestamp = _query_or_create_host_stale(session)
No, it is querying the `HostInventoryMetadata` class, filtering it by: `name == host_stale` and `type == job`. Do not confuse `stale_timestamp` with `stale_host_timestamp`.

2025-02-03 19:18 UTC, jpramos123 commented on stale_host_notification.py
> +    return stale_host_timestamp
The feature it self is related to newly-stale hosts being notified, I believe we need to have word `host` to specify the feature aim... Please, leave a suggestion if any!

2025-02-03 21:55 UTC, kruai requested changes
I think there are further things that can be refactored, but first, I wanna propose that we remove the HostStale class

2025-02-03 21:55 UTC, kruai commented on api/filtering/db_filters.py
> +    return (timestamp_filter_func(*host_stale.stale_in_window()),)
IMO the HostStale class doesn't need to exist. We also don't need to pass in a `timestamp_filter_func` bc it's going to be the same every time. For example:
```suggestion
def find_stale_host_in_window(staleness, host_type, last_run_secs):
    logger.debug("finding hosts that went stale in the last %s seconds", last_run_secs)
    # TODO: We'll want to pass in a value for "end_date"
    end_date = datetime.now()
    prefix = "immutable" if host_type == "edge" else "conventional"
    stale_timestamp = end_date - timedelta(seconds=staleness[f"{prefix}_time_to_stale"])
    return stale_timestamp_filter(
        stale_timestamp - timedelta(seconds=last_run_secs),
        stale_timestamp,
    )
```

2025-02-05 15:28 UTC, kruai commented on jobs/common.py
> +def main(logger, collected_metrics, prometheus_job_name):
I also want to move the scripts for our current jobs into the `jobs` folder (in a later PR). That'll make things more organized, and allow us to clean up some things (like our Dockerfiles)

2025-02-05 22:08 UTC, kruai approved these changes

2025-02-06 12:06 UTC, strider approved these changes
LGTM

2025-02-06 13:02 UTC, thearifismail reviewed
LGTM

2025-02-06 15:05 UTC, merged