[WIP] No review needed atm - Rbac middleware test
RedHatInsights/insights-host-inventory pull request #698
Opened 2020-08-17 14:01 UTC by tahmidefaz

2020-08-19 12:12 UTC, jharting commented on api/__init__.py
> +        if current_app.config["INVENTORY_CONFIG"].rbac_enforced:
it would be better for this to be in a standalone decorator, rather than added to api_operation

2020-08-19 12:12 UTC, jharting commented on lib/middlewares.py
> +read_actions = {
instead listing the required permissions here with standalone decorator (see my comment above) you can define the required permission right next to the definition of an operation, e.g.

```
@api_operation
@rbac("hosts:read")
@metrics.api_request_time.time()
def get_host_list(
```

2020-08-19 12:12 UTC, jharting commented on lib/middlewares.py
> +    rbac_data = get_rbac_permissions()
Don't forget to check whether the x-rh-identity belongs to a user or to a system (cert auth). For cert auth we don't enforce RBAC.

2020-08-24 10:36 UTC, jharting requested changes
Good progress since the last time. There are still problems that need fixing, though.

In addition:

- we'll need test(s) for error handling
- we'll need test(s) to verify that rbac is bypassed for System identity type

2020-08-24 10:36 UTC, jharting commented on tests/fixtures/api_fixtures.py
> +    def _api_patch(url, host_data, query_parameters=None, extra_headers=None, identity_type="System"):
Why do these fixtures default the identity_type to System instead of User?

2020-08-24 10:36 UTC, jharting commented on tests/test_api_facts.py
> +def test_patch_host_with_RBAC_allowed(subtests, mocker, api_put, db_create_host, event_producer_mock, enable_rbac):
What is the `event_producer_mock` parameter for?

2020-08-24 10:36 UTC, jharting commented on tests/test_unit.py
> +        return Identity(account_number="some acct", identity_type="System")
Same as above - why default to System?

2020-08-24 15:32 UTC, ryandillinfelton commented on tests/test_unit.py
> +        return Identity(account_number="some acct", identity_type="System")
We thought it would be necessary to have the old tests bypass rbac by default. On second examination rbac isn't actually enforced by default so I'll change these over to user by default

2020-08-24 15:33 UTC, ryandillinfelton commented on tests/fixtures/api_fixtures.py
> +    def _api_patch(url, host_data, query_parameters=None, extra_headers=None, identity_type="System"):
Answered below

2020-08-24 15:34 UTC, ryandillinfelton commented on tests/test_api_facts.py
> +def test_patch_host_with_RBAC_allowed(subtests, mocker, api_put, db_create_host, event_producer_mock, enable_rbac):
Unnecessary here, I must not have noticed I carried it over from another version of the test that needed it.

2020-08-24 15:35 UTC, ryandillinfelton commented on swagger/api.spec.yaml
> +        Required permisions: inventory:hosts:read
:facepalm:

2020-08-24 16:41 UTC, rodrigonull commented on lib/middlewares.py
> +        def modified_func(*args, **kwargs):
```suggestion
        def modified_func(*args, **kwargs):
            if not inventory_config().rbac_enforced:
                return func(*args, **kwargs)

            if current_identity.identity_type != "User":
                return func(*args, **kwargs)

            rbac_data = get_rbac_permissions()

            for rbac_permission in rbac_data:
                if (
                    rbac_permission["permission"] == "inventory:*:*"
                    or rbac_permission["permission"] == "inventory:hosts:*"
                    or rbac_permission["permission"] == requested_permission
                ):
                    return func(*args, **kwargs)

            rbac_failure(logger, "unauth")
            abort(status.HTTP_403_FORBIDDEN)

        return modified_func
```

2020-08-24 16:44 UTC, rodrigonull commented on lib/middlewares.py
> +        def modified_func(*args, **kwargs):
Your code executes the request before it validates the RBAC user's permission which is wrong because even if the user doesn't has the permissions to for example patch a host, the host would be patched anyway despite the user getting a 403 response.

2020-08-24 17:03 UTC, shdunning commented on lib/middlewares.py
> +        def modified_func(*args, **kwargs):
excellent catch!

2020-08-25 11:31 UTC, jharting approved these changes
Some more tests improvements should be done. Tracked in https://projects.engineering.redhat.com/browse/RHCLOUD-8775

2020-08-25 11:32 UTC, merged