Use externalized schema for system profile validation
RedHatInsights/insights-host-inventory pull request #700
Opened 2020-08-21 15:42 UTC by Glutexo

Message Queue API Ingress uses externalized System Profile schema for validation. The schema has been updated to the [current version](https://github.com/RedHatInsights/inventory-schemas/blob/b4436190454610e93e2d73815d2510e15e817196/schemas/system_profile/v1.yaml) with all Marshmallow constrains included.

There are however some changes, so the schema can be easily used:

* Schema version downgraded to Draft 4 so it is compatible with Connexion that uses the file too.
* The recursive _NestedObject_ definition has been removed. It is not compatible with JSON Schema Draft 4. Empty key validation is done manually.
* Object types are explicitly defined, so Connexion’s type coercion used by our custom validation works properly. There is already a PR to fix this.

2020-08-31 08:44 UTC, jharting requested changes
This implementation does not deal with keys sent by reporters that are not explicitly defined in the schema.

The current (marshmallow) implementation tolerates such keys (does not consider them to be schema violations) but strips them away. As a result, such fields are never stored in the database.

The proposed implementation does not validate such keys but does not remove them either. As a result, such keys are stored in the database which is not desired.

2020-08-31 08:44 UTC, jharting commented on app/models.py
> +    system_profile = fields.Nested(SystemProfileSchema)
Should this be added here?

2020-08-31 08:44 UTC, jharting commented on app/models.py
> +        schema = {**self.system_profile_spec, "$ref": "#/$defs/SystemProfile"}
This combines two static values. Should it be done once i.e. in the constructor rather than repeatedly on every validation?

2020-08-31 09:55 UTC, Glutexo commented on app/models.py
> +        schema = {**self.system_profile_spec, "$ref": "#/$defs/SystemProfile"}
Great point! Not only this is suboptimal, but  also the schema is loaded and parsed repeatedly every time the schema is used. That is even more performace heavy. I’ll fix both.

2020-08-31 09:56 UTC, Glutexo commented on app/models.py
> +    system_profile = fields.Nested(SystemProfileSchema)
It should. I removed the field from the parent _BaseHostSchema_. The definition is now different for _MqHostSchema_ and _HttpHostSchema_.

2020-08-31 09:57 UTC, Glutexo commented
It is not actually easy to test that the Marshmallow schema is not used. It is instantiated on class declaration, not on its instantiation. Because of that it is barely impossible to patch it in any way. I added at least a test verifying that the _MqHostSchema_ is used for deserialization and that the schema class does not directly use a nested _SystemProfileSchema_ instance.

2020-08-31 11:57 UTC, Glutexo commented
One more test to verify that the external schema is actually used. It mocks the specification file and adds a validation that is not in Marshmallow. Then validation is checked for failure.

2020-09-01 07:55 UTC, Glutexo commented on app/models.py
> +        schema = {**self.system_profile_spec, "$ref": "#/$defs/SystemProfile"}
I wanted to prevent a side effect of loading and parsing a file on import, so I introduced a lazy-loaded variable. On its first use, the schema is loaded and cached, further on it is re-used. It requires some shenanigans in the test tampering with the schema, but saves a good deal of performance.

2020-09-02 09:09 UTC, Glutexo commented
Although Marshmallow did remove undefined fields on unmarshall, this is not correct behavior for JSON Schema. To reject unexpected object properties there is an _additionalProperties_ directive that can contain a _false_ schema. If not provided, it is equal to a _true_ schema. Adding this to our schema would be the right thing to do and pairs nicely with disabling the type coercion.

Now, to preserve the current behavior, we need to violate the JSON Schema semantics a bit. I‘d go with this:
- If _properties_ are explicitly defined, use it as a whitelist and silently (without failing) remove the undefined ones. This is what Marshmallow does.
- If there is no _properties_ definition, keep all keys. This makes us not remove everything from arbitrary (disk device-like) objects.
- Ignore (keep) anything that is not explicitly declared as _object_.
- Do not pay any attention to _additionalProperties_. It is not used in the current version of the schema anyway.

2020-09-02 10:39 UTC, Glutexo commented
I implemented the key filtering the way described above. Please review the approach and its implementation. Also please review the new tests verifying that the externalized schema is actually used instead of Marshmallow for System Profile.

2020-09-04 09:21 UTC, jharting commented
> I implemented the key filtering the way described above. Please review the approach and its implementation. Also please review the new tests verifying that the externalized schema is actually used instead of Marshmallow for System Profile.

Did you push all the commits? I cannot see the key filtering neither tests for it.

2020-09-04 10:20 UTC, Glutexo commented
😞🤦🏻‍♂️ Fixed.

2020-09-07 09:12 UTC, Glutexo commented on app/models.py
> +    elif schema_type == "array" and "items" in schema:
I am not sure here. In both cases, this would make the code quite unnecessarily verbose. The inline strings here are string literal key names defined by JSON Schema.

- ```
   class SchemaTypes(Enum):
       ARRAY = "array"
       OBJECT = "object"
   
   if schme
   ```

2020-09-07 09:22 UTC, Glutexo commented on app/models.py
> +        processed_data = deepcopy(raw_data)
This is a good point. Immutability is nice when the language is optimized for object copying. This is not Python’s case. I‘ll take a look.

2020-09-07 12:52 UTC, Glutexo commented on app/models.py
> +        processed_data = deepcopy(raw_data)
I examined deeper (pun intended) the uses of _deepcopy_:

- [In the _pre-load_ function](https://github.com/Glutexo/insights-host-inventory/blob/c37e9f69a71a0c1c46075732eb75820f2c0784fe/app/models.py#L444) it is not necessary as long as the input object is not mutated. Unmarshalling itself then creates a safe copy.
- [In the key filtering function](https://github.com/Glutexo/insights-host-inventory/blob/c37e9f69a71a0c1c46075732eb75820f2c0784fe/app/models.py#L69), this is the most complicated case. If the value is described by the schema, it is traversed and in case of an object, filtered by keys. Each time, a new list/dictionary is created by a comprehension expression. The _deepcopy_ is then called only on leaves, which in case of immutable scalars returns the same object and is thus cheap. In case of arbitrary objects/arrays (only disk devices options in our case), real _deepcopy_ is performed, which is comparable to the recursive schema-aware call of ours.
- [In case of the type coercion function](https://github.com/Glutexo/insights-host-inventory/blob/c37e9f69a71a0c1c46075732eb75820f2c0784fe/app/models.py#L72), this is necessary for the wrapped Connexion function not to mutate the original object. Here it would be possible to omit it if we called in on the result of the filter key function that creates deeply copied object. That would however make the two calls inconsistent and thus possible error-prone.

As a conclusion, I’d refrain to make those two function consistent in that they are going to mutate the existing object. Then only one clearly visible _deepcopy_ call would be used. Although I would like to prevent mutation as much as possible, here the other approach makes sense too.

2020-09-08 10:00 UTC, Glutexo commented on app/models.py
> +    elif schema_type == "array" and "items" in schema:
I gave this some more thought and hopefully came up with a solution. Several ways I tried were unnecessarily verbose and introduced only a lot of syntactic clutter. Finally I achieve these with only a slight increase in the LOC number:

- Magic strings coming from the JSON Schema DSL appear only once each. 
   - Schema keys are used only as a clear dict-key reference in initialization constructs.
   - Type names are listed only in a enum-like type map.
- The whole filter selection dependent on various schema dictionary information is concentrated in a single try-except clause. Fallback is not repeating.
- As a side effect, the filters are represented by Python types.

I hope this makes the code not only efficient, but also a good example for any of our code readers. Any feedback is appreciated!

2020-09-08 10:10 UTC, Glutexo commented
Tests need to be fixed because of changed syntax.

2020-09-08 10:58 UTC, Glutexo commented
Updated the unit tests. Found one bug in them, fixed. Added one more test case.

2020-09-08 13:24 UTC, jharting requested changes

2020-09-08 13:24 UTC, jharting commented on app/models.py
> +        except KeyError:
Let's not use exceptions for flow control.

2020-09-08 13:24 UTC, jharting commented on app/models.py
> +    class ObjectFilter:
How are these objects better than just having functions for object/array/nofilter?

2020-09-08 13:49 UTC, Glutexo commented on app/models.py
> +        except KeyError:
Python encourages this antipattern, calling it an [EAFP principle](https://docs.python.org/3/glossary.html#term-eafp), and its own standard library heavily uses it. It’s more or less officially the standard pythonic way. It’s nicely manifested by the existence of the _else_ part of _try/except/else_ block. More references: [\[1\]](https://jeffknupp.com/blog/2013/02/06/write-cleaner-python-use-exceptions/), [\[2\]](https://devblogs.microsoft.com/python/idiomatic-python-eafp-versus-lbyl/), [\[3\]](https://www.pythonstudio.us/learning-3/a-final-note-on-pythonic-exception-handling.html).

But since you made this a requested change, I‘ll change it to LBYL. We’re already doing much worse with exceptions like using _except Exception_. We can live with this.

2020-09-08 13:57 UTC, Glutexo commented on app/models.py
> +    class ObjectFilter:
If you look at it from the other side, how are functions better than the objects?

The objects provide at least tiny namespaces that couple the two parts together. The _init_ part checks that it’s possible to use this filter and loads the necessary data from the schema. The _call_ part does the actual filtering. Also, classes can prevent function nesting, which may be less readable due to excessive indentation and unintuitive return values.

But again, since this is a requested change, I’ll try to come up with a way that doesn’t use classes. In Python, classes are not that much different from any other objects. Functions themselves are objects, just as dicts and other scalars.

2020-09-08 13:57 UTC, jharting commented on app/models.py
> +        except KeyError:
@Glutexo 
> This common Python coding style assumes the existence of valid keys or attributes and catches exceptions if the assumption proves false.

Well, does that apply in our situation, though? Do we assume the existence of valid keys? We know for sure that in order to process a single host message that except clause will be entered dozens if not hundreds of time.
Also take a look at https://docs.python.org/3/faq/design.html#how-fast-are-exceptions

2020-09-09 09:47 UTC, Glutexo commented on app/models.py
> +        except KeyError:
The documentation says
> A try/except block is extremely efficient if no exceptions are raised.

The only place where this exception is raised and caught is actually the infamous _/DiskDevice/options_ object that doesn’t define _properties_. In all other cases, the _except_ block is not triggered at all.

I did some benchmarking, deserializing 2,000 hosts. The refactored version is in total about 100ms slower. There were a few runs when the refactored version ran faster than the original one.
- The original procedural version with conditionals. Only modified to mutate the passed object.
   ```
   Sum: 3491.9967651367188ms
   Sum: 3478.938579559326ms
   Sum: 3504.4939517974854ms
   Sum: 3426.2311458587646ms
   Sum: 3596.139669418335ms
   ```
- The refactored version using types and exception handling.
   ```
   Sum: 3570.7499980926514ms
   Sum: 3647.9811668395996ms
   Sum: 3569.4141387939453ms
   Sum: 3652.5745391845703ms
   Sum: 3661.5259647369385ms
   ```

For comparison, I add two more measurements. Each of them contains only one of the two possible slowdown factors.

- Uses types, but does not use exceptions.
   ```
   Sum: 3608.1724166870117ms
   Sum: 3581.0811519622803ms
   Sum: 3634.829044342041ms
   Sum: 3566.1404132843018ms
   Sum: 3586.2221717834473ms
   ```
- Uses exceptions, but does not use types.
   ```
   Sum: 3550.719976425171ms
   Sum: 3508.180618286133ms
   Sum: 3527.4999141693115ms
   Sum: 3531.621217727661ms
   Sum: 3595.9036350250244ms
   ```

It looks like both changes decrease the performance a little. The exceptions slightly more than the types. That proves your fear was correct, although in a very small scale. Is it worth considering? What the difference would be in the production cluster?

2020-09-09 10:17 UTC, jharting commented on app/models.py
> +        except KeyError:
> The only place where this exception is raised and caught is actually the infamous /DiskDevice/options object that doesn’t define properties. In all other cases, the except block is not triggered at all.

Really? What about the scalar properties?

2020-09-10 09:49 UTC, Glutexo commented on app/models.py
> +        except KeyError:
🤔 You are right!

2020-09-14 07:38 UTC, Glutexo commented
I gave it some more work and came up with a new refactoring

2020-09-14 08:06 UTC, Glutexo commented on app/models.py
> +            type_str = self._asdict()["type"]
This is necessary to avoid recursion by accessing `self.type`.

2020-09-14 08:19 UTC, Glutexo commented
_Simple is better than complex._ A fresh look gave me a possibility to simplify stuff that required an explanatory comment.

2020-09-14 08:20 UTC, Glutexo commented on app/models.py
> +            type_str = self._asdict()["type"]
Renamed to _schema_type_ to remove this shenanigan.

2020-09-14 08:21 UTC, Glutexo commented on app/models.py
> +    Schema.__new__.__defaults__ = (None,) * len(Schema._fields)
Removed in favor of a simple _dict.get_.

2020-09-17 10:38 UTC, jharting approved these changes

2020-09-17 10:39 UTC, merged

2020-09-17 10:49 UTC, Glutexo commented
Awesome, thanks! 🙇🏻‍♂️