Kafka producer additions
RedHatInsights/insights-host-inventory pull request #701
Opened 2020-08-21 16:31 UTC by bastilian

This makes a few adjustments to the Kafka producer to generate hosts to be created in the inventory.

It allows to set the number of hosts as well as the account they should be created for.
It also uses the random uuid to not have them all be named the same.

2020-08-24 09:38 UTC, bastilian commented
I'm not really sure what the test failures about, since there were no changes to the Pipfile.

2020-08-28 07:07 UTC, jharting requested changes
This fails because of linter rules. Run `make style` to fix the problems.

2020-08-28 07:07 UTC, jharting commented on utils/kafka_producer.py
> +NUM_HOSTS = os.environ.get("NUM_HOSTS", 1)
The env var value will need to be parsed into an integer first for this to work

2020-08-28 07:38 UTC, bastilian commented on utils/kafka_producer.py
> +NUM_HOSTS = os.environ.get("NUM_HOSTS", 1)
AH! I'm a total Python noob. :) Thanks. I'll fix that.

2020-08-28 10:30 UTC, bastilian commented
@jharting Thanks for the hint! I made sure now that `make style` passes. I also shortened the uuid to six chars that should be enough.

2020-08-31 07:32 UTC, jharting approved these changes

2020-08-31 07:33 UTC, merged

2020-08-31 07:33 UTC, jharting commented
@bastilian merged, thanks!