RBAC Test Improvements
RedHatInsights/insights-host-inventory pull request #703
Opened 2020-08-26 12:18 UTC by tahmidefaz

2020-08-26 22:44 UTC, tahmidefaz commented
This is ready for review now. :arrow_up:

2020-08-28 06:56 UTC, jharting requested changes
Found a problem in one test. Moreover, these two operations are not tested at all:
* get_host_system_profile_by_id
* get_host_tag_count

2020-08-28 06:56 UTC, jharting commented on tests/test_api_facts.py
> +            assert db_get_host(host.id).facts != DB_NEW_FACTS
these would never be equal as on the left side you have all the namespaces whereas on the right side you have data in DB_FACTS_NAMESPACE only

```suggestion
            assert db_get_host(host.id).facts[DB_FACTS_NAMESPACE]["facts"] != DB_NEW_FACTS
```

2020-08-31 02:43 UTC, tahmidefaz commented on tests/test_api_facts.py
> +            assert db_get_host(host.id).facts != DB_NEW_FACTS
Looks like we weren't using the `api_put` correctly either. Fixed this + the `api_put`. :+1:

2020-08-31 02:44 UTC, tahmidefaz commented
Just added tests for `get_host_tag_count` and `get_host_system_profile_by_id`. This one needs another round of review now.

2020-08-31 08:09 UTC, jharting approved these changes

2020-08-31 08:09 UTC, merged