Make host delete chunk size configurable - RHCLOUD-8272
RedHatInsights/insights-host-inventory pull request #705
Opened 2020-08-27 18:56 UTC by tahmidefaz

2020-08-28 07:02 UTC, jharting requested changes

2020-08-28 07:02 UTC, jharting commented on lib/host_delete.py
> +        for host in select_query.limit(inventory_config().host_delete_chunk_size):
This relies on the app context which is not available when reaper runs. As a result this change breaks reaper. We may need to pass the value as a parameter instead.

2020-09-02 07:18 UTC, Glutexo commented on lib/host_delete.py
> +        for host in select_query.limit(inventory_config().host_delete_chunk_size):
It may be worth thinking about some “global” configuration context for values common to all environments.

2020-09-02 18:46 UTC, tahmidefaz commented
Finally added that test, any suggestion on improvements?

2020-09-03 08:29 UTC, jharting commented
@tahmidefaz if I undo all the changes in this PR except for the test it still passes. That may be an indication that the test is not very good.

2020-09-03 08:55 UTC, jharting approved these changes

2020-09-03 08:56 UTC, merged