Configuring Kafka Producer- RHCLOUD-8249
RedHatInsights/insights-host-inventory pull request #708
Opened 2020-09-02 21:46 UTC by tahmidefaz

2020-09-02 21:50 UTC, tahmidefaz commented
As far as I could tell, we mock the actual Kafka Producer in tests. So, I am not sure if this was the ask from a testing perspective.

One other thing to note is that the `"acks"` parameter can actually either be a string or an integer.

2020-09-03 09:45 UTC, jharting requested changes
@tahmidefaz if I start the consumer using `KAFKA_PRODUCER_ACKS=1 make run_inv_mq_service` the messages do not seem to be produced any longer

2020-09-03 11:21 UTC, Glutexo commented
@tahmidefaz Is this ready for review?

2020-09-03 11:59 UTC, tahmidefaz commented
@jharting That could be because `"acks"` expects an integer when it equates to `1`, I think I will add an intermediate function to handle that logic. I wished `"acks"` took the values of the same type instead of `[0,1,"all"]` :disappointed: 

@Glutexo Not yet. Need to make this change ^

2020-09-03 12:54 UTC, tahmidefaz commented
Just added a simple dictionary to map those values. This is ready for another look. :+1:

2020-09-04 10:07 UTC, jharting approved these changes
I added some tweaks and proper tests. Would appreciate review from @Glutexo

2020-09-04 11:12 UTC, Glutexo reviewed
Some comments for @jharting on the configuration tests.

2020-09-04 11:12 UTC, Glutexo commented on tests/test_config.py
> +        Config(RuntimeEnvironment.TEST)
Dtto default values. There is already one [test](https://github.com/RedHatInsights/insights-host-inventory/blob/d656bf700a10bf6fca221737a959dc80050ed091/tests/test_unit.py#L271) for those in the aforementioned existing test case.

2020-09-04 11:17 UTC, Glutexo commented on tests/test_config.py
> +    config = Config(RuntimeEnvironment.TEST)
This repeats many times for each test , it’s almost worth extracting to a function.

2020-09-04 12:25 UTC, merged

2020-09-04 15:12 UTC, Glutexo reviewed
Assuming untested code is broken code, I couldn’t give ✅ here. Please test that the configuration values are actually used. Dropped some more comments. Otherwise it looks good to me! Great work, thanks!

2020-09-04 16:27 UTC, Glutexo commented on app/config.py
> +    def _from_dict(self, dict, name, default):
The _dict_ here shadows an internal Python type name. That is not good.

2020-09-04 16:35 UTC, Glutexo commented on app/config.py
> +        return value
```suggestion
        raw = os.environ.get(name, default)
        try:
            return dict[name]
        except KeyError as error:
            raise ValueError(f"{raw} is not a valid value for {name}. Valid values are {dict.keys()}.") from error
```

It’s easier to forgive than to allow. This is more pythonic.