Grafana dashboard migration
RedHatInsights/insights-host-inventory pull request #712
Opened 2020-09-18 14:39 UTC by tahmidefaz

2020-09-21 20:27 UTC, kruai approved these changes
LGTM!

2020-09-22 22:09 UTC, thearifismail commented
/LGTM

2020-09-24 13:08 UTC, tahmidefaz commented
One more :heavy_check_mark: , maybe from @ryandillinfelton ? We should push to get this merged sometime today :slightly_smiling_face:

2020-09-24 14:59 UTC, ryandillinfelton commented on utils/validate_dashboards.py
> +    sys.exit(1)
I think It'd be nice to have some sort of success confirmation message when no errors are found on a file. But I won't hold up migration on that.

2020-09-24 15:20 UTC, tahmidefaz commented on utils/validate_dashboards.py
> +    sys.exit(1)
just did :+1:

2020-09-24 15:28 UTC, ryandillinfelton requested changes
I found some issues with the validation script not catching the issues it's looking for. Everything else looks good though

2020-09-24 15:28 UTC, ryandillinfelton commented on utils/validate_dashboards.py
> +        if not y["metadata"]["name"]:
This throws an error when the name field doesn't exist, but not in the way you want. 

> Traceback (most recent call last):
>   File "utils/validate_dashboards.py", line 29, in validate
>     if not y["metadata"]["name"]:
> KeyError: 'name'

I think you should be using
```
if y["metadata"].get("name")
    yield Error("Resource name not found", f)
```
This will still cause a keyerror if metadata does not exist, so It could be worth doing a get check on that before you check if name exists.

2020-09-24 15:28 UTC, ryandillinfelton commented on utils/validate_dashboards.py
> +        yield Error(e.msg, f)
e.msg does not work for ScannerErrors caused by bad yml. They do not have a `msg` field.

> AttributeError: 'ScannerError' object has no attribute 'msg'

`yield Error(e, f)` works for them, but might cause issues with other Exceptions

2020-09-24 15:28 UTC, ryandillinfelton commented on utils/validate_dashboards.py
> +        if len(d) != 1:
This doesn't seem to work. If I add 
```
general.json: |-
    {"hey": "a key"}
```
above or below the dashboard JSON in the data data field the validator doesn't throw any errors (unless the JSON is bad)

2020-09-24 18:33 UTC, tahmidefaz commented on utils/validate_dashboards.py
> +        if len(d) != 1:
Just added a conditional to check for this, but it still isn't perfect. It has to do with how the yaml parsing library is setup + how dictionaries work in python. For example, if python sees this dictionary `{"key": 1, "key": 2}`, it will shorten it to `{"key":2}`. So, whenever we have two `general.json`, it overwrites it to the latest one it sees. I think a big change like that will likely be caught during review, imo :slightly_smiling_face:

2020-09-24 20:59 UTC, ryandillinfelton approved these changes

2020-09-24 20:59 UTC, ryandillinfelton commented on utils/validate_dashboards.py
> +        if len(d) != 1:
Seems reasonable. If this check isn't doing anything I'd say let's just remove it rather than create a false sense of security. But that being said I think you're right that the odds of this problem surfacing at all is super low. 

I'll approve the PR now since we need it by tomorrow. If we decide want to remove this we can do a follow up change tomorrow.

2020-09-24 21:02 UTC, merged