Fix system profile fields filtering
RedHatInsights/insights-host-inventory pull request #715
Opened 2020-09-24 12:20 UTC by Glutexo

2020-09-25 09:25 UTC, Glutexo commented
Tests fixed. Even more reviewable now.

2020-09-25 15:32 UTC, kruai approved these changes
I think everything looks good... I just had a couple of questions :)

2020-09-25 21:39 UTC, ryandillinfelton requested changes
I had some questions about a few tests that seemed odd to me, and a field name change. Otherwise it looks good!

2020-09-25 21:41 UTC, tahmidefaz commented
^ What Ryan said + you need to fix the merge conflict :+1:

2020-09-29 12:10 UTC, Glutexo commented
Thanks for your reviews, guys! Working on the fixes!

2020-09-29 12:40 UTC, thearifismail commented on swagger/system_profile.spec.yaml
> +      base_url:
How are the two related other than what the parameter is?

2020-09-29 12:51 UTC, thearifismail commented on tests/helpers/system_profile_utils.py
> +)
cores_per_socket
What's the criteria for inclusion to this list?  e.g.  "system_memory_bytes" or "number_of_cpus" not included either?

2020-09-29 16:37 UTC, thearifismail commented
Since I didn't know much about the inventory.  I ran the code locally and it works as expected. Based on that:

/LGTM

2020-09-30 13:23 UTC, Glutexo commented on swagger/system_profile.spec.yaml
> +        maxLength: 256
It looks like an arbitrary length to have at least some validation, but not to break any reporter. We plan on having stricter validation rules, but for now, it has been just moved from the Marshmallow rules as is. I think you can always reach to https://github.com/RedHatInsights/inventory-schemas and raise a concert.

2020-09-30 13:24 UTC, Glutexo commented on swagger/system_profile.spec.yaml
> +        maxLength: 25
If so, this should be an _enum_ instead of a _string_ with a _maxLength_ constrain. I however just took the existing Marshmallow rule as this pull request should not change the behavior. This would need to be first resolved in https://github.com/RedHatInsights/inventory-schemas before changing it here.

2020-09-30 13:28 UTC, Glutexo commented on swagger/system_profile.spec.yaml
> +      base_url:
[Spotted](https://ansible.slack.com/archives/CQFKM031T/p1600350827126100?thread_ts=1600344856.115300&cid=CQFKM031T) by @rodrigonull, it should be "base_url". It happened by mistake. The [inventory schema](https://github.com/RedHatInsights/inventory-schemas/blob/master/schemas/system_profile/v1.yaml#L54) is wrong and should be updated. The bad thing is that now in _master_ we have _baseurl_ and thus are not storing the value sent as _base_url_. It should be fixed.

2020-10-01 11:28 UTC, Glutexo commented on tests/test_unit.py
> +        self.assertEqual(original, payload)
These tests verify that the JSON Schema directives _additionalProperties_ and _required_ are ignored and the filtering takes place regardless of their presence or value.

- _additionalProperties_ defaults to _True_ meaning that if a property is not defined among _properties_, anything is allowed. Our key filtering removes any key that is not explicitly defined, ignoring any rules in there. Other tests already verify that the filtering takes place if _additionalProperties_ is not defined. The _test_additional_properties_are_ignored_ test verifies that the keys are removed even if it is set to something more verbose. The payload contains an undefined key and it’s removed without raising an error even though it violates the rule.
- _required_ defaults to an empty list and lists properties that must be present. These required keys may or may not appear among the _properties_ definitons. The _test_required_properties_are_ignored_ test verifies that even if a key is defined as required, it is still filtered out.

Both of these may seem unintuitive. The point is that the filtering is a temporary hack to emulate the former Marshmallow behavior. It parses some features of JSON Schema, but doesn’t even remotely try to support the whole standard. These tests thus verify that these advanced features are ignored. We don’t use them now and I hope we won’t until the key filtering is removed and replaced by a more standard validation. But if anybody tries to add them, they’ll run into those tests describing the current behavior.

Does it make sense, @ryandillinfelton? Did I answer your question? Have more?

2020-10-01 11:30 UTC, Glutexo commented
@thearifismail Unfortunately _/lgtm_ does not work here. This is not AppSRE GitLab. Please use GitHub review mechanism to approve. Thanks!

2020-10-01 12:40 UTC, thearifismail approved these changes

2020-10-01 12:48 UTC, Glutexo commented on tests/helpers/system_profile_utils.py
> +)
@ryandillinfelton Added the missing rules. Thanks for spotting!

2020-10-01 12:55 UTC, Glutexo commented
Thanks for your review, @ryandillinfelton? Please tak a look at my inline comment on the tests and see my fixup commits. Please drop me a ✅  if it’s ok, so I can merge.

2020-10-01 13:04 UTC, Glutexo commented on swagger/system_profile.spec.yaml
> +      base_url:
I did some excavation and it looks like it has been _baseurl_ ever since. See https://github.com/RedHatInsights/insights-host-inventory/commit/607af09703d322c0696d7c86c3d6c5daa6f182a3#diff-b5704d15302288389d3aef6d5ab2a4f3L952.

2020-10-01 13:53 UTC, rodrigonull commented on swagger/system_profile.spec.yaml
> +      base_url:
I think we may have a problem with our iqe tests. As you can see here: https://gitlab.cee.redhat.com/insights-qe/iqe-host-inventory-plugin/-/blob/master/iqe_host_inventory/tests/rest/validation/test_system_profile.py#L400 we have this test where we validate the `base_url` field. This test was implemented a long time ago and its passing since then and because of that I've assumed that `base_url` name was the correct name of the field, but looking at a real insights archive I found that the yum.repos.d file has the `baseurl` info and not the `base_url` info. So I'm a little confused right now because I don't now how the test was passing since we were sending the wrong field name.

2020-10-01 20:32 UTC, tahmidefaz commented on swagger/system_profile.spec.yaml
> +      base_url:
@Glutexo I just checked my 2 month old branch, I found that field to be set to `baseurl` and not `base_url`. https://github.com/RedHatInsights/insights-host-inventory/blob/set-more-headers/swagger/system_profile.spec.yaml#L46

2020-10-01 20:34 UTC, tahmidefaz commented
Almost LGTM from me, just left a comment for `base_url` vs `baseurl`, please check the comment in the thread above. Basically, I think `baseurl` is the correct field name.

2020-10-02 08:41 UTC, Glutexo commented
AAAAA! I agree that we should stick to what it was and change it separately.

2020-10-02 08:43 UTC, Glutexo commented on swagger/system_profile.spec.yaml
> +      base_url:
Okay. Let’s stick to _baseurl_, because it means no change from the existing behavior. We can and should resolve this separately once we find out what the correct name is. Thanks @rodrigonull for the detective work!

2020-10-02 12:13 UTC, Glutexo commented on swagger/system_profile.spec.yaml
> +      base_url:
I tracked that beast down. It dates as far as to the first commit adding the System Profile support: fa994dd221e9127f83f8ba41419f70d21d52e20a There, in [the Marshmallow model](https://github.com/RedHatInsights/insights-host-inventory/blob/fa994dd221e9127f83f8ba41419f70d21d52e20a/app/models.py#L235), it was _base_url_ and in [the OpenAPI specification](https://github.com/RedHatInsights/insights-host-inventory/blob/fa994dd221e9127f83f8ba41419f70d21d52e20a/swagger/api.spec.yaml#L680) that later became the externalized System Profile schema it was _baseurl_. After a year and a half, greetings to @dehort. 😃

2020-10-02 12:15 UTC, Glutexo commented
@tahmidefaz, @dehort Tracked the base_url/baseurl discrepancy back to fa994dd. See my [comment](https://github.com/RedHatInsights/insights-host-inventory/pull/715#discussion_r498783465).

2020-10-02 12:37 UTC, tahmidefaz commented
@Glutexo you got tests failing. Otherwise, it's a LGTM from me :+1:

2020-10-02 12:45 UTC, Glutexo commented
@tahmidefaz I know, I know. I changed that to a state that doesn’t change the _base_?url_ to see what fails. Because that shows us where the behavior changes. This pull request **should not change behavior** and I am trying to come up with a solution that would satisfy this requirement.

2020-10-02 13:10 UTC, Glutexo commented
So the current behavior is:

- On the deserialization level, _base_url_ is validated for type and length. This applies both to MQ and HTTP.
- On the OpenAPI level, _baseurl_ is validated for type.Length constraint is not there and _uri_ format is ignored. _base_url_ is not validated, but not removed.

I think the right approach is to add _base_url_ to the System Profile schema and remove _baseurl_ from there. The reasons are:

- For MQ, we need _base_url_ to be still validated. We added the missing constraints from Marshmallow to JSON Schema and this is just another one of those. That preserves the behavior.
- For HTTP, previously non-existent constraint is added, which changes behavior. That’s however already expected and desired.
- Removing _baseurl_ preserves behavior for MQ. That field is going to be still filtered out and not preserved For HTTP this slightly changes the behavior, because invalid values would be no longer rejected by OpenAPI, but the field wasn’t persisted anyway, so it causes no harm at all.

@tahmidefaz Do you have any concerns? Does it seem right to you? If so, I’d check the tests, possibly write a one or two more, and close this up.

2020-10-02 13:16 UTC, tahmidefaz commented
@Glutexo Works for me. Thank you!

2020-10-02 17:00 UTC, ryandillinfelton commented on tests/test_unit.py
> +        self.assertEqual(original, payload)
Okay, I understand now.

2020-10-05 12:53 UTC, Glutexo commented
So I did exactly what I advertised: changed the field name in the specification file. It’s now _base_url_ all the way. I also write tests for the described behavior, so it’s not „just happening by accident“, but it’s codified as expected behavior.

- The `format: uri` from the specification is not used, invalid urls pass. This is how it is, Connexion ignores the rule.
- Length constraints are applied by Connexion. This should have been there from ever since, we tested this for MQ already.
- _baseurl_ is neither validated nor saved by neither HTTP nor MQ. It is just ignored, not rejected, even if it’s invalid.

I am going to merge this. There are no changes to the code apart of the name change that has been already approved at least by @tahmidefaz. Some tests were added, but no were removed or changed, so there is no chance for an unsafe unreviewed existing test case change to be introduced.

2020-10-05 14:29 UTC, Glutexo commented
Tests pass, even the new one! All I need here is @ryandillinfelton’s re-review.

2020-10-05 14:35 UTC, tahmidefaz approved these changes
Giving this an LGTM, but we should wait for @ryandillinfelton before we merge this. :+1:

2020-10-05 14:44 UTC, ryandillinfelton approved these changes
Looks good now :100:

2020-10-05 16:46 UTC, merged