[WIP] Add sap_system filter
RedHatInsights/insights-host-inventory pull request #717
Opened 2020-09-25 04:55 UTC by ryandillinfelton

Adds the ability to filter bulk host queries by the sap_system field when using xjoin as the data source.

Because the filtering only works with xjoin as the data source the tests are really is just checking the filter query parameter validation. 

Some things left todo before ready for review:

- [ ] Negative test

- [ ] Verify that 503 is the correct response to use when users try to use filer with DB as data source

2020-09-25 14:11 UTC, ryandillinfelton commented
Flake8 passes locally but detects problems when run here. I'll fix them, but does anyone know why that might be happening?

2020-09-25 14:28 UTC, kruai reviewed
I guess I really just have comments... I don't feel qualified to give this a full review just yet

2020-09-25 14:28 UTC, kruai commented on api/host_query_xjoin.py
> +        return ({"NOT": {"OR": [{"spf_sap_system": {"is": True}}, {"spf_sap_system": {"is": False}}]}},)
This line looks like it has this logic (I'm shortening `spf_sap_system` to `spf`):
`!(spf || !spf)` => `!spf && spf` => `false`
Is this line intended to always return false, as long as `spf_sap_system` is defined?

2020-09-25 14:28 UTC, kruai commented on api/host_query_xjoin.py
> +        return ({"OR": [{"spf_sap_system": {"is": True}}, {"spf_sap_system": {"is": False}}]},)
This line looks like it always returns true if `spf_sap_system` is defined. Is there simpler syntax for this?

2020-09-25 15:05 UTC, ryandillinfelton commented on api/host_query_xjoin.py
> +        return ({"OR": [{"spf_sap_system": {"is": True}}, {"spf_sap_system": {"is": False}}]},)
I just pushed a change simplifying both :+1:

2020-09-28 19:32 UTC, thearifismail commented
/LGTM

2020-09-28 20:41 UTC, kruai approved these changes

2020-09-29 14:12 UTC, tahmidefaz commented on tests/test_api_hosts_get.py
> +DATA_SOURCE_XJOIN_HEADER = {"x-rh-cloud-bulk-query-source": "xjoin"}
@ryandillinfelton I don't know much about x-join, tbh. Can you tell me a little bit about the implication of this header?

2020-09-29 14:19 UTC, ryandillinfelton commented on tests/test_api_hosts_get.py
> +DATA_SOURCE_XJOIN_HEADER = {"x-rh-cloud-bulk-query-source": "xjoin"}
This header tells the API to use xjoin search as a data source for queries instead of the database. In this case the `sap_system` filter is not supported on the `host_query_db.py` `get_host_list` function (it will return a 400), so adding this header to a request makes sure we're testing the `host_query_xjoin.py` which has logic for the filter. All of the deployed environments use xjoin as the data source by default now so we don't need to mirror the functionality with the database (according to Jozef)

2020-09-29 14:26 UTC, ryandillinfelton commented on tests/test_api_hosts_get.py
> +DATA_SOURCE_XJOIN_HEADER = {"x-rh-cloud-bulk-query-source": "xjoin"}
I just swapped it to use a fixture that does the same thing. Cleaner that way.

2020-09-29 18:15 UTC, tahmidefaz commented on api/host_query_xjoin.py
> +            if filter["system_profile"].get("sap_system"):
Is doing so fail anything for us (no idea)? It might be a little more concise? I fine either ways, tbh :slightly_smiling_face: 
`if filter.get("system_profile").get("sap_system"):`

2020-09-29 18:47 UTC, tahmidefaz requested changes
Can we add tests to check whether we are generating the correct graphql query?

2020-09-29 20:56 UTC, ryandillinfelton commented
@tahmidefaz I added the tests you requested :rocket:

2020-09-30 12:34 UTC, jharting commented on api/host_query_db.py
> +        flask.abort(400)
if we happen to run in db mode that's not really a client error. In /tags we abort with 503 https://github.com/RedHatInsights/insights-host-inventory/blob/master/api/tag.py#L71

Also, in this situation might be better to abort before doing a db query, not after.

2020-09-30 12:36 UTC, tahmidefaz approved these changes

2020-09-30 12:40 UTC, jharting reviewed
Looks good. Note that the filter should also go to /tags (https://github.com/RedHatInsights/insights-host-inventory/blob/master/api/tag.py#L60) (not necessarily in the same PR).

2020-09-30 15:43 UTC, ryandillinfelton commented
> Looks good. Note that the filter should also go to /tags (https://github.com/RedHatInsights/insights-host-inventory/blob/master/api/tag.py#L60) (not necessarily in the same PR).

Noted! I'll fold it in with the sap_sids filter PR when it's ready

2020-09-30 17:59 UTC, thearifismail approved these changes

2020-10-01 08:14 UTC, fstavela commented on api/host_query_xjoin.py
> +            if filter["system_profile"].get("sap_system"):
This could result in an attribute error if `filter` didn't have "system_profile" key, because we would be trying to do `.get("sap_system")` on a `None`. What we could do, is set the defaults for the get method to empty dictionaries, like this:
`if filter.get("system_profile", {}).get("sap_system")`
But probably a better way to do this would be to use try/except:
```python3
try:
    if isinstance(filter["system_profile"]["sap_system"], str):
        query_filters += _sap_system_filters(filter["system_profile"]["sap_system"])
    else:
        query_filters += _sap_system_filters(filter["system_profile"]["sap_system"]["eq"])
except (TypeError, KeyError):
    pass
```
We would get rid of a lot of nested ifs this way, which would be cleaner for now, but I think this might make the code less expendable. Especially because we might need those nested ifs in the future, when we start using more `filter` and `system_profile` parameters.

2020-10-01 17:47 UTC, merged