WIP: Ultra-Light Check-In
RedHatInsights/insights-host-inventory pull request #720
Opened 2020-09-28 18:56 UTC by kruai

This is WIP, and should not even be considered for merging yet. I'm opening this so that I can better ask for assistance.

This PR is meant to address [RHCLOUD-9412](https://issues.redhat.com/browse/RHCLOUD-9412).

This adds a POST endpoint that accepts a list of canonical facts and a time offset (in minutes). Given the list of canonical facts, it should find one specific host, and update its staleness timestamp using the supplied time offset.

2020-09-28 19:03 UTC, tahmidefaz commented
@kruai since we are only updating a portion of the host data, I am thinking a `PATCH` maybe the correct method to use rather than a `POST`?

2020-09-28 19:22 UTC, thearifismail commented
@kruai tests?

2020-09-28 20:26 UTC, kruai commented
> @kruai since we are only updating a portion of the host data, I am thinking a `PATCH` maybe the correct method to use rather than a `POST`?

There was a lot of discussion on this, actually; the general consensus was to make it a `POST`. I think the reasoning was that we're adding a new check-in/heartbeat. 

> @kruai tests?
I'll add those once I actually have finished code lmao

2020-10-01 15:09 UTC, jharting requested changes
@kruai don't forget to emit an `updated` event for any host state change

2020-10-01 17:18 UTC, kruai commented
> @kruai don't forget to emit an `updated` event for any host state change

Didn't realize that was a thing! Will do.



> is there a test attempting to cull a host with timedelta < 14 days?

There are so many tests it's hard for me to answer this, but I also don't know if that's relevant to this PR! Unless you're asking if I've added tests for my check-in endpoint that set the culling timestamp at less than 14 days... to which the answer is no

2020-10-01 18:08 UTC, lphiri commented
@jharting @kruai  - how would this behave if the canonical facts passed in did not match any hosts?
Would this create a new host entry?  I am assuming we do not want this to be backdoor for adding hosts via the REST API,
which was recently removed.

2020-10-01 18:17 UTC, kruai commented
> @jharting @kruai - how would this behave if the canonical facts passed in did not match any hosts?
> Would this create a new host entry? I am assuming we do not want this to be backdoor for adding hosts via the REST API,
> which was recently removed.

At the moment, this scenario errors out with my code. I can add a check to return a 400 response if a matching host isn't found. Does that work?

2020-10-02 20:55 UTC, lphiri commented
> > @jharting @kruai - how would this behave if the canonical facts passed in did not match any hosts?
> > Would this create a new host entry? I am assuming we do not want this to be backdoor for adding hosts via the REST API,
> > which was recently removed.
> 
> At the moment, this scenario errors out with my code. I can add a check to return a 400 response if a matching host isn't found. Does that work?

@kruai yes, returning a 400 works

2020-10-02 21:04 UTC, kruai commented
I need to debug to figure out why my my new test's requests are returning 400. I think it might have something to do with the Insights ID or Account atm

2020-10-06 20:00 UTC, tahmidefaz requested changes
In addition to the test, I also have the following questions/suggestions:

* When I sent out the following invalid JSON object, I get a `500`. I think it should throw a `4xx` or something else
```
{
	"canonical_facts": {"insights_id": "3f01b55457674041b75e41829bcee1dc"}
}
```
* When I sent a request with `staleness_offset: 60`, the `staleness_warning_timestamp` shrunk, but the `culled_timestamp` grew to 1 hour in the future. Is this expected behavior?

2020-10-06 20:47 UTC, kruai commented on tests/test_api_hosts_update.py
> +
For sure! I'll re-request your review once I add that test and make some fixes. Thank you

2020-10-06 20:52 UTC, kruai commented
> * When I sent a request with `staleness_offset: 60`, the `staleness_warning_timestamp` shrunk, but the `culled_timestamp` grew to 1 hour in the future. Is this expected behavior?

I'm actually not sure what people are expecting for the other timestamps tbh. My goal was to push only the `stalness_timestamp` back, but I'm not aware of how this should affect other timestamps. How have these been handled in the past @tahmidefaz ?

2020-10-06 21:10 UTC, ryandillinfelton commented
> > * When I sent a request with `staleness_offset: 60`, the `staleness_warning_timestamp` shrunk, but the `culled_timestamp` grew to 1 hour in the future. Is this expected behavior?
> 
> I'm actually not sure what people are expecting for the other timestamps tbh. My goal was to push only the `stalness_timestamp` back, but I'm not aware of how this should affect other timestamps. How have these been handled in the past @tahmidefaz ?

The other timestamps are just a fixed offset away from the base `staleness_timestamp`. You can create the whole set of updated timestamps using the base one and the functions defined [here](https://github.com/RedHatInsights/insights-host-inventory/blob/master/app/culling.py#L25). Here's an [example of them being updated](https://github.com/RedHatInsights/insights-host-inventory/blob/master/app/queue/queue.py#L101).

2020-10-06 23:12 UTC, gmcculloug commented on api/host.py
> +    staleness_offset = body.get("staleness_offset")
@kruai I'm thinking this parameter should be something like `checkin_frequency` for the caller.  If we use it to determine the `staleness_offset` would be an internal decision for the app.  At the moment we may not use it to adjust to staleness_timestamp, but instead to keep track of the next expected checkin.  This allows a caller to use that information to determine how late a system is for a checking in.

Thoughts?

2020-10-07 15:15 UTC, kruai commented on api/host.py
> +    staleness_offset = body.get("staleness_offset")
That works for me, especially if this value is also going to affect the other timestamps.

2020-10-07 16:24 UTC, kruai commented
> > > * When I sent a request with `staleness_offset: 60`, the `staleness_warning_timestamp` shrunk, but the `culled_timestamp` grew to 1 hour in the future. Is this expected behavior?
> > 
> > 
> > I'm actually not sure what people are expecting for the other timestamps tbh. My goal was to push only the `stalness_timestamp` back, but I'm not aware of how this should affect other timestamps. How have these been handled in the past @tahmidefaz ?
> 
> The other timestamps are just a fixed offset away from the base `staleness_timestamp`. You can create the whole set of updated timestamps using the base one and the functions defined [here](https://github.com/RedHatInsights/insights-host-inventory/blob/master/app/culling.py#L25). Here's an [example of them being updated](https://github.com/RedHatInsights/insights-host-inventory/blob/master/app/queue/queue.py#L101).

It took me a while to realize that only the staleness_timestamp is stored, and the other 2 timestamps are only generated while outputting (during serialization). I've changed it up so that I modify the staleness_timestamp and use the default config for output

2020-10-07 16:26 UTC, kruai commented on tests/test_api_hosts_update.py
> +
I assumed that defining a default value in `api.spec.yml` would make it supply the value in `host.py`, but I guess that was wrong. I'm now defaulting the value of checkin_frequency if it isn't passed in

2020-10-07 20:28 UTC, tahmidefaz requested changes
I think there's still an issue with the timestamp fields. 
I had a host with the following timestamps:
```
"stale_timestamp": "2020-11-03T06:20:08+00:00",
"stale_warning_timestamp": "2020-11-10T06:20:08+00:00",
"culled_timestamp": "2020-11-17T06:20:08+00:00",
```
Then, I updated it with `staleness_offset: 60`. This updated the host to have: 
```
"stale_timestamp": "2020-11-03T07:20:08+00:00",
"stale_warning_timestamp": "2020-11-03T08:20:08+00:00",
"culled_timestamp": "2020-11-17T07:20:08+00:00",
```
The `culled_timestamp` value looks good, however, the `stale_warning_timestamp` is incorrect. I think it should be `"2020-11-10T07:20:08+00:00"`. Can you repro this? I am not sure where exactly you need to make this change. You might need to do some digging :slightly_smiling_face:

2020-10-07 20:48 UTC, tahmidefaz approved these changes
Ok, I think these changes are LGTM. However, I would feel much comfortable with at least 1 more :heavy_check_mark: before merging :smile:

2020-10-08 14:04 UTC, kruai commented
@jharting @ryandillinfelton @subpop @gravitypriest @lphiri @iphands: Any of you wanna weigh in before it's merged?

2020-10-12 13:50 UTC, gmcculloug commented
@jharting @subpop @gravitypriest Would really appreciate getting your review on this PR.  Thanks

2020-10-12 13:56 UTC, subpop commented
I don't feel I can give an overall LGTM as I am not familiar with the project codebase, but the API interface that the client will be interacting with LGTM.

2020-10-12 16:08 UTC, thearifismail commented
> There are so many tests it's hard for me to answer this, but I also don't know if that's relevant to this PR! Unless you're asking if I've added tests for my check-in endpoint that set the culling timestamp at less than 14 days... to which the answer is no

IMO, this test is relevant.  Since its relevance spreads beyond this PR, this PR should be not be blocked.

2020-10-12 16:09 UTC, thearifismail approved these changes
LGTM.  All tests executed successfully.

2020-10-12 16:44 UTC, kruai commented
I don't have the option to dismiss @jharting 's review requesting changes (or the ability to re-request a review), so I'm going to need @tahmidefaz or @ryandillinfelton to merge this

2020-10-12 18:49 UTC, iphands approved these changes
Testing

2020-10-12 20:58 UTC, ryandillinfelton approved these changes
LGTM

2020-10-12 21:12 UTC, kruai commented
@ryandillinfelton @tahmidefaz I'm not allowed to merge it... can you?
Or do we have to wait for @jharting to update his review?

2020-10-12 21:53 UTC, gmcculloug commented
@iphands The other week you were thinking that the `staleness` timestamp should just be bumped by the default internal (1 day) during the ultra-light check-in instead of the check-in frequency value.  Is that still what you are thinking you want?

If I'm reading the code, and PR description, correctly we are still using the [check-in frequency with an default of 1 day]( https://github.com/RedHatInsights/insights-host-inventory/pull/720/files#diff-a5c55b46cc9c536070cb56798c97adfaR452).

I had made reference to this previously in https://github.com/RedHatInsights/insights-host-inventory/pull/720#discussion_r500647020 which is easily missed.

2020-10-13 11:16 UTC, jharting commented on tests/test_api_hosts_update.py
> +    expected_stale_timestamp = original_timestamp + timedelta(minutes=checkin_frequency)
I don't think this is correct. The stale_timestamp should not be set to previous stale_timestamp + checkin_frequency. e.g. if stale_timestamp is set to 1 month into the future and checkin_frequence is 60 minutes the outcome shouldn't be 1 month + 60 minutes. Instead, stale_timestamp should be set to now() + 60 minutes, i.e. if the host does not do another "ultralight" check-in 60 minutes from now it is considered stale.

2020-10-13 11:22 UTC, jharting requested changes
I don't think that the implemented logic matches the expected behavior (see inline comment).

Moreover, I did not find any test coverage for the updated event emitted on host checkin. Manual testing revealed problems with the event payload.

2020-10-13 11:22 UTC, jharting commented on api/host.py
> +        _emit_patch_event(serialized_host, host_id, insights_id)
The produced event is not correct. It is missing host tags, system_profile and request_id information.

2020-10-13 11:50 UTC, jharting commented on lib/host_repository.py
> +            {"insights_id": existing_host.canonical_facts["insights_id"]},
what if the host does not have insights_id?

2020-10-13 14:22 UTC, kruai commented on lib/host_repository.py
> +            {"insights_id": existing_host.canonical_facts["insights_id"]},
Oh, I thought they all had to have `insights_id`. Guess I'll need to revise this

2020-10-13 15:49 UTC, kruai commented on api/host.py
> +        _emit_patch_event(serialized_host, host_id, insights_id)
I'm not sure what I'm doing wrong here... I'm using the function in the exact same way as `patch_by_id`. Looking into it, though

2020-10-13 15:56 UTC, kruai commented on tests/test_api_hosts_update.py
> +    expected_stale_timestamp = original_timestamp + timedelta(minutes=checkin_frequency)
Oh, okay. I can change it to do that

2020-10-13 19:00 UTC, kruai commented on tests/test_api_hosts_update.py
> +    expected_stale_timestamp = original_timestamp + timedelta(minutes=checkin_frequency)
Updated

2020-10-13 19:49 UTC, kruai commented on lib/host_repository.py
> +            {"insights_id": existing_host.canonical_facts["insights_id"]},
I'm now passing in the existing canonical facts instead of assuming that `insights_id` exists.

2020-10-13 21:21 UTC, kruai commented on api/host.py
> +        _emit_patch_event(serialized_host, host_id, insights_id)
The only thing I could think of is to set "update_system_profile" to true, but I'm not sure how to test the produced events yet. Got any idea what I could be missing here?

2020-10-14 13:00 UTC, jharting commented on lib/host_repository.py
> +        input_host = Host(
I think that rather than creating new Host() and then calling `update_existing_host` (which is used to update the entire host on upload) it would be better to do

```
existing_host._update_stale_timestamp()
db.session.commit()
```
i.e. update the field(s) you need and commit the session.

Then, not unlike in the PATCH case, serialize the representation and emit the event
https://github.com/RedHatInsights/insights-host-inventory/blob/master/api/host.py#L306

2020-10-14 13:02 UTC, jharting commented on lib/host_repository.py
> +        input_host = Host(
Note that it might be a good idea to define a specific reporter for these ultralight checkins. (As otherwise we risk confusion as of why this host with reporter yupana has stale_timestamp that yupana would never set?)

2020-10-14 15:25 UTC, kruai commented on lib/host_repository.py
> +        input_host = Host(
OK... What value makes sense for this new reporter value, then? Should I just make one up, and call it "heartbeat" or "checkin" or something? I'd like @gmcculloug and @iphands opinions on this one

2020-10-14 15:30 UTC, jharting commented on lib/host_repository.py
> +        input_host = Host(
Yes, I think we should define a new reporter value. Either of the examples you used looks good to me.

2020-10-14 20:48 UTC, kruai commented on lib/host_repository.py
> +        input_host = Host(
I've made the requested changes. Afterwards, the function in host_repository didn't seem necessary, so I've consolidated the code into the function in host.py.
I'm marking this as "resolved" to show that I've addressed these concerns, but please un-resolve it if there's something I missed.

2020-10-14 21:48 UTC, kruai commented on api/host.py
> +        _emit_patch_event(serialized_host, host_id, insights_id)
It now functions nearly identically to the PATCH call. Can you please un-resolve this if you're still seeing the issue?

2020-10-15 07:07 UTC, jharting approved these changes
Functionality-wise looks good to me. I made a few improvements to the tests.

2020-10-15 13:27 UTC, kruai commented
Awesome, thank you!! I'll resolve the merge conflict(s) and merge.

2020-10-15 13:55 UTC, merged

2020-10-26 09:56 UTC, Glutexo reviewed
I found a bug in the schema. There is a field that should contain canonical facts, but it’s schema is defined as Host facts. The fact that this went unnoticed also points to a fact that this is not tested.

2020-10-26 09:56 UTC, Glutexo commented on swagger/api.spec.yaml
> +          $ref: '#/components/schemas/Facts'
This is not _canonical facts_, but _facts_.

2020-10-29 08:29 UTC, Glutexo reviewed
One more comment to the schema. The new _CreateCheckIn_ schema is the only place in the 
whole specification where Canonical Facts is explicitly mentioned. We don’t expose this concept; for the outside world, these are first class properties of a Host object. Thus I don’t think it is correct to break this concept in the new endpoint.

I’d say, just put them in the root CreateCheckIn schema. _Flat is better than nested._ I personally like nested more, and even here, we could just call it like _host_ instead of _canonical_facts_, but it would be inconsistent.

```yaml
CreateCheckIn:
  …
  properties:
    insights_id: …
    suscription_manager_id: …
    …
    checkin_frequency: …
```

Of course, my suggestion to DRY the Canonical Facts property set to an extracted schema and use it here still applies. It would require to use the _allOf_ JSON Schema combinator.

2020-10-29 12:00 UTC, Glutexo reviewed
Is it correct to return _400 Bad Request_ when there is no matching host found? I’d expect _404 Not Found_ instead. I thought that _400 Bad Request_ should occur only if the request is malformed.

Gave this a second thought after reading https://stackoverflow.com/a/44915434/1307676. That use case is however slightly different from ours. Trying to wrap my head around our check-in, I imagine that the request consists of two parts: ⑴ matching the host and ⑵ writing the check-in data. No matter whether we consider this to be a new Check-in resource operation, or a direct Host update, it could be split into two requests: ⑴ would match the host and either redirect or bail out with _404 Not Found_. ⑵ would return _200 OK_ or _201 Created_ depending on the semantics.

2020-10-29 12:19 UTC, rafaelcassau commented on api/host.py
> +        return flask_json_response(serialized_host, 201)
I think return 200 is more accurate in this context, 201 is commonly used when a new resource was created.

2020-10-29 12:20 UTC, Glutexo commented on api/host.py
> +        return flask_json_response(serialized_host, 201)
That’s questionable. We may consider this being a new (virtual) check-in resource, not a direct modification of the Host. In that case, we should be using POST and not PUT. Even if we consider this to be a Host operation, PUT is still not appropriate – PATCH is.

2020-10-29 12:21 UTC, rafaelcassau commented on api/host.py
> +            status=400,
maybe 404 fits better than 400 in this scenario.

2020-10-29 12:23 UTC, Glutexo commented on api/host.py
> +            status=400,
Great point! Please see my comment above and tell me what you think! https://github.com/RedHatInsights/insights-host-inventory/pull/720#pullrequestreview-519590906

2020-10-29 12:29 UTC, rafaelcassau commented on api/host.py
> +        return flask_json_response(serialized_host, 201)
yes, I'll argue about PATCH instead PUT because it just update a part of a host object instead of the whole object, I agree with you about semantic, I prefer to use PATCH but POST can be also considered.

2020-10-29 12:48 UTC, rafaelcassau commented
> Is it correct to return _400 Bad Request_ when there is no matching host found? I’d expect _404 Not Found_ instead. I thought that _400 Bad Request_ should occur only if the request is malformed.
> 
> Gave this a second thought after reading https://stackoverflow.com/a/44915434/1307676. That use case is however slightly different from ours. Trying to wrap my head around our check-in, I imagine that the request consists of two parts: ⑴ matching the host and ⑵ writing the check-in data. No matter whether we consider this to be a new Check-in resource operation, or a direct Host update, it could be split into two requests: ⑴ would match the host and either redirect or bail out with _404 Not Found_. ⑵ would return _200 OK_ or _201 Created_ depending on the semantics.

I agree with you, it's a hard trade off, my point is, I agree 404 is related with the resource, but I always prefer to return more meaningful status code to the client, from the HTTP verb perspective 404 is not the best choice, but I think 400 is too generic, according with mozilla definition maybe 422 can be a better choice, what do you think?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422

2020-10-29 13:13 UTC, Glutexo commented on api/host.py
> +        return flask_json_response(serialized_host, 201)
It all depends on whether we consider the check-in to be a new resource.

- If yes: then it should be POST. We **create** a new object that internally manifests as a host stale timestamp update.
- If no: it should be PATCH, because PATCH provides a subset of object information, whereas PUT replaces the entire object.

After a discussion with Greg we both think that the former is correct. This is not an immediate patch, because we don’t provide new Host stale timestamp. We provide some information that the Inventory **uses** to calculate the new timestamp.

Does this make sense?

2020-10-29 13:21 UTC, rafaelcassau commented on api/host.py
> +        return flask_json_response(serialized_host, 201)
> It all depends on whether we consider the check-in to be a new resource.
> 
> * If yes: then it should be POST. We **create** a new object that internally manifests as a host stale timestamp update.
> * If no: it should be PATCH, because PATCH provides a subset of object information, whereas PUT replaces the entire object.
> 
> After a discussion with Greg we both think that the former is correct. This is not an immediate patch, because we don’t provide new Host stale timestamp. We provide some information that the Inventory **uses** to calculate the new timestamp.
> 
> Does this make sense?

yes, make sense, in this case we need to change the verb and we can maintain with 201 status code.

2020-10-29 13:23 UTC, Glutexo commented
@rafaelcassau If we consider the Check-in to be bound to a specific Host, we can translate it (virtually or physically) into the match and update parts. Like that the Check-in create would be equivatlent to _POST /host/{host_id}/check-in_, in which case 404 Not Found would be the most appropriate choice.

I however agree that _422 Unprocessable Entity_ sounds nice and the description fits kind of. [Here](https://stackoverflow.com/a/44915434/1307676) though, one user says that this is a special-purpose status code introduced as a WebDAV extension and it is not thus a wise choice for a simple HTTP REST operation.

In conclusion, I’d go with

- _404 Not Found_ if Check-in is considered a new resource.
- _422 Unprocessable Entity_ or _400 Bad Request_ if Check-in is considered a patch on a Host.

As already mentioned above, I am more in favor of the former.

2020-10-29 13:38 UTC, kruai commented
Y'all are leaving so many useful comments which would have been great before this merged 2 weeks ago :sweat_smile: 
I'm going to have to respond to most of this once I'm out of meetings; however, on the topic of POST vs PATCH, I'd lean towards PATCH. I have to squint really hard to see this thing as a "create" operation, especially since it's explicitly only an update on the code side

2020-10-29 13:42 UTC, kruai commented
> One more comment to the schema. The new _CreateCheckIn_ schema is the only place in the
> whole specification where Canonical Facts is explicitly mentioned. We don’t expose this concept; for the outside world, these are first class properties of a Host object. Thus I don’t think it is correct to break this concept in the new endpoint.
> 
> I’d say, just put them in the root CreateCheckIn schema. _Flat is better than nested._ I personally like nested more, and even here, we could just call it like _host_ instead of _canonical_facts_, but it would be inconsistent.
> 
> ```yaml
> CreateCheckIn:
>   …
>   properties:
>     insights_id: …
>     suscription_manager_id: …
>     …
>     checkin_frequency: …
> ```
> 
> Of course, my suggestion to DRY the Canonical Facts property set to an extracted schema and use it here still applies. It would require to use the _allOf_ JSON Schema combinator.

I get what you mean - the host creation API is already deprecated, so I may as well delete the CreateHostIn schema, and just use the flat CreateCheckIn schema. Am I understanding you correctly?

2020-10-29 13:43 UTC, rafaelcassau commented
> @rafaelcassau If we consider the Check-in to be bound to a specific Host, we can translate it (virtually or physically) into the match and update parts. Like that the Check-in create would be equivatlent to _POST /host/{host_id}/check-in_, in which case 404 Not Found would be the most appropriate choice.
> 
> I however agree that _422 Unprocessable Entity_ sounds nice and the description fits kind of. [Here](https://stackoverflow.com/a/44915434/1307676) though, one user says that this is a special-purpose status code introduced as a WebDAV extension and it is not thus a wise choice for a simple HTTP REST operation.
> 
> In conclusion, I’d go with
> 
> * _404 Not Found_ if Check-in is considered a new resource.
> * _422 Unprocessable Entity_ or _400 Bad Request_ if Check-in is considered a patch on a Host.
> 
> As already mentioned above, I am more in favor of the former.

agree