[WIP] Add delete handling for rbac-inventory
RedHatInsights/insights-host-inventory pull request #721
Opened 2020-09-28 20:57 UTC by thearifismail

Added delete handler to implement the CRUD methods for rbac-inventory config

2020-09-28 21:02 UTC, ryandillinfelton commented on lib/middleware.py
> +                    or rbac_permission["permission"] == required_permission.value  # inventory:hosts:(read | write| delete)
I know I added these comment, but do y'all actually find them helpful or are they just clutter? I'm a bit partial to removing them, doesn't have to happen in the this PR though (sorry this is a little off-topic, just came to mind while I was reviewing).

2020-09-28 21:09 UTC, thearifismail commented on lib/middleware.py
> +                    or rbac_permission["permission"] == required_permission.value  # inventory:hosts:(read | write| delete)
I found them helpful.  So no harm in leaving them in

2020-09-28 21:09 UTC, kruai commented on lib/middleware.py
> +                    or rbac_permission["permission"] == required_permission.value  # inventory:hosts:(read | write| delete)
Personally, it's a bit of both. It's helpful to me as a newcomer, but it's also more cluttered/harder on the eyes. I'm fine with it being removed

2020-09-28 21:09 UTC, ryandillinfelton requested changes
Just one small change needed, otherwise LGTM.

I did want to comment on the coverage change though. I doubt it will be a problem, but we are no longer covering every permutation of permissions possible.

We should explore a solution to the problem in the future because I don't think it's practical to keep creating a bunch of mock response files for every possible combination of permissions a user could have. I don't think it's urgent to address though, it seems unlikely we'd have a bug that wouldn't get caught in these tests.

2020-09-28 21:09 UTC, ryandillinfelton commented on tests/helpers/api_utils.py
> +    "utils/rbac-mock-data/inv-write-only.json"
Write only is in here twice

2020-09-28 21:30 UTC, ryandillinfelton commented
Try running `make style` and then enabling the pre-commit hook with `pre-commit install`

2020-09-28 21:49 UTC, ryandillinfelton approved these changes

2020-09-28 21:50 UTC, ryandillinfelton commented
Fix the style failure before this is merged, but it looks good outside of that

2020-09-29 12:40 UTC, tahmidefaz requested changes
Just requested some changes. Overall, it looks good to me. Please run `make style` like @ryandillinfelton suggested :slightly_smiling_face:

2020-09-29 12:40 UTC, tahmidefaz commented on tests/helpers/api_utils.py
>  )
`"utils/rbac-mock-data/inv-host-delete.json"` needs to be added to this list, as well as under `READ_PROHIBITED_RBAC_RESPONSE_FILES`

2020-09-29 12:40 UTC, tahmidefaz commented on utils/rbac-mock-data/inv-host-delete.json
> +}
`</nitpick>` might be better to rename this file as `inv-delete-only.json` to align with the other files in the directory, but it's not really a big issue. :slightly_smiling_face:

2020-09-29 12:43 UTC, tahmidefaz commented on lib/middleware.py
> +                    or rbac_permission["permission"] == required_permission.value  # inventory:hosts:(read | write| delete)
I agree that it's clutter. After some time, the variable names become intuitive enough that we don't really need those comments. :slightly_smiling_face:

2020-09-29 13:28 UTC, kruai commented
If the consensus ends up being that DELETE permission is the same as WRITE permission, do we still want to distinguish between them in Inventory?

2020-09-29 16:13 UTC, thearifismail commented
> If the consensus ends up being that DELETE permission is the same as WRITE permission, do we still want to distinguish between them in Inventory?

I don't think so.  For clarity, may be mention it somehwere.

2020-10-05 17:55 UTC, tahmidefaz commented
Closing this because we will be standardizing in `read` and `write` at the moment.

2020-10-05 17:55 UTC, closed without merging