Fix README api call examples
RedHatInsights/insights-host-inventory pull request #723
Opened 2020-09-30 18:06 UTC by rafaelcassau

Fix header base64 encoded parameter to consider the new payload key called type

2020-09-30 18:50 UTC, gmcculloug commented on README.md
> +This is the Base64 enconding the following JSON document:
Small typo in "encoding" here and dropped the "of" from the sentence.

Should read: `This is the Base64 encoding of the following JSON document:`

2020-09-30 18:50 UTC, gmcculloug commented on README.md
> +echo '{"identity": {"account_number": "0000001", "type": "System", "internal": {"org_id": "000001"}}}' | base64
Much better than using a website to encode.  👍

2020-09-30 18:53 UTC, kruai requested changes

2020-09-30 18:53 UTC, kruai commented on README.md
> +instead of "User":
I'd update the grammar to something like this:
`The above is an example with type "User". It's possible to use "System" as a parameter
instead of "User":`

2020-09-30 18:53 UTC, kruai commented on README.md
> +If you want to encode other JSON document you can use command example bellow:
"bellow" should be "below"

2020-09-30 19:05 UTC, thearifismail commented on README.md
> +If you want to encode other JSON document you can use command example bellow:
`LTGM` after fixing the issues identified by Greg and Asa

2020-09-30 19:18 UTC, ryandillinfelton requested changes
Just some small suggestions & typo fixes. Looks good otherwise. Thanks for updating this!

2020-09-30 19:18 UTC, ryandillinfelton commented on README.md
> +This is the Base64 enconding the following JSON document:
```suggestion
This is the Base64 encoding of the following JSON document:
```

2020-09-30 19:18 UTC, ryandillinfelton commented on README.md
> +If you want to encode other JSON document you can use command example bellow:
```suggestion
If you want to encode other JSON documents you can use command bellow:
```

2020-09-30 19:20 UTC, ryandillinfelton commented on README.md
> +The above one is an example with type "User", it's possible to use "System" as a parameter
Asa also suggested a change to this line, I'm happy with either, so whichever you go with is fine by me.

2020-09-30 19:21 UTC, ryandillinfelton commented on README.md
> +This is the Base64 enconding the following JSON document:
Just noticed this is a duplicate of what Greg commented. If you already addressed his ignore this.

2020-09-30 20:56 UTC, rafaelcassau commented
Thanks for all suggestions guys, those suggestions will help me a lot with my English, I always appreciate any kind of feedback.

@gmcculloug @ryandillinfelton @kruai @tahmidefaz @thearifismail

2020-09-30 22:43 UTC, gmcculloug approved these changes
LGTM 👍

2020-10-01 12:52 UTC, tahmidefaz requested changes

2020-10-01 12:52 UTC, tahmidefaz commented on README.md
> +If you want to encode other JSON documents you can use command below:
Just one suggestion. I am fine either way, to be honest. :slightly_smiling_face: 
```suggestion
If you want to encode other JSON documents, you can use the following command:
```

2020-10-01 12:57 UTC, tahmidefaz approved these changes
LGTM :+1:

2020-10-01 14:18 UTC, kruai requested changes
Great work! It just needs one more change :)

2020-10-01 14:18 UTC, kruai commented on README.md
> +The above header has the "User" identity `type`, it's possible to use a "System" `type` header as well.
This is almost correct! These need to either be 2 separate sentences or use a conjunction. So either:

- The above header has the "User" identity `type`. It's possible to use a "System" `type` header as well.
- The above header has the "User" identity `type`, but it's possible to use a "System" `type` header as well.

2020-10-01 16:25 UTC, kruai approved these changes
Looks great!

2020-10-01 16:52 UTC, ryandillinfelton approved these changes
LGTM! :100:

2020-10-01 16:52 UTC, merged