Add addtional SAP facts to system profile
RedHatInsights/insights-host-inventory pull request #731
Opened 2020-10-13 15:01 UTC by CodeHeeler

Pending schema PR: https://github.com/RedHatInsights/inventory-schemas/pull/25

2020-10-13 17:40 UTC, kruai approved these changes
LGTM, but would probably be safe to wait for an additional review from a veteran :)

2020-10-13 19:48 UTC, thearifismail commented
Question... What's the source of`maxLength` values for `sap_sid`, `sap_instance_number`, and `sap_version_info`?  How do I know that the maxLengths in `system_profile_spec` are correct, i.e. is there no chance of `sap_instance_number` being 3 char long?

2020-10-13 20:04 UTC, CodeHeeler commented
> @CodeHeeler, Question... What's the source of`maxLength` values for `sap_sid`, `sap_instance_number`, and `sap_version_info`? How do I know that the maxLengths in `system_profile_spec` are correct, i.e. is there no chance of `sap_instance_number` being 3 char long?

The source for the sap_instance_number is here:
https://help.sap.com/viewer/2c1988d620e04368aa4103bf26f17727/2.0.05/en-US/ae305ab18bad42efa7b067e7cc82b846.html

The source for the version number is an example from Bernd Finger in Red Hat and the example here as this is the output for --version:
https://answers.sap.com/questions/161894/hana-version-check.html

The source for the sid's being 3 is here:
https://help.sap.com/viewer/2c1988d620e04368aa4103bf26f17727/2.0.05/en-US/7672838aa9c44c7ab9d10188531669f3.html?q=sids

Anything longer is incorrect, so we can either make a longer length for cushion for incorrect values or we can validate here and correct reporters that are not using correct values, as with any of the other facts.

2020-10-13 20:21 UTC, thearifismail commented
> Anything longer is incorrect, so we can either make a longer length for cushion for incorrect values or we can validate here and correct reporters that are not using correct values, as with any of the other facts.

No don't need to make longer as it has lower potential for bugs.  Was just curious because `maxLength` for `sap_sid` and `sap_instane_number` appeared too small.  If adjustments is needed in future, it can be dealt with then.

LGTM

2020-10-13 20:21 UTC, thearifismail approved these changes

2020-10-21 18:25 UTC, ryandillinfelton approved these changes

2020-10-21 18:27 UTC, ryandillinfelton commented on swagger/system_profile.spec.yaml
> +        pattern: '(?!99)(?!98)^[0-9]{2}$'
Tahmid had a good improvement suggestion for this field https://github.com/RedHatInsights/inventory-schemas/pull/25/files#r509548114

2020-10-21 18:29 UTC, ryandillinfelton requested changes

2020-10-21 18:29 UTC, ryandillinfelton commented on app/models.py
> +        validate=[marshmallow_validate.Length(max=2), marshmallow_validate.Regexp(regex=r"(?!99)(?!98)^[0-9]{2}$")]
Using the [Range validation](https://www.programcreek.com/python/example/108225/marshmallow.validate.Range) method could make things cleaner here

2020-10-21 20:21 UTC, ryandillinfelton approved these changes

2020-10-22 14:13 UTC, ryandillinfelton approved these changes

2020-10-22 14:15 UTC, tahmidefaz approved these changes

2020-10-22 14:15 UTC, merged