[WIP] Add tags pagination
RedHatInsights/insights-host-inventory pull request #734
Opened 2020-10-21 21:37 UTC by thearifismail

this PR fixes the issue reported in https://issues.redhat.com/browse/RHCLOUD-9925

2020-10-21 22:18 UTC, ryandillinfelton commented on api/host.py
> +                i+=1
You should be able to just use pythons built in list subset selection to accomplish this
`paginated_tags = tags[(page-1)*per_page:page*per_page]` or something like that.

2020-10-21 22:32 UTC, ryandillinfelton commented on api/host.py
> +def _build_serialized_tags(host_list, search, page, per_page):
I'd like to see the name of this function changed to reflect that is paginates the results too.

2020-10-22 12:51 UTC, thearifismail commented on api/host.py
> +                i+=1
Done!!! Renamed the method to _build_paginated_tags.

2020-10-22 12:53 UTC, thearifismail commented on api/host.py
> +def _build_serialized_tags(host_list, search, page, per_page):
Renamed the method to _build_paginated_tags

2020-10-22 15:55 UTC, kruai requested changes
Had a couple questions. This also needs tests to be added or updated, but I know this is still in Draft status

2020-10-22 15:55 UTC, kruai commented on api/host.py
> +        tags = tags[(page-1)*per_page:page*per_page]
What happens when `page*per_page` > `len(tags)`? Hopefully this would be fine... I just don't know how python handles that particular array-slicing scenario

2020-10-22 18:39 UTC, ryandillinfelton commented on api/host.py
> +        tags = tags[(page-1)*per_page:page*per_page]
If stack overflow is to be believed it should be fine https://stackoverflow.com/questions/41166378/slice-to-index-or-end-if-end-is-lesser-then-index-python

2020-10-22 19:44 UTC, thearifismail commented on api/host.py
> +        tags = tags[(page-1)*per_page:page*per_page]
yes and upto 99 per_page worked. 100 threw 404.  I am assuming the 99 per_page limit is being set by the front end.

2020-10-29 00:15 UTC, thearifismail commented on api/host.py
> +    query = query.paginate(1, per_page, True)
this pagination call for paginating hosts NOT for tags. Tags can not use the paginate method because there is no table and are stored as json in `tags` column in `hosts` table.  This PR paginates tags by slicing a list of tags.

2020-10-29 00:16 UTC, thearifismail commented
/test

2020-10-29 00:17 UTC, thearifismail commented
[test]

2020-10-29 03:24 UTC, rafaelcassau commented on api/host.py
> +def _build_paginated_host_tags_count(total, page, per_page, tags_list):
I think those parameters: `total`, `page` and `per_page` aren't used here, right?

2020-10-29 03:27 UTC, rafaelcassau commented on api/host.py
> +    json_output = build_collection_response(tags_list, page, per_page, total)
I think `tags_list` parameter does not exist in this context, so maybe it should be `total` instead, because if this funcion will be called I think this will throw an `before assigment` exception

2020-10-29 21:14 UTC, kruai requested changes
I haven't reviewed the tests too thoroughly yet; I want to make sure I understand what you're trying to achieve with the code before I dig more into the tests.

2020-10-29 21:14 UTC, kruai commented on api/host.py
> +        all_tags_count = len(tags)
This is in a loop, so it will always be set to the number of tags owned by the last host in host_list

2020-10-29 21:14 UTC, kruai commented on tests/test_tags.py
>  def test_tags_count_pagination(mq_create_four_specific_hosts, api_get, subtests):
@thearifismail @ryandillinfelton was there agreement to change the format of the response for `get_host_tag_count`? Because on the master branch, that method appears to return a tag count per host, as a list of paginated hosts: https://github.com/RedHatInsights/insights-host-inventory/blob/fb670f19ac924d47506330b0e6dd374d4cfab592/api/host.py#L391
The Jira card mentioned in this PR's description didn't mention this method, so this seems out of scope.

2020-10-29 21:33 UTC, thearifismail commented on api/host.py
> +    query = query.paginate(1, per_page, True)
`query.paginate(...)` actually runs the query and fetch hosts. Could not find a way around it.  I tried to find an api call to fetch a host directly but could not find one.  

To find a host, like in ultralight-checkins method but it required one of the canonical-facts, which are not yet available.  So had to fall-back to this approach.

2020-10-29 22:17 UTC, thearifismail commented on tests/test_tags.py
>  def test_tags_count_pagination(mq_create_four_specific_hosts, api_get, subtests):
This was to be covered by https://issues.redhat.com/browse/RHCLOUD-10184, the need for which came up when Greg spotted the inconsistency related to what API returned.  As I was working through tags pagination, it looked an easy fix, so I went ahead.  Will work with @ryandillinfelton  when returns.

2020-10-29 22:18 UTC, thearifismail commented on api/host.py
> +    return flask_json_response(json_output)
Waiting for @ryandillinfelton, address in https://github.com/RedHatInsights/insights-host-inventory/pull/734#discussion_r514599574

2020-10-29 22:32 UTC, thearifismail commented on api/host.py
> +    return {"total": total, "count": tags_returned, "page": page, "max_per_page": per_page, "results": data}
Fixed !!!

2020-10-29 22:49 UTC, thearifismail commented on api/host.py
> +        logger.debug("All tags count: {}".format(all_tags_count))
Done!!!

2020-10-30 00:49 UTC, thearifismail commented on api/host.py
> +        all_tags_count = len(tags)
Did not realize that the specs defined output fields.  At the moment works only for one host in the request, which is what the defect is about. Dealing with multiple hosts get complicated.  Will try tomorrow and see many tests are affected by it.

2020-10-30 13:37 UTC, kruai commented on api/host.py
> +    query = query.paginate(1, per_page, True)
I believe you can just use query.all() to execute the query. We don't need to `filter()` again because it happens in `_get_host_list_by_id_list`, and we don't need to `limit()` because we're getting a set number of items, so I think `all()` is the way to go for this one.

2020-10-30 13:39 UTC, kruai commented on tests/test_tags.py
>  def test_tags_count_pagination(mq_create_four_specific_hosts, api_get, subtests):
Gotcha. If you want to address that in that PR as well, can you please update the description to indicate that?

2020-10-31 15:18 UTC, thearifismail commented on api/host.py
> +    query = query.paginate(1, per_page, True)
Done.  Using query.all() now.

2020-10-31 15:31 UTC, thearifismail commented on tests/test_tags.py
>  def test_tags_count_pagination(mq_create_four_specific_hosts, api_get, subtests):
Done!!!

2020-10-31 15:49 UTC, thearifismail commented on api/host.py
> +        tags_returned = len(tags)
Right now it shows only the last host because the current implementation of front-end passes in only one host.  According to Karyle Hala, "I don't think there's a place where you could list all tags for multiple hosts". I am going to get Josef Hartinger's input to see what he says and if there are other consumers or potential consumers, other than `inventory-front-end` and then respond accordingly.

2020-10-31 15:50 UTC, thearifismail commented on api/host.py
> +        all_tags_count = len(tags)
see https://github.com/RedHatInsights/insights-host-inventory/pull/734#discussion_r515509939

2020-10-31 15:50 UTC, thearifismail commented on api/host.py
> +    query = query.paginate(1, per_page, True)
Done!!!

2020-11-02 13:25 UTC, ryandillinfelton commented on api/host.py
> +    return flask_json_response(json_output)
I believe the front end needs to be able to request the tag counts for a list of hosts. They use it on the inventory front end to show how many tags each machine has in the list of hosts. This would break that functionality

2020-11-02 13:30 UTC, jharting commented on api/host.py
> +        tags_returned = len(tags)
> Right now it shows only the last host because the current implementation of front-end passes in only one host. According to Karyle Hala, "I don't think there's a place where you could list all tags for multiple hosts". I am going to get Josef Hartinger's input to see what he says and if there are other consumers or potential consumers, other than inventory-front-end and then respond accordingly.

If you open https://cloud.redhat.com/insights/inventory/ you'll see that the frontend is making a multi-host call to the tags endpoint. Even if it didn't, this is a public API and we cannot just change it's behavior like this.

2020-11-03 19:10 UTC, thearifismail commented on api/host.py
> +        tags_returned = len(tags)
@jharting, the defect [RHCLOUD-9925](https://issues.redhat.com/browse/RHCLOUD-9925) is about paginating through tags with their details NOT just hosts.  The [link](https://cloud.redhat.com/insights/inventory/) you provided lists number of tags againsts hosts.  An immediate fix for the defect is to update the UI to show all tags and remove:

1. remove "1 - 10 of 15
2. remove page numbers, and 
3. remove page navigation arrows.

<img width="681" alt="tags" src="https://user-images.githubusercontent.com/40067075/98028913-c4669580-1ddc-11eb-8070-cd428f10c2a3.png">


The other option is to implement tags pagination.  The tricky part is paginating through tags from multiple hosts with one page shows tags from multiple hosts.  Here is a request getting tag counts from 5 hosts:
`http://127.0.0.1:8080/api/inventory/v1/hosts/1478f9d8-b4d7-4d22-b9ea-306944a5975c,3b4db526-e9dc-42cf-98f6-c8b39c0f27c4,9b9e2ba9-3f61-4407-a393-c70eaea876ac,40e21077-277b-4117-af2b-f1792fe87ab9,70650f6c-ea6d-43e6-9dc1-daa3eaaf80d0/tags/count`
```yaml
{
    "total": 5,
    "page: ": 1,
    "per_page": 50,
    "results": {
        "1478f9d8-b4d7-4d22-b9ea-306944a5975c": 5,
        "3b4db526-e9dc-42cf-98f6-c8b39c0f27c4": 0,
        "9b9e2ba9-3f61-4407-a393-c70eaea876ac": 10,
        "40e21077-277b-4117-af2b-f1792fe87ab9": 15,
        "70650f6c-ea6d-43e6-9dc1-daa3eaaf80d0": 4
    }
}
```



Here are 3 scenarios for paginating through tags with expected JSONs.

**Scenario 1**: Show 10 tags on Page 1.  
```yaml
{
    "total": 34,
    "count": 10,
    "page": 1,
    "per_page": 10,
    "results": {
        "1478f9d8-b4d7-4d22-b9ea-306944a5975c": [
            {
                "namespace": "NS9",
                "key": "key9",
                "value": "val9"
            },
            {
                "namespace": "NS10",
                "key": "key10",
                "value": "val10"
            },
            {
                "namespace": "NS11",
                "key": "key11",
                "value": "val11"
            },
            {
                "namespace": "NS12",
                "key": "key12",
                "value": "val12"
            },
            {
                "namespace": "NS13",
                "key": "key13",
                "value": "val13"
            }
        ],
        "3b4db526-e9dc-42cf-98f6-c8b39c0f27c4": [],
        "9b9e2ba9-3f61-4407-a393-c70eaea876ac": [
            {
                "namespace": "NS1",
                "key": "key3",
                "value": "val3"
            },
            {
                "namespace": "NS2",
                "key": "key2",
                "value": "val2"
            },
            {
                "namespace": "NS3",
                "key": "key3",
                "value": "val3"
            },
            {
                "namespace": "NS4",
                "key": "key4",
                "value": "val4"
            },
            {
                "namespace": "NS5",
                "key": "key5",
                "value": "val5"
            },
        ]
    }
}
```


**Scenario 2**: Show 10 tags on Page 2
```yaml
{
    "total": 34,
    "count": 10,
    "page": 2,
    "per_page": 10,
    "results": {
        "9b9e2ba9-3f61-4407-a393-c70eaea876ac": [
            {
                "namespace": "NS6",
                "key": "key6",
                "value": "val6"
            },
            {
                "namespace": "NS7",
                "key": "key7",
                "value": "val7"
            },
            {
                "namespace": "NS8",
                "key": "key8",
                "value": "val8"
            },
            {
                "namespace": "NS9",
                "key": "key9",
                "value": "val9"
            },
            {
                "namespace": "NS10",
                "key": "key10",
                "value": "val10"
            }
        ],
        "40e21077-277b-4117-af2b-f1792fe87ab9": [
            {
                "namespace": "NS1",
                "key": "key3",
                "value": "val3"
            },
            {
                "namespace": "NS2",
                "key": "key2",
                "value": "val2"
            },
            {
                "namespace": "NS3",
                "key": "key3",
                "value": "val3"
            },
            {
                "namespace": "NS4",
                "key": "key4",
                "value": "val4"
            },
            {
                "namespace": "NS5",
                "key": "key5",
                "value": "val5"
            }
        ]
    }
}
```


**Scenario 3:** Show 10 tags on Page 4
```yaml
{
    "total": 34,
    "count": 4,
    "page": 1,
    "per_page": 10,
    "results": {
        "70650f6c-ea6d-43e6-9dc1-daa3eaaf80d0": [
            {
                "namespace": "NS1",
                "key": "key3",
                "value": "val3"
            },
            {
                "namespace": "NS2",
                "key": "key2",
                "value": "val2"
            },
            {
                "namespace": "Sat",
                "key": "prod",
                "value": null
            },
            {
                "namespace": "SPECIAL",
                "key": "key",
                "value": "val"
            }
        ]
    }
}
```

2020-11-04 16:15 UTC, thearifismail commented on api/host.py
> +        tags_returned = len(tags)
@jharting - can I close this PR because the JIRA card, [RHCLOUD-9925](https://issues.redhat.com/browse/RHCLOUD-9925) triggering this PR, has been assigned to @karelhala to fix the problem on the client side?

2020-11-05 16:44 UTC, thearifismail commented
Slack message response from @jharting "I suggest to close it and instead implement the fix in the UI component"

2020-11-05 16:44 UTC, closed without merging

2020-11-05 16:46 UTC, thearifismail commented
The tag pagination issue encountered on https://cloud.redhat.com/insights/inventory/ is to be fixed in the UI component.  Per @jharting "I suggest to close it and instead implement the fix in the UI component"