WIP: Ultra-Light Check-In bug fixes
RedHatInsights/insights-host-inventory pull request #735
Opened 2020-10-27 18:30 UTC by kruai

Addresses this Jira: https://issues.redhat.com/browse/RHCLOUD-10229

2020-10-27 22:26 UTC, kruai commented
@subpop @lphiri I know we discussed having a "staleness offset" value while we were planning this, but is there any harm in just supplying a staleness timestamp like you do on host creation? This PR standardizes on the existing schema for creating a host, so it's accepting a timestamp instead of an offset value.

2020-10-28 12:30 UTC, Glutexo commented
cc this question to @jharting  and @iphands .

2020-10-29 07:59 UTC, Glutexo commented
May I ask to split the schema fixes from the timestamps change? The former is clear, it’s just a bug in the specification and it is an easy fix. The latter is a change in semantics and may require some more discussion and waiting time not to break reporters. 🙇🏻‍♂️

2020-10-29 08:15 UTC, jharting commented
> is there any harm in just supplying a staleness timestamp like you do on host creation?

I think it's cleaner to let the client provide a "hint" on when the next check-in should be expected (which inventory then uses to compute the next timestamp) instead of giving the client the authority to define the stale timestamp directly.

2020-10-29 08:30 UTC, Glutexo commented
One more comment to the schema format. Please see my newest comment: https://github.com/RedHatInsights/insights-host-inventory/pull/720#pullrequestreview-519429624

2020-10-29 12:54 UTC, subpop commented
> > is there any harm in just supplying a staleness timestamp like you do on host creation?
> 
> I think it's cleaner to let the client provide a "hint" on when the next check-in should be expected (which inventory then uses to compute the next timestamp) instead of giving the client the authority to define the stale timestamp directly.

Agreed. During host creation, the timestamp is actually set by puptoo. In this case, the timestamp value is coming directly from the client. A clever client/user could manipulate the code to set the timestamp to whatever they want.

2020-10-29 13:34 UTC, kruai commented
> May I ask to split the schema fixes from the timestamps change? The former is clear, it’s just a bug in the specification and it is an easy fix. The latter is a change in semantics and may require some more discussion and waiting time not to break reporters. 🙇🏻‍♂️

Can you clarify what you mean by the timestamps change? If you're talking about the way staleness_timestamps is calculated, that was already merged in #720...

2020-11-02 16:48 UTC, Glutexo commented
@kruai Please split the changes to the API – HTTP verbs, response codes, request schemas – from the changes to the logic – calculating the timestamp instead of taking it from the request.

2020-11-02 17:00 UTC, kruai commented
> @kruai Please split the changes to the API – HTTP verbs, response codes, request schemas – from the changes to the logic – calculating the timestamp instead of taking it from the request.

OK, gotcha. Because of the restructuring that came from our latest conversation on Ultra-Light Check-In, that timestamp logic will no longer be a part of this (until Phase 2, once the requirements have been re-solidified). I'll unmark this as Draft once I've got everything in order for those changes

2020-11-02 22:53 UTC, gmcculloug commented on api/host.py
> +        existing_host.modified_on = datetime.now(timezone.utc)
Is this the same as calling `datetime.utcnow()`.  More a curiosity on my part as I see both used in this code base.

2020-11-03 13:15 UTC, Glutexo commented on api/host.py
> +        existing_host.modified_on = datetime.now(timezone.utc)
From the documentation ([link](https://docs.python.org/3.6/library/datetime.html#datetime.datetime.utcnow)):

> This […] returns the current UTC date and time, as a **naive** datetime object. An **aware** current UTC datetime can be obtained by calling `datetime.now(timezone.utc)`.

2020-11-03 14:54 UTC, Glutexo reviewed
Gave some suggestions, found some nice things which pleased me. 😃 I need to go run a Python lecture today, but I’ll check the rest tomorrow.

2020-11-03 14:54 UTC, Glutexo commented on api/host.py
> +                "title": "Not Found",
Thanks!

2020-11-03 14:54 UTC, Glutexo commented on app/serialization.py
> +    return _deserialize_canonical_facts(raw_data)
Don’t we want to run this through Marshmallow? I know that in the long run, we are trying to remove these Python schemas, but now it would be good to do this consistently. It should be easy to extract the canonical fact fields from _BaseHostSchema_ and use it here and make _BaseHostSchema_ inherit them.

2020-11-03 14:54 UTC, Glutexo commented on swagger/api.spec.yaml
> +    post:
Awesome!

2020-11-03 15:02 UTC, kruai commented on api/host.py
> +        existing_host.modified_on = datetime.now(timezone.utc)
Will do!

2020-11-03 15:10 UTC, kruai commented on api/host.py
> +        existing_host.modified_on = datetime.now(timezone.utc)
OK, moved it inside the Host definition

2020-11-03 15:15 UTC, kruai commented on app/serialization.py
> +    return _deserialize_canonical_facts(raw_data)
OK! I haven't done any inheritance with Python yet, but this is my chance to learn. Might take me a bit longer than the other fix, though :)

2020-11-04 10:24 UTC, Glutexo commented on app/serialization.py
> +    return _deserialize_canonical_facts(raw_data)
My idea is to have a canonical facts schema like

```python
class CanonicalFactsSchema(MarshmallowSchema):
    insights_id = fields.Str(validate=verify_uuid_format)
    …
```

and then it should be as simple as

```python
class BaseHostSchema(CanonicalFactsSchema):
    display_name = fields.Str(validate=marshmallow_validate.Length(min=1, max=200))
    …
```

2020-11-04 11:15 UTC, Glutexo requested changes
Second part. As repeated a few times in the in-line comments. Please don’t remove the create/update host by POST in this pull request. It is a big functional change that should be tested and merged separately. Thanks!

2020-11-04 11:41 UTC, Glutexo requested changes
I can’t approve this. There is a mistake in the test and also there is unrelated code. Apart from the _/hosts_ POST removal there is a bunch of unrelated System Profile and SAP tests.

2020-11-04 11:41 UTC, Glutexo commented on tests/test_api_hosts_update.py
> +    assert event_producer_mock.key == str(created_host.id)
This is already checked by the _assert_patch_event_is_valid_ method below. This line is thus redundant.

```suggestion
```

2020-11-04 11:41 UTC, Glutexo commented on tests/test_api_hosts_update.py
> +        record.stale_timestamp,
It’s strange to pass the stale timestamp and not the reporter. Both values fall back to the host’s value. We may however want to check that these values remain untouched. This can be easily achieved by removing both arguments.

```suggestion
```

2020-11-04 11:41 UTC, Glutexo commented on tests/test_api_hosts_update.py
> +    assert record.modified_on > updated_time
Let’s add checks that _stale_timestamp_ and _reporter_ didn’t change.

2020-11-04 11:41 UTC, Glutexo commented on tests/test_api_hosts_update.py
>  @pytest.mark.system_culling
Since this does not change the stale timestamp any more, it is no longer related to system culling. The test above doesn’t have this mark, so let’s remove it from this one too.

```suggestion
```

2020-11-04 11:41 UTC, Glutexo commented on tests/test_api_hosts_update.py
> +    post_doc["insights_id"] = f"nomatch_{created_host.canonical_facts['insights_id']}"
This is not correct. Because with the prefix, the value is no longer a valid UUID and thus does not pass validation. Let’s generate a random UUID instead.

```suggestion
    post_doc["insights_id"] = generate_uuid()
```

2020-11-04 11:41 UTC, Glutexo commented on tests/test_api_hosts_update.py
>      assert_response_status(response_status, expected_status=400)
You correctly changed the response status code to _404 Not Found_ in this case. This test is now wrong and passes only because of the mistake above.

```suggestion
    assert_response_status(response_status, expected_status=404)
```

2020-11-04 11:41 UTC, Glutexo commented on tests/test_system_profile.py
> +    assert_error_response(response_data, expected_title="Bad Request", expected_status=400)
This is completely unrelated to the ultralight check-ins. Please remove and create a separate PR if necessary.

2020-11-04 11:55 UTC, Glutexo requested changes
- Found one more bug with the status code if host is not matcher.
- Confirmed working by manual testing. Only the aforementioned status code is wrong.

2020-11-04 11:55 UTC, Glutexo commented on api/host.py
>              status=400,
You claim status _404 Not Found_ in the JSON object, but the status of the response is still _400 Bad Request_. Both should be _404 Not Found_.

2020-11-04 12:09 UTC, Glutexo requested changes
Found a failing test.

2020-11-04 12:09 UTC, Glutexo commented on tests/test_api_hosts_update.py
> +def test_checkin(event_datetime_mock, event_producer_mock, db_create_host, db_get_host, api_post):
The test is failing on system with a non-UTC time zone. Please see my comment below.

2020-11-04 13:27 UTC, thearifismail commented on tests/test_api_auth.py
> -from tests.helpers.test_utils import set_environment
> If `with set_environment({}):` is not removed, this needs to remain too.

this removal is valid because `tests/test_api_path` does not have any "with set_environment".

2020-11-04 13:31 UTC, thearifismail commented on tests/test_api_hosts_update.py
> +def test_checkin(event_datetime_mock, event_producer_mock, db_create_host, db_get_host, api_post):
> The test is failing on system with a non-UTC time zone. Please see my comment below.

Just ran this test successfully.

2020-11-04 13:59 UTC, kruai commented on app/serialization.py
> +    return _deserialize_canonical_facts(raw_data)
That's what I did, right? Or am I misreading this comment?

2020-11-04 16:45 UTC, thearifismail commented
/LGTM

2020-11-04 22:51 UTC, kruai commented on app/serialization.py
> +        raise ValidationException(str(e.messages)) from None
Sorry, what does DRYing mean in this context (and is it worth holding up the PR for)?

2020-11-04 23:09 UTC, kruai commented
@Glutexo I separated out the host creation endpoint, which got merged. I've also addressed your comments - how does it look now?

2020-11-05 02:26 UTC, ryandillinfelton commented on swagger/api.spec.yaml
> +                $ref: '#/components/schemas/CreateHostOut'
It looks like `BulkHostOut` isn't used by anything now (and I guess wasn't before)

2020-11-05 02:30 UTC, ryandillinfelton commented on swagger/api.spec.yaml
> +        insights_id:
This is as much a comment to you as it is to future me to verify. Should there be more validation here on string lengths and what not, and shouldn't there be some required fields here?

2020-11-05 11:09 UTC, Glutexo commented on app/serialization.py
> +        raise ValidationException(str(e.messages)) from None
I mean, create a function that would be reused in the two places where schemas are used to validate and unmarshall the incoming data. But it’s not worth holing up the PR.

2020-11-05 11:12 UTC, Glutexo commented on app/serialization.py
> +    return _deserialize_canonical_facts(raw_data)
Yes, it is. Perfect!

2020-11-05 12:29 UTC, Glutexo approved these changes
![LGTM](https://cdn.lgtmoon.dev/images/105589)

I offered a few small refactoring tips, but they don’t have to hold up this pull request. Feel free to implement them though if you feel like it.

Thanks for the changes. Everything now works correctly. Great work! 🙇🏻‍♂️🙏🏻

2020-11-05 12:29 UTC, Glutexo commented on tests/test_api_hosts_update.py
> +def test_checkin(event_datetime_mock, event_producer_mock, db_create_host, db_get_host, api_post):
@thearifismail That is strange. Datetimes retrieved from the database by SQLAlchemy are converted to timezone aware Python objects in the local timezone. Is it possible that you run it in a container or something that make Python assume UTC as local timezone?

2020-11-05 12:29 UTC, Glutexo commented on tests/fixtures/api_fixtures.py
> +        return do_request(flask_client.post, url, host_data, query_parameters, extra_headers, auth_type, identity_type)
This is the only request fixture that passes in the _auth_type_ parameter. It passes in a default value though, thus it is redundant. Removing the parameter would make this function nicely aligned with its sister ones: _api_put_ and _api_put_. They are also very repetitive, they may be worth DRYING.

```suggestion
    def _api_post(url, host_data, query_parameters=None, extra_headers=None, identity_type="User"):
        return do_request(flask_client.post, url, host_data, query_parameters, extra_headers, identity_type)
```

2020-11-05 14:18 UTC, kruai commented on swagger/api.spec.yaml
> +                $ref: '#/components/schemas/CreateHostOut'
Good catch! I've removed it.

2020-11-05 14:23 UTC, kruai commented on swagger/api.spec.yaml
> +        insights_id:
If this is a concern, I think we might want to open a Jira card for it! In this PR, I just took the schema that existed for host creation and repurposed it for this new endpoint. I can say that it does do the same amount of validation in the API using Marshmallow. What do you think?

2020-11-05 16:48 UTC, ryandillinfelton approved these changes
LGTM

2020-11-05 16:48 UTC, ryandillinfelton commented on swagger/api.spec.yaml
> +        insights_id:
Since we're not using any of the parameters to update the database I think it's fine to not validate them. Worst case if they're incorrect it just won't be able to find the host. As for required fields, again, if they send nothing they'll find nothing. I don't see why it should be a problem to not specify any required fields.

2020-11-05 17:03 UTC, merged

2020-11-06 12:58 UTC, Glutexo commented
@ryandillinfelton 

> Since we're not using any of the parameters to update the database I think it's fine to not validate them. Worst case if they're incorrect it just won't be able to find the host. As for required fields, again, if they send nothing they'll find nothing. I don't see why it should be a problem to not specify any required fields.

Technically you are right, but validating the input parameters does make some sense. One of the most important ones is that it support easy non-defensive unmarshalling. Now we use Marshallow for that, but we plan to use purely JSONSchema for that. When that is implemented, marking a field as UUID format does not only validate it, but provide us with a UUID Python object.

That being said, I would not remove any validation rules if there is not a very good reason for that.

2020-11-06 13:08 UTC, Glutexo reviewed
I missed a response code 400 in the OpenAPI specification. Please fix the code and its description. Thanks!

https://github.com/RedHatInsights/insights-host-inventory/blob/0456f4c59196e37aacff36c450f28695bcbceb88/swagger/api.spec.yaml#L97