RHCLOUD-10247: Allow for case insensitivity on Inventory name search
RedHatInsights/insights-host-inventory pull request #736
Opened 2020-10-29 19:32 UTC by aleccohan

Modified xjoin filter to allow for case insensitive Inventory name search.

JIRA:  https://issues.redhat.com/browse/RHCLOUD-10247

2020-10-29 20:14 UTC, jharting requested changes

2020-10-29 20:14 UTC, jharting commented on tests/test_xjoin.py
> +                        {"fqdn": {"matches_lc": f"*{hostname_or_id}*"}},
sadly, the fqdn operation does not support lower-case operands https://github.com/RedHatInsights/xjoin-search/blob/master/docs/schema.md#hostfilter so only `matches` can be used

2020-10-29 20:14 UTC, jharting commented on app/xjoin.py
> +    return {"matches_lc": f"*{string}*"}
The `matches_lc` operator only compares whatever argument it receives with a lower-case value of stored value. (i.e. `lower(stored) == "*{string}*"`) For the comparison to work always the argument should be converted to lowercase also so that we get `lower(stored) == "*{lower(string)}*"`

2020-10-30 02:03 UTC, shdunning commented on app/xjoin.py
> +    return {"matches_lc": f"*{string}*"}
@jharting crap. fqdn and display_name both use `string_contains`. i wonder if we should either:
a. make a `string_contains_lc` variant of this func
b. just add `to_lower = false` param and have `string_contains` return either the `matches` or `matches_lc` based on the bool val?
c. something else i hadn't thought of

2020-10-30 06:49 UTC, jharting commented on app/xjoin.py
> +    return {"matches_lc": f"*{string}*"}
@aleccohan Actually disregard my comment - the `*_lc` operators can be used directly i.e. no need to convert the argument to lowercase.

@shdunning yes we'll need a way to distinguish which variant to use. Both a) and b) look good to me

2020-10-30 12:46 UTC, jharting approved these changes

2020-11-02 12:00 UTC, ryandillinfelton approved these changes
LGTM :rocket:

2020-11-02 14:35 UTC, kruai approved these changes
LGTM!

2020-11-02 14:40 UTC, merged