Add config via clowder
RedHatInsights/insights-host-inventory pull request #737
Opened 2020-11-01 20:46 UTC by kylape

2020-11-02 12:42 UTC, thearifismail commented
The code LGTM.  Please me remind me; is Clowder the operator you've been working on?  Why should inventory use `clowder-config`?  Thanks.

2020-11-02 14:08 UTC, kylape commented
Yes, Clowder will create the Deployment and Service (and have other features down the road like autoscaling and metrics/alerts management) on behalf of the app.

2020-11-02 14:32 UTC, thearifismail approved these changes

2020-11-02 21:43 UTC, kruai approved these changes
LGTM!

2020-11-16 17:35 UTC, thearifismail commented
LGTM

2020-11-16 17:39 UTC, thearifismail approved these changes

2020-11-16 17:43 UTC, kruai approved these changes

2020-11-16 19:19 UTC, kruai requested changes

2020-11-16 19:19 UTC, kruai commented on Pipfile.lock
> -        "importlib-resources": {
It looks like the pre-commit check is failing because it can't find `importlib_resources`. Could that be because this section was removed?

2020-11-18 19:33 UTC, thearifismail commented
@klape using `app-common-python = "~=0.1.2"` removes `importlib_resources` from `Pipefile.lock` which causes this failures:
```log
+ /home/jenkins/.local/bin/pipenv run pre-commit run --all-files
Traceback (most recent call last):
  File "/home/jenkins/.local/share/virtualenvs/insights-host-inventory_PR-737-3adJvRb1/bin/pre-commit", line 5, in <module>
    from pre_commit.main import main
  File "/home/jenkins/.local/share/virtualenvs/insights-host-inventory_PR-737-3adJvRb1/lib/python3.6/site-packages/pre_commit/main.py", line 11, in <module>
    from pre_commit import git
  File "/home/jenkins/.local/share/virtualenvs/insights-host-inventory_PR-737-3adJvRb1/lib/python3.6/site-packages/pre_commit/git.py", line 7, in <module>
    from pre_commit.util import cmd_output
  File "/home/jenkins/.local/share/virtualenvs/insights-host-inventory_PR-737-3adJvRb1/lib/python3.6/site-packages/pre_commit/util.py", line 21, in <module>
    from importlib_resources import open_binary
ModuleNotFoundError: No module named 'importlib_resources'
```

It appears that to use `app-common-python` for `clowder-config` and not remove `importlib-resources` requires `python v3.7` or higher but `host-inventory` is still on python v3.6.11.  Question is can `clowder` be used without having to upgrade python version?  here is a link pointing toward the cause, https://ansible.slack.com/archives/CQFKM031T/p1605550926126000

2020-11-20 07:54 UTC, jharting requested changes

2020-11-20 07:54 UTC, jharting commented on app/config.py
> +        self.host_egress_topic = topic("platform.inventory.host-egress")
For historical reasons this defaults to `platform.inventory.host-egress` however in all environments this is overridden via env variable to use platform.inventory.events instead (see e.g. [this](https://github.com/RedHatInsights/e2e-deploy/blob/master/templates/inventory/env/ci.yml#L37) or [this](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/services/insights/host-inventory/deploy.yml#L82)) Therefore, the host-egress topic is effectively never used.

In order to preserve this behavior after the Clowder migration I think it would be best to change the default for host_egress_topic to `platform.inventory.events` so that it does not need to be overridden.

2020-11-30 20:12 UTC, kylape commented
/retest

2020-11-30 23:21 UTC, kylape commented on Pipfile.lock
> -        "importlib-resources": {
I reran the `pipenv lock` using python 3.6 and this was added back

2020-11-30 23:23 UTC, kylape commented
@thearifismail I think the dependency issues have been resolved.  I am trying to get the PR check to pass, but I have a chicken-and-egg problem because I need to add a saas-deploy file for host-inventory deployed via clowder, but it can't be added until the deployment template in this PR is merged to master.  Thus I think I am going to break just the deployment template out into a separate PR.

2020-12-03 17:04 UTC, jharting approved these changes

2020-12-03 18:51 UTC, kruai approved these changes

2020-12-03 19:56 UTC, kruai approved these changes

2020-12-03 19:56 UTC, merged