Remove host-creation endpoint, tests, etc.
RedHatInsights/insights-host-inventory pull request #740
Opened 2020-11-04 20:23 UTC by kruai

Addresses this Jira: https://issues.redhat.com/browse/RHCLOUD-10520
Removes the host-creation API endpoint, plus tests, and code that is no longer used as a result.

2020-11-04 20:33 UTC, thearifismail approved these changes
LGTM

2020-11-04 20:38 UTC, ryandillinfelton requested changes
I don't think the test_system_profile.py test additions should be part of this PR

2020-11-04 20:38 UTC, ryandillinfelton commented on tests/test_system_profile.py
> +def test_get_system_profile_RBAC_allowed(mocker, subtests, api_get, db_create_host, enable_rbac):
Why is adding these test part of this PR?

2020-11-04 20:39 UTC, kruai commented on tests/test_system_profile.py
> +def test_get_system_profile_RBAC_allowed(mocker, subtests, api_get, db_create_host, enable_rbac):
They're not being added - they're being moved from `test_api_hosts_create.py` (they should have been in `test_system_profile.py` to begin with imo)

2020-11-04 20:40 UTC, ryandillinfelton commented on tests/test_system_profile.py
> +def test_get_system_profile_RBAC_allowed(mocker, subtests, api_get, db_create_host, enable_rbac):
Oh I see, they were in the wring file before. Switching to approve :+1:

2020-11-04 20:40 UTC, ryandillinfelton approved these changes

2020-11-04 20:42 UTC, tahmidefaz approved these changes

2020-11-04 20:55 UTC, merged

2020-11-05 11:33 UTC, Glutexo commented
I am glad this is no longer part of #735.