WIP: RHCLOUD-8122 - Add support for compensating events.
RedHatInsights/insights-host-inventory pull request #741
Opened 2020-11-05 15:48 UTC by thearifismail

At the moment, there is only one test.  Currently working on more tests

2020-11-06 14:42 UTC, ryandillinfelton commented
You've got some pre-commit failures. Try installing the pre-commit hook if you haven't yet https://github.com/RedHatInsights/insights-host-inventory#contributing

2020-11-06 19:02 UTC, kruai commented
Just a note while I'm reviewing... Thanks for putting the Jira # in the title, but I think it would be more useful to have a link to it inside the description :smile:

2020-11-06 19:08 UTC, thearifismail commented
> Just a note while I'm reviewing... Thanks for putting the Jira # in the title, but I think it would be more useful to have a link to it inside the description 😄

🤣 🤣 🤣  thanks for reminding my a college professor of mine, he told me "Arif, no matter how perfect your are, I must point out something just to  make sure that I read it"

2020-11-06 19:24 UTC, kruai requested changes
A lot of this appears to be copied+pasted directly from host_reaper.py, host_delete.py, etc. Before I continue reviewing, can you please refactor a bit so there isn't a bunch of duplicated code?

2020-11-06 19:24 UTC, kruai commented on host_synchronizer.py
> +import json
Why? I don't see it used anywhere

2020-11-06 19:24 UTC, kruai commented on lib/host_synchronize.py
> +    return not instance_state(host).expired
The TODO needs to be addressed and removed. This method might not need to exist, depending on how the TODO is resolved

2020-11-06 19:24 UTC, kruai commented on lib/host_synchronize.py
> +    print("Total number: {}".format(select_query.count()))
Don't commit print statements

2020-11-06 19:24 UTC, kruai commented on lib/host_synchronize.py
> +            host_id     = host.id
This var is unnecessary... you can just use host.id

2020-11-06 19:24 UTC, kruai commented on lib/metrics.py
> +synchronize_fail_count = Counter("inventory_synchronize_fail_count", "The total amount of synchronization failures.")
```suggestion
synchronize_fail_count = Counter("inventory_synchronize_fail_count", "The total amount of synchronization failures")
```

2020-11-06 19:24 UTC, kruai commented on lib/host_synchronize.py
> +def _staleness_timestamps():
This function has already been defined in host_query.py. I'd recommend importing it from there.

2020-11-06 19:24 UTC, kruai commented on lib/host_synchronize.py
> +    cullingConfig = CullingConfig(stale_warning_offset_delta=timedelta(days=7), culled_offset_delta=timedelta(days=14))
... just as a side note, if you did need to keep this definition, I'd ask that we not use those hardcoded values; instead, we should stick to the values provided in `inventory_config()`

2020-11-06 19:25 UTC, kruai commented on host_synchronizer.py
> +import json
Looks like this got resolved with your linting fixes.

2020-11-06 19:54 UTC, thearifismail commented on lib/host_synchronize.py
> +    return not instance_state(host).expired
Already gone!!!

2020-11-06 20:04 UTC, thearifismail commented on lib/host_synchronize.py
> +            host_id     = host.id
removed .

2020-11-06 21:06 UTC, thearifismail commented on host_synchronizer.py
> +# TODO question, do we need a counter
removed already!

2020-11-06 21:07 UTC, thearifismail commented on host_synchronizer.py
> +            logger.info("Number of hosts synchronized: {}".format(update_count))
Done.!

2020-11-06 21:23 UTC, thearifismail commented on lib/host_synchronize.py
> +    cullingConfig = CullingConfig(stale_warning_offset_delta=timedelta(days=7), culled_offset_delta=timedelta(days=14))
same problem as the comment above.   Replaced hard-coded values in the method call with pre-defined constants.

2020-11-06 21:30 UTC, thearifismail commented on lib/host_synchronize.py
> +    print("Total number: {}".format(select_query.count()))
Removed a while back.  Should not see any more

2020-11-09 12:44 UTC, jharting requested changes

2020-11-09 12:44 UTC, jharting commented on host_synchronizer.py
> +    delete_host_count,
These delete metrics are not used. synchronize_host_count is missing.

2020-11-09 12:44 UTC, jharting commented on lib/host_synchronize.py
> +    while select_query.offset(start).limit(chunk_size).count():
Looks wasteful to issue a count request first to see if there is more data if the data is going to be read anyway. Moreover, the set of hosts may change in between the count query and the select query. Wouldn't it be better to just fetch the data and if the number of rows is 0 then exit?

2020-11-09 12:44 UTC, jharting commented on lib/host_synchronize.py
> +    # TODO: Check if this is still applicable when hosts are simply read from
As mentioned in the comment I don't think this applies here.

2020-11-09 13:43 UTC, thearifismail commented on host_synchronizer.py
> +    delete_host_count,
Fixed!!!

2020-11-09 15:27 UTC, thearifismail commented on lib/host_synchronize.py
> +    while select_query.offset(start).limit(chunk_size).count():
Done!

2020-11-09 15:28 UTC, thearifismail commented on lib/host_synchronize.py
> +    # TODO: Check if this is still applicable when hosts are simply read from
Gone!!!

2020-11-13 17:14 UTC, thearifismail commented on lib/host_synchronize.py
> +def _staleness_timestamps():
I tried using the one you referenced but got `out of scope` error.  This is the only way got it working.  This time using CONST instead of hard coding values in the function call.

2020-11-17 02:57 UTC, kruai requested changes
This is looking a lot better! I'd feel more comfortable getting another review on this as well, but it's getting there :)

2020-11-17 02:57 UTC, kruai commented on lib/host_synchronize.py
> +    print("Total number: {}".format(select_query.count()))
I still see it here (which means it wasn't removed). I also see it on your branch when I pull it.

2020-11-17 02:57 UTC, kruai commented on tests/test_synchronizer.py
> +    assert event_producer._kafka_producer.send.call_count == 2
I'm assuming this should be 2 because `host_count` is 3. To make this easier to understand for future devs, I'd recommend referencing host_count instead of hardcoding `2`:
```suggestion
    assert event_producer._kafka_producer.send.call_count == (host_count - 1)
```

2020-11-17 16:10 UTC, thearifismail commented
@kruai, it was `RuntimeError: Working outside of application context` that I had gotten.  The console output is included at the end of this comment.  Curious to see how you got it working.

The reason I followed the approach, I took, was that `host_syncronizer` was expected to get triggered manually or run as an ad-hoc openshift job.  Irregardless of how a TimeStamp object is created, the `serialize` method updates it with:
```python
def serialize_host(host, staleness_timestamps, fields=DEFAULT_FIELDS):
    if host.stale_timestamp:
        stale_timestamp = staleness_timestamps.stale_timestamp(host.stale_timestamp)
        stale_warning_timestamp = staleness_timestamps.stale_warning_timestamp(host.stale_timestamp)
        culled_timestamp = staleness_timestamps.culled_timestamp(host.stale_timestamp)
    else:
        stale_timestamp = None
        stale_warning_timestamp = None
        culled_timestamp = None
```

Console log when using `staleness_timestamps()` from `host_query`, which runs in the context of a flask app.
```log
[2020-11-17 10:29:40,681] [6564] [4426395072] [sqlalchemy.engine.base.Engine] [INFO] ROLLBACK
[2020-11-17 10:29:40,684] [6564] [4426395072] [inventory.inventory_synchronizer] [ERROR] Host synchronizer failed
Traceback (most recent call last):
  File "/Users/aarif/.pyenv/versions/3.6.11/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/aarif/.pyenv/versions/3.6.11/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/aarif/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/Users/aarif/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/aarif/.vscode/extensions/ms-python.python-2020.11.358366026/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/Users/aarif/.pyenv/versions/3.6.11/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/Users/aarif/.pyenv/versions/3.6.11/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Users/aarif/.pyenv/versions/3.6.11/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "host_synchronizer.py", line 109, in <module>
    main(logger)
  File "host_synchronizer.py", line 99, in main
    run(config, logger, session, event_producer, shutdown_handler)
  File "<decorator-gen-7>", line 2, in run
  File "/Users/aarif/.local/share/virtualenvs/insights-host-inventory-408tqVB7/lib/python3.6/site-packages/prometheus_client/context_managers.py", line 23, in wrapped
    return func(*args, **kwargs)
  File "host_synchronizer.py", line 67, in run
    for host_id, synchronize in events:
  File "/Users/aarif/Documents/dev-ws/insights/insights-host-inventory/lib/host_synchronize.py", line 32, in synchronize_hosts
    serialized_host = serialize_host(host, staleness_timestamps(), EGRESS_HOST_FIELDS)
  File "/Users/aarif/Documents/dev-ws/insights/insights-host-inventory/api/host_query.py", line 29, in staleness_timestamps
    return Timestamps.from_config(inventory_config())
  File "/Users/aarif/Documents/dev-ws/insights/insights-host-inventory/app/__init__.py", line 71, in inventory_config
    return current_app.config["INVENTORY_CONFIG"]
  File "/Users/aarif/.local/share/virtualenvs/insights-host-inventory-408tqVB7/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/aarif/.local/share/virtualenvs/insights-host-inventory-408tqVB7/lib/python3.6/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/Users/aarif/.local/share/virtualenvs/insights-host-inventory-408tqVB7/lib/python3.6/site-packages/flask/globals.py", line 52, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in some way. To solve
this, set up an application context with app.app_context().  See the
documentation for more information.
[2020-11-17 10:29:41,200] [6564] [4426395072] [inventory.lib.handlers] [INFO] Closing producer
[2020-11-17 10:29:41,204] [6564] [4426395072] [inventory.lib.handlers] [INFO] Closing database
[2020-11-17 10:29:41,205] [6564] [4426395072] [inventory.lib.handlers] [INFO] Pushing metrics
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/aarif/.pyenv/versions/3.6.11/lib/python3.6/urllib/request.py", line 1349, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Users/aarif/.pyenv/versions/3.6.11/lib/python3.6/http/client.py", line 1272, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/aarif/.pyenv/versions/3.6.11/lib/python3.6/http/client.py", line 1318, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/aarif/.pyenv/versions/3.6.11/lib/python3.6/http/client.py", line 1267, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/aarif/.pyenv/versions/3.6.11/lib/python3.6/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/Users/aarif/.pyenv/versions/3.6.11/lib/python3.6/http/client.py", line 976, in send
    self.connect()
  File "/Users/aarif/.pyenv/versions/3.6.11/lib/python3.6/http/client.py", line 948, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/Users/aarif/.pyenv/versions/3.6.11/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/Users/aarif/.pyenv/versions/3.6.11/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aarif/.pyenv/versions/3.6.11/lib/python3.6/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 61] Connection refused>
(insights-host-inventory) bash-3.2$ ```

2020-11-17 17:08 UTC, kruai commented
@thearifismail it turns out that how I got it working was "run the wrong file" :) 
However, I still don't think these values should be hardcoded. If the inventory configuration starts using different values for its culling config, this synchronizer will overwrite the staleness, stale warning, and culled timestamps. It should pull them from this config here: https://github.com/RedHatInsights/insights-host-inventory/blob/master/app/config.py#L88-L95

That said, I don't know how to do that at the moment. I didn't realize app context would be an issue here. There's gotta be a way to use that same config file, though.

2020-11-17 17:39 UTC, kruai commented
@thearifismail I got it working. In host_synchronizer.py, update your `synchronize_hosts` call to this:
```
events = synchronize_hosts(query, event_producer, 1000, config, shutdown_handler.shut_down)
```
Then, in host_synchronize.py, update `synchronize_hosts` to accept that new config argument, and update the host serialization to:
```
serialized_host = serialize_host(host, Timestamps.from_config(config), EGRESS_HOST_FIELDS)
```

2020-11-17 21:57 UTC, thearifismail commented
@kruai implemented your recommendation.

2020-11-17 22:05 UTC, kruai submitted a review, later dismissed
It looks good to me now! We should definitely get another review before merging, though.

2020-11-19 15:36 UTC, jharting commented on lib/host_synchronize.py
> +        host_list = select_query.offset(start).limit(chunk_size)
Does this return the entries in some deterministic order? If not we should perhaps add an explicit ORDER BY clause. If it does implicitly it might be good to mention that in a comment

2020-11-19 15:36 UTC, jharting commented on lib/host_synchronize.py
> +        host_list = select_query.offset(start).limit(chunk_size)
Also, I am wondering if offset-based pagination is stable enough for this possibly long-running script. For example, if a host gets delete while this is running it could cause some other hosts to be missed by the script (as the pages all shift).

2020-11-19 15:36 UTC, jharting commented on lib/host_synchronize.py
> +            event_producer.write_event(event, str(serialized_host), headers, Topic.events, wait=True)
I don't think it's necessary to wait=True here - i.e. if we fail to produce a message we can always re-run this script.

2020-11-19 15:36 UTC, jharting commented on lib/host_synchronize.py
> +            yield host.id, True
If we never yield False then this second return value is probably not needed?

2020-11-20 00:20 UTC, thearifismail commented on lib/host_synchronize.py
> +            yield host.id, True
Gone!

2020-11-20 00:20 UTC, thearifismail commented on lib/host_synchronize.py
> +            event_producer.write_event(event, str(serialized_host), headers, Topic.events, wait=True)
Gone!

2020-11-20 01:17 UTC, thearifismail commented on lib/host_synchronize.py
> +        host_list = select_query.offset(start).limit(chunk_size)
@jharting, I could not find a doc explicitly describing any deterministic order used by `SQLAlchemy.Query.offset and limit`.  For deterministic implementation, we can use:
```python
def synchronize_hosts(select_query, event_producer, chunk_size, config, interrupt=lambda: False):
    start = 0
    ordered_list = select_query.order_by(Host.created_on)
    while True:
        host_list = ordered_list.offset(start).limit(chunk_size)
        if host_list.count() <= 0:
        ...
        ...
        ...
```

This, I fear, will increase the chances of running out of memory because `Query.order_by() is understood to bring all records from the host table in one go.   This fear is supported by 
https://groups.google.com/g/sqlalchemy/c/a8BfpLC_M-w?pli=1, which also states 
`...never SELECT more rows than you'd like to have in memory at once. This means if you are paging through a million rows, use limiting / windowing / criteria to ensure you only get a few hundred at a time. The naive approach to this is to use LIMIT/OFFSET, however OFFSET has the issue that the database has to scan through all the previous rows, limiting
performance. `

In case of one time, manual synch/restore job, performance should not be a concern.  The statement about scanning previous rows for each scan gives me confidence that offset and limits work properly. Furthermore, I have been testing the code with 2,115 records and today with 3,003 records and never saw any wrong count.

With this in mind, if you still have doubts about not using `ORDER_BY`, I can implement it.

2020-11-20 01:45 UTC, thearifismail commented
test_synchronizer test may fail.  Will investigate tomorrow.

2020-11-20 09:16 UTC, jharting commented on lib/host_synchronize.py
> +        host_list = select_query.offset(start).limit(chunk_size)
> This, I fear, will increase the chances of running out of memory because Query.order_by() is understood to bring all records from the host table in one go.
Not if you combine it with limit()

> however OFFSET has the issue that the database has to scan through all the previous rows, limiting
performance
yes, I think that's a major concern given that we need to paginate over the entire database

> The statement about scanning previous rows for each scan gives me confidence that offset and limits work properly. Furthermore, I have been testing the code with 2,115 records and today with 3,003 records and never saw any wrong count.

Well, as long as the entire script runs in an read-isolated transaction then you're correct. Otherwise it is not guaranteed to be consistent. Unless you tried to do a concurrent delete in your testing the problem would not show up

I went ahead and switched to keyset-based pagination in https://github.com/thearifismail/insights-host-inventory/pull/1 This approach will be consistent (even without transaction isolation) and does not suffer from performance problems on high offsets

2020-11-20 17:59 UTC, thearifismail commented on lib/host_synchronize.py
> +        host_list = select_query.offset(start).limit(chunk_size)
Thanks. The key-based pagination is merged into the rhc-8122 branch.

2020-11-20 20:34 UTC, tahmidefaz approved these changes
LGTM! We need to work on the e2e/app-sre deploy configs. :+1:

2020-11-20 20:48 UTC, thearifismail reviewed
@jharting Can you please review again and approve it so that can merge the code?

2020-11-23 13:27 UTC, jharting approved these changes

2020-11-23 13:36 UTC, kruai approved these changes

2020-11-23 13:56 UTC, ryandillinfelton approved these changes

2020-11-23 14:07 UTC, merged