WIP: Check-In endpoint refactoring and cleanup
RedHatInsights/insights-host-inventory pull request #744
Opened 2020-11-06 21:02 UTC by kruai

Addresses https://issues.redhat.com/browse/RHCLOUD-10546

2020-11-09 16:19 UTC, Glutexo commented
@kruai I think we should raise 400 Bad Request if no canonical fact is provided.

2020-11-09 16:20 UTC, Glutexo commented
@kruai There are failing tests.

2020-11-23 16:17 UTC, Glutexo commented
I completely forgot about this. Sorry about that. 😞 May I ask to fix the failing tests @kruai and I‘ll try to not forgot again and review.

2020-11-24 21:16 UTC, kruai commented
@Glutexo Failing tests fixed!

2020-11-25 16:09 UTC, Glutexo requested changes
Sorry about this. I didn’t realize that the Canonical Facts schema in the get Hosts query output is different from the input one. 😞

2020-11-25 16:29 UTC, kruai commented on swagger/api.spec.yaml
> +          description: Bad Request.
OK, so no changes are required here?

2020-11-25 16:30 UTC, kruai commented on api/host.py
> +        )
I can change my responses to flask.abort, though I think changing the other ones in the file would be outside the scope of this PR.

2020-11-25 16:32 UTC, kruai commented on swagger/api.spec.yaml
> +          nullable: true
Okay, I can change it so that it uses CanonicalFactsIn and CanonicalFactsOut. I wish there were a cleaner way to do that, though...

2020-11-25 16:36 UTC, kruai commented on api/host.py
> +        )
Updated.

2020-11-25 16:52 UTC, kruai commented on api/host.py
> +    if not canonical_facts:
OK, updated in the CanonicalFactsIn schema.

2020-11-25 16:54 UTC, kruai commented
@Glutexo I've separated the schema into CanonicalFactsIn and CanonicalFactsOut, and believe I've addressed all the issues you brought up. Can you please take another look?

2020-11-25 19:26 UTC, Glutexo commented on swagger/api.spec.yaml
> +          description: Bad Request.
No changes. 👍🏻

2020-11-25 19:27 UTC, Glutexo commented
What happend to the tests? 😞

2020-11-26 12:34 UTC, Glutexo reviewed
It looks like the suggested schema does not work as expected. I think I figured out a way. Trying this out now.

2020-11-30 13:18 UTC, Glutexo commented
@kruai I took a look at the schema and I think I found a way how to

- make Canonical Facts nullable on the output, but not on the input without repeating the whole definition,
- how to make on the Input at least one Canonical Fact required.

Please check my new commits to this pull request. What did I do:

- Extracted each Canonical Fact to its own component. This was not necessary, I just felt like it.
- Made all the Canonical Fact properties nullable. This needs to be the base state for further combination. Non-null values match both a _nullable schema_ and _non-nullable one_, null values match only a _nullable_ schema. Thus _allOf_ can be used add the _non-nullable_ restriction, but not to remove it.
- For the input, combined the output nullable Canonical Facts set with a set of schemas that only add `nullable: false` for each property. Unfortunately _nullable_ can’t be used just by itself, but always together with _type_. That’s because it’s just an OpenAPI alias for `type: [something, "null"]`.

2020-11-30 19:28 UTC, kruai reviewed
I think this needs 2 changes, one of which I'll do myself. The other change I want to run by you @Glutexo

2020-11-30 19:28 UTC, kruai commented on swagger/api.spec.yaml
> +          description: Bad Request.
OK. Considering my previous changes where I removed that particular flask.abort from the code, I think it makes sense to remove the `400` from here as well (since only deviating from the schema will result in a `400`).

2020-11-30 19:28 UTC, kruai commented on swagger/api.spec.yaml
> +      - oneOf:
Shouldn't this be `anyOf`? `oneOf` tells it to accept one and only one item, whereas `anyOf` specifies one or more.

2020-11-30 19:29 UTC, Glutexo commented on swagger/api.spec.yaml
> +      - oneOf:
Right!

2020-11-30 19:30 UTC, Glutexo commented on swagger/api.spec.yaml
> +          description: Bad Request.
I agree. We however for some reason list 400 almost everywhere. 🤷🏻‍♂️

2020-11-30 20:28 UTC, kruai commented on swagger/api.spec.yaml
> +      - oneOf:
Replaced it and added some tests that validate these scenarios.

2020-12-01 12:49 UTC, Glutexo commented
I pushed a few commits related to the checkin frequency parameter.

1. Added tests for the parameter and its validation.
2. Removed the default value as it’s not used by Connexion.
3. Removed the parameter and all the tests.

I think having the parameter there in the specification is only misleading. The value is not used at all and even if it’s not there, the clients can still use it and it will just be ignored.

If there is a reason to have it there, just revert the last commit and it will be back there with the tests I added. I can imagine that we want to make use of the validation not to break hosts already providing the value, once we implement its actual usage.

2020-12-01 12:51 UTC, Glutexo approved these changes
Thanks for your changes. Nice catch with the _oneOf_ combinator! 👍🏻
Please take a look at my last changes and revert the last commit if you don’t want the checkin frequency parameter to be removed.

2020-12-01 14:11 UTC, kruai commented
Your last changes look good, but we do want to keep the check-in frequency parameter. For now this is just supposed to update the host's updated date, but later on that value will be saved and used in different ways.

2020-12-01 14:12 UTC, kruai commented
@Glutexo how does this PR look now? Is it ready to be merged?

2020-12-01 14:27 UTC, Glutexo approved these changes

2020-12-01 15:42 UTC, thearifismail approved these changes
LGTM

2020-12-01 17:16 UTC, merged

2021-03-08 11:04 UTC, Glutexo commented on swagger/api.spec.yaml
> +        Fqdn:
This breaks stuff!

```suggestion
      fqdn:
```

2021-03-09 14:24 UTC, kruai commented on swagger/api.spec.yaml
> +        Fqdn:
Shit, how'd that get capitalized :notlikethis:

2021-03-09 14:28 UTC, kruai commented on swagger/api.spec.yaml
> +        Fqdn:
Fix is here: https://github.com/RedHatInsights/insights-host-inventory/pull/826