[WIP] Add system owner [RHCLOUD - 8583]
RedHatInsights/insights-host-inventory pull request #747
Opened 2020-11-20 21:28 UTC by ryandillinfelton

2020-11-23 22:14 UTC, thearifismail approved these changes
lgtm

2020-11-30 18:43 UTC, kruai requested changes
This looks good to me. I think it would also benefit from a test that fails the criteria, though... like create an incorrect owner_id and make sure it doesn't accept it

2020-11-30 19:12 UTC, ryandillinfelton commented
> This looks good to me. I think it would also benefit from a test that fails the criteria, though... like create an incorrect owner_id and make sure it doesn't accept it

It wouldn't be possible since we aren't validating any of the system profile right now. I'll make a note to add it when system profile input validation is working.

2020-11-30 19:31 UTC, kruai commented
OK, that's fair. In that case, it's good to go!

2020-11-30 19:31 UTC, kruai approved these changes

2020-12-01 09:02 UTC, jharting requested changes

2020-12-01 09:02 UTC, jharting commented on swagger/system_profile.spec.yaml
> +      owner_id:
Changes to system_profile need to go to https://github.com/redhatinsights/inventory-schemas first. The process is documented in https://docs.google.com/document/d/1-2x4awXu3kZCZ5OUAUTxcpcm3IwaZx8D1Q52QVPah1U/edit#

2020-12-01 09:03 UTC, jharting commented
> It wouldn't be possible since we aren't validating any of the system profile right now. I'll make a note to add it when system profile input validation is working.

I don't follow. Inventory has always been validating SP. Why is it not validating SP right now?

2020-12-01 14:44 UTC, ryandillinfelton commented
> > It wouldn't be possible since we aren't validating any of the system profile right now. I'll make a note to add it when system profile input validation is working.
> 
> I don't follow. Inventory has always been validating SP. Why is it not validating SP right now?

My bad, I realize now that you say this I was confusing the system profile input with the system profile filters. We still validate the input and I'll add a negative test to check our validation for the field.

2020-12-01 14:56 UTC, ryandillinfelton commented
I opened an associated PR on inventory-schemas here: https://github.com/RedHatInsights/inventory-schemas/pull/30

2020-12-01 15:04 UTC, kruai requested changes
Re-requesting changes after seeing the above discussion; I just want to make sure the tests are in before I give my final approval

2020-12-01 15:17 UTC, kruai commented on swagger/system_profile.spec.yaml
> +        pattern: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
@tahmidefaz brought up a good point on the other PR; can you add an example here too?

2020-12-01 17:38 UTC, ryandillinfelton commented on swagger/system_profile.spec.yaml
> +        pattern: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
Yep, just updated it to match all the changes from the other PR

2020-12-01 20:41 UTC, thearifismail approved these changes
LGTM

2020-12-03 15:52 UTC, kruai submitted a review, later dismissed
LGTM - I just want to make sure @gmcculloug is cool with us calling it "owner_id" for now before merging. It would probably save time overall if we were able to use its final name now

2020-12-03 15:53 UTC, kruai commented
@ryandillinfelton It looks like some conflicts need to be resolved before merging first. That might dismiss our approvals again

2020-12-03 16:32 UTC, kruai commented
Slack thread on the `owner_id` discussion here: https://ansible.slack.com/archives/CQFKM031T/p1607010514281400
It sounds like we've got the go-ahead at this point, @ryandillinfelton ! I say let's resolve the merge conflicts and get this thing in

2020-12-03 17:11 UTC, ryandillinfelton commented
> Slack thread on the `owner_id` discussion here: https://ansible.slack.com/archives/CQFKM031T/p1607010514281400
> It sounds like we've got the go-ahead at this point, @ryandillinfelton ! I say let's resolve the merge conflicts and get this thing in

We need to get https://github.com/RedHatInsights/inventory-schemas/pull/34 merged first. It needs one more approval.

2020-12-03 17:21 UTC, thearifismail approved these changes
looks like `owner_id` is the term @asa is settling on and I agree with it.

2020-12-03 18:43 UTC, gmcculloug commented
RedHatInsights/inventory-schemas#34 is now merged.  Let's see if we can address failing checks so this is closer to merging.

2020-12-04 14:55 UTC, jharting submitted a review, later dismissed

2020-12-04 15:19 UTC, kruai approved these changes

2020-12-04 15:47 UTC, thearifismail approved these changes
Looks good.  All tests passed.

2020-12-04 15:48 UTC, merged