operating_system fact should be dict not list
RedHatInsights/insights-host-inventory pull request #754
Opened 2020-12-01 17:27 UTC by CodeHeeler

The os major/minor/name PR [0] just merged in puptoo and ci is having issues with it.  We suspect it's due to the use of List not Dict in the Marshmallow portion of the schema.  Could replace with fields.Dict or omit entirely.  Any feedback on this is appreciated, we'd like to get a fix out rather quickly.  Thanks!

[0] https://github.com/RedHatInsights/insights-puptoo/pull/82

2020-12-01 17:29 UTC, CodeHeeler commented
@tahmidefaz @SteveHNH @ryandillinfelton The os major/minor/name work we did recently has a bug, please take a look when you can.

2020-12-01 21:03 UTC, ryandillinfelton requested changes

2020-12-01 21:03 UTC, ryandillinfelton commented on app/models.py
> +    operating_system = fields.Nested(OperatingSystemSchema)
I think this should be 
```suggestion
    operating_system = fields.Nested(OperatingSystemSchema())
```

2020-12-01 21:11 UTC, kruai commented on app/models.py
> +    operating_system = fields.Nested(OperatingSystemSchema)
I'm actually not clear on this... [the docs](https://marshmallow.readthedocs.io/en/3.0/nesting.html) make it look like you don't use the parens, but some examples use parens when supplying a param

2020-12-01 21:11 UTC, thearifismail approved these changes
LGTM

2020-12-01 21:22 UTC, gmcculloug commented on app/models.py
> +    operating_system = fields.Nested(OperatingSystemSchema)
The use of parens is a little inconsistent elsewhere in this file, but for this section it seems to always pass "()", so might be better to include them.

@CodeHeeler @tahmidefaz Are there sufficient existing tests for this change?

2020-12-01 22:13 UTC, kruai commented on app/models.py
> +    operating_system = fields.Nested(OperatingSystemSchema)
I pushed the parentheses change; we can revert this if we decide against it later

2020-12-01 22:19 UTC, kruai approved these changes

2020-12-01 22:20 UTC, ryandillinfelton approved these changes
LGTM now!

2020-12-01 22:20 UTC, tahmidefaz approved these changes
LGTM!

2020-12-01 22:21 UTC, merged

2021-02-09 16:16 UTC, RonnyPfannschmidt commented on swagger/system_profile.spec.yaml
>          type: object
this type line needs to go