[WIP] RHC 8586: Limit CRUD operations to system owners when cert-auth used
RedHatInsights/insights-host-inventory pull request #755
Opened 2020-12-01 18:22 UTC by thearifismail

https://issues.redhat.com/browse/RHCLOUD-8586

Since this PR is about CRUD operations, the change is about getting list of hosts owned by the cert_owner.  One option is to fetch from database only the systems with the desired owner_id.  The problem with that approach is that fetching systems from DBs is handled by multiple modules and the API is used by others not using REST/CRUD.  This change very likely may have negative impact on those users.

2020-12-03 14:13 UTC, gmcculloug commented
@thearifismail Looks like this PR has extra commits associated with it.  And now it has a conflict, so needs some cleanup work here.  Let me know if you help.

2020-12-07 10:44 UTC, jharting commented on api/host.py
> +    host_id_list = _get_current_owner_host_ids(host_id_list)
You can make `system_profile_facts["owner_id"] == identity.owner` condition part of the delete query instead of two steps where you fetch all the hosts first and then delete them based on id. This applies to other operations also.

2020-12-08 00:19 UTC, thearifismail commented on api/host.py
> +    host_id_list = _get_current_owner_host_ids(host_id_list)
Prior to taking this two-steps approach, I looked into applying filters based on `system owner_id` and `identity owner` and found the two-steps approach simpler.  Fetching hosts using query.filter() is spread over more than one modules and then checking for ownerships and then dealing with hosts in query vs query.items() was additional.  That's why I took this simpler, straight forward.  

I guess the question is, is the computational cost too much for running two queries versus one?  If the computational cost and performance are not an issue, I would like to stay with this approach.  Another reason I chose this option was that the changes were primarily to the `api/host.py` because the PR is for CRUD operations only.

2020-12-08 19:32 UTC, kruai commented on api/host.py
> +    host_id_list = _get_current_owner_host_ids(host_id_list)
I agree with @jharting on this one. This PR is currently adding seemingly-unneeded complexity (both logical complexity and time complexity) to all CRUD API calls. I think instead it makes more sense to modify [queries like these](https://github.com/RedHatInsights/insights-host-inventory/blob/master/api/host.py#L186) to incorporate that logic, rather than getting the full list of host IDs for an owner. I say this mostly because we'll doing this for satellites as well, which will own many hosts and add overhead to these operations

2020-12-18 21:12 UTC, kruai commented
Hey @jharting, can you take a look at the newer changes? They're not "sweeping" per se, but I'd like to make sure you're on board with the direction this PR is taking

2020-12-21 14:34 UTC, jharting commented
The direction looks good to me. However, at this point there are bugs that should be fixed before this change is merged - for example there are access paths where the owner_id is not enforced (e.g. when listing hosts with display_name filter, when using xjoin, etc.)

2021-01-06 23:04 UTC, thearifismail commented
@jharting @kruai @ryandillinfelton Please review the PR because not much time is left and I don't want to hold back the review because of two failing tests.  The two failing tests test "canonical_fact_host_query tests", which should be fixed tomorrow.  I appreciate your help.  Thanks.

2021-01-07 14:42 UTC, thearifismail commented
/test

2021-01-07 14:43 UTC, thearifismail commented
/retest

2021-01-07 16:11 UTC, ryandillinfelton commented on app/auth/__init__.py
> +current_identity = LocalProxy(get_current_identity)
If we don't need LocalProxy when accessing the current identity I think this line can go.

2021-01-07 21:30 UTC, thearifismail commented on app/auth/__init__.py
> +current_identity = LocalProxy(get_current_identity)
Gone!

2021-01-08 20:19 UTC, kruai requested changes
Looking good! Just had a few notes

2021-01-08 20:19 UTC, kruai commented on tests/test_unit.py
> +        # return Identity(account_number="some acct")
Please delete code instead of commenting it out

2021-01-08 20:19 UTC, kruai commented on utils/encode_base64_json.py
> +print("Done!!!")
Why not just do `echo -n $DATA | base64 -w 0`, or `cat -n $DATA | base64 -w 0`? I feel like this script is superfluous, but @ryandillinfelton @tahmidefaz let me know if you think it would help

2021-01-08 20:19 UTC, kruai commented on utils/payloads.py
> +        # "owner_id": random_uuid(),
Please delete this line

2021-01-08 20:21 UTC, kruai commented
@thearifismail please make sure you have the pre-commit hook installed, since the pre-commit check failed.
Also, 4 unit tests are failing. Do you need help with these?

2021-01-08 20:40 UTC, thearifismail commented on api/host.py
> +def _get_host_list_by_id_list(current_identity, host_id_list):
Feel more comfortable this way because the endpoints are hit directly.  e.g I can hit `get_hosts_list` with my identity and someone else can hit `update_host` using her idenity

2021-01-08 20:48 UTC, thearifismail commented on api/host.py
> +    current_identity = get_current_identity()  # TODO: parameter
should have been removed it.  Don't recall the frame of mind for this comment.

2021-01-08 20:53 UTC, thearifismail commented on lib/host_repository.py
> +        if identity.identity_type == "System" and identity.system["cert_type"] == "system":
Keeping it separate for communication purpose with comment `# kafka based requests have dummy identity for working around the identity requirement for CRUD operations`

2021-01-08 20:57 UTC, thearifismail commented on tests/test_unit.py
> +        # return Identity(account_number="some acct")
Gone!

2021-01-08 20:57 UTC, thearifismail commented on tests/test_api_hosts_update.py
> +    # host = db_create_host()
Gone!

2021-01-08 20:57 UTC, thearifismail commented on tests/helpers/api_utils.py
> +# this is WIP
Gone!

2021-01-08 21:03 UTC, thearifismail commented on utils/encode_base64_json.py
> +print("Done!!!")
This IS superfluous but left it for convenience to avoid inadvertent white spaces which would yield different keys.  Doesn't hurt to leave it but I am okay with removing it.

2021-01-08 23:38 UTC, thearifismail commented on app/auth/__init__.py
> +
Removed already.

2021-01-08 23:42 UTC, thearifismail commented on utils/encode_base64_json.py
> +print("Done!!!")
removed this file.

2021-01-09 00:05 UTC, thearifismail commented on utils/payloads.py
> +        # "owner_id": random_uuid(),
Gone!

2021-01-11 13:57 UTC, kruai requested changes
Just needs this last line of commented-out code removed!

2021-01-11 13:57 UTC, kruai commented on app/auth/__init__.py
> +
Is isn't, though

2021-01-11 14:21 UTC, thearifismail commented on app/auth/__init__.py
> +
This time is should be out.

2021-01-11 14:37 UTC, kruai submitted a review, later dismissed

2021-01-11 19:44 UTC, tahmidefaz submitted a review, later dismissed
LGTM!

2021-01-11 19:45 UTC, ryandillinfelton commented on tests/test_api_facts.py
> +    # setting identity type to User does not help.
This seems like a dev comment that should be removed

2021-01-11 19:56 UTC, thearifismail commented on tests/test_api_facts.py
> +    # setting identity type to User does not help.
Yep. Should've been removed.

2021-01-11 19:57 UTC, kruai approved these changes

2021-01-11 20:27 UTC, ryandillinfelton reviewed
LGTM for the most part. I left some suggestions.

2021-01-11 20:27 UTC, ryandillinfelton commented on app/auth/identity.py
>              raise ValueError("Neither the account_number or token has been set")
Would like to see this comment reflect the change to an identity object instead of just an account number

2021-01-11 20:27 UTC, ryandillinfelton commented on tests/fixtures/api_fixtures.py
> +    # flask_app.user_identity = None
This should be deleted

2021-01-11 20:27 UTC, ryandillinfelton commented on tests/test_api_auth.py
> +def test_validate_valid_user_identity(flask_client):
Was there meant to also be a test here using a valid system identiy? It looks like there are supporting changes in place, but I don't see them being used.

2021-01-11 20:35 UTC, ryandillinfelton commented on tests/test_api_auth.py
> +def test_validate_valid_user_identity(flask_client):
Oops, it's right below lol

2021-01-11 20:37 UTC, ryandillinfelton approved these changes
LGTM now

2021-01-11 20:49 UTC, thearifismail commented on tests/test_api_auth.py
> +def test_validate_valid_user_identity(flask_client):
tests using "system" as the idenity_type.

1. https://github.com/thearifismail/insights-host-inventory/blob/ee42a1002365831ce3913442a4370706197f2976/tests/test_api_auth.py#L18
2. https://github.com/thearifismail/insights-host-inventory/blob/ee42a1002365831ce3913442a4370706197f2976/tests/test_api_facts.py#L170
3. https://github.com/thearifismail/insights-host-inventory/blob/ee42a1002365831ce3913442a4370706197f2976/tests/test_api_hosts_delete.py#L215
4. https://github.com/thearifismail/insights-host-inventory/blob/ee42a1002365831ce3913442a4370706197f2976/tests/test_api_hosts_update.py#L445

2021-01-11 20:51 UTC, merged