WIP: Create system_profile validator endpoint
RedHatInsights/insights-host-inventory pull request #774
Opened 2021-01-06 19:27 UTC by kruai

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-10580).
The goal is the provide an endpoint that does the following:
- Takes a branch name and a timeframe as path parameters
- Fetches the System Profile spec from the specified branch in the inventory-schemas repo
- Aggregates the Kafka messages that were produced within the supplied timeframe
- Runs validation on the messages's host data for both the specified branch and the master branch
- Responds with a pass/fail summary, grouped by reporter

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

TODO: I will go through this list and mark the appropriate items before I remove this PR's WIP status.

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-01-06 19:28 UTC, kruai commented
Don't review this quite yet - there's a lot of organization & cleanup I want to work on. I'll remove "WIP" when it's ready!

2021-01-12 19:42 UTC, kruai commented
I'm trying to test this, but the Disk Device options are failing:
```
[ERROR] {'system_profile': ["System profile does not conform to schema.
True is not of type 'object'

Failed validating 'type' in schema['properties']['disk_devices']['items']['properties']['options']['additionalProperties']:
    {'additionalProperties': {'$ref': '#/$defs/NestedObject'},
     'description': 'An arbitrary object that doesn’t allow empty string '
                    'keys.',
     'propertyNames': {'minLength': 1},
     'type': 'object'}

On instance['disk_devices'][0]['options']['ro']:
    True"]}
```

I think our spec for NestedObject might be incorrect. What do you think @tahmidefaz ?

2021-01-13 22:09 UTC, tahmidefaz commented on api/system_profile.py
> +def validate_schema(repo_branch="master", days=14):
@kruai  Got a question: Should it be `days=14`? I thought we were only looking back 1 day :thinking:

2021-01-13 22:14 UTC, kruai commented on api/system_profile.py
> +def validate_schema(repo_branch="master", days=14):
I don't have concrete requirements for that. You can of course configure this value, but we can change the default if necessary. What do you think @gmcculloug ?

2021-01-13 22:23 UTC, tahmidefaz requested changes
It might be better to have some tests for this. What do you think?

2021-01-13 22:42 UTC, tahmidefaz requested changes

2021-01-13 22:42 UTC, tahmidefaz commented on lib/system_profile_validate.py
> +    )
I lot of the updates will be coming in from `forks` and not `branches`. This url might make fetching the files from forks difficult (or impossible, even). :thinking:

2021-01-14 16:46 UTC, ryandillinfelton commented on lib/system_profile_validate.py
> +    )
I think it just needs to be able to take a github username in and swap it with RedHatInsights (i.e.https://raw.githubusercontent.com/tahmidefaz/inventory-schemas/master/schemas/system_profile/v1.yaml)

2021-01-14 16:56 UTC, kruai commented on lib/system_profile_validate.py
> +    )
Hmm, that does complicate things. Would be great if we could ask people to just make branches instead of forking, but that's not reasonable. I'll add an optional `fork` parameter that defaults to RedHatInsights

2021-01-14 17:04 UTC, ryandillinfelton commented on lib/system_profile_validate.py
> +    )
If it's not too much trouble I think adding the optional fork parameter is ideal. We could open the repo up more to allow anyone to make a branch, but I could see requiring branches leading to some inconvenience down the line.

2021-01-14 17:12 UTC, thearifismail commented on lib/system_profile_validate.py
> +    )
Shouldn't then `RedHatInsights` be replaced by a variable say `fork`?

2021-01-14 17:15 UTC, kruai commented on lib/system_profile_validate.py
> +    )
Yeah that's the plan

2021-01-14 17:17 UTC, ryandillinfelton commented on swagger/api.spec.yaml
> +        - in: query
Odds are no one will try this, but the service 500s when you send days=0

2021-01-14 17:30 UTC, ryandillinfelton commented on api/system_profile.py
> +def validate_schema(repo_branch="master", days=14):
14 days would insure that all non-stale hosts work with the new schema, but I worry that it's a lot of data to check. 1-2 days should give us a similar amount of assurance with significantly less data. My vote is to have it default low until we know the performance.

2021-01-14 17:32 UTC, ryandillinfelton requested changes
Looks good and seems to work in my testing so far. I would just like fork support and a fix to the 500 bug I outlined above.

2021-01-14 17:53 UTC, thearifismail reviewed
Shouldn't there be tests for system_profile_validate for testing bad branch, fork, and primarily good and bad fields in the submitted schema?

2021-01-14 17:53 UTC, thearifismail commented on lib/system_profile_validate.py
> +    )
I personally feel at ease using `forks`, which was pretty common among Cloudform team member.  How about 
```python
def _validate_host_list(host_list, repo_branch, fork='RedHatInsights'):
```

2021-01-14 17:53 UTC, thearifismail commented on lib/system_profile_validate.py
> +    tp = TopicPartition(config.host_ingress_topic, 0)
I am assuming `0` is the first partition.  Could there be multiple partitions and the `host_ingress_topic` getting posted to a second or third partition?

2021-01-14 17:53 UTC, thearifismail commented on swagger/api.spec.yaml
> +        - in: query
@ryandillinfelton  do you mean 400, bad request for 0 days

2021-01-14 18:25 UTC, kruai commented on swagger/api.spec.yaml
> +        - in: query
Yep, I defined a minimum for that field which should fix the issue.

2021-01-14 18:27 UTC, kruai commented on lib/system_profile_validate.py
> +    tp = TopicPartition(config.host_ingress_topic, 0)
There's only one partition for all of our topics. I remember trying to make this code work for `n` number of partitions, but ran into some implementation issues. I'll give it another shot, though.

2021-01-14 19:11 UTC, kruai commented on api/system_profile.py
> +def validate_schema(repo_branch="master", days=14):
I set the default to 1 day!

2021-01-14 19:11 UTC, kruai commented on lib/system_profile_validate.py
> +    )
I've parameterized the fork.

2021-01-14 19:22 UTC, kruai commented on lib/system_profile_validate.py
> +    tp = TopicPartition(config.host_ingress_topic, 0)
@thearifismail Since our topics all have 1 partition, and we don't even know if this is going to be a long-term solution, I think just reading from this one partition should work fine. I'll make a note for myself to follow up and verify that it's the same case for all of our environments, including Prod. Is that okay with you?

2021-01-14 19:29 UTC, ryandillinfelton commented on lib/system_profile_validate.py
> +    tp = TopicPartition(config.host_ingress_topic, 0)
afaik we only use one partition in prod too. There was some talk about increasing that though, but we can address that down the line if it ever changes.

2021-01-14 19:41 UTC, thearifismail commented
Will system_profile validation run as a cronjob?

2021-01-14 19:49 UTC, kruai commented
> Will system_profile validation run as a cronjob?

That's the intent for step 2. The goal is to get this API endpoint merged so people can at least validate on their own, and then create a cronjob that scans for PRs and leaves validation summary comments

2021-01-14 19:51 UTC, ryandillinfelton commented on api/system_profile.py
> +@metrics.api_request_time.time()
Is this the right metric for this? If this endpoint takes a while to produce a response when it has a huge amount of data I don't want it to trip any alarms we have for "normal" API requests that are more latency dependent.

2021-01-14 19:55 UTC, tahmidefaz commented on api/system_profile.py
> +@metrics.api_request_time.time()
Yes, agree. We might want to add a new metric in `api/metrics.py` :+1:

2021-01-14 20:06 UTC, ryandillinfelton commented on swagger/api.spec.yaml
> +            minimum: 0
This can be added along with the tests but I wanted to note it. What happens if someone asks for more days of data than kafka can provide?

2021-01-14 20:42 UTC, kruai commented on swagger/api.spec.yaml
> +            minimum: 0
It doesn't matter. There's a consumer method I'm using that calculates the partition offset based on a timestamp (which is determined by the `days` param). If it asks for more days of data than are available, it just returns all the messages available.

2021-01-14 20:43 UTC, kruai commented on api/system_profile.py
> +@metrics.api_request_time.time()
Oh, good point. I'll add that new metric.

2021-01-14 20:48 UTC, kruai commented on api/system_profile.py
> +@metrics.api_request_time.time()
OK, added!

2021-01-14 20:50 UTC, ryandillinfelton commented on api/system_profile.py
> +@metrics.schema_validation_time.time()
I think you replaced the metric in the wrong spot

2021-01-14 20:55 UTC, kruai commented on api/system_profile.py
> +@metrics.schema_validation_time.time()
Ugh, you're right. Sorry about that. Should have taken a deep breath first

2021-01-14 20:58 UTC, tahmidefaz approved these changes
LGTM :+1:

2021-01-14 21:07 UTC, ryandillinfelton approved these changes
:rocket: LGTM

2021-01-14 21:39 UTC, thearifismail approved these changes
LGTM

2021-01-14 21:42 UTC, merged