rhc-8586: Set test identity account number to the one in payload
RedHatInsights/insights-host-inventory pull request #780
Opened 2021-01-12 22:11 UTC by thearifismail

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-8586).

This PR fixed a bug in https://github.com/RedHatInsights/insights-host-inventory/pull/755.  The bug was that `find_existing_host` was using `test` as the account number but should be using the one received in the payload from kafka message.

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-01-12 22:48 UTC, thearifismail commented
@ryandillinfelton comment from #778, "Could you add a test to insure that the bug this is fixing is fixed? I'd like to have it to insure we don't accidentally reintroduce it in the future. A test insuring that a created host has the right account ID should be enough.

2021-01-12 22:54 UTC, thearifismail commented
https://github.com/RedHatInsights/insights-host-inventory/pull/780#issuecomment-759086647

The new functionality is getting touched by https://github.com/thearifismail/insights-host-inventory/blob/20bcd73b8016d073fafbeb48a5b05881e9ef769d/tests/test_mq_service.py#L181

2021-01-13 01:08 UTC, thearifismail commented
@ryandillinfelton, the test you're looking for is already provided https://github.com/thearifismail/insights-host-inventory/blob/4fe5f32ea9fd299a1d38d2d682a1a8e2b61cfc71/tests/test_mq_service.py#L181

Couple of new tests to update host.account has been added.  There are a number of tests present for testing message handling by queue.

2021-01-13 13:30 UTC, thearifismail commented
Added [test_handle_message_with_different_account](https://github.com/thearifismail/insights-host-inventory/blob/246fc9fdd73cfe6906f0fe8b397bcdd0711a82d9/tests/test_mq_service.py#L1023), which updates identity.

2021-01-13 16:22 UTC, kruai requested changes
I'd like one of your new tests to be a bit more precise, and I would also like to see a test that fails if yesterday's scenario happens again. That is to say, if you call `mq_create_or_update_host()` on a host twice, it should not create a host the second time. 

One way to do this is to call `db_get_hosts()` on the host's ID at the beginning of the test (it should return 0), in-between the `mq_create_or_update_host()` calls (it should return 1), and at the end of the test (it should still return 1). That test would make me feel more at ease with merging this.

2021-01-13 16:23 UTC, kruai commented
@tahmidefaz @ryandillinfelton does the new test suggestion in my review make sense to you two?

2021-01-13 17:57 UTC, ryandillinfelton commented
> @tahmidefaz @ryandillinfelton does the new test suggestion in my review make sense to you two?

Yes, I like that idea for a test. I agree that we should have a precise test for the scenario.

2021-01-13 18:09 UTC, ryandillinfelton commented on tests/test_mq_service.py
> +    # account_name = "hbi_test_aaccount"
nitpicky, but small typo in the comment here.

2021-01-13 18:25 UTC, ryandillinfelton commented on tests/test_mq_service.py
> +def test_handle_message_with_different_account(mocker, flask_app, subtests):
This test is overbuilt for it's supposed to be testing. We already test that unicode is not damaged, that doesn't need to be included in a test checking that hosts created through MQ recieve the right account value.

2021-01-13 19:44 UTC, thearifismail commented on tests/test_mq_service.py
> +def test_handle_message_with_different_account(mocker, flask_app, subtests):
I have removed the extra lines but the intent of this test is test the updated identity NOT the unicode.

2021-01-13 19:45 UTC, thearifismail commented on tests/test_mq_service.py
> +    # account_name = "hbi_test_aaccount"
Gone!!!

2021-01-13 19:54 UTC, thearifismail commented on tests/test_api_hosts_get.py
> +    assert db_get_host(created_host.id)
An attempt to add an existing host does not fail; rather returns the same host with an updated timestamp updated.  So to test the scenario mentioned in the comment:

1.  Created "created_host" and "same_host" using the same "fqdn", i.e.  the same host dictionary object.
2. Set `created_host.updated = same_host.updated`
3. Compared the two hosts using `deepequals` for equality.

2021-01-13 20:14 UTC, kruai requested changes

2021-01-13 20:14 UTC, kruai commented on tests/test_api_hosts_get.py
> +    created_host.updated = same_host.updated
Why are you manually setting created_host's "updated" field to the value in `same_host`?

2021-01-13 20:14 UTC, kruai commented on tests/test_api_hosts_get.py
> +    assert created_host.id == same_host.id
I'm not sure this is a meaningful assertion. If everything's working as expected, the IDs would be equal; however, if the add/exist functionality didn't work correctly and created a new host, it would still have that ID, right?
I think that to fully validate the issue we saw yesterday, we really need to use something like `db_get_hosts()` to check how many records exist for a certain ID.

2021-01-13 20:46 UTC, thearifismail commented on tests/test_api_hosts_get.py
> +    assert created_host.id == same_host.id
@kruai, I should have removed `assert created_host.id == same_host.id`.  

you asked, "if the add/exist functionality didn't work correctly and created a new host, it would still have that ID, right?".

The answer is No because each new host gets a unique ID.  Since for both hosts, the same `fqdn` is used, inventory returns the same host.
No, new host has a new `id`, generated by inventory host.  

I can take out `assert created_host.id == same_host.id` if it is causing confusion.

2021-01-13 20:59 UTC, kruai commented on tests/test_api_hosts_get.py
> +    created_host.updated = same_host.updated
Oh, I'm guessing it's so you can compare the `__dict__` for each... I don't know what that would tell us, though, since you added the exact same host twice

2021-01-13 21:00 UTC, kruai commented on tests/test_api_hosts_get.py
> +    assert created_host.id == same_host.id
Oh, I see what you mean. In that case, asserting that the new and old IDs are the same is a good test, as it tells us that it updated a host instead of creating a new one. Thanks for clarifying!

2021-01-13 21:22 UTC, thearifismail commented on tests/test_api_hosts_get.py
> +    assert created_host.id == same_host.id
Updated test to use `get_db_hosts()` and then compared the number of hosts before and after the second attempted to create the same host.

2021-01-13 21:41 UTC, ryandillinfelton commented on tests/test_mq_service.py
> +def test_handle_message_with_different_account(mocker, flask_app, subtests):
Thanks. I think you could go further though, it doesn't seem like you need the test to loop when there is only one message.

2021-01-13 21:47 UTC, ryandillinfelton commented on tests/test_api_hosts_get.py
> +def test_host_account_using_mq(mq_create_or_update_host, api_get, db_get_host, db_get_hosts):
I feel like this test belongs more in test_mq than here. You also don't use the `api_get` function in this test.

2021-01-13 21:48 UTC, kruai approved these changes

2021-01-13 21:49 UTC, ryandillinfelton commented on tests/test_api_hosts_get.py
> +def test_host_account_using_db(db_create_host, db_get_host):
This test should also move to the test_mq file

2021-01-13 21:52 UTC, ryandillinfelton commented on tests/test_api_hosts_get.py
> +    assert len(first_batch.all()) == len(second_batch.all())
This is right, and I'm happy with what the test accomplishes now. Correct me if I'm missing something, but I think you could just compare the id's of both created hosts to check the same thing.

2021-01-13 21:58 UTC, thearifismail commented on tests/test_api_hosts_get.py
> +    assert len(first_batch.all()) == len(second_batch.all())
@kruai had reservation about comparing just the `id`.  https://github.com/RedHatInsights/insights-host-inventory/pull/780#discussion_r556801483

Since comparing `__dict__` includes `id`, I took it out.

2021-01-13 22:05 UTC, thearifismail commented on tests/test_api_hosts_get.py
> +def test_host_account_using_db(db_create_host, db_get_host):
There were three more `mq_create_or_update_host` tests in this file, so I left it in here because it also used `get_db_host()`.  So I left it in here.  

Since @kruai already approved it, I think we should leave it here for now and can move it in a following PR.  On my system, I have moved the test to the `test_mq_service.py` and it executed successfully.

2021-01-13 22:06 UTC, kruai commented on tests/test_api_hosts_get.py
> +    assert len(first_batch.all()) == len(second_batch.all())
@thearifismail you'll see later in that comment chain that I agreed that you only needed to test the IDs and not the other fields. I don't mind either way between comparing the IDs and comparing the whole dicts at this point

2021-01-13 22:15 UTC, thearifismail commented on tests/test_api_hosts_get.py
> +    assert len(first_batch.all()) == len(second_batch.all())
Fidelity-wise, it is better to compare all params to not have any questions.  I am sorry, I did not see your comment about IDs.  

Is it good for approval by both of you, particularly @ryandillinfelton?

2021-01-13 22:18 UTC, kruai commented on tests/test_api_hosts_get.py
> +def test_host_account_using_db(db_create_host, db_get_host):
Feels unfair to use my approval to disregard requested changes from someone else (that's why we have multiple reviewers). If you've already moved it and it's passing, why not just push that change?

2021-01-13 22:23 UTC, ryandillinfelton commented on tests/test_api_hosts_get.py
> +    assert len(first_batch.all()) == len(second_batch.all())
I'm happy enough with how it works to approve.

2021-01-13 22:25 UTC, thearifismail commented on tests/test_api_hosts_get.py
> +    assert len(first_batch.all()) == len(second_batch.all())
Moved `test_host_account_using_mq` to the mq tests file per @ryandillinfelton suggestion.

2021-01-13 22:56 UTC, ryandillinfelton approved these changes

2021-01-13 22:58 UTC, merged