system identity validation fix
RedHatInsights/insights-host-inventory pull request #785
Opened 2021-01-15 23:30 UTC by ryandillinfelton

## Overview

This PR improves out identity validation to prevent system identities lacking the required fields.

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-01-17 23:40 UTC, thearifismail commented on tests/test_api_auth.py
> +def test_validate_valid_invalid_system_identities(flask_client, subtests):
Rename the test to `test_invalid_system_identities` or `test_validate_invalid_system_identities` is more appropriate

2021-01-18 00:13 UTC, thearifismail requested changes
Observing a strange behavior not seen before.  Using `pytest`, `pytest -vv` or `pytest --cov=.` fails 11 tests.  BUT, no such failures are encountered when only the files containing the failed tests `pytest -vv tests/test_api_facts.py` OR only the failing tests are executed directly, e.g `pytest -vv tests/test_api_facts.py::test_put_facts_with_RBAC_bypassed_as_system`.  

[pytest_results.txt](https://github.com/RedHatInsights/insights-host-inventory/files/5827083/pytest_results.txt)
[executed_just_failed_tests_and_passed.txt](https://github.com/RedHatInsights/insights-host-inventory/files/5827085/executed_just_failed_tests_and_passed.txt)

2021-01-18 00:25 UTC, RonnyPfannschmidt commented
Im awake by pure luck and this look like something with the constant or its keys is wrong, examining that data and code that changes it might be helpful

I'll take a closer look tommorow morning when I get back to the computer

2021-01-18 00:30 UTC, RonnyPfannschmidt commented
To be more specific, it may be necessary to examine if some code is missing a copy/deepcopy and modifies things in place, without any deeper investigation this looks like a accidental constant change which is now a unfortunate test dependency may be the cause

2021-01-18 08:17 UTC, RonnyPfannschmidt requested changes
i recommend to create altered copies of SYSTEM_IDENTITY which then use altered copies of the `system` subkey

2021-01-18 08:17 UTC, RonnyPfannschmidt commented on tests/test_api_auth.py
> +def invalid_identities(identity_type):
this code breaks the `SYSTEM_IDENTITY` global as system comes as a reference not as a copy

after this case runs once `SYSTEM_IDENTITY`  is no longer usable

2021-01-18 13:36 UTC, kruai requested changes

2021-01-18 13:36 UTC, kruai commented on tests/test_api_auth.py
> +def test_validate_valid_invalid_system_identities(flask_client, subtests):
I think `test_invalid_system_identities` is more appropriate here.

2021-01-18 13:36 UTC, kruai commented on tests/test_api_auth.py
> +def invalid_identities(identity_type):
Good catch! You'll need to clone the dictionary when it gets passed in @ryandillinfelton

2021-01-18 13:36 UTC, kruai commented on app/auth/identity.py
> +                raise ValueError("The cn field is mandatory.")
Are our stakeholders cool with us erroring out in these scenarios? Just want to make sure, because we'll still end up with a situation like Friday where HBI was throwing a bunch of errors

2021-01-18 13:44 UTC, kruai commented on tests/test_api_auth.py
> +def invalid_identities(identity_type):
Just to clarify, I mean `dict.deepcopy()`

2021-01-18 14:06 UTC, RonnyPfannschmidt commented on tests/test_api_auth.py
> +            Identity(SYSTEM_IDENTITY)._asdict()["system"].pop("cert_type", None),
another issue, as identities are being constructed from the return value, i believe that using the pop as return value is completely incorrect as pop returns the element it took out of a dict

2021-01-18 14:08 UTC, RonnyPfannschmidt commented on tests/test_api_auth.py
> +            Identity(SYSTEM_IDENTITY)._asdict()["system"].pop("cert_type", None),
note that this wont show up as  problem since the incorrect data will cause authentication errors just the "same",

i would recommend to validate the error message to ensure each breakage is handled as one would hope

2021-01-18 15:00 UTC, thearifismail commented on app/auth/identity.py
> +                raise ValueError("The cn field is mandatory.")
@asa who are the stakeholders on your mind?

2021-01-18 15:44 UTC, thearifismail approved these changes
LGTM.  @ryandillinfelton agreed with the change.

2021-01-18 15:44 UTC, thearifismail commented on app/auth/identity.py
> +                raise ValueError("The cn field is mandatory.")
fixed the issue by updating `_asdict()` method to return copies of user as `identity.user.copy()` and system as `identity.system.copy()`
https://github.com/RedHatInsights/insights-host-inventory/blob/368a976d08f09b92f15e0eabf20a4ddf9508bd9d/app/auth/identity.py#L59

2021-01-18 15:44 UTC, thearifismail commented on tests/test_api_auth.py
> +def invalid_identities(identity_type):
fixed the issue by updating `_asdict()` method to return copies of user as `identity.user.copy()` and system as `identity.system.copy()`

2021-01-18 15:55 UTC, kruai commented on app/auth/identity.py
> +                raise ValueError("The cn field is mandatory.")
@thearifismail I'm mostly referring to @lphiri, as he said he was going to discuss the errors we saw on Friday with @coderbydesign. It could be that this change is valid, but that we need to keep this change from going into Production until the corresponding 3scale change has been deployed.

Keith and Lindani, does that sound correct?

2021-01-18 16:05 UTC, kruai commented on tests/test_api_auth.py
> +            Identity(SYSTEM_IDENTITY)._asdict()["system"].pop("cert_type", None),
@thearifismail I believe this comment still has yet to be addressed

2021-01-18 16:07 UTC, ryandillinfelton commented on tests/test_api_auth.py
> +            Identity(SYSTEM_IDENTITY)._asdict()["system"].pop("cert_type", None),
I'm addressing this now. Going to request changes to block till it's ready

2021-01-18 16:12 UTC, thearifismail commented on app/auth/identity.py
> +                raise ValueError("The cn field is mandatory.")
Thanks Asa.  I think we need to run by the producers of all three reporters.

2021-01-18 16:16 UTC, kruai commented on app/auth/identity.py
> +                raise ValueError("The cn field is mandatory.")
I'm not so sure; it seems like this functionality provides the correct desired state, but there's an issue with 3scale or insights-client that gave us some invalid identity headers. I think following up with Lindani and maybe Keith is the best first step to take on this one

2021-01-18 17:07 UTC, ryandillinfelton commented on tests/test_api_auth.py
> +            Identity(SYSTEM_IDENTITY)._asdict()["system"].pop("cert_type", None),
Thanks for the catch Ronny. I've manually validated that the identity headers are now incorrect in the right way. The API responds the same way when the identity header is invalid so I haven't made the test aware of if it's being marked invalid for the correct reason. I'll explore using mocks to verify, but I'm confident that the test is working as intended right now, even if it's less robust than it ideally would be.

2021-01-18 17:11 UTC, RonnyPfannschmidt submitted a review, later dismissed

2021-01-18 18:37 UTC, ryandillinfelton commented
I'm marking this as on hold since merging it will likely make it more difficult to add a work around for requests from insights classic. We can revisit this once the work around is sorted out.

2021-01-20 15:17 UTC, ryandillinfelton commented on app/auth/identity.py
> +                raise ValueError("The cert_type field is mandatory.")
Noting that we've elected to handle this in a follow up

2021-01-20 15:46 UTC, thearifismail commented on lib/host_repository.py
> +    # if identity.auth_type == "classic-proxy":
remove comment the commented `if` and `return` statements.

2021-01-20 15:58 UTC, thearifismail approved these changes
Besides one minor comment, LGTM

2021-01-20 15:59 UTC, ryandillinfelton commented on lib/host_repository.py
> +    # if identity.auth_type == "classic-proxy":
Fixed

2021-01-20 16:02 UTC, thearifismail approved these changes
LGTM

2021-01-20 16:38 UTC, kruai commented on app/auth/identity.py
> +                raise ValueError("The cert_type field is mandatory.")
Follow-up Jira bug: https://issues.redhat.com/browse/RHCLOUD-11801

2021-01-20 16:40 UTC, kruai commented on app/auth/identity.py
> +            if not identity.system["cert_type"]:
Good catch. This should probably be addressed before merging @ryandillinfelton

2021-01-20 16:43 UTC, thearifismail commented on app/auth/identity.py
> +                raise ValueError("The cn field is mandatory.")
We had not expected to `cn` missing from `Identity.idenity_type == system`; now the case is handled when the query is checked and updated for `owner_id`.  Kudos to @ryandillinfelton for adding and updating tests.  Identity checks will get simpler than the current ones when a uniform identity structure is suppported.

2021-01-20 18:45 UTC, kruai submitted a review, later dismissed

2021-01-20 18:46 UTC, tahmidefaz approved these changes
Let's go!!

2021-01-20 19:14 UTC, ryandillinfelton commented
Worried about the assumption that the identity will have an auth-type. It's becoming clear that there are several internal teams making their own identity headers in different ways and that doesn't see to be a safe assumption or a good reason to reject the header IMO.

2021-01-20 19:48 UTC, kruai commented
> Worried about the assumption that the identity will have an auth-type. It's becoming clear that there are several internal teams making their own identity headers in different ways and that doesn't see to be a safe assumption or a good reason to reject the header IMO.

What if we only check for the auth-type if it's from insights-client? Would that help resolve it?

2021-01-20 20:15 UTC, thearifismail commented
> > Worried about the assumption that the identity will have an auth-type. It's becoming clear that there are several internal teams making their own identity headers in different ways and that doesn't see to be a safe assumption or a good reason to reject the header IMO.
> 
> What if we only check for the auth-type if it's from insights-client? Would that help resolve it?

Yes set `auth_type` when present, like the `cn` and `cert_type`.

2021-01-20 20:47 UTC, tahmidefaz commented
> > > Worried about the assumption that the identity will have an auth-type. It's becoming clear that there are several internal teams making their own identity headers in different ways and that doesn't see to be a safe assumption or a good reason to reject the header IMO.
> > 
> > 
> > What if we only check for the auth-type if it's from insights-client? Would that help resolve it?
> 
> Yes set `auth_type` when present, like the `cn` and `cert_type`.

Is doing so going to be safe? It's probably ok? Just wanted to make sure. :slightly_smiling_face:

2021-01-20 20:50 UTC, ryandillinfelton commented
> > > > Worried about the assumption that the identity will have an auth-type. It's becoming clear that there are several internal teams making their own identity headers in different ways and that doesn't see to be a safe assumption or a good reason to reject the header IMO.
> > > 
> > > 
> > > What if we only check for the auth-type if it's from insights-client? Would that help resolve it?
> > 
> > 
> > Yes set `auth_type` when present, like the `cn` and `cert_type`.
> 
> Is doing so going to be safe? This is probably ok? Just wanted to make sure.

I believe it is. We weren't requiring it before, and afaik it's only used for the insights-classic work around.

2021-01-20 21:58 UTC, thearifismail commented on tests/test_api_auth.py
> +    elif identity_type == "Classic":
There is no `identity_type: "Classic"`.  For `"auth_type": "classic-proxy"`, `type` is `System`.  This means to the tests will have to adjust to something like: 
```code
    return Identity(random.choice[INSIGHTS_CLASSIC_IDENTITY, SYSTEM_IDENTITY)
```

2021-01-20 22:04 UTC, asa commented
Can you all take me off your shoutouts?  I am not the asa you are looking for! =). Hi Asa, cool to meet another one, but getting these updates clogs my inbox!

2021-01-20 22:04 UTC, thearifismail commented on tests/test_api_auth.py
>  def valid_payload(identity_type):
Since there is no `identity_type`, this method needs an additional argument to create `INSIGHTS_CLASSIC_IDENTITY`

2021-01-20 22:45 UTC, kruai approved these changes

2021-01-20 22:58 UTC, thearifismail approved these changes
Looks good.  I like a lot the new create_identity_payload.

2021-01-21 14:26 UTC, merged