Ubi8
RedHatInsights/insights-host-inventory pull request #787
Opened 2021-01-19 18:39 UTC by kruai

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-11366).
This is only Part 1 of the work for this Jira card. It changes our dev Dockerfile to use the appropriate UBI8 image, and updates the Jenkinsfile to use postgres 10.6 (the one we use in Stage and Prod).

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-01-19 18:46 UTC, tahmidefaz approved these changes
LGTM

2021-01-19 18:52 UTC, gmcculloug commented on dev.dockerfile
> +FROM registry.access.redhat.com/ubi8/python-36
Happy to see this.  I wonder if we should be using a tag like we do with other ubi images [like sources](https://github.com/RedHatInsights/sources-api/blob/master/Dockerfile#L1).

@lindgrenj6 What's the best practice here?

2021-01-19 19:45 UTC, lindgrenj6 commented on dev.dockerfile
> +FROM registry.access.redhat.com/ubi8/python-36
Usually best practice is to use a tag - that way it's easy for infosec to track vulnerabilities. Also that way there is always an artifact showing the upgrade to mitigate any CVEs that come along. 

Red Hat images are really good about re-tagging latest (as you can see here: [ubi8/python-36](https://catalog.redhat.com/software/containers/ubi8/python-36/5c839d99d70cc51dd4c42610)) e.g. the docker tag `1-123.16099467941` was pushed, re-tagged to `1` which is the "rolling" v1 image, then re-tagged to `latest` as well. 

_but_ 

Looking at the repo there I would recommend tagging with `1-123.16099467941` since that's the latest one that won't be re-taggeed. This provides more control about what gets upgraded rather than the image changing on a rebuild. 

The tag is ugly, but it looks like this might be a one-off thing, the next one might be `1-124`. This can be something that just gets upgraded either every other sprint or just when necessary, either would work.

2021-01-19 20:44 UTC, kruai commented on dev.dockerfile
> +FROM registry.access.redhat.com/ubi8/python-36
Thanks for the info! I've updated it to use that tag.

2021-01-19 20:48 UTC, kruai commented
I've marked this one as "on hold" for now, because we'll need this to be a coordinated change with the RDS upgrade. The UBI images all use postgres 12.5, so it makes sense to move to that version now. However, if we push this change, we won't be able to safely push to Prod until the RDS instances are also running postgres 12.x.

Once we have a schedule prepared, we can merge this and thoroughly test a few days before the RDS instance is upgraded.

2021-01-19 20:55 UTC, tahmidefaz commented
@kruai It might be better to mark this as a WIP PR in the meantime.

2021-01-20 22:24 UTC, thearifismail commented on dev.dockerfile
> +FROM registry.access.redhat.com/ubi8/python-36:1-123.16099467941
What's the plan for moving up to `Python V3.8-x`?

2021-01-20 22:26 UTC, thearifismail requested changes
Shouldn't `yum update` or `yum update all` be in the docker file?

2021-01-21 14:17 UTC, lindgrenj6 commented on dev.dockerfile
> +FROM registry.access.redhat.com/ubi8/python-36:1-123.16099467941
This: https://catalog.redhat.com/software/containers/ubi8/python-38/5dde9cacbed8bd164a0af24a

registry.access.redhat.com/ubi/python-38:xxx

2021-01-21 14:20 UTC, lindgrenj6 commented
@thearifismail typically that is recommended against for prod containers, just for the reasons I mentioned before where the running versions of packages can change out from underneath you between builds. It makes it harder for infosec to track what problems are in each image. 

It's better to just consistently update the tag every couple weeks/month/whenever it updates. That way there is a trackable artifact that shows exactly when upgrades happen.

2021-04-07 19:20 UTC, kruai commented
Closing this, because future work on using UBI will likely use a different image. We should still be able to reference the changes made in this PR if needed.

2021-04-07 19:20 UTC, closed without merging