[WIP] Restart POD when DB is not accessible by inventory-mq
RedHatInsights/insights-host-inventory pull request #788
Opened 2021-01-20 18:44 UTC by thearifismail

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-xxxxx).
 
 **todo** Description to be provide when WIP is removed.

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-01-20 18:57 UTC, RonnyPfannschmidt commented on tests/test_mq_service.py
> +    fake_add_host = mocker.patch("app.queue.queue.add_host", return_value=(mocker.MagicMock(), None, None, None))
you need to mock host_repository.add_host here

2021-01-21 14:47 UTC, tahmidefaz requested changes

2021-01-21 14:47 UTC, tahmidefaz commented on app/queue/queue.py
>                          logger.exception("Unable to process message")
Should we also increment some metrics for `OperationalError` as we do for other `Exceptions`?

2021-01-21 15:16 UTC, thearifismail commented on tests/test_mq_service.py
> +    fake_add_host = mocker.patch("app.queue.queue.add_host", return_value=(mocker.MagicMock(), None, None, None))
This was a dummy test, I created to start but has been deleted since then.

2021-01-21 16:44 UTC, kruai commented on app/queue/queue.py
>                          logger.exception("Unable to process message")
We should definitely do that for visibility purposes ^

2021-01-21 18:00 UTC, thearifismail commented on app/queue/queue.py
>                          logger.exception("Unable to process message")
Done!

2021-01-22 15:50 UTC, kruai approved these changes
I think this looks good now!

2021-01-22 18:20 UTC, tahmidefaz approved these changes

2021-01-22 19:36 UTC, merged