WIP: Test system profile validator
RedHatInsights/insights-host-inventory pull request #790
Opened 2021-01-21 21:44 UTC by kruai

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-11693).
Adds test(s) that validate the system profile validator endpoint's functionality.

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-01-22 20:44 UTC, thearifismail requested changes
This test looks good, but is there a plan to provide tests as suggested in the JIRA card's description.

- Test handling of non-existent forks & branches
- Test insuring that invalid (and possibly excessive) `days` values are rejected with 400

2021-01-22 20:55 UTC, kruai commented
Good call - I had forgotten about that comment. I'm writing some more tests now.

2021-01-22 21:05 UTC, kruai commented
@thearifismail I changed a couple things, and added some tests to validate those particular scenarios.

2021-01-25 13:52 UTC, thearifismail commented on tests/test_system_profile.py
> +    get_schema_from_url_mock.side_effect = ValueError("Schema not found at URL!")
mock not getting used and has no relation to the remainder of the test.

2021-01-25 13:53 UTC, thearifismail commented on tests/test_system_profile.py
> +    assert response_status == 400
When used without the mock above, response_status "200" was received.

2021-01-25 16:21 UTC, kruai commented on tests/test_system_profile.py
> +    get_schema_from_url_mock.side_effect = ValueError("Schema not found at URL!")
The mock is getting used, and is explicitly affecting the rest of the test. I did just notice that a different error is triggering before the ValueError is being raised, which is causing the test failure here.

2021-01-25 16:23 UTC, kruai commented on tests/test_system_profile.py
> +    assert response_status == 400
That's the point of the mock! It shouldn't be returning 200 normally (which I'm working on), but I'm mocking the GET operation to simulate a situation where the repo and/or branch is invalid

2021-01-25 18:16 UTC, kruai commented on tests/test_system_profile.py
> +    get_schema_from_url_mock.side_effect = ValueError("Schema not found at URL!")
It should be triggering the correct error for this test now.

2021-01-25 20:56 UTC, thearifismail submitted a review, later dismissed
Yes.  LGTM

2021-01-25 21:03 UTC, ryandillinfelton approved these changes
LGTM

2021-01-25 21:21 UTC, tahmidefaz approved these changes

2021-01-27 20:51 UTC, ryandillinfelton commented on lib/system_profile_validate.py
>      consumer.close()
This seems a little redundant since you're closing the consumer in both branches of the try/except.

2021-01-27 20:54 UTC, ryandillinfelton commented on lib/system_profile_validate.py
> +        consumer.close()
Same here. You're closing the producer where you call if this function raises and exception right. Seems to me like this should just be raising the ValueError

2021-01-27 21:37 UTC, thearifismail approved these changes
LGTM

2021-01-27 21:47 UTC, ryandillinfelton approved these changes
LGTM

2021-01-27 22:01 UTC, merged