Add section about xjoin dev to readme
RedHatInsights/insights-host-inventory pull request #801
Opened 2021-02-01 22:03 UTC by fijshion

Just a README update to document how to develop locally against a working xjoin pipeline.

2021-02-04 20:49 UTC, thearifismail submitted a review, later dismissed
LGTM.  I have tested using two different accounts.  Created hosts using HBI mq_service and all hosts showed up in xjoin search

2021-02-04 20:52 UTC, thearifismail commented
@ryandillinfelton Can you please verify it?  I tested with hosts but didn't get around to play with tags or system_profile. 
 https://github.com/RedHatInsights/insights-host-inventory/blob/95bb3cfc0609a48bdc9f66e6186f800a8995271c/README.md#integrating-with-cross-join-xjoin

2021-02-08 17:18 UTC, kruai requested changes

2021-02-08 17:18 UTC, kruai commented on README.md
> +1. Run the inventory-mq-service
I think it would be worth noting that the steps that follow are done in the local dir for HBI, within the venv created by `pipenv shell`. I got a little confused here trying to figure out what I was doing wrong (though I also hadn't used `make` for these commands, either)

2021-02-08 17:18 UTC, kruai commented on README.md
> +make run_inv_mq_service_test_producer
When I run this, I get a bunch of errors. Seems to be caused by `sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "hosts" does not exist`, which doesn't make sense to me, because of course that table exists. Wonder if I should have run an additional step before this point

2021-02-08 17:19 UTC, kruai commented on README.md
> +make run_inv_mq_service_test_producer
@thearifismail I saw that you had no issues running this; did you have to do any extra steps before this point?

2021-02-08 19:13 UTC, fijshion commented on README.md
> +make run_inv_mq_service_test_producer
@kruai The hosts table missing could be a few issues. If you're sure the table exists in the inventory database started by `docker-compose up` in the kstreams project then my guess is the make command is pointing to the wrong database. The docker-compose inventory database is initialized with a hosts table so there shouldn't be any additional steps. Are you running the inventory pieces from a clean branch? Did you have a database on port 5432 already running when you ran `docker-compose up` (in this case I would expect to see a failure message in the logs and the pod to not have started)?

2021-02-08 19:31 UTC, fijshion commented on README.md
> +1. Run the inventory-mq-service
Updated in latest commit.

2021-02-08 20:20 UTC, kruai commented on README.md
> +make run_inv_mq_service_test_producer
I am running them from a clean branch, and I do see that the hosts table is defined in the xjoin-kstreams project's db config. I'm pretty sure I didn't have anything running on 5432, but I'll try again and debug a little more.

2021-02-08 20:49 UTC, kruai commented on README.md
> +make run_inv_mq_service_test_producer
Yeah, I'm still having the issue. The error on the xjoin-kstreams side looks like this, followed by the query it tried to run:
```
db-inventory_1      | 2021-02-08 20:25:47.609 GMT [34] ERROR:  relation "hosts" does not exist at character 471
```
I'm going to have to come back to this tomorrow. If it's working for the rest of you, I don't want to hold up this PR, so I'm neither going to approve nor request changes on this one.

2021-02-09 17:03 UTC, fijshion commented on README.md
> +make run_inv_mq_service_test_producer
Cool - yea, there are a lot of moving pieces here :confused:. Hopefully Clowder will be mature enough and more widely adopted soon, which should render this environment obsolete.

2021-02-09 21:19 UTC, tahmidefaz commented on README.md
> +make run_inv_mq_service_test_producer
I am getting this exact same error as well. I need to investigate more :thinking:

2021-02-10 16:57 UTC, tahmidefaz commented on README.md
> +make run_inv_mq_service_test_producer
ok, I think I figured out what's up here. If the user is running this for the first time, they need to do a db migration. So, the user needs to run `make upgrade_db` before running `make run_inv_mq_service`

2021-02-10 19:04 UTC, kruai commented on README.md
> +make run_inv_mq_service_test_producer
Awesome! If we could get that tidbit added to this README section, that would be great, since it stopped us from progressing

2021-02-11 14:14 UTC, fijshion commented on README.md
> +make run_inv_mq_service_test_producer
Running `make upgrade_db` is not necessary in the xjoin-kstreams docker-compose environment. It is initialized as part of `docker-compose up`, see https://github.com/RedHatInsights/xjoin-kstreams/blob/b582f43679647f5111a4336d4f1cb63db9f488a7/docker-compose.yml#L41. 

This makes me believe there is another database running on port 5432 of your machine. Or, for some reason the database container failed to properly initialize. Have you looked at the output of `docker ps` to make sure the docker-compose inventory database is up and running? It should look something like this:

```
CONTAINER ID   IMAGE                           COMMAND                  CREATED         STATUS         PORTS                                                    NAMES
a0debac21f1c   xjoin-kafka-connect:latest      "/docker-entrypoint.…"   2 minutes ago   Up 2 minutes   8778/tcp, 9092/tcp, 0.0.0.0:8083->8083/tcp, 9779/tcp     xjoin-kstreams_connect_1
91d2fa2f8073   debezium/kafka                  "/docker-entrypoint.…"   2 minutes ago   Up 2 minutes   8778/tcp, 9092/tcp, 9779/tcp, 0.0.0.0:29092->29092/tcp   xjoin-kstreams_kafka_1
b323075d8d84   xjoin-kstreams_xjoin-search     "container-entrypoin…"   2 minutes ago   Up 2 minutes   0.0.0.0:4000->4000/tcp, 8080/tcp                         xjoin-kstreams_xjoin-search_1
8715491d8aff   zookeeper                       "/docker-entrypoint.…"   2 minutes ago   Up 2 minutes   2888/tcp, 3888/tcp, 0.0.0.0:2181->2181/tcp, 8080/tcp     xjoin-kstreams_zookeeper_1
e572e8b73b49   debezium/postgres:10.0-alpine   "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes   0.0.0.0:5432->5432/tcp                                   xjoin-kstreams_db-inventory_1
34e6ec282e0b   debezium/postgres:10.0-alpine   "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes   0.0.0.0:5434->5432/tcp                                   xjoin-kstreams_db-vulnerability_1
ca0ff62e6df5   elasticsearch:7.3.1             "/usr/local/bin/dock…"   2 minutes ago   Up 2 minutes   0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp           xjoin-kstreams_elasticsearch_1
e81aed4ecacc   debezium/postgres:10.0-alpine   "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes   0.0.0.0:5433->5432/tcp                                   xjoin-kstreams_db-insights_1
```

Also, what's the output of `docker logs e572e8b73b49` (where e572e8b73b49 is the inventory db container)?

2021-02-12 18:58 UTC, kruai commented on README.md
> +make run_inv_mq_service_test_producer
@fijshion here's my `docker ps`:
```
CONTAINER ID        IMAGE                                                    COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
ca064c9cdd00        xjoin-kstreams_xjoin-search                              "container-entrypoin…"   8 minutes ago       Up 4 minutes        0.0.0.0:4000->4000/tcp, 8080/tcp                         xjoin-kstreams_xjoin-search_1
f6a44a6782bc        xjoin-kafka-connect:latest                               "/docker-entrypoint.…"   4 days ago          Up 4 minutes        8778/tcp, 9092/tcp, 0.0.0.0:8083->8083/tcp, 9779/tcp     xjoin-kstreams_connect_1
8b20fa5583e0        debezium/kafka                                           "/docker-entrypoint.…"   4 days ago          Up 4 minutes        8778/tcp, 9092/tcp, 9779/tcp, 0.0.0.0:29092->29092/tcp   xjoin-kstreams_kafka_1
9927052546f1        debezium/postgres:10.0-alpine                            "docker-entrypoint.s…"   4 days ago          Up 4 minutes        0.0.0.0:5434->5432/tcp                                   xjoin-kstreams_db-vulnerability_1
6e5dcf546a86        zookeeper                                                "/docker-entrypoint.…"   4 days ago          Up 4 minutes        2888/tcp, 3888/tcp, 0.0.0.0:2181->2181/tcp, 8080/tcp     xjoin-kstreams_zookeeper_1
8539e7e5ed9b        elasticsearch:7.3.1                                      "/usr/local/bin/dock…"   4 days ago          Up 4 minutes        0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp           xjoin-kstreams_elasticsearch_1
41e55df7c5df        debezium/postgres:10.0-alpine                            "docker-entrypoint.s…"   4 days ago          Up 4 minutes        0.0.0.0:5433->5432/tcp                                   xjoin-kstreams_db-insights_1
c5977fd9319d        debezium/postgres:10.0-alpine                            "docker-entrypoint.s…"   4 days ago          Up 4 minutes        0.0.0.0:5432->5432/tcp                                   xjoin-kstreams_db-inventory_1
920eff7dbb9e        registry.access.redhat.com/rhscl/redis-32-rhel7:latest   "container-entrypoin…"   21 months ago       Up 3 days           0.0.0.0:6379->6379/tcp                                   entitlements-api_redis_1
```
The database log is pretty long, though I did find this bit potentially interesting:
```
2021-02-08 17:00:17.197 GMT [34] LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE
CREATE ROLE
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init-permissions.sh
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/insights.sql
psql:/docker-entrypoint-initdb.d/insights.sql:0: could not read from input file: Is a directory
2021-02-08 17:01:06.333 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
```
However, the logs from my attempt today look relatively boring:
```
2021-02-12 18:44:37.477 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-02-12 18:44:37.477 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2021-02-12 18:44:37.496 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-02-12 18:44:37.536 GMT [19] LOG:  database system was shut down at 2021-02-09 00:41:23 GMT
2021-02-12 18:44:37.546 GMT [1] LOG:  database system is ready to accept connections
2021-02-12 18:48:47.671 GMT [1] LOG:  received smart shutdown request
2021-02-12 18:48:47.677 GMT [1] LOG:  worker process: logical replication launcher (PID 25) exited with exit code 1
2021-02-12 18:48:47.677 GMT [20] LOG:  shutting down
2021-02-12 18:48:47.734 GMT [1] LOG:  database system is shut down
2021-02-12 18:48:58.302 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-02-12 18:48:58.302 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2021-02-12 18:48:58.311 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-02-12 18:48:58.335 GMT [18] LOG:  database system was shut down at 2021-02-12 18:48:47 GMT
2021-02-12 18:48:58.344 GMT [1] LOG:  database system is ready to accept connections
2021-02-12 18:49:11.514 GMT [27] LOG:  starting logical decoding for slot "xjoin_advisor_v1_0"
2021-02-12 18:49:11.514 GMT [27] DETAIL:  streaming transactions committing after 0/16B2D60, reading WAL from 0/16B2D28
2021-02-12 18:49:11.515 GMT [27] LOG:  logical decoding found consistent point at 0/16B2D28
2021-02-12 18:49:11.515 GMT [27] DETAIL:  There are no running transactions.
2021-02-12 18:49:30.940 GMT [32] LOG:  starting logical decoding for slot "xjoin_advisor_v1_0"
2021-02-12 18:49:30.940 GMT [32] DETAIL:  streaming transactions committing after 0/16B2D60, reading WAL from 0/16B2D28
2021-02-12 18:49:30.940 GMT [32] LOG:  logical decoding found consistent point at 0/16B2D28
2021-02-12 18:49:30.940 GMT [32] DETAIL:  There are no running transactions.
```
Unfortunately, I get the same error I did last time, about the relation "hosts" not existing.

2021-02-12 19:12 UTC, fijshion commented on README.md
> +make run_inv_mq_service_test_producer
I see references to "xjoin_advisor_v1_0" and "insights.sql" in those two logs. This makes me think those are logs from the advisor db, not the inventory db.

Just as a side note, I'd be surprised if this was a docker version issue but this is the version I'm using:

```
$ docker-compose --version
docker-compose version 1.27.4, build unknown

chris at chris-t580 in ~/dev/projects/active/gopath/src/xjoin-operator (master)
$ docker --version
Docker version 20.10.2, build 2291f61
```

2021-02-12 20:10 UTC, kruai commented on README.md
> +make run_inv_mq_service_test_producer
Oops, you're right - I must not have lined the IDs up right. Here's the inventory db log:
```
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init-permissions.sh
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/inventory.sql
psql:/docker-entrypoint-initdb.d/inventory.sql:0: could not read from input file: Is a directory
2021-02-08 17:04:54.140 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-02-08 17:04:54.140 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2021-02-08 17:04:54.158 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-02-08 17:04:54.191 GMT [18] LOG:  database system was interrupted; last known up at 2021-02-08 17:02:34 GMT
2021-02-08 17:04:54.306 GMT [18] LOG:  database system was not properly shut down; automatic recovery in progress
2021-02-08 17:04:54.310 GMT [18] LOG:  redo starts at 0/16B1D10
2021-02-08 17:04:54.311 GMT [18] LOG:  invalid record length at 0/16B2468: wanted 24, got 0
2021-02-08 17:04:54.311 GMT [18] LOG:  redo done at 0/16B2410
2021-02-08 17:04:54.311 GMT [18] LOG:  last completed transaction was at log time 2021-02-08 17:02:34.44533+00
2021-02-08 17:04:54.345 GMT [1] LOG:  database system is ready to accept connections
2021-02-08 17:07:55.224 GMT [29] LOG:  logical decoding found consistent point at 0/16B2BD8
2021-02-08 17:07:55.224 GMT [29] DETAIL:  There are no running transactions.
2021-02-08 17:07:55.224 GMT [29] LOG:  exported logical decoding snapshot: "00000004-0000000B-1" with 0 transaction IDs
2021-02-08 17:07:55.475 GMT [29] LOG:  starting logical decoding for slot "xjoin_inventory_v1_1"
2021-02-08 17:07:55.475 GMT [29] DETAIL:  streaming transactions committing after 0/16B2C10, reading WAL from 0/16B2BD8
2021-02-08 17:07:55.475 GMT [29] LOG:  logical decoding found consistent point at 0/16B2BD8
2021-02-08 17:07:55.475 GMT [29] DETAIL:  There are no running transactions.
2021-02-08 17:15:04.007 GMT [38] ERROR:  relation "hosts" does not exist at character 471
2021-02-08 17:15:04.007 GMT [38] STATEMENT:  SELECT hosts.id AS hosts_id, hosts.account AS hosts_account, hosts.display_name AS hosts_display_name, hosts.ansible_host AS hosts_ansible_host, hosts.created_on AS hosts_created_on, hosts.modified_on AS hosts_modified_on, hosts.facts AS hosts_facts, hosts.tags AS hosts_tags, hosts.canonical_facts AS hosts_canonical_facts, hosts.system_profile_facts AS hosts_system_profile_facts, hosts.stale_timestamp AS hosts_stale_timestamp, hosts.reporter AS hosts_reporter 
	FROM hosts 
	WHERE hosts.account = 'test' AND (hosts.canonical_facts ->> 'insights_id') = '28c7816c-81fd-4b72-9f7a-784edb01aa1c' AND (hosts.stale_timestamp > '2021-02-08T17:15:03.997565+00:00'::timestamptz OR hosts.stale_timestamp > '2021-02-01T17:15:03.997565+00:00'::timestamptz AND hosts.stale_timestamp <= '2021-02-08T17:15:03.997565+00:00'::timestamptz OR hosts.stale_timestamp > '2021-01-25T17:15:03.997565+00:00'::timestamptz AND hosts.stale_timestamp <= '2021-02-01T17:15:03.997565+00:00'::timestamptz OR hosts.stale_timestamp IS NULL) 
	 LIMIT 1
2021-02-08 17:17:25.898 GMT [38] ERROR:  relation "hosts" does not exist at character 471
2021-02-08 17:17:25.898 GMT [38] STATEMENT:  SELECT hosts.id AS hosts_id, hosts.account AS hosts_account, hosts.display_name AS hosts_display_name, hosts.ansible_host AS hosts_ansible_host, hosts.created_on AS hosts_created_on, hosts.modified_on AS hosts_modified_on, hosts.facts AS hosts_facts, hosts.tags AS hosts_tags, hosts.canonical_facts AS hosts_canonical_facts, hosts.system_profile_facts AS hosts_system_profile_facts, hosts.stale_timestamp AS hosts_stale_timestamp, hosts.reporter AS hosts_reporter 
	FROM hosts 
	WHERE hosts.account = 'test' AND (hosts.canonical_facts ->> 'insights_id') = '8b4e6110-a846-4305-aa6e-389338bd0bce' AND (hosts.stale_timestamp > '2021-02-08T17:17:25.896025+00:00'::timestamptz OR hosts.stale_timestamp > '2021-02-01T17:17:25.896025+00:00'::timestamptz AND hosts.stale_timestamp <= '2021-02-08T17:17:25.896025+00:00'::timestamptz OR hosts.stale_timestamp > '2021-01-25T17:17:25.896025+00:00'::timestamptz AND hosts.stale_timestamp <= '2021-02-01T17:17:25.896025+00:00'::timestamptz OR hosts.stale_timestamp IS NULL) 
	 LIMIT 1
2021-02-08 17:17:33.613 GMT [38] ERROR:  relation "hosts" does not exist at character 471
2021-02-08 17:17:33.613 GMT [38] STATEMENT:  SELECT hosts.id AS hosts_id, hosts.account AS hosts_account, hosts.display_name AS hosts_display_name, hosts.ansible_host AS hosts_ansible_host, hosts.created_on AS hosts_created_on, hosts.modified_on AS hosts_modified_on, hosts.facts AS hosts_facts, hosts.tags AS hosts_tags, hosts.canonical_facts AS hosts_canonical_facts, hosts.system_profile_facts AS hosts_system_profile_facts, hosts.stale_timestamp AS hosts_stale_timestamp, hosts.reporter AS hosts_reporter 
	FROM hosts 
	WHERE hosts.account = 'test' AND (hosts.canonical_facts ->> 'insights_id') = 'd84bfc83-2c4a-4de4-b955-439768fcb087' AND (hosts.stale_timestamp > '2021-02-08T17:17:33.611281+00:00'::timestamptz OR hosts.stale_timestamp > '2021-02-01T17:17:33.611281+00:00'::timestamptz AND hosts.stale_timestamp <= '2021-02-08T17:17:33.611281+00:00'::timestamptz OR hosts.stale_timestamp > '2021-01-25T17:17:33.611281+00:00'::timestamptz AND hosts.stale_timestamp <= '2021-02-01T17:17:33.611281+00:00'::timestamptz OR hosts.stale_timestamp IS NULL) 
	 LIMIT 1
2021-02-08 17:17:43.503 GMT [38] ERROR:  relation "hosts" does not exist at character 471
2021-02-08 17:17:43.503 GMT [38] STATEMENT:  SELECT hosts.id AS hosts_id, hosts.account AS hosts_account, hosts.display_name AS hosts_display_name, hosts.ansible_host AS hosts_ansible_host, hosts.created_on AS hosts_created_on, hosts.modified_on AS hosts_modified_on, hosts.facts AS hosts_facts, hosts.tags AS hosts_tags, hosts.canonical_facts AS hosts_canonical_facts, hosts.system_profile_facts AS hosts_system_profile_facts, hosts.stale_timestamp AS hosts_stale_timestamp, hosts.reporter AS hosts_reporter 
	FROM hosts 
	WHERE hosts.account = 'test' AND (hosts.canonical_facts ->> 'insights_id') = '4c363eb2-a764-4c5d-a429-58f3bcac1704' AND (hosts.stale_timestamp > '2021-02-08T17:17:43.500660+00:00'::timestamptz OR hosts.stale_timestamp > '2021-02-01T17:17:43.500660+00:00'::timestamptz AND hosts.stale_timestamp <= '2021-02-08T17:17:43.500660+00:00'::timestamptz OR hosts.stale_timestamp > '2021-01-25T17:17:43.500660+00:00'::timestamptz AND hosts.stale_timestamp <= '2021-02-01T17:17:43.500660+00:00'::timestamptz OR hosts.stale_timestamp IS NULL) 
	 LIMIT 1
2021-02-08 20:11:17.770 GMT [1] LOG:  received smart shutdown request
2021-02-08 20:11:17.777 GMT [1] LOG:  worker process: logical replication launcher (PID 24) exited with exit code 1
2021-02-08 20:20:51.871 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-02-08 20:20:51.871 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2021-02-08 20:20:51.897 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-02-08 20:20:51.928 GMT [18] LOG:  database system was interrupted; last known up at 2021-02-08 17:09:55 GMT
2021-02-08 20:20:52.030 GMT [18] LOG:  database system was not properly shut down; automatic recovery in progress
2021-02-08 20:20:52.035 GMT [18] LOG:  redo starts at 0/16B2CA8
2021-02-08 20:20:52.036 GMT [18] LOG:  invalid record length at 0/16B2D88: wanted 24, got 0
2021-02-08 20:20:52.036 GMT [18] LOG:  redo done at 0/16B2D50
2021-02-08 20:20:52.081 GMT [1] LOG:  database system is ready to accept connections
2021-02-08 20:21:04.628 GMT [27] LOG:  starting logical decoding for slot "xjoin_inventory_v1_1"
2021-02-08 20:21:04.628 GMT [27] DETAIL:  streaming transactions committing after 0/16B2C10, reading WAL from 0/16B2C10
2021-02-08 20:21:04.628 GMT [27] LOG:  logical decoding found consistent point at 0/16B2C10
2021-02-08 20:21:04.628 GMT [27] DETAIL:  There are no running transactions.
2021-02-08 20:25:47.609 GMT [34] ERROR:  relation "hosts" d [...]

2021-02-12 20:11 UTC, kruai commented on README.md
> +make run_inv_mq_service_test_producer
And here are my versions:
```
docker-compose version 1.27.4, build unknown
Docker version 19.03.13, build 4484c46
```
I sure hope using Docker 19 vs Docker 20 wouldn't be causing this issue. @tahmidefaz , what versions are you running?

2021-02-12 20:15 UTC, fijshion commented on README.md
> +make run_inv_mq_service_test_producer
I'm starting to think it might be an issue with the docker versions. Maybe [the {PWD} directive](https://github.com/RedHatInsights/xjoin-kstreams/blob/b582f43679647f5111a4336d4f1cb63db9f488a7/docker-compose.yml#L53) is handled differently between versions. Just for testing, could you try specifying the absolute path to that file? Also make sure the file exists just in case.

2021-02-12 20:27 UTC, kruai commented on README.md
> +make run_inv_mq_service_test_producer
I was scrolling through the logs and saw:
```
WARNING: The PWD variable is not set. Defaulting to a blank string.
```
The solutions I'm seeing online say you can just replace all the `${PWD}` instances with `.`; I'll give it a shot

2021-02-12 20:32 UTC, kruai commented on README.md
> +make run_inv_mq_service_test_producer
Rats, I thought for sure that would work. Same error :/

2021-02-23 20:17 UTC, tahmidefaz approved these changes
Not sure where we ended up on the above thread, but I am approving this under the impression that the issue has something to do with my local docker config.

2021-02-23 21:05 UTC, kruai approved these changes
I don't wanna hold this up, either. Tahmid and I can look into the issue we're running into and update the documentation later.

2021-03-26 14:45 UTC, merged