WIP: RHCLOUD-11719 Sparse fieldset sp toplevel
RedHatInsights/insights-host-inventory pull request #805
Opened 2021-02-03 20:18 UTC by tahmidefaz

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-11719).
(A description of your PR's changes goes here.)

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-02-05 15:47 UTC, tahmidefaz commented
I know this is a decent size PR, but the main changes are in `api/api_parsing`, `api/fields_parser` and `api/system_profile_host_list`.

2021-02-10 14:31 UTC, ryandillinfelton commented
Jotting down notes during walk through:
- why separate field parsing from parsing.py?
- have you made sure that the new field parsing doesn't cause unexpected behavior on filter
- Should we fall back to the DB?

Tests:
- Unit tests for new order_by (especially with weird characters that sorts differently on different platforms)
- Tests to insure new array support doesn't wack out filter payload

I'll edit this if it turns out some of these are handled when I review

2021-02-10 21:25 UTC, tahmidefaz commented
@ryandillinfelton 

> why separate field parsing from parsing.py?

I remember QE wanting to extract the fields to deep object parsing into a library in the future. That was my main reasoning behind separating it into a different file.

2021-02-10 22:24 UTC, ryandillinfelton requested changes
Most of it looks good, but there's a bug that needs fixing :(. I also think it would be good to add a test case that would catch the bug I identified to make sure it doesn't pop back up. Otherwise all the tests make sense to me (except the kinda nitpicky comment I left on one) and the coverage seems pretty good. The only other things I have are organizational/structure suggestions.

2021-02-10 22:24 UTC, ryandillinfelton commented on api/system_profile_host_list.py
> +            host_ids = [{"id": {"eq": host_id}} for host_id in host_id_list]
This causes a 500 if you give it any other string as the index i.e. `hosts/f{host_id_list}/system_profile?fields[foo]=bar`
since the request never gets made, and as a  result `response_list` is not defined when you try to return it.

I think you either need to some of the request logic outside of this block, or make the initial check on line 62 that decides between using the database and xjoin stricter.

2021-02-11 12:46 UTC, RonnyPfannschmidt commented on api/parsing.py
> +from api.fields_parser import custom_fields_parser
from the code management perspective its entirely ok to put this into the parsing file for now

as its currently integrated in the deep object parsing, its not yet extract-able anyway

2021-02-11 12:47 UTC, RonnyPfannschmidt commented on swagger/api.spec.yaml
> -      operationId: api.host.get_host_system_profile_by_id
the operation id change is a breaking api change

2021-02-12 21:51 UTC, tahmidefaz commented on tests/helpers/api_utils.py
> +    "/api/inventory/v1/hosts/6e7b6317-0a2d-4552-a2f2-b7da0aece49d,22cd8e39-13bb-4d02-8316-84b850dc5136/system_profile"
If I can remember, I opt-out from using the `build_system_profile_url` function is because it expects host objects as the parameter value for `host_list_or_id`. Anyways, I have changed the tests to use a `minimal_host` instances :+1:

2021-02-12 21:56 UTC, tahmidefaz commented on api/system_profile_host_list.py
> +            host_ids = [{"id": {"eq": host_id}} for host_id in host_id_list]
I changed this to check for the `system_profile` key if a user provides the `fields` parameter. If it can't find `system_profile` in `fields`, we now throw a good ol' `400` on their face. 
Great catch! Thanks! :+1:

2021-02-12 22:03 UTC, tahmidefaz commented on api/parsing.py
> +from api.fields_parser import custom_fields_parser
I tried to think of how we can separate it from the deep object parsing in a clean way, but I couldn't think of one. If you have any suggestions, feel free to let me know. Seems like we first have to define the parsing library before we can make it extractable.  Since it's not that extract-able atm, I have copied the function over to `api/parsing.py`.

2021-02-15 15:27 UTC, tahmidefaz commented on swagger/api.spec.yaml
> -      operationId: api.host.get_host_system_profile_by_id
@RonnyPfannschmidt did you mentioned this for reference purposes?

2021-02-15 16:37 UTC, RonnyPfannschmidt commented on swagger/api.spec.yaml
> -      operationId: api.host.get_host_system_profile_by_id
if we have that spec deployed to prod as it was before, we cant change the name without putting in a deprecated version

2021-02-15 18:21 UTC, ryandillinfelton approved these changes

2021-02-15 18:50 UTC, kruai submitted a review, later dismissed
This looks good to me, though I'm curious about the point Ronny raised.

2021-02-15 18:52 UTC, kruai commented on swagger/api.spec.yaml
> -      operationId: api.host.get_host_system_profile_by_id
@RonnyPfannschmidt Would just changing the operationId actually break anything? I thought that just pointed to the method used for that request. The new path param is optional, and the schema for the return value hasn't changed. What would break, exactly?

2021-02-15 19:53 UTC, RonnyPfannschmidt commented
the changed operation id changes method names in generated clients

2021-02-15 22:33 UTC, thearifismail commented on api/system_profile_host_list.py
> +        if not xjoin_enabled():
This assumes that xjoin is always enabled.  If that's the assumption then it is not being enforced anywhere else.

2021-02-15 22:40 UTC, thearifismail commented on api/host.py
> -def get_host_system_profile_by_id(host_id_list, page=1, per_page=100, order_by=None, order_how=None):
`get_host_system_profile_by_id` should be placed back into `api/host.py` and redirect traffic the way `get_host_list` does

2021-02-15 23:22 UTC, thearifismail reviewed
pytests and manual tests using postman worked.  That said, a couple of gaps were realized that have been reported in:

1. https://issues.redhat.com/browse/RHCLOUD-12387
2. https://issues.redhat.com/browse/RHCLOUD-12388

2021-02-16 13:19 UTC, tahmidefaz commented on api/system_profile_host_list.py
> +        if not xjoin_enabled():
Can you elaborate here a little bit? Yes, it should assume that xjoin is always enabled, otherwise, we throw a `5xx` on xjoin enabled functionalities.

2021-02-16 13:22 UTC, tahmidefaz commented
> pytests and manual tests using postman worked. That said, a couple of gaps were realized that have been reported in:
> 
> 1. https://issues.redhat.com/browse/RHCLOUD-12378
> 2. https://issues.redhat.com/browse/RHCLOUD-12388

@thearifismail I think you linked the wrong ticket for no. 1. Please update.

2021-02-16 16:07 UTC, thearifismail commented on api/system_profile_host_list.py
> +        if not xjoin_enabled():
Since it is an openAPI, it is a contract that HBI announced and should not change endpoints without proper announcements.

I think the request should come to `api/host/get_host_system_profile_by_id`, then it should check if `x-rh-cloud-bulk-query-source == xjoin`, then it should send to xjoin else, it should serve the request itself.

2021-02-16 18:20 UTC, tahmidefaz commented on api/system_profile_host_list.py
> +        if not xjoin_enabled():
@thearifismail I am moving this to `api/host`. 

Question: If `xjoin` is down, and we receive a sparse fields request, how would HBI serve this request by itself?

2021-02-16 22:48 UTC, ryandillinfelton commented on api/system_profile_host_list.py
> +        if not xjoin_enabled():
If xjoin is down and we get a request for system profile that uses the spare feildset query responding with a **500** is correct because part of our service is compromised. It's the same thing we do the the `/tags` endpoint which relies on xjoin and has no db equivalent. If the user specifies db as the data-source in the header of their request to `/tags` HBI responds with a **503**. If xjoin-search is down it responds with a plain **500** because it needs xjoin-search up to serve the response.

I believe what is currently set up in this PR is that queries that don't specify a sparse fieldset are fulfilled the same way they were before, directly querying the database. However if the user asks for a sparse fieldset we fulfill with xjoin. I don't see much point in duplicating the sparse fieldset functionality for the database since every environment defaults to xjoin as the data source, and we should expect xjoin to have reliable uptime.

2021-02-17 16:02 UTC, kruai commented
> pytests and manual tests using postman worked. That said, a couple of gaps were realized that have been reported in:
> 
> 1. https://issues.redhat.com/browse/RHCLOUD-12378
> 2. https://issues.redhat.com/browse/RHCLOUD-12388

@thearifismail For the first Jira, did you mean [this one](https://issues.redhat.com/browse/RHCLOUD-12387)? (CC @tahmidefaz )

2021-02-17 16:07 UTC, kruai approved these changes
Still LGTM! I think it's a good call to keep the same operationID, and just have the functionality not change if the `fields` param isn't provided.

2021-02-17 18:04 UTC, thearifismail commented on api/system_profile_host_list.py
> +        if not xjoin_enabled():
Agree after hearing the rationale this morning that `xjoin` is a MUST WORK service.

2021-02-17 20:15 UTC, thearifismail approved these changes
BTW for specifying a bogus parameter, the following was returned:

2021-02-17 21:48 UTC, tahmidefaz commented
@thearifismail 
> Question: Should it show a warning/error that the requested field does not exist and check the name or spelling?

Eventually, we would throw a `400` if a requested field does not exist in the schema, but as a first approach, we decided not to pursue it as part of this pr.

2021-02-18 13:40 UTC, merged

2021-02-18 16:17 UTC, RonnyPfannschmidt commented
jsut as a fyi - https://issues.redhat.com/browse/RHCLOUD-12512 tracks the throwing error on invalid fields