[WIP] Generate a consistent api_key for user, system, or classic auth_types every time
RedHatInsights/insights-host-inventory pull request #806
Opened 2021-02-04 01:01 UTC by thearifismail

## Overview

Submitting this script for generating a consistent apiKey.  Using the same owner_id every and not worrying whether there were new line in the identity json will save a lot of time.

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-02-11 01:11 UTC, ryandillinfelton commented on utils/create_api_key.py
> +    print("")
newlines could clean this up a bit, but I see no reason to block on cleanliness for a utility script :shrug:.

2021-02-11 01:17 UTC, ryandillinfelton requested changes
Could you add en example of how to use the script in the comment at the top of the file and/or in the README?

Otherwise it looks fine, I just suggested some small nice to have changes.

Thanks for fixing the UUIT in test_utils BTW

2021-02-11 01:17 UTC, ryandillinfelton commented on utils/create_api_key.py
> +  thinking about new-line character, which is add by default when using
```suggestion
  thinking about new-line character, which is added by default when using
```

2021-02-16 00:24 UTC, thearifismail commented on utils/create_api_key.py
> +  thinking about new-line character, which is add by default when using
Thanks @ryandillinfelton for the review.  Replaced blank line prints with new-line character.  Also created CONSTANTS for each identity type for future used in tests and kafka_producer for having one source.

2021-02-17 18:54 UTC, ryandillinfelton commented
Thanks for adding an example to the script. I still think an addition to the readme.md would be nice to expose that the script exists at all to people unfamiliar with the project but I'll leave that up to you and approve now. There is a conflict that needs to be sorted out but I don't think that will dismiss my review. If I'm wrong just ping me on slack and I can re-approve.

2021-02-17 18:55 UTC, ryandillinfelton submitted a review, later dismissed

2021-02-22 17:04 UTC, thearifismail commented
Putting `on hold` until [Use identity for adding and updating hosts](https://github.com/RedHatInsights/insights-host-inventory/pull/814) is merged

2021-02-22 20:09 UTC, ryandillinfelton requested changes
Sorry to keep requesting changes. I just had some suggestions to make to correct a few trypos and inconsistencies

2021-02-22 20:09 UTC, ryandillinfelton commented on README.md
> +For creating and accessing hosts in the insights-inventory database, it is important to know which api key was used to create a host.  There have been occasions when a considerable amount of time was
I think this could be made more concise. Also some suggestions for the sake of consistance (e.g. apiKey vs API key, and json to JSON.
```suggestion
When accessing hosts the inventory API, it is important to know which API key was used to create the host. If you are not seeing the hosts you have created in responses from the API an API key mismatch may be the cause. To avoid such problems, generate the same API key every time using the same input JSON for a desired authentication type:
```

2021-02-22 20:09 UTC, ryandillinfelton commented on README.md
> +It outputs a base64-encode apiKey alongwith the json used for generating the key
just some little typos and changes to maintain consistency. 
```suggestion
This outputs a base64 encoded API key along with the JSON used for generating the key
```

2021-04-08 13:55 UTC, closed without merging