add rhsm to marshmallow
RedHatInsights/insights-host-inventory pull request #808
Opened 2021-02-08 20:30 UTC by beav

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/HBISPSC-33).

This adds "rhsm" to match a similar PR in inventory schema.

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-02-08 20:38 UTC, tahmidefaz requested changes
@beav we actually need the schema changes here as well. You can find the schema under `swagger/system_profile.spec.yaml`

2021-02-08 20:51 UTC, tahmidefaz approved these changes
LGTM :+1:

2021-02-08 20:55 UTC, kruai requested changes

2021-02-08 20:55 UTC, kruai commented on app/models.py
> +    version = fields.Str(validate=marshmallow_validate.Length(max=256))
This is a tiny issue, but I think this should be `max=255` based on the change in the spec

2021-02-08 20:59 UTC, ryandillinfelton commented on swagger/system_profile.spec.yaml
> +            example: "8.1"
Is this example correct? If we're expecting strings like this 255 characters feels a little unnecessarily long.

2021-02-08 21:02 UTC, kruai commented on swagger/system_profile.spec.yaml
> +            example: "8.1"
That's also a good point

2021-02-09 14:21 UTC, kruai approved these changes
Looks like it matches up now. Did we decide to shorten the max length or keep it at 255?

2021-02-09 14:22 UTC, kruai commented
> Looks like it matches up now. Did we decide to shorten the max length or keep it at 255?

I saw a conversation on another thread saying that the length is fine. LGTM :+1:

2021-02-09 14:42 UTC, tahmidefaz approved these changes
LGTM! :+1:

2021-02-09 14:42 UTC, tahmidefaz approved these changes
LGTM!

2021-02-09 14:42 UTC, merged