[[WIP] Add per_reporter_staleness tracking [RHC-z12221]
RedHatInsights/insights-host-inventory pull request #810
Opened 2021-02-16 22:21 UTC by ryandillinfelton

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-12221).

This PR is to add a new column to the database for tracking when individual reporters last checked in a host. This PR does not contain any of the filtering work that this data will be used for. All this is/should be is a migration for adding the new jsonb column to the db, changes to host updating and creation to insure we are setting the values in this new column, and tests to make sure that's happening correctly.

The design document for the data formatting (and it's relation to the filters we will add later) is [here](https://docs.google.com/document/d/107ljikJHs5-mj7n2eUt3dIUlRO6R9_VQi3tssqGTM9Y/edit?usp=sharing).

I took some liberties with the final names, they're a little longer, but I think that helps avoid ambiguity. Let me know what you think when you review.

:raccoon: 

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-02-17 09:38 UTC, RonnyPfannschmidt commented on migrations/versions/3d06b0a8828f_add_per_reporter_staleness_column.py
> +    op.add_column("hosts", sa.Column("per_reporter_staleness", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
should we consider this as non-nullable with a default of a empty mapping ? 
that could ease some of the logic

2021-02-17 09:50 UTC, RonnyPfannschmidt commented on app/models.py
> +        self.per_reporter_staleness[reporter]["stale_timestamp"] = stale_timestamp.isoformat()
this needs extra tooling inform sqlalchemy of the field update

`orm.attributes.flag_modified(self, "per_reporter_staleness")` at the end should do the trick

as we ensure `self.per_reporter_staleness[reporter]` is a mapping, i suggest to use a compact dict.update call

```python
self.per_reporter_staleness[reporter].update(
        stale_timestamp=stale_timestamp.isoformat(),
        last_check_in=datetime.now(timezone.utc).isoformat(),
        check_in_succeeded=True,
    )

2021-02-19 18:46 UTC, ryandillinfelton commented on tests/test_unit.py
> -    def test_updated_when_empty(self):
We can't create hosts without reporter or staleness timestamp anymore so I think this test is pretty pointless, and basically impossible to actually do.

2021-02-19 19:25 UTC, RonnyPfannschmidt commented on migrations/versions/3d06b0a8828f_add_per_reporter_staleness_column.py
> +    op.execute("UPDATE hosts SET per_reporter_staleness = '{}'::jsonb WHERE per_reporter_staleness is NULL;")
i believe its possible to use `text("'{}'::jsonb")` as a default

is there a structural difference between adding a null column + update and adding a default value?

2021-02-19 21:01 UTC, ryandillinfelton commented on migrations/versions/3d06b0a8828f_add_per_reporter_staleness_column.py
> +    op.execute("UPDATE hosts SET per_reporter_staleness = '{}'::jsonb WHERE per_reporter_staleness is NULL;")
Nope! switched it over. I did however find that, while it will insure the the field is initialized for all the hosts in the db which I expect will be good for filtering queries based on the field, we still need the logic initializing the field in models.

2021-02-19 21:02 UTC, ryandillinfelton commented
Tests should now be passing :frog:

2021-02-22 21:05 UTC, kruai requested changes
I just have a couple notes on this one

2021-02-22 21:05 UTC, kruai commented on tests/test_models.py
> +    # per_reporter_timestamp = {"yupana": {"last_check_in": now(), "stale_timestamp": n}}
Commented-out code should be removed

2021-02-22 21:05 UTC, kruai commented on tests/test_models.py
> +    # TODO: finish this test
Is it finished? If so, please remove this comment

2021-02-22 21:09 UTC, ryandillinfelton commented on tests/test_models.py
> +    # TODO: finish this test
yep! Just pushed a commit removing the things you pointed out :+1:

2021-02-22 21:14 UTC, kruai approved these changes
LGTM!

2021-02-22 21:44 UTC, thearifismail reviewed
Needs a couple of tests with a host reported by more than one reporter and with different stalessness times

2021-02-23 08:45 UTC, RonnyPfannschmidt commented on migrations/versions/3d06b0a8828f_add_per_reporter_staleness_column.py
> +            server_default="{}",
i vaguely recall requiring a text element here wit the server side value of the data

2021-02-23 19:30 UTC, tahmidefaz commented on migrations/versions/3d06b0a8828f_add_per_reporter_staleness_column.py
> +            server_default="{}",
@ryandillinfelton is this autogenerated?

2021-02-23 19:45 UTC, ryandillinfelton commented on migrations/versions/3d06b0a8828f_add_per_reporter_staleness_column.py
> +            server_default="{}",
Not auto generated. Yeah, Ronny is right. Not sure what happened that it changed. I"ll change it back.

2021-02-23 19:59 UTC, tahmidefaz commented
Apart from the concern raised by Ronny, other changes look good to me :+1:

2021-02-23 20:01 UTC, ryandillinfelton commented
> Needs a couple of tests with a host reported by more than one reporter and with different stalessness times

That's what the test I added does. It reports twice with puptoo to test overwriting, then once with yupana to insure multiple reporters work, and a new reporter does not alter existing per_reporter data.

https://github.com/RedHatInsights/insights-host-inventory/pull/810/files#diff-0adb667cd397bd56edce10eec11e1b10821740a10d72bd148b09645fc9108968R412

2021-02-23 20:41 UTC, ryandillinfelton commented on migrations/versions/3d06b0a8828f_add_per_reporter_staleness_column.py
> +            server_default="{}",
wait, it's the same thing it was just collapsed. I'm not sure I follow @RonnyPfannschmidt

2021-02-23 20:48 UTC, RonnyPfannschmidt commented on migrations/versions/3d06b0a8828f_add_per_reporter_staleness_column.py
> +            server_default="{}",
@ryandillinfelton i do recall that the jsonb form for a default would have to be used in a text element, im now crosschecking the docs, i may have missed a feature addition to make it simpler

2021-02-23 21:01 UTC, RonnyPfannschmidt commented on migrations/versions/3d06b0a8828f_add_per_reporter_staleness_column.py
> +            server_default="{}",
it seems sqlalchemy handles the details

2021-02-23 21:08 UTC, ryandillinfelton commented on migrations/versions/3d06b0a8828f_add_per_reporter_staleness_column.py
> +            server_default="{}",
Okay. So all good?

2021-02-24 15:28 UTC, RonnyPfannschmidt commented on app/models.py
> +        per_reporter_staleness=None,
im wondering, should this perhaps not be passed in `__init__` as a parameter and instead always be set to a new empty-dict (i recall that instance reconstruction in sqlalchemy skips the ctor)

2021-02-24 15:30 UTC, RonnyPfannschmidt commented on app/models.py
> +        per_reporter_staleness=None,
(this is fine as followup)

2021-02-24 16:55 UTC, kruai commented on app/models.py
> +        per_reporter_staleness=None,
@RonnyPfannschmidt would having it be set to `None` cause issues? And if so, should we also be doing that for `system_profile_facts`?

2021-02-24 18:19 UTC, ryandillinfelton commented on app/models.py
> +        per_reporter_staleness=None,
I think the correct thing to do is just remove it since the values in per_reporter_staleness should always and only be determined by the values of `reporter` and `stale_timestamp` to avoid discrepancies.

2021-02-24 19:02 UTC, thearifismail approved these changes
LGTM

2021-02-24 19:05 UTC, merged