Use identity for adding and updating hosts
RedHatInsights/insights-host-inventory pull request #814
Opened 2021-02-18 19:08 UTC by thearifismail

## Overview

This PR is being created to address [RHCLOUD-11482](https://issues.redhat.com/browse/RHCLOUD-11482).

It is about using `identity` when `adding` or `updating` a `host` in the `insights-inventory`.  When a Kafka message is received, its identity is retrieved from the message's platform_metadata.  If the identity type is `User`, then the host is saved and subsequent access to this host is granted using RBAC.  If the identity type is `System`, then the host's `system_profile['owner_id']` must match the "CN" in the `identity['system']['cn']`.  If the `owner_id` does not match the "CN", then an error is raised stating, "The owner in host does not match the owner in identity".

When adding a host, the `identity type` is `system` but `host['system_profile']['owner_id']` is not provided, then the `owner_id` is set to the `identity['system']['cn']`.  Once a system has been created, it is accessible only when the "CN" in the `identity` matches the `owner_id`. 

The hosts reported by `rhsm-conduit` do not provide any `identity`.  In that case, the `host['system_profile']['owner_id']` is set to the "subscription_manager_id".  If a message is received without an `identity` and the host data is missing `subscription_manager_id`, the host is rejected.  If a message is received with no identity and the reporter is not rhsm-conduit, then the host is rejected.

This PR has a lot of code changes.  It is suggested to start the review from the `handle_message` method in `app/queue/queue.py` and follow the `add_host` and `find_existing_host` methods.  Among tests, major change is the use "User" and "System" as `identity types` and the use the use of`b64_identity` in `platform_metadata`.

I hope this helps.

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [x] Input Validation
- [x] Authentication and Password Management
- [x] Access Control
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Database Security
- [x] General Coding Practices

2021-02-22 23:39 UTC, kruai requested changes
I'm not sure I got to everything I wanted to comment on, but this is a huge PR and we might need to talk through it a bit. One of the biggest changes that caused ripples throughout the files is that the "identity" dict structure now has a top-level field called "identity". This required changes to be made across every file that used this structure, but I'm not yet convinced it was a necessary change.

I'm also nervous about using mock Identity values as the base for Identities we're actually using for hosts; these used to be in the test utils, but now they're being used for actual requests. It feels dangerous to use those as a base, especially when the values in the mocks look very believable, and would be way harder to track down than an account number named "test" or something like that.

Finally, I'm a little confused about our usage of the `Identity` class. It was defined and we use it in a few places, but most of the time, the code is just using the raw `dict` structure, and assuming all the keys are in the right place. I think if you leaned a little more on the class implementation, it could simplify the code in a lot of places.

2021-02-22 23:39 UTC, kruai commented on app/utils.py
> +            return self.__data == other.__data
It seems strange to implement a comparator that compares against just any dict. The `else` part of it I'm OK with, though again, I think it would break if you passed in any object that wasn't a dict or a HostWrapper

2021-02-22 23:39 UTC, kruai commented on tests/helpers/db_utils.py
> +log = logging.getLogger(__name__)
can we call this var `logger` for consistency with all the other instances?

2021-02-22 23:39 UTC, kruai commented on tests/helpers/test_utils.py
> +        "b64_identity": SYSTEM_API_KEY.decode("ascii"),
I'm a little confused... in the `SYSTEM_API_KEY` definition, it's encoded with UTF-8. Here's it's decoding from ASCII. I see UTF-8 and ASCII encoding/decoding in various places. Which one is it?

2021-02-22 23:39 UTC, kruai commented on tests/helpers/test_utils.py
> +    return SYSTEM_API_KEY.decode("ascii")
If you define this function above `get_platform_metadata_with_system_identity()`, you can use its value for "b64_identity" (small refactoring)

2021-02-22 23:39 UTC, kruai commented on tests/test_api_facts.py
> +    assert_response_status(response_status, 400)
Are you sure that's what we should expect here? `HTTP 400` is for bad/malformed requests. If we're trying to say "permission denied", isn't `HTTP 401` more appropriate?

2021-02-22 23:39 UTC, kruai commented on tests/test_deduplication.py
> +
delete this

2021-02-22 23:39 UTC, kruai commented on tests/test_deduplication.py
> +    # host = minimal_db_host(identity=USER_IDENTITY["identity"], canonical_facts=canonical_facts)
delete this

2021-02-22 23:39 UTC, kruai commented on utils/kafka_producer.py
> +
delete this

2021-02-23 14:04 UTC, thearifismail commented on app/auth/identity.py
> +        if isinstance(other, dict):
It is back to `    def __eq__(self, other):
        return self.account_number == other.account_number
`

2021-02-23 14:08 UTC, thearifismail commented on app/auth/identity.py
> +            return self.account_number == other.account_number
this snippet has been removed.

2021-02-23 15:43 UTC, thearifismail commented on app/queue/queue.py
> +    return json.loads(id)
Added exception handler

2021-02-23 18:02 UTC, thearifismail commented on app/queue/queue.py
> +        raise ValueError("Missing identity and the rhsm-conduit reporter, which does not use identity")
Fixed the comment and the message:
`def _get_identity(host, metadata):
    identity = None
    # Identity is required unless the reporter type is "rhsm-conduit"
    if not metadata.get("b64_identity") and not host.get("reporter") == "rhsm-conduit":
        raise ValueError("Provide identity or the reporter MUST be rhsm-conduit, which does not provide identity")
`

2021-02-23 18:06 UTC, thearifismail commented on tests/helpers/test_utils.py
> +    return SYSTEM_API_KEY.decode("ascii")
Done!

2021-02-23 18:52 UTC, thearifismail commented on tests/test_api_facts.py
> +    assert_response_status(response_status, 400)
Fixed the test to pass to use the correct identity

2021-02-23 18:53 UTC, thearifismail commented on tests/test_deduplication.py
> +
Done!!!

2021-02-23 18:59 UTC, thearifismail commented on utils/kafka_producer.py
> +
Gone!!!

2021-02-23 18:59 UTC, thearifismail commented on tests/test_deduplication.py
> +    # host = minimal_db_host(identity=USER_IDENTITY["identity"], canonical_facts=canonical_facts)
Gone!!!

2021-02-23 19:02 UTC, thearifismail commented on app/queue/queue.py
> +    base64_id = encoded_id
Fixed the code.

2021-02-23 19:13 UTC, thearifismail commented on app/queue/queue.py
> +    return json.loads(id)
Added exception handler

2021-02-23 19:14 UTC, thearifismail commented on app/queue/queue.py
> +        raise ValueError("Missing identity and the rhsm-conduit reporter, which does not use identity")
Updated the comment and  message

2021-02-23 19:15 UTC, thearifismail commented on app/queue/queue.py
> +    if not metadata.get("b64_identity") and host.get("reporter") == "rhsm-conduit":
This is not correct.  A better comment and message hopefully helps.

2021-02-23 19:20 UTC, thearifismail commented on app/queue/queue.py
> +    host = validated_operation_msg["data"]
Fixed.

2021-02-23 19:23 UTC, thearifismail commented on lib/identity.py
> +}
The reason is that `b64_identity` passed in by the reporters has {"identity": {value}} and needs handling.

2021-02-23 19:35 UTC, thearifismail commented on lib/identity.py
> +        "system": {"cert_type": "system", "cn": "1b36b20f-7fa0-4454-a6d2-008294e06378"},
This is CN is primarily used for testing.  Reporters are supposed to provide their identities, except `rhsm-conduit`, which does not have any identity when reporting a host BUT for subsequent access, `system` identity will be used.  That's the only reason that it is being used in the `queue` module; even then the dummy `CN` is replaced using `system_profile['owner_id] = SUBSCRIPTION_MANAGER_ID`

2021-02-23 19:51 UTC, thearifismail commented on app/queue/queue.py
> +    identity = Identity(identity.get("identity"))
It does seem so.  `_get_identity()` returns a dictionary with only one key `identity` at the top level.  That dictionary from _get_identity is used to create the identity object of type `Identity`

2021-02-23 21:08 UTC, thearifismail commented on app/queue/queue.py
> +# test for no system_profile or no owner_id,
Fixed the comment.

2021-02-23 21:49 UTC, thearifismail commented on app/utils.py
> +            return self.__data == other.__data
If the object is not a HostWrapper instance, then it should not be called.  That said, the check `if isinstance(other, dict):` his being used to make a couple of tests pass.  IMO, these tests should scrapped because the use of identity has rendered them un-passable without this hack.  

For now, I am removing this hack and commenting out these bad tests.

2021-02-23 21:50 UTC, thearifismail commented on tests/helpers/db_utils.py
> +log = logging.getLogger(__name__)
Done!

2021-02-23 22:32 UTC, thearifismail commented on tests/helpers/test_utils.py
> +        "b64_identity": SYSTEM_API_KEY.decode("ascii"),
reporters provide `utf-8` encoded `b64_identity`, which has to be decoded to ASCII in platform-metadata.  Without ASCII decoding, the apiKey remains in `bytes` format and is not `JSON serializable`.   To make it JSON serializable, it must be decoded to `ASCII`, otherwise `return json.dumps(message).encode("utf-8")` throws `TypeError: Object of type 'bytes' is not JSON serializable` error

2021-02-23 22:33 UTC, thearifismail commented on tests/helpers/test_utils.py
> +    return SYSTEM_API_KEY.decode("ascii")
Done!

2021-02-23 22:33 UTC, thearifismail commented on tests/test_api_facts.py
> +    assert_response_status(response_status, 400)
Fixed the test.

2021-02-23 22:34 UTC, thearifismail commented on tests/test_deduplication.py
> +
Gone!

2021-02-23 22:34 UTC, thearifismail commented on tests/test_deduplication.py
> +    # host = minimal_db_host(identity=USER_IDENTITY["identity"], canonical_facts=canonical_facts)
Gone!

2021-02-23 22:38 UTC, thearifismail commented on utils/kafka_producer.py
> +
Gone!

2021-03-02 20:34 UTC, lphiri commented
Reviewed  with @thearifismail . The general approach looks good to me ( review did not cover test coverage).

2021-03-02 21:51 UTC, kruai commented on app/queue/queue.py
> +    if not metadata.get("b64_identity") and host.get("reporter") == "rhsm-conduit":
The conditionals can still be refactored to the above logic to make the flow easier to follow (see the code block in my comment).

2021-03-02 22:10 UTC, kruai commented on lib/identity.py
> +        "system": {"cert_type": "system", "cn": "1b36b20f-7fa0-4454-a6d2-008294e06378"},
So... I understand this reasoning, but there are 2 sticking points for me:
- If these are values that should be used for testing, they should be defined in the test utils instead.
- If these variables are used in production, I'm nervous having the values pre-populated in case there's a logic error somewhere and we end up with mock data in our prod database

2021-03-02 22:21 UTC, kruai commented on app/queue/queue.py
> +    identity = Identity(identity.get("identity"))
It does return a dictionary, but... why doesn't it return an Identity? That would make a lot of this cleaner

2021-03-02 22:23 UTC, kruai commented on lib/identity.py
> +}
That's true, but you coded the functions that decode it and return the values; why not just have them return the "identity" node so you don't have to fetch "identity" each time? Better yet, why not initialize an Identity object from it, since the class is already defined? I think that would be a lot cleaner than passing around a dictionary

2021-03-02 22:26 UTC, kruai commented
I've left some responses, though I really think @ryandillinfelton and/or @tahmidefaz should take a look as well... I want to make sure my comments aren't off-base!

2021-03-03 21:39 UTC, thearifismail commented
> I've left some responses, though I really think @ryandillinfelton and/or @tahmidefaz should take a look as well... I want to make sure my comments aren't off-base!

@kruai , All issue have been addressed.  The issues were:

1. refactored the checks for `identity` and `rhsm-conduit`
2. removed the `identity` keyword from the `identity` object.
3. removed the identity file from lib directory and put it back in `test_utils`.  For rhsm-reported systems, identity is created using a bare-bone dictionary with no `cn`.  The `cn` is set to the `subscription_manager_id` of the host.

2021-03-04 20:04 UTC, kruai requested changes
In addition to my inline comments, I just have a general question about these sweeping changes to our MQ tests. Are 100% of messages read from the Kafka queue going to both be of type "System" and have an identity (besides RHSM)? Because if they don't, it's gonna start breaking for a lot of people

2021-03-04 22:15 UTC, tahmidefaz commented on app/queue/queue.py
> +    identity = Identity(identity)
I agree with @kruai here, doing this will clear this PR up a little bit

2021-03-04 22:16 UTC, thearifismail commented on app/queue/queue.py
> +    "account_number": "sysaccount",
Gone!

2021-03-04 22:16 UTC, tahmidefaz commented
I do not have any additional comments at this point from what Asa mentioned. Good progress! We're almost there :+1:

2021-03-04 22:24 UTC, thearifismail commented on app/queue/queue.py
> +        raise json.JSONDecodeError(jde)
If a bad json is passed in, JSONDecodeError is raised instead of failure encountered somewhere down the line.

2021-03-04 23:23 UTC, thearifismail commented on tests/test_api_facts.py
> +        extra_data={"facts": DB_FACTS, "system_profile_facts": {"owner_id": SYSTEM_IDENTITY["system"].get("cn")}}
As the name indicates, the intent is to use "System" as account type to bypass RBAC.   Using `identity_type: system` requires `system_profile['ownd_id']` set to `cn`

2021-03-04 23:27 UTC, thearifismail commented on tests/test_api_facts.py
> +    host.account = SYSTEM_IDENTITY["account_number"]
A host created by the `db_create_host` fixtures has `account = `usraccount`, whereas `SYSTEM_IDENTITY["account_number"]` has  value `sysaccount`. That's why host.account is set to `sysaccount`

2021-03-04 23:29 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    host.account = SYSTEM_IDENTITY["account_number"]
Same reason as stated above.

2021-03-04 23:30 UTC, thearifismail commented on tests/test_api_hosts_update.py
> +    host.account = "sysaccount"
same reason as above.

2021-03-04 23:32 UTC, thearifismail commented on utils/payloads.py
> +
This `identity` key is to simulate what `puptoo` sends as `b64_identity`

2021-03-04 23:36 UTC, thearifismail commented on utils/payloads.py
> +    account = os.environ.get("INVENTORY_HOST_ACCOUNT", IDENTITY["identity"]["account_number"])
same reason as above.

2021-03-04 23:38 UTC, thearifismail commented on utils/payloads.py
> +        # "reporter": "rhsm-conduit",
To test a scenario using no-rhsm reporter.

2021-03-05 00:05 UTC, thearifismail commented on app/queue/queue.py
> +    "type": "System",
Now `_get_identity()` returns `Identity` instead of a dictionary

2021-03-05 00:06 UTC, thearifismail commented on app/queue/queue.py
> +    identity = None
Gone!

2021-03-05 00:06 UTC, thearifismail commented on app/queue/queue.py
> +            identity = SYSTEM_IDENTITY
Done!

2021-03-05 13:35 UTC, thearifismail commented on tests/test_mq_service.py
> -
This test was not valid anymore due to the way identity is used when adding a host.

2021-03-05 13:55 UTC, thearifismail commented on tests/test_mq_service.py
> +        print(str(ve))
Replaced `try/except` with `pytest.raises`

2021-03-05 14:05 UTC, thearifismail commented on tests/test_mq_service.py
> +    with pytest.raises(InventoryException):
Fixed!.

2021-03-05 14:06 UTC, thearifismail commented on tests/test_mq_service.py
> +
Gone!

2021-03-05 14:07 UTC, thearifismail commented on tests/test_mq_service.py
> +        assert_mq_host_data(key, event, expected_results, host_keys_to_check)
Gone!

2021-03-05 14:27 UTC, thearifismail commented on tests/test_mq_service.py
> +    }
Yep.  Gone! and removed other instances also. Now have `expected_results = {
        "host": {**host.data()},
    }
`

2021-03-05 14:29 UTC, thearifismail commented on tests/test_mq_service.py
> +        handle_message(json.dumps(message), mock_event_producer)
Fixed.  It was a left over snippet which should have been replaced by `pytest.raises()`

2021-03-05 15:12 UTC, thearifismail commented on app/queue/queue.py
> +    identity = Identity(identity)
Addressed all issues mentioned in this group of comments, except `Enum`.  Will use a separate commit for `Enum` because it affects multiple files.

2021-03-05 15:55 UTC, thearifismail commented on app/queue/queue.py
> +    identity = Identity(identity)
IMO, using `Enum` for `IdentityType` and `AuthTypes` should wait for now and be added in a separate PR.

2021-03-09 20:43 UTC, kruai commented on app/queue/queue.py
> +        raise json.JSONDecodeError(jde)
What do you mean? You're catching a JSONDecodeError and re-raising that same error. This is effectively the same as not having the try/except clause at all

2021-03-09 20:46 UTC, kruai commented on app/auth/identity.py
> +        elif identity.identity_type == "User":
The "System" and "User" identity types should also be enums, but this can wait for a follow-up PR.

2021-03-09 22:12 UTC, kruai requested changes
Things are looking better! 
Since we're doing the `identity_type` enum as a follow-up, I've created a task for it here: https://issues.redhat.com/browse/RHCLOUD-12861

2021-03-09 22:12 UTC, kruai commented on tests/test_mq_service.py
> -
Ah... it was replaced with `test_add_host_with_wrong_owner`, right?

2021-03-09 22:12 UTC, kruai commented on utils/payloads.py
> +        "system": {"cn": "1b36b20f-7fa0-4454-a6d2-008294e06378", "cert_type": "system"},
Should use the enum value for cert_type

2021-03-09 22:15 UTC, kruai commented on app/queue/queue.py
> +    identity = Identity(identity)
It looks like you added AuthTypes, but I've created a follow-up Jira for IdentityTypes here https://issues.redhat.com/browse/RHCLOUD-12861

2021-03-09 22:17 UTC, kruai commented on app/auth/identity.py
> +        elif identity.identity_type == "User":
(update: created here https://issues.redhat.com/browse/RHCLOUD-12861)

2021-03-09 22:21 UTC, kruai commented on utils/payloads.py
> +    account = os.environ.get("INVENTORY_HOST_ACCOUNT", IDENTITY["identity"]["account_number"])
I still had the same question as above :)

2021-03-10 18:20 UTC, thearifismail commented on tests/test_mq_service.py
> -
The messages structure was not the best, particularly wrapping the whole message in single quote.  Adding identity would increase the length beyond 120 chars, linters' limit for a line.  Rounding by linter produced bad message.  Until, I forced it work somehow.  Dues to the changed in identity code, the test did not work at all, so finally it was its to time to go.

2021-03-10 18:24 UTC, thearifismail commented on tests/test_api_auth.py
> -# TODO: Remove when workaround is no longer needed
it was related to `claassic-proxy` work around but has been removed because now a valid `CN` is expected per https://issues.redhat.com/browse/RHCLOUD-12798

2021-03-10 18:31 UTC, thearifismail commented on tests/helpers/test_utils.py
> +    "auth_type": "basic-auth",
`enum` values to be implemented in a separate PR.

2021-03-10 18:31 UTC, thearifismail commented on app/queue/queue.py
> +SYSTEM_IDENTITY = {"auth_type": "cert-auth", "system": {"cert_type": "system"}, "type": "System"}
`enum` values to be implemented in a separate PR.

2021-03-10 18:31 UTC, thearifismail commented on tests/helpers/test_utils.py
>      "auth_type": "cert-auth",
`enum` values to be implemented in a separate PR.

2021-03-10 18:31 UTC, thearifismail commented on utils/payloads.py
> +        "auth_type": "cert-auth",
`enum` values to be implemented in a separate PR.

2021-03-10 18:32 UTC, thearifismail commented on tests/helpers/test_utils.py
> +    "system": {"cert_type": "system", "cn": "1b36b20f-7fa0-4454-a6d2-008294e06378"},
`enum` values to be implemented in a separate PR.

2021-03-10 18:34 UTC, thearifismail commented on utils/payloads.py
> +        "system": {"cn": "1b36b20f-7fa0-4454-a6d2-008294e06378", "cert_type": "system"},
`enum` values to be implemented in a separate PR.

2021-03-10 18:36 UTC, thearifismail commented on utils/payloads.py
> +        # "insights_id": random_uuid(),
Gone!!!

2021-03-10 18:37 UTC, thearifismail commented on utils/payloads.py
> +
Done!

2021-03-10 18:39 UTC, thearifismail commented on utils/payloads.py
> +        # "reporter": "rhsm-conduit",
Changed to payloads.py are made based on what's being tests or was tested the last.   Need to update the test utility to not have to modify payloads.py

2021-03-10 20:28 UTC, kruai commented on app/queue/queue.py
> +SYSTEM_IDENTITY = {"auth_type": "cert-auth", "system": {"cert_type": "system"}, "type": "System"}
Ah - I misunderstood and thought you had created [2 Enums here](https://github.com/RedHatInsights/insights-host-inventory/blob/a5e2f8df186188c18323f0bf691937dc09268130/app/auth/identity.py#L15-L16). Resolving this conversation.

2021-03-10 20:29 UTC, kruai commented on tests/helpers/test_utils.py
>      "auth_type": "cert-auth",
(duplicate): I misunderstood and thought you had created [2 Enums here](https://github.com/RedHatInsights/insights-host-inventory/blob/a5e2f8df186188c18323f0bf691937dc09268130/app/auth/identity.py#L15-L16). Resolving this conversation.

2021-03-10 20:29 UTC, kruai commented on tests/helpers/test_utils.py
> +    "system": {"cert_type": "system", "cn": "1b36b20f-7fa0-4454-a6d2-008294e06378"},
(duplicate): I misunderstood and thought you had created [2 Enums here](https://github.com/RedHatInsights/insights-host-inventory/blob/a5e2f8df186188c18323f0bf691937dc09268130/app/auth/identity.py#L15-L16). Resolving this conversation.

2021-03-10 23:06 UTC, kruai requested changes
Phew, there are hundreds more lines of changes than the last time. I don't think these sweeping changes are the best way to approach this... I've left comments inline with more details

2021-03-16 13:27 UTC, thearifismail commented on tests/helpers/test_utils.py
> +            values["system_profile"]["owner_id"] = SYSTEM_IDENTITY["system"]["cn"]
Done!.  code not pushed yet

2021-03-16 22:12 UTC, thearifismail commented on tests/helpers/test_utils.py
> +
`minimal_host_owned_by_system` gone!

2021-03-16 22:14 UTC, thearifismail commented on tests/helpers/db_utils.py
> +def minimal_db_host(identity, **values):
Done.  Now an `account` is set using `**values`.

2021-03-17 16:04 UTC, kruai requested changes
I'm requesting many changes here, but most are repeated one-line issues. It's getting closer!

2021-03-17 16:04 UTC, kruai commented on tests/test_xjoin.py
> +        HOST_URL, SYSTEM_IDENTITY, extra_headers={"x-rh-cloud-bulk-query-source": "db"}
Same Q here about using SYSTEM_IDENTITY for these API requests. Again, won't copy/paste it for every instance in this file

2021-03-17 20:26 UTC, thearifismail commented on app/auth/identity.py
> +            validate(self)
Done.  Moved it to _get_identity function in queue

2021-03-17 20:53 UTC, thearifismail commented on tests/helpers/api_utils.py
> +    dict_ = {"identity": Identity(identity)._asdict()}
removed the unnecessary Identity creation.

2021-03-17 20:55 UTC, thearifismail commented on tests/helpers/api_utils.py
> +                url, SYSTEM_IDENTITY, query_parameters={"page": page, "per_page": per_page}
just to tests pagination using a system account

2021-03-17 21:35 UTC, thearifismail commented on tests/test_xjoin.py
> +        HOST_URL, SYSTEM_IDENTITY, extra_headers={"x-rh-cloud-bulk-query-source": "db"}
there are 4 tests in `tests/test-xjoin.py` which require `SYSTEM_IDENTITY` and 8 more tests using SYSTEM_IDENTITY but can use the default `USER_IDENTITY`.  For better coverage by SYSTEM_IDENTITY, used it in those tests.  There are a lot more tests testing xjoin use the default USER_IDENTITY

2021-03-17 21:48 UTC, thearifismail commented on tests/test_synchronizer.py
> +    created_host = db_create_host(USER_IDENTITY, host)
identity is required when a host info is passed to db_create_host()

2021-03-17 21:48 UTC, thearifismail commented on tests/test_synchronizer.py
> +    db_create_multiple_hosts(USER_IDENTITY, how_many=host_count)
identity is required when hosts info is passed to db_create_multiple_hosts()

2021-03-17 22:00 UTC, thearifismail commented on tests/test_system_profile.py
> +    response_status, response_data = api_get(url, SYSTEM_IDENTITY)
The tests using `mq_create_or_update_host` fixture require `api_get(url, SYSTEM_IDENTITY)` because the way the fixture was updated to test system_identity.

2021-03-17 22:01 UTC, thearifismail commented on tests/test_deduplication.py
> +    created_host = db_create_host(USER_IDENTITY, host)
identity is required when a host info is passed to db_create_host()

2021-03-17 22:02 UTC, thearifismail commented on tests/test_deduplication.py
> +    created_host = db_create_host(USER_IDENTITY, host)
identity is required when a host info is passed to db_create_host()

2021-03-17 22:03 UTC, thearifismail commented on tests/test_deduplication.py
> +    created_host = db_create_host(USER_IDENTITY, host)
identity is required when a host info is passed to db_create_host()

2021-03-17 22:03 UTC, thearifismail commented on tests/test_deduplication.py
> +    created_host = db_create_host(USER_IDENTITY, host)
test_find_host_using_superset_canonical_fact_match

2021-03-17 22:04 UTC, thearifismail commented on tests/test_culling.py
> +        created_host = db_create_host(USER_IDENTITY, host)
test_find_host_using_superset_canonical_fact_match

2021-03-17 22:05 UTC, thearifismail commented on tests/test_api_hosts_get.py
> +    response_status, response_data = api_get(HOST_URL, SYSTEM_IDENTITY)
identity is required when a host info is passed to db_create_host()

2021-03-17 22:05 UTC, thearifismail commented on tests/test_api_hosts_update.py
> +    created_host = db_create_host(USER_IDENTITY, host)
identity is required when a host info is passed to db_create_host()

2021-03-17 22:05 UTC, thearifismail commented on tests/test_api_hosts_update.py
> +    created_host = db_create_host(USER_IDENTITY, host)
identity is required when a host info is passed to db_create_host()

2021-03-17 22:05 UTC, thearifismail commented on tests/test_api_hosts_update.py
> +    created_host = db_create_host(USER_IDENTITY, host)
identity is required when a host info is passed to db_create_host()

2021-03-17 22:06 UTC, thearifismail commented on tests/test_api_hosts_get.py
> +# from tests.helpers.test_utils import USER_IDENTITY
Gone.

2021-03-17 22:07 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    hosts = db_create_multiple_hosts(USER_IDENTITY, how_many=3)
identity is required when hosts info is passed to db_create_multiple_hosts()

2021-03-17 22:07 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    hosts = db_create_multiple_hosts(USER_IDENTITY, how_many=2)
identity is required when hosts info is passed to db_create_multiple_hosts()

2021-03-17 22:08 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    hosts = db_create_multiple_hosts(USER_IDENTITY, how_many=2)
identity is required when hosts info is passed to db_create_multiple_hosts()

2021-03-17 22:08 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    hosts = db_create_multiple_hosts(USER_IDENTITY, how_many=2)
identity is required when hosts info is passed to db_create_multiple_hosts()

2021-03-17 22:09 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    db_create_host(USER_IDENTITY, host)
identity is required when a host info is passed to db_create_host()

2021-03-17 22:11 UTC, thearifismail commented on tests/fixtures/api_fixtures.py
> +        return do_request(flask_client.post, url, identity, host_data, query_parameters, extra_headers)
agree

2021-03-17 22:19 UTC, thearifismail commented on tests/helpers/api_utils.py
> +                url, SYSTEM_IDENTITY, query_parameters={"page": page, "per_page": per_page}
The tests using this utility require the use of SYSTEM_IDENTITY

2021-03-17 22:22 UTC, thearifismail commented on tests/helpers/api_utils.py
> +            response_status, response_data = api_get(url, SYSTEM_IDENTITY, query_parameters={parameter: invalid_value})
Removed though using both identity types worked.

2021-03-17 22:24 UTC, thearifismail commented on tests/helpers/api_utils.py
> +        url, SYSTEM_IDENTITY, query_parameters={"page": non_existent_page, "per_page": 1}
Removed though using both identity types worked.

2021-03-17 22:26 UTC, thearifismail commented on tests/helpers/test_utils.py
> +
Gone!

2021-03-17 22:28 UTC, thearifismail commented on tests/test_models.py
> +    existing_host = db_create_host(USER_IDENTITY, input_host)
identity is required when a host info is passed to db_create_host()

2021-03-17 22:28 UTC, thearifismail commented on tests/test_models.py
> +    created_host = db_create_host(USER_IDENTITY, input_host)
identity is required when a host info is passed to db_create_host()

2021-03-17 22:28 UTC, thearifismail commented on tests/test_models.py
> +        db_create_host(USER_IDENTITY, host)
identity is required when a host info is passed to db_create_host()

2021-03-17 22:28 UTC, thearifismail commented on tests/test_models.py
> +    db_create_host(USER_IDENTITY, host)
identity is required when a host info is passed to db_create_host()

2021-03-17 22:28 UTC, thearifismail commented on tests/test_models.py
> +    db_create_host(USER_IDENTITY, host)
identity is required when a host info is passed to db_create_host()

2021-03-17 22:28 UTC, thearifismail commented on tests/test_models.py
> +    db_create_host(USER_IDENTITY, host)
identity is required when a host info is passed to db_create_host()

2021-03-17 22:29 UTC, thearifismail commented on tests/test_models.py
> +    db_create_host(USER_IDENTITY, host)
identity is required when a host info is passed to db_create_host()

2021-03-17 22:29 UTC, thearifismail commented on tests/test_models.py
> +    db_create_host(USER_IDENTITY, inserted_host)
identity is required when a host info is passed to db_create_host()

2021-03-17 22:29 UTC, thearifismail commented on tests/test_deduplication.py
> +        created_host = db_create_host(USER_IDENTITY, host)
identity is required when a host info is passed to db_create_host()

2021-03-17 22:52 UTC, thearifismail commented on app/queue/queue.py
> +        raise "The account number in identity does not match the number in the host."
Now raises `ValidationException`

2021-03-17 22:54 UTC, thearifismail commented on tests/test_rbac.py
> +
Gone.

2021-03-17 23:22 UTC, thearifismail commented on tests/test_tags.py
> +    response_status, response_data = api_get(url, SYSTEM_IDENTITY)
The tests using mq_create_four_specific_hosts fixture require api_get(url, SYSTEM_IDENTITY) because the way the fixture was updated to test system_identity.

2021-03-17 23:29 UTC, thearifismail commented on tests/test_mq_service.py
> +    with pytest.raises(InventoryException):
Changed to pytest.raises(ValidationException)

2021-03-18 00:04 UTC, thearifismail commented on tests/test_culling.py
> +    response_status, response_data = api_get(HOST_URL, SYSTEM_IDENTITY)
SYSTEM_IDENTITY is required when a host is created using `mq_create_or_update_host`

2021-03-18 00:18 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +            assert_response_status(response_status, 404)
The test attempts to delete a host not created by it, so the host is not found that's why the error 404 is retuned by
`        if not query.count():
            flask.abort(status.HTTP_404_NOT_FOUND)
`

2021-03-18 00:21 UTC, thearifismail commented on tests/test_mq_service.py
> +        key, event, headers = mq_create_or_update_host(host, return_all_data=True)
for now changed it to pytest.raise(ValidationException)

2021-03-18 00:37 UTC, thearifismail commented on tests/test_mq_service.py
> +        key, event, headers = mq_create_or_update_host(host, return_all_data=True)
Changed to pytest.raises(ValidationException) and asserted for the exact message "The owner in host does not match the owner in identity"

2021-03-18 15:47 UTC, kruai requested changes
I responded to a lot of your comments, though I eventually stopped bc I ended up just copy/pasting

2021-03-18 15:47 UTC, kruai commented on tests/helpers/api_utils.py
> +    dict_ = {"identity": Identity(identity)._asdict()}
You didn't remove it, though...

2021-03-18 15:47 UTC, kruai commented on tests/helpers/api_utils.py
> +                url, SYSTEM_IDENTITY, query_parameters={"page": page, "per_page": per_page}
Can you please elaborate about why that identity is required? It doesn't make sense to me for our API tests to use `SYSTEM_IDENTITY`

2021-03-18 15:47 UTC, kruai commented on tests/test_api_hosts_delete.py
> +    db_create_host(USER_IDENTITY, host)
No, the Identity is an optional parameter. To pass the `host` param and not the `identity` one, you can just use `db_create_host(host=host)`

2021-03-18 15:47 UTC, kruai commented on tests/test_api_hosts_delete.py
> +    hosts = db_create_multiple_hosts(USER_IDENTITY, how_many=2)
No, it's optional. Same answer as above

2021-03-18 15:47 UTC, kruai commented on tests/test_api_hosts_delete.py
> +    hosts = db_create_multiple_hosts(USER_IDENTITY, how_many=2)
No, it's optional. Same answer as above

2021-03-18 15:47 UTC, kruai commented on tests/test_api_hosts_delete.py
> +            assert_response_status(response_status, 404)
That's not what this is testing, though. This is an RBAC test, which is attempting to validate that the RBAC checks restrict permissions correctly; this test isn't trying to test anything related to `owner_id`

2021-03-18 15:47 UTC, kruai commented on tests/test_api_hosts_delete.py
> +    hosts = db_create_multiple_hosts(USER_IDENTITY, how_many=2)
No, it's optional. Same answer as above

2021-03-18 15:47 UTC, kruai commented on tests/test_api_hosts_delete.py
> +    hosts = db_create_multiple_hosts(USER_IDENTITY, how_many=3)
No, it's optional. Same answer as above

2021-03-18 15:47 UTC, kruai commented on tests/test_api_hosts_get.py
> +    response_status, response_data = api_get(HOST_URL, SYSTEM_IDENTITY)
Actually the Identity param is optional, but that's not what I'm asking here. I'm asking why all of these API tests have been changed to use `SYSTEM_IDENTITY`, when we almost always get User identities in API calls

2021-03-18 15:47 UTC, kruai commented on tests/test_api_hosts_update.py
> +    created_host = db_create_host(USER_IDENTITY, host)
No, the Identity is optional - see my previous comments

2021-03-18 15:47 UTC, kruai commented on tests/test_api_hosts_update.py
> +    created_host = db_create_host(USER_IDENTITY, host)
No, the Identity is optional - see my previous comments

2021-03-18 15:47 UTC, kruai commented on tests/test_api_hosts_update.py
> +    created_host = db_create_host(USER_IDENTITY, host)
No, the Identity is optional - see my previous comments

2021-03-18 15:47 UTC, kruai commented on tests/test_culling.py
> +    response_status, response_data = api_get(HOST_URL, SYSTEM_IDENTITY)
The `SYSTEM_IDENTITY` requirement is an issue you created with this line: https://github.com/RedHatInsights/insights-host-inventory/blob/4d5e98f217381a3d728add3bd85bb08569d117f2/tests/fixtures/mq_fixtures.py#L31
API calls are almost always users, so it doesn't make sense to change all these tests to test system identities. IMO,  `mq_create_or_update_host` needs to be updated with another optional param (either Identity or account number).

2021-03-18 15:47 UTC, kruai commented on tests/test_culling.py
> +        created_host = db_create_host(USER_IDENTITY, host)
nope, optional (see previous)

2021-03-18 15:47 UTC, kruai commented on tests/test_deduplication.py
> +    created_host = db_create_host(USER_IDENTITY, host)
nope, optional (see previous)

2021-03-18 15:47 UTC, kruai commented on tests/test_deduplication.py
> +    created_host = db_create_host(USER_IDENTITY, host)
nope, optional (see previous)

2021-03-18 15:47 UTC, kruai commented on tests/test_deduplication.py
> +    created_host = db_create_host(USER_IDENTITY, host)
nope, optional (see previous)

2021-03-18 15:47 UTC, kruai commented on tests/test_deduplication.py
> +    created_host = db_create_host(USER_IDENTITY, host)
nope, optional (see previous)

2021-03-18 15:47 UTC, kruai commented on tests/test_deduplication.py
> +        created_host = db_create_host(USER_IDENTITY, host)
nope, optional (see previous)

2021-03-18 15:47 UTC, kruai commented on tests/test_models.py
> +    db_create_host(USER_IDENTITY, inserted_host)
nope, optional (see previous)

2021-03-18 15:47 UTC, kruai commented on tests/test_models.py
> +    db_create_host(USER_IDENTITY, host)
nope, optional (see previous)

2021-03-18 15:47 UTC, kruai commented on tests/test_models.py
> +    db_create_host(USER_IDENTITY, host)
nope, optional (see previous)

2021-03-18 15:47 UTC, kruai commented on tests/test_models.py
> +    db_create_host(USER_IDENTITY, host)
nope, optional (see previous)

2021-03-18 15:47 UTC, kruai commented on tests/test_models.py
> +    db_create_host(USER_IDENTITY, host)
nope, optional (see previous)

2021-03-18 15:47 UTC, kruai commented on tests/test_models.py
> +        db_create_host(USER_IDENTITY, host)
nope, optional (see previous)

2021-03-18 15:47 UTC, kruai commented on tests/test_models.py
> +    created_host = db_create_host(USER_IDENTITY, input_host)
nope, optional (see previous)

2021-03-18 15:47 UTC, kruai commented on tests/test_models.py
> +    existing_host = db_create_host(USER_IDENTITY, input_host)
nope, optional (see previous)

2021-03-18 15:47 UTC, kruai commented on tests/test_mq_service.py
> -
Whoa, this is confusing - did you edit my comment and replace its content with your response? :thinking: 
Regardless, a linting error in implementation does not constitute a test being invalid. If you're having trouble getting it to format correctly, please reach out to me (or your other teammates!) to get help

2021-03-18 15:47 UTC, kruai commented on tests/test_mq_service.py
> +        key, event, headers = mq_create_or_update_host(host, return_all_data=True)
perfect!

2021-03-18 15:47 UTC, kruai commented on tests/test_synchronizer.py
> +    created_host = db_create_host(USER_IDENTITY, host)
nope, it's optional (see previous)

2021-03-18 15:47 UTC, kruai commented on tests/test_synchronizer.py
> +    db_create_multiple_hosts(USER_IDENTITY, how_many=host_count)
nope, it's optional (see previous)

2021-03-18 15:47 UTC, kruai commented on tests/test_system_profile.py
> +    response_status, response_data = api_get(url, SYSTEM_IDENTITY)
If the fixture being modified requires a bunch of tests to be changed, then something is likely wrong with the change to the fixture. If every `api_get()` test is changed to use SYSTEM_IDENTITY, then we are only testing the scenarios where a system is making GET calls (I don't even think that happens).

2021-03-18 16:18 UTC, thearifismail commented on tests/helpers/api_utils.py
> +    dict_ = {"identity": Identity(identity)._asdict()}
I did but rebasing with the master must have put it back in.  This is what I had and pushing it again.
```
def build_account_auth_header(identity):
    dict_ = {"identity": identity}

    json_doc = json.dumps(dict_)
    auth_header = {"x-rh-identity": b64encode(json_doc.encode())}
    return auth_header
```

2021-03-18 16:19 UTC, thearifismail commented on tests/test_synchronizer.py
> +    created_host = db_create_host(USER_IDENTITY, host)
Gone!

2021-03-18 16:19 UTC, thearifismail commented on tests/test_synchronizer.py
> +    db_create_multiple_hosts(USER_IDENTITY, how_many=host_count)
Gone!

2021-03-18 16:35 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    db_create_host(USER_IDENTITY, host)
Gone!

2021-03-18 16:36 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    hosts = db_create_multiple_hosts(USER_IDENTITY, how_many=2)
Gone!

2021-03-18 16:36 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +    hosts = db_create_multiple_hosts(USER_IDENTITY, how_many=2)
Gone!

2021-03-18 17:01 UTC, thearifismail commented on tests/test_api_hosts_delete.py
> +            assert_response_status(response_status, 404)
Fixed.

2021-03-18 20:10 UTC, thearifismail commented on tests/test_tags.py
> +    response_status, response_data = api_get(url, SYSTEM_IDENTITY)
SYSTEM_IDENTITY gone from all `api_get() calls` except the test IS about using the SYSTEM_IDENTITY

2021-03-18 20:10 UTC, thearifismail commented on tests/test_system_profile.py
> +    response_status, response_data = api_get(url, SYSTEM_IDENTITY)
SYSTEM_IDENTITY gone from all `api_get() calls` except the test IS about using the SYSTEM_IDENTITY

2021-03-18 20:15 UTC, thearifismail commented on tests/helpers/api_utils.py
> +                url, SYSTEM_IDENTITY, query_parameters={"page": page, "per_page": per_page}
Gone!

2021-03-22 15:34 UTC, ryandillinfelton requested changes

2021-03-22 15:34 UTC, ryandillinfelton commented on tests/test_xjoin.py
> -    response_status, response_data = api_get(url, identity_type="Insights_Classic_System")
These test that use the insight_classic_system identity pass but no longer tests what they're supposed to. If we no longer need special handling for insights_classic_system identities we should just remove these tests, if we do still need special handling these tests need to be restored to using insights_classic_system identities.

2021-03-22 15:34 UTC, ryandillinfelton commented on tests/test_tags.py
> +    created_hosts = [db_create_host()]
Why change this from multiple hosts?

2021-03-22 15:34 UTC, ryandillinfelton commented on tests/test_api_auth.py
> -# TODO: Remove when workaround is no longer needed
If we expect a valid CN and the workaround is no longer needed then the test for the workaround should be removed.

2021-03-22 15:34 UTC, ryandillinfelton commented on tests/test_api_auth.py
> -# TODO: Remove when workaround is no longer needed
`test_insights_classic_workaround` and `test_validate_valid_user_identity_no_auth_type` should be deleted

2021-03-22 15:54 UTC, kruai requested changes
A whole lot of the API calls in the tests are still using `SYSTEM_IDENTITY`...

2021-03-22 15:54 UTC, kruai commented on tests/test_culling.py
> +    response_status, response_data = api_get(HOST_URL, SYSTEM_IDENTITY)
All the tests in this file are still using `SYSTEM_IDENTITY` for API request testing

2021-03-22 15:54 UTC, kruai commented on tests/test_system_profile.py
> +    response_status, response_data = api_get(f"{HOST_URL}/{host_id}/system_profile", SYSTEM_IDENTITY)
This one is still using `SYSTEM_IDENTITY`

2021-03-22 15:54 UTC, kruai commented on tests/test_system_profile.py
> +    response_status, response_data = api_get(f"{HOST_URL}/{invalid_host_id}/system_profile", SYSTEM_IDENTITY)
This one is still using `SYSTEM_IDENTITY`

2021-03-22 15:54 UTC, kruai commented on tests/test_xjoin.py
> +        HOST_URL, SYSTEM_IDENTITY, extra_headers={"x-rh-cloud-bulk-query-source": "db"}
This one is still using `SYSTEM_IDENTITY`

2021-03-22 15:54 UTC, kruai commented on tests/test_xjoin.py
> +        HOST_URL, SYSTEM_IDENTITY, extra_headers={"x-rh-cloud-bulk-query-source": "xjoin"}
It looks like a lot of the tests in this file are also still using `SYSTEM_IDENTITY` for API calls

2021-03-22 18:10 UTC, thearifismail commented on tests/test_tags.py
> +    created_hosts = [db_create_host()]
Back to using multiple hosts.

2021-03-22 18:10 UTC, thearifismail commented on tests/test_xjoin.py
> -    response_status, response_data = api_get(url, identity_type="Insights_Classic_System")
The `Insights_Classic_Identity` is being fix by https://issues.redhat.com/browse/RHCLOUD-12798.  For now leaving these test to not forget Insights-Classic until the fix is available.  Very likely will be removed by separate PR.

2021-03-22 18:10 UTC, thearifismail commented on tests/test_culling.py
> +    response_status, response_data = api_get(HOST_URL, SYSTEM_IDENTITY)
Fixed.

2021-03-22 18:10 UTC, thearifismail commented on tests/test_system_profile.py
> +    response_status, response_data = api_get(f"{HOST_URL}/{host_id}/system_profile", SYSTEM_IDENTITY)
Fixed.

2021-03-22 18:11 UTC, thearifismail commented on tests/test_system_profile.py
> +    response_status, response_data = api_get(f"{HOST_URL}/{invalid_host_id}/system_profile", SYSTEM_IDENTITY)
Fixed.

2021-03-22 18:13 UTC, thearifismail commented on tests/test_xjoin.py
> +        HOST_URL, SYSTEM_IDENTITY, extra_headers={"x-rh-cloud-bulk-query-source": "xjoin"}
Fixed.

2021-03-22 18:15 UTC, kruai reviewed
`_db_create_host()`'s identity param should probably default to the mock System Identity bc systems are the only ones creating hosts at this point, but you've got tests that use both identities, so it's not critical IMO. I second Ryan's requested changes, but I think we're almost there

2021-03-22 19:12 UTC, kruai commented on tests/test_xjoin.py
> -    response_status, response_data = api_get(url, identity_type="Insights_Classic_System")
@thearifismail Isn't that Jira unrelated to Ryan's comment? These "Insights_Classic_System" tests are no longer testing what they were created for

2021-03-22 19:37 UTC, ryandillinfelton approved these changes
LGTM :rocket:

2021-03-22 19:40 UTC, kruai approved these changes
:+1:

2021-03-22 19:55 UTC, tahmidefaz approved these changes
yolo!

2021-03-22 19:58 UTC, merged

2021-03-22 20:05 UTC, thearifismail commented
this PR better be YOLO