Fix bonfire breaking changes
RedHatInsights/insights-host-inventory pull request #816
Opened 2021-02-19 21:31 UTC by BlakeHolifield

## Overview

Bonfire has new features and improvments that break syntax. To solve this and add some quality of life fixes, I've updated the pr_check to do the following:

* Break out unit tests to a separate file
* Install bonfire via pip and pin to a known working version for the syntax we are using
* Update the command syntax to use bonfire
* Wait for all deployments to come up using bonfire -- this times out after 5 minutes and the PR check will exit after. No more running 700 tests that all fail :)

There are a few more improvements coming, like jobs and smoke testing. This should get your PRs in a better place for ephemeral envs and remain stable until we add more features later on.

2021-02-23 12:56 UTC, thearifismail approved these changes

2021-02-23 14:37 UTC, kruai requested changes
Had a few comments/questions

2021-02-23 14:37 UTC, kruai commented on unit_test.sh
> +pytest --cov=. --junitxml=junit.xml --cov-report html -sv
I realize this was originally in pr_check.sh, but is naming this after JUnit intentional? Seems weird since we're using pytest

2021-02-23 14:37 UTC, kruai commented on unit_test.sh
> +}
This function's unused. Is this being added for later use?

2021-02-23 14:37 UTC, kruai commented on unit_test.sh
> +RANDOM_PORT=62212
This variable is defined in both pr_check.sh and unit_test.sh. It doesn't appear to be used in pr_check.sh.

2021-02-23 14:37 UTC, kruai commented on pr_check.sh
> +export GIT_COMMIT=$(git rev-parse HEAD)
These variables are either used in unit_test.sh and not this one (`APP_ROOT`/`WORKSPACE`, `IMAGE_TAG`), or not used at all (`GIT_COMMIT`). Can `APP_ROOT`, `WORKSPACE` and `IMAGE_TAG` be defined in unit_test.sh instead, for the sake of readability? Or are they also used in deploy_ephemeral_env.sh?

2021-02-23 14:37 UTC, kruai commented on unit_test.sh
> +BG_PID=1010101
Since you're redefining this variable here, you'll want to delete the one in pr_check.sh

2021-02-23 21:52 UTC, BlakeHolifield commented on unit_test.sh
> +pytest --cov=. --junitxml=junit.xml --cov-report html -sv
I'm using what was in the Jenkinsfile in master: https://github.com/RedHatInsights/insights-host-inventory/blob/9d076a1f5a8194ffab956da55179cbb3bd765096/Jenkinsfile#L78

We can for sure change it if you'd like though!

2021-02-23 21:53 UTC, BlakeHolifield commented on unit_test.sh
> +}
Nope that needs to be deleted. Good catch

2021-02-23 21:53 UTC, BlakeHolifield commented on unit_test.sh
> +RANDOM_PORT=62212
Another good catch. Cleaning up.

2021-02-23 21:55 UTC, BlakeHolifield commented on pr_check.sh
> +export GIT_COMMIT=$(git rev-parse HEAD)
Yep! The `export` vars are being using inside `deploy_ephemeral_env.sh` and `unit_test.sh`

2021-02-23 21:55 UTC, BlakeHolifield commented on unit_test.sh
> +BG_PID=1010101
Deleting.

2021-02-24 16:05 UTC, kruai commented on unit_test.sh
> +pytest --cov=. --junitxml=junit.xml --cov-report html -sv
Oh... if we already had that, I guess it's fine. It feels wrong, but I really just wanted to make sure we weren't putting new incorrect naming into the script!

2021-02-24 16:26 UTC, kruai requested changes
I'd like one more change but then I think it's good to go :+1:

2021-02-24 16:26 UTC, kruai commented on unit_test.sh
> +# random_unused_port
This block should probably be deleted now

2021-02-24 16:46 UTC, BlakeHolifield commented on unit_test.sh
> +# random_unused_port
Doh! Fixed now.

2021-02-24 16:52 UTC, kruai approved these changes
Cool, looks good now :+1:

2021-03-31 15:33 UTC, thearifismail approved these changes

2021-03-31 15:39 UTC, merged