SP Validator: fixes, enhancements, performance improvements, tests
RedHatInsights/insights-host-inventory pull request #821
Opened 2021-02-25 19:04 UTC by kruai

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-12307) (again).
After discussing with Jozef and Chris Mitchell, I found out that the validator needs a slightly different approach. Here is a summary of changes I made in this PR:

- Changed the validator's consumer_group_id to be distinct from the standard inventory-mq one.
- Added the ability to limit the number of messages the validator processes (for performance reasons).
- Added support for 2 new env vars to make deployment configuration easier and faster.
- Made the validator subscribe to both the host-ingress and host-ingress-p1 topics, by default.
- Changed the validator's behavior to poll repeatedly until there are no new messages or the message limit is reached.
- Simplified and improved performance for get_hosts_from_kafka_messages().
- Improved coverage of the validator's testing, and combined 2 similar tests.

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [x] General Coding Practices

2021-03-01 13:59 UTC, kruai commented
Opened an e2e-deploy PR for the new env vars I added: https://github.com/RedHatInsights/e2e-deploy/pull/2813

2021-03-02 15:54 UTC, ryandillinfelton approved these changes
LGTM

2021-03-02 16:09 UTC, jharting commented on lib/system_profile_validate.py
> +    parsed_hosts = get_hosts_from_kafka_messages(consumer, topics, days, max_messages)
I am a bit worried that if you try to load 1 million hosts into memory and then do the validation the pod's memory will blow up. I think it would be better to iterate in smaller chunks and do the validations right away of the chunk before next iteration.

2021-03-02 18:07 UTC, kruai commented on api/system_profile.py
> +def validate_schema(repo_fork="RedHatInsights", repo_branch="master", days=1, max_messages=10000):
Are you specifically referring to the security of fetching the schema document from any of the repo's forks? I use yaml.safeLoad() to pull in the YAML file at the system profile spec's expected location, which is a safe way to parse YAML for untrusted input. That YAML file is then only used to attempt deserialization of hosts, and isn't stored on our end anywhere.

2021-03-02 18:26 UTC, kruai commented on lib/system_profile_validate.py
> +    parsed_hosts = get_hosts_from_kafka_messages(consumer, topics, days, max_messages)
Hmm, that's a fair point... I had built it this way to guarantee that the same list of hosts would be validated for each schema, but it should work that way too. I'll try to do a bit of redesigning this afternoon

2021-03-02 18:51 UTC, jharting commented on api/system_profile.py
> +def validate_schema(repo_fork="RedHatInsights", repo_branch="master", days=1, max_messages=10000):
@kruai no sorry. What I meant is that this operation is somewhat costly (puts load on kafka, blocks on inventory process/thread until finished, etc.) As such, it may be a good candidate for a user with bad intentions. I.e. if I, as a user, wanted to bring inventory down I would try calling `/system_profile/validate_schema` e.g. 100 times in quick succession. Is there something preventing users from doing so (that I missed)?

2021-03-03 19:10 UTC, kruai commented on api/system_profile.py
> +def validate_schema(repo_fork="RedHatInsights", repo_branch="master", days=1, max_messages=10000):
No, I haven't prevented anything like that. I'll look into ways to prevent multiple execution while I'm making the main restructuring change

2021-03-03 19:22 UTC, jharting commented on api/system_profile.py
> +def validate_schema(repo_fork="RedHatInsights", repo_branch="master", days=1, max_messages=10000):
Might be better to just restrict this operation so that ordinary users cannot trigger it.

2021-03-04 15:31 UTC, kruai commented on api/system_profile.py
> +def validate_schema(repo_fork="RedHatInsights", repo_branch="master", days=1, max_messages=10000):
Oh, ok. I'm changing the required permissions to `@rbac(Permission.ADMIN)`, which I'm assuming we all have. I don't know a lot about our RBAC permission setup; @tahmidefaz would you happen to know more?

2021-03-04 15:54 UTC, tahmidefaz commented on api/system_profile.py
> +def validate_schema(repo_fork="RedHatInsights", repo_branch="master", days=1, max_messages=10000):
`@rbac(Permission.ADMIN)` are all the account admins, you can check the RBAC permissions you have by going [here](https://cloud.redhat.com/api/rbac/v1/access/?application=inventory). `Permission.ADMIN` is also a platform-default role that gets added to all the users by default for orgs that do not enable RBAC. So, `Permission.ADMIN` is probably a decent role to use. Another way I can think of is using our org's account number to restrict access, but I am not sure how safe would it be to hardcode it somewhere.

2021-03-04 16:03 UTC, kruai commented on api/system_profile.py
> +def validate_schema(repo_fork="RedHatInsights", repo_branch="master", days=1, max_messages=10000):
OK. The user already has to be logged into c.rh.c and pass an acceptable auth header, so I'm hoping adding this will be enough. If using ADMIN will make it so that regular users with only READ or WRITE access can't use the endpoint, I think that's an improvement. I guess the only mystery I'd be nervous about here is... approximately how many people are in non-RBAC orgs and thus have ADMIN by default?

2021-03-08 09:05 UTC, jharting commented on api/system_profile.py
> +def validate_schema(repo_fork="RedHatInsights", repo_branch="master", days=1, max_messages=10000):
@kruai Inventory Admin is the default role i.e. all users are inventory admins by default https://github.com/RedHatInsights/rbac-config/blob/master/configs/roles/inventory.json#L7

2021-03-09 14:21 UTC, kruai commented on api/system_profile.py
> +def validate_schema(repo_fork="RedHatInsights", repo_branch="master", days=1, max_messages=10000):
Okay, then... is there a better role for this, or is there a way to check against specific user IDs?

2021-03-10 14:53 UTC, jharting commented on api/system_profile.py
> +def validate_schema(repo_fork="RedHatInsights", repo_branch="master", days=1, max_messages=10000):
@kruai there's only this single role https://github.com/RedHatInsights/rbac-config/blob/master/configs/roles/inventory.json#L2

You can see the user id in the identity header so restricting that in code may be a way to do it. Alternatively, you may restrict the access further by requiring a pre-shared key to be provided by the client. Or perhaps even defining the access policy in turnpike (instead of making this operation available via 3scale) may work.

2021-03-10 23:11 UTC, kruai commented on lib/system_profile_validate.py
> +    parsed_hosts = get_hosts_from_kafka_messages(consumer, topics, days, max_messages)
OK, I've restructured it so that it only loads one poll's worth of messages into memory at a time. Might be slower, but will mitigate potential memory issues

2021-03-11 14:24 UTC, kruai commented on api/system_profile.py
> +def validate_schema(repo_fork="RedHatInsights", repo_branch="master", days=1, max_messages=10000):
Gotcha. I've done the restructuring, and will focus on this particular issue today.

2021-03-11 17:41 UTC, kruai commented on api/system_profile.py
> +def validate_schema(repo_fork="RedHatInsights", repo_branch="master", days=1, max_messages=10000):
OK, I've restricted this endpoint to a set list of users. Not the most elegant, but I hope it'll do for now; getting things set up in Turnpike would be an entirely new can of worms that I'm not ready to open yet.

2021-03-11 19:03 UTC, tahmidefaz requested changes
I just shared a concern that I have atm, I will do an in-depth review later

2021-03-11 19:03 UTC, tahmidefaz commented on api/system_profile.py
> +    "tuser@redhat.com",
I don't think these are c.rh.c usernames. If we go down this route, might be better to have an env variable set to a list of usernames instead of hardcoding. Or, authorize access via a secret key of some sort instead of emails.

2021-03-11 19:36 UTC, kruai commented on api/system_profile.py
> +    "tuser@redhat.com",
Good call! I just changed this so it gets the list of users from a space-delimited config string. I was going to make it comma-delimited, but space-delimiting is the default pythonic way

2021-03-11 19:36 UTC, kruai commented on api/system_profile.py
> +def validate_schema(repo_fork="RedHatInsights", repo_branch="master", days=1, max_messages=10000):
Thanks to @tahmidefaz I've implemented a more elegant solution :)

2021-03-11 22:21 UTC, tahmidefaz commented on lib/system_profile_validate.py
> +    while total_message_count < max_messages:
Should this me `total_message_count <= max_messages`? Either way is fine with me. :+1:

2021-03-11 22:21 UTC, tahmidefaz approved these changes
Looks good to me :+1:

2021-03-12 14:52 UTC, kruai commented
Forgot to update my latest unit test with the change from HTTP 401 to HTTP 403, but that's in now!

2021-03-12 14:58 UTC, kruai commented on lib/system_profile_validate.py
> +    while total_message_count < max_messages:
Nope, it should be `<`. When `total_message_count == max_messages`, we don't want to poll any more messages.

2021-03-12 15:03 UTC, tahmidefaz approved these changes
Sneaky tests! Still looks good! :+1:

2021-03-12 15:23 UTC, jharting commented on api/system_profile.py
> +    if get_current_identity().user.get("username") not in config.sp_authorized_users:
Might be good to check the presence of `user` in the identity object. Otherwise, a request with cert-auth header will fail instead of returning 403.

2021-03-12 15:24 UTC, jharting submitted a review, later dismissed

2021-03-12 15:29 UTC, kruai commented on api/system_profile.py
> +    if get_current_identity().user.get("username") not in config.sp_authorized_users:
Good call. That's a quick fix

2021-03-12 16:02 UTC, tahmidefaz approved these changes
The new change/test looks good. Thanks!

2021-03-12 16:05 UTC, merged