IQE-12800: prepare a alternate normalized openapi spec
RedHatInsights/insights-host-inventory pull request #825
Opened 2021-03-08 14:32 UTC by RonnyPfannschmidt

this helps the codegen and api compat

in this pr we implement bundling of the api specs using a alternate bunlder to avoid the bugs in the native bundlers

related https://issues.redhat.com/browse/RHCLOUD-11860

also related 
* https://github.com/jfinkhaeuser/prance/pull/82
* https://github.com/jfinkhaeuser/prance/issues/76
* https://github.com/jfinkhaeuser/prance/issues/77

- [ ] verify generated code in the qe side on python
- [ ] integrate the new bundled spec in serving data
- [ ] feedback from @Glutexo

2021-03-11 11:02 UTC, Glutexo approved these changes
Wouldn’t it be possible to add the helper schema references using a Python code somewhere between loading the file and processing the schema, instead of adding them to the API file and then storing somehow compiled version?

2021-03-11 11:02 UTC, Glutexo commented on swagger/api.spec.yaml
> +      $ref: 'system_profile.spec.yaml#/$defs/NetworkInterface'
These objects are not referenced from anywhere in _api.spec.yaml_.

If you need them to nudge your code generator in the right direction, can’t you add them programmatically?

2021-03-11 11:02 UTC, Glutexo commented
Didn’t intend to approve. I wanted to just comment.

2021-03-11 15:18 UTC, RonnyPfannschmidt commented on swagger/openapi.json
> +{
the unbundling lib we currently use has bugs and jsut went unmaintained, we have to figure a solution

this is to manually manage unbundleing with correct references

2021-03-11 15:21 UTC, RonnyPfannschmidt commented on swagger/api.spec.yaml
> +      $ref: 'system_profile.spec.yaml#/$defs/NetworkInterface'
this pretty much nudges a standard compliant tool/verification tool-chain into the right direction,
as a intermediate solution i would consider that better than a custom python hack, i haven't figured yet how to do the de-ref correctly - when i made a script, the first iteration had some really dumb mistakes, so this helps to go to working

those names pretty much prevent in-lining of the sub-types used in the system profile spec

2021-03-11 15:22 UTC, RonnyPfannschmidt commented on swagger/api.spec.yaml
>        nullable: false
this was added by the verification tool i added to pre-commit, its perhaps due to the surrounding null-able
im crosschecking now

2021-03-11 15:46 UTC, kruai commented on swagger/api.spec.yaml
> +        fqdn:
FYI, this was fixed by #826. You probably need to update this branch with master

2021-03-15 10:09 UTC, RonnyPfannschmidt commented on swagger/api.spec.yaml
> +        fqdn:
@kruai fixed, we should have a little discuss on the implication of the nested validation removal, but it practically was never implemented as far as i understood

2021-03-15 14:26 UTC, kruai reviewed
I'm still a bit unclear on the direction this will take us in. My main concern is regarding `swagger/openapi.json`: is it a requirement for us to switch our API spec from yaml to json?

2021-03-15 16:48 UTC, RonnyPfannschmidt commented
@kruai no, the json is a autogenerated and pre-commit enforced de-bundle while we resolve the issue with broken and unmaintained prasec

We will work with the yaml

2021-03-15 17:13 UTC, tahmidefaz commented on swagger/system_profile.spec.yaml
> +
Question: How are we handling this `NestedObject`? By the current schema definition, `NestedObject` can have an unspecified number of keys and each key definition must have a length of at least 1. A key can also be other `NestedObjects`, and so on.

2021-03-15 17:41 UTC, RonnyPfannschmidt commented on swagger/system_profile.spec.yaml
> +
As far as I understood, the incorrect unbundleing broke this , I'll add a unittest that demonstrate the behaviour later

2021-03-16 20:45 UTC, kruai submitted a review, later dismissed
Based on our discussion... this makes sense for the interim until the Prance issue is resolved, even though I don't like the duplication. Do you have a Jira card to track the follow-up work to remove the JSON, etc.?

2021-03-16 21:12 UTC, tahmidefaz requested changes

2021-03-16 21:12 UTC, tahmidefaz commented on swagger/openapi.json
> +      },
Correct me if I am wrong but I think this means that it will fail on something like:
`{"disk_device":{"options": {"": "something"}}}`

But, it will pass on something like:
`{"disk_device": {"options": {"key": {"": "empty_key"}}}}`

I think that diverges from our current behavior e.g. all keys in `disk_device.options` and in its nested objects should have a length of at least 1.

2021-03-16 21:12 UTC, tahmidefaz commented on swagger/openapi.json
> +      },
For adding host via MQ, this won't matter as this gets re-verified with another function, but trying to fetch a host that has
`{"disk_device": {"options": {"key": {"": "empty_key"}}}}` will not throw a `5xx` anymore as this is not invalid anymore per this new definition, whereas it should throw a `5xx` in this situation

2021-03-16 21:16 UTC, tahmidefaz commented
Note to self: we need to update our HBI unit tests to catch the aforementioned failure :memo:

2021-05-19 15:52 UTC, Glutexo commented on swagger/openapi.json
> +      },
`{"disk_device": {"options": {"key": {"": "empty_key"}}}}` should not pass!

2021-05-19 15:52 UTC, Glutexo commented on swagger/openapi.json
> +      },
I’ll double check.

2021-05-19 17:08 UTC, Glutexo commented on swagger/openapi.json
> +      },
I tested with a host entry like this 

```sql
INSERT INTO public.hosts (id, account, display_name, created_on, modified_on, facts, tags, canonical_facts, system_profile_facts, ansible_host, stale_timestamp, reporter, per_reporter_staleness) VALUES ('e0a2bcc2-3c68-4a7e-adf9-9af38e343f3e', 'test', 'test', '2021-05-07 17:35:39.397000', '2021-05-07 17:35:43.006000', '{}', '{}', '{"insights_id": "8b75c23f-8149-499e-848a-1638295ccb1a"}', '{"arch": "x86-64", "owner_id": "1b36b20f-7fa0-4454-a6d2-008294e06378", "cpu_flags": ["flag1", "flag2"], "cpu_model": "Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz", "yum_repos": [{"name": "repo1", "enabled": true, "base_url": "http://rpms.redhat.com", "gpgcheck": true}], "os_release": "Red Hat EL 7.0.1", "bios_vendor": "Turd Ferguson", "bios_version": "1.0.0uhoh", "disk_devices": [{"type": "ext3", "label": "home drive", "device": "/dev/sdb1", "options": {"ro": true, "key": {"": "empty_key", "C": "D"}, "uid": "0"}, "mount_point": "/home"}], "captured_date": "2020-02-13T12:16:00Z", "rhc_client_id": "044e36dc-4e2b-4e69-8948-9c65a7bf4976", "is_marketplace": false, "kernel_modules": ["i915", "e1000e"], "last_boot_time": "12:25 Mar 19, 2019", "number_of_cpus": 1, "cores_per_socket": 4, "enabled_services": ["ndb", "krb5"], "rhc_config_state": "044e36dc-4e2b-4e69-8948-9c65a7bf4976", "bios_release_date": "10/31/2013", "number_of_sockets": 2, "os_kernel_version": "3.10.0", "running_processes": ["vim", "gcc", "python"], "satellite_managed": false, "installed_products": [{"id": "123", "name": "eap", "status": "UP"}, {"id": "321", "name": "jbws", "status": "DOWN"}], "installed_services": ["ndb", "krb5"], "network_interfaces": [{"mtu": 1500, "name": "eth0", "type": "loopback", "state": "UP", "mac_address": "aa:bb:cc:dd:ee:ff", "ipv4_addresses": ["10.10.10.1"], "ipv6_addresses": ["2001:0db8:85a3:0000:0000:8a2e:0370:7334"]}], "infrastructure_type": "jingleheimer junction cpu", "selinux_config_file": "enforcing", "subscription_status": "valid", "system_memory_bytes": 1024, "insights_egg_version": "120.0.1", "selinux_current_mode": "enforcing", "infrastructure_vendor": "dell", "katello_agent_running": false, "insights_client_version": "12.0.12", "subscription_auto_attach": "yes"}', null, '2021-06-07 17:36:07.934000', 'reporter', '{}');
```

containing `"options": {"ro": true, "key": {"": "empty_key", "C": "D"}`.

`GET http://localhost:8081/api/inventory/v1/hosts/e0a2bcc2-3c68-4a7e-adf9-9af38e343f3e/system_profile` results in  an _500 Internal Server Error_ just as expected.

```json
{
  "detail": "{'': 'empty_key', 'C': 'D'} is not valid under any of the given schemas\n\nFailed validating 'oneOf' in schema['properties']['results']['items']['properties']['system_profile']['properties']['disk_devices']['items']['properties']['options']['additionalProperties']:\n    {'oneOf': [{'additionalProperties': <Recursion on dict with id=4436957248>,\n                'description': 'An arbitrary object that does not allow '\n                               'empty string keys.',\n                'type': 'object',\n                'x-propertyNames': {'minLength': 1},\n                'x-scope': ['']},\n               {'not': {'type': 'object'}}]}\n\nOn instance['results'][0]['system_profile']['disk_devices'][0]['options']['key']:\n    {'': 'empty_key', 'C': 'D'}",
  "status": 500,
  "title": "Response body does not conform to specification",
  "type": "about:blank"
}
```

Can you please verify? @tahmidefaz If you can’t reproduce, let’s hop on a call to find the cause.

2021-08-24 18:25 UTC, kruai commented on swagger/system_profile_commit_id
> +dd15575876c2869e1318919a71e5551fc3cd5374
Adding this file is a good call :+1:

2021-08-24 18:25 UTC, kruai commented on swagger/api.spec.yaml
> +       # description: System profile field values to filter with
Why comment instead of remove?

2021-08-24 18:25 UTC, kruai commented on swagger/api.spec.yaml
> +        # description: System profile field values to fetch
Same Q here

2021-08-24 18:25 UTC, kruai commented on swagger/openapi.json
> +{
This file raises a few Qs. Does adding this mean we have to maintain 2 files now? Are we moving from YAML to JSON?

2021-09-07 14:30 UTC, RonnyPfannschmidt commented on swagger/api.spec.yaml
>        nullable: false
removed

2021-09-07 14:31 UTC, RonnyPfannschmidt commented on swagger/api.spec.yaml
> +        nullable: False
removed

2021-09-07 14:32 UTC, RonnyPfannschmidt commented on swagger/system_profile.spec.yaml
> +
undone

2021-09-07 14:32 UTC, RonnyPfannschmidt commented on swagger/openapi.json
> +      },
i beleive we don't follow up on this detail we included the details again

2021-09-07 14:33 UTC, RonnyPfannschmidt commented on swagger/api.spec.yaml
> +        # description: System profile field values to fetch
also upstream issue

2021-09-14 14:42 UTC, kruai requested changes
Only had one minor request in the comments. My main concern is that the build is failing every time. The most recent error appears to be caused by the setuptools pinning:
`ERROR: Invalid requirement: 'pip setuptools<58'`

Once you get the builds passing, I'll approve this.

2021-09-14 14:42 UTC, kruai commented on check_schemas.py
> +# spec.parse()
Should be removed instead of commented

2021-09-14 16:01 UTC, RonnyPfannschmidt commented
moved to draft, need to run another api spec update

2021-09-14 16:17 UTC, kruai approved these changes
I think this is good now!

2021-10-01 14:34 UTC, kruai submitted a review, later dismissed

2021-10-01 15:01 UTC, ryandillinfelton commented on app/__init__.py
> +# temporary replaced for RHCLOUD-12800 - correct normalization of the bundled spec
Might want to switch this to the ESSNTL card number if there is one

2021-10-01 16:04 UTC, ryandillinfelton commented on check_schemas.py
> +    # make_diff("api.spec.yaml", "prace_reads_spec")
I think it'd be cool to add a script to `package.json` that runs this, but I won't block on it.

2021-10-01 16:08 UTC, ryandillinfelton commented
@RonnyPfannschmidt could you open a PR on `[inventory-schemas](https://github.com/RedHatInsights/inventory-schemas)` with the same changes you made to the base schema. We should merge it there first to make sure they stay in sync.

2021-10-04 11:21 UTC, RonnyPfannschmidt commented on app/__init__.py
> +# temporary replaced for RHCLOUD-12800 - correct normalization of the bundled spec
```suggestion
# temporary replaced for ESSNTL-746 - correct normalization of the bundled spec
```

2021-10-04 11:22 UTC, RonnyPfannschmidt commented on check_schemas.py
> +    # make_diff("api.spec.yaml", "prace_reads_spec")
before prance is fixed, this may not be as interesting as we'd like it

2021-10-04 13:18 UTC, RonnyPfannschmidt commented
@ryandillinfelton the pagination changes only belong to our own api, no upstreaming needed

2021-10-04 14:31 UTC, kruai approved these changes

2021-10-04 19:18 UTC, ryandillinfelton approved these changes

2021-10-04 19:22 UTC, merged