[WIP] Add per reporter staleness filter
RedHatInsights/insights-host-inventory pull request #838
Opened 2021-03-19 19:12 UTC by ryandillinfelton

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-xxxxx).
(A description of your PR's changes goes here.)

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-03-23 09:09 UTC, RonnyPfannschmidt reviewed
i'm getting the impression that the filter building is/qA very repetitive and handles None/nulls/missing all over the place

as a followup/side project i would like us to investigate expressing this in a more general compact way in order to remove those null/none/missing checks

cc @gmcculloug @kruai 

as we use tuples often and do check for empty/`()` often, and given that
```pycon
>>> () + (1,) + ()
(1,)
```

i believe changing the filters creation to something we could just add up without sprinkling conditionals all over the place  wil lhelp to make for compact more readable code

2021-03-23 19:22 UTC, ryandillinfelton commented
This is ready for review. I don't believe there is anything stopping us from merging it in, but there is still some work to be done on the xjoin side to transform the data as it goes into elasticsearch. All that to say, I think we can merge it in and just not tell anyone about the filters until they actually work.

2021-03-23 20:19 UTC, RonnyPfannschmidt commented on api/host_query_xjoin.py
> +    for reporter in per_reporter_staleness:
```suggestion
    for reporter, props in per_reporter_staleness.items():
```
should drop duplicate sub-expressions nicely

2021-03-24 18:31 UTC, kruai requested changes
Had a few notes/questions

2021-03-24 18:31 UTC, kruai commented on api/host_query_xjoin.py
> +    for reporter in per_reporter_staleness:
I agree... then you can just use `props["stale_timestamp"]` instead of `per_reporter_staleness[reporter]["stale_timestamp"]`, etc etc

2021-03-24 18:31 UTC, kruai commented on api/host_query_xjoin.py
> +def build_prs_reporter_filter(sap_sids):
This function looks like it's specifically for `sap_sids`. Can you explain why the function is called `build_prs_reporter_filter`? I'm a little confused

2021-03-24 18:31 UTC, kruai commented on tests/test_xjoin.py
> +        "filter[per_reporter_staleness][yupana][exists]",
This will need to be updated if we're going with the `[exists]=true` syntax (along with the other instances in this file)

2021-03-24 18:31 UTC, kruai commented on api/host_query_xjoin.py
> +def build_prs_reporter_filter(sap_sids):
Actually, is this used anywhere? If not, it should be removed

2021-03-24 19:25 UTC, thearifismail commented on tests/test_xjoin.py
> +        "filter[per_reporter_staleness][yupana][exists]",
> This will need to be updated if we're going with the `[exists]=true` syntax (along with the other instances in this file)

or `nil`

2021-03-24 19:26 UTC, kruai commented on api/host_query_xjoin.py
> +    if system_profile.get("sap_system"):
This PR is only for per-reporter staleness filters, not system_profile fields. I'm on board with this new `_build_system_profile_filter` function to better separate the new filters that will be added soon

2021-03-24 19:30 UTC, thearifismail commented on tests/test_xjoin.py
> +        "filter[per_reporter_staleness][yupana][stale_timestamp][gte]=2021-03-18T21%3A21%3A00.935093%2B00%3A00",
How about replacing hard-coded timestamps with dynamically generated ones using something `Time.now()`

2021-03-25 09:28 UTC, RonnyPfannschmidt commented on tests/test_xjoin.py
> +        "filter[per_reporter_staleness][yupana][stale_timestamp][gte]=2021-03-18T21%3A21%3A00.935093%2B00%3A00",
i'm seeing that we use this timestamp in a lot of places both urlencoded and plain
i'd recommend to at least put it in a constant as currently it constitutes a magic number

2021-03-25 13:56 UTC, ryandillinfelton commented on api/host_query_xjoin.py
> +def build_prs_reporter_filter(sap_sids):
removed it

2021-03-25 14:19 UTC, ryandillinfelton commented on api/host_query_xjoin.py
> +    for reporter in per_reporter_staleness:
Done :+1:

2021-03-25 14:20 UTC, ryandillinfelton commented on tests/test_xjoin.py
> +        "filter[per_reporter_staleness][yupana][exists]",
I'm going with the existing way to query nil/not_nil and expanding it to work with strings aswell

2021-03-25 14:49 UTC, ryandillinfelton commented on tests/test_xjoin.py
> +        "filter[per_reporter_staleness][yupana][stale_timestamp][gte]=2021-03-18T21%3A21%3A00.935093%2B00%3A00",
I think using time.now would be more hassle than it's worth. It could be wise to extract some timestamps into constants, but since we often need a mix of timestamp values I think an effort to do so should be it's own PR and not rolled into this one. This test is the only spot where this specific timestamp shows up at all, and I'd rather not open up the bag of worms of unifying it and other tests to a set of timestamps now.

2021-03-25 15:07 UTC, RonnyPfannschmidt commented on api/host_query_xjoin.py
> +    if isinstance(field_value, field_type):
if we return a empty tuple when `field_value is None` i believe we can replace the conditionals for get with 
streamlined calls

2021-03-25 15:13 UTC, RonnyPfannschmidt commented on api/host_query_xjoin.py
> +            prs_dict["check_in_succeeded"] = {"is": props["check_in_succeeded"].lower() == "true"}
it does seem to me, that this one looks like a boolean filter as well, would it make sense, or should this one stay specific

2021-03-25 15:14 UTC, RonnyPfannschmidt commented on tests/test_xjoin.py
> +        "filter[per_reporter_staleness][yupana][stale_timestamp][gte]=2021-03-18T21%3A21%3A00.935093%2B00%3A00",
lets have a low prio  followup card then

2021-03-25 15:49 UTC, ryandillinfelton commented on tests/test_xjoin.py
> +        "filter[per_reporter_staleness][yupana][exists]",
Actually, I think we need exists for this. Specifically because we can't send
`filter[per_reporter_staleness][yupana]=not_nil,filter[per_reporter_staleness][yupana][check_in_succeeded]=true`
without one overwritting the other in the resulting object. It would be possible to do some parsing trickery but I don't think it'd be wise. So I think just adding [exists] as on operation for checking if objects exists makes sense and doesn't clash with existing operations for other types.

2021-03-25 15:50 UTC, ryandillinfelton commented
Fiddling with existence queries. Hold off on reviewing until I say otherwise in another comment. I got ahead of myself.

2021-03-25 16:15 UTC, ryandillinfelton commented on api/host_query_xjoin.py
> +            prs_dict["check_in_succeeded"] = {"is": props["check_in_succeeded"].lower() == "true"}
I think I'll make it a boolean filter as well. My only hesitation is that the field is never really going to be nil, but I don't suppose that is really a problem

2021-03-25 17:21 UTC, ryandillinfelton commented on api/host_query_xjoin.py
> +            prs_dict["check_in_succeeded"] = {"is": props["check_in_succeeded"].lower() == "true"}
Okay so it's actually bad to let it be nullable so I made a non_nullable boolean filter function.

2021-03-25 17:25 UTC, ryandillinfelton commented
Okay I believe this is ready for re-review.
Also, short comment. You may notice that the test is only for happy path and there is nothing enforcing the inputs. There is a similar issue to the system_profile filters where we cannot validate the parameters using jsonschema. I'll be doing a follow up PR to this and the incoming extra system profile filters that adds manual checking in.

2021-03-26 12:44 UTC, thearifismail commented on tests/test_xjoin.py
> +        "filter[per_reporter_staleness][yupana][stale_timestamp][gte]=2021-03-18T21%3A21%3A00.935093%2B00%3A00",
Yes in the spirit of keep PR short.  here is [RHCLOUD-13225](https://issues.redhat.com/browse/RHCLOUD-13225) for followup.

2021-03-26 12:50 UTC, thearifismail commented on tests/test_xjoin.py
> +        "filter[per_reporter_staleness][yupana][exists]",
Agree.  Let's get it working now.  Elegance can be added later.

2021-03-26 13:24 UTC, kruai commented on tests/test_xjoin.py
> +        "filter[per_reporter_staleness][yupana][exists]",
> Agree. Let's get it working now. Elegance can be added later.

That feels like a dangerous mindset that can lead to lots of technical debt... but I agree that the `[exists]` operation is fine. I really just want to make sure we agree on one and keep it consistent throughout or app!

2021-03-26 14:28 UTC, RonnyPfannschmidt commented on api/host_query_xjoin.py
> +        return ({"NOT": {field_name: {"eq": None}}},)
compared to bools, why do the nils not use is

2021-03-26 14:39 UTC, ryandillinfelton commented on api/host_query_xjoin.py
> +        return ({"NOT": {field_name: {"eq": None}}},)
`Is` isn't supported on string fields in xjoin. This is the equivalent expression for strings and wildcard strings.

2021-03-26 14:49 UTC, thearifismail commented
> Agree. Let's get it working now. Elegance can be added later.

Oops, should have said, "Agree. Let's get it working now. Elegance can be added later `after the Summit`

2021-04-05 14:29 UTC, kruai approved these changes
LGTM!

2021-04-05 15:54 UTC, thearifismail commented on api/host_query_xjoin.py
> +def build_check_in_succeeded_filter(check_in_succeeded):
Is `def build_check_in_succeeded_filter()` is still needed because it is not referenced anywhere?

2021-04-05 15:55 UTC, thearifismail commented on api/host_query_xjoin.py
> +def build_filter(field_name, field_value, field_type, operation, filter_building_function):
This function should be private because it is not used outside of this module.

2021-04-05 15:57 UTC, thearifismail reviewed
Any plan replacing CONSTANTS NIL and NOT_NIL.  Theoretical correct but making the code more congested.

2021-04-05 17:07 UTC, ryandillinfelton commented
> Any plan replacing CONSTANTS NIL and NOT_NIL. Theoretical correct but making the code more congested.

What would you suggest I replace them with?

2021-04-05 17:11 UTC, thearifismail commented
> > Any plan replacing CONSTANTS NIL and NOT_NIL. Theoretical correct but making the code more congested.
> 
> What would you suggest I replace them with?

nothing; just remove `NIL` and `NOT_NIL` constants and use `nil` and `not_nil` directly.

2021-04-05 17:28 UTC, kruai commented
> > > Any plan replacing CONSTANTS NIL and NOT_NIL. Theoretical correct but making the code more congested.
> > 
> > 
> > What would you suggest I replace them with?
> 
> nothing; just remove `NIL` and `NOT_NIL` constants and use `nil` and `not_nil` directly.

That definitely feels like a step backward to me. What would we gain by doing this?

2021-04-05 17:31 UTC, ryandillinfelton commented
> > > > Any plan replacing CONSTANTS NIL and NOT_NIL. Theoretical correct but making the code more congested.
> > > 
> > > 
> > > What would you suggest I replace them with?
> > 
> > 
> > nothing; just remove `NIL` and `NOT_NIL` constants and use `nil` and `not_nil` directly.
> 
> That definitely feels like a step backward to me. What would we gain by doing this?

2021-04-05 17:31 UTC, ryandillinfelton commented
I always think that's the cancel comment button :facepalm:

2021-04-05 17:35 UTC, ryandillinfelton commented
> > > Any plan replacing CONSTANTS NIL and NOT_NIL. Theoretical correct but making the code more congested.
> > 
> > 
> > What would you suggest I replace them with?
> 
> nothing; just remove `NIL` and `NOT_NIL` constants and use `nil` and `not_nil` directly.

I felt like just using the raw string was bad practice since bugs could arise from a simple typo.

2021-04-05 18:02 UTC, thearifismail commented
> > > > Any plan replacing CONSTANTS NIL and NOT_NIL. Theoretical correct but making the code more congested.
> > > 
> > > 
> > > What would you suggest I replace them with?
> > 
> > 
> > nothing; just remove `NIL` and `NOT_NIL` constants and use `nil` and `not_nil` directly.
> 
> That definitely feels like a step backward to me. What would we gain by doing this?

IMO, the code should look cleaner with `nil` `not_nil` than`NIL` and `NOT_NIL`.  Constants are good when their values are subject to change, which is not the case here.  It is just a suggestion.

2021-04-05 22:58 UTC, ryandillinfelton commented
Conflicts fixed

2021-04-06 08:19 UTC, RonnyPfannschmidt commented on api/host_query_xjoin.py
> +    prs_dict_array = []
lets just return `()` here if `per_reporter_staleness` is falsey

2021-04-06 08:22 UTC, RonnyPfannschmidt commented on api/host_query_xjoin.py
> +        if filter.get("per_reporter_staleness"):
if we let the `_build_per_reporter_staleness_filter` function return `()` on falsey values, we can start to take the ifs out of the equation
ideal case is that eventually the composition of the filter is free of most conditions at this level

2021-11-18 15:29 UTC, kruai commented
@ryandillinfelton This is a feature we still want to implement, but this PR is pretty old. If this PR is still the way to go, what do we need in order for it to not be on hold? 
(Also if we still want to use this PR, please update the Jira link in the description because it's still using the placeholder :slightly_smiling_face:)

2022-05-17 11:55 UTC, kruai commented
Out of date. Replaced by #1115.

2022-05-17 11:55 UTC, closed without merging