Topic logic refactoring
RedHatInsights/insights-host-inventory pull request #840
Opened 2021-03-22 13:39 UTC by tahmidefaz

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-xxxxx).
(A description of your PR's changes goes here.)

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [x] General Coding Practices

2021-03-22 13:43 UTC, tahmidefaz commented on tests/test_mq_service.py
> +# def test_events_sent_to_correct_topic(mocker, flask_app):
I remember adding this test when introducing multiple topic functionality. Do we still need to keep it? It's not easy to test this functionality based on the way I am refactoring here. Also, I am thinking, since we only have one egress topic, what purpose does this test serve?

2021-03-22 13:49 UTC, tahmidefaz commented on tests/test_unit.py
> -    def test_invalid_topic_causes_failure(self):
Same thing as above

2021-03-22 13:50 UTC, kruai commented on tests/test_mq_service.py
> +# def test_events_sent_to_correct_topic(mocker, flask_app):
I think this test still makes sense; it's validating that the correct event type is created, and that the event is sent to the topic... so it's making sure that the logic doesn't change and it starts sending messages to the Ingress queue or something like that

2021-03-22 13:54 UTC, kruai commented on tests/test_unit.py
> -    def test_invalid_topic_causes_failure(self):
Considering the changes made in your implementation, _this_ test can definitely be removed :laughing:

2021-03-22 14:03 UTC, tahmidefaz commented on tests/test_mq_service.py
> +# def test_events_sent_to_correct_topic(mocker, flask_app):
Ooo, I need to think of how to modify this test! It's quite difficult to test this functionality, unless I change the way things are laid out here :thinking:

2021-03-22 14:30 UTC, tahmidefaz commented on tests/test_mq_service.py
> +# def test_events_sent_to_correct_topic(mocker, flask_app):
@kruai Actually, after the refactoring, [this test](https://github.com/RedHatInsights/insights-host-inventory/blob/master/tests/test_unit.py#L1700) is testing the exact same thing. What do you think? :thinking:

2021-03-22 19:33 UTC, kruai commented on tests/test_mq_service.py
> +# def test_events_sent_to_correct_topic(mocker, flask_app):
Yeah, I think you're right... due to the naming, I think I'd prefer this test to get destroyed? But idc either way tbh

2021-03-22 19:35 UTC, kruai requested changes
I think this is almost ready to merge. If you remove one of the redundant tests (as per my comment response), I'll LGTM it

2021-03-22 19:54 UTC, tahmidefaz commented on tests/test_mq_service.py
> +# def test_events_sent_to_correct_topic(mocker, flask_app):
Just removed it :slightly_smiling_face:

2021-03-22 20:09 UTC, kruai approved these changes
LGTM, once you deal with that new merge conflict!

2021-03-22 20:44 UTC, kruai approved these changes
LGTM!

2021-03-22 21:26 UTC, ryandillinfelton approved these changes

2021-03-22 22:46 UTC, thearifismail approved these changes
LGTM.

2021-03-22 22:48 UTC, thearifismail commented
Yes I approved based the expectation that the environment variables in inventory-mq deployment templates will be updated soon.

2021-03-23 08:49 UTC, RonnyPfannschmidt approved these changes

2021-03-23 12:32 UTC, merged