[WIP] enable satellite identity handling by host-inventory
RedHatInsights/insights-host-inventory pull request #842
Opened 2021-03-23 17:02 UTC by thearifismail

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-11752).  To enable the use of `satellite` IDs, needed to remove the check of `cert_type == "system"`; rest is very similar to the [PR #814](https://github.com/RedHatInsights/insights-host-inventory/pull/814).

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-03-23 17:04 UTC, thearifismail commented
@lphiri can we release this satellite related code change?   Do I need to do anything to communicate with the satellite team?

2021-03-23 21:23 UTC, lphiri commented
@thearifismail  - this looks good to me.  Once classic identity header is fixed, we should come back and remove the "classic_proxy" check.  https://issues.redhat.com/browse/RHCLOUD-12798
I assume that we already have solid tests for filtering - otherwise i would recommend adding tests that show that the filter returns a list for Satellite system, if all of them match a given owner.

2021-03-23 21:33 UTC, thearifismail commented
No, we don't have filtering in yet. When it is I will add tests to it.

2021-03-24 18:51 UTC, kruai requested changes
Mostly looks good, though I had a few notes

2021-03-24 18:51 UTC, kruai commented on tests/helpers/test_utils.py
> +SATELLITE_IDENTITY["system"]["cert_type"] = "satellite"
Because Python passes objects by reference, doing this will also set `SYSTEM_IDENTITY["system"]["cert_type"]` to satellite. Either create the dict in the same way as the others, or use a deep clone

2021-03-24 18:51 UTC, kruai commented on tests/test_mq_service.py
> +    message = wrap_message(host.data(), "add_host", get_platform_metadata(SYSTEM_IDENTITY))
`SYSTEM_IDENTITY` is the default, so you don't need to pass it as an arg

2021-03-24 18:51 UTC, kruai commented on tests/test_mq_service.py
> +        "platform_metadata": get_platform_metadata(SYSTEM_IDENTITY),
`SYSTEM_IDENTITY` is the default, so you don't need to pass it as an arg

2021-03-24 18:51 UTC, kruai commented on tests/test_mq_service.py
> +        "metadata": {"request_id": get_platform_metadata(SYSTEM_IDENTITY).get("request_id")},
`SYSTEM_IDENTITY` is the default, so you don't need to pass it as an arg

2021-03-24 18:51 UTC, kruai commented on tests/test_mq_service.py
> +        msg = json.dumps(wrap_message(host.data(), "", get_platform_metadata(SYSTEM_IDENTITY)))
`SYSTEM_IDENTITY` is the default, so you don't need to pass it as an arg

2021-03-24 18:51 UTC, kruai commented on tests/test_mq_service.py
> +    message = json.dumps(wrap_message(host.data(), "add_host", get_platform_metadata(SYSTEM_IDENTITY)))
`SYSTEM_IDENTITY` is the default, so you don't need to pass it as an arg

2021-03-24 18:51 UTC, kruai commented on tests/test_mq_service.py
> +    message = wrap_message(host.data(), "add_host", get_platform_metadata(SYSTEM_IDENTITY))
`SYSTEM_IDENTITY` is the default, so you don't need to pass it as an arg

2021-03-24 18:51 UTC, kruai commented on tests/test_mq_service.py
> +        "metadata": {"request_id": get_platform_metadata(SYSTEM_IDENTITY).get("request_id")},
Why are you asserting that they'll have the `SYSTEM_IDENTITY` metadata if this is a `SATELLITE_IDENTITY` test?

2021-03-24 20:25 UTC, thearifismail commented on tests/helpers/test_utils.py
> +SATELLITE_IDENTITY["system"]["cert_type"] = "satellite"
Done!

2021-03-24 20:31 UTC, thearifismail commented on tests/test_mq_service.py
> +    message = wrap_message(host.data(), "add_host", get_platform_metadata(SYSTEM_IDENTITY))
done!

2021-03-24 20:31 UTC, thearifismail commented on tests/test_mq_service.py
> +        "platform_metadata": get_platform_metadata(SYSTEM_IDENTITY),
Done!

2021-03-24 20:31 UTC, thearifismail commented on tests/test_mq_service.py
> +        "metadata": {"request_id": get_platform_metadata(SYSTEM_IDENTITY).get("request_id")},
Done!

2021-03-24 20:31 UTC, thearifismail commented on tests/test_mq_service.py
> +        msg = json.dumps(wrap_message(host.data(), "", get_platform_metadata(SYSTEM_IDENTITY)))
Done!

2021-03-24 20:31 UTC, thearifismail commented on tests/test_mq_service.py
> +    message = json.dumps(wrap_message(host.data(), "add_host", get_platform_metadata(SYSTEM_IDENTITY)))
Done!

2021-03-24 20:32 UTC, thearifismail commented on tests/test_mq_service.py
> +    message = wrap_message(host.data(), "add_host", get_platform_metadata(SYSTEM_IDENTITY))
Done!

2021-03-24 20:33 UTC, thearifismail commented on tests/test_mq_service.py
> +        "metadata": {"request_id": get_platform_metadata(SYSTEM_IDENTITY).get("request_id")},
Fixed.  This and all of the above produced by a sleeping brain

2021-03-24 20:51 UTC, kruai requested changes
One more thing I missed!

2021-03-24 20:51 UTC, kruai commented on tests/test_mq_service.py
> +def test_handle_message_happy_satellite(mocker, event_datetime_mock, flask_app):
This test case looks exactly like `test_handle_message_happy_path`, but using `SATELLITE_IDENTITY` instead of `SYSTEM_IDENTITY`. Instead of making a new test, can you just parameterize the identity?

2021-03-24 21:29 UTC, thearifismail commented on tests/test_mq_service.py
> +def test_handle_message_happy_satellite(mocker, event_datetime_mock, flask_app):
Done!

2021-03-24 21:39 UTC, kruai submitted a review, later dismissed
LGTM! Do you think we need another test @ryandillinfelton @tahmidefaz ?

2021-03-24 21:47 UTC, thearifismail commented
@kruai here is a reminder for creating tests to filter satellite systems https://issues.redhat.com/browse/RHCLOUD-13151

2021-03-24 21:49 UTC, kruai commented
> @kruai here is a reminder for creating tests to filter satellite systems https://issues.redhat.com/browse/RHCLOUD-13151

If it needs another test, shouldn't that be included in this PR?

2021-03-25 12:42 UTC, thearifismail commented
> If it needs another test, shouldn't that be included in this PR?

Yes, new tests will be created in a separate PR. The Jira card was created as a reminder to not forget creating tests to filter out satellite systems when filtration PR is merged.

2021-03-25 20:43 UTC, kruai approved these changes

2021-03-25 20:43 UTC, kruai commented on utils/payloads.py
> +# comment added for jenkins check
This should probably be removed, but it's not a big deal to me since it's a `utils/*` file

2021-03-25 21:32 UTC, thearifismail commented on utils/payloads.py
> +# comment added for jenkins check
thanks!.

2021-03-25 21:45 UTC, ryandillinfelton approved these changes

2021-03-25 21:45 UTC, ryandillinfelton commented
Looks good. I'd hold off merging until tomorrow morning though in case something goes wonky

2021-03-26 13:40 UTC, merged