[WIP] Add handler for system_profile messages
RedHatInsights/insights-host-inventory pull request #843
Opened 2021-03-23 22:09 UTC by kruai

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-12844).
This is still WIP, but I wanted to run this idea by you guys before I got too deep into it. Do you agree with the direction I'm taking? Obviously the functionality is not yet finished, there are no tests, etc.

Basically, I'm enhancing `inv_mq_service` to be configured with the env var `mq_restrict_to_field`, which informs how the message handler operates. The default is "ALL", which causes the service to work as it currently does. Setting it to "SYSTEM_PROFILE" tells the message handler to update the system profile, rather than add/update the whole host. 

I implemented it this way for flexibility, and due to discussions about AI CoE potentially requiring a similar approach but for a new field. I also wanted to avoid copypasta as much as possible, since the message-handling part of this is very similar to what we already have.

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-03-24 09:54 UTC, RonnyPfannschmidt requested changes
i do wonder if instead of a new service with new restrictions and deployment env vars,
a new message type wouldn't fit better


then the system profile update message could update jsut the system profile,
additionally we wouldnt see the event/egress queue order issues as well

if we basically start a new mq service with a new queue that inter spares different types of inventory updates we are going to see the same temporal issues we saw with just having 2 input queues

i think we should have a new message type for limited updates, not a new queue/mq consumer

2021-03-24 09:54 UTC, RonnyPfannschmidt commented on inv_mq_service.py
> +field_restriction_to_handler = {{"ALL": add_host}, {"SYSTEM_PROFILE": update_system_profile}}
this looks like it should be a single dict

2021-03-24 09:58 UTC, RonnyPfannschmidt commented
i  just cross-read the reasoning for the separate topic/deployment in the jira and i can agree on that

2021-03-24 10:03 UTC, RonnyPfannschmidt commented
i have a alternative proposal - how about instead of making a new topic with a different "permission" having a new message for the "non-reporter" updates and actually restricting the messages specific topics are allowed to consume

so the default topic would not be allowed to consume the system profile updates and the system profile topic would only be allowed to consume the system profile updates

i'm currently pretty sure that a new message type will be better than a shift of function in multiple layers

2021-03-24 12:59 UTC, kruai commented on inv_mq_service.py
> +field_restriction_to_handler = {{"ALL": add_host}, {"SYSTEM_PROFILE": update_system_profile}}
Yep, you're right!

2021-03-24 17:06 UTC, thearifismail commented
@kruai I feel I am missing some piece of information but going ahead with asking questions and commenting on it.

how will `non-reporters` be authenticating to access a host before modifying? 
IOW, how will they gain access to a host?

Why there has to be a different topic?  How about a new event_type?  For this event type, use `update_system_profile` method by finding the desired host.
`
EVENT_TYPE_MAP = {
    EventType.created: host_create_update_event,
    EventType.updated: host_create_update_event,
    EventType.delete: host_delete_event,
    EventType.update_system_profile: update_system_profile,
}

def def update_system_profile(input_host, identity, staleness_offset, fields):
    ...
    ...
    ...
    return output_host, existing_host.id, insights_id, UpdateSystemProfileResult.updated
`

2021-03-24 17:55 UTC, kruai commented
> @kruai I feel I am missing some piece of information but going ahead with asking questions and commenting on it.
> 
> how will `non-reporters` be authenticating to access a host before modifying?
> IOW, how will they gain access to a host?
> 
> Why there has to be a different topic? How about a new event_type? For this event type, use `update_system_profile` method by finding the desired host.
> 
> ```
> EVENT_TYPE_MAP = {
>     EventType.created: host_create_update_event,
>     EventType.updated: host_create_update_event,
>     EventType.delete: host_delete_event,
>     EventType.update_system_profile: update_system_profile,
> }
> 
> def def update_system_profile(input_host, identity, staleness_offset, fields):
>     ...
>     ...
>     ...
>     return output_host, existing_host.id, insights_id, UpdateSystemProfileResult.updated
> ```

Non-reporters will need to supply identity via metadata, just like we're used to.
We decided to go with a separate topic so that an influx of host-ingress messages wouldn't cause kafka lag for system-profile updates, and vice-versa. Messages that come in on the system-profile topic would only be allowed to modify the system_profile field on hosts. On this Jira card, Fero and I were chatting about this and agreed that we should use another operation type... though whether we'll need another event type might need a little more analysis

2021-03-24 18:11 UTC, thearifismail commented
Okay avoiding Kafka lag time makes sense and having a dedicated topic for system_profile update is fine.  Do we expect that much traffic?  If someone has a host.id, why shouldn't she be able to update the general properties of a host?  Why such block?

2021-03-24 18:17 UTC, kruai commented
> Okay avoiding Kafka lag time makes sense and having a dedicated topic for system_profile update is fine. Do we expect that much traffic? 

We don't expect it at first, but we don't know how frequently we're going to get these requests in the future, and we don't want their updates to be delayed if puptoo/yupana suddenly pushes 100K messages to the queue. We're also preparing for the possibility that AI CoE may also use this topic (if we don't give them their own; TBD)

> If someone has a host.id, why shouldn't she be able to update the general properties of a host? Why such block?

We're trying to lock down access as much as is reasonable. It would be nice to fully trust any app on our platform, but we don't want some random app to accidentally change a host's canonical facts or something. We only want to grant limited access to these apps that want to push this data without updating the staleness or reporter data.

2021-03-30 06:08 UTC, jharting requested changes

2021-03-30 06:08 UTC, jharting commented on app/queue/events.py
> +EventType = Enum("EventType", ("created", "updated", "delete", "system_profile_updated"))
The event type tells the downstream consumers how to deal with the given event (create a new entry, update existing one, delete old one). In this regard I don't think `system_profile_updated` is any different from `updated`. If you think downstream consumers may want to distinguish between different ways of host updates (e.g. host-ingress, system-profile or HTTP patch) it may be better to add that info in a specific event header.

2021-03-30 08:14 UTC, RonnyPfannschmidt commented on app/queue/events.py
> +EventType = Enum("EventType", ("created", "updated", "delete", "system_profile_updated"))
@kruai until we have a better handle on what we push out to consumers, i believe we should map the system profile update action to a normal update event

2021-03-30 08:37 UTC, RonnyPfannschmidt requested changes
overall this comes together nicely,
the considerations for output messages need some more iteration and a followup after other teams give input on what they want to use

2021-03-30 08:37 UTC, RonnyPfannschmidt commented on app/config.py
> +                self.logger.info("Kafka System Profile Topic: %s" % self.system_profile_topic)
short note on logging, lets replace all the `%` by `,`

2021-03-30 08:37 UTC, RonnyPfannschmidt commented on app/instrumentation.py
> +    logger.info("System profile updated for host", extra={"host": host_data})
for optional followup: would it help to make the host id part of the normal message?

2021-03-30 08:37 UTC, RonnyPfannschmidt commented on app/models.py
>              self.system_profile_facts = input_system_profile
followup critical question: i just took note, that the system profile update is a flat merge instead of a deep merge, is that a potential bug?

2021-03-30 08:37 UTC, RonnyPfannschmidt commented on lib/host_repository.py
> +            return output_host, existing_host.id, insights_id, AddHostResult.system_profile_updated
i believe at this point we should not return a `system_profile_updated` message until we have the consumers onboard

2021-03-30 12:53 UTC, kruai commented on app/queue/events.py
> +EventType = Enum("EventType", ("created", "updated", "delete", "system_profile_updated"))
OK, that's fine with me!

2021-03-30 12:54 UTC, kruai commented on app/config.py
> +                self.logger.info("Kafka System Profile Topic: %s" % self.system_profile_topic)
I can do that for my additions! If you think it's a big enough deal to change it for all of these strings, can you make a follow-up Jira for it?

2021-03-30 13:06 UTC, kruai commented on lib/host_repository.py
> +            return output_host, existing_host.id, insights_id, AddHostResult.system_profile_updated
Fine with me! Updated.

2021-03-30 13:38 UTC, RonnyPfannschmidt commented on app/instrumentation.py
> +    logger.info("System profile updated for host", extra={"host": host_data})
i vaguely recall tat i don't see host ids for those on the cli log, do we have a log processor that makes them accessible?

2021-03-30 13:39 UTC, RonnyPfannschmidt commented on app/models.py
>              self.system_profile_facts = input_system_profile
done

2021-03-30 14:37 UTC, kruai commented on app/instrumentation.py
> +    logger.info("System profile updated for host", extra={"host": host_data})
I'm not sure if it's super visible on the CLI log, but using this syntax causes the data to be outputted in the Kibana logs. You can see some examples of this [here](https://kibana.apps.crcp01ue1.o9m8.p1.openshiftapps.com/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(_source),filters:!(),index:'43c5fed0-d5ce-11ea-b58c-a7c95afd7a5d',interval:auto,query:(language:lucene,query:'@log_stream:%20%22inventory-mq%22%20AND%20@message:%20%22Host%20updated%22'),sort:!(!('@timestamp',desc))))

2021-03-30 19:53 UTC, kruai commented on app/instrumentation.py
> +    logger.info("System profile updated for host", extra={"host": host_data})
I was trying to keep it consistent with our add/update Host logging, but if we want to keep this log concise, that's fine with me. I'll make that change shortly

2021-03-30 19:54 UTC, thearifismail commented on app/config.py
> +                self.logger.info("Kafka Host Ingress Topic: %s", self.host_ingress_topic)
nitpick: should start using f"... {var}" instead of `%s, var`

2021-03-30 19:58 UTC, kruai commented on app/config.py
> +        self.kafka_consumer_topic = os.environ.get("KAFKA_CONSUMER_TOPIC", "platform.inventory.host-ingress")
This change follows the standards we set in the e2e PR: https://github.com/RedHatInsights/e2e-deploy/pull/2914
Basically, the `KAFKA_CONSUMER_TOPIC` tells the app which topic it should be assigned to. 

Setting `KAFKA_HOST_INGRESS_TOPIC` and `KAFKA_SYSTEM_PROFILE_TOPIC` allows the app to be aware of what the ingress and system profile topics are, so it can determine whether `KAFKA_CONSUMER_TOPIC == KAFKA_HOST_INGRESS_TOPIC`, `KAFKA_CONSUMER_TOPIC == KAFKA_SYSTEM_PROFILE_TOPIC`, etc.

2021-03-30 19:59 UTC, kruai commented on app/config.py
> +                self.logger.info("Kafka Host Ingress Topic: %s", self.host_ingress_topic)
I'd also be fine with that, but I just made that change to address @RonnyPfannschmidt 's earlier requested change. If y'all want these to change any more, please open up a Jira card, because that's unrelated to this PR's goal

2021-03-30 20:01 UTC, RonnyPfannschmidt commented on app/config.py
> +                self.logger.info("Kafka Host Ingress Topic: %s", self.host_ingress_topic)
full stop, this one is the valid logging syntax (no f strings there intentionally)

2021-03-30 20:06 UTC, kruai commented on app/instrumentation.py
> +    logger.info("System profile updated for host", extra={"host": host_data})
OK, updated

2021-03-30 20:08 UTC, kruai commented on app/config.py
> +                self.logger.info("Kafka Host Ingress Topic: %s", self.host_ingress_topic)
OK. In that case, I'm resolving this thread

2021-03-30 20:35 UTC, kruai commented on app/instrumentation.py
> +    logger.info("System profile updated for host", extra={"host": host_data})
As you and @thearifismail noted, it's most important that we log the Host ID for these transactions. I've changed the log to just output the message + the Host ID. My main concern with this is that it isn't great for auditing. Or is that not an issue?

2021-03-31 15:00 UTC, kruai commented on app/instrumentation.py
> +    logger.info("System profile updated for host", extra={"host": host_data})
Note: I've now updated `log_update_system_profile_failure` with this change as well.

2021-03-31 16:02 UTC, thearifismail commented
Will approve it after the update branch build completes.

2021-03-31 17:58 UTC, thearifismail commented on app/instrumentation.py
> +    logger.exception("Error updating system profile for host ID: %s", host_data.get("id"))
For failures, the whole host_data should be logged.

2021-03-31 18:00 UTC, kruai commented on app/instrumentation.py
> +    logger.exception("Error updating system profile for host ID: %s", host_data.get("id"))
OK. Reverted that change

2021-03-31 20:17 UTC, tahmidefaz approved these changes
Looks good! :+1:

2021-03-31 23:55 UTC, thearifismail approved these changes
My questions and comments have been addressed.

2021-04-01 10:02 UTC, RonnyPfannschmidt approved these changes

2021-04-01 13:23 UTC, jharting approved these changes

2021-04-01 13:31 UTC, merged