Updated identity and tests to use enums for identity type, auth_type,…
RedHatInsights/insights-host-inventory pull request #844
Opened 2021-03-24 00:19 UTC by thearifismail

… and cert_type

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-12861).
This PR updates identity and tests to use enums for `identity_type`, `auth_type`, and `cert_type`

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-03-24 19:16 UTC, kruai requested changes
This looks great! The only big thing I'd change is the capitalization to comply with Python's standards

2021-03-24 19:44 UTC, tahmidefaz commented
Looking good, I don't have any further concerns apart from what Asa mentioned. :+1:

2021-03-24 21:01 UTC, thearifismail commented on utils/payloads.py
> +    "system": {"cn": "1b36b20f-7fa0-4454-a6d2-008294e06378", "cert_type": "system"},
`payloads.py` is used for manual testing during development that's why it is better to keep it different from formal tests to avoid auto-piloting.

2021-03-24 21:33 UTC, thearifismail commented on utils/payloads.py
> +    "system": {"cn": "1b36b20f-7fa0-4454-a6d2-008294e06378", "cert_type": "system"},
@kruai keep it different to trigger thinking while testing.

2021-03-25 14:40 UTC, kruai approved these changes
LGTM

2021-03-25 14:42 UTC, tahmidefaz approved these changes

2021-03-25 14:42 UTC, merged