RHC-13159: Update the handling of missing platform_metadata
RedHatInsights/insights-host-inventory pull request #851
Opened 2021-03-29 23:14 UTC by thearifismail

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-13159).
This PR is to gracefully handle missing "identity" or the platform_metadata altogether

Log the host_data provided in the message.

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-03-30 15:32 UTC, kruai requested changes
Mostly looks good, but needs a couple changes

2021-03-30 15:32 UTC, kruai commented on tests/test_mq_service.py
> +
There's a lot of stuff in here that's unnecessary due to what you're testing.

```suggestion
def test_rhsm_reporter_and_no_platform_metadata(mocker, flask_app):
    host = minimal_host(
        account=SYSTEM_IDENTITY["account_number"],
        insights_id=generate_uuid(),
        reporter="rhsm-conduit",
        subscription_manager_id=OWNER_ID,
    )

    message = wrap_message(host.data(), "add_host")

    with pytest.raises(ValidationException):
        handle_message(json.dumps(message), mocker.Mock())


```

2021-03-30 15:32 UTC, kruai commented on tests/test_mq_service.py
> +    with pytest.raises(ValidationException):
This changes what the test is testing. This was originally supposed to test the scenario where an RHSM-reporter message has no identity, which results in a `ValueError`. This code change has altered it to another "no platform_metadata" test

2021-03-30 17:28 UTC, thearifismail commented on tests/test_mq_service.py
> +    with pytest.raises(ValidationException):
Fixed.  I should have passed platform_metadata without identity.

2021-03-30 17:29 UTC, thearifismail commented on tests/test_mq_service.py
> +
Fixed using your code.

2021-03-30 17:39 UTC, kruai commented on tests/test_mq_service.py
> +
If you did, you didn't push the change @thearifismail

2021-03-30 17:56 UTC, kruai submitted a review, later dismissed
LGTM

2021-03-30 19:35 UTC, tahmidefaz requested changes
The changes almost looks good to me.
Question: Are all the reporters aware of the fact that they need to send us some data in `platform_metadata`?

2021-03-30 19:35 UTC, tahmidefaz commented on app/queue/queue.py
> +        raise ValidationException("platform_metadata with identity is mandatory")
Should we change the message that comes with the `ValidationException` or change this to also check for the `identity` header in `platform_metadata`? `"platform_metadata with identity is mandatory"` is kind of misleading since we are not checking for `identity` here.

2021-03-31 19:09 UTC, thearifismail commented on app/queue/queue.py
> +        raise ValidationException("platform_metadata with identity is mandatory")
Fixed with `raise ValidationException("platform_metadata is mandatory")`

2021-03-31 19:16 UTC, thearifismail commented
> The changes almost looks good to me.
> Question: Are all the reporters aware of the fact that they need to send us some data in `platform_metadata`?

Should be covered by https://issues.redhat.com/browse/RHCLOUD-13160

2021-03-31 20:32 UTC, ryandillinfelton approved these changes

2021-03-31 23:08 UTC, merged

2021-03-31 23:09 UTC, thearifismail commented
I merged it because it has two approvals and LGTM from Asa