[WIP] disable owner_id check after matching owner_id to CN
RedHatInsights/insights-host-inventory pull request #856
Opened 2021-03-31 23:34 UTC by thearifismail

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-13254).
This PR disables `owner_id` check for adding host AFTER VERIFYING the `cn` in the requestor's `identity` matches the `owner_id` in the `host['system_profile']`.  This does not disable the owner_id check for CRUD operations.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-03-31 23:44 UTC, thearifismail commented
@fstavela, can you please try to update an existing host with a different owner_id.  First create a host as usual and then try to update it.  The only requirement is that when updating a host, update the value of `host['system_profile']['owner_id'] AND the `cn` in the identity.

2021-04-01 12:50 UTC, fstavela commented
> @fstavela, can you please test it by updating an existing host with a different owner_id. First create a host as usual and then try to update it. The only requirement is that when updating a host, update the value of `host['system_profile']['owner_id'] AND the `cn` in the identity.

@thearifismail 
I tested 5 scenarios with update. I used "4eeb3735-438f-4338-b0df-27912f153278" as identity.system.cn in all of them. These are the scenarios:
existing_host["system_profile"]["owner_id"] = None
message["data"]["system_profile"]["owner_id"] = "4eeb3735-438f-4338-b0df-27912f153278"
PASSED - owner_id has been updated to "4eeb3735-438f-4338-b0df-27912f153278"

existing_host["system_profile"]["owner_id"] = None
message["data"]["system_profile"]["owner_id"] = None
PASSED - owner_id has been updated to "4eeb3735-438f-4338-b0df-27912f153278"

existing_host["system_profile"]["owner_id"] = "4eeb3735-438f-4338-b0df-27912f153278"
message["data"]["system_profile"]["owner_id"] = None
PASSED - host has been updated and owner_id stayed as "4eeb3735-438f-4338-b0df-27912f153278"

existing_host["system_profile"]["owner_id"] = "0b32fb94-a265-4b85-9728-d86a0b6a3092"
message["data"]["system_profile"]["owner_id"] = "4eeb3735-438f-4338-b0df-27912f153278"
PASSED - owner_id has been updated to "4eeb3735-438f-4338-b0df-27912f153278"

existing_host["system_profile"]["owner_id"] = "0b32fb94-a265-4b85-9728-d86a0b6a3092"
message["data"]["system_profile"]["owner_id"] = None
FAILED - host has not been updated. I think the owner_id should be updated to  "4eeb3735-438f-4338-b0df-27912f153278" here (from CN), same as in the second scenario.
```
Traceback (most recent call last):
  File "/home/fstavela/redhat/services/insights-host-inventory/app/queue/queue.py", line 221, in event_loop
    handler(message.value, event_producer)
  File "<decorator-gen-6>", line 2, in handle_message
  File "/home/fstavela/.local/share/virtualenvs/insights-host-inventory-0M2Qa99W/lib/python3.6/site-packages/prometheus_client/context_managers.py", line 66, in wrapped
    return func(*args, **kwargs)
  File "/home/fstavela/redhat/services/insights-host-inventory/app/queue/queue.py", line 195, in handle_message
    host = _set_owner(host, identity)
  File "/home/fstavela/redhat/services/insights-host-inventory/app/queue/queue.py", line 91, in _set_owner
    raise ValidationException("The owner in host does not match the owner in identity")
app.exceptions.ValidationException: The owner in host does not match the owner in identity
```

I also tested scenarios where message["data"]["system_profile"]["owner_id"] != identity.system.cn (and neither of them is None) and all scenarios passed - the host has NOT been updated.

And I have one question, is the identity required even if the reporter is rhsm-conduit?

2021-04-08 14:21 UTC, thearifismail commented
@lphiri please review.  Thanks!

2021-04-08 15:44 UTC, kruai requested changes
Sorry, I'm not quite understanding why we need to add a new `include_owner_id` parameter to multiple functions, when we already have the Identity to work with. We may need to step back and ask what scenarios we _do_ want to restrict based on `owner_id`.

2021-04-08 15:44 UTC, kruai commented on lib/host_repository.py
> +):
Why do we need this new `include_owner_id` parameter? The only place this function is called is in `add_host()` in queue.py, and it's set to False there.

2021-04-08 15:44 UTC, kruai commented on lib/host_repository.py
> +def find_existing_host(identity, canonical_facts, include_owner_id=True):
Same question here. This function is only used by `add_host()` and `update_system_profile()`, and it makes sense to keep their functionality in sync.

(Note: It's also used by the ultra-light check-in API endpoint, but that's not really used at the moment, and I don't think it should be considered for this issue)

2021-04-08 18:11 UTC, thearifismail commented on lib/host_repository.py
> +):
Now `include_owner_id` is used to call `single_canonical_fact_host_query` and `multiple_canonical_facts_host_query`

2021-04-08 18:11 UTC, thearifismail commented on lib/host_repository.py
> +def find_existing_host(identity, canonical_facts, include_owner_id=True):
Now include_owner_id is used to call `single_canonical_fact_host_query` and `multiple_canonical_facts_host_query`

2021-04-08 20:31 UTC, ryandillinfelton requested changes
The host repository changes look good to me. I think the tests could be improved though, especially the one checking changing the owner_id. It doesn't look like it's verifying that the owner id has been changed.

2021-04-08 20:31 UTC, ryandillinfelton commented on tests/test_mq_service.py
> +    assert updated_event["host"]["display_name"] != created_event["host"]["display_name"]
I think it'd be better to check that each display name is set to the correct value, not just that they're different.

2021-04-08 20:31 UTC, ryandillinfelton commented on tests/test_mq_service.py
> +    assert updated_host.fqdn == created_host.fqdn
It looks like you change `cn` when you update the host, but I don't see where you check that the owner_id has been updated

2021-04-08 22:17 UTC, thearifismail commented on tests/test_mq_service.py
> +    assert updated_event["host"]["display_name"] != created_event["host"]["display_name"]
Added:
`    assert db_get_host(created_host.id).display_name == "test_host"
     assert updated_host.display_name == "better_test_host"
`

2021-04-08 22:18 UTC, thearifismail commented on tests/test_mq_service.py
> +    assert updated_host.fqdn == created_host.fqdn
Added:
`
    assert updated_host.system_profile.get("owner_id") == "137c9d58-941c-4bb9-9426-7879a367c23b"
`

2021-04-09 01:31 UTC, ryandillinfelton approved these changes
LGTM

2021-04-09 15:17 UTC, kruai requested changes

2021-04-09 15:17 UTC, kruai commented on tests/test_mq_service.py
> +    assert created_event["host"]["display_name"] == "test_host"
Why call `mq_create_or_update_host()` on the same host twice? It doesn't look like you're using any of the extra data afforded to you by passing `return_all_data=True`. It's giving you the same data in a different format, since that function creates the HostWrapper using the event data

2021-04-09 15:17 UTC, kruai commented on tests/test_mq_service.py
> +    assert updated_host.display_name != created_host.display_name
This inequality assertion is redundant, since you're making an equality assertion right under it

2021-04-09 15:17 UTC, kruai commented on tests/test_mq_service.py
> +    assert updated_event["host"]["display_name"] == "better_test_host"
Same thing as above; you don't need to repeat the host-creation and assertions. It's just giving you the same data in a different format, and then you're asserting the same things

2021-04-09 15:17 UTC, kruai commented on tests/test_mq_service.py
> +    assert updated_host.insights_id == created_host.insights_id
You've already verified that it's the same host, so I don't see why you'd need to validate the insights_id in this test

2021-04-09 15:17 UTC, kruai commented on tests/test_mq_service.py
> +    assert updated_host.display_name == "better_test_host"
I'd recommend also adding an owner_id assertion to this section. Something like
`assert updated_host.system_profile["owner_id"] == "137c9d58-941c-4bb9-9426-7879a367c23b"`

2021-04-09 15:33 UTC, tahmidefaz requested changes
Just left some tiny suggestions, mostly looks good :+1:

2021-04-09 15:33 UTC, tahmidefaz commented on tests/test_mq_service.py
> +    new_id["system"]["cn"] = "137c9d58-941c-4bb9-9426-7879a367c23b"
nitpick: since we use this UUID in three different places in this test, might be nice to assign it to a variable for cleanliness :slightly_smiling_face:

2021-04-09 15:33 UTC, tahmidefaz commented on lib/host_repository.py
> +    logger.debug("find_existing_host(%s, %s, %s)", identity, canonical_facts)
This change isn't necessary

2021-04-09 15:33 UTC, tahmidefaz commented on lib/host_repository.py
> +    logger.debug("find_host_by_single_canonical_fact(%s, %s, %s, %s)", identity, canonical_fact)
any reason to stop logging the `value`? Also, I think the extra `%s` is wrong

2021-04-09 15:33 UTC, tahmidefaz commented on tests/test_mq_service.py
> +    assert updated_host.display_name == "better_test_host"
I think `assert updated_host.display_name != created_host.display_name` is redundant here.

2021-04-09 15:33 UTC, tahmidefaz commented on tests/test_mq_service.py
> +    assert updated_event["host"]["display_name"] != created_event["host"]["display_name"]
This one seems a little redundant as well since we check `updated_event["host"]["display_name"] == "better_test_host"` later in the test

2021-04-09 15:35 UTC, tahmidefaz commented on lib/host_repository.py
> +def single_canonical_fact_host_query(identity, canonical_fact, value, include_owner_id=True):
I support this as well. Renaming this will make it more clear :+1:

2021-04-09 16:05 UTC, thearifismail commented on tests/test_mq_service.py
> +        message_operation=mock_add_host,
Removed, very likely related to the redundant `else` statement in the fixture that Tahmid had run into.

2021-04-09 16:05 UTC, thearifismail commented on lib/host_repository.py
> +def multiple_canonical_facts_host_query(identity, canonical_facts, include_owner_id=True):
Yes for parity and clarity

2021-04-09 16:05 UTC, thearifismail commented on lib/host_repository.py
> +def single_canonical_fact_host_query(identity, canonical_fact, value, include_owner_id=True):
Done!

2021-04-09 16:05 UTC, thearifismail commented on lib/host_repository.py
> +    logger.debug("find_host_by_single_canonical_fact(%s, %s, %s, %s)", identity, canonical_fact)
Done!

2021-04-09 16:06 UTC, thearifismail commented on lib/host_repository.py
> +    logger.debug("find_existing_host(%s, %s, %s)", identity, canonical_facts)
Done!

2021-04-09 16:14 UTC, thearifismail commented on tests/test_mq_service.py
> +    new_id["system"]["cn"] = "137c9d58-941c-4bb9-9426-7879a367c23b"
Not so much because the same value was being used in other places.  Set the value to a const `NEW_CN`

2021-04-09 16:14 UTC, thearifismail commented on lib/host_repository.py
> +    logger.debug("find_existing_host(%s, %s, %s)", identity, canonical_facts)
fixed.

2021-04-09 16:15 UTC, thearifismail commented on lib/host_repository.py
> +    logger.debug("find_host_by_single_canonical_fact(%s, %s, %s, %s)", identity, canonical_fact)
typo, put it back in.

2021-04-09 16:17 UTC, thearifismail commented on tests/test_mq_service.py
> +    assert updated_host.display_name == "better_test_host"
Didn't have it first but then Ryan pointed out to better show it for confirmation.  I agree with him.  This just shows that the new display name is the desired one.

2021-04-09 16:20 UTC, thearifismail commented on tests/test_mq_service.py
> +    assert updated_event["host"]["display_name"] != created_event["host"]["display_name"]
Though may be redundant but this test uses same test is used to get two different responses.  First returns host and second returns an event with the host in it.

2021-04-09 17:04 UTC, kruai commented on tests/test_mq_service.py
> +    new_id["system"]["cn"] = "137c9d58-941c-4bb9-9426-7879a367c23b"
I don't think it needs to be scoped to the top-level of the file... this should probably be defined in the test itself

2021-04-09 17:11 UTC, kruai commented on tests/test_mq_service.py
> +    assert updated_host.display_name == "better_test_host"
I think @tahmidefaz is echoing what I also commented... since you're already asserting that `foo == bar`, it doesn't make sense to also assert that `foo != baz`. 

As far as what Ryan pointed out... it looks to me like he was requesting you assert `foo == bar` _instead of_ `foo != baz`. But feel free to clarify if I read that wrong @ryandillinfelton

2021-04-09 17:15 UTC, kruai commented on tests/test_mq_service.py
> +    assert updated_event["host"]["display_name"] != created_event["host"]["display_name"]
But it's the same data... see this line in [mq_create_or_update_host()](https://github.com/RedHatInsights/insights-host-inventory/blob/mq-sp-fixes/tests/fixtures/mq_fixtures.py#L42). It's the same data in a different format.

If you don't need all the extra data (event key, headers, etc), there's no reason to set `return_all_data=True`

2021-04-09 17:18 UTC, kruai requested changes
I still have unaddressed issues from my previous review, and I agree with Tahmid's requested changes.

2021-04-09 19:34 UTC, thearifismail commented on tests/test_mq_service.py
> +    assert updated_host.insights_id == created_host.insights_id
removed!

2021-04-09 19:35 UTC, thearifismail commented on tests/test_mq_service.py
> +    assert updated_host.fqdn == created_host.fqdn
Removed FQDN check

2021-04-09 19:35 UTC, thearifismail commented on tests/test_mq_service.py
> +    assert updated_host.system_profile.get("owner_id") != created_host.system_profile.get("owner_id")
Done!

2021-04-09 19:43 UTC, thearifismail commented on tests/test_mq_service.py
> +    assert created_event["host"]["display_name"] == "test_host"
The one returning host would not include system_profile so owner_id could not be checked. Whereas the event returned by "return_all_data" included "host" with "system_profile" in it.  That's why I used both.  Though it looked redundant, I erred on providing more info than needed.  Now using only "return_all_data" call.

2021-04-09 19:44 UTC, thearifismail commented on tests/test_mq_service.py
> +    assert updated_host.display_name != created_host.display_name
Gone!

2021-04-09 19:44 UTC, thearifismail commented on tests/test_mq_service.py
> +    assert updated_event["host"]["display_name"] == "better_test_host"
Gone!

2021-04-09 19:45 UTC, thearifismail commented on tests/test_mq_service.py
> +    assert updated_host.insights_id == created_host.insights_id
Gone!

2021-04-09 19:45 UTC, thearifismail commented on tests/test_mq_service.py
> +    assert updated_host.display_name == "better_test_host"
Done!

2021-04-09 19:45 UTC, thearifismail commented on tests/test_mq_service.py
> +    assert updated_host.display_name == "better_test_host"
Gone!

2021-04-09 19:46 UTC, thearifismail commented on tests/test_mq_service.py
> +    assert updated_event["host"]["display_name"] != created_event["host"]["display_name"]
Gone!

2021-04-09 20:13 UTC, thearifismail commented on tests/test_mq_service.py
> +    new_id["system"]["cn"] = "137c9d58-941c-4bb9-9426-7879a367c23b"
@kruai the same value was being used in 3 different tests, so I defined it at the top-level.  I can move the "NEW_CN" to tests if that's what is desired.

2021-04-09 20:19 UTC, tahmidefaz requested changes
Mostly looks good, had one request

2021-04-09 20:19 UTC, tahmidefaz commented on tests/test_mq_service.py
> +    assert updated_event["host"]["system_profile"]["owner_id"] == NEW_CN
I meant to assign this UUID to a variable within the scope of this test function. Having this as on the higher scope seems a little messy :slightly_smiling_face:

2021-04-09 20:34 UTC, thearifismail commented on tests/test_mq_service.py
> +    assert updated_event["host"]["system_profile"]["owner_id"] == NEW_CN
Localized `NEW_CN` to tests and removed the global var.

2021-04-09 20:39 UTC, tahmidefaz approved these changes
Looks good!

2021-04-12 14:22 UTC, kruai approved these changes
LGTM

2021-04-12 14:22 UTC, kruai commented on tests/test_mq_service.py
> +    assert created_event["host"]["display_name"] == "test_host"
I don't see why it wouldn't have `system_profile` in it... but even though I don't think we need `return_all_data=True` for this, I don't see it as a reason to hold up this PR.

2021-04-12 14:24 UTC, merged