Transform subscription_manager_id to have dashes when setting it to owner_id [RHCLOUD-12813]
RedHatInsights/insights-host-inventory pull request #860
Opened 2021-04-07 16:47 UTC by tahmidefaz

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-12813).

Adds dashes to the value of subscription_manager_id when we set that to `system.cn` or `system_profile.owner_id` for hosts reported by `rhsm-conduit`.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [x] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [x] Tests: validate exceptions and failure scenarios
- [x] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [x] Input Validation
- [x] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [x] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

2021-04-07 18:27 UTC, kruai requested changes

2021-04-07 18:27 UTC, kruai commented on tests/test_mq_service.py
> +    metadata_without_b64 = get_platform_metadata(identity=USER_IDENTITY)
Makes more sense to use the `SYSTEM_IDENTITY` here, right?

2021-04-07 18:27 UTC, kruai commented on tests/fixtures/mq_fixtures.py
> +        elif overwrite_identity:
Wondering if there's a more elegant solution... do other tests break if you just check the identity field like this?
```suggestion
        elif "b64_identity" not in platform_metadata:
```

2021-04-07 18:27 UTC, kruai commented on tests/test_mq_service.py
> +    assert event["host"]["system_profile"]["owner_id"] != OWNER_ID
This assertion is unnecessary, since you assert equality in the next line.

2021-04-07 18:36 UTC, tahmidefaz commented on tests/fixtures/mq_fixtures.py
> +        elif overwrite_identity:
Actually, one of the test I wrote here is meant to not have the `b64_identity` so that we can validate the custom logic :slightly_smiling_face:

2021-04-07 19:43 UTC, kruai commented on tests/fixtures/mq_fixtures.py
> +        elif overwrite_identity:
I see... I was a bit confused bc I thought we already tested with that scenario. Should this test be merged with the existing [test_rhsm_reporter_and_no_identity](https://github.com/RedHatInsights/insights-host-inventory/blob/cfa63ab04980d2fd638ac41a75fbe754999892f6/tests/test_mq_service.py#L1197) one?

It looks like that test has a different approach to creating the host without setting the Identity

2021-04-08 10:26 UTC, thearifismail commented on tests/fixtures/mq_fixtures.py
> +        elif overwrite_identity:
@tahmidefaz I don't remember the context for adding the `else platform_metadata["b64_identity"] = get_encoded_idstr()` statement.  If you look at [PR-856](https://github.com/RedHatInsights/insights-host-inventory/pull/856), this `else` statement has been taken out.  I run into the same issue while writing a test involving 'CN` change.  If you take out the `else` statement before your change, `overwrite_identity` parameter is not needed anymore.

2021-04-08 10:42 UTC, thearifismail requested changes
From `mq_fixtures.py`, delete the statement 
`        elif overwrite_identity:
            platform_metadata["b64_identity"] = get_encoded_idstr()
` 
and `overwrite_identity`, which is not needed.

2021-04-08 12:41 UTC, tahmidefaz commented on tests/fixtures/mq_fixtures.py
> +        elif overwrite_identity:
@thearifismail great suggestion! Removing that `else` statement did fail one of the tests, but it was very simple to fix by just adding a `reporter` and `subscription_manager_id`. So, I went ahead and removed it!

@kruai I have been poking around and trying the follow the pattern in that test and I think it was getting a little complex and confusing. I choose to simply take Arif's suggestion and keep this test simple. Lmk, if you think otherwise :slightly_smiling_face:

2021-04-08 12:45 UTC, thearifismail reviewed
LGTM.  Will approve upon the successful execution of the build

2021-04-08 13:12 UTC, kruai commented on tests/fixtures/mq_fixtures.py
> +        elif overwrite_identity:
Yep, that works for me. I just didn't want to add yet another param to that function when it only seemed to be used in that one test. I like the way it looks now

2021-04-08 13:13 UTC, kruai approved these changes
LGTM!

2021-04-08 13:15 UTC, thearifismail approved these changes
LGTM

2021-04-08 13:29 UTC, merged