Add filter for system profile operating_system field
RedHatInsights/insights-host-inventory pull request #866
Opened 2021-04-13 02:10 UTC by ryandillinfelton

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-13257).
We need a way to filter based on the operating system field of system profile. This adds support and some tests.

corresponding xjoin-search PR is here: https://github.com/RedHatInsights/xjoin-search/pull/95

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-04-13 14:27 UTC, kruai requested changes
Implementation looks good to me; I have a few suggestions for the tests

2021-04-13 14:27 UTC, kruai commented on tests/test_xjoin.py
> +# system_profile insights_client_version tests
Copypasta comment doesn't apply here

2021-04-13 14:27 UTC, kruai commented on tests/test_xjoin.py
> +    mocker, subtests, query_source_xjoin, graphql_query_empty_response, patch_xjoin_post, api_get
`query_source_xjoin` and `patch_xjoin_post` aren't used in this test

2021-04-13 14:27 UTC, kruai commented on tests/test_xjoin.py
> +            response_status, response_data = api_get(url)
Since `response_data` isn't used, would it make more sense to do it this way?
```suggestion
            response_status = api_get(url)[0]
```

2021-04-13 20:47 UTC, tahmidefaz commented on api/host_query_xjoin.py
> +
@ryandillinfelton `major` and `minor` are `integers`, is the interface for `strings` and `integers` different for `xjoin-search`?

2021-04-14 13:45 UTC, thearifismail commented on tests/test_xjoin.py
> +    mocker, subtests, query_source_xjoin, graphql_query_empty_response, patch_xjoin_post, api_get
`query_source_xjoin` gets hit by some behind the scene call; just verified using  debugger

2021-04-16 20:38 UTC, ryandillinfelton commented on tests/test_xjoin.py
> +            response_status, response_data = api_get(url)
:+1:

2021-04-16 21:23 UTC, ryandillinfelton commented
You'll notice that there is validation code strewn about in here. I'm thinking of it as a "better than nothing" stop gap until I can address it in this spike: https://issues.redhat.com/browse/RHCLOUD-10001

2021-04-21 19:19 UTC, ryandillinfelton commented on api/host_query_xjoin.py
> +            raise ValidationException(f"Incomplete path provided: {operating_system} ")
WRT the ongoing ValidationException metrics discussion. Should I set this up to increment any counter?
Also, partly a question for myself really. Is raising an exception here the right approach or should I be doing something else?

2021-04-21 19:35 UTC, tahmidefaz commented on api/host_query_xjoin.py
> +            raise ValidationException(f"Incomplete path provided: {operating_system} ")
I am not sure if we should increment any metrics here since we don't have any metrics for API validation exceptions. Throwing a `ValidationException` and a subsequent response `400` here sounds good to me.

2021-04-21 20:05 UTC, ryandillinfelton commented on api/host_query_xjoin.py
> +            raise ValidationException(f"Incomplete path provided: {operating_system} ")
After further exploration the ValidationExceptions seem to work how I want. I suppose we only want to track validation exceptions from uploads right? Someone messing up a query really shouldn't be cause for alarm.

2021-04-21 21:16 UTC, tahmidefaz commented on api/host_query_xjoin.py
> +            raise ValidationException(f"Incomplete path provided: {operating_system} ")
Yep! That's sounds right to me! :+1:

2021-04-22 15:15 UTC, thearifismail commented on tests/test_xjoin.py
> +    http_queries = (
Should test for `invalid version` value like `filter[system_profile][operating_system][RHEL][version][gte]="Johny"

2021-04-22 15:15 UTC, thearifismail commented on tests/test_xjoin.py
> +    graphql_queries = (
Should test for invalid version values

2021-04-22 18:47 UTC, ryandillinfelton commented on tests/test_xjoin.py
> +    http_queries = (
added to the below exception handling test

2021-04-22 18:47 UTC, ryandillinfelton commented on tests/test_xjoin.py
> +    graphql_queries = (
Added some more invalid values to the exception handling test below this one

2021-04-22 18:58 UTC, tahmidefaz approved these changes
Looks good :+1:

2021-04-22 19:36 UTC, thearifismail approved these changes

2021-04-23 19:17 UTC, kruai approved these changes
LGTM!

2021-04-23 19:17 UTC, merged