Add owner id filter
RedHatInsights/insights-host-inventory pull request #876
Opened 2021-04-15 21:09 UTC by tahmidefaz

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-13172).
Adds filter for owner_id including the filtering of multiple owner_ids

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-04-16 16:15 UTC, tahmidefaz commented
To make you all's life a little easier, `api/host_query_xjoin.py ` is the place you want to start. The tests are almost an exact copy of the `rhc_client_id` since this filter is no different than that one. This PR also enables filtering based on multiple `owner_id` and `rhc_client_id`

2021-04-16 19:17 UTC, ryandillinfelton requested changes
Mostly looks good. I pointed out some improvements I'd like to see.

2021-04-16 19:17 UTC, ryandillinfelton commented on api/host_query_xjoin.py
> +    else:
Since we have basically no validation of these from the api spec (and this recently bit Ronny) I'd like to at least get some decent validation coverage in the executive code for new filters. you don't have to go add checks to everything in the file, but right here could use one. Instead of assuming anything that doesn't fit the first case is a list, an explicit check that it's a list and an else that raises a validation exception would be nice.
```suggestion
    if isinstance(field_value, list) or isinstance(field_value[operation], list):
        return build_filter(field_name, field_value[operation], list, operation, _nullable_multiple_string_filter)
    else:
        raise ValidationException(f"field_name expected to be a string or array of strings, instead got {type(field_value)}")
```
something like that. The suggestion is not precise.

2021-04-16 19:17 UTC, ryandillinfelton commented on api/host_query_xjoin.py
> +        system_profile_filter += build_filter_string_multiple(
TY :heart:

2021-04-16 19:17 UTC, ryandillinfelton commented on tests/test_xjoin.py
> +def test_query_hosts_filter_spf_rhc_client_id_multiple(
:heart: :heart:

2021-04-19 21:09 UTC, tahmidefaz commented on api/host_query_xjoin.py
> +def build_filter_string_multiple(field_name, field_value, field_type, operation):
I think the `field_type` was kind of implied by the function name. Removed. :+1:

2021-04-19 21:11 UTC, tahmidefaz commented on api/host_query_xjoin.py
> +    else:
Added a `ValidationException` and added tests for it as well :+1:

2021-04-21 20:40 UTC, ryandillinfelton commented on tests/test_xjoin.py
> +    mocker.patch(
I don't understand what this patch is supposed to do

2021-04-21 20:54 UTC, tahmidefaz commented on tests/test_xjoin.py
> +    mocker.patch(
I added this test as a followup to one of your earlier concern that we should throw a `ValidationException` whenever `build_filter_string_multiple` receive something other than a string or an array. However, I didn't find an easy way to have it receive anything but a string or an array. Therefore, I am patching the return value of `api.parsing.customURIParser._make_deep_object` to intentionally make `build_filter_string_multiple` receive `{"owner_id": {"eq": None}}` (in other world, a `nulltype`) so that we can hit that `ValidationException` in `build_filter_string_multiple`. Does this clear it up a little?

2021-04-21 21:32 UTC, ryandillinfelton commented on tests/test_xjoin.py
> +    mocker.patch(
Yeah it clears it up. It does make me question if we even need to handle that if it basically can't happen.

2021-04-21 21:40 UTC, ryandillinfelton commented on tests/test_xjoin.py
> +    mocker.patch(
If you hit the endpoint with `?filter[system_profile][owner_id][foo][bar]` it should come through as a `dict` for those checks and fail. Though I think you'd want to catch those with another kind of check to make sure the operation is valid. But that could be a good way to catch invalid paths and not have them cause a `500`

2021-04-23 16:56 UTC, tahmidefaz commented on tests/test_xjoin.py
> +    mocker.patch(
Yes! I was scratching my head around it a bit, and my changes that I committed earlier actually catches it throws `ValidationExceptions` accordingly (I didn't even know)! So, I just went ahead and simplified my invalid tests :+1: 
Lmk, what you think!

2021-04-23 18:31 UTC, ryandillinfelton approved these changes
Sweet! Looking good now :+1:

2021-04-23 19:32 UTC, ryandillinfelton approved these changes

2021-04-23 21:20 UTC, ryandillinfelton commented
@thearifismail @kruai Monday thing, but we just need one more :+1: on this

2021-04-26 13:06 UTC, kruai approved these changes
LGTM!

2021-04-26 13:07 UTC, kruai commented on tests/test_xjoin.py
> +    mocker.patch(
@ryandillinfelton anything you wanna follow up on in this thread?

2021-04-26 13:22 UTC, merged