[WIP] RHC-12580: Add cloud provider to model/DB as canonical facts
RedHatInsights/insights-host-inventory pull request #887
Opened 2021-04-26 21:46 UTC by thearifismail

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-12586).
It adds cloud provider type and Id to model, i.e. database, canonical_facts.  It is the first of two PRs for adding provider support.  The second PR will implement API support.

The only requirement is that if a `provider_type` is provided, `provide_id` must be present.  Both are of type String with max_length 50.  Provider_type must be "alibaba", "aws", "azure", "gcp", or "ibm".  Unknown provider_types will encounter "ValidationException"

cc @syncrou @roliveri, 
## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-04-27 13:52 UTC, thearifismail commented
@ryandillinfelton comment from PR #887 
> Since host creation isn't synchronous users won't see this message and be able to correct the payload they're sending. If this exception occurs this message will pretty much just be for us, and the problem will likely lie with a reporter sending the wrong data or us needing to expand the enum of acceptable provider type. I would leave off the valid provider types part of the message.
Added reporter to the message.

2021-04-27 17:53 UTC, ryandillinfelton requested changes

2021-04-27 17:53 UTC, ryandillinfelton commented on app/queue/events.py
> +    provider_id = fields.Str()
I know this is picky but could they be next to each other?

2021-04-27 17:53 UTC, ryandillinfelton commented on docs/_index.md
> +- `provider_id`
Looks like provider_type is missing in the list of canonical facts. There should also be some note about type being required if ID is present and vice versa

2021-04-27 17:53 UTC, ryandillinfelton commented on docs/_index.md
> +          "provider_id": "<provider_id>",
Type should also be in this list

2021-04-27 17:53 UTC, ryandillinfelton commented on tests/test_unit.py
> +            "canonical_facts": {"fqdn": "some fqdn", "provider_id": "i-05d2313e6b9a42b16"},
I thought provider_type was required if provider_id was defined?

2021-04-27 17:53 UTC, ryandillinfelton commented on tests/test_mq_service.py
> +    "provider", ({"type": "invalid", "id": "i-05d2313e6b9a42b16"}, {"type": "azure"}, {"id": generate_uuid()})
Shouldn't azure be valid? it's in both the valid and invalid tests?

2021-04-27 18:30 UTC, kruai requested changes
In addition to the testing notes I had in my comments, I think additional tests are required. We need to validate that the app will find a host based on the `provider_id` before the other canonical fact fields (since it's an elevated ID), and also that the `insights_id` and `subscription_manager_id` take priority.

Also, as I mentioned in my comments, the validation code should be in the schema definition, not in a separate function that's called before schema validation.

2021-04-27 18:30 UTC, kruai commented on app/queue/events.py
> +    provider_id = fields.Str()
I second this; I'd prefer if `provider_type` was moved up here

2021-04-27 18:30 UTC, kruai commented on docs/_index.md
> +          "provider_id": "<provider_id>",
+1

2021-04-27 18:30 UTC, kruai commented on docs/_index.md
> +- `provider_id`
+1

2021-04-27 18:30 UTC, kruai commented on docs/_index.md
> +
Same thing - `provider_type` should also be here

2021-04-27 18:30 UTC, kruai commented on app/serialization.py
> +
I don't think this validation logic should be in its own function separate from the schema validation. Since these fields are part of the schema, this logic should be defined within CanonicalFactsSchema as a `@validates` method.

2021-04-27 18:30 UTC, kruai commented on tests/test_mq_service.py
> +    "provider", ({"type": "invalid", "id": "i-05d2313e6b9a42b16"}, {"type": "azure"}, {"id": generate_uuid()})
The type "azure" is valid, but according to the validation function, it's not valid to define a provider_type without a provder_id.

2021-04-27 18:30 UTC, kruai commented on tests/test_mq_service.py
> +    "provider", ({"type": "invalid", "id": "i-05d2313e6b9a42b16"}, {"type": "azure"}, {"id": generate_uuid()})
That being said, your validation function doesn't look like it should be failing if you provide a provder_id without provider_type. Your validation function & the deserialization function both return a ValidationException; can you verify that the correct exception is being raised?

Also, the functionality you're changing isn't really MQ-related, so I don't think these are the tests you should be adding... I think it makes more sense to instead add to `test_models.py` to test the model validation, and perhaps add to (or modify) `test_unit.py` if you want to verify something specific with the serialization/deserialization.

2021-04-27 18:30 UTC, kruai commented on tests/test_unit.py
> +            "canonical_facts": {"fqdn": "some fqdn", "provider_id": "i-05d2313e6b9a42b16"},
The change to this line is also unnecessary... `provider_id` isn't always required, so I think this test should be left alone

2021-04-27 18:30 UTC, kruai commented on tests/test_mq_service.py
> +        mq_create_or_update_host(host)
Same thing here - what you're testing is the model, not the MQ service

2021-04-28 15:04 UTC, thearifismail commented on app/queue/events.py
> +    provider_id = fields.Str()
Done!

2021-04-28 15:20 UTC, thearifismail commented on docs/_index.md
> +          "provider_id": "<provider_id>",
Done!

2021-04-28 21:44 UTC, thearifismail commented on docs/_index.md
> +- `provider_id`
Done!

2021-04-28 21:44 UTC, thearifismail commented on docs/_index.md
> +
Done!

2021-04-29 22:14 UTC, thearifismail commented on tests/test_unit.py
> +            "canonical_facts": {"fqdn": "some fqdn", "provider_id": "i-05d2313e6b9a42b16"},
Done!

2021-04-29 23:13 UTC, thearifismail commented on tests/test_mq_service.py
> +    "provider", ({"type": "invalid", "id": "i-05d2313e6b9a42b16"}, {"type": "azure"}, {"id": generate_uuid()})
Moved tests to `test_models.py` testing `CanonicalFactsSchema`

2021-04-29 23:14 UTC, thearifismail commented on app/serialization.py
> +
moved this logic to CanonicalFactSchema.

2021-04-30 13:42 UTC, thearifismail commented
>We need to validate that the app will find a host based on the provider_id before the other canonical fact fields (since it's an elevated ID), and also that the insights_id and subscription_manager_id take priority.

Adding new tests requires updating `api` package leading to PR becoming too big.  The intent of this PR is to get `provider_id` and `provider_type` into model.  This PR does that along with tests testing model.

I think adding tests to find hosts based on provider_id should be done in a separate PR to keep the PR size manageable.

2021-05-06 16:33 UTC, kruai requested changes

2021-05-06 16:33 UTC, kruai commented on tests/fixtures/mq_fixtures.py
> +            fqdn = f"host{i}.domain.test"
Why set the `fqdn` to this predetermined value? Doesn't seem necessary

2021-05-06 16:33 UTC, kruai commented on tests/fixtures/mq_fixtures.py
> +            i += 1
Instead of doing this:
```
i = 0
while i < num:
  i += 1
```

I think it's much cleaner to do this:
```
for i in range(0, num):
```

2021-05-06 16:33 UTC, kruai commented on tests/test_api_hosts_get.py
> +    assert len(response_data["results"]) == 20
Not sure this makes sense to have in the test, since the purpose of the test is to validate the `provider_type` query. If you change the random part of the test (below this) to instead check every value, this section will be redundant

2021-05-06 16:33 UTC, kruai commented on tests/test_models.py
> +    canonical_facts = {"provider_id": provider.get("id"), "provider_type": provider.get("type"), "reporter": "test"}
`reporter` isn't a canonical fact

2021-05-06 16:33 UTC, kruai commented on tests/test_models.py
> +def test_invalid_providers(mq_create_or_update_host, provider):
`mq_create_or_update_host` is not used

2021-05-06 16:33 UTC, kruai commented on tests/test_models.py
> +from marshmallow import ValidationError as MarshmallowValidationError
Why? You're importing the same thing twice

2021-05-06 16:33 UTC, kruai commented on tests/test_deduplication.py
>  def test_find_host_using_elevated_ids_match(db_create_host, host_create_order, expected_host):
In general, I think the additions to this test make sense. My main issue with it right now is... this used to validate that `insights_id` takes precedence over `subscriptions_manager_id`, but now it only tests that `provider_id` takes precedence over the other 2.

Can you change it so that it tests your current requirements, without removing the old validations?

2021-05-06 16:33 UTC, kruai commented on tests/test_unit.py
> +            "external_type": "aws",
did you mean `provider_type` here?

2021-05-06 16:33 UTC, kruai commented on tests/test_unit.py
> +
Wait why are you doing this? It looks like you're just forcing the "actual" value to match the expected value to make the test pass :/

2021-05-06 17:58 UTC, thearifismail commented on api/host_query_xjoin.py
> +        query_filters = ({"provider_id": {"eq": insights_id}},)
No both are needed but just put `provider_id` before `insights_id` in terms of importance, i.e. as listed in ELEVATED_CANONICAL_FACT_FIELDS

2021-05-06 18:17 UTC, thearifismail commented on api/host_query_xjoin.py
> +    provider_type,
Yes just adding it now.  The reason I was left out was that `provider_type` initially was not one among the parameters to query about.  Had to add it while adding tests for fetching systems based on provider_type.

2021-05-06 18:19 UTC, thearifismail commented on app/models.py
> +        reporter = data.get("reporter")
The only reason for adding is that if there is an exception/error, it could be included in the message.

2021-05-06 18:23 UTC, thearifismail commented on app/models.py
> +                f'Unknown Provider Type: "{provider_type}" from reporter: "{reporter}".  '
It is better to have reporter right with the corresponding error message.  Removing it does not make the message any cleaner than it is now.

2021-05-06 18:37 UTC, thearifismail commented on tests/test_models.py
> +def test_invalid_providers(mq_create_or_update_host, provider):
Gone!

2021-05-06 18:48 UTC, thearifismail commented on tests/test_models.py
> +from marshmallow import ValidationError as MarshmallowValidationError
Did not realize the presence of `ValidationError`.  I guess the linter put them next to each other.  Any now using MarshmallowValidationError which clearer than ValidationError.

2021-05-06 18:52 UTC, thearifismail commented on tests/test_deduplication.py
>  def test_find_host_using_elevated_ids_match(db_create_host, host_create_order, expected_host):
This was a tricky test to work with.  I wanted to test what you just said but could not make it work at the time.  It just occurred to me to leave the old test as it was and make new test out of this one.

2021-05-06 18:54 UTC, thearifismail commented on tests/test_unit.py
> +            "external_type": "aws",
No.  did not touch `external_id`.  When will remove it when `external_id` is removed altogether.

2021-05-06 18:58 UTC, thearifismail commented on tests/test_unit.py
> +
yes, to deal with the way the `serialize_host` method is written

2021-05-06 19:52 UTC, thearifismail commented on swagger/api.spec.yaml
> +      example: aws
Fixed the message.

2021-05-06 20:44 UTC, thearifismail commented on swagger/api.spec.yaml
> +          - provider_type
what do you mean by combining the two?

2021-05-06 21:21 UTC, thearifismail commented on tests/test_api_hosts_get.py
> +    random_choice = random.choice(providers_tuple)
Changed the test to create a give number of hosts of the same provider type and then verify their numbers and type

2021-05-06 21:22 UTC, thearifismail commented on tests/test_api_hosts_get.py
> +            all_hosts.append(host)
created_hosts and all_hosts to count hosts of every type and verify the total number.

2021-05-06 21:41 UTC, thearifismail commented on tests/test_api_hosts_get.py
> +            all_hosts.append(host)
changed the test and all_hosts gone

2021-05-06 21:41 UTC, thearifismail commented on tests/fixtures/mq_fixtures.py
> +def mq_create_multiple_hosts_by_provider_type(mq_create_or_update_host):
Gone!  I was on the fence to begin with.

2021-05-06 21:42 UTC, thearifismail commented on tests/fixtures/mq_fixtures.py
> +            fqdn = f"host{i}.domain.test"
the whole fixture is gone.

2021-05-06 21:42 UTC, thearifismail commented on tests/fixtures/mq_fixtures.py
> +            i += 1
Gone!

2021-05-06 21:43 UTC, thearifismail commented on tests/test_api_hosts_get.py
> +    assert len(response_data["results"]) == 20
This was to verify the total number of hosts, but gone altogether

2021-05-06 21:46 UTC, thearifismail commented on tests/test_models.py
> +    canonical_facts = {"provider_id": provider.get("id"), "provider_type": provider.get("type"), "reporter": "test"}
hmmm, must have been left from copy paste.  Gone!

2021-05-06 22:32 UTC, thearifismail commented on tests/test_deduplication.py
>  def test_find_host_using_elevated_ids_match(db_create_host, host_create_order, expected_host):
renamed the origin test to communicate the intent and created a new one to test provider_id has preference over others

2021-05-07 16:07 UTC, kruai requested changes

2021-05-07 16:11 UTC, kruai commented on api/host_query_xjoin.py
> +        query_filters = ({"provider_id": {"eq": provider_type}},)
Noticed this after my review, but I'm pretty sure the filter name should be `provider_type`
```suggestion
        query_filters = ({"provider_type": {"eq": provider_type}},)
```

2021-05-07 16:13 UTC, kruai commented on api/host_query_xjoin.py
> +        query_filters = ({"provider_id": {"eq": insights_id}},)
Not sure what you meant by this comment, but it looks like you fixed this line (although now the `provider_type` line is wrong)

2021-05-07 19:21 UTC, thearifismail commented on api/host_query_xjoin.py
> +        query_filters = ({"provider_id": {"eq": provider_type}},)
fixed.

2021-05-07 19:58 UTC, thearifismail commented on app/models.py
> +        reporter = data.get("reporter")
Done. reporter Gone!

2021-05-07 19:58 UTC, thearifismail commented on app/models.py
> +                f'Unknown Provider Type: "{provider_type}" from reporter: "{reporter}".  '
Done!

2021-05-07 19:59 UTC, thearifismail commented on docs/_index.md
> +
Sorry.  Done this time.

2021-05-07 20:13 UTC, thearifismail commented on swagger/api.spec.yaml
> +          - provider_type
Ahhh got it.

2021-05-07 20:14 UTC, thearifismail commented on tests/test_unit.py
> +            "external_type": "aws",
Fixed.

2021-05-07 20:14 UTC, thearifismail commented on tests/test_unit.py
> +
Wow.  What a twisted state of mind I was in both time.  Fixed irt.

2021-05-10 15:09 UTC, kruai submitted a review, later dismissed
One note, but LGTM

2021-05-10 16:17 UTC, thearifismail commented on tests/test_deduplication.py
> +def test_provider_id_preference_over_other_elevated_facts(db_create_host, host_create_order, expected_host):
Thanks Me too.

2021-05-12 19:23 UTC, kruai approved these changes
LGTM

2021-05-12 19:32 UTC, ryandillinfelton commented on app/models.py
> +                f'Valid provider types are: {", ".join([p.value for p in ProviderType])}.'
I still think this is unnecessary since it'll only be seen in logs, not real time. But I don't think it's worth blocking on alone.

2021-05-12 19:52 UTC, thearifismail commented on app/models.py
> +                f'Valid provider types are: {", ".join([p.value for p in ProviderType])}.'
the intent is that whoever upstream handles this exception will log the message with the reporter

2021-05-12 20:05 UTC, ryandillinfelton requested changes
Requesting some test changes

2021-05-12 20:05 UTC, ryandillinfelton commented on tests/test_models.py
> +def test_invalid_providers(provider):
I don't think this ever tests the case where either field is missing entirely.

2021-05-12 22:25 UTC, thearifismail commented on tests/test_models.py
> +def test_invalid_providers(provider):
`provider_type` and `provider_id` missing altogether creates a valid host

2021-05-12 22:26 UTC, thearifismail commented on tests/test_xjoin.py
>                  "ip_addresses": None,
created `test_query_variables_provider_id` and `test_query_variables_provider_type`

2021-05-12 22:31 UTC, thearifismail commented on tests/test_api_hosts_get.py
> +def test_query_using_provider_type(mq_create_or_update_host, api_get, provider):
I had a test where all providers with differing counts were within the test.  The test kept count of total number hosts as wells specific type.  The test worked, but it was too complicated.  In response to Asa's comment, I deleted the test and simplified it to this parametrized one.

2021-05-12 22:53 UTC, ryandillinfelton requested changes

2021-05-12 22:53 UTC, ryandillinfelton commented on tests/test_xjoin.py
> +    url = build_hosts_url(query=f"?provider_type={quote(provider_type)}")
If you're not using a set of values for provider_type why not just hardcode the whole query string?

2021-05-12 22:53 UTC, ryandillinfelton commented on tests/test_models.py
> +def test_invalid_providers(provider):
I mean the way the test is set up it never tests how it handles one of the key missing.

2021-05-12 22:54 UTC, ryandillinfelton commented
@thearifismail have the changes to support the filters been made to xjoin-search?

2021-05-12 23:21 UTC, thearifismail commented on tests/test_models.py
> +def test_invalid_providers(provider):
Added  separate tests for missing provider_id and provider_type.

2021-05-13 13:08 UTC, ryandillinfelton commented on tests/test_models.py
> +def test_invalid_providers(provider):
Nice! looks good now. Is this the one you're refactoring?

2021-05-13 14:14 UTC, kruai requested changes

2021-05-13 14:14 UTC, kruai commented on tests/test_xjoin.py
> +def test_query_variables_provider_type(mocker, query_source_xjoin, graphql_query_empty_response, api_get):
`query_source_xjoin` isn't used in this test

2021-05-13 14:14 UTC, kruai commented on tests/test_xjoin.py
> +    url = build_hosts_url(query=f"?provider_type={quote(provider_type)}")
I agree with this ^

2021-05-13 14:14 UTC, kruai commented on tests/test_xjoin.py
> +def test_query_variables_provider_id(mocker, query_source_xjoin, graphql_query_empty_response, api_get):
`query_source_xjoin` is not used in this test

2021-05-13 14:14 UTC, kruai commented on tests/test_xjoin.py
> +    provider_type = "provider_type"
Since provider_type is an enum, why not set this to one of the valid values (like aws or azure)? Seems odd to query for all hosts where the provder_type is set to the string "provider_type", since that's not a valid value.

2021-05-13 14:22 UTC, thearifismail commented on tests/test_models.py
> +def test_invalid_providers(provider):
Yes.  combined the two new tests into one by parameterizing provider keys.

2021-05-13 14:44 UTC, thearifismail commented on tests/test_xjoin.py
> +    provider_type = "provider_type"
fixed.  now uses valid provider types.

2021-05-13 14:45 UTC, thearifismail commented on tests/test_xjoin.py
> +    url = build_hosts_url(query=f"?provider_type={quote(provider_type)}")
Fixed using @asa's comment above.

2021-05-13 14:59 UTC, thearifismail commented on tests/test_xjoin.py
> +def test_query_variables_provider_id(mocker, query_source_xjoin, graphql_query_empty_response, api_get):
`query_source_xjoin` is a fixture and doesn't need an explicit call.

2021-05-13 14:59 UTC, thearifismail commented on tests/test_xjoin.py
> +def test_query_variables_provider_type(mocker, query_source_xjoin, graphql_query_empty_response, api_get):
`query_source_xjoin` is a fixture and doesn't need an explicit call.

2021-05-13 15:43 UTC, ryandillinfelton commented on deployment.yaml
> +          value: http://${XJOIN_SEARCH_HOST}:{XJOIN_SEARCH_PORT}/graphql
I think that merging with master should sort this out, but this has a typo. I think it's the same one that Asa just added a fix for though. Not sure why it shows up in the changes here.

2021-05-13 15:58 UTC, thearifismail commented on deployment.yaml
> +          value: http://${XJOIN_SEARCH_HOST}:{XJOIN_SEARCH_PORT}/graphql
Just resolved the conflict.

2021-05-13 16:03 UTC, ryandillinfelton requested changes
Should be the last change requests, sorry there have been so many. I didn't notice this the last time I was reviewing, but it looks like the parameter values aren't validated. I've left some suggestions on how to fix that and some tests to add.

To summarize:

- [ ] add validation to query parameters in the api spec
- [ ] add invalid value tests to `test_api_hosts_get`
- [ ] add invalid value tests to `test_xjoin`
- [ ] remove a stray commented out variable in `test_xjoin`

2021-05-13 16:03 UTC, ryandillinfelton commented on tests/test_xjoin.py
> +    # provider_type = "aws"
Commented out code should be removed

2021-05-13 17:11 UTC, thearifismail commented on swagger/api.spec.yaml
> +            type: string
No validation is needed for `provider_id` other than is a string with max_length 500.  It does not have to be a UUID.  UUID has been used in tests for ease-of-use and looks clean.

2021-05-13 17:16 UTC, thearifismail commented on tests/test_xjoin.py
> +    # provider_type = "aws"
Gone!

2021-05-13 17:32 UTC, kruai commented on swagger/api.spec.yaml
> +            type: string
@thearifismail is right; we can't validate `provider_id`'s structure, because it's different for each provider.

2021-05-13 17:50 UTC, thearifismail commented
> * [x]  add validation to query parameters in the api spec
Accepted the `enum` suggestion for `provider_type`.  There is no format requirement for `provider_id`
> * [x]  add invalid value tests to `test_api_hosts_get`
Since changed are made to the model, `test_models.py` has `def test_invalid_providers(canonical_facts):` 
> * [x]  add invalid value tests to `test_xjoin`
Added `def test_query_using_invalid_provider_type` to `test_xjoin.py`
> * [x]  remove a stray commented out variable in `test_xjoin`
Stray comment Gone!

2021-05-13 18:24 UTC, ryandillinfelton commented on swagger/api.spec.yaml
> +            type: string
Gotcha :+1:

2021-05-13 18:39 UTC, ryandillinfelton approved these changes
Looking good now :+1:. 

I just want to check that xjoin-search supports the filters you're using. We can merge regardless, the filtering won't work if someone tries to use it but it shouldn't break anything. I'd just like to know the status.

2021-05-13 18:41 UTC, thearifismail commented
@kruai  can you please take a look?  Thanks.

2021-05-13 18:42 UTC, ryandillinfelton commented on api/host_query_xjoin.py
> +    elif provider_type:
Wait, I was looking through this again. It doesn't look like you can filter by `provider_type` and `provider_id` in the same query. Is that intentional? I would expect people to commonly combine the two.

2021-05-13 18:45 UTC, ryandillinfelton requested changes
Dang I spoke to soon. Was checking to make sure merging without xjoin-search support wouldn't cause an issue and caught that the provider field filters can't be used together.

2021-05-13 18:45 UTC, ryandillinfelton commented on api/host_query_db.py
> +    elif provider_type:
Same issue here where the provider field filters are mutually exclusive

2021-05-13 18:45 UTC, ryandillinfelton commented on tests/test_xjoin.py
> +def test_query_variables_provider_type(
We need coverage of the two filters being used together. It would have caught the fact that it's not possible. I think combining the `provider_type` and `provider_id` valid input tests together might make sense, but I'll leave that up to you.

2021-05-13 20:24 UTC, thearifismail commented on tests/test_xjoin.py
> +def test_query_variables_provider_type(
Done!!!

2021-05-13 20:32 UTC, thearifismail commented on api/host_query_db.py
> +    elif provider_type:
Fixed!!!

2021-05-14 14:40 UTC, ryandillinfelton commented on api/host_query_db.py
> +    provider_id,
These are needed to keep the interface consistent between db & xjoin.

2021-05-14 18:14 UTC, ryandillinfelton commented
So I've tested locally that this is generating the correct xjoin-search query. The PR for the xjoin-search branch I'm using for testing is [here](https://github.com/RedHatInsights/xjoin-search/pull/101). This PR if merged in will work fine, and will not break any existing functionality, however it will not work until the xjoin-search PR above is approved and released. I suspect it'll be fairly quick since it's rather boilerplate but I think it's good to be aware of that.

2021-05-14 18:16 UTC, ryandillinfelton approved these changes
LGTMing this to get rid of my request for changes. I've contributed to this, but mainly in just removing the database query side of things. Still, I'd like to get two other approvals before we merge.

2021-05-14 18:52 UTC, kruai approved these changes
One comment, but LGTM.

2021-05-14 18:52 UTC, kruai commented on tests/test_xjoin.py
> +def test_query_using_invalid_provider_type(
Do we benefit from having this test in addition to `test_invalid_providers`? I would think it's a bit redundant, but if this is just to hammer in that we return a 400, I get it

2021-05-14 19:11 UTC, tahmidefaz commented on app/models.py
> +            raise MarshmallowValidationError("provider_type and provider_id are both required.")
This logic can be simplified as:
```
if provider_type and provider_id:
    ... ...
    ... ...
```
right?

2021-05-14 19:28 UTC, ryandillinfelton commented on tests/test_xjoin.py
> +def test_query_using_invalid_provider_type(
The test in test_models only verifies that we validate host data correctly on host creation. This test insures that the API correctly validates the value of the parameter. In effect it is just testing that the api spec is being enforced correctly.

2021-05-14 19:31 UTC, kruai commented on app/models.py
> +            raise MarshmallowValidationError("provider_type and provider_id are both required.")
Yep, classic logic refactor. Good call!

2021-05-14 19:36 UTC, ryandillinfelton commented on app/models.py
> +            raise MarshmallowValidationError("provider_type and provider_id are both required.")
A NAND would fire when both `provider_type` and `provider_id` are present. We want the check to function as an XOR. If they were booleans a simple != would do the trick, but here it would do the wrong comparison.
we could maybe do
```suggestion
        if (provider_type is None) != (provider_id is None):
            raise MarshmallowValidationError("provider_type and provider_id are both required.")
```
I think that might be less readable though

2021-05-14 19:47 UTC, tahmidefaz commented on app/models.py
> +            raise MarshmallowValidationError("provider_type and provider_id are both required.")
Actually, with how the code is currently, if `provider_type = None` and `provider_id = None`, it won't raise a `MarshmallowValidationError` either. That should be a bug, right? :bug:

2021-05-14 19:51 UTC, kruai commented on app/models.py
> +            raise MarshmallowValidationError("provider_type and provider_id are both required.")
Nope, I was mistaken earlier @tahmidefaz; it's valid if both are provided, or if neither are provided. We effectively need like an xor existence check on this thing

2021-05-14 20:16 UTC, tahmidefaz commented on app/models.py
> +            raise MarshmallowValidationError("provider_type and provider_id are both required.")
Since it's an XOR comparison, I think the current code readability here is good enough. :+1:

2021-05-14 20:22 UTC, tahmidefaz approved these changes
Looks solid :+1:

2021-05-14 20:52 UTC, merged