Adding kafka consumer ssl configs
RedHatInsights/insights-host-inventory pull request #888
Opened 2021-04-27 17:32 UTC by tahmidefaz

## Overview

This PR is part of the work needeed for [this Jira](https://issues.redhat.com/browse/RHCLOUD-10353).
This is a similar PR to that of RedHatInsights/insights-advisor-service#293
The Kafka Consumer API doc can be found [here](https://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html).

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [x] Links to related PRs

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [x] Input Validation
- [x] General Coding Practices

2021-04-27 20:00 UTC, kruai requested changes

2021-04-27 20:00 UTC, kruai commented on app/config.py
> +
I think it would be better if these values were always set, instead of them only existing if `KAFKA_SSL_ENABLED == true`. If SSL shouldn't be enabled, you should just be able to set "security_protocol" to "PLAINTEXT" and "ssl_cafile" to None.

2021-04-27 20:00 UTC, kruai commented on app/config.py
> +
I'm also not sure we need both an env var to specify that SSL is enabled, and an additional env var to specify "SSL". I think it would be better to just use `KAFKA_SECURITY_PROTOCOL` and `KAFKA_SSL_CAFILE`

2021-04-27 20:00 UTC, kruai commented on app/config.py
> +            **self.kafka_consumer_ssl,
... And the values would be set here, instead of doing a var expansion:

```suggestion
            "security_protocol": os.environ.get("KAFKA_SECURITY_PROTOCOL", "PLAINTEXT"),
            "ssl_cafile": os.environ.get("KAFKA_SSL_CAFILE"),
```

2021-04-27 20:42 UTC, tahmidefaz commented on app/config.py
> +
Great suggestion, it simplifies this PR even more. Thanks!

2021-04-27 20:45 UTC, kruai approved these changes
LGTM!

2021-04-28 13:59 UTC, thearifismail approved these changes
LGTM

2021-04-28 14:10 UTC, merged