Documenting HBI identity logic
RedHatInsights/insights-host-inventory pull request #900
Opened 2021-05-07 20:04 UTC by tahmidefaz

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-13433).
This PR documents the identity logic used within HBI.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [x] Documentation, if this PR changes the way other services interact with host inventory

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [x] General Coding Practices

2021-05-10 14:53 UTC, kruai requested changes

2021-05-10 14:53 UTC, kruai commented on docs/_index.md
> +To create, update and access host data, the identity header must comply with the following logic.
```suggestion
To create, update and access host data, the provided identity must comply with the following logic:
```
I'm only removing "header" because the Identity can be provided via header or platform_metadata

2021-05-10 14:53 UTC, kruai commented on docs/_index.md
> +If the identity is of type `User`, there is not any additional requirements. However, ff the identity type is `System`, the `system` object should be present in identity and the following identity lo
```suggestion
If the identity is of type `User`, there are no additional requirements. However, if the identity type is `System`, the `system` object should be present in identity and the following logic will be used to validate:
```

2021-05-10 14:53 UTC, kruai commented on docs/_index.md
> +Host update messages received over `platform.inventory.system-profile` topic does not need to provide an identity header.
```suggestion
Host update messages received over `platform.inventory.system-profile` topic do not need to provide an identity.
```

2021-05-10 14:53 UTC, kruai commented on docs/_index.md
> +The following must be true for host add or update messages received over `platform.inventory.events`.
```suggestion
The following must be true for `add_host` messages received over `platform.inventory.host-ingress` and `platform.inventory.host-ingress-p1`.
```

2021-05-10 14:53 UTC, kruai commented on docs/_index.md
> +- they must contain `platform_metadata` and the `identity` field must be encoded within the `platform_metadata`, except when the reporter is `rhsm-conduit`
```suggestion
- they must contain `platform_metadata` and the `b64_identity` field must be encoded within the `platform_metadata`, except when the reporter is `rhsm-conduit`
```

2021-05-10 14:53 UTC, kruai commented on docs/_index.md
> +- providing identity is optional when the reporter is `rhsm-conduit`
I think this one might be redundant after the previous bullet point

2021-05-10 14:53 UTC, kruai commented on docs/_index.md
> +- the `owner_id` of the host must match the value in `system.cn` of the identity.
I just wanna clarify that this requirement is only for updating existing hosts; if no match is found, a new host is created

2021-05-10 14:53 UTC, kruai commented on docs/_index.md
> +If the reporter is `rhsm-conduit`, and an identity is not provided, adding or updating hosts over the `platform.inventory.events` will follow the logic below.
```suggestion
If the reporter is `rhsm-conduit` and an identity is not provided, adding or updating hosts over `platform.inventory.host-ingress` and `platform.inventory.host-ingress-p1` will follow this logic:
```

2021-05-10 14:53 UTC, kruai commented on docs/_index.md
> +- a `subscription_manager_id` must be present
```suggestion
- `subscription_manager_id` must be present
```

2021-05-10 14:53 UTC, kruai commented on docs/_index.md
> +- `subscription_manager_id` of the hosts gets set as its `owner_id`
```suggestion
- the host's `owner_id` gets set to its `subscription_manager_id`
```

2021-05-10 14:53 UTC, kruai commented on docs/_index.md
> +- if `owner_id` of a host does not equate its `subscription_manager_id`, it gets overwritten to the value of `subscription_manager_id`
I think this one is redundant, since its `owner_id` gets set to its `subscription_manager_id` regardless

2021-05-10 21:13 UTC, tahmidefaz commented on docs/_index.md
> +- the `owner_id` of the host must match the value in `system.cn` of the identity.
just added a clause to this point :+1:

2021-05-10 21:15 UTC, tahmidefaz commented
@kruai thanks for the suggestions. Just updated :+1:

2021-05-10 21:54 UTC, thearifismail commented on docs/_index.md
>      - `basic_auth`, `cert-auth`, `classic-auth`, `jwt-auth` or `uhc-auth`
`classic-auth` should be `classic-proxy`, https://github.com/RedHatInsights/insights-host-inventory/blob/f33d27d9e3fc3d5426fbc56f9f2c9b281c9b4aab/app/auth/identity.py#L30

2021-05-10 21:57 UTC, thearifismail commented on docs/_index.md
>  - the value provided in `cn` must be equal to the `owner_id` of the host being added or updated
the `owner_id` in the host.system_profile being added or update.

2021-05-10 22:02 UTC, thearifismail reviewed
Except for minor comments, LGTM

2021-05-10 22:02 UTC, thearifismail submitted a review, later dismissed

2021-05-11 15:12 UTC, thearifismail commented on docs/_index.md
> +If the identity is of type `User`, there are no additional requirements. However, if the identity type is `System`, the `system` object should be present in identity and the following logic will be u
Needs update to describe when `identity.type == "System"` and `identity.auth_type == "classic-proxy"`.   See https://github.com/RedHatInsights/insights-host-inventory/pull/902

2021-05-11 15:13 UTC, thearifismail reviewed
Needs update to describe when identity.type == "System" and identity.auth_type == "classic-proxy". See #902

2021-05-11 16:02 UTC, tahmidefaz commented on docs/_index.md
> +If the identity is of type `User`, there are no additional requirements. However, if the identity type is `System`, the `system` object should be present in identity and the following logic will be u
@thearifismail I think you meant auth type is `classic-proxy`, there are no additional requirements.

2021-05-11 17:29 UTC, thearifismail approved these changes
LGTM

2021-05-11 17:29 UTC, merged