[WIP] generic filtering
RedHatInsights/insights-host-inventory pull request #909
Opened 2021-05-14 19:55 UTC by ryandillinfelton

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-xxxxx).
(A description of your PR's changes, along with why/context to the PR, goes here.)

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-06-02 14:37 UTC, ryandillinfelton commented
Okay, so the test failure if from an issue with a grafana dashboard that is unchanged in this PR. I think @kruai is working on that fix, but just for the sake of clarity, all test tests and linting pass for this PR.

2021-06-02 14:58 UTC, kruai commented
FYI: The failure in pr-head is caused by an issue with the Grafana dashboard. PR #918 fixes this.

2021-06-04 15:58 UTC, tahmidefaz requested changes
@ryandillinfelton We should improve the usability around having a `system_profile_block_list.yaml`. Right now, if the file does not exist or if the file is empty, it throws errors.

2021-06-04 16:40 UTC, ryandillinfelton commented
Whoops I must not have added it to the commit > @ryandillinfelton We should improve the usability around having a `system_profile_block_list.yaml`. Right now, if the file does not exist or if the file is empty, it throws errors.

2021-06-04 18:51 UTC, kruai requested changes
I like the structure you've implemented! There are a few things that could be refactored, and some errors that could be a bit more descriptive, but in general things are looking good

2021-06-04 18:51 UTC, kruai commented on api/filtering/filtering.py
> +        raise ValidationException("invalid field value")
I had originally left a comment on each ValidationException, but that would have been overwhelming and redundant. Basically, I don't think these exceptions provide enough information. Instead of:
`ValidationException("invalid field value")`
I'd much prefer to see something like:
`ValidationException(f"{field_value} is an invalid value for the {field_type} field {field_name}")`

I'd love more details in the other similar exceptions that are thrown, like `invalid filter field`, `wrong type for filter`, `filter key is invalid`, etc. We should help the user out as much as we can if we fail their request

2021-06-04 18:51 UTC, kruai commented on api/system_profile.py
> +            raise ValidationException("filter key is invalid")
This block is exactly the same as L119-123; can we refactor this, or is that overkill?
I realize that there are other commonalities between the functions, but since you didn't change anything beyond the filters, those can wait.

2021-06-04 18:51 UTC, kruai commented on api/tag.py
> +            hostfilter_and_variables += build_system_profile_filter(filter["system_profile"])
Same thing here

2021-06-04 18:51 UTC, kruai commented on tests/test_api_hosts_get.py
>  # DISABLED. Query validation will be added back in a future PR
Since it's no longer disabled, this should be removed

2021-06-04 18:51 UTC, kruai commented on tests/test_xjoin.py
> +        # build_system_profile_sap_sids_url
Why do each of these have their final line commented out? If there's no particular reason, let's remove them

2021-06-04 18:51 UTC, kruai commented on tests/test_xjoin.py
> +        # build_system_profile_sap_sids_url
same Q here

2021-06-04 18:51 UTC, kruai commented on tests/test_xjoin.py
> +        "[gte]=bar",
Is this test's purpose to check invalid values, invalid operations, or both? If it's just for values, I think the invalid operations are redundant here

2021-06-04 19:03 UTC, ryandillinfelton commented on tests/test_xjoin.py
> +        "[gte]=bar",
Both. Since both are dependent on the type of the field I though it'd make sense to roll them up together

2021-06-04 19:08 UTC, ryandillinfelton commented on tests/test_xjoin.py
> +        # build_system_profile_sap_sids_url
Removed. It was related to getting one test working on all endpoints at once. Should have just removed the lines once I gave up on making that part of this PR.

2021-06-04 19:10 UTC, kruai commented on tests/test_xjoin.py
> +        "[gte]=bar",
Ah, I forgot that the allowed operations are also dependent on the field type. No issue here, then

2021-06-04 19:17 UTC, ryandillinfelton commented on api/system_profile.py
> +            raise ValidationException("filter key is invalid")
I think factoring this out to a function would lead to a weird kind of pattern. I think I'd rather refactor the system_profile stuff more broadly at the next opportunity though.

2021-06-04 19:18 UTC, ryandillinfelton commented on api/tag.py
> +            hostfilter_and_variables += build_system_profile_filter(filter["system_profile"])
I do need to add the proper check here

2021-06-06 22:47 UTC, tahmidefaz requested changes

2021-06-07 12:15 UTC, ryandillinfelton commented on app/__init__.py
> +            return "wildcard"
Adding fields to the schema technically doesn't break spec with JSONschema but it could cause compatibility issues down the line. There is no requirement on how tools should handle custom fields, so it's possible that tooling could the field out entirely. So I'm partial to re-purposing  some of the annotation fields like description. My hope also is that having it work this way will encourage better documentation, since users will want to know if wildcards are supported on a field.

2021-06-07 12:16 UTC, ryandillinfelton commented on app/__init__.py
> +        print(f"block list fields: {system_profile_blocklist}")
Yes, I'll swap it to an info level log

2021-06-07 14:29 UTC, kruai commented on app/__init__.py
> +            return "wildcard"
I must have missed this in my review! It feels sketchy and kinda dangerous doing things this way; IMO changing something's description should not affect the functionality of the app

2021-06-07 16:40 UTC, ryandillinfelton commented on app/__init__.py
> +            return "wildcard"
I'll explore using a custom field. Since we're parsing it ourselves in this instance it might not make any difference. My plan as is was just to create robust documentation and a checklist for all inventory-schema PRs to insure that people have considered this.

2021-06-07 17:48 UTC, ryandillinfelton commented on app/__init__.py
> +            return "wildcard"
If we end up able to use custom fields in the JSONschema. Would y'all prefer we use a marker like `indexed: false` instead of the current block list?

2021-06-07 17:59 UTC, tahmidefaz commented on app/__init__.py
> +            return "wildcard"
@ryandillinfelton I think we should be able to use custom fields in our JSONschema. We already have one (`x-propertyNames`). I don't have any preferences as to the use of a marker.

2021-06-08 12:48 UTC, ryandillinfelton commented on app/__init__.py
> +            return "wildcard"
I swapped both over to using custom tags in JSONschema.
So to mark a field as supporting wildcard you just add:
`x-wildcard: true`
and to block a field from being indexed you add:
x-indexed: false`
I have it default to assuming fields are indexed and don't support wildcards.

Do these seem like good and intuitive names, and more readable than the description approach?

2021-06-08 16:23 UTC, kruai commented on api/system_profile.py
> +            raise ValidationException("filter key is invalid")
Yes, that's fine!

2021-06-08 18:30 UTC, ryandillinfelton commented on api/filtering/filtering.py
> +        raise ValidationException("invalid field value")
I think I've addressed this. LMK if you see any more places it can be improved.

2021-06-08 19:35 UTC, kruai commented on app/__init__.py
> +            return "wildcard"
I'm cool with those names, at least :)

2021-06-08 19:35 UTC, kruai commented on api/filtering/filtering.py
> +        raise ValidationException("invalid field value")
Looks good!

2021-06-10 19:08 UTC, kruai approved these changes
I think this looks good now!

2021-06-10 20:22 UTC, ryandillinfelton commented
> Looks good!  
> You also need to open a PR in `inventory-schemas` so that both versions of the system_profile schema are the same.

opened a PR on inventory schemas. Also includes some documentation on the steps to add a new field
https://github.com/RedHatInsights/inventory-schemas/pull/70

2021-06-11 15:14 UTC, merged