RHCLOUD-12800: subtask - add inventory schemas as submodule
RedHatInsights/insights-host-inventory pull request #911
Opened 2021-05-19 09:43 UTC by RonnyPfannschmidt

uses a submodule to link the repo,
adds a makefile command to do the updates updating the  repo link and the local file
normally a submodule checkout is not needed

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-xxxxx).
(A description of your PR's changes, along with why/context to the PR, goes here.)

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-06-04 19:07 UTC, kruai reviewed
I'm very interested in this! If we went in this direction, would we have to manually run `update_schema`, or can we automate that as well?

2021-06-07 09:45 UTC, RonnyPfannschmidt commented
@kruai yes, this only makes the mechanics more foolproof for now

we still copy the file content so the submodules are not in general required
a followup would be a sheduled/triggered github action that updates the submodule data regular

2021-06-07 19:40 UTC, kruai requested changes

2021-06-07 19:40 UTC, kruai commented on .gitignore
> +.hypothesis/
Were these for some changes that weren't committed?

2021-06-07 19:45 UTC, RonnyPfannschmidt commented on .gitignore
> +.hypothesis/
indeed, those where accidentally added while finishing the rebases, should i move them to a different pr

2021-06-07 19:46 UTC, kruai commented on .gitignore
> +.hypothesis/
Yeah - if the related files are in the other PR, this change should be there instead

2021-06-07 19:48 UTC, RonnyPfannschmidt commented on .gitignore
> +.hypothesis/
there are no related files .hypothesis was something visual studio code adds and .idea is from pycharm

2021-06-07 20:53 UTC, kruai commented on .gitignore
> +.hypothesis/
OK. I haven't seen those files in mine, but I guess I'm not against this gitignore addition

2021-06-07 20:53 UTC, kruai submitted a review, later dismissed

2021-06-07 21:33 UTC, tahmidefaz submitted a review, later dismissed
Looks good! If we can make gh actions run `update_schema` periodically and open PRs, that'd be cool! :+1:

2021-06-07 22:16 UTC, ryandillinfelton requested changes
Sorry, a bit of a picky change request, but I'd like to keep up with best practices in this case. Everything else looks good to me though, so it should be an easy merge once this small fix is made.

2021-06-07 22:16 UTC, ryandillinfelton commented on .gitignore
> +.hypothesis/
I'm gonna disagree here. We should only have rules in the gitignore that relate directly to this specific project. IDE file extensions and such should be added to your own global gitignore rather than the gitignore of each project you contribute to.

2021-06-23 15:16 UTC, ryandillinfelton commented
I'm not convinced we need to add a submodule for this. If we want it to be automated through a github action already, and we aren't using the file from the submodule directly, why not update the file in the action itself? We could have the job checkout the schema repo and copy the latest version over.

2021-06-23 17:32 UTC, RonnyPfannschmidt commented
@ryandillinfelton however if we set the complete logic out in a action, it cant be nicely used/integrated

like for example tracking a branch of the upstream

also we loose the direct information about what commit a update was taken from

for me the key feature of the subrepo being possibly usable is that it is extremely easy, straightforward and well tested and works in all envs

2021-08-24 18:21 UTC, kruai approved these changes
LGTM! I especially think the SP commit ID is a good idea.

2021-08-24 19:34 UTC, ryandillinfelton approved these changes

2021-08-25 16:19 UTC, merged