Move initContainers to host-inventory-mq-p1 deployment
RedHatInsights/insights-host-inventory pull request #925
Opened 2021-06-09 21:54 UTC by thearifismail

## Overview

This PR is being created to address [this bug](https://issues.redhat.com/browse/RHCLOUD-14541), which is being fixed by moving `initContainers` from "host-inventory-service" to "host-inventory-inventory-mq-p1" deployment, which did not use `urllib3`, the library used for pushing logs to `cloudwatch`.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-06-09 22:32 UTC, ryandillinfelton requested changes
I haven't taken a thorough look at the whole thing yet so I can't say it's the only issue. It just stood out to me.

2021-06-09 22:32 UTC, ryandillinfelton commented on utils/payloads.py
> +        "provider_id": random_uuid(),
This looks like it might be an unintentionally committed change

2021-06-10 13:48 UTC, kruai requested changes
I'm fine with trying this out, but I'm pretty sure the only change you need is the one in `deployment.yaml`

2021-06-10 13:48 UTC, kruai commented on utils/kafka_producer.py
> +NUM_HOSTS = int(os.environ.get("NUM_HOSTS", 100))
This isn't related to the PR's purpose

2021-06-10 13:48 UTC, kruai commented on utils/payloads.py
> +        "provider_id": random_uuid(),
This isn't related to the PR's purpose

2021-06-10 16:14 UTC, thearifismail commented
Changes to `test_producder.py` and `payloads.py` reflect how the very last host(s) were created.  Changes to these files do not affect the PR.

2021-06-10 17:24 UTC, kruai commented on utils/kafka_producer.py
> +NUM_HOSTS = int(os.environ.get("NUM_HOSTS", 100))
As far as I can tell, the port is now incorrect. And were these changes just for your local manual testing?
If so, I really don't think these should be included in the PR

2021-06-10 17:27 UTC, kruai commented on utils/payloads.py
> +        "provider_id": random_uuid(),
What do you mean by it forcing updates? It's not clear to me how the changes to this file and `kafka_producer.py` are relevant to this PR's purpose... they look like they were changed for your manual local testing, and shouldn't be committed IMO

2021-06-10 17:38 UTC, kruai approved these changes
LGTM!

2021-06-10 17:39 UTC, ryandillinfelton approved these changes

2021-06-10 17:47 UTC, merged