Inventory Pendo Syncher [ESSNTL-613]
RedHatInsights/insights-host-inventory pull request #951
Opened 2021-07-09 13:29 UTC by tahmidefaz

# Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/ESSNTL-613).

This PR implements the Pendo Syncher cron job to sync hosts per account data with pendo.

On a high level, this does the following two things:

- Runs a query on the HBI DB that is equivalent to the SQL: 
  - `SELECT account, count(id) from hosts GROUP BY account ORDER BY account;`
- Sends a POST request to Pendo with the request body formatted by the following syntax:
```
[{
  "accountId: "hbi-account-1",
  "values": {
    "hostCount": count
  }
},
{
  "accountId: "hbi-account-2",
  "values": {
    "hostCount": count
  }
}...]
```

The `hostCount` is a custom Pendo account metadata what we added using an admin account.

To successfully send a request to Pendo, the following environment variables with the correct values must be present:

- `PENDO_SYNC_ACTIVE`
- `PENDO_INTEGRATION_KEY`

Information on the endpoint used and other functionalities of the Pendo API can be [found here](https://developers.pendo.io/docs/?python#set-value-for-a-set-of-agent-or-custom-fields).

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [x] Links to helpful references

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [x] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

2021-07-12 13:56 UTC, ryandillinfelton commented on lib/pendo_sync_helpers.py
> +    )
This spot could use a little layout touch up. Everything works fine, just a little cramped visually

2021-07-12 14:16 UTC, ryandillinfelton commented on lib/pendo_sync_helpers.py
> +        account_list = query.filter(Host.account > account_list[-1].account).limit(limit).all()
This note is also kind of to myself when I re-review. This looks like it'd work but I'm not sure it seems like kind of a strange way to do it. I need to dust off my SQL alchemy and take a closer look.

2021-07-12 14:20 UTC, tahmidefaz commented on lib/pendo_sync_helpers.py
> +        account_list = query.filter(Host.account > account_list[-1].account).limit(limit).all()
@ryandillinfelton this part is somewhat similar to what's being used in `host_synchronizer`. But if you can think of a better/simpler way to do this, let me know for sure and I will change it :+1:

2021-07-12 14:46 UTC, ryandillinfelton commented on pendo_syncher.py
> +def _init_db(config):
Not sure I understand what the distinction is between functions that are put in the helpers file, vs functions put in this file. I understand why main and run are in here, it just looks like a few more could be factored into helpers if you're going to divide it anyways.

2021-07-12 14:57 UTC, tahmidefaz commented on pendo_syncher.py
> +def _init_db(config):
@ryandillinfelton right now, the main file initializing everything for the scripts, such as db, metrics etc. The functions in the `pendo_sync_helpers` currently does the actual work of querying, making the request etc. Does this clear it up a little? Maybe we shouldn't call it `pendo_sync_helpers`... :thinking:

2021-07-13 16:57 UTC, tahmidefaz commented on lib/pendo_sync_helpers.py
> +    )
@ryandillinfelton updated this to only label and show three number, e.g. `total`, `updated`, `failed`. Lmk, if this works for you!

2021-07-13 18:19 UTC, ryandillinfelton commented on pendo_syncher.py
> +def _init_db(config):
I would almost expect it to be the opposite. I'm a little partial to just combining stuff, especially since the helper functions are only going to be used in this one script for the foreseeable future. I don't think it would be too long either. I'm open to other ideas though if you find that disagreeable.

2021-07-13 18:21 UTC, ryandillinfelton commented on lib/pendo_sync_helpers.py
> +    )
I should've been more specific that I literally just wanted a newline in there to uncramp things. It's all looking good now though.

2021-07-13 20:10 UTC, tahmidefaz commented on pendo_syncher.py
> +def _init_db(config):
@ryandillinfelton sure thing! They should all be in the same file now

2021-07-13 20:25 UTC, ryandillinfelton requested changes
Requesting changes because I'd like the tests to be a little more intentional. Otherwise everything looks good to me outside of a few nitpicks.

2021-07-13 20:25 UTC, ryandillinfelton commented on tests/test_pendo_syncher.py
> +    mock_response.status_code = 200
This seems redundant since it's already set in the initialization

2021-07-13 20:25 UTC, ryandillinfelton commented on tests/test_pendo_syncher.py
> +    request_body = [{"accountId": host.account, "values": {"hostCount": 1}}]
Being picky, but I think this could be one line without sacrificing readability. I won't request changes for this alone though.

2021-07-13 20:25 UTC, ryandillinfelton commented on tests/test_pendo_syncher.py
> +    mock_pendo_failure.assert_called_once()
I'd like to see this check the error message that pendo_failure is passed to make sure that the failure is cause by the expected issue.

2021-07-13 21:03 UTC, tahmidefaz commented on tests/test_pendo_syncher.py
> +    mock_pendo_failure.assert_called_once()
@ryandillinfelton it was a little tricky, but I changes this to check for the failure message as cleanly as possible.

2021-07-13 21:09 UTC, kruai requested changes
I just have one note so far. There's also a lot of redundancy in the tests, and it would be great if we could refactor them, but I wouldn't want to hold it up on that.

2021-07-13 21:09 UTC, kruai commented on pendo_syncher.py
> +    if config.pendo_sync_active:
Shouldn't this be higher up? As it stands, this code will always do the processing even if the sync isn't active, but stop just short of actually sending the data. It might make sense for this logic to be in `main()`, `run()`, or `pendo_sync()`, unless I'm misunderstanding the variable's purpose.

2021-07-13 21:31 UTC, tahmidefaz commented on pendo_syncher.py
> +    if config.pendo_sync_active:
@kruai I actually added this variable to do just that - stop just short of actually sending the data to pendo. I was thinking that initially we will initialize this cron job with `pendo_sync_active=False` and verify all the pre-processing is working great in the pods and then finally set it to `True`. I want to avoid sending bulk of invalid data to pendo at all cost, because doing so might make it very difficult for us to revert those changes. Lmk, what you think about it!

2021-07-14 13:44 UTC, kruai commented on pendo_syncher.py
> +    if config.pendo_sync_active:
OK, I can understand that. I thought the purpose was similar to the `REAPER_SUSPEND` variable or whatever it was called. But yes, it makes sense to verify that everything's working first.

2021-07-14 14:00 UTC, kruai approved these changes
LGTM

2021-07-14 15:38 UTC, ryandillinfelton commented on tests/test_pendo_syncher.py
> +    mock_pendo_failure.assert_called_once()
I was hoping you could do it for all of the failure cases

2021-07-14 15:50 UTC, tahmidefaz commented on tests/test_pendo_syncher.py
> +    mock_pendo_failure.assert_called_once()
Ah, you meant all of them!

2021-07-14 15:57 UTC, tahmidefaz commented on tests/test_pendo_syncher.py
> +    mock_pendo_failure.assert_called_once()
@ryandillinfelton the other exception messages are different then this `403`, since a generic exception message won't be provided unlike the case we had here. Anyways, I added a exception string check for one additional test. The test for the `RetryFailure` doesn't provide an exception message by default, so, I refrained from adding a similar check for that one.

2021-07-14 17:31 UTC, ryandillinfelton approved these changes
LGTM!

2021-07-14 17:51 UTC, kruai approved these changes
Still LGTM!

2021-07-14 18:55 UTC, merged