Improve canonical facts MAC address validation
RedHatInsights/insights-host-inventory pull request #952
Opened 2021-07-12 19:43 UTC by ryandillinfelton

# Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/ESSNTL-549).

Pretty simple one. We aren't validating these MAC addresses very well, we just check that they are a reasonable length. This PR adds validation allowing all valid MAC address formats, including those weird long ones that we get occasionally.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-07-12 20:48 UTC, kruai requested changes
The actual implementation looks good to me, though I had a few notes on the tests

2021-07-12 20:48 UTC, kruai commented on tests/test_mq_service.py
> +    Tests that owner_id in the system profile is rejected if it's in the wrong format
Copy/paste casualty

2021-07-12 20:48 UTC, kruai commented on tests/test_mq_service.py
> +def test_add_host_with_canonical_facts_MAC_address_incorrect_format(event_datetime_mock, mq_create_or_update_host):
`event_datetime_mock` isn't used

2021-07-12 20:48 UTC, kruai commented on tests/test_mq_service.py
> +        account=SYSTEM_IDENTITY["account_number"], system_profile={"owner_id": OWNER_ID}, mac_addresses=["bad"]
Are the account number and system profile needed here? They're not causing an issue, I just don't think they're required for this test

2021-07-12 20:48 UTC, kruai commented on tests/test_mq_service.py
> +    event_datetime_mock, mq_create_or_update_host, db_get_host
`event_datetime_mock` not used

2021-07-12 20:48 UTC, kruai commented on tests/test_mq_service.py
> +    Tests that owner_id in the system profile is rejected if it's in the wrong format
Another copy/paste casualty

2021-07-12 20:48 UTC, kruai commented on tests/test_mq_service.py
> +        system_profile={"owner_id": OWNER_ID},
I think these can be removed again, and it can just go with the default?

2021-07-12 20:48 UTC, kruai commented on tests/test_mq_service.py
> +    assert created_host.id == str(host_from_db.id)
Seems like this assertion is testing whether `db_get_host()` works correctly, instead of being related to the mac_address stuff

2021-07-13 02:25 UTC, thearifismail commented on tests/test_mq_service.py
> +def test_add_host_with_canonical_facts_MAC_address_incorrect_format(event_datetime_mock, mq_create_or_update_host):
`incorrect_format` should include zero length and longer than max length 59

2021-07-13 13:46 UTC, ryandillinfelton commented on tests/test_mq_service.py
> +    assert created_host.id == str(host_from_db.id)
It's more so just to check that the host is in the database at all and hasn't been rejected because of malformed MAC addresses. I think the assertion below will catch that too, but if the test fails it might be nice to know if the host isn't being created at all, or if some of the MAC addresses aren't making it to the DB.

2021-07-13 13:54 UTC, thearifismail commented on app/validators.py
> +        r"^([A-Fa-f0-9]{2}[:-]){5}[A-Fa-f0-9]{2}$|"
How did you come up with these regex? i.e. does it follow some standards for mac_addresses?

2021-07-13 13:56 UTC, ryandillinfelton commented on tests/test_mq_service.py
> +def test_add_host_with_canonical_facts_MAC_address_incorrect_format(event_datetime_mock, mq_create_or_update_host):
I've expanded the incorrect format test to include more cases. I removed the pure character limit, but I've added cases the test for mac addresses that are too long or too short. I have also removed the `event_datetime_mock` that this thread was started about.

2021-07-13 13:56 UTC, ryandillinfelton commented on tests/test_mq_service.py
> +    Tests that owner_id in the system profile is rejected if it's in the wrong format
:facepalm:

2021-07-13 14:29 UTC, ryandillinfelton commented on app/validators.py
> +        r"^([A-Fa-f0-9]{2}[:-]){5}[A-Fa-f0-9]{2}$|"
It's the same regex I used in this [schema PR](https://github.com/RedHatInsights/inventory-schemas/pull/69). It's just a simple regex I created for all of the different MAC address formats, including the 20 byte infiniband ones.

2021-07-13 16:31 UTC, kruai approved these changes

2021-07-13 17:29 UTC, thearifismail approved these changes

2021-07-13 17:30 UTC, merged