Remove 'external_id'; replaced by provider_id
RedHatInsights/insights-host-inventory pull request #963
Opened 2021-07-26 16:00 UTC by thearifismail

# Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/ESSNTL-656).  

The host creators, like `puptoo`, `insights-client`, and `yupana` do not use "external_id".  Waiting for a response from @kahowell  because systems registered with `RHSM` can be hosted by cloud providers like AWS; so there is a potential of "external_id" in host being reported by "rhsm-conduit".

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-07-26 19:27 UTC, kruai approved these changes
Can't find any other references in the repo, and everything's passing. LGTM!

2021-08-02 15:02 UTC, ryandillinfelton submitted a review, later dismissed
LGTM. Out of curiousity, what would happen if a payload did contain `external_id` after we merge this change?

2021-08-03 13:40 UTC, thearifismail commented
> LGTM. Out of curiousity, what would happen if a payload did contain `external_id` after we merge this change?
Let me test it before merging it.

2021-08-03 18:40 UTC, thearifismail commented
> > LGTM. Out of curiousity, what would happen if a payload did contain `external_id` after we merge this change?
> > Let me test it before merging it.

It get ignored as unknown field.  It is verified by https://github.com/RedHatInsights/insights-host-inventory/blob/d6d383faa2f25e165786571ecd5285bd9774a72a/tests/test_unit.py#L1496

2021-08-03 19:25 UTC, ryandillinfelton requested changes
I appreciate the testing of how external_id is handled but I'm requesting you change the test you altered back. I explain more in the comment. Otherwise everything looks good and I'd be comfortable approving once the test is sorted out.

2021-08-03 19:25 UTC, ryandillinfelton commented on tests/test_unit.py
> +        input = {**canonical_facts, "external_id": str(uuid4())}
I'm assuming you edited this file to test out how external_id is handled when it's rejected. I don't think you should commit this change though as, while it does not change the core purpose of the test, it's an unnecessary change and hurts readability. I would be okay with adding another case to check external_id specifically, but I do think it would be basically redundant since this test, as it was, handled the general case of handling unknown fields.

2021-08-05 13:53 UTC, kruai commented on tests/test_unit.py
> +        input = {**canonical_facts, "external_id": str(uuid4())}
I'm not sure we need to add a test for this; the other tests (such as `test_unknown_fields_are_rejected`) already implicitly check this. I think it would be best if we just removed references to `external_id` entirely.
What do you think @ryandillinfelton ?

2021-08-05 14:27 UTC, ryandillinfelton commented on tests/test_unit.py
> +        input = {**canonical_facts, "external_id": str(uuid4())}
Yeah I agree. In my first comment I was pretty neutral on adding it, despite it's redundancy, but upon reflection I do think that the redundancy is worse because if one test needs to be updated down the line, now both will. I'd say just remove it.

2021-08-05 14:47 UTC, thearifismail commented on tests/test_unit.py
> +        input = {**canonical_facts, "external_id": str(uuid4())}
Removed!!!

2021-08-05 14:48 UTC, kruai submitted a review, later dismissed
I think this is ready!

2021-08-05 14:49 UTC, thearifismail commented on tests/test_unit.py
> +        input = {**canonical_facts, "external_id": str(uuid4())}
I guess I over-thought; just wanted to make sure in case questioned.

2021-08-05 14:50 UTC, ryandillinfelton approved these changes

2021-08-10 13:55 UTC, thearifismail commented
[retest]

2021-08-10 13:55 UTC, thearifismail commented
/retest

2021-08-10 14:15 UTC, kruai approved these changes

2021-08-10 14:15 UTC, ryandillinfelton approved these changes

2021-08-10 14:16 UTC, merged