Update per-reporter staleness schema to be more precise
RedHatInsights/insights-host-inventory pull request #986
Opened 2021-09-01 18:25 UTC by kruai

# Overview

This PR is being created to address [ESSNTL-1032](https://issues.redhat.com/browse/ESSNTL-1032).
It updates the API schema for the per-reporter staleness field to be more precise. Instead of just defining a general object, it specifies the dictionary structure along with the 3 fields in the "value" part of the key-value pair.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

2021-09-01 18:28 UTC, RonnyPfannschmidt requested changes

2021-09-01 18:28 UTC, RonnyPfannschmidt commented on swagger/api.spec.yaml
> +              additionalProperties:
additionalProperties is incorrect ,please use properties, and create a own schema entry to support the code genrator

2021-09-01 18:30 UTC, kruai commented on swagger/api.spec.yaml
> +              additionalProperties:
OK, I can make it work that way

2021-09-01 18:32 UTC, kruai commented on swagger/api.spec.yaml
> +              additionalProperties:
properties works differently from additionalProperties, though, right? I was using additionalProperties to make it a dictionary, key-value pair style

2021-09-02 12:49 UTC, thearifismail submitted a review, later dismissed
LGTM

2021-09-02 13:21 UTC, RonnyPfannschmidt commented on swagger/api.spec.yaml
> +              additionalProperties:
my mistake when reading, the levelling is correct, i wish there was a map type

2021-09-02 13:45 UTC, kruai commented on swagger/api.spec.yaml
> +              additionalProperties:
Same! Thanks for checking, though.

2021-09-14 17:16 UTC, ryandillinfelton commented on swagger/api.spec.yaml
> +        last_check_in:
Can you add an example value here, and for `stale_timestamp`

2021-09-14 18:12 UTC, kruai commented on swagger/api.spec.yaml
> +        last_check_in:
Done!

2021-09-14 19:07 UTC, ryandillinfelton approved these changes
Thank you!

2021-09-15 08:04 UTC, RonnyPfannschmidt approved these changes

2021-09-15 08:04 UTC, RonnyPfannschmidt commented on swagger/api.spec.yaml
> +        stale_timestamp:
an optional follow-up would be to make a shared item for datetime formats

2021-09-21 14:14 UTC, RonnyPfannschmidt approved these changes

2021-09-21 21:19 UTC, thearifismail reviewed
There should be a test using zero timezone, i.e. timestamp ending with "Z" e.g. 2020-02-13T12:08:55Z

2021-09-21 21:27 UTC, kruai commented
> There should be a test using zero timezone, i.e. timestamp ending with "Z" e.g. 2020-02-13T12:08:55Z

What kind of test do you mean? We don't have unit tests for the swagger doc. And we do have unit tests for datetime formats in my other PR: https://github.com/RedHatInsights/insights-host-inventory/pull/988

2021-09-21 21:34 UTC, thearifismail commented
> > There should be a test using zero timezone, i.e. timestamp ending with "Z" e.g. 2020-02-13T12:08:55Z
> 
> What kind of test do you mean? We don't have unit tests for the swagger doc. And we do have unit tests for datetime formats in my other PR: #988

Yes I was looking for using this format "2021-05-11T19:46:56.951+00:00Z" in `per_reporter_staleness`.  Since the format is being tested in PR #988, it should be good.

2021-09-21 21:34 UTC, thearifismail approved these changes

2021-09-22 13:06 UTC, merged