[WIP] Delete duplicate hosts
RedHatInsights/insights-host-inventory pull request #991
Opened 2021-09-12 20:58 UTC by thearifismail

# Overview

@kruai here is a PR attempting to delete duplicate hosts.  When deleting hosts, when deleting hosts elevated CFs are used in the order of their priority and then the regular CFs.  

Questions:  Is using Identity the correct approach? 

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-09-13 19:22 UTC, kruai requested changes
I have some questions and I'm a bit confused about the design patterns here. But this also definitely needs thorough tests to make sure we don't delete data that we're not supposed to delete

2021-09-13 19:22 UTC, kruai commented on lib/host_remove_duplicates.py
> +duplicate_list = []
Using these as static variables feels like a bit of a strange pattern to me. Was this based off of another job's implementation?

2021-09-13 19:22 UTC, kruai commented on lib/host_remove_duplicates.py
> +duplicate_list = []
I'm also concerned that `unique_list` would become enormous using this approach

2021-09-13 19:22 UTC, kruai commented on lib/host_remove_duplicates.py
> +            canonical_facts.pop("subscription_manager_id")
Can you explain why you're popping all but the highest-prio elevated ID? I'm a bit lost

2021-09-13 19:22 UTC, kruai commented on lib/host_remove_duplicates.py
> +            find_host_by_multiple_elevated_canonical_facts(elevated_facts, query, logger)
Definitely confusing to see this not return anything, and it's not clear that this "find" method is actually updating a static list defined at the top of the file. Why not instead define those 2 lists at the top of this function, and add/remove values based on the results of the function calls?

2021-09-13 19:58 UTC, thearifismail commented on host_delete_duplicates.py
> +    event_serialization_time,
They should've been removed.  Gone now.

2021-09-13 20:15 UTC, thearifismail commented on lib/host_remove_duplicates.py
> +    for fact in canonical_facts:
This function is called when there is no elevated canonical fact in the host.  To ensure that every canonical_fact(CF) is looked at, each fact is queried by the loop.  If there are > 1 hosts, only the first host is saved because the query results are provided with descending update time.  

The only possibility that this fact may be a duplicate is if it is in a host which also has an elevated canonical fact.

2021-09-13 20:19 UTC, thearifismail commented on lib/host_remove_duplicates.py
> +    delete_query = query.filter(Host.id == host["id"].hex)
The value of `host["id']` is an object of type `class 'uuid.UUID'`, which converted into a string by `.hex` and String is what is saved in DB

2021-09-13 20:22 UTC, thearifismail commented on lib/host_remove_duplicates.py
> +duplicate_list = []
Size of `unique_list` has been on my concern but at this time I want to get the logic right.  Since this job will be run only once and seldom after that, hopefully.  It may be okay.  We need to test the heck out before using it on the Prod cluster.

2021-09-13 20:26 UTC, thearifismail commented on lib/host_remove_duplicates.py
> +            canonical_facts.pop("subscription_manager_id")
Since highest priority CF takes precedence over others, the code checks for the highest CF. My understand is that same `insights_id` CF may be present in two different hosts with unique `provider_ids`, right? 

If there is no provider_id, then the host is checked for "insights_id", if there is no "insights_id" then the "subscription_manager_id" is used.

2021-09-13 20:30 UTC, thearifismail commented on lib/host_remove_duplicates.py
> +            find_host_by_multiple_elevated_canonical_facts(elevated_facts, query, logger)
I agree method and variable names should be changed for clarity, but for now I wanted to focus on logic to make sure that only the right hosts are deleted.

2021-09-14 15:00 UTC, kruai commented on lib/host_remove_duplicates.py
> +CANONICAL_FACTS = ("fqdn", "satellite_id", "bios_uuid", "ip_addresses", "mac_addresses")
True, though that's kind of an odd one since it goes hand-in-hand with `provider_id`. Because a host can only have both or neither of these fields, I think it makes sense to leave that out here

2021-09-14 15:20 UTC, kruai commented on lib/host_remove_duplicates.py
> +duplicate_list = []
Every time it runs, though, we can expect it to contain every host in the database at once (excluding duplicates). That might cause the pod to run out of memory in the worst case; a better case being that it just runs extremely slowly.
And I agree about the testing, but it doesn't look like you've added any tests to this yet

2021-09-14 15:20 UTC, kruai commented on lib/host_remove_duplicates.py
> +    for fact in canonical_facts:
Now that `trim_extra_facts` isn't being called, this is only searching for one canonical fact at a time, and adding the first entry to the list of unique hosts each time. This means that the FQDN on the host is `localhost`, this function could put any other host with with FQDN `localhost` in the list of unique hosts. I'm not sure what this function is trying to do makes sense

2021-09-14 15:20 UTC, kruai commented on lib/host_remove_duplicates.py
> +# The order is important, particularly the first 3 which are elevated facts with provider_id being the highest priority
Minor, but order is no longer important for `CANONICAL_FACTS`

2021-09-14 15:20 UTC, kruai commented on lib/host_remove_duplicates.py
> +            find_host_by_multiple_elevated_canonical_facts(elevated_facts, query, logger)
I understand wanting to focus on logic, it's just harder to review when a function does something other than what the name implies. I do still think it would be much easier to read if `unique_list` and `duplicate_list` were scoped to this function instead of being static vars; then each of these functions could return the host values that should be added to each list

2021-09-14 15:22 UTC, kruai requested changes
I'm going to have to review more in-depth again later, but I've requested some changes. We do need tests to go along with this to make sure your code is working as you intend

2021-09-15 18:38 UTC, ryandillinfelton commented on lib/host_remove_duplicates.py
> +CANONICAL_FACTS = ("fqdn", "satellite_id", "bios_uuid", "ip_addresses", "mac_addresses")
I know we talked about the possibility of provider_ids being the same, bur from different providers, but I'm pretty sure the ones we support right now all use different formats so I agree with Asa that we don't need to worry about the provider_type.

2021-09-15 18:41 UTC, ryandillinfelton commented on lib/host_remove_duplicates.py
> +    First check if multiple hosts are returned.  If they are then retain the with the highest
Obviously not gonna block on this. Real nit-picking hours.

```suggestion
    First check if multiple hosts are returned.  If they are then retain the one with the highest
```

2021-09-15 18:52 UTC, ryandillinfelton commented on utils/duplicate_remover_clowd_job_invocation.yaml
> +# Host synchronizer is run manually to synchronize host-invnenotry DB
This a copy-paste casualty?

2021-09-15 19:14 UTC, ryandillinfelton commented on lib/host_remove_duplicates.py
> +                hosts = find_host_by_elevated_canonical_facts(elevated_cfs, acct_query, logger)
Since in either case you only use the 0th entry in hosts why not have `find_host_by_elevated_canonical_facts` use `.first()` and return just one host value?

2021-09-15 19:19 UTC, ryandillinfelton commented on lib/host_remove_duplicates.py
> +        for host in host_list:
This can be done with a set operation. Just make sure the superset is on the left.
```suggestion
        duplicate_list = list(set(host_list) - set(unique_list))
```

2021-09-15 19:22 UTC, ryandillinfelton commented on lib/host_remove_duplicates.py
> +        for host in host_list:
Just realized you transform the elements of host_list before comparison. You could maybe do that with a map, but at that point I think it's just a little too much reworking, and too little simplifying. Especially for something that already works.

2021-09-15 19:39 UTC, ryandillinfelton requested changes
Let me know if I'm mistaken, but I think I found a bug that will prevent the script from de-duplicating any accounts with more hosts than the chunk size. Otherwise the logic is looking good. Just had some minor suggestions.

2021-09-15 19:39 UTC, ryandillinfelton commented on lib/host_remove_duplicates.py
> +        host_list = query.filter(Host.id > host_list[-1].id).limit(chunk_size).all()
I don't think you're processing any more than the first chunk of hosts with this approach. You set host_list to the next chunk, but you're in the for(accounts) loop, so the next time you hit the for(host_list) loop you'll have a different account number and the host list will have been redefined. I think you need some kind of `while there are still chunks` loop. Maybe check if the query returns the full chunk size, and if not you're at the end of the hosts.

2021-09-16 07:50 UTC, RonnyPfannschmidt commented on lib/host_remove_duplicates.py
> +        distinct_accounts.append(acct.account)
```suggestion
    distinct_accounts = [row.account for row in distinct_accounts_query.limit(chunk_size).all()]
  
```

2021-09-16 07:50 UTC, RonnyPfannschmidt commented on lib/host_remove_duplicates.py
> +        host_list = query.filter(Host.id > host_list[-1].id).limit(chunk_size).all()
this line doesnt work correct unless there is a extra lop level

2021-09-16 07:50 UTC, RonnyPfannschmidt commented on lib/host_remove_duplicates.py
> +        host_list = acct_query.limit(chunk_size).all()
use use https://docs.sqlalchemy.org/en/14/orm/query.html#sqlalchemy.orm.Query.yield_per here here and introduce a extra lloop level while at it to enable the processing of all host lists at once

2021-09-16 07:50 UTC, RonnyPfannschmidt commented on host_delete_duplicates.py
> +    events = delete_duplicate_hosts(query, config.script_chunk_size, logger, shutdown_handler.shut_down)
can we move the complete logging into the delete_duplicate_hosts and only return the update count here?

2021-09-16 07:50 UTC, RonnyPfannschmidt commented on lib/host_remove_duplicates.py
> +    return or_(*filter_)
i recal lthat this should do the job as well
```suggestion
    return or_(Host.canonical_facts.contains({key: value}) for key, value in canonical_facts.items())
```

2021-09-16 07:50 UTC, RonnyPfannschmidt commented on lib/host_remove_duplicates.py
> +            and_(Host.canonical_facts.has_key(key), not_(Host.canonical_facts.contains({key: value}))),  # noqa: W601
i do believe that a null-able lookup compared to a text would be more effective than the has_key and contains combination
i couldnt find the correct way to query this in my timebox

2021-09-16 07:50 UTC, RonnyPfannschmidt commented on lib/host_remove_duplicates.py
> +        while len(duplicate_list) > 0 and not interrupt():
just use the boolean check here

2021-09-16 07:50 UTC, RonnyPfannschmidt commented on lib/host_remove_duplicates.py
> +                _delete_host(query, host)
should there be Kafka delete events?
also why not use a singe query for the duplicate list

2021-09-16 09:21 UTC, fstavela commented on lib/host_remove_duplicates.py
> +CANONICAL_FACTS = ("fqdn", "satellite_id", "bios_uuid", "ip_addresses", "mac_addresses")
Ah yeah, that's true. Okay, then there is no need to add `provider_type` here.

2021-09-16 14:20 UTC, kruai commented on lib/host_remove_duplicates.py
> +            and_(Host.canonical_facts.has_key(key), not_(Host.canonical_facts.contains({key: value}))),  # noqa: W601
Resolving since this is low prio. But if you figure it out, please unresolve and let me know bc we'll want to use that in the function this is based on

2021-09-16 14:21 UTC, kruai commented on lib/host_remove_duplicates.py
> +        unique_list = []
Yep, we brought that up yesterday. I'll change it

2021-09-16 14:33 UTC, kruai commented on lib/host_remove_duplicates.py
> +        host_list = query.filter(Host.id > host_list[-1].id).limit(chunk_size).all()
Yeah, it doesn't look like the code in general does the chunking loop correctly

2021-09-16 14:49 UTC, kruai commented on lib/host_remove_duplicates.py
> +            find_host_by_multiple_elevated_canonical_facts(elevated_facts, query, logger)
Still an issue, but we've got bigger things to deal with. Resolving

2021-09-16 19:55 UTC, kruai commented on lib/host_remove_duplicates.py
> +                _delete_host(query, host)
Added kafka delete events, and updated how we query and delete

2021-09-17 07:59 UTC, RonnyPfannschmidt commented on lib/host_remove_duplicates.py
> +    hosts = multiple_canonical_facts_host_query(elevated_cfs, query).order_by(Host.modified_on.desc()).all()
based on the errors seen, i wonder if we can fetch them in groups - and we should use first instead

2021-09-17 12:33 UTC, kruai commented on lib/host_remove_duplicates.py
> +    hosts = multiple_canonical_facts_host_query(elevated_cfs, query).order_by(Host.modified_on.desc()).all()
@RonnyPfannschmidt I've gone back to using `all()`, and treating the first host returned as "unique" and the others as potential duplicates. What kind of groups do you mean we should fetch them in?

2021-09-17 14:46 UTC, ryandillinfelton approved these changes

2021-09-17 14:51 UTC, kruai approved these changes

2021-09-17 14:52 UTC, merged