Canonical facts uuids must be hyphenated to help control deduplication
RedHatInsights/insights-host-inventory pull request #993
Opened 2021-09-14 15:25 UTC by thearifismail

# Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/ESSNTL-616).  
Only the CanonicalFactsIn have been changed to control the UUID format during ingestion for better deduplication control.  The CanonicalFactsOut have been left the same to allow the existing hosts, with old relaxed format, still be be returned by host queries.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-09-14 16:15 UTC, kruai requested changes

2021-09-14 16:15 UTC, kruai commented on swagger/api.spec.yaml
> +      $ref: "#/components/schemas/HyphenatedUuid"
Why keep both `InsightsId` and `InsightsId_In`? `InsightsId` is only referenced inside `CanonicalFactsOut`.
This applies to all the other IDs, as well - I won't leave a bunch of duplicate comments.

2021-09-14 16:15 UTC, kruai commented on swagger/api.spec.yaml
> +      $ref: "#/components/schemas/HyphenatedUuid"
To be clear, I think it would be preferable to just modify the original ID schemas, e.g. `InsightsId`, `SubscriptionManagerId`, etc. Then, `CanonicalFactsOut` will already be using the updated definitions

2021-09-14 16:15 UTC, kruai commented on swagger/api.spec.yaml
> +            $ref: "#/components/schemas/BiosUuid_In"
Instead of removing `CanonicalFactsOut`, can you just delete the duplicate properties here? That would clean things up a bit

2021-09-14 16:15 UTC, kruai commented on tests/test_validators.py
> +    assert verify_uuid_format("4a8fb994-57fe-4dbb-ad2a-9e922560b6c1") is True
```suggestion
    assert verify_uuid_format("4a8fb994-57fe-4dbb-ad2a-9e922560b6c1")
```

2021-09-14 16:15 UTC, kruai commented on tests/test_unit.py
> +                "subscription_manager_id": uuid4().hex,  # uuid witout dashes not allowed for dedup control
why `.hex`? That's going to generate the hex value, which will be the incorrect length. You could just do something like `str(uuid4()).replace("-","")`. There might be a more elegant way to do that though

2021-09-24 18:38 UTC, kruai requested changes

2021-09-24 18:38 UTC, kruai commented on swagger/api.spec.yaml
> +    # values for the same canonical_fact.
I understand keeping that knowledge somewhere; I just don't think this is the right place for it. Comments explaining why the change is being made might make more sense in the description of a PR. If it's information you think we need to hold on to for later, it might make more sense in our docs.

2021-09-24 18:38 UTC, kruai commented on swagger/api.spec.yaml
> +      $ref: "#/components/schemas/HyphenatedUuid"
OK, that makes sense. I think a lot of it could still be refactored to remove most of that duplication, though. Something like this: https://github.com/RedHatInsights/insights-host-inventory/commit/a3eda9dc589d3c85f05f592a82dffee2e8c322ac

2021-09-27 15:39 UTC, thearifismail commented
Rebasing shows more files changed than the ones directly affected by this PR.  The files changed by this PR are:

1. app/validators.py
2. swagger/api.spec.yaml
3. tests/test_mq_service.py
4. tests/test_unit.py
5. tests/test_validators.py

2021-09-27 15:43 UTC, thearifismail commented
@kruai, the `api.spec.yaml has been refactored matching your suggestion.  Please take a look at it and if you approve these changes, please add a comment and put it `on-hold` because it needs to wait for https://issues.redhat.com/browse/ENT-4315.

@kahowell  FYI

2021-09-27 17:08 UTC, kruai approved these changes

2021-09-27 19:33 UTC, thearifismail commented
Remove the hold and merge this PR upon the implementation of [ENT-4315](https://issues.redhat.com/browse/ENT-4315) by the `rhsm-conduit` team.

2021-11-01 19:40 UTC, thearifismail commented
@ryandillinfelton can you please bless it?
@kruai can we merge it but not deploy it to stage and Prod until `rhsm-conduit` code is deployed to Prod.  The rhsm-conduit card is https://issues.redhat.com/browse/ENT-4315

2021-11-01 20:06 UTC, kruai commented
> @ryandillinfelton can you please bless it? @kruai can we merge it but not deploy it to stage and Prod until `rhsm-conduit` code is deployed to Prod. The rhsm-conduit card is https://issues.redhat.com/browse/ENT-4315

@thearifismail If we merge it, it will get deployed to Stage automatically. Prod is the only one we can reasonably hold off.

2021-11-02 11:27 UTC, thearifismail commented
> > @ryandillinfelton can you please bless it? @kruai can we merge it but not deploy it to stage and Prod until `rhsm-conduit` code is deployed to Prod. The rhsm-conduit card is https://issues.redhat.com/browse/ENT-4315
> 
> @thearifismail If we merge it, it will get deployed to Stage automatically. Prod is the only one we can reasonably hold off.

@kruai Let's merge it and hold off its deployment to prod.

2021-11-02 13:28 UTC, kruai commented on swagger/api.spec.yaml
> +      $ref: "#/components/schemas/HyphenatedUuid"
Thanks for making these changes, though I just realized that I left `InsightsId_In` in my refactoring, even though it's unused. Can you please remove it as well?

2021-11-02 13:30 UTC, kruai commented
> > > @ryandillinfelton can you please bless it? @kruai can we merge it but not deploy it to stage and Prod until `rhsm-conduit` code is deployed to Prod. The rhsm-conduit card is https://issues.redhat.com/browse/ENT-4315
> > 
> > 
> > @thearifismail If we merge it, it will get deployed to Stage automatically. Prod is the only one we can reasonably hold off.
> 
> @kruai Let's merge it and hold off its deployment to prod. Thanks to rebasing, the PR lost your approval. Can you please approve it? Thanks.

I'm fine with that. I just re-reviewed and I just want to request one tiny change (remove `InsightsId_In`). Thanks!

2021-11-02 15:01 UTC, thearifismail commented
> > > > @ryandillinfelton can you please bless it? @kruai can we merge it but not deploy it to stage and Prod until `rhsm-conduit` code is deployed to Prod. The rhsm-conduit card is https://issues.redhat.com/browse/ENT-4315
> > > 
> > > 
> > > @thearifismail If we merge it, it will get deployed to Stage automatically. Prod is the only one we can reasonably hold off.
> > 
> > 
> > @kruai Let's merge it and hold off its deployment to prod. Thanks to rebasing, the PR lost your approval. Can you please approve it? Thanks.
> 
> I'm fine with that. I just re-reviewed and I just want to request one tiny change (remove `InsightsId_In`). Thanks!

Removed!!!

2021-11-02 20:56 UTC, ryandillinfelton commented on app/validators.py
> +        return uuid.UUID(uuid_str) and "-" in uuid_str is not None
Not going to break anything since the check is still satisfied but you don't need `is not None`. `"-" in uuid_str` will return True if the character is in it.

2021-11-02 21:04 UTC, ryandillinfelton approved these changes
Looks good. Left an optional suggestion that I think improves the simplicity, but it's not a big deal.

2021-11-02 21:34 UTC, merged